### Convert generated opt output coordinates into spe input files of ligand and optimized complex

In [1]:
# Workflow
# Extract coordinates within opt file
# Convert into spe input file for M06/def2tzvp/Lanl2dz calculationfrom xyz2graph import MolGraph, to_networkx_graph, to_plotly_figure

In [2]:
# Install a pip package in the current Jupyter kernel
import sys
!{sys.executable} -m pip install git+https://github.com/zotko/xyz2graph.git
# python -m pip install git+https://github.com/zotko/xyz2graph.git

Collecting git+https://github.com/zotko/xyz2graph.git
  Cloning https://github.com/zotko/xyz2graph.git to c:\users\george\appdata\local\temp\pip-req-build-70lnqgu6
  Resolved https://github.com/zotko/xyz2graph.git to commit b11d841e60432225740620aca1582bcdc562f115
  Installing build dependencies: started
  Installing build dependencies: finished with status 'done'
  Getting requirements to build wheel: started
  Getting requirements to build wheel: finished with status 'done'
  Preparing metadata (pyproject.toml): started
  Preparing metadata (pyproject.toml): finished with status 'done'
Requirement already satisfied: networkx<3.4.0,>=3.1.0 in c:\users\george\.conda\envs\chem3\lib\site-packages (from xyz2graph==3.4.3.dev74+gb11d841e6) (3.3)
Requirement already satisfied: numpy<2.2.0,>=1.26.0 in c:\users\george\.conda\envs\chem3\lib\site-packages (from xyz2graph==3.4.3.dev74+gb11d841e6) (1.26.4)
Requirement already satisfied: plotly>=5.0.0 in c:\users\george\.conda\envs\chem3\lib\site-packages (from xyz2graph==3.4.3.dev74+gb11d841e6) (5.22.0)
Requirement already satisfied: tenacity>=6.2.0 in c:\users\george\.conda\envs\chem3\lib\site-packages (from plotly>=5.0.0->xyz2graph==3.4.3.dev74+gb11d841e6) (8.2.2)
Requirement already satisfied: packaging in c:\users\george\.conda\envs\chem3\lib\site-packages (from plotly>=5.0.0->xyz2graph==3.4.3.dev74+gb11d841e6) (23.2)

  Running command git clone --filter=blob:none --quiet https://github.com/zotko/xyz2graph.git 'C:\Users\George\AppData\Local\Temp\pip-req-build-70lnqgu6'

In [3]:
import os
from pathlib import Path
import re #Import RegEx
import os
import math
import numpy as np
import pandas as pd
from pathlib import Path
from plotly.offline import offline
import networkx as nx
from xyz2graph import MolGraph, to_networkx_graph, to_plotly_figure

In [6]:
directory = os.getcwd()
directory

'C:\\Users\\George\\Desktop\\Research_UCLA\\CIC\\Computational Work\\Project cluster version 2\\project_catalyst_repurposing\\structures_ligand_id'

In [5]:
# Check if all three files (opt, spe-complex and spe-ligand is present for each ligand)

opt_directory = directory + '\\pd_me2_structures\\opt'
spe_complex_directory = directory + '\\pd_me2_structures\\spe'
complex_xyz_directory = directory + '\\pd_me2_structures\\complex_xyz'
ligand_xyz_directory = directory + '\\pd_me2_structures\\ligand_xyz'
directory_list = [opt_directory, spe_complex_directory]
replace_list = ['-opt','-spe']

opt_list = []
spe_complex_list =[]
name_lists = [opt_list,spe_complex_list]

for check_directory,word,name_list in zip(directory_list,replace_list,name_lists):
# Read in .out file
    index_count = 0
#     name_list = []
    for subdir,dirs,files in os.walk(check_directory):                  # Loop over each directory, subdirectory and files
        for file in files:                                      # Loop over each file
            if any([file.endswith('.out')]):                    # If file is a .out file
                filename = os.path.join(subdir, file)       # Return path to file
                name = Path(filename).stem           # Extract filename from the end of path and return as a string
                name = name.replace(word,'')     #Remove -opt in string to get just the name of ligand 'pd-x-x-x'
                name_list.append(name)
                
                
print('Number of files in opt: ', len(opt_list))
print('Number of files in spe: ', len(spe_complex_list))
missing_in_opt_list = np.unique([x for x in spe_complex_list if x not in opt_list])
missing_in_spe_complex_list = np.unique([x for x in opt_list if x not in spe_complex_list])


print('Missing in opt list: ', missing_in_opt_list)
print('Missing in spe complex list: ',missing_in_spe_complex_list)

missing_list = []
missing_list.extend(missing_in_opt_list)
missing_list.extend(missing_in_spe_complex_list)
print(missing_list)

# with open("missing_list.txt", "w") as output:
#     output.write(str(missing_list))

Number of files in opt:  490
Number of files in spe:  490
Missing in opt list:  []
Missing in spe complex list:  []
[]

In [7]:
#Define functions

def get_h_atoms(cart_distances):
    sorted_indices = sorted(range(len(cart_distances)), key=lambda i: cart_distances[i])
    second_smallest_index = sorted_indices[1]
    third_smallest_index = sorted_indices[2]
    fourth_smallest_index = sorted_indices[3]
    fifth_smallest_index = sorted_indices[4] 
    return second_smallest_index, third_smallest_index, fourth_smallest_index, fifth_smallest_index

def get_donor_atoms(cart_distances, element_list):
    # Sort the indices based on cartesian distances
    sorted_indices = sorted(range(len(cart_distances)), key=lambda i: cart_distances[i])
    
    # Filter out indices where the corresponding element is 'H'
    filtered_indices = [i for i in sorted_indices if element_list[i] != 'H']

    second_smallest_index = filtered_indices[1]
    third_smallest_index = filtered_indices[2]
    fourth_smallest_index = filtered_indices[3]
    fifth_smallest_index = filtered_indices[4]
    
    return second_smallest_index, third_smallest_index, fourth_smallest_index, fifth_smallest_index

def get_neighbor_atoms(numbers):
    sorted_indices = sorted(range(len(numbers)), key=lambda i: numbers[i]) 
    return sorted_indices


def xyz_to_dataframe(filename):
    with open(filename, 'r') as file:
        lines = file.readlines()
        
    # Initialize lists to store data
    atoms = []
    x_coords = []
    y_coords = []
    z_coords = []
    
    # Parse the lines and extract coordinates
    for line in lines:
        parts = line.split()
        atoms.append(parts[0])
        x_coords.append(float(parts[1]))
        y_coords.append(float(parts[2]))
        z_coords.append(float(parts[3]))

    # Create a pandas DataFrame
    data = {
        'Atom': atoms,
        'X': x_coords,
        'Y': y_coords,
        'Z': z_coords
    }

    xyz_df = pd.DataFrame(data)    
    return(xyz_df)

# def generate_ligand_spe(atoms_to_remove,ligand_name):


# Define element dictionary once, globally
element_dict = {
    "1": "H",   "2": "He",  "3": "Li",  "4": "Be",  "5": "B",
    "6": "C",   "7": "N",   "8": "O",   "9": "F",   "10": "Ne",
    "11": "Na", "12": "Mg", "13": "Al", "14": "Si", "15": "P",
    "16": "S",  "17": "Cl", "18": "Ar", "19": "K",  "20": "Ca",
    "21": "Sc", "22": "Ti", "23": "V",  "24": "Cr", "25": "Mn",
    "26": "Fe", "27": "Co", "28": "Ni", "29": "Cu", "30": "Zn",
    "31": "Ga", "32": "Ge", "33": "As", "34": "Se", "35": "Br",
    "36": "Kr", "37": "Rb", "38": "Sr", "39": "Y",  "40": "Zr",
    "41": "Nb", "42": "Mo", "43": "Tc", "44": "Ru", "45": "Rh",
    "46": "Pd", "47": "Ag", "48": "Cd", "49": "In", "50": "Sn",
    "51": "Sb", "52": "Te", "53": "I",  "54": "Xe", "55": "Cs",
    "56": "Ba", "57": "La", "58": "Ce", "59": "Pr", "60": "Nd",
    "61": "Pm", "62": "Sm", "63": "Eu", "64": "Gd", "65": "Tb",
    "66": "Dy", "67": "Ho", "68": "Er", "69": "Tm", "70": "Yb",
    "71": "Lu", "72": "Hf", "73": "Ta", "74": "W",  "75": "Re",
    "76": "Os", "77": "Ir", "78": "Pt", "79": "Au", "80": "Hg",
    "81": "Tl", "82": "Pb", "83": "Bi", "84": "Po", "85": "At",
    "86": "Rn", "87": "Fr", "88": "Ra", "89": "Ac", "90": "Th",
    "91": "Pa", "92": "U",  "93": "Np", "94": "Pu", "95": "Am",
    "96": "Cm", "97": "Bk", "98": "Cf", "99": "Es", "100": "Fm",
    "101": "Md","102": "No", "103": "Lr","104": "Rf","105": "Db",
    "106": "Sg","107": "Bh", "108": "Hs","109": "Mt","110": "Ds",
    "111": "Rg","112": "Cn","113": "Nh","114": "Fl","115": "Mc",
    "116": "Lv","117": "Ts","118": "Og"
}

### Obtain XYZ coordinates, obtain metal and  ligand atom labels from -opt.out files.
### Ligand atom labels for each bond distance away from the metal center is also obtained. 
### Skip this code to only generate spe.com files from opt.out files

In [8]:
xyz_match = ['X           Y           Z']
nbo_match = ['Natural Population Analysis']
unique_atom_list = []
ligand_atom_pair_list = []
missing_nbo_calc = []

# Intialize list to store atom labels
names = []
pd_atoms = []
methyl_atom_1 = []
methyl_atom_2 = []
hydrogens_methyl_1 = []
hydrogens_methyl_2 = []
ligand_atom_1 = []
ligand_atom_2 = []
atom_distance_lists_2 = []
atom_distance_lists_3 = []
atom_distance_lists_4 = []
atom_distance_lists_2_a = []
atom_distance_lists_3_a = []
atom_distance_lists_4_a = []
atom_distance_lists_2_b = []
atom_distance_lists_3_b = []
atom_distance_lists_4_b = []
shortest_path_atom_label_lists = []

for subdir,dirs,files in os.walk(opt_directory):                  # Loop over each directory, subdirectory and files
    for file in files:                                      # Loop over each file
        if any([file.endswith('-opt.out')]):                    # If file is a .out file
            filename = os.path.join(subdir, file)       # Return path to file
            name = Path(filename).stem.replace('-opt',"")         # Extract filename from the end of path and return as a string
            print(name)
        
            mylines = []
            with open (filename, 'rt') as myfile:       # Open .out for reading text
                # myfile = myfile.read()                # Read the entire file to a string
                for myline in myfile:                    # For each line, stored as myline,
                    mylines.append(myline)               # add its contents to mylines list.
                    
#                 # Find XYZ Coordinates
                for line in mylines:
                    if 'NAtoms=' in line:
                        number_list = re.findall('-?\d*\.?\d+',line)            # get NAtoms value
                        natoms = int(number_list[0])
#                         print(natoms)                
                
                xyz_count = 0
                for line in mylines:
                    for phrase in xyz_match:                                # iterate through each phrases
                        if phrase in line:                                          # check if phrase is in line
                            xyz_count = xyz_count + 1
                
                line_count = 0
                for line in mylines:
                    line_count = line_count + 1
                    for phrase in xyz_match:                                # iterate through each phrases
                        if phrase in line:                                          # check if phrase is in line
                            xyz_count = xyz_count - 1
                            if xyz_count > 0:
                                continue
                            elif xyz_count == 0:
                                
                                                                               # For loop for generating the XYZ coordinates
                                count = 0
                                xyz = []
                                while count < natoms:
                                    count = count + 1
                                    xyz.append(mylines[line_count + 1])
                                    line_count = line_count +1

                x_coord = []
                y_coord = []
                z_coord = []
                atom_symbol =[]
                
                # Generate XYZ file in .txt form, then find xyz coordinates for metal, atom_a and atom_b
                for line in xyz:
                    number_list = re.findall('-?\d*\.?\d+',line)
                    atom_number = int(number_list[0])
                    element_number = int(number_list[1])
                    atom_x = float(number_list[3])
                    atom_x = f"{atom_x:.6f}"
                    atom_y = float(number_list[4])
                    atom_y = f"{atom_y:.6f}"
                    atom_z = float(number_list[5])
                    atom_z = f"{atom_z:.6f}"
                
                    # Make xyz coord into .txt file 
                    x_coord.append(atom_x)
                    y_coord.append(atom_y)
                    z_coord.append(atom_z)
                    atom_symbol.append(element_dict[str(element_number)])
                    unique_atoms = list(set(atom_symbol))
                    name_xyz = name + '-complex_xyz.txt'            
                    
                data = {
                    'Atom': atom_symbol,
                    'X': x_coord,
                    'Y': y_coord,
                    'Z': z_coord
                }

                xyz_df = pd.DataFrame(data)

                # Check if output directory for complex xyz exist, create if it doesn't
                os.makedirs(complex_xyz_directory, exist_ok=True)

                # Combine the directory and filename to create the full file path
                complex_xyz_file_path = os.path.join(complex_xyz_directory, name_xyz)

                
#               xyz_df.to_csv(name_xyz, header=False, index=False, sep = " ")          # Generates .txt file                
                new_row = pd.DataFrame({'Atom':'filler', 'X':'', 'Y':'', 'Z':''}, index=[0])
                xyz_df_txt = pd.concat([new_row,xyz_df.loc[:]]).reset_index(drop=True) 
                new_row_2 = pd.DataFrame({'Atom':natoms, 'X':'', 'Y':'', 'Z':''}, index=[0])
                xyz_df_txt = pd.concat([new_row_2,xyz_df_txt.loc[:]]).reset_index(drop=True)

                # Save complex_xyz as text file in the complex_xyz directory            
                xyz_df_txt.to_csv(complex_xyz_file_path, header=False, index=False, sep = " ")          # Generates .txt file   

                                
                # Identify ligand atoms from xyz_df
                condition = (xyz_df['Atom'] == 'Pd')
                pd_row = xyz_df[condition].iloc[0]
                pd_atom = xyz_df[condition].index[0]
                print('Pd number index: ', pd_atom)


                pd_x = pd_row['X']
                pd_y = pd_row['Y']
                pd_z = pd_row['Z']

                #     print(pd_x,pd_y,pd_z)

                cart_distance_pd_list = []
                element_list = []
                for index, row in xyz_df.iterrows():           #Obtain difference between Pd(x,y,z) coordinates and the rest of the atom's cartesian coordinates

                    x_diff = float(pd_x) - float(row['X'])
                    y_diff = float(pd_y) - float(row['Y'])
                    z_diff = float(pd_z) - float(row['Z'])
                    element = row['Atom']
                    
                    cart_distance_pd = np.sqrt(x_diff**2 + y_diff**2 + z_diff**2)

                    cart_distance_pd_list.append(cart_distance_pd)
                    element_list.append(element)
                print(element_list)

                donor_atom_1, donor_atom_2, donor_atom_3, donor_atom_4 = get_donor_atoms(cart_distance_pd_list,element_list)   #Get atoms coordinated to Pd
                
                # pd_row = xyz_df[condition].iloc[0]    

                donor_atoms = [donor_atom_1, donor_atom_2, donor_atom_3, donor_atom_4]   # List of atom indices that is bonded to Pd

                new_donor_atoms = []

                for donor_atom in donor_atoms:
            #         print('Atom index closest to Pd: ', donor_atom)
                    atom_name = xyz_df.iloc[donor_atom,0]
                    if atom_name == 'C':
                        new_donor_atoms.append(donor_atom)   #Obtain index with carbon atom only

                donor_atom_df = xyz_df.loc[new_donor_atoms]

                #Identifying methyl groups attached on Pd
                methyl_atoms = []
                hydrogen_atoms = []
                hydrogen_indices = []

                for donor_atom in new_donor_atoms:    #iterate through the index of each carbon donor atom

                    c_x = xyz_df.iloc[donor_atom,1]   #obtain x y z coordinates for each carbon donor atom
                    c_y = xyz_df.iloc[donor_atom,2]
                    c_z = xyz_df.iloc[donor_atom,3]

                    cart_distance_c_list = []
                    for index, row in xyz_df.iterrows():
                        x_diff = float(c_x) - float(row['X'])
                        y_diff = float(c_y) - float(row['Y'])
                        z_diff = float(c_z) - float(row['Z'])            

                        cart_distance_c = np.sqrt(x_diff**2 + y_diff**2 + z_diff**2)
                        cart_distance_c_list.append(cart_distance_c)

                    h_atom_1, h_atom_2, h_atom_3, h_atom_4 = get_h_atoms(cart_distance_c_list)

                    h_atoms = [h_atom_1, h_atom_2, h_atom_3, h_atom_4]
            #         print(donor_atom, h_atoms)

                    new_h_atoms = []
                    new_h_indices = []

                    for h_atom in h_atoms:
                        atom_name = xyz_df.iloc[h_atom,0]
                        if atom_name == 'H':
                            h_index = h_atom
                            new_h_indices.append(h_index)
                            h_atom = h_atom + 1
                            new_h_atoms.append(h_atom)

            #         print('Index of donor atom: ', donor_atom, 'Number of Hs: ', len(new_h_atoms)) 

                    if len(new_h_atoms) == 3:
                        methyl_atoms.append(donor_atom)
                        hydrogen_atoms.append(new_h_atoms)
                        hydrogen_indices.append(new_h_indices)


            #     print('Methyl atom indices: ', methyl_atoms)
            #     print('Hydrogen atom indices: ', hydrogen_atoms)

                ligand_atoms_label = []
                new_ligand_atoms_label = []
                ligand_atoms_indicies = []


                ligand_atoms_indicies = [x for x in donor_atoms if x not in methyl_atoms] # Remove atom label to only obtain indices related to ligand atom
                for atom in ligand_atoms_indicies:
                    ligand_atoms_label.append(atom + 1)
                # print('Ligand atom label list: ', ligand_atoms_label)
                ligand_atom_pair_list.append(ligand_atoms_label)
#--------------------------------------------------------------------------------------------------------------------------  

#### Identify ligand atoms based on nbo charge calculated in opt file

                for phrase in nbo_match:                                       # iterate through each phrases
                    nbo_match_count = 0
                    for line in mylines:
                        if phrase in line:                                          # check if phrase is in line
                            nbo_match_count = nbo_match_count + 1
                            count = 0
                            nbo_xyz = []
                            line_number = mylines.index(line) + 6
                            while count < natoms:
                                count = count + 1
                                nbo_xyz.append(mylines[line_number])
                                line_number = line_number + 1

                            with open('nbo.txt', 'w') as filehandle:                   # Save nbo_xyz  into a txt file
                                for listitem in nbo_xyz:
                                    filehandle.write(listitem)

                # Extract NBO charge for metal, atom A and atom B, atom at distance 2,3,4
                if nbo_match_count == 0:
                    print('No NBO Charge calculation for ', name)
                    missing_nbo_calc.append(name)
                    continue


                elif nbo_match_count > 0:    
                    for line in nbo_xyz:
                        number_list = re.findall('-?\d*\.?\d+',line)
                        atom_number = int(number_list[0])

                        if atom_number == ligand_atoms_label[0]:
                            a_nbo = float(number_list[1])
                            print('Ligand atom label: ', atom_number,
                                  ' Ligand atom A nbo: ', a_nbo)

                        elif atom_number == ligand_atoms_label[1]:
                            b_nbo = float(number_list[1]) 
                            print('Ligand atom label: ', atom_number,
                                  ' Ligand atom B nbo: ', b_nbo)                
                
                
                if a_nbo >= b_nbo:
                    new_ligand_atom_a = ligand_atoms_label[0]
                    new_ligand_atom_b = ligand_atoms_label[1]
                elif a_nbo < b_nbo:
                    new_ligand_atom_a = ligand_atoms_label[1]
                    new_ligand_atom_b = ligand_atoms_label[0]
                
                new_ligand_atoms_label.append(new_ligand_atom_a)
                new_ligand_atoms_label.append(new_ligand_atom_b)
                
                print('Atom_a: ', new_ligand_atom_a, 'Atom_b: ', new_ligand_atom_b)
              
                
#--------------------------------------------------------------------------------------------------------------------------                

                    
                #Obtain xyz coordinates for donor atoms
        
                ligand_atom_1_row = xyz_df.loc[new_ligand_atoms_label[0]-1]
                ligand_atom_2_row = xyz_df.loc[new_ligand_atoms_label[1]-1]
                # print('Ligand number index: ', ligand_atom_1_row)

                ligand_atom_1_x = ligand_atom_1_row['X']
                ligand_atom_1_y = ligand_atom_1_row['Y']
                ligand_atom_1_z = ligand_atom_1_row['Z']
                # print('Atom_a_x: ',ligand_atom_1_x)
                # print('Atom_a_y: ',ligand_atom_1_y)                
                # print('Atom_a_z: ',ligand_atom_1_z)                
                
                ligand_atom_2_x = ligand_atom_2_row['X']
                ligand_atom_2_y = ligand_atom_2_row['Y']
                ligand_atom_2_z = ligand_atom_2_row['Z'] 
                # print('Atom_b_x: ',ligand_atom_2_x)
                # print('Atom_b_y: ',ligand_atom_2_y)                
                # print('Atom_b_z: ',ligand_atom_2_z)   
                
                
                #Find atoms at distance 2 (connected to donor atoms)
                
                atom_distance_2 = []
                atom_distance_2_with_a = []
                atom_distance_2_with_b = []
                
                
                for index, row in xyz_df.iterrows():

                    ligand_1_x_diff = float(ligand_atom_1_x) - float(row['X'])
                    ligand_1_y_diff = float(ligand_atom_1_y) - float(row['Y'])
                    ligand_1_z_diff = float(ligand_atom_1_z) - float(row['Z'])

                    ligand_2_x_diff = float(ligand_atom_2_x) - float(row['X'])
                    ligand_2_y_diff = float(ligand_atom_2_y) - float(row['Y'])
                    ligand_2_z_diff = float(ligand_atom_2_z) - float(row['Z'])


                    cart_distance_ligand_1 = np.sqrt(ligand_1_x_diff**2 + ligand_1_y_diff**2 + ligand_1_z_diff**2)
                    if 0.1 < cart_distance_ligand_1 < 1.93 and index != pd_atom:
                        atom_distance_2.append(index+1)
                        atom_distance_2_with_a.append(index+1)


                    cart_distance_ligand_2 = np.sqrt(ligand_2_x_diff**2 + ligand_2_y_diff**2 + ligand_2_z_diff**2)
                    if 0.1 < cart_distance_ligand_2 < 1.93 and index != pd_atom:
                        atom_distance_2.append(index+1)    
                        atom_distance_2_with_b.append(index+1)

                    # Remove duplicates
                atom_distance_2 = list(set(atom_distance_2))
                # print('Atoms at distance 2: ', atom_distance_2)
                # print('Atoms connected to atom a: ',atom_distance_2_with_a)
                # print('Atoms connected to atom b: ',atom_distance_2_with_b)


                # Find atoms at atom distance 3
                atoms_to_avoid_3 = []
                atoms_to_avoid_3_with_a = []
                atoms_to_avoid_3_with_b = []
                
                atom_distance_3 = []
                atom_distance_3_with_a = []
                atom_distance_3_with_b = []

                atoms_to_avoid_3.extend(atom_distance_2)
                atoms_to_avoid_3.append(pd_atom+1)
                atoms_to_avoid_3.append(new_ligand_atoms_label[0])
                atoms_to_avoid_3.append(new_ligand_atoms_label[1])
                
                atoms_to_avoid_3_with_a.append(pd_atom+1)
                atoms_to_avoid_3_with_a.append(new_ligand_atoms_label[0])
                atoms_to_avoid_3_with_a.append(new_ligand_atoms_label[1])
                atoms_to_avoid_3_with_a.extend(atom_distance_2_with_a)
                
                atoms_to_avoid_3_with_b.append(pd_atom+1)
                atoms_to_avoid_3_with_b.append(new_ligand_atoms_label[0])
                atoms_to_avoid_3_with_b.append(new_ligand_atoms_label[1])
                atoms_to_avoid_3_with_b.extend(atom_distance_2_with_b)
                            
                
                # print('Atoms to avoid at distance 3: ',atoms_to_avoid_3)
                # print('Atoms to avoid at distance 3 with a: ',atoms_to_avoid_3_with_a)
                # print('Atoms to avoid at distance 3 with b: ',atoms_to_avoid_3_with_b)
                
                for atom in atom_distance_2:
                    atom_row = xyz_df.loc[atom-1]

                    atom_x = atom_row['X']
                    atom_y = atom_row['Y']
                    atom_z = atom_row['Z']

                    for index, row in xyz_df.iterrows():
                        atom_distance_diff_x = float(atom_x) - float(row['X'])
                        atom_distance_diff_y = float(atom_y) - float(row['Y'])
                        atom_distance_diff_z = float(atom_z) - float(row['Z'])

                        cart_distance_atom = np.sqrt(atom_distance_diff_x**2 + atom_distance_diff_y**2 + atom_distance_diff_z**2)
                        if 0.1 < cart_distance_atom < 1.93:
                            atom_distance_3.append(index+1)     
                
                for atom in atom_distance_2_with_a:
                    atom_row = xyz_df.loc[atom-1]

                    atom_x = atom_row['X']
                    atom_y = atom_row['Y']
                    atom_z = atom_row['Z']

                    for index, row in xyz_df.iterrows():
                        atom_distance_diff_x = float(atom_x) - float(row['X'])
                        atom_distance_diff_y = float(atom_y) - float(row['Y'])
                        atom_distance_diff_z = float(atom_z) - float(row['Z'])

                        cart_distance_atom = np.sqrt(atom_distance_diff_x**2 + atom_distance_diff_y**2 + atom_distance_diff_z**2)
                        if 0.1 < cart_distance_atom < 1.93:
                            atom_distance_3_with_a.append(index+1)      
                
                for atom in atom_distance_2_with_b:
                    atom_row = xyz_df.loc[atom-1]

                    atom_x = atom_row['X']
                    atom_y = atom_row['Y']
                    atom_z = atom_row['Z']

                    for index, row in xyz_df.iterrows():
                        atom_distance_diff_x = float(atom_x) - float(row['X'])
                        atom_distance_diff_y = float(atom_y) - float(row['Y'])
                        atom_distance_diff_z = float(atom_z) - float(row['Z'])

                        cart_distance_atom = np.sqrt(atom_distance_diff_x**2 + atom_distance_diff_y**2 + atom_distance_diff_z**2)
                        if 0.1 < cart_distance_atom < 1.93:
                            atom_distance_3_with_b.append(index+1)      
                

                #Remove duplicates
                atom_distance_3 = list(set(atom_distance_3))
                atom_distance_3 = [x for x in atom_distance_3 if x not in atoms_to_avoid_3]
                # print('Atoms at distance 3: ', atom_distance_3)

                atom_distance_3_with_a = list(set(atom_distance_3_with_a))
                atom_distance_3_with_a = [x for x in atom_distance_3_with_a if x not in atoms_to_avoid_3_with_a]
                # print('Atoms at distance 3 from donor atom A: ', atom_distance_3_with_a)

                atom_distance_3_with_b = list(set(atom_distance_3_with_b))
                # print('Atom 3, b: ', atom_distance_3_with_b)
                atom_distance_3_with_b = [x for x in atom_distance_3_with_b if x not in atoms_to_avoid_3_with_b]
                # print('Atoms at distance 3 from donor atom B: ', atom_distance_3_with_b)
                                    
                #Find atom at distance 4

                atom_distance_4 = []
                atoms_to_avoid_4 = []
                atom_distance_4_with_a = []
                atoms_to_avoid_4_with_a = []
                atom_distance_4_with_b = []
                atoms_to_avoid_4_with_b = []  
                
                atoms_to_avoid_4 = atoms_to_avoid_3
                atoms_to_avoid_4.extend(atom_distance_3)
                
                atoms_to_avoid_4_with_a = atoms_to_avoid_3_with_a
                atoms_to_avoid_4_with_a.extend(atom_distance_3_with_a)
                
                atoms_to_avoid_4_with_b = atoms_to_avoid_3_with_b
                atoms_to_avoid_4_with_b.extend(atom_distance_3_with_b)                
                
                           
                # print('Atoms to avoid at distance 4: ',atoms_to_avoid_4)
                # print('Atoms to avoid at distance 4 from a: ',atoms_to_avoid_4_with_a)
                # print('Atoms to avoid at distance 4 from b: ',atoms_to_avoid_4_with_b)
                
                for atom in atom_distance_3:
                    atom_row = xyz_df.loc[atom-1]

                    atom_x = atom_row['X']
                    atom_y = atom_row['Y']
                    atom_z = atom_row['Z']

                    for index, row in xyz_df.iterrows():
                        atom_distance_diff_x = float(atom_x) - float(row['X'])
                        atom_distance_diff_y = float(atom_y) - float(row['Y'])
                        atom_distance_diff_z = float(atom_z) - float(row['Z'])

                        cart_distance_atom = np.sqrt(atom_distance_diff_x**2 + atom_distance_diff_y**2 + atom_distance_diff_z**2)
                        if 0.1 < cart_distance_atom < 1.93:
                            atom_distance_4.append(index+1)     
                            
                for atom in atom_distance_3_with_a:
                    atom_row = xyz_df.loc[atom-1]

                    atom_x = atom_row['X']
                    atom_y = atom_row['Y']
                    atom_z = atom_row['Z']

                    for index, row in xyz_df.iterrows():
                        atom_distance_diff_x = float(atom_x) - float(row['X'])
                        atom_distance_diff_y = float(atom_y) - float(row['Y'])
                        atom_distance_diff_z = float(atom_z) - float(row['Z'])

                        cart_distance_atom = np.sqrt(atom_distance_diff_x**2 + atom_distance_diff_y**2 + atom_distance_diff_z**2)
                        if 0.1 < cart_distance_atom < 1.93:
                            atom_distance_4_with_a.append(index+1)                                 
                            
                for atom in atom_distance_3_with_b:
                    atom_row = xyz_df.loc[atom-1]

                    atom_x = atom_row['X']
                    atom_y = atom_row['Y']
                    atom_z = atom_row['Z']

                    for index, row in xyz_df.iterrows():
                        atom_distance_diff_x = float(atom_x) - float(row['X'])
                        atom_distance_diff_y = float(atom_y) - float(row['Y'])
                        atom_distance_diff_z = float(atom_z) - float(row['Z'])

                        cart_distance_atom = np.sqrt(atom_distance_diff_x**2 + atom_distance_diff_y**2 + atom_distance_diff_z**2)
                        if 0.1 < cart_distance_atom < 1.93:
                            atom_distance_4_with_b.append(index+1)                                             
                            
                
                #Remove duplicates
                atom_distance_4 = list(set(atom_distance_4))
                atom_distance_4 = [x for x in atom_distance_4 if x not in atoms_to_avoid_4]
                # print('Atoms at distance 4: ', atom_distance_4)

                atom_distance_4_with_a = list(set(atom_distance_4_with_a))
                atom_distance_4_with_a = [x for x in atom_distance_4_with_a if x not in atoms_to_avoid_4_with_a]
                # print('Atoms at distance 4 from A: ', atom_distance_4_with_a)
                
                atom_distance_4_with_b = list(set(atom_distance_4_with_b))
                atom_distance_4_with_b = [x for x in atom_distance_4_with_b if x not in atoms_to_avoid_4_with_b]
                # print('Atoms at distance 4 from B: ', atom_distance_4_with_b)
               
                              
                # Add 1 to every index to fit label naming
                names.append(name)
                methyl_atom_1.append(methyl_atoms[0]+1)
                methyl_atom_2.append(methyl_atoms[1]+1)
                hydrogens_methyl_1.append(hydrogen_atoms[0])
                hydrogens_methyl_2.append(hydrogen_atoms[1])
                ligand_atom_1.append(new_ligand_atoms_label[0])
                ligand_atom_2.append(new_ligand_atoms_label[1])
                pd_atoms.append(pd_atom+1)
                atom_distance_lists_2.append(atom_distance_2)
                atom_distance_lists_3.append(atom_distance_3)
                atom_distance_lists_4.append(atom_distance_4)
                atom_distance_lists_2_a.append(atom_distance_2_with_a)
                atom_distance_lists_3_a.append(atom_distance_3_with_a)
                atom_distance_lists_4_a.append(atom_distance_4_with_a)
                atom_distance_lists_2_b.append(atom_distance_2_with_b)                
                atom_distance_lists_3_b.append(atom_distance_3_with_b)                   
                atom_distance_lists_4_b.append(atom_distance_4_with_b)                   

                # Generate ligand_spe file by removing palladium and the two methyl atoms
                atoms_to_remove = methyl_atoms + hydrogen_indices[0] + hydrogen_indices[1]
                atoms_to_remove.append(pd_atom)
                # print('atoms_to_remove',atoms_to_remove)
                ligand_xyz_df = xyz_df.drop(atoms_to_remove,axis =0)
                # new_row = pd.DataFrame({'Atom':'filler', 'X':'filler', 'Y':'filler', 'Z':'filler'}, index=[0])
                # ligand_xyz_df = pd.concat([new_row,ligand_xyz_df.loc[:]]).reset_index(drop=True) 
                #Add first line with number of atoms extra filler line to fit format for graph generation
                natoms_ligand = ligand_xyz_df.shape[0]
                new_row = pd.DataFrame({'Atom':'filler', 'X':'filler', 'Y':'filler', 'Z':'filler'}, index=[0])
                ligand_xyz_df = pd.concat([new_row,ligand_xyz_df.loc[:]]).reset_index(drop=True) 
                new_row_2 = pd.DataFrame({'Atom':natoms_ligand, 'X':'', 'Y':'', 'Z':''}, index=[0])
                ligand_xyz_df = pd.concat([new_row_2,ligand_xyz_df.loc[:]]).reset_index(drop=True)
                ligand_xyz_filename = name+'-ligand_xyz.txt'

                # Ensure the output directory exists, create it if it doesn't
                os.makedirs(ligand_xyz_directory, exist_ok=True)

                # Combine the directory and filename to create the full file path
                ligand_xyz_file_path = os.path.join(ligand_xyz_directory, ligand_xyz_filename)
                print(ligand_xyz_file_path)

                # Save as text file in the ligand_xyz directory
                ligand_xyz_df.to_csv(ligand_xyz_file_path, header=False,index=False,sep=" ")

                #Use ligand_xyz_df to generate a graph to find the atoms for calculating internal angle
                # Using Graph network
                # Identify nodes with xyz coordinates as ID
                # Use removed PdMe2 structure to construct graph
                #Identify atom A and atom B nodes with their xyz coordinates
                # identify shortest path from A --> 
                # store the xyz atoms for these atoms, convert to atom label in the complex from by matching
                # do this code separately to the csv data generator and add into dataframe
                from plotly.offline import offline
                import networkx as nx
                from xyz2graph import MolGraph, to_networkx_graph, to_plotly_figure
                # Create the MolGraph object
                mg = MolGraph()

                # # Read the data from the .xyz file in the directory
                # mg.read_xyz(name+'-ligand_xyz.txt')

                # Read the data from the .xyz file in the directory
                mg.read_xyz(ligand_xyz_file_path)

                # Create the Plotly figure object
                fig = to_plotly_figure(mg)

                # Plot the figure
                # offline.plot(fig)

                # Convert the molecular graph to the NetworkX graph
                G = to_networkx_graph(mg)
                #Set donor atom xyz coordinates for matching
                
                atom_a_x = float(ligand_atom_1_x)
                atom_a_y = float(ligand_atom_1_y)
                atom_a_z = float(ligand_atom_1_z)
                atom_a_xyz = (atom_a_x,atom_a_y,atom_a_z)
                atom_b_x = float(ligand_atom_2_x)
                atom_b_y = float(ligand_atom_2_y)
                atom_b_z = float(ligand_atom_2_z)
                atom_b_xyz = (atom_b_x,atom_b_y,atom_b_z)

                starting_node = None
                ending_node = None

                starting_node_value = atom_a_xyz
                ending_node_value = atom_b_xyz

                # Iterate through nodes and find the one with the desired attribute value
                desired_node = None
                for node in G.nodes():
                    # print(G.nodes[node]['xyz'])
                    if G.nodes[node]['xyz'] == starting_node_value:
                        starting_node = node
                        print('Starting node:',node)
                    if G.nodes[node]['xyz'] == ending_node_value:
                        ending_node = node
                        print('Ending node:',node)

                if starting_node is None or ending_node is None:
                    raise ValueError("Could not find matching node(s) for the provided coordinates")                
                    
                shortest_path_xyz_list = []
                shortest_path_list = nx.shortest_path(G, source=starting_node, target=ending_node)
                for node in shortest_path_list:
                    print(G.nodes[node]['xyz'], ' ', node)                
                    shortest_path_xyz_list.append(G.nodes[node]['xyz'])
                #Create dictionary to store xyz for each ligand, then use it to match with the xyz in the original opt file
                
                shortest_path_xyz_dict = {}
                atom_order = 0
                for xyz in shortest_path_xyz_list:
                    shortest_path_atom = "Atom%d" %atom_order
                    shortest_path_xyz_dict[shortest_path_atom] = xyz
                    atom_order= atom_order + 1
                # print(shortest_path_xyz_dict)
                
                
                shortest_path_list_atom_label = [pd_atom+1]
                for xyz in shortest_path_xyz_dict:                       #Match with target xyz 
                    target_x = shortest_path_xyz_dict[xyz][0]
                    target_y = shortest_path_xyz_dict[xyz][1]
                    target_z = shortest_path_xyz_dict[xyz][2]
                    
                    # print(target_x)
                    # print(target_y)
                    # print(target_z)
                    
                    for index, row in xyz_df.iterrows():
                        if float(target_x) == float(row['X']) and (float(target_y) == float(row['Y']) and float(target_z) == float(row['Z'])):
                            shortest_path_list_atom_label.append(index+1)
                            break
                            
                
                # print('Atom label shortest path: ', shortest_path_list_atom_label)
                shortest_path_atom_label_lists.append(shortest_path_list_atom_label)
                              

data = {
    'Filename' : names,
    'Pd_atom label' : pd_atoms,
    'Methyl_atom_1 label' : methyl_atom_1,
    'Methyl_atom_2 label' : methyl_atom_2,
    'Hydrogens_methyl_1_label' : hydrogens_methyl_1,
    'Hydrogens_methyl_2_label' : hydrogens_methyl_2,
    'Ligand_atom_1 label' : ligand_atom_1,
    'Ligand_atom_2 label' : ligand_atom_2,
    'Atoms_distance_2 label' : atom_distance_lists_2,
    'Atoms_distance_3 label' : atom_distance_lists_3,
    'Atoms_distance_4 label' : atom_distance_lists_4,
    'Atoms_distance_2_a label': atom_distance_lists_2_a,
    'Atoms_distance_3_a label': atom_distance_lists_3_a,
    'Atoms_distance_4_a label': atom_distance_lists_4_a,
    'Atoms_distance_2_b label': atom_distance_lists_2_b,
    'Atoms_distance_3_b label': atom_distance_lists_3_b,
    'Atoms_distance_4_b label': atom_distance_lists_4_b,
    'Atom label shortest paths' : shortest_path_atom_label_lists
    }


atom_label_df = pd.DataFrame(data)


# Modify Atom_label_df to only include those that are have all three files 

mask = ~atom_label_df['Filename'].isin(missing_list)
atom_label_df = atom_label_df[mask]


csv_filename = 'atoms_label.csv'
atom_label_df.to_csv(csv_filename, index=False)
print(atom_label_df.head())

ligand-001-n-n-1
Pd number index:  1
['C', 'Pd', 'C', 'H', 'H', 'H', 'C', 'H', 'H', 'H', 'H', 'H', 'C', 'H', 'C', 'H', 'C', 'C', 'C', 'H', 'H', 'N', 'N', 'H', 'H', 'H', 'H', 'H', 'H', 'H', 'H', 'H', 'H']
Ligand atom label:  22  Ligand atom B nbo:  -0.55126
Ligand atom label:  23  Ligand atom A nbo:  -0.48882
Atom_a:  23 Atom_b:  22
C:\Users\George\Desktop\Research_UCLA\CIC\Computational Work\Project cluster version 2\project_catalyst_repurposing\structures_ligand_id\pd_me2_structures\ligand_xyz\ligand-001-n-n-1-ligand_xyz.txt

C:\Users\George\AppData\Local\Temp\ipykernel_7832\386804788.py:583: DeprecationWarning:

to_plotly_figure is deprecated and will be removed in version 4.0.0. Use MolGraph.to_plotly() instead.

C:\Users\George\AppData\Local\Temp\ipykernel_7832\386804788.py:589: DeprecationWarning:

to_networkx_graph is deprecated and will be removed in version 4.0.0. Use MolGraph.to_networkx() instead.

Ending node: 12
Starting node: 13
(-1.491218, -0.956693, 0.003991)   13
(-0.668134, -2.116302, 0.349288)   9
(0.678885, -2.114263, -0.344581)   0
(1.496369, -0.949341, -0.00377)   12
ligand-002-p-p-1
Pd number index:  1
['C', 'Pd', 'C', 'H', 'H', 'H', 'C', 'H', 'H', 'H', 'H', 'H', 'C', 'H', 'H', 'P', 'P', 'C', 'C', 'C', 'C', 'H', 'C', 'H', 'C', 'H', 'H', 'H', 'C', 'C', 'C', 'C', 'H', 'C', 'H', 'C', 'H', 'H', 'H', 'C', 'C', 'C', 'C', 'H', 'C', 'H', 'C', 'H', 'H', 'H', 'C', 'C', 'C', 'C', 'H', 'C', 'H', 'C', 'H', 'H', 'H']
Ligand atom label:  16  Ligand atom A nbo:  1.17518
Ligand atom label:  17  Ligand atom B nbo:  0.95542
Atom_a:  16 Atom_b:  17
C:\Users\George\Desktop\Research_UCLA\CIC\Computational Work\Project cluster version 2\project_catalyst_repurposing\structures_ligand_id\pd_me2_structures\ligand_xyz\ligand-002-p-p-1-ligand_xyz.txt

C:\Users\George\AppData\Local\Temp\ipykernel_7832\386804788.py:583: DeprecationWarning:

to_plotly_figure is deprecated and will be removed in version 4.0.0. Use MolGraph.to_plotly() instead.

C:\Users\George\AppData\Local\Temp\ipykernel_7832\386804788.py:589: DeprecationWarning:

to_networkx_graph is deprecated and will be removed in version 4.0.0. Use MolGraph.to_networkx() instead.

Starting node: 6
Ending node: 7
(1.688751, -0.141338, 0.220698)   6
(0.91271, -0.573164, 1.865196)   0
(-0.509342, -0.025928, 1.940818)   3
(-1.432395, -0.288589, 0.318623)   7
ligand-003-p-p-2
Pd number index:  2
['P', 'C', 'Pd', 'C', 'H', 'H', 'H', 'C', 'H', 'H', 'H', 'P', 'H', 'H', 'C', 'H', 'C', 'H', 'H', 'H', 'C', 'C', 'C', 'C', 'H', 'C', 'H', 'C', 'H', 'H', 'H', 'C', 'C', 'C', 'C', 'H', 'C', 'H', 'C', 'H', 'H', 'H', 'C', 'C', 'C', 'C', 'H', 'C', 'H', 'C', 'H', 'H', 'H', 'C', 'C', 'C', 'C', 'H', 'C', 'H', 'C', 'H', 'H', 'H']
Ligand atom label:  1  Ligand atom A nbo:  1.02659
Ligand atom label:  12  Ligand atom B nbo:  1.02437
Atom_a:  1 Atom_b:  12
C:\Users\George\Desktop\Research_UCLA\CIC\Computational Work\Project cluster version 2\project_catalyst_repurposing\structures_ligand_id\pd_me2_structures\ligand_xyz\ligand-003-p-p-2-ligand_xyz.txt
Starting node: 0
Ending node: 2
(-1.70582, 0.264426, -0.437921)   0
(-1.325801, 0.370988, -2.256722)   7
(-0.054687, -0.3512, -2.695941)   5
(1.26702, 0.275635, -2.256145)   1
(1.647728, 0.300935, -0.4365)   2
ligand-004-p-p-3
Pd number index:  2
['P', 'C', 'Pd', 'C', 'H', 'H', 'H', 'C', 'H', 'H', 'H', 'H', 'H', 'C', 'H', 'C', 'H', 'H', 'H', 'C', 'C', 'C', 'C', 'H', 'C', 'H', 'C', 'H', 'H', 'H', 'C', 'C', 'C', 'C', 'H', 'C', 'H', 'C', 'H', 'H', 'H', 'C', 'H', 'H', 'P', 'C', 'C', 'C', 'C', 'H', 'C', 'H', 'C', 'H', 'H', 'H', 'C', 'C', 'C', 'C', 'H', 'C', 'H', 'C', 'H', 'H', 'H']
Ligand atom label:  1  Ligand atom B nbo:  1.10291
Ligand atom label:  45  Ligand atom A nbo:  1.38915
Atom_a:  45 Atom_b:  1

C:\Users\George\AppData\Local\Temp\ipykernel_7832\386804788.py:583: DeprecationWarning:

to_plotly_figure is deprecated and will be removed in version 4.0.0. Use MolGraph.to_plotly() instead.

C:\Users\George\AppData\Local\Temp\ipykernel_7832\386804788.py:589: DeprecationWarning:

to_networkx_graph is deprecated and will be removed in version 4.0.0. Use MolGraph.to_networkx() instead.

C:\Users\George\Desktop\Research_UCLA\CIC\Computational Work\Project cluster version 2\project_catalyst_repurposing\structures_ligand_id\pd_me2_structures\ligand_xyz\ligand-004-p-p-3-ligand_xyz.txt
Ending node: 0
Starting node: 35
(-1.821684, 0.390221, 0.581315)   35
(-1.833118, 0.734155, 2.413395)   32
(-0.444306, 0.939033, 2.997387)   1
(0.465273, -0.299132, 2.959841)   4
(1.821799, -0.021, 2.324504)   6
(1.793732, 0.226827, 0.476328)   0
ligand-005-c-n-1
Pd number index:  0
['Pd', 'C', 'C', 'C', 'H', 'N', 'C', 'C', 'C', 'C', 'C', 'C', 'H', 'H', 'C', 'H', 'C', 'H', 'H', 'C', 'C', 'H', 'H', 'C', 'C', 'C', 'H', 'H', 'H', 'C', 'H', 'H', 'H', 'C', 'H', 'H', 'H', 'C', 'H', 'H', 'H', 'C', 'H', 'H', 'H', 'C', 'H', 'H', 'H', 'C', 'C', 'C', 'C', 'H', 'C', 'H', 'H', 'H', 'N', 'H', 'N']

C:\Users\George\AppData\Local\Temp\ipykernel_7832\386804788.py:583: DeprecationWarning:

to_plotly_figure is deprecated and will be removed in version 4.0.0. Use MolGraph.to_plotly() instead.

C:\Users\George\AppData\Local\Temp\ipykernel_7832\386804788.py:589: DeprecationWarning:

to_networkx_graph is deprecated and will be removed in version 4.0.0. Use MolGraph.to_networkx() instead.

Ligand atom label:  2  Ligand atom A nbo:  0.23056
Ligand atom label:  59  Ligand atom B nbo:  -0.48965
Atom_a:  2 Atom_b:  59
C:\Users\George\Desktop\Research_UCLA\CIC\Computational Work\Project cluster version 2\project_catalyst_repurposing\structures_ligand_id\pd_me2_structures\ligand_xyz\ligand-005-c-n-1-ligand_xyz.txt
Starting node: 0
Ending node: 49
(-0.067313, 0.516721, 0.001935)   0
(-0.927297, 1.545788, 0.333196)   4
(-2.325283, 1.550867, 0.339055)   23
(-3.13136, 0.39144, -0.099489)   40
(-2.772904, -0.860542, 0.230531)   49
ligand-006-c-n-2

C:\Users\George\AppData\Local\Temp\ipykernel_7832\386804788.py:583: DeprecationWarning:

to_plotly_figure is deprecated and will be removed in version 4.0.0. Use MolGraph.to_plotly() instead.

C:\Users\George\AppData\Local\Temp\ipykernel_7832\386804788.py:589: DeprecationWarning:

to_networkx_graph is deprecated and will be removed in version 4.0.0. Use MolGraph.to_networkx() instead.

Pd number index:  0
['Pd', 'C', 'C', 'C', 'H', 'N', 'C', 'C', 'C', 'C', 'C', 'C', 'H', 'H', 'C', 'C', 'H', 'H', 'C', 'C', 'H', 'C', 'C', 'C', 'H', 'H', 'H', 'C', 'H', 'H', 'H', 'C', 'H', 'H', 'H', 'C', 'C', 'C', 'C', 'H', 'C', 'H', 'H', 'N', 'H', 'H', 'C', 'H', 'H', 'H', 'H', 'H', 'C', 'C', 'H', 'H', 'H', 'C', 'H', 'H', 'H', 'C', 'H', 'H', 'H', 'C', 'C', 'H', 'H', 'H', 'C', 'H', 'H', 'H', 'C', 'H', 'H', 'H', 'N']
Ligand atom label:  2  Ligand atom A nbo:  0.24281
Ligand atom label:  44  Ligand atom B nbo:  -0.49801
Atom_a:  2 Atom_b:  44
C:\Users\George\Desktop\Research_UCLA\CIC\Computational Work\Project cluster version 2\project_catalyst_repurposing\structures_ligand_id\pd_me2_structures\ligand_xyz\ligand-006-c-n-2-ligand_xyz.txt

C:\Users\George\AppData\Local\Temp\ipykernel_7832\386804788.py:583: DeprecationWarning:

to_plotly_figure is deprecated and will be removed in version 4.0.0. Use MolGraph.to_plotly() instead.

C:\Users\George\AppData\Local\Temp\ipykernel_7832\386804788.py:589: DeprecationWarning:

to_networkx_graph is deprecated and will be removed in version 4.0.0. Use MolGraph.to_networkx() instead.

Starting node: 0
Ending node: 34
(1.046587, 0.173372, -0.15753)   0
(-0.001262, 1.071983, -0.080806)   4
(-1.345092, 0.831819, 0.207587)   21
(-1.894198, -0.539433, 0.294416)   26
(-1.20275, -1.520666, 0.897393)   34
ligand-007-c-n-3
Pd number index:  0
['Pd', 'C', 'C', 'C', 'H', 'N', 'C', 'C', 'C', 'C', 'C', 'C', 'H', 'H', 'C', 'C', 'H', 'C', 'C', 'H', 'C', 'C', 'C', 'H', 'H', 'H', 'C', 'H', 'H', 'H', 'C', 'H', 'H', 'H', 'C', 'C', 'C', 'C', 'H', 'C', 'H', 'H', 'N', 'H', 'H', 'C', 'H', 'H', 'H', 'H', 'C', 'C', 'H', 'H', 'H', 'C', 'H', 'H', 'H', 'C', 'H', 'H', 'H', 'C', 'C', 'H', 'H', 'H', 'C', 'H', 'H', 'H', 'C', 'H', 'H', 'H', 'C', 'H', 'H', 'H', 'C', 'H', 'H', 'H', 'N']
Ligand atom label:  2  Ligand atom A nbo:  0.23698
Ligand atom label:  43  Ligand atom B nbo:  -0.49863
Atom_a:  2 Atom_b:  43
C:\Users\George\Desktop\Research_UCLA\CIC\Computational Work\Project cluster version 2\project_catalyst_repurposing\structures_ligand_id\pd_me2_structures\ligand_xyz\ligand-007-c-n-3-ligand_xyz.txt
Starting node: 0
Ending node: 33
(-0.855198, 0.12005, 0.121325)   0
(0.164757, 1.048236, 0.018284)   4
(1.524606, 0.833723, -0.198805)   20
(2.108864, -0.52314, -0.277002)   25
(1.47375, -1.503505, -0.942386)   33
ligand-008-c-n-4
Pd number index:  0
['Pd', 'C', 'C', 'C', 'H', 'N', 'C', 'C', 'C', 'C', 'C', 'C', 'H', 'H', 'C', 'C', 'H', 'C', 'C', 'H', 'C', 'C', 'C', 'H', 'H', 'H', 'C', 'H', 'H', 'H', 'C', 'C', 'C', 'C', 'H', 'C', 'H', 'H', 'N', 'H', 'H', 'C', 'H', 'H', 'H', 'C', 'C', 'H', 'H', 'H', 'C', 'H', 'H', 'H', 'C', 'H', 'H', 'H', 'C', 'C', 'H', 'H', 'H', 'C', 'H', 'H', 'H', 'C', 'H', 'H', 'H', 'C', 'H', 'H', 'H', 'C', 'H', 'H', 'H', 'C', 'H', 'H', 'H', 'H', 'N']
Ligand atom label:  2  Ligand atom A nbo:  0.24493
Ligand atom label:  39  Ligand atom B nbo:  -0.49897
Atom_a:  2 Atom_b:  39

C:\Users\George\AppData\Local\Temp\ipykernel_7832\386804788.py:583: DeprecationWarning:

to_plotly_figure is deprecated and will be removed in version 4.0.0. Use MolGraph.to_plotly() instead.

C:\Users\George\AppData\Local\Temp\ipykernel_7832\386804788.py:589: DeprecationWarning:

to_networkx_graph is deprecated and will be removed in version 4.0.0. Use MolGraph.to_networkx() instead.

C:\Users\George\Desktop\Research_UCLA\CIC\Computational Work\Project cluster version 2\project_catalyst_repurposing\structures_ligand_id\pd_me2_structures\ligand_xyz\ligand-008-c-n-4-ligand_xyz.txt
Starting node: 0
Ending node: 29
(0.865196, 0.108848, -0.118676)   0
(-0.159855, 1.034831, -0.059627)   4
(-1.511756, 0.830898, 0.214129)   20
(-2.088115, -0.522091, 0.374488)   21
(-1.426709, -1.471295, 1.058107)   29
ligand-009-c-n-5

C:\Users\George\AppData\Local\Temp\ipykernel_7832\386804788.py:583: DeprecationWarning:

to_plotly_figure is deprecated and will be removed in version 4.0.0. Use MolGraph.to_plotly() instead.

C:\Users\George\AppData\Local\Temp\ipykernel_7832\386804788.py:589: DeprecationWarning:

to_networkx_graph is deprecated and will be removed in version 4.0.0. Use MolGraph.to_networkx() instead.

Pd number index:  0
['Pd', 'C', 'C', 'C', 'H', 'N', 'C', 'C', 'H', 'C', 'C', 'C', 'H', 'H', 'H', 'C', 'H', 'H', 'H', 'C', 'C', 'C', 'C', 'H', 'C', 'H', 'H', 'N', 'H', 'C', 'C', 'H', 'H', 'H', 'C', 'H', 'H', 'H', 'C', 'H', 'H', 'H', 'C', 'C', 'H', 'H', 'H', 'C', 'H', 'H', 'H', 'C', 'H', 'H', 'H', 'C', 'C', 'C', 'C', 'C', 'C', 'C', 'H', 'C', 'C', 'H', 'C', 'H', 'H', 'H', 'H', 'C', 'H', 'H', 'H', 'N']
Ligand atom label:  2  Ligand atom A nbo:  0.23532
Ligand atom label:  28  Ligand atom B nbo:  -0.49845
Atom_a:  2 Atom_b:  28
C:\Users\George\Desktop\Research_UCLA\CIC\Computational Work\Project cluster version 2\project_catalyst_repurposing\structures_ligand_id\pd_me2_structures\ligand_xyz\ligand-009-c-n-5-ligand_xyz.txt
Starting node: 0
Ending node: 18
(0.899524, 0.166137, -0.203912)   0
(-0.139452, 1.073334, -0.232554)   4
(-1.511588, 0.82607, -0.235012)   9
(-2.076858, -0.541943, -0.191659)   10
(-1.501183, -1.542434, -0.883009)   18
ligand-010-c-n-6

C:\Users\George\AppData\Local\Temp\ipykernel_7832\386804788.py:583: DeprecationWarning:

to_plotly_figure is deprecated and will be removed in version 4.0.0. Use MolGraph.to_plotly() instead.

C:\Users\George\AppData\Local\Temp\ipykernel_7832\386804788.py:589: DeprecationWarning:

to_networkx_graph is deprecated and will be removed in version 4.0.0. Use MolGraph.to_networkx() instead.

Pd number index:  0
['Pd', 'C', 'C', 'C', 'H', 'N', 'C', 'C', 'C', 'C', 'C', 'C', 'H', 'H', 'C', 'C', 'C', 'C', 'H', 'C', 'C', 'C', 'H', 'H', 'H', 'C', 'H', 'H', 'H', 'C', 'C', 'C', 'C', 'H', 'C', 'H', 'H', 'N', 'H', 'H', 'C', 'C', 'H', 'H', 'H', 'C', 'H', 'H', 'H', 'C', 'H', 'H', 'H', 'C', 'C', 'H', 'H', 'H', 'C', 'H', 'H', 'H', 'C', 'H', 'H', 'H', 'H', 'C', 'C', 'C', 'C', 'H', 'C', 'H', 'C', 'H', 'H', 'H', 'C', 'C', 'C', 'C', 'H', 'C', 'H', 'C', 'H', 'H', 'H', 'C', 'C', 'C', 'C', 'H', 'C', 'H', 'C', 'H', 'H', 'H', 'C', 'C', 'C', 'C', 'H', 'C', 'H', 'C', 'H', 'H', 'H', 'C', 'H', 'H', 'H', 'N']
Ligand atom label:  2  Ligand atom A nbo:  0.23381
Ligand atom label:  38  Ligand atom B nbo:  -0.50125
Atom_a:  2 Atom_b:  38
C:\Users\George\Desktop\Research_UCLA\CIC\Computational Work\Project cluster version 2\project_catalyst_repurposing\structures_ligand_id\pd_me2_structures\ligand_xyz\ligand-010-c-n-6-ligand_xyz.txt
Starting node: 0
Ending node: 28
(0.108395, 0.16314, -0.052504)   0
(1.066255, 0.625757, 0.823)   4
(2.411882, 0.905693, 0.586858)   19
(3.07424, 0.532103, -0.680704)   20
(2.471246, 0.749196, -1.861079)   28
ligand-011-c-n-7
Pd number index:  0
['Pd', 'C', 'C', 'N', 'C', 'C', 'H', 'H', 'H', 'C', 'H', 'H', 'H', 'C', 'C', 'C', 'C', 'H', 'C', 'H', 'H', 'N', 'H', 'H', 'H', 'H', 'C', 'C', 'C', 'H', 'C', 'C', 'H', 'H', 'N', 'C', 'C', 'C', 'C', 'C', 'C', 'H', 'H', 'C', 'H', 'H', 'H', 'C', 'H', 'H', 'H', 'C', 'H', 'H', 'H']

C:\Users\George\AppData\Local\Temp\ipykernel_7832\386804788.py:583: DeprecationWarning:

to_plotly_figure is deprecated and will be removed in version 4.0.0. Use MolGraph.to_plotly() instead.

C:\Users\George\AppData\Local\Temp\ipykernel_7832\386804788.py:589: DeprecationWarning:

to_networkx_graph is deprecated and will be removed in version 4.0.0. Use MolGraph.to_networkx() instead.

Ligand atom label:  2  Ligand atom A nbo:  0.25976
Ligand atom label:  22  Ligand atom B nbo:  -0.48823
Atom_a:  2 Atom_b:  22
C:\Users\George\Desktop\Research_UCLA\CIC\Computational Work\Project cluster version 2\project_catalyst_repurposing\structures_ligand_id\pd_me2_structures\ligand_xyz\ligand-011-c-n-7-ligand_xyz.txt
Starting node: 0
Ending node: 12
(0.445111, 1.034705, -0.625795)   0
(1.58921, 1.721456, -0.875917)   2
(2.806136, 1.035441, -1.277663)   3
(3.3298, 0.145718, -0.178039)   4
(2.522102, -0.847432, 0.221544)   12
ligand-013-p-p-5

C:\Users\George\AppData\Local\Temp\ipykernel_7832\386804788.py:583: DeprecationWarning:

to_plotly_figure is deprecated and will be removed in version 4.0.0. Use MolGraph.to_plotly() instead.

C:\Users\George\AppData\Local\Temp\ipykernel_7832\386804788.py:589: DeprecationWarning:

to_networkx_graph is deprecated and will be removed in version 4.0.0. Use MolGraph.to_networkx() instead.

Pd number index:  2
['P', 'C', 'Pd', 'C', 'H', 'H', 'H', 'C', 'H', 'H', 'H', 'P', 'H', 'H', 'C', 'H', 'C', 'H', 'H', 'H', 'C', 'C', 'C', 'H', 'C', 'H', 'H', 'C', 'H', 'H', 'C', 'H', 'H', 'H', 'H', 'H', 'H', 'C', 'C', 'C', 'H', 'C', 'H', 'H', 'C', 'H', 'H', 'C', 'H', 'H', 'H', 'H', 'H', 'H', 'C', 'C', 'C', 'H', 'C', 'H', 'H', 'C', 'H', 'H', 'C', 'H', 'H', 'H', 'H', 'H', 'H', 'C', 'C', 'C', 'H', 'C', 'H', 'H', 'C', 'H', 'H', 'C', 'H', 'H', 'H', 'H', 'H', 'H']
Ligand atom label:  1  Ligand atom A nbo:  1.04568
Ligand atom label:  12  Ligand atom B nbo:  1.03379
Atom_a:  1 Atom_b:  12
C:\Users\George\Desktop\Research_UCLA\CIC\Computational Work\Project cluster version 2\project_catalyst_repurposing\structures_ligand_id\pd_me2_structures\ligand_xyz\ligand-013-p-p-5-ligand_xyz.txt
Starting node: 0
Ending node: 2
(-1.755755, 0.210035, -0.349979)   0
(-1.430384, 0.332116, -2.173753)   7
(-0.093907, -0.208912, -2.675497)   5
(1.158765, 0.555734, -2.250899)   1
(1.642832, 0.435878, -0.457803)   2
ligand-014-p-c-1
Pd number index:  1
['P', 'Pd', 'C', 'H', 'H', 'C', 'H', 'H', 'H', 'C', 'H', 'H', 'C', 'C', 'C', 'H', 'C', 'H', 'H', 'C', 'H', 'H', 'C', 'H', 'H', 'H', 'H', 'H', 'H', 'C', 'C', 'C', 'H', 'C', 'H', 'H', 'C', 'H', 'H', 'C', 'H', 'H', 'H', 'H', 'H', 'H', 'C', 'C', 'H', 'C', 'H', 'N', 'N', 'C', 'C', 'C', 'C', 'C', 'C', 'H', 'H', 'C', 'H', 'H', 'H', 'C', 'H', 'H', 'H', 'C', 'H', 'H', 'H', 'H']

C:\Users\George\AppData\Local\Temp\ipykernel_7832\386804788.py:583: DeprecationWarning:

to_plotly_figure is deprecated and will be removed in version 4.0.0. Use MolGraph.to_plotly() instead.

C:\Users\George\AppData\Local\Temp\ipykernel_7832\386804788.py:589: DeprecationWarning:

to_networkx_graph is deprecated and will be removed in version 4.0.0. Use MolGraph.to_networkx() instead.

Ligand atom label:  1  Ligand atom B nbo:  1.16437
Ligand atom label:  47  Ligand atom A nbo:  0.40352
Atom_a:  1 Atom_b:  47
C:\Users\George\Desktop\Research_UCLA\CIC\Computational Work\Project cluster version 2\project_catalyst_repurposing\structures_ligand_id\pd_me2_structures\ligand_xyz\ligand-014-p-c-1-ligand_xyz.txt
Starting node: 0
Ending node: 38
(1.763323, -0.143596, 0.098196)   0
(1.253404, 0.206195, 1.86762)   1
(-0.172619, 0.474728, 1.893032)   43
(-1.040031, -0.029575, 0.963768)   38
ligand-015-p-c-2

C:\Users\George\AppData\Local\Temp\ipykernel_7832\386804788.py:583: DeprecationWarning:

to_plotly_figure is deprecated and will be removed in version 4.0.0. Use MolGraph.to_plotly() instead.

C:\Users\George\AppData\Local\Temp\ipykernel_7832\386804788.py:589: DeprecationWarning:

to_networkx_graph is deprecated and will be removed in version 4.0.0. Use MolGraph.to_networkx() instead.

Pd number index:  1
['P', 'Pd', 'C', 'H', 'H', 'C', 'H', 'H', 'H', 'C', 'H', 'H', 'C', 'C', 'C', 'H', 'C', 'H', 'H', 'C', 'H', 'H', 'C', 'H', 'H', 'H', 'H', 'H', 'H', 'C', 'C', 'C', 'H', 'C', 'H', 'H', 'C', 'H', 'H', 'C', 'H', 'H', 'H', 'H', 'H', 'H', 'C', 'C', 'H', 'C', 'H', 'N', 'N', 'C', 'C', 'C', 'C', 'C', 'C', 'H', 'H', 'C', 'H', 'H', 'H', 'C', 'H', 'H', 'H', 'C', 'H', 'H', 'H', 'H', 'H', 'H']
Ligand atom label:  1  Ligand atom B nbo:  1.16731
Ligand atom label:  47  Ligand atom A nbo:  0.42427
Atom_a:  1 Atom_b:  47
C:\Users\George\Desktop\Research_UCLA\CIC\Computational Work\Project cluster version 2\project_catalyst_repurposing\structures_ligand_id\pd_me2_structures\ligand_xyz\ligand-015-p-c-2-ligand_xyz.txt
Starting node: 0
Ending node: 38
(1.775158, -0.127121, 0.076491)   0
(1.25569, 0.248057, 1.833802)   1
(-0.15768, 0.534481, 1.837969)   43
(-1.039167, 0.009918, 0.951707)   38
ligand-016-p-c-3
Pd number index:  1
['P', 'Pd', 'C', 'H', 'H', 'C', 'H', 'H', 'H', 'C', 'H', 'H', 'C', 'C', 'C', 'H', 'C', 'H', 'H', 'C', 'H', 'H', 'C', 'H', 'H', 'H', 'H', 'H', 'H', 'C', 'C', 'C', 'H', 'C', 'H', 'H', 'C', 'H', 'H', 'C', 'H', 'H', 'H', 'H', 'H', 'H', 'C', 'N', 'N', 'C', 'C', 'C', 'C', 'C', 'C', 'H', 'H', 'C', 'H', 'H', 'H', 'C', 'H', 'H', 'H', 'C', 'H', 'H', 'H', 'C', 'C', 'C', 'C', 'C', 'H', 'C', 'H', 'H', 'H', 'H']
Ligand atom label:  1  Ligand atom B nbo:  1.00219
Ligand atom label:  47  Ligand atom A nbo:  0.32003
Atom_a:  1 Atom_b:  47

C:\Users\George\AppData\Local\Temp\ipykernel_7832\386804788.py:583: DeprecationWarning:

to_plotly_figure is deprecated and will be removed in version 4.0.0. Use MolGraph.to_plotly() instead.

C:\Users\George\AppData\Local\Temp\ipykernel_7832\386804788.py:589: DeprecationWarning:

to_networkx_graph is deprecated and will be removed in version 4.0.0. Use MolGraph.to_networkx() instead.

C:\Users\George\Desktop\Research_UCLA\CIC\Computational Work\Project cluster version 2\project_catalyst_repurposing\structures_ligand_id\pd_me2_structures\ligand_xyz\ligand-016-p-c-3-ligand_xyz.txt
Starting node: 0
Ending node: 38
(-1.953873, -0.252208, -0.063293)   0
(-1.304573, 1.016178, -1.27964)   1
(0.129825, 1.122908, -1.106843)   39
(0.906079, 0.095207, -0.633469)   38
ligand-017-p-c-4

C:\Users\George\AppData\Local\Temp\ipykernel_7832\386804788.py:583: DeprecationWarning:

to_plotly_figure is deprecated and will be removed in version 4.0.0. Use MolGraph.to_plotly() instead.

C:\Users\George\AppData\Local\Temp\ipykernel_7832\386804788.py:589: DeprecationWarning:

to_networkx_graph is deprecated and will be removed in version 4.0.0. Use MolGraph.to_networkx() instead.

Pd number index:  1
['P', 'Pd', 'C', 'H', 'H', 'C', 'H', 'H', 'H', 'C', 'H', 'H', 'C', 'C', 'C', 'H', 'C', 'H', 'H', 'C', 'H', 'H', 'C', 'H', 'H', 'H', 'H', 'H', 'H', 'C', 'C', 'C', 'H', 'C', 'H', 'H', 'C', 'H', 'H', 'C', 'H', 'H', 'H', 'H', 'H', 'H', 'C', 'C', 'C', 'N', 'N', 'C', 'C', 'C', 'C', 'C', 'C', 'H', 'H', 'C', 'H', 'H', 'H', 'C', 'H', 'H', 'H', 'C', 'H', 'H', 'H', 'C', 'H', 'H', 'H', 'C', 'H', 'H', 'H', 'H']
Ligand atom label:  1  Ligand atom B nbo:  1.1667
Ligand atom label:  47  Ligand atom A nbo:  0.40392
Atom_a:  1 Atom_b:  47
C:\Users\George\Desktop\Research_UCLA\CIC\Computational Work\Project cluster version 2\project_catalyst_repurposing\structures_ligand_id\pd_me2_structures\ligand_xyz\ligand-017-p-c-4-ligand_xyz.txt

C:\Users\George\AppData\Local\Temp\ipykernel_7832\386804788.py:583: DeprecationWarning:

to_plotly_figure is deprecated and will be removed in version 4.0.0. Use MolGraph.to_plotly() instead.

C:\Users\George\AppData\Local\Temp\ipykernel_7832\386804788.py:589: DeprecationWarning:

to_networkx_graph is deprecated and will be removed in version 4.0.0. Use MolGraph.to_networkx() instead.

Starting node: 0
Ending node: 38
(1.863543, -0.228279, 0.040136)   0
(1.302396, 0.675061, 1.581306)   1
(-0.120986, 0.924121, 1.466138)   41
(-0.952427, 0.087874, 0.777382)   38
ligand-018-p-c-5
Pd number index:  1
['C', 'Pd', 'C', 'H', 'H', 'H', 'C', 'H', 'H', 'H', 'P', 'H', 'H', 'C', 'H', 'C', 'H', 'H', 'H', 'C', 'C', 'C', 'H', 'C', 'H', 'H', 'C', 'H', 'H', 'C', 'H', 'H', 'H', 'H', 'H', 'H', 'C', 'C', 'C', 'H', 'C', 'H', 'H', 'C', 'H', 'H', 'C', 'H', 'H', 'H', 'H', 'H', 'H', 'C', 'C', 'H', 'C', 'H', 'N', 'N', 'C', 'C', 'C', 'C', 'C', 'C', 'H', 'H', 'C', 'H', 'H', 'H', 'C', 'H', 'H', 'H', 'C', 'H', 'H', 'H']
Ligand atom label:  11  Ligand atom B nbo:  0.98465
Ligand atom label:  55  Ligand atom A nbo:  0.34263
Atom_a:  11 Atom_b:  55
C:\Users\George\Desktop\Research_UCLA\CIC\Computational Work\Project cluster version 2\project_catalyst_repurposing\structures_ligand_id\pd_me2_structures\ligand_xyz\ligand-018-p-c-5-ligand_xyz.txt
Starting node: 1
Ending node: 45
(1.704788, -0.101654, -0.536298)   1
(2.173405, 0.569571, -2.21104)   0
(1.002692, 1.007116, -3.086832)   4
(0.215292, 2.222345, -2.635112)   6
(-0.739685, 2.035396, -1.540719)   49
(-1.230544, 0.866179, -1.037697)   45
ligand-019-p-c-6
Pd number index:  1
['C', 'Pd', 'C', 'H', 'H', 'H', 'C', 'H', 'H', 'H', 'P', 'H', 'H', 'C', 'H', 'C', 'H', 'H', 'H', 'C', 'C', 'C', 'H', 'C', 'H', 'H', 'C', 'H', 'H', 'C', 'H', 'H', 'H', 'H', 'H', 'H', 'C', 'C', 'C', 'H', 'C', 'H', 'H', 'C', 'H', 'H', 'C', 'H', 'H', 'H', 'H', 'H', 'H', 'C', 'C', 'H', 'C', 'H', 'N', 'N', 'C', 'H', 'H', 'C', 'C', 'C', 'C', 'C', 'C', 'H', 'C', 'H', 'C', 'C', 'H', 'C', 'H', 'H', 'H', 'H']

C:\Users\George\AppData\Local\Temp\ipykernel_7832\386804788.py:583: DeprecationWarning:

to_plotly_figure is deprecated and will be removed in version 4.0.0. Use MolGraph.to_plotly() instead.

C:\Users\George\AppData\Local\Temp\ipykernel_7832\386804788.py:589: DeprecationWarning:

to_networkx_graph is deprecated and will be removed in version 4.0.0. Use MolGraph.to_networkx() instead.

Ligand atom label:  11  Ligand atom B nbo:  0.98253
Ligand atom label:  55  Ligand atom A nbo:  0.33483
Atom_a:  11 Atom_b:  55
C:\Users\George\Desktop\Research_UCLA\CIC\Computational Work\Project cluster version 2\project_catalyst_repurposing\structures_ligand_id\pd_me2_structures\ligand_xyz\ligand-019-p-c-6-ligand_xyz.txt

C:\Users\George\AppData\Local\Temp\ipykernel_7832\386804788.py:583: DeprecationWarning:

to_plotly_figure is deprecated and will be removed in version 4.0.0. Use MolGraph.to_plotly() instead.

C:\Users\George\AppData\Local\Temp\ipykernel_7832\386804788.py:589: DeprecationWarning:

to_networkx_graph is deprecated and will be removed in version 4.0.0. Use MolGraph.to_networkx() instead.

Starting node: 1
Ending node: 45
(2.311927, 0.082691, -0.444687)   1
(2.951322, 1.32578, -1.677354)   0
(1.894641, 1.866579, -2.63928)   4
(0.939338, 2.914169, -2.101238)   6
(-0.101059, 2.471118, -1.174151)   49
(-0.536842, 1.202016, -0.934181)   45
ligand-020-p-c-7
Pd number index:  1
['C', 'Pd', 'C', 'H', 'H', 'H', 'C', 'H', 'H', 'H', 'P', 'H', 'H', 'C', 'H', 'C', 'H', 'H', 'H', 'C', 'C', 'C', 'H', 'C', 'H', 'H', 'C', 'H', 'H', 'C', 'H', 'H', 'H', 'H', 'H', 'H', 'C', 'C', 'C', 'H', 'C', 'H', 'H', 'C', 'H', 'H', 'C', 'H', 'H', 'H', 'H', 'H', 'H', 'C', 'C', 'H', 'C', 'H', 'N', 'N', 'C', 'H', 'H', 'C', 'C', 'C', 'C', 'C', 'H', 'C', 'H', 'H', 'H', 'H']
Ligand atom label:  11  Ligand atom B nbo:  0.98169
Ligand atom label:  55  Ligand atom A nbo:  0.33517
Atom_a:  11 Atom_b:  55
C:\Users\George\Desktop\Research_UCLA\CIC\Computational Work\Project cluster version 2\project_catalyst_repurposing\structures_ligand_id\pd_me2_structures\ligand_xyz\ligand-020-p-c-7-ligand_xyz.txt
Starting node: 1
Ending node: 45
(1.764516, -0.198422, -0.441179)   1
(2.080542, -0.243272, -2.277748)   0
(0.905102, -0.751134, -3.11108)   4
(-0.235349, 0.215988, -3.36382)   6
(-1.116277, 0.537954, -2.242253)   49
(-1.266969, -0.130095, -1.063218)   45
ligand-021-p-c-8

C:\Users\George\AppData\Local\Temp\ipykernel_7832\386804788.py:583: DeprecationWarning:

to_plotly_figure is deprecated and will be removed in version 4.0.0. Use MolGraph.to_plotly() instead.

C:\Users\George\AppData\Local\Temp\ipykernel_7832\386804788.py:589: DeprecationWarning:

to_networkx_graph is deprecated and will be removed in version 4.0.0. Use MolGraph.to_networkx() instead.

Pd number index:  1
['C', 'Pd', 'C', 'H', 'H', 'H', 'C', 'H', 'H', 'H', 'P', 'H', 'H', 'C', 'H', 'C', 'H', 'H', 'H', 'C', 'C', 'C', 'H', 'C', 'H', 'H', 'C', 'H', 'H', 'C', 'H', 'H', 'H', 'H', 'H', 'H', 'C', 'C', 'C', 'H', 'C', 'H', 'H', 'C', 'H', 'H', 'C', 'H', 'H', 'H', 'H', 'H', 'H', 'C', 'C', 'H', 'C', 'H', 'N', 'N', 'C', 'H', 'H', 'C', 'C', 'C', 'C', 'C', 'H', 'C', 'H', 'H', 'H', 'F']
Ligand atom label:  11  Ligand atom B nbo:  0.98213
Ligand atom label:  55  Ligand atom A nbo:  0.33402
Atom_a:  11 Atom_b:  55
C:\Users\George\Desktop\Research_UCLA\CIC\Computational Work\Project cluster version 2\project_catalyst_repurposing\structures_ligand_id\pd_me2_structures\ligand_xyz\ligand-021-p-c-8-ligand_xyz.txt
Starting node: 1
Ending node: 45
(2.008505, -0.202937, -0.423431)   1
(2.37168, -0.240465, -2.251212)   0
(1.214421, -0.734821, -3.117386)   4
(0.087941, 0.242142, -3.393559)   6
(-0.820539, 0.562517, -2.293409)   49
(-1.0067, -0.112166, -1.123393)   45
ligand-022-p-c-9

C:\Users\George\AppData\Local\Temp\ipykernel_7832\386804788.py:583: DeprecationWarning:

to_plotly_figure is deprecated and will be removed in version 4.0.0. Use MolGraph.to_plotly() instead.

C:\Users\George\AppData\Local\Temp\ipykernel_7832\386804788.py:589: DeprecationWarning:

to_networkx_graph is deprecated and will be removed in version 4.0.0. Use MolGraph.to_networkx() instead.

Pd number index:  1
['C', 'Pd', 'C', 'H', 'H', 'H', 'C', 'H', 'H', 'H', 'P', 'H', 'H', 'C', 'H', 'C', 'H', 'H', 'H', 'C', 'C', 'C', 'H', 'C', 'H', 'H', 'C', 'H', 'H', 'C', 'H', 'H', 'H', 'H', 'H', 'H', 'C', 'C', 'C', 'H', 'C', 'H', 'H', 'C', 'H', 'H', 'C', 'H', 'H', 'H', 'H', 'H', 'H', 'C', 'C', 'H', 'C', 'H', 'N', 'N', 'C', 'H', 'H', 'C', 'C', 'C', 'C', 'C', 'H', 'C', 'H', 'H', 'H', 'O', 'C', 'H', 'H', 'H']
Ligand atom label:  11  Ligand atom B nbo:  0.98181
Ligand atom label:  55  Ligand atom A nbo:  0.33479
Atom_a:  11 Atom_b:  55
C:\Users\George\Desktop\Research_UCLA\CIC\Computational Work\Project cluster version 2\project_catalyst_repurposing\structures_ligand_id\pd_me2_structures\ligand_xyz\ligand-022-p-c-9-ligand_xyz.txt
Starting node: 1
Ending node: 45
(2.286103, -0.203971, -0.370813)   1
(2.729679, -0.334582, -2.176534)   0
(1.622752, -0.901998, -3.063773)   4
(0.483338, 0.028242, -3.432657)   6
(-0.48699, 0.363327, -2.391882)   49
(-0.699048, -0.256266, -1.195948)   45
ligand-027-p-p-6
Pd number index:  1
['C', 'Pd', 'C', 'H', 'H', 'H', 'C', 'H', 'H', 'H', 'H', 'H', 'C', 'H', 'H', 'P', 'P', 'C', 'C', 'C', 'C', 'C', 'H', 'H', 'H', 'C', 'H', 'H', 'H', 'C', 'H', 'H', 'H', 'C', 'H', 'H', 'H', 'C', 'H', 'H', 'H', 'C', 'H', 'H', 'H', 'C', 'H', 'H', 'H', 'C', 'H', 'H', 'H', 'C', 'H', 'H', 'H', 'C', 'H', 'H', 'H', 'C', 'H', 'H', 'H', 'C', 'H', 'H', 'H']
Ligand atom label:  16  Ligand atom B nbo:  0.97586
Ligand atom label:  17  Ligand atom A nbo:  0.95978
Atom_a:  16 Atom_b:  17

C:\Users\George\AppData\Local\Temp\ipykernel_7832\386804788.py:583: DeprecationWarning:

to_plotly_figure is deprecated and will be removed in version 4.0.0. Use MolGraph.to_plotly() instead.

C:\Users\George\AppData\Local\Temp\ipykernel_7832\386804788.py:589: DeprecationWarning:

to_networkx_graph is deprecated and will be removed in version 4.0.0. Use MolGraph.to_networkx() instead.

C:\Users\George\Desktop\Research_UCLA\CIC\Computational Work\Project cluster version 2\project_catalyst_repurposing\structures_ligand_id\pd_me2_structures\ligand_xyz\ligand-027-p-p-6-ligand_xyz.txt
Starting node: 6
Ending node: 7
(1.657465, 0.100932, 0.379245)   6
(0.693091, 0.088933, 1.987791)   0
(-0.705339, 0.693068, 1.869995)   3
(-1.665293, 0.090781, 0.374825)   7
ligand-029-p-p-8
Pd number index:  0
['Pd', 'C', 'H', 'H', 'H', 'C', 'H', 'H', 'H', 'C', 'H', 'C', 'C', 'C', 'H', 'H', 'C', 'H', 'H', 'H', 'H', 'P', 'C', 'C', 'C', 'H', 'H', 'H', 'H', 'H', 'H', 'P', 'H', 'C', 'C', 'H', 'H', 'H', 'C', 'H', 'H', 'H', 'C', 'H', 'H', 'H', 'C', 'C', 'H', 'H', 'H', 'C', 'H', 'H', 'H', 'C', 'H', 'H', 'H']

C:\Users\George\AppData\Local\Temp\ipykernel_7832\386804788.py:583: DeprecationWarning:

to_plotly_figure is deprecated and will be removed in version 4.0.0. Use MolGraph.to_plotly() instead.

C:\Users\George\AppData\Local\Temp\ipykernel_7832\386804788.py:589: DeprecationWarning:

to_networkx_graph is deprecated and will be removed in version 4.0.0. Use MolGraph.to_networkx() instead.

Ligand atom label:  22  Ligand atom A nbo:  1.20928
Ligand atom label:  32  Ligand atom B nbo:  1.18716
Atom_a:  22 Atom_b:  32
C:\Users\George\Desktop\Research_UCLA\CIC\Computational Work\Project cluster version 2\project_catalyst_repurposing\structures_ligand_id\pd_me2_structures\ligand_xyz\ligand-029-p-p-8-ligand_xyz.txt

C:\Users\George\AppData\Local\Temp\ipykernel_7832\386804788.py:583: DeprecationWarning:

to_plotly_figure is deprecated and will be removed in version 4.0.0. Use MolGraph.to_plotly() instead.

C:\Users\George\AppData\Local\Temp\ipykernel_7832\386804788.py:589: DeprecationWarning:

to_networkx_graph is deprecated and will be removed in version 4.0.0. Use MolGraph.to_networkx() instead.

Starting node: 12
Ending node: 22
(1.586598, 0.188267, -0.343544)   12
(0.682393, 1.86143, -0.348858)   2
(-0.682482, 1.861608, 0.34777)   0
(-1.586769, 0.188384, 0.343777)   22
ligand-030-p-p-9
Pd number index:  0
['Pd', 'C', 'H', 'H', 'H', 'C', 'H', 'H', 'H', 'P', 'P', 'C', 'C', 'C', 'H', 'H', 'H', 'C', 'H', 'H', 'H', 'C', 'H', 'H', 'H', 'C', 'H', 'H', 'H', 'C', 'H', 'H', 'H', 'C', 'H', 'H', 'H', 'C', 'C', 'C', 'C', 'C', 'C', 'C', 'H', 'C', 'H', 'H', 'H', 'N', 'N', 'C', 'H', 'H', 'H', 'C', 'H', 'H', 'H']
Ligand atom label:  10  Ligand atom B nbo:  0.99117
Ligand atom label:  11  Ligand atom A nbo:  1.10455
Atom_a:  11 Atom_b:  10
C:\Users\George\Desktop\Research_UCLA\CIC\Computational Work\Project cluster version 2\project_catalyst_repurposing\structures_ligand_id\pd_me2_structures\ligand_xyz\ligand-030-p-p-9-ligand_xyz.txt
Ending node: 0
Starting node: 1
(-0.576358, -1.514204, -0.57121)   1
(1.053047, -0.640904, -0.326092)   28
(1.053046, 0.641028, 0.326146)   29
(-0.576355, 1.514351, 0.571284)   0
ligand-031-p-p-10

C:\Users\George\AppData\Local\Temp\ipykernel_7832\386804788.py:583: DeprecationWarning:

to_plotly_figure is deprecated and will be removed in version 4.0.0. Use MolGraph.to_plotly() instead.

C:\Users\George\AppData\Local\Temp\ipykernel_7832\386804788.py:589: DeprecationWarning:

to_networkx_graph is deprecated and will be removed in version 4.0.0. Use MolGraph.to_networkx() instead.

Pd number index:  2
['P', 'C', 'Pd', 'C', 'H', 'H', 'H', 'C', 'H', 'H', 'H', 'P', 'H', 'H', 'C', 'H', 'C', 'H', 'C', 'C', 'H', 'H', 'H', 'C', 'H', 'H', 'H', 'C', 'C', 'H', 'H', 'H', 'C', 'H', 'H', 'H', 'C', 'H', 'H', 'H', 'C', 'H', 'H', 'H', 'C', 'H', 'H', 'H', 'C', 'H', 'H', 'H', 'H', 'H', 'C', 'H', 'H']
Ligand atom label:  1  Ligand atom B nbo:  0.91328
Ligand atom label:  12  Ligand atom A nbo:  1.17333
Atom_a:  12 Atom_b:  1
C:\Users\George\Desktop\Research_UCLA\CIC\Computational Work\Project cluster version 2\project_catalyst_repurposing\structures_ligand_id\pd_me2_structures\ligand_xyz\ligand-031-p-p-10-ligand_xyz.txt
Ending node: 0
Starting node: 2
(1.666939, 0.41881, 0.225986)   2
(0.814123, 1.614685, 1.382589)   1
(-0.622477, 1.933201, 0.979326)   45
(-1.56516, 0.460084, 0.288663)   0
ligand-032-p-p-11

C:\Users\George\AppData\Local\Temp\ipykernel_7832\386804788.py:583: DeprecationWarning:

to_plotly_figure is deprecated and will be removed in version 4.0.0. Use MolGraph.to_plotly() instead.

C:\Users\George\AppData\Local\Temp\ipykernel_7832\386804788.py:589: DeprecationWarning:

to_networkx_graph is deprecated and will be removed in version 4.0.0. Use MolGraph.to_networkx() instead.

Pd number index:  2
['P', 'C', 'Pd', 'C', 'H', 'H', 'H', 'C', 'H', 'H', 'H', 'P', 'H', 'H', 'C', 'H', 'C', 'H', 'C', 'C', 'H', 'H', 'H', 'C', 'H', 'H', 'H', 'C', 'C', 'H', 'H', 'H', 'C', 'H', 'H', 'H', 'C', 'H', 'H', 'H', 'C', 'H', 'H', 'H', 'C', 'H', 'H', 'H', 'C', 'H', 'H', 'H', 'H', 'H', 'C', 'H', 'C', 'H', 'H', 'H']
Ligand atom label:  1  Ligand atom A nbo:  0.94031
Ligand atom label:  12  Ligand atom B nbo:  1.25954
Atom_a:  12 Atom_b:  1
C:\Users\George\Desktop\Research_UCLA\CIC\Computational Work\Project cluster version 2\project_catalyst_repurposing\structures_ligand_id\pd_me2_structures\ligand_xyz\ligand-032-p-p-11-ligand_xyz.txt
Ending node: 0
Starting node: 2
(1.749835, 0.365927, 0.500853)   2
(1.117581, 1.39538, 1.926735)   1
(-0.196566, 2.14719, 1.729085)   45
(-1.440087, 1.267132, 1.81262)   47
(-1.781866, 0.188508, 0.332093)   0
ligand-033-p-p-12

C:\Users\George\AppData\Local\Temp\ipykernel_7832\386804788.py:583: DeprecationWarning:

to_plotly_figure is deprecated and will be removed in version 4.0.0. Use MolGraph.to_plotly() instead.

C:\Users\George\AppData\Local\Temp\ipykernel_7832\386804788.py:589: DeprecationWarning:

to_networkx_graph is deprecated and will be removed in version 4.0.0. Use MolGraph.to_networkx() instead.

Pd number index:  2
['P', 'C', 'Pd', 'C', 'H', 'H', 'H', 'C', 'H', 'H', 'H', 'P', 'H', 'H', 'C', 'H', 'C', 'H', 'C', 'C', 'H', 'H', 'H', 'C', 'H', 'H', 'H', 'C', 'C', 'H', 'H', 'H', 'C', 'H', 'H', 'H', 'C', 'H', 'H', 'H', 'C', 'H', 'H', 'H', 'C', 'H', 'H', 'H', 'C', 'H', 'H', 'H', 'H', 'H', 'C', 'H', 'C', 'H', 'H', 'H', 'C', 'H', 'H']
Ligand atom label:  1  Ligand atom A nbo:  0.86349
Ligand atom label:  12  Ligand atom B nbo:  1.08394
Atom_a:  12 Atom_b:  1
C:\Users\George\Desktop\Research_UCLA\CIC\Computational Work\Project cluster version 2\project_catalyst_repurposing\structures_ligand_id\pd_me2_structures\ligand_xyz\ligand-033-p-p-12-ligand_xyz.txt
Ending node: 0
Starting node: 2
(1.953181, 0.492888, 0.28381)   2
(1.696121, 2.098356, 1.218813)   1
(0.312782, 2.700812, 1.029703)   45
(-0.730394, 2.060847, 1.949563)   47
(-2.047551, 1.776366, 1.244336)   51
(-1.97949, 0.226735, 0.1937)   0
ligand-035-p-p-14

C:\Users\George\AppData\Local\Temp\ipykernel_7832\386804788.py:583: DeprecationWarning:

to_plotly_figure is deprecated and will be removed in version 4.0.0. Use MolGraph.to_plotly() instead.

C:\Users\George\AppData\Local\Temp\ipykernel_7832\386804788.py:589: DeprecationWarning:

to_networkx_graph is deprecated and will be removed in version 4.0.0. Use MolGraph.to_networkx() instead.

Pd number index:  0
['Pd', 'C', 'H', 'H', 'H', 'C', 'H', 'H', 'H', 'C', 'H', 'C', 'C', 'H', 'H', 'P', 'C', 'H', 'H', 'P', 'H', 'C', 'C', 'H', 'H', 'H', 'C', 'H', 'H', 'H', 'C', 'H', 'H', 'H', 'C', 'C', 'H', 'H', 'H', 'C', 'H', 'H', 'H', 'C', 'H', 'H', 'H', 'C', 'C', 'C', 'C', 'H', 'C', 'C', 'H', 'H', 'H', 'C', 'C', 'C', 'C', 'C', 'H', 'C', 'H', 'H', 'H']
Ligand atom label:  16  Ligand atom A nbo:  1.22104
Ligand atom label:  20  Ligand atom B nbo:  1.22663
Atom_a:  20 Atom_b:  16
C:\Users\George\Desktop\Research_UCLA\CIC\Computational Work\Project cluster version 2\project_catalyst_repurposing\structures_ligand_id\pd_me2_structures\ligand_xyz\ligand-035-p-p-14-ligand_xyz.txt
Ending node: 6
Starting node: 10
(0.290778, 1.576684, 0.235048)   10
(0.375576, 0.66982, -1.434728)   0
(-0.375096, -0.6695, -1.43504)   2
(-0.290745, -1.576832, 0.234732)   6
ligand-036-p-p-15

C:\Users\George\AppData\Local\Temp\ipykernel_7832\386804788.py:583: DeprecationWarning:

to_plotly_figure is deprecated and will be removed in version 4.0.0. Use MolGraph.to_plotly() instead.

C:\Users\George\AppData\Local\Temp\ipykernel_7832\386804788.py:589: DeprecationWarning:

to_networkx_graph is deprecated and will be removed in version 4.0.0. Use MolGraph.to_networkx() instead.

Pd number index:  9
['P', 'C', 'C', 'C', 'C', 'C', 'C', 'H', 'H', 'Pd', 'H', 'C', 'H', 'H', 'H', 'C', 'H', 'H', 'H', 'H', 'P', 'C', 'C', 'H', 'H', 'H', 'C', 'H', 'H', 'H', 'C', 'H', 'H', 'H', 'C', 'H', 'H', 'H', 'C', 'H', 'H', 'H', 'C', 'C', 'H', 'H', 'H', 'C', 'H', 'H', 'H', 'C', 'H', 'H', 'H']
Ligand atom label:  1  Ligand atom A nbo:  1.03655
Ligand atom label:  21  Ligand atom B nbo:  1.3325
Atom_a:  21 Atom_b:  1
C:\Users\George\Desktop\Research_UCLA\CIC\Computational Work\Project cluster version 2\project_catalyst_repurposing\structures_ligand_id\pd_me2_structures\ligand_xyz\ligand-036-p-p-15-ligand_xyz.txt
Ending node: 0
Starting node: 11
(-1.475244, 0.081943, -0.606711)   11
(-0.61561, 1.704144, -0.343227)   2
(0.615443, 1.704158, 0.343114)   1
(1.475357, 0.081935, 0.606485)   0
ligand-037-p-o-1

C:\Users\George\AppData\Local\Temp\ipykernel_7832\386804788.py:583: DeprecationWarning:

to_plotly_figure is deprecated and will be removed in version 4.0.0. Use MolGraph.to_plotly() instead.

C:\Users\George\AppData\Local\Temp\ipykernel_7832\386804788.py:589: DeprecationWarning:

to_networkx_graph is deprecated and will be removed in version 4.0.0. Use MolGraph.to_networkx() instead.

Pd number index:  1
['C', 'Pd', 'C', 'H', 'H', 'H', 'C', 'H', 'H', 'H', 'P', 'H', 'H', 'C', 'C', 'C', 'C', 'H', 'C', 'H', 'C', 'H', 'H', 'H', 'C', 'C', 'C', 'C', 'H', 'C', 'H', 'C', 'H', 'H', 'H', 'C', 'C', 'C', 'H', 'H', 'C', 'H', 'H', 'H', 'H', 'N', 'C', 'O', 'C', 'C', 'H', 'H', 'H', 'C', 'H', 'H', 'H', 'C', 'H', 'H', 'H', 'H']
Ligand atom label:  11  Ligand atom B nbo:  0.98445
Ligand atom label:  48  Ligand atom A nbo:  -0.60364
Atom_a:  11 Atom_b:  48
C:\Users\George\Desktop\Research_UCLA\CIC\Computational Work\Project cluster version 2\project_catalyst_repurposing\structures_ligand_id\pd_me2_structures\ligand_xyz\ligand-037-p-o-1-ligand_xyz.txt
Starting node: 1
Ending node: 38
(1.048111, 0.137193, -0.236826)   1
(0.540626, 0.961321, -1.827533)   0
(-0.8716, 0.630575, -2.317181)   26
(-1.911578, 0.775064, -1.279625)   36
(-2.316314, -0.334191, -0.595097)   37
(-1.756737, -1.410319, -0.803697)   38
ligand-038-p-o-2

C:\Users\George\AppData\Local\Temp\ipykernel_7832\386804788.py:583: DeprecationWarning:

to_plotly_figure is deprecated and will be removed in version 4.0.0. Use MolGraph.to_plotly() instead.

C:\Users\George\AppData\Local\Temp\ipykernel_7832\386804788.py:589: DeprecationWarning:

to_networkx_graph is deprecated and will be removed in version 4.0.0. Use MolGraph.to_networkx() instead.

Pd number index:  45
['P', 'C', 'C', 'S', 'O', 'O', 'O', 'C', 'C', 'C', 'C', 'C', 'C', 'H', 'H', 'H', 'H', 'C', 'C', 'C', 'C', 'C', 'H', 'H', 'H', 'H', 'O', 'C', 'C', 'C', 'C', 'C', 'O', 'H', 'H', 'H', 'H', 'C', 'H', 'H', 'H', 'C', 'H', 'H', 'H', 'Pd', 'C', 'H', 'H', 'H', 'C', 'H', 'H', 'H']
Ligand atom label:  1  Ligand atom B nbo:  0.98035
Ligand atom label:  5  Ligand atom A nbo:  -0.94348
Atom_a:  1 Atom_b:  5
C:\Users\George\Desktop\Research_UCLA\CIC\Computational Work\Project cluster version 2\project_catalyst_repurposing\structures_ligand_id\pd_me2_structures\ligand_xyz\ligand-038-p-o-2-ligand_xyz.txt
Starting node: 0
Ending node: 4
(-0.222319, 0.252902, 0.223948)   0
(1.156771, 0.39995, 1.455329)   1
(2.49421, 0.389677, 1.025629)   2
(2.927483, 0.336775, -0.736465)   3
(2.469384, -1.019009, -1.188504)   4
ligand-039-p-o-3

C:\Users\George\AppData\Local\Temp\ipykernel_7832\386804788.py:583: DeprecationWarning:

to_plotly_figure is deprecated and will be removed in version 4.0.0. Use MolGraph.to_plotly() instead.

C:\Users\George\AppData\Local\Temp\ipykernel_7832\386804788.py:589: DeprecationWarning:

to_networkx_graph is deprecated and will be removed in version 4.0.0. Use MolGraph.to_networkx() instead.

Pd number index:  14
['P', 'C', 'C', 'S', 'O', 'O', 'O', 'C', 'C', 'C', 'C', 'H', 'H', 'H', 'Pd', 'C', 'H', 'H', 'H', 'C', 'H', 'H', 'H', 'C', 'C', 'H', 'H', 'H', 'C', 'H', 'H', 'H', 'C', 'H', 'H', 'H', 'C', 'C', 'C', 'C', 'H', 'C', 'H', 'C', 'H', 'H', 'H', 'H']
Ligand atom label:  1  Ligand atom B nbo:  1.01756
Ligand atom label:  5  Ligand atom A nbo:  -0.93815
Atom_a:  1 Atom_b:  5
C:\Users\George\Desktop\Research_UCLA\CIC\Computational Work\Project cluster version 2\project_catalyst_repurposing\structures_ligand_id\pd_me2_structures\ligand_xyz\ligand-039-p-o-3-ligand_xyz.txt

C:\Users\George\AppData\Local\Temp\ipykernel_7832\386804788.py:583: DeprecationWarning:

to_plotly_figure is deprecated and will be removed in version 4.0.0. Use MolGraph.to_plotly() instead.

C:\Users\George\AppData\Local\Temp\ipykernel_7832\386804788.py:589: DeprecationWarning:

to_networkx_graph is deprecated and will be removed in version 4.0.0. Use MolGraph.to_networkx() instead.

Starting node: 0
Ending node: 4
(-0.186915, -0.642001, 0.525937)   0
(-1.205382, 0.855197, 0.977937)   1
(-1.101229, 2.023095, 0.188846)   2
(0.074676, 2.196003, -1.188536)   3
(1.395151, 2.073812, -0.483955)   4
ligand-041-p-o-5
Pd number index:  15
['P', 'C', 'C', 'S', 'O', 'O', 'O', 'C', 'C', 'C', 'C', 'H', 'H', 'H', 'H', 'Pd', 'C', 'H', 'H', 'H', 'C', 'H', 'H', 'H', 'C', 'C', 'C', 'C', 'H', 'C', 'H', 'C', 'H', 'H', 'H', 'C', 'C', 'C', 'C', 'C', 'H', 'C', 'H', 'H', 'H', 'C', 'C', 'C', 'C', 'C', 'C', 'H', 'H', 'H', 'O', 'O', 'C', 'H', 'H', 'H', 'C', 'H', 'H', 'H']
Ligand atom label:  1  Ligand atom B nbo:  0.96908
Ligand atom label:  5  Ligand atom A nbo:  -0.94476
Atom_a:  1 Atom_b:  5
C:\Users\George\Desktop\Research_UCLA\CIC\Computational Work\Project cluster version 2\project_catalyst_repurposing\structures_ligand_id\pd_me2_structures\ligand_xyz\ligand-041-p-o-5-ligand_xyz.txt

C:\Users\George\AppData\Local\Temp\ipykernel_7832\386804788.py:583: DeprecationWarning:

to_plotly_figure is deprecated and will be removed in version 4.0.0. Use MolGraph.to_plotly() instead.

C:\Users\George\AppData\Local\Temp\ipykernel_7832\386804788.py:589: DeprecationWarning:

to_networkx_graph is deprecated and will be removed in version 4.0.0. Use MolGraph.to_networkx() instead.

Starting node: 0
Ending node: 4
(0.515307, 0.66327, -0.034186)   0
(1.798115, 0.132632, 1.212313)   1
(2.62141, -0.981064, 0.9627)   2
(2.522485, -1.953533, -0.568474)   3
(1.109556, -2.474607, -0.570452)   4
ligand-042-p-p-16
Pd number index:  1
['C', 'Pd', 'C', 'H', 'H', 'H', 'C', 'H', 'H', 'H', 'H', 'H', 'C', 'H', 'H', 'P', 'P', 'C', 'C', 'C', 'C', 'H', 'C', 'C', 'H', 'H', 'H', 'C', 'C', 'C', 'C', 'H', 'C', 'C', 'H', 'H', 'H', 'C', 'C', 'C', 'C', 'H', 'C', 'C', 'H', 'H', 'H', 'C', 'C', 'C', 'C', 'H', 'C', 'C', 'H', 'H', 'H', 'O', 'O', 'O', 'O', 'C', 'H', 'H', 'H', 'C', 'H', 'H', 'H', 'C', 'H', 'H', 'H', 'C', 'H', 'H', 'H']
Ligand atom label:  16  Ligand atom A nbo:  1.19129
Ligand atom label:  17  Ligand atom B nbo:  1.02643
Atom_a:  16 Atom_b:  17
C:\Users\George\Desktop\Research_UCLA\CIC\Computational Work\Project cluster version 2\project_catalyst_repurposing\structures_ligand_id\pd_me2_structures\ligand_xyz\ligand-042-p-p-16-ligand_xyz.txt
Starting node: 6
Ending node: 7
(-1.505672, -0.486489, -0.492221)   6
(-0.453887, -0.992087, -1.944018)   0
(0.73879, -0.049071, -2.054279)   3
(1.74735, -0.10532, -0.491511)   7
ligand-043-p-p-17

C:\Users\George\AppData\Local\Temp\ipykernel_7832\386804788.py:583: DeprecationWarning:

to_plotly_figure is deprecated and will be removed in version 4.0.0. Use MolGraph.to_plotly() instead.

C:\Users\George\AppData\Local\Temp\ipykernel_7832\386804788.py:589: DeprecationWarning:

to_networkx_graph is deprecated and will be removed in version 4.0.0. Use MolGraph.to_networkx() instead.

Pd number index:  2
['P', 'C', 'Pd', 'C', 'H', 'H', 'H', 'C', 'H', 'H', 'H', 'P', 'H', 'H', 'C', 'H', 'C', 'H', 'H', 'H', 'C', 'C', 'C', 'C', 'H', 'C', 'C', 'H', 'H', 'H', 'C', 'C', 'C', 'C', 'H', 'C', 'C', 'H', 'H', 'H', 'C', 'C', 'C', 'C', 'H', 'C', 'C', 'H', 'H', 'H', 'C', 'C', 'C', 'C', 'C', 'H', 'C', 'H', 'H', 'H', 'O', 'O', 'C', 'H', 'H', 'H', 'C', 'H', 'H', 'H', 'O', 'O', 'C', 'H', 'H', 'H', 'C', 'H', 'H', 'H']
Ligand atom label:  1  Ligand atom A nbo:  1.019
Ligand atom label:  12  Ligand atom B nbo:  1.32683
Atom_a:  12 Atom_b:  1
C:\Users\George\Desktop\Research_UCLA\CIC\Computational Work\Project cluster version 2\project_catalyst_repurposing\structures_ligand_id\pd_me2_structures\ligand_xyz\ligand-043-p-p-17-ligand_xyz.txt
Ending node: 0
Starting node: 2
(1.499306, 0.234049, 0.659398)   2
(0.95113, 0.34154, 2.451229)   1
(-0.262238, 1.249653, 2.672074)   5
(-1.618881, 0.605623, 2.394904)   7
(-1.80042, -0.047738, 0.661106)   0
ligand-044-p-p-18

C:\Users\George\AppData\Local\Temp\ipykernel_7832\386804788.py:583: DeprecationWarning:

to_plotly_figure is deprecated and will be removed in version 4.0.0. Use MolGraph.to_plotly() instead.

C:\Users\George\AppData\Local\Temp\ipykernel_7832\386804788.py:589: DeprecationWarning:

to_networkx_graph is deprecated and will be removed in version 4.0.0. Use MolGraph.to_networkx() instead.

Pd number index:  2
['P', 'C', 'Pd', 'C', 'H', 'H', 'H', 'C', 'H', 'H', 'H', 'P', 'H', 'H', 'C', 'H', 'C', 'H', 'H', 'H', 'C', 'H', 'H', 'C', 'C', 'C', 'H', 'C', 'H', 'H', 'C', 'H', 'H', 'C', 'H', 'H', 'H', 'H', 'H', 'H', 'C', 'C', 'C', 'H', 'C', 'H', 'H', 'C', 'H', 'H', 'C', 'H', 'H', 'H', 'H', 'H', 'H', 'C', 'C', 'C', 'H', 'C', 'H', 'H', 'C', 'H', 'H', 'C', 'H', 'H', 'H', 'H', 'H', 'H', 'C', 'C', 'C', 'H', 'C', 'H', 'H', 'C', 'H', 'H', 'C', 'H', 'H', 'H', 'H', 'H', 'H']
Ligand atom label:  1  Ligand atom A nbo:  0.9527
Ligand atom label:  12  Ligand atom B nbo:  1.15433
Atom_a:  12 Atom_b:  1
C:\Users\George\Desktop\Research_UCLA\CIC\Computational Work\Project cluster version 2\project_catalyst_repurposing\structures_ligand_id\pd_me2_structures\ligand_xyz\ligand-044-p-p-18-ligand_xyz.txt
Ending node: 0
Starting node: 2
(-1.83152, 0.51888, 0.574553)   2
(-1.900957, 1.043011, 2.358059)   1
(-0.812601, 0.563284, 3.312667)   5
(0.63407, 0.880896, 2.92172)   7
(1.387676, -0.251442, 2.203301)   11
(1.77693, 0.040247, 0.400604)   0
ligand-046-p-p-20

C:\Users\George\AppData\Local\Temp\ipykernel_7832\386804788.py:583: DeprecationWarning:

to_plotly_figure is deprecated and will be removed in version 4.0.0. Use MolGraph.to_plotly() instead.

C:\Users\George\AppData\Local\Temp\ipykernel_7832\386804788.py:589: DeprecationWarning:

to_networkx_graph is deprecated and will be removed in version 4.0.0. Use MolGraph.to_networkx() instead.

Pd number index:  1
['C', 'Pd', 'C', 'H', 'H', 'H', 'C', 'H', 'H', 'H', 'H', 'H', 'C', 'H', 'H', 'P', 'P', 'C', 'C', 'C', 'C', 'H', 'C', 'C', 'H', 'H', 'C', 'C', 'C', 'C', 'H', 'C', 'C', 'H', 'H', 'C', 'C', 'C', 'C', 'H', 'C', 'C', 'H', 'H', 'C', 'C', 'C', 'C', 'H', 'C', 'C', 'H', 'H', 'H', 'O', 'C', 'H', 'H', 'H', 'H', 'O', 'C', 'H', 'H', 'H', 'H', 'O', 'C', 'H', 'H', 'H', 'H', 'O', 'C', 'H', 'H', 'H']
Ligand atom label:  16  Ligand atom A nbo:  0.95921
Ligand atom label:  17  Ligand atom B nbo:  0.97815
Atom_a:  17 Atom_b:  16
C:\Users\George\Desktop\Research_UCLA\CIC\Computational Work\Project cluster version 2\project_catalyst_repurposing\structures_ligand_id\pd_me2_structures\ligand_xyz\ligand-046-p-p-20-ligand_xyz.txt
Ending node: 6
Starting node: 7
(-1.453015, -0.452395, -0.496343)   7
(-0.46509, -0.751789, -2.048525)   3
(0.774744, 0.132188, -2.028996)   0
(1.731969, -0.132408, -0.449448)   6
ligand-047-p-p-21

C:\Users\George\AppData\Local\Temp\ipykernel_7832\386804788.py:583: DeprecationWarning:

to_plotly_figure is deprecated and will be removed in version 4.0.0. Use MolGraph.to_plotly() instead.

C:\Users\George\AppData\Local\Temp\ipykernel_7832\386804788.py:589: DeprecationWarning:

to_networkx_graph is deprecated and will be removed in version 4.0.0. Use MolGraph.to_networkx() instead.

Pd number index:  2
['P', 'C', 'Pd', 'C', 'H', 'H', 'H', 'C', 'H', 'H', 'H', 'P', 'H', 'H', 'C', 'H', 'C', 'H', 'H', 'H', 'C', 'C', 'C', 'C', 'H', 'C', 'C', 'H', 'H', 'C', 'C', 'C', 'C', 'H', 'C', 'C', 'H', 'H', 'C', 'C', 'C', 'C', 'H', 'C', 'C', 'H', 'H', 'C', 'C', 'C', 'C', 'C', 'H', 'C', 'H', 'H', 'H', 'H', 'H', 'H', 'O', 'O', 'O', 'O', 'C', 'H', 'H', 'H', 'C', 'H', 'H', 'H', 'C', 'H', 'H', 'H', 'C', 'H', 'H', 'H']
Ligand atom label:  1  Ligand atom B nbo:  1.01167
Ligand atom label:  12  Ligand atom A nbo:  1.32163
Atom_a:  12 Atom_b:  1
C:\Users\George\Desktop\Research_UCLA\CIC\Computational Work\Project cluster version 2\project_catalyst_repurposing\structures_ligand_id\pd_me2_structures\ligand_xyz\ligand-047-p-p-21-ligand_xyz.txt
Ending node: 0
Starting node: 2
(1.79195, -0.303477, 0.547254)   2
(1.363931, -0.5862, 2.332629)   1
(0.191141, 0.261697, 2.826868)   5
(-1.19302, -0.271897, 2.464682)   7
(-1.678518, -0.252584, 0.656723)   0
ligand-048-p-p-22

C:\Users\George\AppData\Local\Temp\ipykernel_7832\386804788.py:583: DeprecationWarning:

to_plotly_figure is deprecated and will be removed in version 4.0.0. Use MolGraph.to_plotly() instead.

C:\Users\George\AppData\Local\Temp\ipykernel_7832\386804788.py:589: DeprecationWarning:

to_networkx_graph is deprecated and will be removed in version 4.0.0. Use MolGraph.to_networkx() instead.

Pd number index:  2
['P', 'C', 'Pd', 'C', 'H', 'H', 'H', 'C', 'H', 'H', 'H', 'P', 'H', 'H', 'C', 'H', 'C', 'H', 'H', 'H', 'C', 'C', 'C', 'C', 'H', 'C', 'C', 'H', 'C', 'C', 'C', 'C', 'H', 'C', 'C', 'H', 'C', 'C', 'C', 'C', 'H', 'C', 'C', 'H', 'C', 'C', 'C', 'C', 'C', 'H', 'C', 'H', 'H', 'H', 'H', 'H', 'H', 'H', 'H', 'H', 'O', 'O', 'O', 'O', 'C', 'H', 'H', 'H', 'C', 'H', 'H', 'H', 'C', 'H', 'H', 'H', 'C', 'H', 'H', 'H']
Ligand atom label:  1  Ligand atom B nbo:  1.00726
Ligand atom label:  12  Ligand atom A nbo:  1.31983
Atom_a:  12 Atom_b:  1
C:\Users\George\Desktop\Research_UCLA\CIC\Computational Work\Project cluster version 2\project_catalyst_repurposing\structures_ligand_id\pd_me2_structures\ligand_xyz\ligand-048-p-p-22-ligand_xyz.txt
Ending node: 0
Starting node: 2
(-1.750518, -0.390352, -0.375564)   2
(-1.288465, -0.651502, -2.157399)   1
(-0.098704, 0.183701, -2.629089)   5
(1.274378, -0.340577, -2.213308)   7
(1.71296, -0.314523, -0.39382)   0
ligand-053-p-c-18

C:\Users\George\AppData\Local\Temp\ipykernel_7832\386804788.py:583: DeprecationWarning:

to_plotly_figure is deprecated and will be removed in version 4.0.0. Use MolGraph.to_plotly() instead.

C:\Users\George\AppData\Local\Temp\ipykernel_7832\386804788.py:589: DeprecationWarning:

to_networkx_graph is deprecated and will be removed in version 4.0.0. Use MolGraph.to_networkx() instead.

Pd number index:  44
['C', 'C', 'C', 'C', 'C', 'C', 'H', 'H', 'H', 'C', 'H', 'H', 'H', 'C', 'H', 'H', 'H', 'H', 'P', 'C', 'C', 'C', 'C', 'H', 'C', 'H', 'C', 'H', 'H', 'H', 'C', 'C', 'C', 'C', 'H', 'C', 'C', 'H', 'H', 'H', 'C', 'C', 'H', 'H', 'Pd', 'C', 'N', 'N', 'C', 'C', 'C', 'C', 'H', 'C', 'H', 'C', 'H', 'H', 'H']
Ligand atom label:  19  Ligand atom B nbo:  1.37417
Ligand atom label:  46  Ligand atom A nbo:  0.57325
Atom_a:  19 Atom_b:  46
C:\Users\George\Desktop\Research_UCLA\CIC\Computational Work\Project cluster version 2\project_catalyst_repurposing\structures_ligand_id\pd_me2_structures\ligand_xyz\ligand-053-p-c-18-ligand_xyz.txt
Starting node: 10
Ending node: 36
(-1.391397, -0.304422, 0.135489)   10
(-1.707925, 0.975164, -1.174177)   1
(-0.654974, 1.796209, -1.614847)   0
(0.648474, 1.706738, -1.033616)   37
(1.328984, 0.544567, -0.801923)   36
ligand-054-p-c-19

C:\Users\George\AppData\Local\Temp\ipykernel_7832\386804788.py:583: DeprecationWarning:

to_plotly_figure is deprecated and will be removed in version 4.0.0. Use MolGraph.to_plotly() instead.

C:\Users\George\AppData\Local\Temp\ipykernel_7832\386804788.py:589: DeprecationWarning:

to_networkx_graph is deprecated and will be removed in version 4.0.0. Use MolGraph.to_networkx() instead.

Pd number index:  44
['C', 'C', 'C', 'C', 'C', 'C', 'H', 'H', 'H', 'C', 'H', 'H', 'H', 'C', 'H', 'H', 'H', 'H', 'P', 'C', 'C', 'C', 'C', 'H', 'C', 'H', 'C', 'H', 'H', 'H', 'C', 'C', 'C', 'C', 'H', 'C', 'C', 'H', 'H', 'H', 'C', 'C', 'H', 'H', 'Pd', 'C', 'N', 'N', 'C', 'C', 'C', 'C', 'C', 'C', 'H', 'H', 'C', 'H', 'H', 'H', 'C', 'H', 'H', 'H', 'C', 'H', 'H', 'H', 'H']
Ligand atom label:  19  Ligand atom B nbo:  1.37803
Ligand atom label:  46  Ligand atom A nbo:  0.56012
Atom_a:  19 Atom_b:  46
C:\Users\George\Desktop\Research_UCLA\CIC\Computational Work\Project cluster version 2\project_catalyst_repurposing\structures_ligand_id\pd_me2_structures\ligand_xyz\ligand-054-p-c-19-ligand_xyz.txt
Starting node: 10
Ending node: 36
(1.690908, 0.250905, -0.059104)   10
(2.107217, -1.541502, -0.231825)   1
(1.094954, -2.516522, -0.138507)   0
(-0.237961, -2.184505, 0.243064)   37
(-0.977656, -1.13213, -0.23292)   36
ligand-055-p-c-20

C:\Users\George\AppData\Local\Temp\ipykernel_7832\386804788.py:583: DeprecationWarning:

to_plotly_figure is deprecated and will be removed in version 4.0.0. Use MolGraph.to_plotly() instead.

C:\Users\George\AppData\Local\Temp\ipykernel_7832\386804788.py:589: DeprecationWarning:

to_networkx_graph is deprecated and will be removed in version 4.0.0. Use MolGraph.to_networkx() instead.

Pd number index:  44
['C', 'C', 'C', 'C', 'C', 'C', 'H', 'H', 'H', 'C', 'H', 'H', 'H', 'C', 'H', 'H', 'H', 'H', 'P', 'C', 'C', 'C', 'C', 'H', 'C', 'H', 'C', 'H', 'H', 'H', 'C', 'C', 'C', 'C', 'H', 'C', 'C', 'H', 'H', 'H', 'C', 'C', 'H', 'H', 'Pd', 'C', 'N', 'N', 'C', 'C', 'C', 'C', 'C', 'C', 'H', 'H', 'C', 'H', 'C', 'H', 'C', 'H', 'H', 'H', 'C', 'H', 'H', 'H', 'C', 'H', 'H', 'H', 'C', 'H', 'H', 'H', 'H', 'H']
Ligand atom label:  19  Ligand atom B nbo:  1.38202
Ligand atom label:  46  Ligand atom A nbo:  0.55738
Atom_a:  19 Atom_b:  46
C:\Users\George\Desktop\Research_UCLA\CIC\Computational Work\Project cluster version 2\project_catalyst_repurposing\structures_ligand_id\pd_me2_structures\ligand_xyz\ligand-055-p-c-20-ligand_xyz.txt
Starting node: 10
Ending node: 36
(1.922513, -0.028126, -0.153203)   10
(2.053716, -1.622236, 0.769301)   1
(0.90742, -2.187982, 1.35874)   0
(-0.337777, -1.494745, 1.390046)   37
(-0.935635, -0.860188, 0.330396)   36
ligand-056-p-c-21

C:\Users\George\AppData\Local\Temp\ipykernel_7832\386804788.py:583: DeprecationWarning:

to_plotly_figure is deprecated and will be removed in version 4.0.0. Use MolGraph.to_plotly() instead.

C:\Users\George\AppData\Local\Temp\ipykernel_7832\386804788.py:589: DeprecationWarning:

to_networkx_graph is deprecated and will be removed in version 4.0.0. Use MolGraph.to_networkx() instead.

Pd number index:  68
['C', 'C', 'C', 'C', 'C', 'C', 'H', 'H', 'H', 'H', 'H', 'H', 'H', 'H', 'H', 'H', 'C', 'C', 'C', 'N', 'N', 'C', 'H', 'C', 'H', 'H', 'H', 'C', 'H', 'H', 'H', 'H', 'C', 'C', 'C', 'C', 'H', 'C', 'H', 'C', 'H', 'H', 'H', 'N', 'H', 'P', 'C', 'C', 'C', 'C', 'H', 'C', 'H', 'C', 'H', 'H', 'H', 'C', 'C', 'C', 'C', 'H', 'C', 'H', 'C', 'H', 'H', 'H', 'Pd', 'C', 'H', 'H', 'H', 'C', 'H', 'H', 'H']
Ligand atom label:  18  Ligand atom A nbo:  0.24784
Ligand atom label:  46  Ligand atom B nbo:  1.06543
Atom_a:  46 Atom_b:  18
C:\Users\George\Desktop\Research_UCLA\CIC\Computational Work\Project cluster version 2\project_catalyst_repurposing\structures_ligand_id\pd_me2_structures\ligand_xyz\ligand-056-p-c-21-ligand_xyz.txt
Ending node: 17
Starting node: 45
(1.848079, -0.5164, 0.08957)   45
(0.784494, -1.835725, 0.437988)   43
(-0.602772, -1.446838, 0.684877)   1
(-1.27244, -1.157569, -0.689765)   0
(-1.89373, 0.174662, -0.642185)   19
(-1.020066, 1.225654, -0.714031)   17
ligand-057-p-c-22

C:\Users\George\AppData\Local\Temp\ipykernel_7832\386804788.py:583: DeprecationWarning:

to_plotly_figure is deprecated and will be removed in version 4.0.0. Use MolGraph.to_plotly() instead.

C:\Users\George\AppData\Local\Temp\ipykernel_7832\386804788.py:589: DeprecationWarning:

to_networkx_graph is deprecated and will be removed in version 4.0.0. Use MolGraph.to_networkx() instead.

Pd number index:  62
['C', 'C', 'C', 'C', 'C', 'C', 'H', 'H', 'H', 'H', 'H', 'H', 'H', 'H', 'H', 'H', 'C', 'C', 'C', 'N', 'N', 'C', 'H', 'C', 'H', 'H', 'H', 'C', 'H', 'H', 'H', 'H', 'C', 'C', 'C', 'C', 'H', 'C', 'H', 'C', 'H', 'H', 'H', 'N', 'H', 'P', 'C', 'C', 'C', 'C', 'C', 'C', 'H', 'H', 'C', 'C', 'C', 'C', 'C', 'C', 'H', 'H', 'Pd', 'C', 'H', 'H', 'H', 'C', 'H', 'H', 'H', 'C', 'H', 'H', 'H', 'C', 'H', 'H', 'H', 'C', 'H', 'H', 'H', 'C', 'H', 'H', 'H', 'C', 'H', 'H', 'H', 'C', 'H', 'H', 'H']
Ligand atom label:  18  Ligand atom A nbo:  0.25533
Ligand atom label:  46  Ligand atom B nbo:  1.06731
Atom_a:  46 Atom_b:  18
C:\Users\George\Desktop\Research_UCLA\CIC\Computational Work\Project cluster version 2\project_catalyst_repurposing\structures_ligand_id\pd_me2_structures\ligand_xyz\ligand-057-p-c-22-ligand_xyz.txt
Ending node: 17
Starting node: 45
(1.497854, -0.130801, 0.068916)   45
(0.568438, -1.400003, 0.834548)   43
(-0.830821, -1.049671, 1.067615)   1
(-1.622762, -1.311929, -0.238304)   0
(-2.443566, -0.132571, -0.550959)   19
(-1.753438, 0.943598, -1.032576)   17
ligand-058-p-c-23

C:\Users\George\AppData\Local\Temp\ipykernel_7832\386804788.py:583: DeprecationWarning:

to_plotly_figure is deprecated and will be removed in version 4.0.0. Use MolGraph.to_plotly() instead.

C:\Users\George\AppData\Local\Temp\ipykernel_7832\386804788.py:589: DeprecationWarning:

to_networkx_graph is deprecated and will be removed in version 4.0.0. Use MolGraph.to_networkx() instead.

Pd number index:  60
['C', 'C', 'C', 'C', 'C', 'C', 'H', 'H', 'H', 'H', 'H', 'H', 'H', 'H', 'H', 'H', 'C', 'C', 'C', 'N', 'N', 'C', 'H', 'H', 'C', 'C', 'C', 'C', 'H', 'C', 'H', 'C', 'H', 'H', 'H', 'N', 'H', 'P', 'C', 'C', 'C', 'C', 'H', 'C', 'H', 'C', 'H', 'H', 'H', 'C', 'C', 'C', 'C', 'H', 'C', 'H', 'C', 'H', 'H', 'H', 'Pd', 'C', 'H', 'H', 'H', 'C', 'H', 'H', 'H', 'C', 'C', 'C', 'C', 'H', 'C', 'H', 'C', 'H', 'H', 'H', 'C', 'C', 'C', 'C', 'H', 'C', 'H', 'C', 'H', 'H', 'H']
Ligand atom label:  18  Ligand atom A nbo:  0.25458
Ligand atom label:  38  Ligand atom B nbo:  1.06562
Atom_a:  38 Atom_b:  18
C:\Users\George\Desktop\Research_UCLA\CIC\Computational Work\Project cluster version 2\project_catalyst_repurposing\structures_ligand_id\pd_me2_structures\ligand_xyz\ligand-058-p-c-23-ligand_xyz.txt
Ending node: 17
Starting node: 37
(-2.468315, 0.148268, -0.092262)   37
(-2.194364, 1.740541, 0.52001)   35
(-0.805917, 2.065545, 0.835482)   1
(-0.057879, 2.344532, -0.502191)   0
(1.131546, 1.482033, -0.569449)   19
(0.883639, 0.169953, -0.856406)   17
ligand-059-p-c-24

C:\Users\George\AppData\Local\Temp\ipykernel_7832\386804788.py:583: DeprecationWarning:

to_plotly_figure is deprecated and will be removed in version 4.0.0. Use MolGraph.to_plotly() instead.

C:\Users\George\AppData\Local\Temp\ipykernel_7832\386804788.py:589: DeprecationWarning:

to_networkx_graph is deprecated and will be removed in version 4.0.0. Use MolGraph.to_networkx() instead.

Pd number index:  54
['C', 'C', 'C', 'C', 'C', 'C', 'H', 'H', 'H', 'H', 'H', 'H', 'H', 'H', 'H', 'H', 'C', 'C', 'C', 'N', 'N', 'C', 'H', 'H', 'C', 'C', 'C', 'C', 'H', 'C', 'H', 'C', 'H', 'H', 'H', 'N', 'H', 'P', 'C', 'C', 'C', 'C', 'C', 'C', 'H', 'H', 'C', 'C', 'C', 'C', 'C', 'C', 'H', 'H', 'Pd', 'C', 'H', 'H', 'H', 'C', 'H', 'H', 'H', 'C', 'H', 'H', 'H', 'C', 'H', 'H', 'H', 'C', 'H', 'H', 'H', 'C', 'H', 'H', 'H', 'C', 'H', 'H', 'H', 'C', 'H', 'H', 'H', 'C', 'C', 'C', 'C', 'H', 'C', 'H', 'C', 'H', 'H', 'H', 'C', 'C', 'C', 'C', 'H', 'C', 'H', 'C', 'H', 'H', 'H']
Ligand atom label:  18  Ligand atom A nbo:  0.24455
Ligand atom label:  38  Ligand atom B nbo:  1.05928
Atom_a:  38 Atom_b:  18
C:\Users\George\Desktop\Research_UCLA\CIC\Computational Work\Project cluster version 2\project_catalyst_repurposing\structures_ligand_id\pd_me2_structures\ligand_xyz\ligand-059-p-c-24-ligand_xyz.txt
Ending node: 17
Starting node: 37
(-2.234088, -0.139461, -0.058723)   37
(-1.957587, 1.54385, 0.334113)   35
(-0.579395, 1.932349, 0.637822)   1
(0.173729, 2.216176, -0.689878)   0
(1.474033, 1.523843, -0.661441)   19
(1.413749, 0.167588, -0.802888)   17
ligand-060-p-c-25

C:\Users\George\AppData\Local\Temp\ipykernel_7832\386804788.py:583: DeprecationWarning:

to_plotly_figure is deprecated and will be removed in version 4.0.0. Use MolGraph.to_plotly() instead.

C:\Users\George\AppData\Local\Temp\ipykernel_7832\386804788.py:589: DeprecationWarning:

to_networkx_graph is deprecated and will be removed in version 4.0.0. Use MolGraph.to_networkx() instead.

Pd number index:  58
['C', 'C', 'C', 'C', 'C', 'C', 'H', 'H', 'H', 'H', 'H', 'H', 'H', 'H', 'H', 'H', 'C', 'C', 'C', 'N', 'N', 'H', 'C', 'C', 'C', 'C', 'H', 'C', 'H', 'C', 'H', 'H', 'H', 'N', 'H', 'P', 'C', 'C', 'C', 'C', 'H', 'C', 'H', 'C', 'H', 'H', 'H', 'C', 'C', 'C', 'C', 'H', 'C', 'H', 'C', 'H', 'H', 'H', 'Pd', 'C', 'H', 'H', 'H', 'C', 'H', 'H', 'H', 'C', 'H', 'H', 'C', 'H', 'H', 'C', 'H', 'H', 'H']
Ligand atom label:  18  Ligand atom A nbo:  0.25111
Ligand atom label:  36  Ligand atom B nbo:  1.0652
Atom_a:  36 Atom_b:  18
C:\Users\George\Desktop\Research_UCLA\CIC\Computational Work\Project cluster version 2\project_catalyst_repurposing\structures_ligand_id\pd_me2_structures\ligand_xyz\ligand-060-p-c-25-ligand_xyz.txt
Ending node: 17
Starting node: 35
(1.715202, -0.624165, 0.17267)   35
(0.549394, -1.715972, 0.829453)   33
(-0.827098, -1.230261, 0.911445)   1
(-1.439119, -1.215709, -0.523017)   0
(-1.928114, 0.145245, -0.798244)   19
(-0.94822, 1.061942, -1.068633)   17
ligand-071-n-n-2
Pd number index:  0
['Pd', 'C', 'H', 'H', 'H', 'C', 'H', 'H', 'H', 'C', 'C', 'C', 'C', 'C', 'H', 'C', 'H', 'C', 'H', 'H', 'C', 'C', 'H', 'C', 'H', 'H', 'H', 'N', 'N']
Ligand atom label:  28  Ligand atom A nbo:  -0.49319
Ligand atom label:  29  Ligand atom B nbo:  -0.49167
Atom_a:  29 Atom_b:  28
C:\Users\George\Desktop\Research_UCLA\CIC\Computational Work\Project cluster version 2\project_catalyst_repurposing\structures_ligand_id\pd_me2_structures\ligand_xyz\ligand-071-n-n-2-ligand_xyz.txt

C:\Users\George\AppData\Local\Temp\ipykernel_7832\386804788.py:583: DeprecationWarning:

to_plotly_figure is deprecated and will be removed in version 4.0.0. Use MolGraph.to_plotly() instead.

C:\Users\George\AppData\Local\Temp\ipykernel_7832\386804788.py:589: DeprecationWarning:

to_networkx_graph is deprecated and will be removed in version 4.0.0. Use MolGraph.to_networkx() instead.

C:\Users\George\AppData\Local\Temp\ipykernel_7832\386804788.py:583: DeprecationWarning:

to_plotly_figure is deprecated and will be removed in version 4.0.0. Use MolGraph.to_plotly() instead.

C:\Users\George\AppData\Local\Temp\ipykernel_7832\386804788.py:589: DeprecationWarning:

to_networkx_graph is deprecated and will be removed in version 4.0.0. Use MolGraph.to_networkx() instead.

Ending node: 18
Starting node: 19
(0.496438, -1.303878, -0.004097)   19
(1.60875, -0.545482, 0.000573)   3
(1.411633, 0.925083, -0.000106)   0
(0.138758, 1.360507, 0.004304)   18
ligand-072-n-n-3
Pd number index:  0
['Pd', 'C', 'H', 'H', 'H', 'C', 'H', 'H', 'H', 'C', 'C', 'C', 'C', 'C', 'H', 'C', 'H', 'C', 'H', 'C', 'C', 'H', 'C', 'H', 'H', 'N', 'N', 'C', 'C', 'C', 'H', 'H', 'H', 'C', 'H', 'H', 'H', 'C', 'H', 'H', 'H', 'C', 'H', 'H', 'H', 'C', 'H', 'H', 'H', 'C', 'H', 'H', 'H']
Ligand atom label:  26  Ligand atom A nbo:  -0.50041
Ligand atom label:  27  Ligand atom B nbo:  -0.50035
Atom_a:  27 Atom_b:  26
C:\Users\George\Desktop\Research_UCLA\CIC\Computational Work\Project cluster version 2\project_catalyst_repurposing\structures_ligand_id\pd_me2_structures\ligand_xyz\ligand-072-n-n-3-ligand_xyz.txt

C:\Users\George\AppData\Local\Temp\ipykernel_7832\386804788.py:583: DeprecationWarning:

to_plotly_figure is deprecated and will be removed in version 4.0.0. Use MolGraph.to_plotly() instead.

C:\Users\George\AppData\Local\Temp\ipykernel_7832\386804788.py:589: DeprecationWarning:

to_networkx_graph is deprecated and will be removed in version 4.0.0. Use MolGraph.to_networkx() instead.

Ending node: 16
Starting node: 17
(1.306787, -1.080549, -0.006161)   17
(0.76016, 0.151054, -0.001185)   3
(-0.72416, 0.215672, 0.000997)   0
(-1.371929, -0.96462, 0.005653)   16
ligand-073-n-o-1
Pd number index:  43
['N', 'C', 'H', 'C', 'C', 'C', 'C', 'H', 'C', 'C', 'H', 'H', 'H', 'O', 'C', 'C', 'C', 'C', 'C', 'C', 'H', 'H', 'H', 'C', 'H', 'C', 'H', 'H', 'H', 'C', 'H', 'H', 'H', 'C', 'H', 'C', 'H', 'H', 'H', 'C', 'H', 'H', 'H', 'Pd', 'C', 'H', 'H', 'H', 'C', 'H', 'H', 'H']
Ligand atom label:  1  Ligand atom B nbo:  -0.54332
Ligand atom label:  14  Ligand atom A nbo:  -0.66761
Atom_a:  1 Atom_b:  14
C:\Users\George\Desktop\Research_UCLA\CIC\Computational Work\Project cluster version 2\project_catalyst_repurposing\structures_ligand_id\pd_me2_structures\ligand_xyz\ligand-073-n-o-1-ligand_xyz.txt
Starting node: 0
Ending node: 13
(-0.121194, -0.38551, -0.195439)   0
(0.748988, -1.334727, -0.310492)   1
(2.176731, -1.285293, -0.18716)   3
(2.934227, -0.063275, 0.016793)   5
(2.438832, 1.08646, 0.156915)   13
ligand-074-n-o-2
Pd number index:  42
['N', 'C', 'H', 'C', 'C', 'C', 'C', 'H', 'C', 'C', 'H', 'H', 'O', 'C', 'C', 'C', 'C', 'C', 'C', 'H', 'H', 'H', 'C', 'H', 'C', 'H', 'H', 'H', 'C', 'H', 'H', 'H', 'C', 'H', 'C', 'H', 'H', 'H', 'C', 'H', 'H', 'H', 'Pd', 'C', 'H', 'H', 'H', 'C', 'H', 'H', 'H', 'C', 'C', 'H', 'H', 'H', 'C', 'H', 'H', 'H', 'C', 'H', 'H', 'H']

C:\Users\George\AppData\Local\Temp\ipykernel_7832\386804788.py:583: DeprecationWarning:

to_plotly_figure is deprecated and will be removed in version 4.0.0. Use MolGraph.to_plotly() instead.

C:\Users\George\AppData\Local\Temp\ipykernel_7832\386804788.py:589: DeprecationWarning:

to_networkx_graph is deprecated and will be removed in version 4.0.0. Use MolGraph.to_networkx() instead.

Ligand atom label:  1  Ligand atom B nbo:  -0.54589
Ligand atom label:  13  Ligand atom A nbo:  -0.68295
Atom_a:  1 Atom_b:  13
C:\Users\George\Desktop\Research_UCLA\CIC\Computational Work\Project cluster version 2\project_catalyst_repurposing\structures_ligand_id\pd_me2_structures\ligand_xyz\ligand-074-n-o-2-ligand_xyz.txt
Starting node: 0
Ending node: 12
(0.91982, 0.446798, -0.199155)   0
(0.199564, 1.512532, -0.329458)   1
(-1.224681, 1.683928, -0.270639)   3
(-2.166065, 0.593474, -0.114171)   5
(-1.813009, -0.61315, 0.000212)   12
ligand-075-n-o-3

C:\Users\George\AppData\Local\Temp\ipykernel_7832\386804788.py:583: DeprecationWarning:

to_plotly_figure is deprecated and will be removed in version 4.0.0. Use MolGraph.to_plotly() instead.

C:\Users\George\AppData\Local\Temp\ipykernel_7832\386804788.py:589: DeprecationWarning:

to_networkx_graph is deprecated and will be removed in version 4.0.0. Use MolGraph.to_networkx() instead.

Pd number index:  42
['N', 'C', 'H', 'C', 'C', 'C', 'C', 'H', 'C', 'C', 'H', 'H', 'O', 'C', 'C', 'C', 'C', 'C', 'C', 'H', 'H', 'H', 'C', 'H', 'C', 'H', 'H', 'H', 'C', 'H', 'H', 'H', 'C', 'H', 'C', 'H', 'H', 'H', 'C', 'H', 'H', 'H', 'Pd', 'C', 'H', 'H', 'H', 'C', 'H', 'H', 'H', 'C', 'C', 'C', 'C', 'H', 'C', 'H', 'C', 'H', 'H', 'H']
Ligand atom label:  1  Ligand atom B nbo:  -0.54231
Ligand atom label:  13  Ligand atom A nbo:  -0.66694
Atom_a:  1 Atom_b:  13
C:\Users\George\Desktop\Research_UCLA\CIC\Computational Work\Project cluster version 2\project_catalyst_repurposing\structures_ligand_id\pd_me2_structures\ligand_xyz\ligand-075-n-o-3-ligand_xyz.txt

C:\Users\George\AppData\Local\Temp\ipykernel_7832\386804788.py:583: DeprecationWarning:

to_plotly_figure is deprecated and will be removed in version 4.0.0. Use MolGraph.to_plotly() instead.

C:\Users\George\AppData\Local\Temp\ipykernel_7832\386804788.py:589: DeprecationWarning:

to_networkx_graph is deprecated and will be removed in version 4.0.0. Use MolGraph.to_networkx() instead.

Starting node: 0
Ending node: 12
(1.243369, 0.461125, -0.158079)   0
(0.638886, 1.602214, -0.149641)   1
(-0.763263, 1.90278, -0.055203)   3
(-1.807221, 0.894986, -0.055834)   5
(-1.591117, -0.341257, -0.147274)   12
ligand-076-n-o-4
Pd number index:  42
['N', 'C', 'H', 'C', 'C', 'C', 'C', 'H', 'C', 'C', 'H', 'H', 'O', 'C', 'C', 'C', 'C', 'C', 'C', 'H', 'H', 'H', 'C', 'H', 'C', 'H', 'H', 'H', 'C', 'H', 'H', 'H', 'C', 'H', 'C', 'H', 'H', 'H', 'C', 'H', 'H', 'H', 'Pd', 'C', 'H', 'H', 'H', 'C', 'H', 'H', 'H', 'C', 'C', 'C', 'C', 'C', 'C', 'H', 'C', 'C', 'H', 'H', 'H', 'C', 'C', 'C', 'C', 'C', 'H', 'C', 'H', 'H', 'H', 'H']
Ligand atom label:  1  Ligand atom B nbo:  -0.54099
Ligand atom label:  13  Ligand atom A nbo:  -0.6802
Atom_a:  1 Atom_b:  13
C:\Users\George\Desktop\Research_UCLA\CIC\Computational Work\Project cluster version 2\project_catalyst_repurposing\structures_ligand_id\pd_me2_structures\ligand_xyz\ligand-076-n-o-4-ligand_xyz.txt
Starting node: 0
Ending node: 12
(2.445806, 0.296904, -0.33994)   0
(1.936946, 1.257626, -1.035892)   1
(0.559834, 1.603262, -1.265122)   3
(-0.563181, 0.843415, -0.746161)   5
(-0.450926, -0.183074, -0.029884)   12
ligand-077-n-o-5

C:\Users\George\AppData\Local\Temp\ipykernel_7832\386804788.py:583: DeprecationWarning:

to_plotly_figure is deprecated and will be removed in version 4.0.0. Use MolGraph.to_plotly() instead.

C:\Users\George\AppData\Local\Temp\ipykernel_7832\386804788.py:589: DeprecationWarning:

to_networkx_graph is deprecated and will be removed in version 4.0.0. Use MolGraph.to_networkx() instead.

Pd number index:  42
['N', 'C', 'H', 'C', 'C', 'C', 'C', 'H', 'C', 'C', 'H', 'H', 'O', 'C', 'C', 'C', 'C', 'C', 'C', 'H', 'H', 'H', 'C', 'H', 'C', 'H', 'H', 'H', 'C', 'H', 'H', 'H', 'C', 'H', 'C', 'H', 'H', 'H', 'C', 'H', 'H', 'H', 'Pd', 'C', 'H', 'H', 'H', 'C', 'H', 'H', 'H', 'C', 'C', 'C', 'C', 'C', 'H', 'C', 'C', 'C', 'H', 'H', 'H', 'H', 'C', 'C', 'C', 'C', 'H', 'C', 'C', 'H', 'H', 'H']
Ligand atom label:  1  Ligand atom B nbo:  -0.54455
Ligand atom label:  13  Ligand atom A nbo:  -0.67182
Atom_a:  1 Atom_b:  13
C:\Users\George\Desktop\Research_UCLA\CIC\Computational Work\Project cluster version 2\project_catalyst_repurposing\structures_ligand_id\pd_me2_structures\ligand_xyz\ligand-077-n-o-5-ligand_xyz.txt

C:\Users\George\AppData\Local\Temp\ipykernel_7832\386804788.py:583: DeprecationWarning:

to_plotly_figure is deprecated and will be removed in version 4.0.0. Use MolGraph.to_plotly() instead.

C:\Users\George\AppData\Local\Temp\ipykernel_7832\386804788.py:589: DeprecationWarning:

to_networkx_graph is deprecated and will be removed in version 4.0.0. Use MolGraph.to_networkx() instead.

Starting node: 0
Ending node: 12
(2.149319, -0.572356, 0.172286)   0
(1.601929, -1.308266, 1.07922)   1
(0.219475, -1.392677, 1.468948)   3
(-0.860666, -0.775814, 0.7248)   5
(-0.717413, -0.149915, -0.357568)   12
ligand-078-n-o-6
Pd number index:  42
['N', 'C', 'H', 'C', 'C', 'C', 'C', 'H', 'C', 'C', 'H', 'H', 'O', 'C', 'C', 'C', 'C', 'C', 'C', 'H', 'H', 'H', 'C', 'H', 'C', 'H', 'H', 'H', 'C', 'H', 'H', 'H', 'C', 'H', 'C', 'H', 'H', 'H', 'C', 'H', 'H', 'H', 'Pd', 'C', 'H', 'H', 'H', 'C', 'H', 'H', 'H', 'O', 'C', 'H', 'H', 'H']
Ligand atom label:  1  Ligand atom B nbo:  -0.54049
Ligand atom label:  13  Ligand atom A nbo:  -0.67305
Atom_a:  1 Atom_b:  13
C:\Users\George\Desktop\Research_UCLA\CIC\Computational Work\Project cluster version 2\project_catalyst_repurposing\structures_ligand_id\pd_me2_structures\ligand_xyz\ligand-078-n-o-6-ligand_xyz.txt
Starting node: 0
Ending node: 12
(-0.432624, -0.287881, -0.160803)   0
(0.711244, -0.887688, -0.21328)   1
(2.031547, -0.342648, -0.072166)   3
(2.313464, 1.071366, 0.081622)   5
(1.45079, 1.990383, 0.155943)   12
ligand-079-n-o-7

C:\Users\George\AppData\Local\Temp\ipykernel_7832\386804788.py:583: DeprecationWarning:

to_plotly_figure is deprecated and will be removed in version 4.0.0. Use MolGraph.to_plotly() instead.

C:\Users\George\AppData\Local\Temp\ipykernel_7832\386804788.py:589: DeprecationWarning:

to_networkx_graph is deprecated and will be removed in version 4.0.0. Use MolGraph.to_networkx() instead.

Pd number index:  42
['N', 'C', 'H', 'C', 'C', 'C', 'C', 'H', 'C', 'C', 'H', 'H', 'O', 'C', 'C', 'C', 'C', 'C', 'C', 'H', 'H', 'H', 'C', 'H', 'C', 'H', 'H', 'H', 'C', 'H', 'H', 'H', 'C', 'H', 'C', 'H', 'H', 'H', 'C', 'H', 'H', 'H', 'Pd', 'C', 'H', 'H', 'H', 'C', 'H', 'H', 'H', 'N', 'O', 'O']
Ligand atom label:  1  Ligand atom B nbo:  -0.53449
Ligand atom label:  13  Ligand atom A nbo:  -0.62209
Atom_a:  1 Atom_b:  13
C:\Users\George\Desktop\Research_UCLA\CIC\Computational Work\Project cluster version 2\project_catalyst_repurposing\structures_ligand_id\pd_me2_structures\ligand_xyz\ligand-079-n-o-7-ligand_xyz.txt

C:\Users\George\AppData\Local\Temp\ipykernel_7832\386804788.py:583: DeprecationWarning:

to_plotly_figure is deprecated and will be removed in version 4.0.0. Use MolGraph.to_plotly() instead.

C:\Users\George\AppData\Local\Temp\ipykernel_7832\386804788.py:589: DeprecationWarning:

to_networkx_graph is deprecated and will be removed in version 4.0.0. Use MolGraph.to_networkx() instead.

Starting node: 0
Ending node: 12
(-0.529108, -0.255129, -0.156846)   0
(0.654158, -0.759618, -0.200867)   1
(1.930112, -0.100031, -0.063085)   3
(2.099525, 1.344934, 0.065724)   5
(1.164447, 2.173504, 0.112336)   12
ligand-080-p-o-6
Pd number index:  28
['P', 'C', 'C', 'C', 'C', 'C', 'C', 'C', 'C', 'H', 'H', 'C', 'C', 'C', 'C', 'C', 'H', 'H', 'H', 'H', 'C', 'C', 'C', 'C', 'C', 'H', 'H', 'H', 'Pd', 'H', 'O', 'C', 'C', 'H', 'H', 'H', 'C', 'H', 'H', 'H', 'C', 'H', 'H', 'H', 'H', 'H', 'H', 'C', 'H', 'H', 'H', 'C', 'H', 'H', 'H']
Ligand atom label:  1  Ligand atom B nbo:  1.00904
Ligand atom label:  31  Ligand atom A nbo:  -0.70804
Atom_a:  1 Atom_b:  31
C:\Users\George\Desktop\Research_UCLA\CIC\Computational Work\Project cluster version 2\project_catalyst_repurposing\structures_ligand_id\pd_me2_structures\ligand_xyz\ligand-080-p-o-6-ligand_xyz.txt
Starting node: 0
Ending node: 29
(0.90968, 0.028392, 0.00727)   0
(-0.509298, 1.140905, -0.176631)   1
(-1.786801, 0.498662, -0.016493)   2
(-1.89619, -0.750428, 0.226032)   29
ligand-081-p-o-7

C:\Users\George\AppData\Local\Temp\ipykernel_7832\386804788.py:583: DeprecationWarning:

to_plotly_figure is deprecated and will be removed in version 4.0.0. Use MolGraph.to_plotly() instead.

C:\Users\George\AppData\Local\Temp\ipykernel_7832\386804788.py:589: DeprecationWarning:

to_networkx_graph is deprecated and will be removed in version 4.0.0. Use MolGraph.to_networkx() instead.

Pd number index:  28
['P', 'C', 'C', 'C', 'C', 'C', 'C', 'C', 'C', 'H', 'H', 'C', 'C', 'C', 'C', 'C', 'H', 'H', 'H', 'H', 'C', 'C', 'C', 'C', 'C', 'H', 'H', 'H', 'Pd', 'H', 'O', 'C', 'C', 'H', 'H', 'H', 'C', 'H', 'H', 'H', 'C', 'H', 'H', 'H', 'H', 'H', 'C', 'H', 'H', 'H', 'C', 'H', 'H', 'H', 'C', 'C', 'C', 'C', 'C', 'C', 'H', 'H', 'H', 'O', 'O', 'C', 'H', 'H', 'H', 'C', 'H', 'H', 'H']
Ligand atom label:  1  Ligand atom B nbo:  1.01136
Ligand atom label:  31  Ligand atom A nbo:  -0.71325
Atom_a:  1 Atom_b:  31
C:\Users\George\Desktop\Research_UCLA\CIC\Computational Work\Project cluster version 2\project_catalyst_repurposing\structures_ligand_id\pd_me2_structures\ligand_xyz\ligand-081-p-o-7-ligand_xyz.txt
Starting node: 0
Ending node: 29
(-1.08664, -0.480388, -0.204324)   0
(0.45625, -0.872256, -1.078322)   1
(1.613964, -0.989401, -0.234014)   2
(1.567478, -0.763342, 1.021185)   29
ligand-082-p-o-8

C:\Users\George\AppData\Local\Temp\ipykernel_7832\386804788.py:583: DeprecationWarning:

to_plotly_figure is deprecated and will be removed in version 4.0.0. Use MolGraph.to_plotly() instead.

C:\Users\George\AppData\Local\Temp\ipykernel_7832\386804788.py:589: DeprecationWarning:

to_networkx_graph is deprecated and will be removed in version 4.0.0. Use MolGraph.to_networkx() instead.

Pd number index:  28
['P', 'C', 'C', 'C', 'C', 'C', 'C', 'C', 'C', 'H', 'H', 'C', 'C', 'C', 'C', 'C', 'H', 'H', 'H', 'H', 'C', 'C', 'C', 'C', 'C', 'H', 'H', 'H', 'Pd', 'H', 'O', 'C', 'C', 'H', 'H', 'H', 'C', 'H', 'H', 'H', 'C', 'H', 'H', 'H', 'H', 'H', 'C', 'H', 'H', 'H', 'C', 'H', 'H', 'H', 'C', 'C', 'C', 'C', 'C', 'C', 'H', 'H', 'H', 'H', 'H']
Ligand atom label:  1  Ligand atom B nbo:  1.0318
Ligand atom label:  31  Ligand atom A nbo:  -0.69335
Atom_a:  1 Atom_b:  31
C:\Users\George\Desktop\Research_UCLA\CIC\Computational Work\Project cluster version 2\project_catalyst_repurposing\structures_ligand_id\pd_me2_structures\ligand_xyz\ligand-082-p-o-8-ligand_xyz.txt

C:\Users\George\AppData\Local\Temp\ipykernel_7832\386804788.py:583: DeprecationWarning:

to_plotly_figure is deprecated and will be removed in version 4.0.0. Use MolGraph.to_plotly() instead.

C:\Users\George\AppData\Local\Temp\ipykernel_7832\386804788.py:589: DeprecationWarning:

to_networkx_graph is deprecated and will be removed in version 4.0.0. Use MolGraph.to_networkx() instead.

Starting node: 0
Ending node: 29
(1.137368, -0.181328, 0.048452)   0
(-0.238911, -0.194052, 1.227722)   1
(-1.46715, -0.711651, 0.688678)   2
(-1.558698, -1.129985, -0.514858)   29
ligand-083-p-o-9
Pd number index:  28
['P', 'C', 'C', 'C', 'C', 'C', 'C', 'C', 'C', 'H', 'H', 'C', 'C', 'C', 'C', 'C', 'H', 'H', 'H', 'H', 'C', 'C', 'C', 'C', 'C', 'H', 'H', 'H', 'Pd', 'H', 'O', 'C', 'C', 'H', 'H', 'H', 'C', 'H', 'H', 'H', 'C', 'H', 'H', 'H', 'H', 'C', 'H', 'H', 'H', 'C', 'H', 'H', 'H', 'C', 'C', 'C', 'C', 'C', 'C', 'H', 'H', 'H', 'H', 'H', 'C', 'C', 'C', 'C', 'H', 'C', 'H', 'C', 'H', 'H', 'H']
Ligand atom label:  1  Ligand atom B nbo:  1.03174
Ligand atom label:  31  Ligand atom A nbo:  -0.696
Atom_a:  1 Atom_b:  31
C:\Users\George\Desktop\Research_UCLA\CIC\Computational Work\Project cluster version 2\project_catalyst_repurposing\structures_ligand_id\pd_me2_structures\ligand_xyz\ligand-083-p-o-9-ligand_xyz.txt
Starting node: 0
Ending node: 29
(-0.543698, 0.377092, -0.400595)   0
(1.117654, 0.677634, -1.098699)   1
(2.046051, -0.39998, -0.908809)   2
(1.693323, -1.505049, -0.37632)   29
ligand-084-p-o-10
Pd number index:  27
['P', 'C', 'C', 'C', 'C', 'C', 'C', 'C', 'C', 'H', 'H', 'C', 'C', 'C', 'C', 'C', 'H', 'H', 'H', 'C', 'C', 'C', 'C', 'C', 'H', 'H', 'H', 'Pd', 'O', 'H', 'C', 'H', 'H', 'H', 'C', 'H', 'H', 'H', 'O', 'O', 'C', 'H', 'H', 'H', 'C', 'H', 'H', 'H', 'O', 'C', 'H', 'H', 'H', 'O', 'C', 'H', 'H', 'H', 'C', 'C', 'H', 'H', 'H', 'C', 'H', 'H', 'H', 'C', 'H', 'H', 'H']

C:\Users\George\AppData\Local\Temp\ipykernel_7832\386804788.py:583: DeprecationWarning:

to_plotly_figure is deprecated and will be removed in version 4.0.0. Use MolGraph.to_plotly() instead.

C:\Users\George\AppData\Local\Temp\ipykernel_7832\386804788.py:589: DeprecationWarning:

to_networkx_graph is deprecated and will be removed in version 4.0.0. Use MolGraph.to_networkx() instead.

Ligand atom label:  1  Ligand atom B nbo:  1.02701
Ligand atom label:  29  Ligand atom A nbo:  -0.70866
Atom_a:  1 Atom_b:  29
C:\Users\George\Desktop\Research_UCLA\CIC\Computational Work\Project cluster version 2\project_catalyst_repurposing\structures_ligand_id\pd_me2_structures\ligand_xyz\ligand-084-p-o-10-ligand_xyz.txt
Starting node: 0
Ending node: 27
(-0.472808, -0.069702, 0.101675)   0
(0.966694, 0.381424, 1.109339)   1
(2.225001, 0.041461, 0.508489)   2
(2.301158, -0.594782, -0.600842)   27

C:\Users\George\AppData\Local\Temp\ipykernel_7832\386804788.py:583: DeprecationWarning:

to_plotly_figure is deprecated and will be removed in version 4.0.0. Use MolGraph.to_plotly() instead.

C:\Users\George\AppData\Local\Temp\ipykernel_7832\386804788.py:589: DeprecationWarning:

to_networkx_graph is deprecated and will be removed in version 4.0.0. Use MolGraph.to_networkx() instead.

ligand-085-p-o-11
Pd number index:  15
['P', 'C', 'C', 'S', 'O', 'O', 'O', 'C', 'C', 'C', 'C', 'H', 'H', 'H', 'H', 'Pd', 'C', 'H', 'H', 'H', 'C', 'H', 'H', 'H', 'C', 'C', 'C', 'C', 'C', 'H', 'C', 'H', 'H', 'H', 'C', 'C', 'C', 'C', 'C', 'C', 'H', 'H', 'H', 'O', 'O', 'C', 'H', 'H', 'H', 'C', 'H', 'H', 'H', 'C', 'C', 'C', 'H', 'C', 'H', 'H', 'C', 'H', 'H', 'C', 'H', 'H', 'H', 'H', 'H', 'H']
Ligand atom label:  1  Ligand atom B nbo:  0.9725
Ligand atom label:  5  Ligand atom A nbo:  -0.94164
Atom_a:  1 Atom_b:  5
C:\Users\George\Desktop\Research_UCLA\CIC\Computational Work\Project cluster version 2\project_catalyst_repurposing\structures_ligand_id\pd_me2_structures\ligand_xyz\ligand-085-p-o-11-ligand_xyz.txt
Starting node: 0
Ending node: 4
(0.450016, 0.572611, 0.077437)   0
(1.645062, -0.032127, 1.375813)   1
(2.537931, -1.089015, 1.107692)   2
(2.596361, -1.975, -0.47804)   3
(1.19476, -2.496305, -0.646016)   4
ligand-086-p-o-12
Pd number index:  14
['P', 'C', 'C', 'S', 'O', 'O', 'O', 'C', 'C', 'C', 'C', 'H', 'H', 'H', 'Pd', 'C', 'H', 'H', 'H', 'C', 'H', 'H', 'H', 'C', 'C', 'C', 'C', 'H', 'C', 'H', 'C', 'H', 'H', 'H', 'C', 'C', 'C', 'C', 'C', 'H', 'C', 'H', 'H', 'H', 'C', 'C', 'C', 'C', 'C', 'C', 'H', 'H', 'H', 'O', 'O', 'C', 'H', 'H', 'H', 'C', 'H', 'H', 'H', 'C', 'C', 'C', 'C', 'C', 'C', 'F', 'F', 'F', 'F', 'F']

C:\Users\George\AppData\Local\Temp\ipykernel_7832\386804788.py:583: DeprecationWarning:

to_plotly_figure is deprecated and will be removed in version 4.0.0. Use MolGraph.to_plotly() instead.

C:\Users\George\AppData\Local\Temp\ipykernel_7832\386804788.py:589: DeprecationWarning:

to_networkx_graph is deprecated and will be removed in version 4.0.0. Use MolGraph.to_networkx() instead.

Ligand atom label:  1  Ligand atom B nbo:  0.96979
Ligand atom label:  5  Ligand atom A nbo:  -0.93517
Atom_a:  1 Atom_b:  5
C:\Users\George\Desktop\Research_UCLA\CIC\Computational Work\Project cluster version 2\project_catalyst_repurposing\structures_ligand_id\pd_me2_structures\ligand_xyz\ligand-086-p-o-12-ligand_xyz.txt

C:\Users\George\AppData\Local\Temp\ipykernel_7832\386804788.py:583: DeprecationWarning:

to_plotly_figure is deprecated and will be removed in version 4.0.0. Use MolGraph.to_plotly() instead.

C:\Users\George\AppData\Local\Temp\ipykernel_7832\386804788.py:589: DeprecationWarning:

to_networkx_graph is deprecated and will be removed in version 4.0.0. Use MolGraph.to_networkx() instead.

Starting node: 0
Ending node: 4
(-1.318392, 0.944751, 0.099362)   0
(0.260138, 0.842681, 1.10572)   1
(1.486952, 0.459367, 0.522167)   2
(1.542072, 0.051635, -1.26164)   3
(0.608409, -1.118508, -1.370483)   4
ligand-087-p-o-13
Pd number index:  15
['P', 'C', 'C', 'S', 'O', 'O', 'O', 'C', 'C', 'C', 'C', 'H', 'H', 'H', 'H', 'Pd', 'C', 'H', 'H', 'H', 'C', 'H', 'H', 'H', 'C', 'C', 'C', 'C', 'C', 'H', 'C', 'H', 'H', 'H', 'C', 'C', 'C', 'C', 'C', 'C', 'H', 'H', 'H', 'O', 'O', 'C', 'H', 'H', 'H', 'C', 'H', 'H', 'H', 'C', 'C', 'H', 'H', 'H', 'C', 'H', 'H', 'H', 'C', 'H', 'H', 'H']
Ligand atom label:  1  Ligand atom B nbo:  0.98804
Ligand atom label:  5  Ligand atom A nbo:  -0.94041
Atom_a:  1 Atom_b:  5
C:\Users\George\Desktop\Research_UCLA\CIC\Computational Work\Project cluster version 2\project_catalyst_repurposing\structures_ligand_id\pd_me2_structures\ligand_xyz\ligand-087-p-o-13-ligand_xyz.txt
Starting node: 0
Ending node: 4
(0.439456, 0.819928, -0.748568)   0
(1.967121, 0.916794, 0.327075)   1
(2.805417, -0.185881, 0.581071)   2
(2.479653, -1.913534, 0.073322)   3
(1.022203, -2.11844, 0.373261)   4
ligand-088-p-o-14

C:\Users\George\AppData\Local\Temp\ipykernel_7832\386804788.py:583: DeprecationWarning:

to_plotly_figure is deprecated and will be removed in version 4.0.0. Use MolGraph.to_plotly() instead.

C:\Users\George\AppData\Local\Temp\ipykernel_7832\386804788.py:589: DeprecationWarning:

to_networkx_graph is deprecated and will be removed in version 4.0.0. Use MolGraph.to_networkx() instead.

Pd number index:  14
['P', 'C', 'C', 'S', 'O', 'O', 'O', 'C', 'C', 'C', 'C', 'H', 'H', 'H', 'Pd', 'C', 'H', 'H', 'H', 'C', 'H', 'H', 'H', 'C', 'C', 'C', 'C', 'H', 'C', 'H', 'C', 'H', 'H', 'H', 'C', 'C', 'C', 'C', 'C', 'H', 'C', 'H', 'H', 'H', 'C', 'C', 'C', 'C', 'C', 'C', 'H', 'H', 'H', 'O', 'O', 'C', 'H', 'H', 'H', 'C', 'H', 'H', 'H', 'Si', 'C', 'H', 'H', 'H', 'C', 'H', 'H', 'H', 'C', 'H', 'H', 'H']
Ligand atom label:  1  Ligand atom B nbo:  0.96603
Ligand atom label:  5  Ligand atom A nbo:  -0.93786
Atom_a:  1 Atom_b:  5
C:\Users\George\Desktop\Research_UCLA\CIC\Computational Work\Project cluster version 2\project_catalyst_repurposing\structures_ligand_id\pd_me2_structures\ligand_xyz\ligand-088-p-o-14-ligand_xyz.txt

C:\Users\George\AppData\Local\Temp\ipykernel_7832\386804788.py:583: DeprecationWarning:

to_plotly_figure is deprecated and will be removed in version 4.0.0. Use MolGraph.to_plotly() instead.

C:\Users\George\AppData\Local\Temp\ipykernel_7832\386804788.py:589: DeprecationWarning:

to_networkx_graph is deprecated and will be removed in version 4.0.0. Use MolGraph.to_networkx() instead.

Starting node: 0
Ending node: 4
(-0.513588, 0.951916, 0.009851)   0
(1.094347, 0.76432, 0.941326)   1
(2.205721, 0.091069, 0.400192)   2
(2.099186, -0.756597, -1.198793)   3
(0.881975, -1.627884, -1.132643)   4
ligand-089-p-o-15
Pd number index:  64
['P', 'O', 'P', 'N', 'C', 'C', 'C', 'C', 'C', 'C', 'H', 'H', 'H', 'H', 'H', 'C', 'C', 'C', 'C', 'C', 'C', 'H', 'H', 'H', 'H', 'H', 'C', 'C', 'C', 'C', 'H', 'C', 'H', 'C', 'H', 'H', 'C', 'C', 'C', 'C', 'C', 'C', 'H', 'H', 'C', 'H', 'H', 'H', 'O', 'H', 'C', 'C', 'C', 'C', 'C', 'C', 'H', 'H', 'H', 'C', 'H', 'H', 'H', 'O', 'Pd', 'H', 'H', 'H', 'C', 'H', 'H', 'H', 'C', 'H', 'H', 'H']
Ligand atom label:  1  Ligand atom B nbo:  1.17968
Ligand atom label:  2  Ligand atom A nbo:  -1.03962
Atom_a:  1 Atom_b:  2
C:\Users\George\Desktop\Research_UCLA\CIC\Computational Work\Project cluster version 2\project_catalyst_repurposing\structures_ligand_id\pd_me2_structures\ligand_xyz\ligand-089-p-o-15-ligand_xyz.txt
Starting node: 0
Ending node: 1
(-0.905411, 0.764687, 0.27269)   0
(0.730609, 0.111532, 0.373557)   3
(1.056041, -0.99432, -0.889)   2
(0.531395, -0.579383, -2.245736)   1
ligand-090-p-o-16

C:\Users\George\AppData\Local\Temp\ipykernel_7832\386804788.py:583: DeprecationWarning:

to_plotly_figure is deprecated and will be removed in version 4.0.0. Use MolGraph.to_plotly() instead.

C:\Users\George\AppData\Local\Temp\ipykernel_7832\386804788.py:589: DeprecationWarning:

to_networkx_graph is deprecated and will be removed in version 4.0.0. Use MolGraph.to_networkx() instead.

Pd number index:  54
['P', 'O', 'P', 'N', 'C', 'C', 'C', 'C', 'C', 'C', 'H', 'H', 'H', 'H', 'H', 'C', 'C', 'C', 'C', 'C', 'C', 'H', 'H', 'H', 'H', 'H', 'C', 'C', 'C', 'C', 'H', 'C', 'H', 'C', 'H', 'H', 'C', 'C', 'C', 'C', 'C', 'C', 'H', 'H', 'H', 'C', 'C', 'C', 'C', 'C', 'C', 'H', 'H', 'H', 'Pd', 'H', 'H', 'C', 'H', 'H', 'H', 'C', 'H', 'H', 'H', 'H', 'H', 'C', 'C', 'C', 'C', 'C', 'C', 'H', 'H', 'H', 'O', 'O', 'C', 'H', 'H', 'H', 'C', 'H', 'H', 'H']
Ligand atom label:  1  Ligand atom B nbo:  1.23016
Ligand atom label:  2  Ligand atom A nbo:  -0.9369
Atom_a:  1 Atom_b:  2
C:\Users\George\Desktop\Research_UCLA\CIC\Computational Work\Project cluster version 2\project_catalyst_repurposing\structures_ligand_id\pd_me2_structures\ligand_xyz\ligand-090-p-o-16-ligand_xyz.txt
Starting node: 0
Ending node: 1
(-0.60887, 0.849647, 0.373043)   0
(1.115469, 0.386619, 0.376042)   3
(1.566135, -0.840728, -0.724992)   2
(0.43142, -1.183775, -1.66211)   1
ligand-091-p-o-17

C:\Users\George\AppData\Local\Temp\ipykernel_7832\386804788.py:583: DeprecationWarning:

to_plotly_figure is deprecated and will be removed in version 4.0.0. Use MolGraph.to_plotly() instead.

C:\Users\George\AppData\Local\Temp\ipykernel_7832\386804788.py:589: DeprecationWarning:

to_networkx_graph is deprecated and will be removed in version 4.0.0. Use MolGraph.to_networkx() instead.

Pd number index:  54
['P', 'O', 'P', 'N', 'C', 'C', 'C', 'C', 'C', 'C', 'H', 'H', 'H', 'H', 'H', 'C', 'C', 'C', 'C', 'C', 'C', 'H', 'H', 'H', 'H', 'H', 'C', 'C', 'C', 'C', 'H', 'C', 'H', 'C', 'H', 'H', 'C', 'C', 'C', 'C', 'C', 'C', 'H', 'H', 'H', 'C', 'C', 'C', 'C', 'C', 'C', 'H', 'H', 'H', 'Pd', 'H', 'H', 'C', 'H', 'H', 'H', 'C', 'H', 'H', 'H', 'H', 'C', 'C', 'C', 'C', 'C', 'C', 'H', 'H', 'H', 'O', 'O', 'C', 'H', 'H', 'H', 'C', 'H', 'H', 'H', 'O', 'C', 'H', 'H', 'H']
Ligand atom label:  1  Ligand atom B nbo:  1.22972
Ligand atom label:  2  Ligand atom A nbo:  -0.93692
Atom_a:  1 Atom_b:  2
C:\Users\George\Desktop\Research_UCLA\CIC\Computational Work\Project cluster version 2\project_catalyst_repurposing\structures_ligand_id\pd_me2_structures\ligand_xyz\ligand-091-p-o-17-ligand_xyz.txt
Starting node: 0
Ending node: 1
(-0.57554, 0.942425, 0.151526)   0
(0.960271, 0.043146, 0.063568)   3
(0.905905, -1.460475, -0.744695)   2
(-0.435021, -1.685424, -1.40464)   1
ligand-092-p-o-13
Pd number index:  14
['P', 'C', 'C', 'S', 'O', 'O', 'O', 'C', 'C', 'C', 'C', 'H', 'H', 'H', 'Pd', 'C', 'H', 'H', 'H', 'C', 'H', 'H', 'H', 'C', 'C', 'C', 'C', 'C', 'H', 'C', 'H', 'H', 'H', 'C', 'H', 'H', 'H', 'C', 'C', 'C', 'C', 'C', 'H', 'C', 'H', 'H', 'H', 'O', 'O', 'C', 'H', 'H', 'H', 'C', 'H', 'H', 'H']

C:\Users\George\AppData\Local\Temp\ipykernel_7832\386804788.py:583: DeprecationWarning:

to_plotly_figure is deprecated and will be removed in version 4.0.0. Use MolGraph.to_plotly() instead.

C:\Users\George\AppData\Local\Temp\ipykernel_7832\386804788.py:589: DeprecationWarning:

to_networkx_graph is deprecated and will be removed in version 4.0.0. Use MolGraph.to_networkx() instead.

Ligand atom label:  1  Ligand atom B nbo:  0.9813
Ligand atom label:  5  Ligand atom A nbo:  -0.93944
Atom_a:  1 Atom_b:  5
C:\Users\George\Desktop\Research_UCLA\CIC\Computational Work\Project cluster version 2\project_catalyst_repurposing\structures_ligand_id\pd_me2_structures\ligand_xyz\ligand-092-p-o-13-ligand_xyz.txt
Starting node: 0
Ending node: 4
(0.211733, 0.179101, 0.337012)   0
(-1.322286, 1.014098, -0.276993)   1
(-2.447076, 0.235349, -0.596041)   2
(-2.447026, -1.567954, -0.408355)   3
(-1.47536, -2.04503, -1.448391)   4
ligand-093-p-o-19

C:\Users\George\AppData\Local\Temp\ipykernel_7832\386804788.py:583: DeprecationWarning:

to_plotly_figure is deprecated and will be removed in version 4.0.0. Use MolGraph.to_plotly() instead.

C:\Users\George\AppData\Local\Temp\ipykernel_7832\386804788.py:589: DeprecationWarning:

to_networkx_graph is deprecated and will be removed in version 4.0.0. Use MolGraph.to_networkx() instead.

Pd number index:  14
['P', 'C', 'C', 'S', 'O', 'O', 'O', 'C', 'C', 'C', 'C', 'H', 'H', 'H', 'Pd', 'C', 'H', 'H', 'H', 'C', 'H', 'H', 'H', 'C', 'H', 'H', 'H', 'C', 'C', 'C', 'H', 'C', 'H', 'H', 'C', 'H', 'H', 'C', 'H', 'H', 'H', 'H', 'H', 'H', 'C', 'C', 'C', 'H', 'C', 'H', 'H', 'C', 'H', 'H', 'C', 'H', 'H', 'H', 'H', 'H', 'H']
Ligand atom label:  1  Ligand atom B nbo:  0.99696
Ligand atom label:  5  Ligand atom A nbo:  -0.93977
Atom_a:  1 Atom_b:  5
C:\Users\George\Desktop\Research_UCLA\CIC\Computational Work\Project cluster version 2\project_catalyst_repurposing\structures_ligand_id\pd_me2_structures\ligand_xyz\ligand-093-p-o-19-ligand_xyz.txt

C:\Users\George\AppData\Local\Temp\ipykernel_7832\386804788.py:583: DeprecationWarning:

to_plotly_figure is deprecated and will be removed in version 4.0.0. Use MolGraph.to_plotly() instead.

C:\Users\George\AppData\Local\Temp\ipykernel_7832\386804788.py:589: DeprecationWarning:

to_networkx_graph is deprecated and will be removed in version 4.0.0. Use MolGraph.to_networkx() instead.

Starting node: 0
Ending node: 4
(0.368793, 0.105193, 0.061733)   0
(-0.986286, 1.270094, -0.474514)   1
(-2.334453, 0.8623, -0.406492)   2
(-2.844539, -0.786042, 0.162576)   3
(-2.221371, -1.71047, -0.840841)   4
ligand-094-p-o-20
Pd number index:  27
['P', 'C', 'C', 'C', 'C', 'C', 'C', 'C', 'C', 'H', 'H', 'C', 'C', 'C', 'C', 'C', 'H', 'H', 'H', 'C', 'C', 'C', 'C', 'C', 'H', 'H', 'H', 'Pd', 'O', 'C', 'H', 'H', 'H', 'C', 'H', 'H', 'H', 'O', 'O', 'O', 'O', 'C', 'H', 'H', 'H', 'C', 'H', 'H', 'H', 'C', 'H', 'H', 'H', 'C', 'H', 'H', 'H', 'P', 'C', 'C', 'C', 'C', 'C', 'C', 'H', 'H', 'H', 'C', 'C', 'C', 'C', 'C', 'C', 'H', 'H', 'H', 'O', 'O', 'C', 'H', 'H', 'H', 'C', 'H', 'H', 'H', 'O', 'O', 'C', 'H', 'H', 'H', 'C', 'H', 'H', 'H', 'C', 'C', 'H', 'H', 'H', 'C', 'H', 'H', 'H', 'C', 'H', 'H', 'H']
Ligand atom label:  1  Ligand atom B nbo:  1.02855
Ligand atom label:  29  Ligand atom A nbo:  -0.6795
Atom_a:  1 Atom_b:  29
C:\Users\George\Desktop\Research_UCLA\CIC\Computational Work\Project cluster version 2\project_catalyst_repurposing\structures_ligand_id\pd_me2_structures\ligand_xyz\ligand-094-p-o-20-ligand_xyz.txt
Starting node: 0
Ending node: 27
(2.352735, -0.064246, 0.042164)   0
(0.774521, 0.760955, -0.281572)   1
(-0.341798, 0.00299, 0.180838)   2
(-0.246023, -1.163771, 0.700328)   27
ligand-095-p-o-21

C:\Users\George\AppData\Local\Temp\ipykernel_7832\386804788.py:583: DeprecationWarning:

to_plotly_figure is deprecated and will be removed in version 4.0.0. Use MolGraph.to_plotly() instead.

C:\Users\George\AppData\Local\Temp\ipykernel_7832\386804788.py:589: DeprecationWarning:

to_networkx_graph is deprecated and will be removed in version 4.0.0. Use MolGraph.to_networkx() instead.

Pd number index:  24
['P', 'C', 'C', 'C', 'C', 'C', 'C', 'H', 'C', 'C', 'C', 'C', 'C', 'H', 'H', 'H', 'C', 'C', 'C', 'C', 'C', 'H', 'H', 'H', 'Pd', 'O', 'C', 'H', 'H', 'H', 'C', 'H', 'H', 'H', 'O', 'O', 'O', 'O', 'C', 'H', 'H', 'H', 'C', 'H', 'H', 'H', 'C', 'H', 'H', 'H', 'C', 'H', 'H', 'H', 'H', 'C', 'C', 'C', 'C', 'H', 'C', 'C', 'H', 'H', 'C', 'C', 'C', 'C', 'H', 'C', 'C', 'H', 'C', 'C', 'H', 'C', 'H', 'H', 'H', 'C', 'H', 'H', 'H', 'C', 'H', 'H', 'H', 'C', 'H', 'H', 'H', 'C', 'H', 'H', 'H', 'C', 'H', 'H', 'H']
Ligand atom label:  1  Ligand atom B nbo:  1.01533
Ligand atom label:  26  Ligand atom A nbo:  -0.68262
Atom_a:  1 Atom_b:  26
C:\Users\George\Desktop\Research_UCLA\CIC\Computational Work\Project cluster version 2\project_catalyst_repurposing\structures_ligand_id\pd_me2_structures\ligand_xyz\ligand-095-p-o-21-ligand_xyz.txt
Starting node: 0
Ending node: 24
(1.853486, -0.116997, 0.344361)   0
(0.965089, -1.680046, 0.50423)   1
(-0.446177, -1.51085, 0.616746)   2
(-0.998329, -0.395604, 0.858722)   24
ligand-096-p-o-22
Pd number index:  14
['P', 'C', 'C', 'S', 'O', 'O', 'O', 'C', 'C', 'C', 'C', 'H', 'H', 'H', 'Pd', 'C', 'H', 'H', 'H', 'C', 'H', 'H', 'H', 'C', 'C', 'C', 'C', 'C', 'C', 'H', 'H', 'O', 'C', 'H', 'H', 'H', 'C', 'C', 'C', 'H', 'C', 'H', 'H', 'C', 'H', 'C', 'H', 'H', 'H', 'H', 'H', 'C', 'H', 'C', 'H', 'H', 'H', 'C', 'H', 'H', 'H', 'C', 'H', 'H', 'H', 'O', 'C', 'H', 'H', 'H', 'O', 'C', 'H', 'H', 'H', 'H']

C:\Users\George\AppData\Local\Temp\ipykernel_7832\386804788.py:583: DeprecationWarning:

to_plotly_figure is deprecated and will be removed in version 4.0.0. Use MolGraph.to_plotly() instead.

C:\Users\George\AppData\Local\Temp\ipykernel_7832\386804788.py:589: DeprecationWarning:

to_networkx_graph is deprecated and will be removed in version 4.0.0. Use MolGraph.to_networkx() instead.

Ligand atom label:  1  Ligand atom B nbo:  0.98988
Ligand atom label:  5  Ligand atom A nbo:  -0.9178
Atom_a:  1 Atom_b:  5
C:\Users\George\Desktop\Research_UCLA\CIC\Computational Work\Project cluster version 2\project_catalyst_repurposing\structures_ligand_id\pd_me2_structures\ligand_xyz\ligand-096-p-o-22-ligand_xyz.txt

C:\Users\George\AppData\Local\Temp\ipykernel_7832\386804788.py:583: DeprecationWarning:

to_plotly_figure is deprecated and will be removed in version 4.0.0. Use MolGraph.to_plotly() instead.

C:\Users\George\AppData\Local\Temp\ipykernel_7832\386804788.py:589: DeprecationWarning:

to_networkx_graph is deprecated and will be removed in version 4.0.0. Use MolGraph.to_networkx() instead.

Starting node: 0
Ending node: 4
(0.13126, 0.157761, 0.09228)   0
(0.584112, -0.355341, 1.825097)   1
(1.378206, -1.488064, 2.077194)   2
(2.136368, -2.500988, 0.769922)   3
(0.983926, -2.994342, -0.059894)   4
ligand-097-p-o-23
Pd number index:  14
['P', 'C', 'C', 'S', 'O', 'O', 'O', 'C', 'C', 'C', 'C', 'H', 'H', 'H', 'Pd', 'C', 'H', 'H', 'H', 'C', 'H', 'H', 'H', 'C', 'C', 'C', 'C', 'C', 'C', 'H', 'H', 'C', 'C', 'C', 'H', 'C', 'H', 'H', 'C', 'H', 'C', 'H', 'H', 'H', 'H', 'H', 'C', 'H', 'C', 'H', 'H', 'H', 'C', 'H', 'H', 'H', 'C', 'H', 'H', 'H', 'H', 'H', 'C', 'C', 'C', 'C', 'C', 'C', 'H', 'H', 'H', 'O', 'O', 'C', 'H', 'H', 'H', 'C', 'H', 'H', 'H', 'H']
Ligand atom label:  1  Ligand atom B nbo:  0.92513
Ligand atom label:  5  Ligand atom A nbo:  -0.95137
Atom_a:  1 Atom_b:  5
C:\Users\George\Desktop\Research_UCLA\CIC\Computational Work\Project cluster version 2\project_catalyst_repurposing\structures_ligand_id\pd_me2_structures\ligand_xyz\ligand-097-p-o-23-ligand_xyz.txt
Starting node: 0
Ending node: 4
(0.34457, 0.311226, 0.432891)   0
(1.253215, -0.895384, 1.559072)   1
(1.858479, -2.087874, 1.110728)   2
(1.834627, -2.730347, -0.601187)   3
(0.405239, -2.5705, -1.034669)   4
ligand-098-p-o-24

C:\Users\George\AppData\Local\Temp\ipykernel_7832\386804788.py:583: DeprecationWarning:

to_plotly_figure is deprecated and will be removed in version 4.0.0. Use MolGraph.to_plotly() instead.

C:\Users\George\AppData\Local\Temp\ipykernel_7832\386804788.py:589: DeprecationWarning:

to_networkx_graph is deprecated and will be removed in version 4.0.0. Use MolGraph.to_networkx() instead.

Pd number index:  14
['P', 'C', 'C', 'S', 'O', 'O', 'O', 'C', 'C', 'C', 'C', 'H', 'H', 'H', 'Pd', 'C', 'H', 'H', 'H', 'C', 'H', 'H', 'H', 'C', 'C', 'C', 'C', 'C', 'C', 'H', 'C', 'C', 'C', 'H', 'C', 'H', 'H', 'C', 'H', 'C', 'H', 'H', 'H', 'H', 'H', 'C', 'H', 'C', 'H', 'H', 'H', 'C', 'H', 'H', 'H', 'C', 'H', 'H', 'H', 'H', 'H', 'H', 'C', 'C', 'C', 'C', 'H', 'C', 'H', 'C', 'H', 'H', 'H', 'H']
Ligand atom label:  1  Ligand atom B nbo:  0.97008
Ligand atom label:  5  Ligand atom A nbo:  -0.92128
Atom_a:  1 Atom_b:  5
C:\Users\George\Desktop\Research_UCLA\CIC\Computational Work\Project cluster version 2\project_catalyst_repurposing\structures_ligand_id\pd_me2_structures\ligand_xyz\ligand-098-p-o-24-ligand_xyz.txt
Starting node: 0
Ending node: 4
(0.288374, 0.335296, -0.312464)   0
(-0.480438, 0.597629, 1.35935)   1
(-0.893654, -0.480061, 2.166144)   2
(-0.599271, -2.238993, 1.776322)   3
(-1.181411, -2.468488, 0.412419)   4
ligand-099-p-o-25

C:\Users\George\AppData\Local\Temp\ipykernel_7832\386804788.py:583: DeprecationWarning:

to_plotly_figure is deprecated and will be removed in version 4.0.0. Use MolGraph.to_plotly() instead.

C:\Users\George\AppData\Local\Temp\ipykernel_7832\386804788.py:589: DeprecationWarning:

to_networkx_graph is deprecated and will be removed in version 4.0.0. Use MolGraph.to_networkx() instead.

Pd number index:  14
['P', 'C', 'C', 'S', 'O', 'O', 'O', 'C', 'C', 'C', 'C', 'H', 'H', 'H', 'Pd', 'C', 'H', 'H', 'H', 'C', 'H', 'H', 'H', 'C', 'C', 'C', 'C', 'C', 'C', 'H', 'C', 'C', 'C', 'H', 'C', 'H', 'H', 'C', 'H', 'C', 'H', 'H', 'H', 'H', 'H', 'C', 'H', 'C', 'H', 'H', 'H', 'C', 'H', 'H', 'H', 'C', 'H', 'H', 'H', 'H', 'H', 'H', 'C', 'C', 'C', 'C', 'C', 'C', 'H', 'H', 'H', 'F', 'F', 'H']
Ligand atom label:  1  Ligand atom B nbo:  0.96796
Ligand atom label:  5  Ligand atom A nbo:  -0.92429
Atom_a:  1 Atom_b:  5
C:\Users\George\Desktop\Research_UCLA\CIC\Computational Work\Project cluster version 2\project_catalyst_repurposing\structures_ligand_id\pd_me2_structures\ligand_xyz\ligand-099-p-o-25-ligand_xyz.txt
Starting node: 0
Ending node: 4
(0.429849, 0.310435, -0.289771)   0
(0.166504, 0.845168, 1.473118)   1
(-0.213446, -0.068266, 2.475707)   2
(-0.392096, -1.859812, 2.204938)   3
(-1.403492, -1.99575, 1.105255)   4
ligand-100-p-o-26

C:\Users\George\AppData\Local\Temp\ipykernel_7832\386804788.py:583: DeprecationWarning:

to_plotly_figure is deprecated and will be removed in version 4.0.0. Use MolGraph.to_plotly() instead.

C:\Users\George\AppData\Local\Temp\ipykernel_7832\386804788.py:589: DeprecationWarning:

to_networkx_graph is deprecated and will be removed in version 4.0.0. Use MolGraph.to_networkx() instead.

Pd number index:  2
['P', 'C', 'Pd', 'C', 'H', 'H', 'H', 'C', 'H', 'H', 'H', 'P', 'O', 'H', 'H', 'C', 'H', 'H', 'H', 'C', 'H', 'H', 'H', 'C', 'C', 'H', 'H', 'H', 'C', 'H', 'H', 'H', 'C', 'H', 'H', 'H', 'C', 'C', 'H', 'H', 'H', 'C', 'H', 'H', 'C', 'H', 'H', 'H', 'H']
Ligand atom label:  1  Ligand atom B nbo:  1.01549
Ligand atom label:  13  Ligand atom A nbo:  -1.01993
Atom_a:  1 Atom_b:  13
C:\Users\George\Desktop\Research_UCLA\CIC\Computational Work\Project cluster version 2\project_catalyst_repurposing\structures_ligand_id\pd_me2_structures\ligand_xyz\ligand-100-p-o-26-ligand_xyz.txt

C:\Users\George\AppData\Local\Temp\ipykernel_7832\386804788.py:583: DeprecationWarning:

to_plotly_figure is deprecated and will be removed in version 4.0.0. Use MolGraph.to_plotly() instead.

C:\Users\George\AppData\Local\Temp\ipykernel_7832\386804788.py:589: DeprecationWarning:

to_networkx_graph is deprecated and will be removed in version 4.0.0. Use MolGraph.to_networkx() instead.

Starting node: 0
Ending node: 3
(-0.903384, 0.159989, 0.031261)   0
(-0.232784, 1.877511, 0.40757)   1
(1.591557, 1.838463, 0.222245)   2
(2.059996, 0.790152, -0.766401)   3
ligand-101-p-o-27
Pd number index:  2
['P', 'C', 'Pd', 'C', 'H', 'H', 'H', 'C', 'H', 'H', 'H', 'P', 'O', 'H', 'H', 'C', 'C', 'C', 'C', 'H', 'H', 'H', 'C', 'H', 'H', 'H', 'C', 'H', 'H', 'H', 'C', 'C', 'H', 'H', 'H', 'C', 'H', 'H', 'C', 'H', 'H', 'H', 'C', 'H', 'H', 'H', 'C', 'H', 'H', 'H', 'C', 'H', 'H', 'H', 'C', 'H', 'H', 'H', 'C', 'H', 'H', 'H', 'C', 'H', 'H', 'H', 'H']
Ligand atom label:  1  Ligand atom B nbo:  1.02016
Ligand atom label:  13  Ligand atom A nbo:  -1.03361
Atom_a:  1 Atom_b:  13
C:\Users\George\Desktop\Research_UCLA\CIC\Computational Work\Project cluster version 2\project_catalyst_repurposing\structures_ligand_id\pd_me2_structures\ligand_xyz\ligand-101-p-o-27-ligand_xyz.txt
Starting node: 0
Ending node: 3
(-1.316258, 0.582534, 0.195808)   0
(0.376817, 1.253835, 0.720864)   1
(1.748085, 0.223818, 0.020324)   2
(1.237145, -0.618007, -1.141502)   3
ligand-102-p-o-28
Pd number index:  6
['P', 'C', 'C', 'C', 'C', 'H', 'Pd', 'O', 'C', 'H', 'H', 'H', 'C', 'H', 'H', 'H', 'H', 'C', 'C', 'C', 'C', 'H', 'C', 'C', 'H', 'H', 'C', 'C', 'C', 'C', 'H', 'C', 'H', 'C', 'H', 'H', 'H', 'C', 'C', 'C', 'C', 'H', 'C', 'H', 'C', 'H', 'H', 'H', 'H']
Ligand atom label:  1  Ligand atom B nbo:  0.99789
Ligand atom label:  8  Ligand atom A nbo:  -0.69179
Atom_a:  1 Atom_b:  8

C:\Users\George\AppData\Local\Temp\ipykernel_7832\386804788.py:583: DeprecationWarning:

to_plotly_figure is deprecated and will be removed in version 4.0.0. Use MolGraph.to_plotly() instead.

C:\Users\George\AppData\Local\Temp\ipykernel_7832\386804788.py:589: DeprecationWarning:

to_networkx_graph is deprecated and will be removed in version 4.0.0. Use MolGraph.to_networkx() instead.

C:\Users\George\Desktop\Research_UCLA\CIC\Computational Work\Project cluster version 2\project_catalyst_repurposing\structures_ligand_id\pd_me2_structures\ligand_xyz\ligand-102-p-o-28-ligand_xyz.txt
Starting node: 0
Ending node: 6
(-0.80758, -0.080099, 0.011819)   0
(0.868405, -0.74325, -0.081019)   1
(1.896884, 0.238668, 0.058089)   2
(1.689088, 1.478315, 0.207423)   6
ligand-103-p-o-29

C:\Users\George\AppData\Local\Temp\ipykernel_7832\386804788.py:583: DeprecationWarning:

to_plotly_figure is deprecated and will be removed in version 4.0.0. Use MolGraph.to_plotly() instead.

C:\Users\George\AppData\Local\Temp\ipykernel_7832\386804788.py:589: DeprecationWarning:

to_networkx_graph is deprecated and will be removed in version 4.0.0. Use MolGraph.to_networkx() instead.

Pd number index:  6
['P', 'C', 'C', 'C', 'C', 'H', 'Pd', 'O', 'C', 'H', 'H', 'H', 'C', 'H', 'H', 'H', 'H', 'C', 'C', 'C', 'C', 'H', 'C', 'C', 'H', 'H', 'C', 'C', 'C', 'C', 'H', 'C', 'H', 'C', 'H', 'H', 'H', 'C', 'C', 'C', 'C', 'H', 'C', 'H', 'C', 'H', 'H', 'H', 'C', 'C', 'C', 'C', 'H', 'C', 'H', 'C', 'H', 'H', 'H']
Ligand atom label:  1  Ligand atom B nbo:  0.99439
Ligand atom label:  8  Ligand atom A nbo:  -0.67075
Atom_a:  1 Atom_b:  8
C:\Users\George\Desktop\Research_UCLA\CIC\Computational Work\Project cluster version 2\project_catalyst_repurposing\structures_ligand_id\pd_me2_structures\ligand_xyz\ligand-103-p-o-29-ligand_xyz.txt

C:\Users\George\AppData\Local\Temp\ipykernel_7832\386804788.py:583: DeprecationWarning:

to_plotly_figure is deprecated and will be removed in version 4.0.0. Use MolGraph.to_plotly() instead.

C:\Users\George\AppData\Local\Temp\ipykernel_7832\386804788.py:589: DeprecationWarning:

to_networkx_graph is deprecated and will be removed in version 4.0.0. Use MolGraph.to_networkx() instead.

Starting node: 0
Ending node: 6
(1.541817, -0.068266, 0.003228)   0
(0.315393, 1.260841, -0.018759)   1
(-1.037899, 0.808493, -0.120849)   2
(-1.355079, -0.404057, -0.284097)   6
ligand-104-p-o-30
Pd number index:  6
['P', 'C', 'C', 'C', 'C', 'H', 'Pd', 'O', 'C', 'H', 'H', 'H', 'C', 'H', 'H', 'H', 'H', 'C', 'C', 'C', 'C', 'H', 'C', 'C', 'H', 'H', 'C', 'C', 'C', 'C', 'H', 'C', 'H', 'C', 'H', 'H', 'H', 'C', 'C', 'C', 'C', 'H', 'C', 'H', 'C', 'H', 'H', 'H', 'C', 'C', 'C', 'C', 'H', 'C', 'H', 'C', 'H', 'C', 'H', 'H', 'H', 'C', 'H', 'H', 'H']
Ligand atom label:  1  Ligand atom B nbo:  0.99442
Ligand atom label:  8  Ligand atom A nbo:  -0.66945
Atom_a:  1 Atom_b:  8
C:\Users\George\Desktop\Research_UCLA\CIC\Computational Work\Project cluster version 2\project_catalyst_repurposing\structures_ligand_id\pd_me2_structures\ligand_xyz\ligand-104-p-o-30-ligand_xyz.txt
Starting node: 0
Ending node: 6
(1.823787, -0.133033, 0.061709)   0
(0.763668, 1.322008, -0.105901)   1
(-0.62896, 1.053998, 0.073732)   2
(-1.079957, -0.080127, 0.405371)   6
ligand-105-p-o-31

C:\Users\George\AppData\Local\Temp\ipykernel_7832\386804788.py:583: DeprecationWarning:

to_plotly_figure is deprecated and will be removed in version 4.0.0. Use MolGraph.to_plotly() instead.

C:\Users\George\AppData\Local\Temp\ipykernel_7832\386804788.py:589: DeprecationWarning:

to_networkx_graph is deprecated and will be removed in version 4.0.0. Use MolGraph.to_networkx() instead.

Pd number index:  6
['P', 'C', 'C', 'C', 'C', 'H', 'Pd', 'O', 'C', 'H', 'H', 'H', 'C', 'H', 'H', 'H', 'H', 'C', 'C', 'C', 'C', 'H', 'C', 'C', 'H', 'H', 'C', 'C', 'C', 'C', 'H', 'C', 'H', 'C', 'H', 'H', 'H', 'C', 'C', 'C', 'C', 'H', 'C', 'H', 'C', 'H', 'H', 'H', 'C', 'C', 'C', 'C', 'H', 'C', 'H', 'C', 'H', 'C', 'C', 'F', 'F', 'F', 'F', 'F', 'F']
Ligand atom label:  1  Ligand atom B nbo:  0.99498
Ligand atom label:  8  Ligand atom A nbo:  -0.67697
Atom_a:  1 Atom_b:  8
C:\Users\George\Desktop\Research_UCLA\CIC\Computational Work\Project cluster version 2\project_catalyst_repurposing\structures_ligand_id\pd_me2_structures\ligand_xyz\ligand-105-p-o-31-ligand_xyz.txt

C:\Users\George\AppData\Local\Temp\ipykernel_7832\386804788.py:583: DeprecationWarning:

to_plotly_figure is deprecated and will be removed in version 4.0.0. Use MolGraph.to_plotly() instead.

C:\Users\George\AppData\Local\Temp\ipykernel_7832\386804788.py:589: DeprecationWarning:

to_networkx_graph is deprecated and will be removed in version 4.0.0. Use MolGraph.to_networkx() instead.

Starting node: 0
Ending node: 6
(-2.527587, -0.139807, 0.198007)   0
(-1.679096, 1.369076, -0.340699)   1
(-0.257836, 1.314179, -0.228918)   2
(0.366527, 0.352799, 0.309503)   6
ligand-106-p-o-32
Pd number index:  28
['P', 'C', 'C', 'C', 'C', 'C', 'C', 'C', 'C', 'H', 'H', 'C', 'C', 'C', 'C', 'C', 'H', 'H', 'H', 'H', 'C', 'C', 'C', 'C', 'C', 'H', 'H', 'H', 'Pd', 'H', 'O', 'H', 'H', 'H', 'C', 'H', 'H', 'H', 'C', 'H', 'H', 'H', 'H']
Ligand atom label:  1  Ligand atom B nbo:  1.00913
Ligand atom label:  31  Ligand atom A nbo:  -0.6916
Atom_a:  1 Atom_b:  31
C:\Users\George\Desktop\Research_UCLA\CIC\Computational Work\Project cluster version 2\project_catalyst_repurposing\structures_ligand_id\pd_me2_structures\ligand_xyz\ligand-106-p-o-32-ligand_xyz.txt
Starting node: 0
Ending node: 29
(-0.205562, 0.02963, 0.002957)   0
(0.215296, -1.727262, -0.11554)   1
(1.619819, -2.00445, 0.060536)   2
(2.502993, -1.109263, 0.248153)   29
ligand-107-p-o-33
Pd number index:  28
['P', 'C', 'C', 'C', 'C', 'C', 'C', 'C', 'C', 'H', 'H', 'C', 'C', 'C', 'C', 'C', 'H', 'H', 'H', 'H', 'C', 'C', 'C', 'C', 'C', 'H', 'H', 'H', 'Pd', 'H', 'O', 'H', 'H', 'H', 'C', 'H', 'H', 'H', 'C', 'H', 'H', 'H', 'C', 'C', 'C', 'C', 'H', 'C', 'H', 'C', 'H', 'H', 'H']
Ligand atom label:  1  Ligand atom B nbo:  1.00949
Ligand atom label:  31  Ligand atom A nbo:  -0.68928
Atom_a:  1 Atom_b:  31

C:\Users\George\AppData\Local\Temp\ipykernel_7832\386804788.py:583: DeprecationWarning:

to_plotly_figure is deprecated and will be removed in version 4.0.0. Use MolGraph.to_plotly() instead.

C:\Users\George\AppData\Local\Temp\ipykernel_7832\386804788.py:589: DeprecationWarning:

to_networkx_graph is deprecated and will be removed in version 4.0.0. Use MolGraph.to_networkx() instead.

C:\Users\George\Desktop\Research_UCLA\CIC\Computational Work\Project cluster version 2\project_catalyst_repurposing\structures_ligand_id\pd_me2_structures\ligand_xyz\ligand-107-p-o-33-ligand_xyz.txt
Starting node: 0
Ending node: 29
(1.221749, 0.014498, -0.008104)   0
(-0.173935, 1.171542, -0.091198)   1
(-1.468881, 0.537925, -0.034427)   2
(-1.612077, -0.723804, 0.011673)   29
ligand-108-p-o-34
Pd number index:  25
['P', 'C', 'C', 'C', 'C', 'C', 'C', 'H', 'C', 'C', 'C', 'C', 'C', 'H', 'H', 'H', 'H', 'C', 'C', 'C', 'C', 'C', 'H', 'H', 'H', 'Pd', 'H', 'O', 'H', 'H', 'C', 'H', 'H', 'H', 'C', 'H', 'H', 'H', 'C', 'C', 'C', 'C', 'H', 'C', 'H', 'C', 'H', 'H', 'H', 'C', 'C', 'C', 'C', 'H', 'C', 'C', 'H', 'H', 'H']
Ligand atom label:  1  Ligand atom B nbo:  1.01246
Ligand atom label:  28  Ligand atom A nbo:  -0.68831
Atom_a:  1 Atom_b:  28

C:\Users\George\AppData\Local\Temp\ipykernel_7832\386804788.py:583: DeprecationWarning:

to_plotly_figure is deprecated and will be removed in version 4.0.0. Use MolGraph.to_plotly() instead.

C:\Users\George\AppData\Local\Temp\ipykernel_7832\386804788.py:589: DeprecationWarning:

to_networkx_graph is deprecated and will be removed in version 4.0.0. Use MolGraph.to_networkx() instead.

C:\Users\George\Desktop\Research_UCLA\CIC\Computational Work\Project cluster version 2\project_catalyst_repurposing\structures_ligand_id\pd_me2_structures\ligand_xyz\ligand-108-p-o-34-ligand_xyz.txt
Starting node: 0
Ending node: 26
(1.12454, 0.120041, 0.148885)   0
(-0.422879, 0.863111, 0.703038)   1
(-1.42983, -0.083295, 1.063687)   2
(-1.252496, -1.335896, 1.103553)   26
ligand-109-p-o-35
Pd number index:  15
['P', 'C', 'C', 'S', 'O', 'O', 'O', 'C', 'C', 'C', 'C', 'H', 'H', 'H', 'H', 'Pd', 'C', 'H', 'H', 'H', 'C', 'H', 'H', 'H', 'C', 'C', 'C', 'C', 'H', 'C', 'H', 'C', 'H', 'H', 'H', 'C', 'C', 'C', 'C', 'C', 'H', 'C', 'H', 'H', 'H', 'O', 'C', 'H', 'H', 'H']

C:\Users\George\AppData\Local\Temp\ipykernel_7832\386804788.py:583: DeprecationWarning:

to_plotly_figure is deprecated and will be removed in version 4.0.0. Use MolGraph.to_plotly() instead.

C:\Users\George\AppData\Local\Temp\ipykernel_7832\386804788.py:589: DeprecationWarning:

to_networkx_graph is deprecated and will be removed in version 4.0.0. Use MolGraph.to_networkx() instead.

Ligand atom label:  1  Ligand atom B nbo:  0.97709
Ligand atom label:  5  Ligand atom A nbo:  -0.94008
Atom_a:  1 Atom_b:  5
C:\Users\George\Desktop\Research_UCLA\CIC\Computational Work\Project cluster version 2\project_catalyst_repurposing\structures_ligand_id\pd_me2_structures\ligand_xyz\ligand-109-p-o-35-ligand_xyz.txt

C:\Users\George\AppData\Local\Temp\ipykernel_7832\386804788.py:583: DeprecationWarning:

to_plotly_figure is deprecated and will be removed in version 4.0.0. Use MolGraph.to_plotly() instead.

C:\Users\George\AppData\Local\Temp\ipykernel_7832\386804788.py:589: DeprecationWarning:

to_networkx_graph is deprecated and will be removed in version 4.0.0. Use MolGraph.to_networkx() instead.

Starting node: 0
Ending node: 4
(0.296769, 0.428979, 0.041062)   0
(-0.778902, 0.677459, -1.442672)   1
(-2.130952, 0.302882, -1.383479)   2
(-2.863501, -0.364198, 0.138038)   3
(-2.153144, -1.67377, 0.343559)   4
ligand-110-p-o-36
Pd number index:  15
['P', 'C', 'C', 'S', 'O', 'O', 'O', 'C', 'C', 'C', 'C', 'H', 'H', 'H', 'H', 'Pd', 'C', 'H', 'H', 'H', 'C', 'H', 'H', 'H', 'C', 'C', 'C', 'C', 'H', 'C', 'H', 'C', 'H', 'H', 'H', 'C', 'C', 'C', 'C', 'C', 'H', 'C', 'H', 'H', 'H', 'O', 'C', 'C', 'C', 'C', 'H', 'C', 'H', 'C', 'H', 'H', 'H']
Ligand atom label:  1  Ligand atom B nbo:  0.97506
Ligand atom label:  5  Ligand atom A nbo:  -0.93995
Atom_a:  1 Atom_b:  5
C:\Users\George\Desktop\Research_UCLA\CIC\Computational Work\Project cluster version 2\project_catalyst_repurposing\structures_ligand_id\pd_me2_structures\ligand_xyz\ligand-110-p-o-36-ligand_xyz.txt
Starting node: 0
Ending node: 4
(0.843747, 0.451014, 0.077548)   0
(0.828605, -0.542097, 1.633485)   1
(0.996229, -1.934709, 1.557019)   2
(1.306058, -2.774184, -0.02495)   3
(0.047822, -2.557184, -0.818855)   4
ligand-111-p-o-37

C:\Users\George\AppData\Local\Temp\ipykernel_7832\386804788.py:583: DeprecationWarning:

to_plotly_figure is deprecated and will be removed in version 4.0.0. Use MolGraph.to_plotly() instead.

C:\Users\George\AppData\Local\Temp\ipykernel_7832\386804788.py:589: DeprecationWarning:

to_networkx_graph is deprecated and will be removed in version 4.0.0. Use MolGraph.to_networkx() instead.

Pd number index:  15
['P', 'C', 'C', 'S', 'O', 'O', 'O', 'C', 'C', 'C', 'C', 'H', 'H', 'H', 'H', 'Pd', 'C', 'H', 'H', 'H', 'C', 'H', 'H', 'H', 'C', 'C', 'C', 'C', 'H', 'C', 'H', 'C', 'H', 'H', 'H', 'C', 'C', 'C', 'C', 'C', 'H', 'C', 'H', 'H', 'H', 'O', 'C', 'C', 'C', 'C', 'C', 'C', 'H', 'H', 'H', 'C', 'H', 'H', 'H', 'C', 'H', 'H', 'H']
Ligand atom label:  1  Ligand atom B nbo:  0.97398
Ligand atom label:  5  Ligand atom A nbo:  -0.94101
Atom_a:  1 Atom_b:  5
C:\Users\George\Desktop\Research_UCLA\CIC\Computational Work\Project cluster version 2\project_catalyst_repurposing\structures_ligand_id\pd_me2_structures\ligand_xyz\ligand-111-p-o-37-ligand_xyz.txt
Starting node: 0
Ending node: 4
(0.985876, 0.468607, 0.100783)   0
(0.693421, -0.588516, 1.592861)   1
(0.857452, -1.980397, 1.498509)   2
(1.466626, -2.773128, -0.021327)   3
(0.410778, -2.492501, -1.052626)   4
ligand-112-p-o-38

C:\Users\George\AppData\Local\Temp\ipykernel_7832\386804788.py:583: DeprecationWarning:

to_plotly_figure is deprecated and will be removed in version 4.0.0. Use MolGraph.to_plotly() instead.

C:\Users\George\AppData\Local\Temp\ipykernel_7832\386804788.py:589: DeprecationWarning:

to_networkx_graph is deprecated and will be removed in version 4.0.0. Use MolGraph.to_networkx() instead.

Pd number index:  15
['P', 'C', 'C', 'S', 'O', 'O', 'O', 'C', 'C', 'C', 'C', 'H', 'H', 'H', 'H', 'Pd', 'C', 'H', 'H', 'H', 'C', 'H', 'H', 'H', 'C', 'C', 'C', 'C', 'H', 'C', 'H', 'C', 'H', 'H', 'H', 'C', 'C', 'C', 'C', 'C', 'H', 'C', 'H', 'H', 'H', 'C', 'C', 'C', 'C', 'C', 'C', 'H', 'H', 'H', 'C', 'H', 'H', 'H', 'C', 'H', 'H', 'H', 'S', 'O', 'O']
Ligand atom label:  1  Ligand atom B nbo:  1.03849
Ligand atom label:  5  Ligand atom A nbo:  -0.9449
Atom_a:  1 Atom_b:  5
C:\Users\George\Desktop\Research_UCLA\CIC\Computational Work\Project cluster version 2\project_catalyst_repurposing\structures_ligand_id\pd_me2_structures\ligand_xyz\ligand-112-p-o-38-ligand_xyz.txt
Starting node: 0
Ending node: 4
(1.120848, 0.401162, -0.290518)   0
(1.138592, 0.874083, 1.490117)   1
(1.695371, -0.020765, 2.42009)   2
(2.517943, -1.558929, 1.908455)   3
(1.439512, -2.389837, 1.272025)   4
ligand-113-n-n-4

C:\Users\George\AppData\Local\Temp\ipykernel_7832\386804788.py:583: DeprecationWarning:

to_plotly_figure is deprecated and will be removed in version 4.0.0. Use MolGraph.to_plotly() instead.

C:\Users\George\AppData\Local\Temp\ipykernel_7832\386804788.py:589: DeprecationWarning:

to_networkx_graph is deprecated and will be removed in version 4.0.0. Use MolGraph.to_networkx() instead.

Pd number index:  0
['Pd', 'C', 'C', 'N', 'N', 'C', 'C', 'C', 'C', 'C', 'C', 'H', 'H', 'C', 'C', 'C', 'C', 'C', 'C', 'H', 'H', 'C', 'H', 'H', 'H', 'C', 'H', 'H', 'H', 'C', 'C', 'C', 'C', 'C', 'C', 'H', 'C', 'C', 'C', 'C', 'H', 'H', 'C', 'H', 'C', 'H', 'H', 'H', 'H', 'H', 'H', 'C', 'C', 'C', 'C', 'H', 'C', 'H', 'C', 'H', 'H', 'H', 'C', 'C', 'C', 'C', 'H', 'C', 'H', 'C', 'H', 'H', 'H', 'C', 'C', 'C', 'C', 'H', 'C', 'H', 'C', 'H', 'H', 'H', 'C', 'C', 'C', 'C', 'H', 'C', 'H', 'C', 'H', 'H', 'H', 'C', 'H', 'H', 'H', 'C', 'H', 'H', 'H']
Ligand atom label:  4  Ligand atom A nbo:  -0.46865
Ligand atom label:  5  Ligand atom B nbo:  -0.48217
Atom_a:  4 Atom_b:  5
C:\Users\George\Desktop\Research_UCLA\CIC\Computational Work\Project cluster version 2\project_catalyst_repurposing\structures_ligand_id\pd_me2_structures\ligand_xyz\ligand-113-n-n-4-ligand_xyz.txt
Starting node: 2
Ending node: 3
(-2.0304, -0.084768, -1.372858)   2
(-1.955345, -0.096251, -0.093119)   0
(-0.603163, -0.042531, 0.556771)   1
(0.4337, 0.011178, -0.195164)   3
ligand-114-n-n-5

C:\Users\George\AppData\Local\Temp\ipykernel_7832\386804788.py:583: DeprecationWarning:

to_plotly_figure is deprecated and will be removed in version 4.0.0. Use MolGraph.to_plotly() instead.

C:\Users\George\AppData\Local\Temp\ipykernel_7832\386804788.py:589: DeprecationWarning:

to_networkx_graph is deprecated and will be removed in version 4.0.0. Use MolGraph.to_networkx() instead.

Pd number index:  0
['Pd', 'C', 'C', 'N', 'N', 'C', 'C', 'C', 'C', 'C', 'C', 'H', 'H', 'C', 'C', 'C', 'C', 'C', 'C', 'H', 'H', 'C', 'H', 'H', 'H', 'C', 'H', 'H', 'H', 'C', 'C', 'C', 'C', 'C', 'C', 'H', 'C', 'C', 'C', 'C', 'H', 'H', 'C', 'H', 'C', 'H', 'H', 'H', 'H', 'H', 'H', 'C', 'C', 'C', 'C', 'H', 'C', 'H', 'C', 'H', 'H', 'H', 'C', 'C', 'C', 'C', 'H', 'C', 'H', 'C', 'H', 'H', 'H', 'C', 'C', 'C', 'C', 'H', 'C', 'H', 'C', 'H', 'H', 'H', 'C', 'C', 'C', 'C', 'H', 'C', 'H', 'C', 'H', 'H', 'H', 'C', 'H', 'H', 'C', 'H', 'H', 'C', 'H', 'H', 'H', 'C', 'H', 'H', 'H']
Ligand atom label:  4  Ligand atom B nbo:  -0.47041
Ligand atom label:  5  Ligand atom A nbo:  -0.48867
Atom_a:  4 Atom_b:  5
C:\Users\George\Desktop\Research_UCLA\CIC\Computational Work\Project cluster version 2\project_catalyst_repurposing\structures_ligand_id\pd_me2_structures\ligand_xyz\ligand-114-n-n-5-ligand_xyz.txt
Starting node: 2
Ending node: 3
(-2.011319, -0.390131, -1.064596)   2
(-1.815673, -0.349906, 0.201016)   0
(-0.424649, -0.118018, 0.716649)   1
(0.520364, 0.064295, -0.130207)   3
ligand-115-n-n-6

C:\Users\George\AppData\Local\Temp\ipykernel_7832\386804788.py:583: DeprecationWarning:

to_plotly_figure is deprecated and will be removed in version 4.0.0. Use MolGraph.to_plotly() instead.

C:\Users\George\AppData\Local\Temp\ipykernel_7832\386804788.py:589: DeprecationWarning:

to_networkx_graph is deprecated and will be removed in version 4.0.0. Use MolGraph.to_networkx() instead.

Pd number index:  0
['Pd', 'C', 'C', 'N', 'N', 'C', 'C', 'C', 'C', 'C', 'C', 'H', 'H', 'C', 'C', 'C', 'C', 'C', 'C', 'H', 'H', 'C', 'H', 'H', 'H', 'C', 'H', 'H', 'H', 'C', 'C', 'C', 'C', 'C', 'C', 'H', 'C', 'C', 'C', 'C', 'H', 'H', 'C', 'H', 'C', 'H', 'H', 'H', 'H', 'H', 'H', 'C', 'C', 'C', 'C', 'H', 'C', 'H', 'C', 'H', 'H', 'H', 'C', 'C', 'C', 'C', 'H', 'C', 'H', 'C', 'H', 'H', 'H', 'C', 'C', 'C', 'C', 'H', 'C', 'H', 'C', 'H', 'H', 'H', 'C', 'C', 'C', 'C', 'H', 'C', 'H', 'C', 'H', 'H', 'H', 'C', 'H', 'C', 'H', 'C', 'H', 'H', 'H', 'C', 'H', 'H', 'H', 'C', 'H', 'H', 'H', 'C', 'H', 'H', 'H']
Ligand atom label:  4  Ligand atom B nbo:  -0.46637
Ligand atom label:  5  Ligand atom A nbo:  -0.46279
Atom_a:  5 Atom_b:  4
C:\Users\George\Desktop\Research_UCLA\CIC\Computational Work\Project cluster version 2\project_catalyst_repurposing\structures_ligand_id\pd_me2_structures\ligand_xyz\ligand-115-n-n-6-ligand_xyz.txt
Ending node: 2
Starting node: 3
(-0.653475, -0.003744, -0.106054)   3
(0.276468, 0.003776, 0.776797)   1
(1.705986, 0.01391, 0.317795)   0
(1.958654, 0.008102, -0.937724)   2
ligand-116-n-n-7

C:\Users\George\AppData\Local\Temp\ipykernel_7832\386804788.py:583: DeprecationWarning:

to_plotly_figure is deprecated and will be removed in version 4.0.0. Use MolGraph.to_plotly() instead.

C:\Users\George\AppData\Local\Temp\ipykernel_7832\386804788.py:589: DeprecationWarning:

to_networkx_graph is deprecated and will be removed in version 4.0.0. Use MolGraph.to_networkx() instead.

Pd number index:  0
['Pd', 'C', 'C', 'N', 'N', 'C', 'C', 'C', 'C', 'C', 'C', 'H', 'H', 'C', 'C', 'C', 'C', 'C', 'C', 'H', 'H', 'C', 'H', 'H', 'H', 'C', 'H', 'H', 'H', 'C', 'C', 'C', 'C', 'C', 'C', 'H', 'C', 'C', 'C', 'C', 'H', 'H', 'C', 'H', 'C', 'H', 'H', 'H', 'H', 'H', 'C', 'C', 'C', 'C', 'H', 'C', 'H', 'C', 'H', 'H', 'H', 'C', 'C', 'C', 'C', 'H', 'C', 'H', 'C', 'H', 'H', 'H', 'C', 'C', 'C', 'C', 'H', 'C', 'H', 'C', 'H', 'H', 'H', 'C', 'C', 'C', 'C', 'H', 'C', 'H', 'C', 'H', 'H', 'H', 'C', 'H', 'H', 'H', 'C', 'H', 'H', 'H', 'C', 'H', 'H', 'H']
Ligand atom label:  4  Ligand atom A nbo:  -0.46733
Ligand atom label:  5  Ligand atom B nbo:  -0.48233
Atom_a:  4 Atom_b:  5
C:\Users\George\Desktop\Research_UCLA\CIC\Computational Work\Project cluster version 2\project_catalyst_repurposing\structures_ligand_id\pd_me2_structures\ligand_xyz\ligand-116-n-n-7-ligand_xyz.txt
Starting node: 2
Ending node: 3
(-2.078879, -0.016307, -0.980569)   2
(-1.803877, -0.027454, 0.271408)   0
(-0.365322, -0.014496, 0.699974)   1
(0.54101, -0.000228, -0.206557)   3
ligand-117-n-n-8

C:\Users\George\AppData\Local\Temp\ipykernel_7832\386804788.py:583: DeprecationWarning:

to_plotly_figure is deprecated and will be removed in version 4.0.0. Use MolGraph.to_plotly() instead.

C:\Users\George\AppData\Local\Temp\ipykernel_7832\386804788.py:589: DeprecationWarning:

to_networkx_graph is deprecated and will be removed in version 4.0.0. Use MolGraph.to_networkx() instead.

Pd number index:  0
['Pd', 'C', 'C', 'N', 'N', 'C', 'C', 'C', 'C', 'C', 'C', 'H', 'H', 'C', 'C', 'C', 'C', 'C', 'C', 'H', 'H', 'C', 'H', 'H', 'H', 'C', 'H', 'H', 'H', 'C', 'C', 'C', 'C', 'C', 'C', 'H', 'C', 'C', 'C', 'C', 'H', 'H', 'C', 'H', 'C', 'H', 'H', 'H', 'H', 'H', 'C', 'C', 'C', 'C', 'H', 'C', 'H', 'C', 'H', 'H', 'H', 'C', 'C', 'C', 'C', 'H', 'C', 'H', 'C', 'H', 'H', 'H', 'C', 'C', 'C', 'C', 'H', 'C', 'H', 'C', 'H', 'H', 'H', 'C', 'C', 'C', 'C', 'H', 'C', 'H', 'C', 'H', 'H', 'H', 'C', 'H', 'H', 'C', 'H', 'H', 'C', 'H', 'H', 'H', 'C', 'H', 'H', 'H', 'C', 'H', 'H', 'H']
Ligand atom label:  4  Ligand atom A nbo:  -0.46534
Ligand atom label:  5  Ligand atom B nbo:  -0.48347
Atom_a:  4 Atom_b:  5
C:\Users\George\Desktop\Research_UCLA\CIC\Computational Work\Project cluster version 2\project_catalyst_repurposing\structures_ligand_id\pd_me2_structures\ligand_xyz\ligand-117-n-n-8-ligand_xyz.txt
Starting node: 2
Ending node: 3
(-1.98662, -0.012331, -0.782842)   2
(-1.634127, 0.004816, 0.448983)   0
(-0.172437, 0.005641, 0.788477)   1
(0.67809, 7.5e-05, -0.170966)   3
ligand-118-p-n-1

C:\Users\George\AppData\Local\Temp\ipykernel_7832\386804788.py:583: DeprecationWarning:

to_plotly_figure is deprecated and will be removed in version 4.0.0. Use MolGraph.to_plotly() instead.

C:\Users\George\AppData\Local\Temp\ipykernel_7832\386804788.py:589: DeprecationWarning:

to_networkx_graph is deprecated and will be removed in version 4.0.0. Use MolGraph.to_networkx() instead.

Pd number index:  24
['N', 'C', 'H', 'C', 'C', 'C', 'C', 'H', 'C', 'C', 'H', 'H', 'H', 'C', 'C', 'C', 'C', 'C', 'C', 'H', 'H', 'C', 'H', 'C', 'Pd', 'C', 'H', 'H', 'H', 'C', 'H', 'H', 'H', 'P', 'C', 'C', 'C', 'C', 'H', 'C', 'H', 'C', 'H', 'H', 'H', 'C', 'C', 'C', 'C', 'H', 'C', 'H', 'C', 'H', 'H', 'H', 'H', 'C', 'C', 'C', 'C', 'H', 'C', 'H', 'C', 'H', 'H', 'H', 'C', 'C', 'C', 'C', 'H', 'C', 'H', 'C', 'H', 'H', 'H', 'C', 'C', 'C', 'C', 'H', 'C', 'H', 'C', 'H', 'H', 'H', 'C', 'C', 'C', 'C', 'H', 'C', 'H', 'C', 'H', 'H', 'H', 'C', 'H', 'H', 'H']
Ligand atom label:  1  Ligand atom A nbo:  -0.49579
Ligand atom label:  34  Ligand atom B nbo:  1.32481
Atom_a:  34 Atom_b:  1
C:\Users\George\Desktop\Research_UCLA\CIC\Computational Work\Project cluster version 2\project_catalyst_repurposing\structures_ligand_id\pd_me2_structures\ligand_xyz\ligand-118-p-n-1-ligand_xyz.txt
Ending node: 0
Starting node: 24
(-2.602749, -0.005956, -0.065484)   24
(-2.291632, -0.256034, 1.73799)   5
(-1.005187, -0.108013, 2.306467)   3
(0.283468, 0.041924, 1.616149)   1
(0.589812, -0.023545, 0.374647)   0
ligand-119-p-n-2

C:\Users\George\AppData\Local\Temp\ipykernel_7832\386804788.py:583: DeprecationWarning:

to_plotly_figure is deprecated and will be removed in version 4.0.0. Use MolGraph.to_plotly() instead.

C:\Users\George\AppData\Local\Temp\ipykernel_7832\386804788.py:589: DeprecationWarning:

to_networkx_graph is deprecated and will be removed in version 4.0.0. Use MolGraph.to_networkx() instead.

Pd number index:  24
['N', 'C', 'H', 'C', 'C', 'C', 'C', 'H', 'C', 'C', 'H', 'H', 'H', 'C', 'C', 'C', 'C', 'C', 'C', 'H', 'H', 'C', 'H', 'C', 'Pd', 'C', 'H', 'H', 'H', 'C', 'H', 'H', 'H', 'P', 'C', 'C', 'C', 'C', 'H', 'C', 'H', 'C', 'H', 'H', 'H', 'C', 'C', 'C', 'C', 'H', 'C', 'H', 'C', 'H', 'H', 'H', 'H', 'C', 'C', 'C', 'C', 'H', 'C', 'H', 'C', 'H', 'H', 'H', 'C', 'C', 'C', 'C', 'H', 'C', 'H', 'C', 'H', 'H', 'H', 'F', 'C', 'C', 'C', 'C', 'H', 'C', 'H', 'C', 'H', 'H', 'H', 'C', 'C', 'C', 'C', 'H', 'C', 'H', 'C', 'H', 'H', 'H']
Ligand atom label:  1  Ligand atom A nbo:  -0.49799
Ligand atom label:  34  Ligand atom B nbo:  1.32445
Atom_a:  34 Atom_b:  1
C:\Users\George\Desktop\Research_UCLA\CIC\Computational Work\Project cluster version 2\project_catalyst_repurposing\structures_ligand_id\pd_me2_structures\ligand_xyz\ligand-119-p-n-2-ligand_xyz.txt
Ending node: 0
Starting node: 24
(-2.5963, -0.000677, -0.063474)   24
(-2.28299, -0.254698, 1.739254)   5
(-0.996122, -0.107535, 2.307324)   3
(0.292281, 0.041117, 1.616958)   1
(0.598573, -0.024179, 0.375092)   0
ligand-120-p-n-3

C:\Users\George\AppData\Local\Temp\ipykernel_7832\386804788.py:583: DeprecationWarning:

to_plotly_figure is deprecated and will be removed in version 4.0.0. Use MolGraph.to_plotly() instead.

C:\Users\George\AppData\Local\Temp\ipykernel_7832\386804788.py:589: DeprecationWarning:

to_networkx_graph is deprecated and will be removed in version 4.0.0. Use MolGraph.to_networkx() instead.

Pd number index:  22
['N', 'C', 'H', 'C', 'C', 'C', 'C', 'H', 'C', 'C', 'H', 'H', 'H', 'C', 'C', 'C', 'C', 'C', 'C', 'H', 'H', 'C', 'Pd', 'C', 'H', 'H', 'H', 'C', 'H', 'H', 'H', 'P', 'C', 'C', 'C', 'C', 'H', 'C', 'H', 'C', 'H', 'H', 'H', 'C', 'C', 'C', 'C', 'H', 'C', 'H', 'C', 'H', 'H', 'H', 'H', 'H', 'C', 'H', 'C', 'H', 'H', 'H', 'C', 'H', 'H', 'H', 'C', 'H', 'H', 'H', 'C', 'H', 'H', 'H']
Ligand atom label:  1  Ligand atom A nbo:  -0.51261
Ligand atom label:  32  Ligand atom B nbo:  1.33463
Atom_a:  32 Atom_b:  1
C:\Users\George\Desktop\Research_UCLA\CIC\Computational Work\Project cluster version 2\project_catalyst_repurposing\structures_ligand_id\pd_me2_structures\ligand_xyz\ligand-120-p-n-3-ligand_xyz.txt
Ending node: 0
Starting node: 22
(1.612623, 0.14214, -0.114423)   22
(1.420322, 1.163969, 1.410878)   5
(0.160966, 1.259913, 2.048641)   3
(-1.101803, 0.667239, 1.581262)   1
(-1.444393, 0.354119, 0.390775)   0
ligand-121-p-p-23

C:\Users\George\AppData\Local\Temp\ipykernel_7832\386804788.py:583: DeprecationWarning:

to_plotly_figure is deprecated and will be removed in version 4.0.0. Use MolGraph.to_plotly() instead.

C:\Users\George\AppData\Local\Temp\ipykernel_7832\386804788.py:589: DeprecationWarning:

to_networkx_graph is deprecated and will be removed in version 4.0.0. Use MolGraph.to_networkx() instead.

Pd number index:  2
['P', 'C', 'Pd', 'C', 'H', 'H', 'H', 'C', 'H', 'H', 'H', 'P', 'H', 'H', 'C', 'H', 'C', 'H', 'C', 'C', 'H', 'H', 'H', 'C', 'H', 'H', 'H', 'C', 'C', 'H', 'H', 'H', 'C', 'H', 'H', 'H', 'C', 'H', 'H', 'H', 'C', 'H', 'H', 'H', 'C', 'H', 'H', 'H', 'C', 'H', 'H', 'H', 'H', 'H']
Ligand atom label:  1  Ligand atom A nbo:  1.02145
Ligand atom label:  12  Ligand atom B nbo:  1.18013
Atom_a:  12 Atom_b:  1
C:\Users\George\Desktop\Research_UCLA\CIC\Computational Work\Project cluster version 2\project_catalyst_repurposing\structures_ligand_id\pd_me2_structures\ligand_xyz\ligand-121-p-p-23-ligand_xyz.txt
Ending node: 0
Starting node: 2
(1.522781, 0.44243, 0.133015)   2
(0.14108, 1.373715, 1.000988)   1
(-1.342978, 0.44544, 0.327715)   0
ligand-122-c-o-1
Pd number index:  0
['Pd', 'C', 'C', 'C', 'H', 'N', 'N', 'C', 'C', 'C', 'C', 'C', 'C', 'H', 'H', 'C', 'H', 'C', 'H', 'H', 'C', 'C', 'H', 'H', 'C', 'C', 'C', 'H', 'C', 'C', 'C', 'H', 'H', 'C', 'H', 'H', 'H', 'C', 'H', 'H', 'H', 'C', 'H', 'H', 'H', 'C', 'H', 'H', 'H', 'C', 'H', 'H', 'H', 'C', 'H', 'H', 'H', 'O']

C:\Users\George\AppData\Local\Temp\ipykernel_7832\386804788.py:583: DeprecationWarning:

to_plotly_figure is deprecated and will be removed in version 4.0.0. Use MolGraph.to_plotly() instead.

C:\Users\George\AppData\Local\Temp\ipykernel_7832\386804788.py:589: DeprecationWarning:

to_networkx_graph is deprecated and will be removed in version 4.0.0. Use MolGraph.to_networkx() instead.

Ligand atom label:  2  Ligand atom A nbo:  0.23792
Ligand atom label:  58  Ligand atom B nbo:  -0.67023
Atom_a:  2 Atom_b:  58
C:\Users\George\Desktop\Research_UCLA\CIC\Computational Work\Project cluster version 2\project_catalyst_repurposing\structures_ligand_id\pd_me2_structures\ligand_xyz\ligand-122-c-o-1-ligand_xyz.txt
Starting node: 0
Ending node: 48
(0.245125, -0.210628, 3.1e-05)   0
(1.409597, -0.958231, -3.6e-05)   5
(2.764151, -0.511685, 0.000106)   25
(3.102267, 0.891729, 0.000121)   27
(2.282801, 1.853144, -7.2e-05)   48
ligand-123-c-o-2

C:\Users\George\AppData\Local\Temp\ipykernel_7832\386804788.py:583: DeprecationWarning:

to_plotly_figure is deprecated and will be removed in version 4.0.0. Use MolGraph.to_plotly() instead.

C:\Users\George\AppData\Local\Temp\ipykernel_7832\386804788.py:589: DeprecationWarning:

to_networkx_graph is deprecated and will be removed in version 4.0.0. Use MolGraph.to_networkx() instead.

Pd number index:  0
['Pd', 'C', 'C', 'C', 'H', 'N', 'N', 'C', 'C', 'C', 'C', 'C', 'C', 'H', 'H', 'C', 'H', 'C', 'H', 'C', 'C', 'H', 'H', 'C', 'C', 'C', 'H', 'C', 'C', 'C', 'H', 'H', 'C', 'H', 'H', 'H', 'C', 'H', 'H', 'H', 'O', 'C', 'C', 'C', 'C', 'H', 'C', 'H', 'C', 'H', 'H', 'H', 'C', 'C', 'C', 'C', 'H', 'C', 'H', 'C', 'H', 'H', 'H', 'C', 'C', 'C', 'C', 'H', 'C', 'H', 'C', 'H', 'H', 'H', 'C', 'C', 'C', 'C', 'H', 'C', 'H', 'C', 'H', 'H', 'H', 'C', 'H', 'H', 'H']
Ligand atom label:  2  Ligand atom A nbo:  0.23355
Ligand atom label:  41  Ligand atom B nbo:  -0.67499
Atom_a:  2 Atom_b:  41
C:\Users\George\Desktop\Research_UCLA\CIC\Computational Work\Project cluster version 2\project_catalyst_repurposing\structures_ligand_id\pd_me2_structures\ligand_xyz\ligand-123-c-o-2-ligand_xyz.txt
Starting node: 0
Ending node: 31
(-0.313868, 0.678717, -0.177122)   0
(-0.275631, 1.862721, 0.523681)   5
(-1.104293, 3.006624, 0.376796)   24
(-2.287118, 2.97935, -0.448588)   26
(-2.718661, 1.972132, -1.085921)   31
ligand-124-c-o-3

C:\Users\George\AppData\Local\Temp\ipykernel_7832\386804788.py:583: DeprecationWarning:

to_plotly_figure is deprecated and will be removed in version 4.0.0. Use MolGraph.to_plotly() instead.

C:\Users\George\AppData\Local\Temp\ipykernel_7832\386804788.py:589: DeprecationWarning:

to_networkx_graph is deprecated and will be removed in version 4.0.0. Use MolGraph.to_networkx() instead.

Pd number index:  0
['Pd', 'C', 'C', 'C', 'H', 'N', 'N', 'C', 'C', 'C', 'C', 'C', 'C', 'H', 'H', 'C', 'H', 'C', 'H', 'C', 'C', 'H', 'H', 'C', 'C', 'C', 'H', 'C', 'C', 'C', 'H', 'H', 'C', 'H', 'H', 'H', 'C', 'H', 'H', 'H', 'O', 'C', 'C', 'C', 'C', 'H', 'C', 'H', 'C', 'H', 'C', 'C', 'C', 'C', 'H', 'C', 'H', 'C', 'H', 'C', 'C', 'C', 'C', 'H', 'C', 'H', 'C', 'H', 'C', 'C', 'C', 'C', 'H', 'C', 'H', 'C', 'H', 'C', 'H', 'H', 'H', 'C', 'H', 'H', 'H', 'C', 'H', 'H', 'H', 'C', 'H', 'H', 'H', 'C', 'H', 'H', 'H', 'C', 'H', 'H', 'H', 'C', 'H', 'H', 'H', 'C', 'H', 'H', 'H', 'C', 'H', 'H', 'H']
Ligand atom label:  2  Ligand atom A nbo:  0.2177
Ligand atom label:  41  Ligand atom B nbo:  -0.6904
Atom_a:  2 Atom_b:  41
C:\Users\George\Desktop\Research_UCLA\CIC\Computational Work\Project cluster version 2\project_catalyst_repurposing\structures_ligand_id\pd_me2_structures\ligand_xyz\ligand-124-c-o-3-ligand_xyz.txt
Starting node: 0
Ending node: 31
(-0.191312, 0.301615, 0.607155)   0
(0.168351, -0.254897, 1.814876)   5
(-0.352256, 0.000657, 3.116654)   24
(-1.477248, 0.880659, 3.321421)   26
(-2.06683, 1.545643, 2.417735)   31
ligand-125-p-p-24

C:\Users\George\AppData\Local\Temp\ipykernel_7832\386804788.py:583: DeprecationWarning:

to_plotly_figure is deprecated and will be removed in version 4.0.0. Use MolGraph.to_plotly() instead.

C:\Users\George\AppData\Local\Temp\ipykernel_7832\386804788.py:589: DeprecationWarning:

to_networkx_graph is deprecated and will be removed in version 4.0.0. Use MolGraph.to_networkx() instead.

Pd number index:  2
['P', 'C', 'Pd', 'C', 'H', 'H', 'H', 'C', 'H', 'H', 'H', 'P', 'H', 'H', 'C', 'C', 'C', 'C', 'H', 'H', 'H', 'C', 'H', 'H', 'H', 'C', 'C', 'H', 'H', 'H', 'C', 'H', 'H', 'H', 'C', 'H', 'H', 'H', 'C', 'H', 'H', 'H', 'C', 'H', 'H', 'H', 'C', 'H', 'H', 'H', 'C', 'H', 'H', 'H', 'C', 'H', 'H', 'H', 'C', 'H', 'H', 'H', 'C', 'H', 'H', 'H']
Ligand atom label:  1  Ligand atom A nbo:  1.06872
Ligand atom label:  12  Ligand atom B nbo:  1.20948
Atom_a:  12 Atom_b:  1
C:\Users\George\Desktop\Research_UCLA\CIC\Computational Work\Project cluster version 2\project_catalyst_repurposing\structures_ligand_id\pd_me2_structures\ligand_xyz\ligand-125-p-p-24-ligand_xyz.txt
Ending node: 0
Starting node: 2
(1.487346, 0.315337, 0.114762)   2
(0.017124, 1.254635, 0.83785)   1
(-1.469613, 0.27085, 0.210598)   0
ligand-126-p-p-25

C:\Users\George\AppData\Local\Temp\ipykernel_7832\386804788.py:583: DeprecationWarning:

to_plotly_figure is deprecated and will be removed in version 4.0.0. Use MolGraph.to_plotly() instead.

C:\Users\George\AppData\Local\Temp\ipykernel_7832\386804788.py:589: DeprecationWarning:

to_networkx_graph is deprecated and will be removed in version 4.0.0. Use MolGraph.to_networkx() instead.

Pd number index:  2
['P', 'C', 'Pd', 'C', 'H', 'H', 'H', 'C', 'H', 'H', 'H', 'P', 'H', 'H', 'C', 'C', 'C', 'H', 'H', 'H', 'C', 'H', 'H', 'H', 'C', 'H', 'H', 'H', 'C', 'H', 'H', 'H', 'C', 'H', 'H', 'H', 'C', 'H', 'H', 'H', 'C', 'C', 'C', 'C', 'H', 'C', 'H', 'C', 'H', 'H', 'H', 'C', 'C', 'C', 'C', 'H', 'C', 'H', 'C', 'H', 'H', 'H']
Ligand atom label:  1  Ligand atom A nbo:  1.05457
Ligand atom label:  12  Ligand atom B nbo:  1.20917
Atom_a:  12 Atom_b:  1
C:\Users\George\Desktop\Research_UCLA\CIC\Computational Work\Project cluster version 2\project_catalyst_repurposing\structures_ligand_id\pd_me2_structures\ligand_xyz\ligand-126-p-p-25-ligand_xyz.txt
Ending node: 0
Starting node: 2
(1.750152, -0.139455, 0.505448)   2
(0.120269, -0.072997, 1.431464)   1
(-1.082318, 0.043302, -0.005154)   0
ligand-127-p-p-26

C:\Users\George\AppData\Local\Temp\ipykernel_7832\386804788.py:583: DeprecationWarning:

to_plotly_figure is deprecated and will be removed in version 4.0.0. Use MolGraph.to_plotly() instead.

C:\Users\George\AppData\Local\Temp\ipykernel_7832\386804788.py:589: DeprecationWarning:

to_networkx_graph is deprecated and will be removed in version 4.0.0. Use MolGraph.to_networkx() instead.

Pd number index:  2
['P', 'C', 'Pd', 'C', 'H', 'H', 'H', 'C', 'H', 'H', 'H', 'P', 'H', 'H', 'C', 'C', 'C', 'H', 'H', 'H', 'C', 'H', 'H', 'H', 'C', 'H', 'H', 'H', 'C', 'H', 'H', 'H', 'C', 'H', 'H', 'H', 'C', 'H', 'H', 'H', 'C', 'C', 'C', 'H', 'C', 'H', 'H', 'C', 'H', 'H', 'C', 'H', 'H', 'H', 'H', 'H', 'H', 'C', 'C', 'C', 'H', 'C', 'H', 'H', 'C', 'H', 'H', 'C', 'H', 'H', 'H', 'H', 'H', 'H']
Ligand atom label:  1  Ligand atom A nbo:  1.0752
Ligand atom label:  12  Ligand atom B nbo:  1.20257
Atom_a:  12 Atom_b:  1
C:\Users\George\Desktop\Research_UCLA\CIC\Computational Work\Project cluster version 2\project_catalyst_repurposing\structures_ligand_id\pd_me2_structures\ligand_xyz\ligand-127-p-p-26-ligand_xyz.txt
Ending node: 0
Starting node: 2
(-1.980621, 0.165781, -0.414371)   2
(-0.44268, 0.250653, -1.50232)   1
(0.901464, 0.02279, -0.208455)   0
ligand-128-p-p-27
Pd number index:  2
['P', 'C', 'Pd', 'C', 'H', 'H', 'H', 'C', 'H', 'H', 'H', 'P', 'H', 'H', 'C', 'C', 'C', 'H', 'H', 'H', 'C', 'H', 'H', 'H', 'C', 'H', 'H', 'H', 'C', 'H', 'H', 'H', 'C', 'H', 'H', 'H', 'C', 'H', 'H', 'H', 'C', 'H', 'C', 'H', 'H', 'H', 'C', 'H', 'H', 'H', 'C', 'H', 'C', 'H', 'H', 'H', 'C', 'H', 'H', 'H']

C:\Users\George\AppData\Local\Temp\ipykernel_7832\386804788.py:583: DeprecationWarning:

to_plotly_figure is deprecated and will be removed in version 4.0.0. Use MolGraph.to_plotly() instead.

C:\Users\George\AppData\Local\Temp\ipykernel_7832\386804788.py:589: DeprecationWarning:

to_networkx_graph is deprecated and will be removed in version 4.0.0. Use MolGraph.to_networkx() instead.

Ligand atom label:  1  Ligand atom A nbo:  0.92157
Ligand atom label:  12  Ligand atom B nbo:  0.92215
Atom_a:  12 Atom_b:  1
C:\Users\George\Desktop\Research_UCLA\CIC\Computational Work\Project cluster version 2\project_catalyst_repurposing\structures_ligand_id\pd_me2_structures\ligand_xyz\ligand-128-p-p-27-ligand_xyz.txt
Ending node: 0
Starting node: 2
(-1.304955, 0.185053, 0.158366)   2
(-0.043522, 1.257386, 1.050011)   1
(1.562672, 0.543504, 0.380736)   0
ligand-129-p-p-28

C:\Users\George\AppData\Local\Temp\ipykernel_7832\386804788.py:583: DeprecationWarning:

to_plotly_figure is deprecated and will be removed in version 4.0.0. Use MolGraph.to_plotly() instead.

C:\Users\George\AppData\Local\Temp\ipykernel_7832\386804788.py:589: DeprecationWarning:

to_networkx_graph is deprecated and will be removed in version 4.0.0. Use MolGraph.to_networkx() instead.

Pd number index:  2
['P', 'C', 'Pd', 'C', 'H', 'H', 'H', 'C', 'H', 'H', 'H', 'P', 'H', 'H', 'C', 'C', 'C', 'H', 'C', 'H', 'H', 'C', 'H', 'H', 'C', 'H', 'H', 'H', 'H', 'H', 'H', 'C', 'C', 'C', 'H', 'C', 'H', 'H', 'C', 'H', 'H', 'C', 'H', 'H', 'H', 'H', 'H', 'H', 'C', 'C', 'C', 'H', 'C', 'H', 'H', 'C', 'H', 'H', 'C', 'H', 'H', 'H', 'H', 'H', 'H', 'C', 'C', 'C', 'H', 'C', 'H', 'H', 'C', 'H', 'H', 'C', 'H', 'H', 'H', 'H', 'H', 'H']
Ligand atom label:  1  Ligand atom A nbo:  1.07022
Ligand atom label:  12  Ligand atom B nbo:  1.21862
Atom_a:  12 Atom_b:  1
C:\Users\George\Desktop\Research_UCLA\CIC\Computational Work\Project cluster version 2\project_catalyst_repurposing\structures_ligand_id\pd_me2_structures\ligand_xyz\ligand-129-p-p-28-ligand_xyz.txt
Ending node: 0
Starting node: 2
(-1.430618, -0.017796, -0.194435)   2
(-0.010187, 0.02312, -1.416549)   1
(1.426402, -0.005308, -0.214808)   0
ligand-130-n-n-9

C:\Users\George\AppData\Local\Temp\ipykernel_7832\386804788.py:583: DeprecationWarning:

to_plotly_figure is deprecated and will be removed in version 4.0.0. Use MolGraph.to_plotly() instead.

C:\Users\George\AppData\Local\Temp\ipykernel_7832\386804788.py:589: DeprecationWarning:

to_networkx_graph is deprecated and will be removed in version 4.0.0. Use MolGraph.to_networkx() instead.

Pd number index:  0
['Pd', 'C', 'C', 'N', 'N', 'C', 'C', 'C', 'C', 'C', 'C', 'H', 'H', 'C', 'C', 'C', 'C', 'C', 'C', 'H', 'H', 'C', 'H', 'H', 'H', 'C', 'H', 'H', 'H', 'C', 'C', 'C', 'C', 'C', 'C', 'H', 'C', 'C', 'C', 'C', 'H', 'H', 'H', 'H', 'H', 'H', 'H', 'C', 'C', 'C', 'C', 'H', 'C', 'H', 'C', 'H', 'H', 'C', 'C', 'C', 'C', 'H', 'C', 'H', 'C', 'H', 'H', 'C', 'C', 'C', 'C', 'H', 'C', 'H', 'C', 'H', 'H', 'C', 'C', 'C', 'C', 'H', 'C', 'H', 'C', 'H', 'H', 'C', 'H', 'H', 'C', 'H', 'H', 'C', 'H', 'H', 'C', 'H', 'H']
Ligand atom label:  4  Ligand atom B nbo:  -0.45649
Ligand atom label:  5  Ligand atom A nbo:  -0.4546
Atom_a:  5 Atom_b:  4
C:\Users\George\Desktop\Research_UCLA\CIC\Computational Work\Project cluster version 2\project_catalyst_repurposing\structures_ligand_id\pd_me2_structures\ligand_xyz\ligand-130-n-n-9-ligand_xyz.txt
Ending node: 2
Starting node: 3
(-0.000249, -1.375549, 0.099872)   3
(-0.000235, -0.542281, 1.068791)   1
(-0.000321, 0.920412, 0.756379)   0
(-0.000398, 1.302993, -0.46688)   2
ligand-131-p-n-4

C:\Users\George\AppData\Local\Temp\ipykernel_7832\386804788.py:583: DeprecationWarning:

to_plotly_figure is deprecated and will be removed in version 4.0.0. Use MolGraph.to_plotly() instead.

C:\Users\George\AppData\Local\Temp\ipykernel_7832\386804788.py:589: DeprecationWarning:

to_networkx_graph is deprecated and will be removed in version 4.0.0. Use MolGraph.to_networkx() instead.

Pd number index:  11
['P', 'C', 'C', 'C', 'C', 'C', 'C', 'H', 'H', 'H', 'H', 'Pd', 'C', 'H', 'H', 'H', 'C', 'H', 'H', 'H', 'N', 'C', 'H', 'H', 'H', 'C', 'H', 'H', 'H', 'C', 'C', 'C', 'C', 'H', 'C', 'H', 'C', 'H', 'H', 'H', 'C', 'C', 'C', 'C', 'H', 'C', 'H', 'C', 'H', 'H', 'H']
Ligand atom label:  1  Ligand atom A nbo:  0.96325
Ligand atom label:  21  Ligand atom B nbo:  -0.57274
Atom_a:  1 Atom_b:  21
C:\Users\George\Desktop\Research_UCLA\CIC\Computational Work\Project cluster version 2\project_catalyst_repurposing\structures_ligand_id\pd_me2_structures\ligand_xyz\ligand-131-p-n-4-ligand_xyz.txt
Starting node: 0
Ending node: 11
(-0.459217, 0.116961, -0.021119)   0
(0.133174, -1.566331, -0.463518)   1
(1.51447, -1.82495, -0.362287)   2
(2.407933, -0.817882, 0.166434)   11
ligand-132-p-n-5

C:\Users\George\AppData\Local\Temp\ipykernel_7832\386804788.py:583: DeprecationWarning:

to_plotly_figure is deprecated and will be removed in version 4.0.0. Use MolGraph.to_plotly() instead.

C:\Users\George\AppData\Local\Temp\ipykernel_7832\386804788.py:589: DeprecationWarning:

to_networkx_graph is deprecated and will be removed in version 4.0.0. Use MolGraph.to_networkx() instead.

Pd number index:  11
['P', 'C', 'C', 'C', 'C', 'C', 'C', 'H', 'H', 'H', 'H', 'Pd', 'C', 'H', 'H', 'H', 'C', 'H', 'H', 'H', 'N', 'C', 'H', 'H', 'H', 'C', 'H', 'H', 'H', 'C', 'C', 'C', 'C', 'C', 'C', 'H', 'H', 'H', 'C', 'C', 'C', 'C', 'C', 'C', 'H', 'H', 'H', 'C', 'H', 'C', 'H', 'H', 'H', 'C', 'H', 'H', 'H', 'C', 'H', 'C', 'H', 'H', 'H', 'C', 'H', 'H', 'H', 'H', 'H']
Ligand atom label:  1  Ligand atom A nbo:  0.94702
Ligand atom label:  21  Ligand atom B nbo:  -0.57171
Atom_a:  1 Atom_b:  21
C:\Users\George\Desktop\Research_UCLA\CIC\Computational Work\Project cluster version 2\project_catalyst_repurposing\structures_ligand_id\pd_me2_structures\ligand_xyz\ligand-132-p-n-5-ligand_xyz.txt
Starting node: 0
Ending node: 11
(0.278685, 0.117616, 0.250092)   0
(-0.997711, 0.119151, 1.580173)   1
(-2.0231, -0.844354, 1.536404)   2
(-1.983747, -1.905008, 0.55476)   11
ligand-133-p-n-6

C:\Users\George\AppData\Local\Temp\ipykernel_7832\386804788.py:583: DeprecationWarning:

to_plotly_figure is deprecated and will be removed in version 4.0.0. Use MolGraph.to_plotly() instead.

C:\Users\George\AppData\Local\Temp\ipykernel_7832\386804788.py:589: DeprecationWarning:

to_networkx_graph is deprecated and will be removed in version 4.0.0. Use MolGraph.to_networkx() instead.

Pd number index:  11
['P', 'C', 'C', 'C', 'C', 'C', 'C', 'H', 'H', 'H', 'H', 'Pd', 'C', 'H', 'H', 'H', 'C', 'H', 'H', 'H', 'N', 'C', 'H', 'H', 'H', 'C', 'H', 'H', 'H', 'C', 'C', 'C', 'C', 'C', 'C', 'H', 'H', 'H', 'C', 'C', 'C', 'C', 'C', 'C', 'H', 'H', 'H', 'H', 'H', 'C', 'C', 'C', 'C', 'H', 'C', 'H', 'C', 'H', 'H', 'H', 'C', 'C', 'C', 'C', 'H', 'C', 'H', 'C', 'H', 'H', 'H']
Ligand atom label:  1  Ligand atom A nbo:  0.94369
Ligand atom label:  21  Ligand atom B nbo:  -0.57367
Atom_a:  1 Atom_b:  21
C:\Users\George\Desktop\Research_UCLA\CIC\Computational Work\Project cluster version 2\project_catalyst_repurposing\structures_ligand_id\pd_me2_structures\ligand_xyz\ligand-133-p-n-6-ligand_xyz.txt
Starting node: 0
Ending node: 11
(0.085652, 0.565886, 0.167483)   0
(-1.366857, 0.52859, 1.305211)   1
(-1.696944, -0.694783, 1.916364)   2
(-0.871064, -1.866168, 1.710843)   11
ligand-134-p-n-7

C:\Users\George\AppData\Local\Temp\ipykernel_7832\386804788.py:583: DeprecationWarning:

to_plotly_figure is deprecated and will be removed in version 4.0.0. Use MolGraph.to_plotly() instead.

C:\Users\George\AppData\Local\Temp\ipykernel_7832\386804788.py:589: DeprecationWarning:

to_networkx_graph is deprecated and will be removed in version 4.0.0. Use MolGraph.to_networkx() instead.

Pd number index:  11
['P', 'C', 'C', 'C', 'C', 'C', 'C', 'H', 'H', 'H', 'H', 'Pd', 'C', 'H', 'H', 'H', 'C', 'H', 'H', 'H', 'N', 'C', 'H', 'H', 'H', 'C', 'H', 'H', 'H', 'C', 'C', 'C', 'C', 'C', 'C', 'H', 'H', 'H', 'C', 'C', 'C', 'C', 'C', 'C', 'H', 'H', 'H', 'H', 'H', 'O', 'C', 'H', 'H', 'H', 'O', 'C', 'H', 'H', 'H']
Ligand atom label:  1  Ligand atom A nbo:  0.96896
Ligand atom label:  21  Ligand atom B nbo:  -0.57211
Atom_a:  1 Atom_b:  21
C:\Users\George\Desktop\Research_UCLA\CIC\Computational Work\Project cluster version 2\project_catalyst_repurposing\structures_ligand_id\pd_me2_structures\ligand_xyz\ligand-134-p-n-7-ligand_xyz.txt
Starting node: 0
Ending node: 11
(0.328645, -0.035888, 0.229523)   0
(-0.845139, -0.201379, 1.637487)   1
(-2.147886, -0.662469, 1.373849)   2
(-2.523732, -1.075547, 0.03815)   11
ligand-135-p-n-8

C:\Users\George\AppData\Local\Temp\ipykernel_7832\386804788.py:583: DeprecationWarning:

to_plotly_figure is deprecated and will be removed in version 4.0.0. Use MolGraph.to_plotly() instead.

C:\Users\George\AppData\Local\Temp\ipykernel_7832\386804788.py:589: DeprecationWarning:

to_networkx_graph is deprecated and will be removed in version 4.0.0. Use MolGraph.to_networkx() instead.

Pd number index:  11
['P', 'C', 'C', 'C', 'C', 'C', 'C', 'H', 'H', 'H', 'H', 'Pd', 'C', 'H', 'H', 'H', 'C', 'H', 'H', 'H', 'N', 'C', 'H', 'H', 'H', 'C', 'H', 'H', 'H', 'C', 'C', 'C', 'C', 'C', 'C', 'H', 'H', 'H', 'C', 'C', 'C', 'C', 'C', 'C', 'H', 'H', 'H', 'H', 'H', 'H', 'C', 'C', 'C', 'C', 'C', 'C', 'H', 'H', 'H', 'O', 'O', 'C', 'H', 'H', 'H', 'C', 'H', 'H', 'H']
Ligand atom label:  1  Ligand atom A nbo:  0.95366
Ligand atom label:  21  Ligand atom B nbo:  -0.5734
Atom_a:  1 Atom_b:  21
C:\Users\George\Desktop\Research_UCLA\CIC\Computational Work\Project cluster version 2\project_catalyst_repurposing\structures_ligand_id\pd_me2_structures\ligand_xyz\ligand-135-p-n-8-ligand_xyz.txt
Starting node: 0
Ending node: 11
(0.884656, 0.376237, -0.132858)   0
(0.09536, 0.725736, 1.48873)   1
(-0.220873, -0.356295, 2.325599)   2
(0.104204, -1.717821, 1.942588)   11
ligand-136-p-o-39

C:\Users\George\AppData\Local\Temp\ipykernel_7832\386804788.py:583: DeprecationWarning:

to_plotly_figure is deprecated and will be removed in version 4.0.0. Use MolGraph.to_plotly() instead.

C:\Users\George\AppData\Local\Temp\ipykernel_7832\386804788.py:589: DeprecationWarning:

to_networkx_graph is deprecated and will be removed in version 4.0.0. Use MolGraph.to_networkx() instead.

Pd number index:  28
['P', 'C', 'C', 'C', 'C', 'C', 'C', 'C', 'C', 'H', 'H', 'C', 'C', 'C', 'C', 'C', 'H', 'H', 'H', 'H', 'C', 'C', 'C', 'C', 'C', 'H', 'H', 'H', 'Pd', 'H', 'O', 'H', 'H', 'C', 'H', 'H', 'H', 'C', 'H', 'H', 'H', 'C', 'C', 'C', 'C', 'C', 'C', 'H', 'H', 'H', 'O', 'O', 'C', 'H', 'H', 'H', 'C', 'H', 'H', 'H', 'C', 'F', 'F', 'F']
Ligand atom label:  1  Ligand atom B nbo:  1.00782
Ligand atom label:  31  Ligand atom A nbo:  -0.6844
Atom_a:  1 Atom_b:  31
C:\Users\George\Desktop\Research_UCLA\CIC\Computational Work\Project cluster version 2\project_catalyst_repurposing\structures_ligand_id\pd_me2_structures\ligand_xyz\ligand-136-p-o-39-ligand_xyz.txt

C:\Users\George\AppData\Local\Temp\ipykernel_7832\386804788.py:583: DeprecationWarning:

to_plotly_figure is deprecated and will be removed in version 4.0.0. Use MolGraph.to_plotly() instead.

C:\Users\George\AppData\Local\Temp\ipykernel_7832\386804788.py:589: DeprecationWarning:

to_networkx_graph is deprecated and will be removed in version 4.0.0. Use MolGraph.to_networkx() instead.

Starting node: 0
Ending node: 29
(0.053634, 0.48517, -0.134494)   0
(-1.582168, 1.297313, -0.154883)   1
(-2.680887, 0.37687, 0.017167)   2
(-2.523993, -0.879812, 0.0757)   29
ligand-137-p-o-40
Pd number index:  1
['P', 'Pd', 'C', 'H', 'H', 'H', 'C', 'H', 'H', 'H', 'P', 'O', 'C', 'C', 'C', 'C', 'H', 'C', 'C', 'H', 'H', 'H', 'C', 'C', 'C', 'C', 'H', 'C', 'C', 'H', 'H', 'H', 'O', 'O', 'C', 'H', 'H', 'H', 'C', 'H', 'H', 'H', 'O', 'O', 'C', 'H', 'H', 'C', 'H', 'H', 'H', 'C', 'H', 'H', 'C', 'H', 'H', 'H', 'C', 'C', 'C', 'C', 'C', 'H', 'C', 'H', 'H', 'H']
Ligand atom label:  1  Ligand atom B nbo:  0.94428
Ligand atom label:  12  Ligand atom A nbo:  -0.88551
Atom_a:  1 Atom_b:  12
C:\Users\George\Desktop\Research_UCLA\CIC\Computational Work\Project cluster version 2\project_catalyst_repurposing\structures_ligand_id\pd_me2_structures\ligand_xyz\ligand-137-p-o-40-ligand_xyz.txt
Starting node: 0
Ending node: 2
(-1.035023, -0.011494, 0.129382)   0
(-0.063648, -0.270322, 1.699933)   50
(1.341452, -0.190912, 1.75595)   49
(2.355787, 0.125202, 0.298708)   1
(1.973765, 1.22603, -0.644145)   2
ligand-138-p-o-41

C:\Users\George\AppData\Local\Temp\ipykernel_7832\386804788.py:583: DeprecationWarning:

to_plotly_figure is deprecated and will be removed in version 4.0.0. Use MolGraph.to_plotly() instead.

C:\Users\George\AppData\Local\Temp\ipykernel_7832\386804788.py:589: DeprecationWarning:

to_networkx_graph is deprecated and will be removed in version 4.0.0. Use MolGraph.to_networkx() instead.

Pd number index:  1
['P', 'Pd', 'C', 'H', 'H', 'H', 'C', 'H', 'H', 'H', 'P', 'O', 'C', 'C', 'C', 'C', 'H', 'C', 'C', 'H', 'H', 'H', 'C', 'C', 'C', 'C', 'H', 'C', 'C', 'H', 'H', 'H', 'O', 'O', 'C', 'H', 'H', 'H', 'C', 'H', 'H', 'H', 'C', 'C', 'C', 'C', 'C', 'H', 'C', 'H', 'H', 'H', 'C', 'C', 'C', 'C', 'C', 'H', 'C', 'H', 'H', 'H', 'C', 'C', 'C', 'C', 'C', 'H', 'C', 'H', 'H', 'H', 'O', 'O', 'C', 'H', 'H', 'H', 'C', 'H', 'H', 'H']
Ligand atom label:  1  Ligand atom B nbo:  0.94075
Ligand atom label:  12  Ligand atom A nbo:  -0.85581
Atom_a:  1 Atom_b:  12
C:\Users\George\Desktop\Research_UCLA\CIC\Computational Work\Project cluster version 2\project_catalyst_repurposing\structures_ligand_id\pd_me2_structures\ligand_xyz\ligand-138-p-o-41-ligand_xyz.txt
Starting node: 0
Ending node: 2
(-1.786177, 0.298773, 0.29522)   0
(-0.740768, 0.456655, 1.826692)   34
(0.669079, 0.470079, 1.773456)   33
(1.598418, 0.404757, 0.192769)   1
(0.812136, 0.973289, -0.974947)   2
ligand-139-p-o-42

C:\Users\George\AppData\Local\Temp\ipykernel_7832\386804788.py:583: DeprecationWarning:

to_plotly_figure is deprecated and will be removed in version 4.0.0. Use MolGraph.to_plotly() instead.

C:\Users\George\AppData\Local\Temp\ipykernel_7832\386804788.py:589: DeprecationWarning:

to_networkx_graph is deprecated and will be removed in version 4.0.0. Use MolGraph.to_networkx() instead.

Pd number index:  1
['P', 'Pd', 'C', 'H', 'H', 'H', 'C', 'H', 'H', 'H', 'P', 'O', 'C', 'C', 'C', 'C', 'H', 'C', 'C', 'H', 'H', 'H', 'C', 'C', 'C', 'C', 'H', 'C', 'C', 'H', 'H', 'H', 'O', 'O', 'C', 'H', 'H', 'H', 'C', 'H', 'H', 'H', 'C', 'C', 'C', 'C', 'C', 'H', 'C', 'H', 'H', 'H', 'C', 'C', 'C', 'C', 'C', 'H', 'C', 'H', 'H', 'H', 'C', 'C', 'C', 'C', 'C', 'H', 'C', 'H', 'H', 'H', 'O', 'O', 'C', 'H', 'H', 'C', 'H', 'H', 'C', 'H', 'H', 'C', 'H', 'H', 'O', 'O', 'C', 'H', 'H', 'H', 'C', 'H', 'H', 'H']
Ligand atom label:  1  Ligand atom B nbo:  0.94067
Ligand atom label:  12  Ligand atom A nbo:  -0.85464
Atom_a:  1 Atom_b:  12
C:\Users\George\Desktop\Research_UCLA\CIC\Computational Work\Project cluster version 2\project_catalyst_repurposing\structures_ligand_id\pd_me2_structures\ligand_xyz\ligand-139-p-o-42-ligand_xyz.txt
Starting node: 0
Ending node: 2
(2.706151, -0.096093, 0.225801)   0
(1.672087, 0.185338, 1.741637)   34
(0.262937, 0.130343, 1.688531)   33
(-0.689007, -0.317485, 0.179744)   1
(0.164259, -0.828594, -0.965797)   2
ligand-140-n-n-10

C:\Users\George\AppData\Local\Temp\ipykernel_7832\386804788.py:583: DeprecationWarning:

to_plotly_figure is deprecated and will be removed in version 4.0.0. Use MolGraph.to_plotly() instead.

C:\Users\George\AppData\Local\Temp\ipykernel_7832\386804788.py:589: DeprecationWarning:

to_networkx_graph is deprecated and will be removed in version 4.0.0. Use MolGraph.to_networkx() instead.

Pd number index:  0
['Pd', 'C', 'H', 'H', 'H', 'C', 'H', 'H', 'H', 'C', 'C', 'C', 'C', 'C', 'C', 'H', 'H', 'N', 'N', 'H', 'C', 'C', 'C', 'C', 'C', 'C', 'H', 'H', 'H', 'C', 'H', 'H', 'H', 'C', 'H', 'H', 'H', 'C', 'C', 'C', 'C', 'C', 'C', 'H', 'H', 'H', 'C', 'H', 'H', 'H', 'C', 'H', 'C', 'H', 'H', 'H', 'C', 'H', 'H', 'H', 'C', 'H', 'C', 'H', 'H', 'H', 'C', 'H', 'H', 'H']
Ligand atom label:  18  Ligand atom B nbo:  -0.50237
Ligand atom label:  19  Ligand atom A nbo:  -0.48353
Atom_a:  19 Atom_b:  18
C:\Users\George\Desktop\Research_UCLA\CIC\Computational Work\Project cluster version 2\project_catalyst_repurposing\structures_ligand_id\pd_me2_structures\ligand_xyz\ligand-140-n-n-10-ligand_xyz.txt
Ending node: 8
Starting node: 9
(1.485528, 0.424964, -0.243328)   9
(1.16325, 1.486515, -0.886707)   3
(-0.278969, 1.839986, -0.95349)   0
(-1.163727, 0.953351, -0.448761)   8
ligand-141-n-n-11
Pd number index:  0
['Pd', 'C', 'H', 'H', 'H', 'C', 'H', 'H', 'H', 'C', 'C', 'C', 'C', 'C', 'C', 'H', 'H', 'N', 'N', 'H', 'C', 'C', 'C', 'C', 'C', 'C', 'H', 'H', 'H', 'C', 'H', 'H', 'H', 'C', 'H', 'H', 'H', 'C', 'C', 'C', 'C', 'C', 'C', 'H', 'H', 'H', 'H', 'C', 'H', 'H', 'H', 'C', 'H', 'H', 'H']

C:\Users\George\AppData\Local\Temp\ipykernel_7832\386804788.py:583: DeprecationWarning:

to_plotly_figure is deprecated and will be removed in version 4.0.0. Use MolGraph.to_plotly() instead.

C:\Users\George\AppData\Local\Temp\ipykernel_7832\386804788.py:589: DeprecationWarning:

to_networkx_graph is deprecated and will be removed in version 4.0.0. Use MolGraph.to_networkx() instead.

Ligand atom label:  18  Ligand atom B nbo:  -0.49984
Ligand atom label:  19  Ligand atom A nbo:  -0.43606
Atom_a:  19 Atom_b:  18
C:\Users\George\Desktop\Research_UCLA\CIC\Computational Work\Project cluster version 2\project_catalyst_repurposing\structures_ligand_id\pd_me2_structures\ligand_xyz\ligand-141-n-n-11-ligand_xyz.txt
Ending node: 8
Starting node: 9
(-1.810626, 0.59519, 0.08782)   9
(-1.413803, 1.807395, 0.126003)   3
(0.014857, 2.125387, 0.141676)   0
(0.878693, 1.091269, 0.069387)   8
ligand-142-n-n-12

C:\Users\George\AppData\Local\Temp\ipykernel_7832\386804788.py:583: DeprecationWarning:

to_plotly_figure is deprecated and will be removed in version 4.0.0. Use MolGraph.to_plotly() instead.

C:\Users\George\AppData\Local\Temp\ipykernel_7832\386804788.py:589: DeprecationWarning:

to_networkx_graph is deprecated and will be removed in version 4.0.0. Use MolGraph.to_networkx() instead.

Pd number index:  0
['Pd', 'C', 'H', 'H', 'H', 'C', 'H', 'H', 'H', 'C', 'C', 'C', 'C', 'C', 'C', 'H', 'H', 'N', 'N', 'H', 'C', 'C', 'C', 'C', 'C', 'C', 'H', 'H', 'H', 'H', 'C', 'H', 'C', 'H', 'C', 'H', 'H', 'H', 'C', 'H', 'H', 'H', 'C', 'H', 'H', 'H', 'C', 'H', 'H', 'H', 'C', 'H', 'H', 'H']
Ligand atom label:  18  Ligand atom B nbo:  -0.50706
Ligand atom label:  19  Ligand atom A nbo:  -0.46395
Atom_a:  19 Atom_b:  18
C:\Users\George\Desktop\Research_UCLA\CIC\Computational Work\Project cluster version 2\project_catalyst_repurposing\structures_ligand_id\pd_me2_structures\ligand_xyz\ligand-142-n-n-12-ligand_xyz.txt
Ending node: 8
Starting node: 9
(0.401818, 0.47864, 0.189826)   9
(-0.230452, 1.287855, 0.945209)   3
(-1.690586, 1.248453, 1.039004)   0
(-2.335165, 0.322794, 0.301611)   8

C:\Users\George\AppData\Local\Temp\ipykernel_7832\386804788.py:583: DeprecationWarning:

to_plotly_figure is deprecated and will be removed in version 4.0.0. Use MolGraph.to_plotly() instead.

C:\Users\George\AppData\Local\Temp\ipykernel_7832\386804788.py:589: DeprecationWarning:

to_networkx_graph is deprecated and will be removed in version 4.0.0. Use MolGraph.to_networkx() instead.

ligand-143-n-n-13
Pd number index:  0
['Pd', 'C', 'H', 'H', 'H', 'C', 'H', 'H', 'H', 'C', 'C', 'C', 'C', 'C', 'C', 'H', 'H', 'N', 'N', 'H', 'C', 'C', 'C', 'C', 'C', 'C', 'H', 'H', 'H', 'C', 'H', 'C', 'H', 'C', 'H', 'H', 'H', 'C', 'H', 'H', 'H', 'C', 'H', 'H', 'H', 'C', 'H', 'H', 'H', 'C', 'H', 'H', 'H', 'C', 'H', 'H', 'H']
Ligand atom label:  18  Ligand atom B nbo:  -0.50122
Ligand atom label:  19  Ligand atom A nbo:  -0.47524
Atom_a:  19 Atom_b:  18
C:\Users\George\Desktop\Research_UCLA\CIC\Computational Work\Project cluster version 2\project_catalyst_repurposing\structures_ligand_id\pd_me2_structures\ligand_xyz\ligand-143-n-n-13-ligand_xyz.txt
Ending node: 8
Starting node: 9
(0.353846, 0.431798, -0.295553)   9
(-0.255464, 1.554082, -0.425786)   3
(-1.734831, 1.547607, -0.294588)   0
(-2.328258, 0.363527, -0.039514)   8
ligand-144-p-o-43

C:\Users\George\AppData\Local\Temp\ipykernel_7832\386804788.py:583: DeprecationWarning:

to_plotly_figure is deprecated and will be removed in version 4.0.0. Use MolGraph.to_plotly() instead.

C:\Users\George\AppData\Local\Temp\ipykernel_7832\386804788.py:589: DeprecationWarning:

to_networkx_graph is deprecated and will be removed in version 4.0.0. Use MolGraph.to_networkx() instead.

Pd number index:  28
['P', 'C', 'C', 'C', 'C', 'C', 'C', 'C', 'C', 'H', 'H', 'C', 'C', 'C', 'C', 'C', 'H', 'H', 'H', 'H', 'C', 'C', 'C', 'C', 'C', 'H', 'H', 'H', 'Pd', 'H', 'O', 'H', 'C', 'H', 'H', 'H', 'C', 'H', 'H', 'H', 'C', 'C', 'C', 'C', 'C', 'C', 'H', 'H', 'H', 'O', 'O', 'C', 'H', 'H', 'H', 'C', 'H', 'H', 'H', 'C', 'O', 'C', 'H', 'H', 'H', 'C', 'H', 'H', 'H', 'C', 'H', 'H', 'H']
Ligand atom label:  1  Ligand atom B nbo:  0.98994
Ligand atom label:  31  Ligand atom A nbo:  -0.54255
Atom_a:  1 Atom_b:  31
C:\Users\George\Desktop\Research_UCLA\CIC\Computational Work\Project cluster version 2\project_catalyst_repurposing\structures_ligand_id\pd_me2_structures\ligand_xyz\ligand-144-p-o-43-ligand_xyz.txt
Starting node: 0
Ending node: 29
(0.222436, 0.494341, -0.233579)   0
(-1.495835, 1.157642, -0.346247)   1
(-2.544168, 0.116727, -0.140432)   2
(-2.244096, -1.067929, -0.244079)   29
ligand-145-p-o-44

C:\Users\George\AppData\Local\Temp\ipykernel_7832\386804788.py:583: DeprecationWarning:

to_plotly_figure is deprecated and will be removed in version 4.0.0. Use MolGraph.to_plotly() instead.

C:\Users\George\AppData\Local\Temp\ipykernel_7832\386804788.py:589: DeprecationWarning:

to_networkx_graph is deprecated and will be removed in version 4.0.0. Use MolGraph.to_networkx() instead.

Pd number index:  28
['P', 'C', 'C', 'C', 'C', 'C', 'C', 'C', 'C', 'H', 'H', 'C', 'C', 'C', 'C', 'C', 'H', 'H', 'H', 'H', 'C', 'C', 'C', 'C', 'C', 'H', 'H', 'H', 'Pd', 'H', 'O', 'H', 'C', 'H', 'H', 'H', 'C', 'H', 'H', 'H', 'C', 'C', 'C', 'C', 'C', 'C', 'H', 'H', 'H', 'C', 'O', 'C', 'H', 'H', 'H', 'C', 'H', 'H', 'H', 'C', 'H', 'H', 'H', 'F', 'F']
Ligand atom label:  1  Ligand atom B nbo:  0.99104
Ligand atom label:  31  Ligand atom A nbo:  -0.53053
Atom_a:  1 Atom_b:  31
C:\Users\George\Desktop\Research_UCLA\CIC\Computational Work\Project cluster version 2\project_catalyst_repurposing\structures_ligand_id\pd_me2_structures\ligand_xyz\ligand-145-p-o-44-ligand_xyz.txt
Starting node: 0
Ending node: 29
(0.595248, 0.927179, 0.002314)   0
(-1.168601, 1.338466, -0.33015)   1
(-1.983307, 0.103144, -0.524927)   2
(-1.429634, -0.938889, -0.858672)   29
ligand-146-n-o-8

C:\Users\George\AppData\Local\Temp\ipykernel_7832\386804788.py:583: DeprecationWarning:

to_plotly_figure is deprecated and will be removed in version 4.0.0. Use MolGraph.to_plotly() instead.

C:\Users\George\AppData\Local\Temp\ipykernel_7832\386804788.py:589: DeprecationWarning:

to_networkx_graph is deprecated and will be removed in version 4.0.0. Use MolGraph.to_networkx() instead.

Pd number index:  31
['N', 'O', 'C', 'C', 'C', 'C', 'C', 'C', 'H', 'H', 'H', 'C', 'H', 'C', 'H', 'H', 'H', 'C', 'H', 'H', 'H', 'C', 'H', 'C', 'H', 'H', 'H', 'C', 'H', 'H', 'H', 'Pd', 'C', 'H', 'H', 'H', 'C', 'H', 'H', 'H', 'C', 'C', 'C', 'C', 'C', 'H', 'H', 'H', 'H', 'C', 'H', 'H', 'H']
Ligand atom label:  1  Ligand atom B nbo:  -0.63027
Ligand atom label:  2  Ligand atom A nbo:  -0.59412
Atom_a:  2 Atom_b:  1
C:\Users\George\Desktop\Research_UCLA\CIC\Computational Work\Project cluster version 2\project_catalyst_repurposing\structures_ligand_id\pd_me2_structures\ligand_xyz\ligand-146-n-o-8-ligand_xyz.txt

C:\Users\George\AppData\Local\Temp\ipykernel_7832\386804788.py:583: DeprecationWarning:

to_plotly_figure is deprecated and will be removed in version 4.0.0. Use MolGraph.to_plotly() instead.

C:\Users\George\AppData\Local\Temp\ipykernel_7832\386804788.py:589: DeprecationWarning:

to_networkx_graph is deprecated and will be removed in version 4.0.0. Use MolGraph.to_networkx() instead.

Ending node: 0
Starting node: 1
(-2.690167, -0.015348, -0.219612)   1
(-2.170113, 1.133136, -0.047933)   32
(-0.713732, 1.30701, 0.109548)   31
(0.059611, 0.276097, 0.147246)   0
ligand-147-n-o-10
Pd number index:  10
['N', 'O', 'C', 'C', 'C', 'C', 'C', 'C', 'H', 'H', 'Pd', 'C', 'H', 'H', 'H', 'C', 'H', 'H', 'H', 'C', 'C', 'C', 'C', 'C', 'H', 'H', 'H', 'H', 'C', 'H', 'H', 'H', 'C', 'H', 'H', 'H', 'C', 'H', 'H', 'H', 'C', 'H', 'H', 'H']
Ligand atom label:  1  Ligand atom A nbo:  -0.56707
Ligand atom label:  2  Ligand atom B nbo:  -0.58614
Atom_a:  1 Atom_b:  2
C:\Users\George\Desktop\Research_UCLA\CIC\Computational Work\Project cluster version 2\project_catalyst_repurposing\structures_ligand_id\pd_me2_structures\ligand_xyz\ligand-147-n-o-10-ligand_xyz.txt
Starting node: 0
Ending node: 1
(0.000456, 0.29138, -0.003845)   0
(-0.779747, 1.316771, 0.006023)   10
(-2.243753, 1.130351, 0.001005)   11
(-2.765621, -0.028699, -0.012757)   1
ligand-148-n-o-11

C:\Users\George\AppData\Local\Temp\ipykernel_7832\386804788.py:583: DeprecationWarning:

to_plotly_figure is deprecated and will be removed in version 4.0.0. Use MolGraph.to_plotly() instead.

C:\Users\George\AppData\Local\Temp\ipykernel_7832\386804788.py:589: DeprecationWarning:

to_networkx_graph is deprecated and will be removed in version 4.0.0. Use MolGraph.to_networkx() instead.

Pd number index:  9
['N', 'O', 'C', 'C', 'C', 'C', 'C', 'C', 'H', 'Pd', 'C', 'H', 'H', 'H', 'C', 'H', 'H', 'H', 'C', 'C', 'C', 'C', 'C', 'H', 'H', 'H', 'H', 'H', 'H', 'C', 'H', 'H', 'H', 'C', 'H', 'H', 'H', 'C', 'H', 'H', 'H']
Ligand atom label:  1  Ligand atom A nbo:  -0.47744
Ligand atom label:  2  Ligand atom B nbo:  -0.70267
Atom_a:  1 Atom_b:  2
C:\Users\George\Desktop\Research_UCLA\CIC\Computational Work\Project cluster version 2\project_catalyst_repurposing\structures_ligand_id\pd_me2_structures\ligand_xyz\ligand-148-n-o-11-ligand_xyz.txt
Starting node: 0
Ending node: 1
(0.009529, 0.312518, -0.003159)   0
(-0.75662, 1.335684, 0.123408)   9
(-2.217178, 1.167137, 0.088378)   10
(-2.758907, 0.03869, -0.124071)   1

C:\Users\George\AppData\Local\Temp\ipykernel_7832\386804788.py:583: DeprecationWarning:

to_plotly_figure is deprecated and will be removed in version 4.0.0. Use MolGraph.to_plotly() instead.

C:\Users\George\AppData\Local\Temp\ipykernel_7832\386804788.py:589: DeprecationWarning:

to_networkx_graph is deprecated and will be removed in version 4.0.0. Use MolGraph.to_networkx() instead.

ligand-149-n-o-12
Pd number index:  10
['N', 'O', 'C', 'C', 'C', 'C', 'C', 'C', 'H', 'H', 'Pd', 'C', 'H', 'H', 'H', 'C', 'H', 'H', 'H', 'C', 'C', 'C', 'C', 'C', 'H', 'H', 'H', 'H', 'H', 'H', 'C', 'H', 'H', 'H', 'C', 'H', 'H', 'H']
Ligand atom label:  1  Ligand atom A nbo:  -0.56058
Ligand atom label:  2  Ligand atom B nbo:  -0.5861
Atom_a:  1 Atom_b:  2
C:\Users\George\Desktop\Research_UCLA\CIC\Computational Work\Project cluster version 2\project_catalyst_repurposing\structures_ligand_id\pd_me2_structures\ligand_xyz\ligand-149-n-o-12-ligand_xyz.txt
Starting node: 0
Ending node: 1
(-0.134969, -0.304995, -0.021992)   0
(0.626834, -1.348276, -0.008493)   10
(2.094348, -1.184367, -0.009123)   11
(2.640207, -0.040455, -0.085868)   1
ligand-150-n-o-13

C:\Users\George\AppData\Local\Temp\ipykernel_7832\386804788.py:583: DeprecationWarning:

to_plotly_figure is deprecated and will be removed in version 4.0.0. Use MolGraph.to_plotly() instead.

C:\Users\George\AppData\Local\Temp\ipykernel_7832\386804788.py:589: DeprecationWarning:

to_networkx_graph is deprecated and will be removed in version 4.0.0. Use MolGraph.to_networkx() instead.

Pd number index:  10
['N', 'O', 'C', 'C', 'C', 'C', 'C', 'C', 'H', 'H', 'Pd', 'C', 'H', 'H', 'H', 'C', 'H', 'H', 'H', 'C', 'C', 'C', 'C', 'C', 'H', 'C', 'C', 'H', 'H', 'H', 'C', 'C', 'C', 'C', 'H', 'C', 'H', 'C', 'H', 'H', 'H', 'C', 'H', 'C', 'H', 'H', 'H', 'C', 'H', 'H', 'H', 'C', 'H', 'C', 'H', 'H', 'H', 'C', 'H', 'H', 'H', 'H']
Ligand atom label:  1  Ligand atom A nbo:  -0.58044
Ligand atom label:  2  Ligand atom B nbo:  -0.53805
Atom_a:  2 Atom_b:  1
C:\Users\George\Desktop\Research_UCLA\CIC\Computational Work\Project cluster version 2\project_catalyst_repurposing\structures_ligand_id\pd_me2_structures\ligand_xyz\ligand-150-n-o-13-ligand_xyz.txt

C:\Users\George\AppData\Local\Temp\ipykernel_7832\386804788.py:583: DeprecationWarning:

to_plotly_figure is deprecated and will be removed in version 4.0.0. Use MolGraph.to_plotly() instead.

C:\Users\George\AppData\Local\Temp\ipykernel_7832\386804788.py:589: DeprecationWarning:

to_networkx_graph is deprecated and will be removed in version 4.0.0. Use MolGraph.to_networkx() instead.

Ending node: 0
Starting node: 1
(-1.529588, -0.674157, -0.013206)   1
(-1.457491, 0.572609, -0.059395)   11
(-0.073038, 1.156416, -0.167053)   10
(0.873035, 0.240481, -0.188562)   0
ligand-151-n-o-14
Pd number index:  10
['N', 'O', 'C', 'C', 'C', 'C', 'C', 'C', 'H', 'H', 'Pd', 'C', 'H', 'H', 'H', 'C', 'H', 'H', 'H', 'C', 'C', 'C', 'C', 'C', 'H', 'C', 'C', 'H', 'H', 'H', 'C', 'C', 'C', 'C', 'H', 'C', 'C', 'H', 'H', 'C', 'H', 'C', 'H', 'H', 'H', 'C', 'H', 'H', 'H', 'C', 'H', 'C', 'H', 'H', 'H', 'C', 'H', 'H', 'H', 'H', 'H', 'O', 'C', 'H', 'H', 'H']
Ligand atom label:  1  Ligand atom A nbo:  -0.57948
Ligand atom label:  2  Ligand atom B nbo:  -0.53791
Atom_a:  2 Atom_b:  1
C:\Users\George\Desktop\Research_UCLA\CIC\Computational Work\Project cluster version 2\project_catalyst_repurposing\structures_ligand_id\pd_me2_structures\ligand_xyz\ligand-151-n-o-14-ligand_xyz.txt
Ending node: 0
Starting node: 1
(-1.122575, -0.417846, -0.111099)   1
(-0.910046, 0.814212, -0.101981)   11
(0.533451, 1.240087, -0.148031)   10
(1.371204, 0.223554, -0.179785)   0

C:\Users\George\AppData\Local\Temp\ipykernel_7832\386804788.py:583: DeprecationWarning:

to_plotly_figure is deprecated and will be removed in version 4.0.0. Use MolGraph.to_plotly() instead.

C:\Users\George\AppData\Local\Temp\ipykernel_7832\386804788.py:589: DeprecationWarning:

to_networkx_graph is deprecated and will be removed in version 4.0.0. Use MolGraph.to_networkx() instead.

ligand-152-n-o-15
Pd number index:  10
['N', 'O', 'C', 'C', 'C', 'C', 'C', 'C', 'H', 'H', 'Pd', 'C', 'H', 'H', 'H', 'C', 'H', 'H', 'H', 'C', 'C', 'C', 'C', 'C', 'H', 'C', 'C', 'H', 'H', 'H', 'C', 'C', 'C', 'C', 'H', 'C', 'C', 'H', 'H', 'C', 'H', 'C', 'H', 'H', 'H', 'C', 'H', 'H', 'H', 'C', 'H', 'C', 'H', 'H', 'H', 'C', 'H', 'H', 'H', 'H', 'H', 'C', 'F', 'F', 'F']
Ligand atom label:  1  Ligand atom A nbo:  -0.57762
Ligand atom label:  2  Ligand atom B nbo:  -0.53946
Atom_a:  2 Atom_b:  1
C:\Users\George\Desktop\Research_UCLA\CIC\Computational Work\Project cluster version 2\project_catalyst_repurposing\structures_ligand_id\pd_me2_structures\ligand_xyz\ligand-152-n-o-15-ligand_xyz.txt

C:\Users\George\AppData\Local\Temp\ipykernel_7832\386804788.py:583: DeprecationWarning:

to_plotly_figure is deprecated and will be removed in version 4.0.0. Use MolGraph.to_plotly() instead.

C:\Users\George\AppData\Local\Temp\ipykernel_7832\386804788.py:589: DeprecationWarning:

to_networkx_graph is deprecated and will be removed in version 4.0.0. Use MolGraph.to_networkx() instead.

Ending node: 0
Starting node: 1
(-0.678819, -0.400685, -0.130886)   1
(-0.454999, 0.828241, -0.140127)   11
(0.993242, 1.241082, -0.197832)   10
(1.820721, 0.219056, -0.194509)   0
ligand-153-p-o-45
Pd number index:  22
['P', 'C', 'C', 'C', 'C', 'C', 'C', 'C', 'C', 'C', 'H', 'H', 'H', 'H', 'C', 'C', 'C', 'C', 'C', 'H', 'H', 'H', 'Pd', 'H', 'O', 'H', 'C', 'H', 'H', 'H', 'C', 'H', 'H', 'H', 'C', 'C', 'C', 'C', 'H', 'C', 'H', 'C', 'H', 'H', 'H', 'H', 'H']
Ligand atom label:  1  Ligand atom B nbo:  0.9871
Ligand atom label:  25  Ligand atom A nbo:  -0.67444
Atom_a:  1 Atom_b:  25
C:\Users\George\Desktop\Research_UCLA\CIC\Computational Work\Project cluster version 2\project_catalyst_repurposing\structures_ligand_id\pd_me2_structures\ligand_xyz\ligand-153-p-o-45-ligand_xyz.txt
Starting node: 0
Ending node: 23
(0.741441, 0.15705, 0.014232)   0
(-0.828327, 0.969127, -0.126845)   1
(-1.94701, 0.157292, 0.068455)   2
(-1.918697, -1.079791, 0.348269)   23
ligand-154-p-o-46

C:\Users\George\AppData\Local\Temp\ipykernel_7832\386804788.py:583: DeprecationWarning:

to_plotly_figure is deprecated and will be removed in version 4.0.0. Use MolGraph.to_plotly() instead.

C:\Users\George\AppData\Local\Temp\ipykernel_7832\386804788.py:589: DeprecationWarning:

to_networkx_graph is deprecated and will be removed in version 4.0.0. Use MolGraph.to_networkx() instead.

Pd number index:  22
['P', 'C', 'C', 'C', 'C', 'C', 'C', 'C', 'C', 'C', 'H', 'H', 'H', 'H', 'C', 'C', 'C', 'C', 'C', 'H', 'H', 'H', 'Pd', 'H', 'O', 'H', 'C', 'H', 'H', 'H', 'C', 'H', 'H', 'H', 'H', 'C', 'F', 'F', 'F', 'O', 'O', 'C', 'H', 'H', 'C', 'H', 'H', 'H', 'C']
Ligand atom label:  1  Ligand atom B nbo:  1.01308
Ligand atom label:  25  Ligand atom A nbo:  -0.64615
Atom_a:  1 Atom_b:  25
C:\Users\George\Desktop\Research_UCLA\CIC\Computational Work\Project cluster version 2\project_catalyst_repurposing\structures_ligand_id\pd_me2_structures\ligand_xyz\ligand-154-p-o-46-ligand_xyz.txt
Starting node: 0
Ending node: 23
(-0.092429, 0.554392, 0.029645)   0
(0.133282, -1.231015, -0.171707)   1
(1.487227, -1.627551, -0.03171)   2
(2.454315, -0.867528, 0.162361)   23
ligand-155-p-o-47

C:\Users\George\AppData\Local\Temp\ipykernel_7832\386804788.py:583: DeprecationWarning:

to_plotly_figure is deprecated and will be removed in version 4.0.0. Use MolGraph.to_plotly() instead.

C:\Users\George\AppData\Local\Temp\ipykernel_7832\386804788.py:589: DeprecationWarning:

to_networkx_graph is deprecated and will be removed in version 4.0.0. Use MolGraph.to_networkx() instead.

Pd number index:  22
['P', 'C', 'C', 'C', 'C', 'C', 'C', 'C', 'C', 'C', 'H', 'H', 'H', 'H', 'C', 'C', 'C', 'C', 'C', 'H', 'H', 'H', 'Pd', 'H', 'O', 'H', 'C', 'H', 'H', 'H', 'C', 'H', 'H', 'H', 'H', 'O', 'O', 'C', 'H', 'H', 'C', 'H', 'H', 'H', 'C', 'C', 'C', 'C', 'F', 'F', 'F', 'F', 'F', 'F', 'F']
Ligand atom label:  1  Ligand atom B nbo:  1.01295
Ligand atom label:  25  Ligand atom A nbo:  -0.64568
Atom_a:  1 Atom_b:  25
C:\Users\George\Desktop\Research_UCLA\CIC\Computational Work\Project cluster version 2\project_catalyst_repurposing\structures_ligand_id\pd_me2_structures\ligand_xyz\ligand-155-p-o-47-ligand_xyz.txt
Starting node: 0
Ending node: 23
(1.397969, -0.375566, -0.013172)   0
(-0.034072, 0.735289, -0.05549)   1
(-1.255983, 0.066249, 0.175609)   2
(-1.394944, -1.149775, 0.427311)   23
ligand-156-p-o-48

C:\Users\George\AppData\Local\Temp\ipykernel_7832\386804788.py:583: DeprecationWarning:

to_plotly_figure is deprecated and will be removed in version 4.0.0. Use MolGraph.to_plotly() instead.

C:\Users\George\AppData\Local\Temp\ipykernel_7832\386804788.py:589: DeprecationWarning:

to_networkx_graph is deprecated and will be removed in version 4.0.0. Use MolGraph.to_networkx() instead.

Pd number index:  22
['P', 'C', 'C', 'C', 'C', 'C', 'C', 'C', 'C', 'C', 'H', 'H', 'H', 'H', 'C', 'C', 'C', 'C', 'C', 'H', 'H', 'H', 'Pd', 'H', 'O', 'H', 'C', 'H', 'H', 'H', 'C', 'H', 'H', 'H', 'H', 'O', 'O', 'C', 'H', 'H', 'C', 'H', 'H', 'H', 'C', 'C', 'C', 'C', 'C', 'C', 'C', 'F', 'F', 'F', 'F', 'F']
Ligand atom label:  1  Ligand atom B nbo:  0.99524
Ligand atom label:  25  Ligand atom A nbo:  -0.64302
Atom_a:  1 Atom_b:  25
C:\Users\George\Desktop\Research_UCLA\CIC\Computational Work\Project cluster version 2\project_catalyst_repurposing\structures_ligand_id\pd_me2_structures\ligand_xyz\ligand-156-p-o-48-ligand_xyz.txt
Starting node: 0
Ending node: 23
(-1.553905, 0.181816, 0.050069)   0
(0.157335, -0.313146, -0.244851)   1
(1.104588, 0.661937, 0.1432)   2
(0.860788, 1.802486, 0.590227)   23
ligand-157-p-o-49

C:\Users\George\AppData\Local\Temp\ipykernel_7832\386804788.py:583: DeprecationWarning:

to_plotly_figure is deprecated and will be removed in version 4.0.0. Use MolGraph.to_plotly() instead.

C:\Users\George\AppData\Local\Temp\ipykernel_7832\386804788.py:589: DeprecationWarning:

to_networkx_graph is deprecated and will be removed in version 4.0.0. Use MolGraph.to_networkx() instead.

Pd number index:  22
['P', 'C', 'C', 'C', 'C', 'C', 'C', 'C', 'C', 'C', 'H', 'H', 'H', 'H', 'C', 'C', 'C', 'C', 'C', 'H', 'H', 'H', 'Pd', 'H', 'O', 'H', 'C', 'H', 'H', 'H', 'C', 'H', 'H', 'H', 'H', 'O', 'O', 'C', 'C', 'H', 'H', 'H', 'C', 'C', 'C', 'C', 'C', 'C', 'C', 'F', 'F', 'F', 'F', 'F', 'C', 'H', 'H', 'H', 'C', 'H', 'H', 'H']
Ligand atom label:  1  Ligand atom B nbo:  1.01418
Ligand atom label:  25  Ligand atom A nbo:  -0.63376
Atom_a:  1 Atom_b:  25
C:\Users\George\Desktop\Research_UCLA\CIC\Computational Work\Project cluster version 2\project_catalyst_repurposing\structures_ligand_id\pd_me2_structures\ligand_xyz\ligand-157-p-o-49-ligand_xyz.txt
Starting node: 0
Ending node: 23
(1.510592, -0.499681, 0.10961)   0
(-0.169887, 0.132692, -0.052902)   1
(-1.168722, -0.851886, 0.113104)   2
(-0.986545, -2.072697, 0.308889)   23
ligand-158-p-o-50

C:\Users\George\AppData\Local\Temp\ipykernel_7832\386804788.py:583: DeprecationWarning:

to_plotly_figure is deprecated and will be removed in version 4.0.0. Use MolGraph.to_plotly() instead.

C:\Users\George\AppData\Local\Temp\ipykernel_7832\386804788.py:589: DeprecationWarning:

to_networkx_graph is deprecated and will be removed in version 4.0.0. Use MolGraph.to_networkx() instead.

Pd number index:  22
['P', 'C', 'C', 'C', 'C', 'C', 'C', 'C', 'C', 'C', 'H', 'H', 'H', 'H', 'C', 'C', 'C', 'C', 'C', 'H', 'H', 'H', 'Pd', 'H', 'O', 'H', 'C', 'H', 'H', 'H', 'C', 'H', 'H', 'H', 'H', 'O', 'O', 'C', 'C', 'C', 'C', 'C', 'C', 'C', 'C', 'F', 'F', 'F', 'F', 'F', 'H', 'H', 'C', 'C', 'C', 'C', 'H', 'C', 'H', 'C', 'H', 'H', 'H']
Ligand atom label:  1  Ligand atom B nbo:  1.00228
Ligand atom label:  25  Ligand atom A nbo:  -0.63654
Atom_a:  1 Atom_b:  25
C:\Users\George\Desktop\Research_UCLA\CIC\Computational Work\Project cluster version 2\project_catalyst_repurposing\structures_ligand_id\pd_me2_structures\ligand_xyz\ligand-158-p-o-50-ligand_xyz.txt
Starting node: 0
Ending node: 23
(-1.058576, 1.199776, 0.088566)   0
(0.363137, 0.093963, 0.242715)   1
(1.577865, 0.660572, -0.212259)   2
(1.725908, 1.786712, -0.728966)   23
ligand-159-p-o-51

C:\Users\George\AppData\Local\Temp\ipykernel_7832\386804788.py:583: DeprecationWarning:

to_plotly_figure is deprecated and will be removed in version 4.0.0. Use MolGraph.to_plotly() instead.

C:\Users\George\AppData\Local\Temp\ipykernel_7832\386804788.py:589: DeprecationWarning:

to_networkx_graph is deprecated and will be removed in version 4.0.0. Use MolGraph.to_networkx() instead.

Pd number index:  22
['P', 'C', 'C', 'C', 'C', 'C', 'C', 'C', 'C', 'C', 'H', 'H', 'H', 'H', 'C', 'C', 'C', 'C', 'C', 'H', 'H', 'H', 'Pd', 'H', 'O', 'H', 'C', 'H', 'H', 'H', 'C', 'H', 'H', 'H', 'H', 'O', 'O', 'C', 'C', 'H', 'H', 'C', 'C', 'C', 'C', 'H', 'C', 'H', 'C', 'H', 'H', 'H', 'C', 'H', 'H', 'H']
Ligand atom label:  1  Ligand atom B nbo:  1.01126
Ligand atom label:  25  Ligand atom A nbo:  -0.64528
Atom_a:  1 Atom_b:  25
C:\Users\George\Desktop\Research_UCLA\CIC\Computational Work\Project cluster version 2\project_catalyst_repurposing\structures_ligand_id\pd_me2_structures\ligand_xyz\ligand-159-p-o-51-ligand_xyz.txt

C:\Users\George\AppData\Local\Temp\ipykernel_7832\386804788.py:583: DeprecationWarning:

to_plotly_figure is deprecated and will be removed in version 4.0.0. Use MolGraph.to_plotly() instead.

C:\Users\George\AppData\Local\Temp\ipykernel_7832\386804788.py:589: DeprecationWarning:

to_networkx_graph is deprecated and will be removed in version 4.0.0. Use MolGraph.to_networkx() instead.

Starting node: 0
Ending node: 23
(0.717053, -0.340684, 0.11867)   0
(-0.798185, 0.596321, -0.168914)   1
(-1.980285, -0.198032, -0.085581)   2
(-1.986203, -1.447795, 0.0252)   23
ligand-160-p-o-52
Pd number index:  22
['P', 'C', 'C', 'C', 'C', 'C', 'C', 'C', 'C', 'C', 'H', 'H', 'H', 'H', 'C', 'C', 'C', 'C', 'C', 'H', 'H', 'H', 'Pd', 'H', 'O', 'H', 'C', 'H', 'H', 'H', 'C', 'H', 'H', 'H', 'H', 'O', 'O', 'C', 'C', 'H', 'H', 'C', 'H', 'H', 'H', 'C', 'H', 'H', 'H']
Ligand atom label:  1  Ligand atom B nbo:  1.01061
Ligand atom label:  25  Ligand atom A nbo:  -0.65379
Atom_a:  1 Atom_b:  25
C:\Users\George\Desktop\Research_UCLA\CIC\Computational Work\Project cluster version 2\project_catalyst_repurposing\structures_ligand_id\pd_me2_structures\ligand_xyz\ligand-160-p-o-52-ligand_xyz.txt

C:\Users\George\AppData\Local\Temp\ipykernel_7832\386804788.py:583: DeprecationWarning:

to_plotly_figure is deprecated and will be removed in version 4.0.0. Use MolGraph.to_plotly() instead.

C:\Users\George\AppData\Local\Temp\ipykernel_7832\386804788.py:589: DeprecationWarning:

to_networkx_graph is deprecated and will be removed in version 4.0.0. Use MolGraph.to_networkx() instead.

Starting node: 0
Ending node: 23
(-0.186004, 0.064228, -0.079107)   0
(0.113452, -1.492621, 0.77519)   1
(-1.069221, -2.256696, 1.029321)   2
(-2.22027, -1.89479, 0.693315)   23
ligand-161-n-o-16
Pd number index:  41
['N', 'C', 'H', 'C', 'C', 'C', 'C', 'H', 'C', 'C', 'H', 'O', 'C', 'C', 'C', 'C', 'C', 'C', 'H', 'H', 'H', 'C', 'H', 'C', 'H', 'H', 'H', 'C', 'H', 'H', 'H', 'C', 'H', 'C', 'H', 'H', 'H', 'C', 'H', 'H', 'H', 'Pd', 'C', 'H', 'H', 'H', 'C', 'H', 'H', 'H', 'C', 'C', 'H', 'H', 'H', 'C', 'H', 'H', 'H', 'C', 'H', 'H', 'H', 'C', 'O', 'H', 'C', 'C', 'C', 'C', 'H', 'C', 'H', 'C', 'H', 'H', 'H', 'C', 'C', 'C', 'C', 'H', 'C', 'H', 'C', 'H', 'H', 'H']
Ligand atom label:  1  Ligand atom B nbo:  -0.53704
Ligand atom label:  12  Ligand atom A nbo:  -0.70711
Atom_a:  1 Atom_b:  12
C:\Users\George\Desktop\Research_UCLA\CIC\Computational Work\Project cluster version 2\project_catalyst_repurposing\structures_ligand_id\pd_me2_structures\ligand_xyz\ligand-161-n-o-16-ligand_xyz.txt
Starting node: 0
Ending node: 11
(2.334829, 0.469857, -0.261722)   0
(1.49813, 1.444102, -0.155938)   1
(0.057064, 1.407726, -0.15284)   3
(-0.713891, 0.241272, -0.489832)   5
(-0.212514, -0.860128, -0.886278)   11
ligand-162-n-o-17

C:\Users\George\AppData\Local\Temp\ipykernel_7832\386804788.py:583: DeprecationWarning:

to_plotly_figure is deprecated and will be removed in version 4.0.0. Use MolGraph.to_plotly() instead.

C:\Users\George\AppData\Local\Temp\ipykernel_7832\386804788.py:589: DeprecationWarning:

to_networkx_graph is deprecated and will be removed in version 4.0.0. Use MolGraph.to_networkx() instead.

Pd number index:  41
['N', 'C', 'H', 'C', 'C', 'C', 'C', 'H', 'C', 'C', 'H', 'O', 'C', 'C', 'C', 'C', 'C', 'C', 'H', 'H', 'H', 'C', 'H', 'C', 'H', 'H', 'H', 'C', 'H', 'H', 'H', 'C', 'H', 'C', 'H', 'H', 'H', 'C', 'H', 'H', 'H', 'Pd', 'C', 'H', 'H', 'H', 'C', 'H', 'H', 'H', 'C', 'C', 'H', 'H', 'H', 'C', 'H', 'H', 'H', 'C', 'H', 'H', 'H', 'C', 'O', 'C', 'C', 'C', 'C', 'H', 'C', 'H', 'C', 'H', 'H', 'H', 'C', 'C', 'C', 'C', 'H', 'C', 'H', 'C', 'H', 'H', 'H', 'C', 'H', 'H', 'H']
Ligand atom label:  1  Ligand atom B nbo:  -0.54066
Ligand atom label:  12  Ligand atom A nbo:  -0.64172
Atom_a:  1 Atom_b:  12
C:\Users\George\Desktop\Research_UCLA\CIC\Computational Work\Project cluster version 2\project_catalyst_repurposing\structures_ligand_id\pd_me2_structures\ligand_xyz\ligand-162-n-o-17-ligand_xyz.txt
Starting node: 0
Ending node: 11
(2.433686, 0.427786, -0.181179)   0
(1.590438, 1.38249, 0.034839)   1
(0.153314, 1.358507, 0.073267)   3
(-0.640497, 0.171463, -0.187463)   5
(-0.150475, -0.962673, -0.403748)   11
ligand-163-n-n-14

C:\Users\George\AppData\Local\Temp\ipykernel_7832\386804788.py:583: DeprecationWarning:

to_plotly_figure is deprecated and will be removed in version 4.0.0. Use MolGraph.to_plotly() instead.

C:\Users\George\AppData\Local\Temp\ipykernel_7832\386804788.py:589: DeprecationWarning:

to_networkx_graph is deprecated and will be removed in version 4.0.0. Use MolGraph.to_networkx() instead.

Pd number index:  0
['Pd', 'C', 'C', 'N', 'N', 'C', 'C', 'C', 'C', 'C', 'C', 'H', 'H', 'C', 'C', 'C', 'C', 'C', 'C', 'H', 'H', 'C', 'H', 'H', 'H', 'C', 'H', 'H', 'H', 'C', 'C', 'C', 'C', 'C', 'C', 'H', 'C', 'C', 'C', 'C', 'H', 'H', 'H', 'H', 'H', 'C', 'C', 'C', 'C', 'H', 'C', 'H', 'C', 'H', 'H', 'H', 'C', 'C', 'C', 'C', 'H', 'C', 'H', 'C', 'H', 'H', 'H', 'C', 'C', 'C', 'C', 'H', 'C', 'H', 'C', 'H', 'H', 'H', 'C', 'C', 'C', 'C', 'H', 'C', 'H', 'C', 'H', 'H', 'H', 'C', 'H', 'H', 'H', 'C', 'H', 'H', 'H']
Ligand atom label:  4  Ligand atom B nbo:  -0.46139
Ligand atom label:  5  Ligand atom A nbo:  -0.45797
Atom_a:  5 Atom_b:  4
C:\Users\George\Desktop\Research_UCLA\CIC\Computational Work\Project cluster version 2\project_catalyst_repurposing\structures_ligand_id\pd_me2_structures\ligand_xyz\ligand-163-n-n-14-ligand_xyz.txt
Ending node: 2
Starting node: 3
(1.355899, 0.000328, -0.3221)   3
(0.689229, 5.3e-05, 0.775193)   1
(-0.809827, -7.9e-05, 0.736593)   0
(-1.413154, -0.000209, -0.392975)   2
ligand-164-n-n-15

C:\Users\George\AppData\Local\Temp\ipykernel_7832\386804788.py:583: DeprecationWarning:

to_plotly_figure is deprecated and will be removed in version 4.0.0. Use MolGraph.to_plotly() instead.

C:\Users\George\AppData\Local\Temp\ipykernel_7832\386804788.py:589: DeprecationWarning:

to_networkx_graph is deprecated and will be removed in version 4.0.0. Use MolGraph.to_networkx() instead.

Pd number index:  0
['Pd', 'C', 'C', 'N', 'N', 'C', 'C', 'C', 'C', 'C', 'C', 'H', 'H', 'C', 'C', 'C', 'C', 'C', 'C', 'H', 'H', 'C', 'H', 'H', 'H', 'C', 'H', 'H', 'H', 'C', 'C', 'C', 'C', 'C', 'C', 'H', 'C', 'C', 'C', 'C', 'H', 'H', 'H', 'H', 'H', 'C', 'C', 'C', 'C', 'H', 'C', 'H', 'C', 'H', 'H', 'C', 'C', 'C', 'C', 'H', 'C', 'H', 'C', 'H', 'H', 'C', 'C', 'C', 'C', 'H', 'C', 'H', 'C', 'H', 'H', 'C', 'C', 'C', 'C', 'H', 'C', 'H', 'C', 'H', 'H', 'C', 'H', 'H', 'H', 'C', 'H', 'H', 'H', 'F', 'F', 'F', 'F']
Ligand atom label:  4  Ligand atom B nbo:  -0.5416
Ligand atom label:  5  Ligand atom A nbo:  -0.53314
Atom_a:  5 Atom_b:  4
C:\Users\George\Desktop\Research_UCLA\CIC\Computational Work\Project cluster version 2\project_catalyst_repurposing\structures_ligand_id\pd_me2_structures\ligand_xyz\ligand-164-n-n-15-ligand_xyz.txt
Ending node: 2
Starting node: 3
(0.064754, 1.38559, -0.166945)   3
(0.348945, 0.659206, 0.849124)   1
(0.175323, -0.82346, 0.745446)   0
(-0.06164, -1.348984, -0.39936)   2
ligand-165-n-n-16

C:\Users\George\AppData\Local\Temp\ipykernel_7832\386804788.py:583: DeprecationWarning:

to_plotly_figure is deprecated and will be removed in version 4.0.0. Use MolGraph.to_plotly() instead.

C:\Users\George\AppData\Local\Temp\ipykernel_7832\386804788.py:589: DeprecationWarning:

to_networkx_graph is deprecated and will be removed in version 4.0.0. Use MolGraph.to_networkx() instead.

Pd number index:  0
['Pd', 'C', 'C', 'N', 'N', 'C', 'C', 'C', 'C', 'C', 'C', 'H', 'H', 'C', 'C', 'C', 'C', 'C', 'C', 'H', 'H', 'C', 'H', 'H', 'H', 'C', 'H', 'H', 'H', 'C', 'C', 'C', 'C', 'C', 'C', 'H', 'C', 'C', 'C', 'C', 'H', 'H', 'H', 'H', 'H', 'C', 'C', 'C', 'C', 'H', 'C', 'H', 'C', 'C', 'C', 'C', 'C', 'H', 'C', 'H', 'C', 'C', 'C', 'C', 'C', 'H', 'C', 'H', 'C', 'C', 'C', 'C', 'C', 'H', 'C', 'H', 'C', 'C', 'H', 'H', 'H', 'C', 'H', 'H', 'H', 'H', 'H', 'H', 'H', 'F', 'F', 'F', 'F', 'F', 'F', 'F', 'F']
Ligand atom label:  4  Ligand atom B nbo:  -0.46379
Ligand atom label:  5  Ligand atom A nbo:  -0.46778
Atom_a:  4 Atom_b:  5
C:\Users\George\Desktop\Research_UCLA\CIC\Computational Work\Project cluster version 2\project_catalyst_repurposing\structures_ligand_id\pd_me2_structures\ligand_xyz\ligand-165-n-n-16-ligand_xyz.txt
Starting node: 2
Ending node: 3
(-0.084231, -1.286099, -0.44143)   2
(-0.057272, -0.921669, 0.787237)   0
(0.03132, 0.535911, 1.105648)   1
(0.079714, 1.370284, 0.13715)   3
ligand-166-n-n-17

C:\Users\George\AppData\Local\Temp\ipykernel_7832\386804788.py:583: DeprecationWarning:

to_plotly_figure is deprecated and will be removed in version 4.0.0. Use MolGraph.to_plotly() instead.

C:\Users\George\AppData\Local\Temp\ipykernel_7832\386804788.py:589: DeprecationWarning:

to_networkx_graph is deprecated and will be removed in version 4.0.0. Use MolGraph.to_networkx() instead.

Pd number index:  0
['Pd', 'C', 'C', 'N', 'N', 'C', 'C', 'C', 'C', 'C', 'C', 'H', 'H', 'C', 'C', 'C', 'C', 'C', 'C', 'H', 'H', 'C', 'H', 'H', 'H', 'C', 'H', 'H', 'H', 'C', 'C', 'C', 'C', 'C', 'C', 'H', 'C', 'C', 'C', 'C', 'H', 'H', 'H', 'H', 'H', 'C', 'C', 'C', 'C', 'H', 'C', 'H', 'C', 'C', 'C', 'C', 'C', 'H', 'C', 'H', 'C', 'C', 'C', 'C', 'C', 'H', 'C', 'H', 'C', 'C', 'C', 'C', 'C', 'H', 'C', 'H', 'C', 'C', 'H', 'H', 'H', 'C', 'H', 'H', 'H', 'F', 'F', 'F', 'F', 'F', 'F', 'F', 'F', 'F', 'F', 'F', 'F']
Ligand atom label:  4  Ligand atom B nbo:  -0.52536
Ligand atom label:  5  Ligand atom A nbo:  -0.51641
Atom_a:  5 Atom_b:  4
C:\Users\George\Desktop\Research_UCLA\CIC\Computational Work\Project cluster version 2\project_catalyst_repurposing\structures_ligand_id\pd_me2_structures\ligand_xyz\ligand-166-n-n-17-ligand_xyz.txt
Ending node: 2
Starting node: 3
(-0.343498, 1.325478, 0.143592)   3
(-0.218329, 0.50537, 1.118843)   1
(0.155007, -0.912274, 0.823272)   0
(0.3595, -1.258875, -0.393893)   2
ligand-167-n-n-18

C:\Users\George\AppData\Local\Temp\ipykernel_7832\386804788.py:583: DeprecationWarning:

to_plotly_figure is deprecated and will be removed in version 4.0.0. Use MolGraph.to_plotly() instead.

C:\Users\George\AppData\Local\Temp\ipykernel_7832\386804788.py:589: DeprecationWarning:

to_networkx_graph is deprecated and will be removed in version 4.0.0. Use MolGraph.to_networkx() instead.

Pd number index:  0
['Pd', 'C', 'C', 'N', 'N', 'C', 'C', 'C', 'C', 'C', 'C', 'H', 'H', 'C', 'C', 'C', 'C', 'C', 'C', 'H', 'H', 'C', 'H', 'H', 'H', 'C', 'H', 'H', 'H', 'C', 'C', 'C', 'C', 'C', 'C', 'H', 'C', 'C', 'C', 'C', 'H', 'H', 'H', 'H', 'H', 'C', 'C', 'C', 'C', 'C', 'C', 'C', 'C', 'C', 'C', 'C', 'C', 'C', 'C', 'C', 'C', 'C', 'C', 'C', 'C', 'C', 'C', 'C', 'C', 'C', 'H', 'H', 'H', 'C', 'H', 'H', 'H', 'F', 'F', 'F', 'F', 'H', 'H', 'H', 'H', 'H', 'H', 'H', 'H', 'F', 'F', 'F', 'F', 'F', 'F', 'F', 'F']
Ligand atom label:  4  Ligand atom A nbo:  -0.50129
Ligand atom label:  5  Ligand atom B nbo:  -0.48689
Atom_a:  5 Atom_b:  4
C:\Users\George\Desktop\Research_UCLA\CIC\Computational Work\Project cluster version 2\project_catalyst_repurposing\structures_ligand_id\pd_me2_structures\ligand_xyz\ligand-167-n-n-18-ligand_xyz.txt
Ending node: 2
Starting node: 3
(0.461159, -1.347995, -0.098092)   3
(0.623628, -0.600285, 0.934467)   1
(0.143347, 0.819108, 0.89098)   0
(-0.60511, 1.192087, -0.085613)   2
ligand-168-n-n-19

C:\Users\George\AppData\Local\Temp\ipykernel_7832\386804788.py:583: DeprecationWarning:

to_plotly_figure is deprecated and will be removed in version 4.0.0. Use MolGraph.to_plotly() instead.

C:\Users\George\AppData\Local\Temp\ipykernel_7832\386804788.py:589: DeprecationWarning:

to_networkx_graph is deprecated and will be removed in version 4.0.0. Use MolGraph.to_networkx() instead.

Pd number index:  0
['Pd', 'C', 'C', 'N', 'N', 'C', 'C', 'C', 'C', 'C', 'C', 'H', 'H', 'C', 'C', 'C', 'C', 'C', 'C', 'H', 'H', 'C', 'H', 'H', 'H', 'C', 'H', 'H', 'H', 'C', 'C', 'C', 'C', 'C', 'C', 'H', 'C', 'C', 'C', 'C', 'H', 'H', 'H', 'H', 'H', 'C', 'C', 'C', 'C', 'C', 'C', 'C', 'C', 'C', 'C', 'C', 'C', 'C', 'C', 'C', 'C', 'C', 'C', 'C', 'C', 'C', 'C', 'C', 'C', 'C', 'H', 'H', 'H', 'C', 'H', 'H', 'H', 'F', 'F', 'F', 'F', 'F', 'F', 'F', 'F', 'F', 'F', 'F', 'F', 'F', 'F', 'F', 'F', 'F', 'F', 'F', 'F']
Ligand atom label:  4  Ligand atom B nbo:  -0.49394
Ligand atom label:  5  Ligand atom A nbo:  -0.47829
Atom_a:  5 Atom_b:  4
C:\Users\George\Desktop\Research_UCLA\CIC\Computational Work\Project cluster version 2\project_catalyst_repurposing\structures_ligand_id\pd_me2_structures\ligand_xyz\ligand-168-n-n-19-ligand_xyz.txt
Ending node: 2
Starting node: 3
(-0.308027, -1.336828, 0.142022)   3
(-0.423653, -0.506874, 1.117367)   1
(-0.005943, 0.920699, 0.909616)   0
(0.468867, 1.265236, -0.233407)   2
ligand-169-n-o-20
Pd number index:  12
['N', 'C', 'O', 'C', 'C', 'C', 'C', 'C', 'C', 'H', 'H', 'H', 'Pd', 'C', 'H', 'H', 'H', 'C', 'H', 'H', 'H', 'C', 'C', 'H', 'C', 'H', 'C', 'H', 'H', 'H', 'C', 'H', 'H', 'H', 'C', 'H', 'C', 'H', 'H', 'H', 'C', 'H', 'H', 'H', 'C', 'O', 'C', 'F', 'F', 'F', 'C', 'F', 'F', 'F']

C:\Users\George\AppData\Local\Temp\ipykernel_7832\386804788.py:583: DeprecationWarning:

to_plotly_figure is deprecated and will be removed in version 4.0.0. Use MolGraph.to_plotly() instead.

C:\Users\George\AppData\Local\Temp\ipykernel_7832\386804788.py:589: DeprecationWarning:

to_networkx_graph is deprecated and will be removed in version 4.0.0. Use MolGraph.to_networkx() instead.

Ligand atom label:  1  Ligand atom B nbo:  -0.55691
Ligand atom label:  3  Ligand atom A nbo:  -0.5158
Atom_a:  3 Atom_b:  1
C:\Users\George\Desktop\Research_UCLA\CIC\Computational Work\Project cluster version 2\project_catalyst_repurposing\structures_ligand_id\pd_me2_structures\ligand_xyz\ligand-169-n-o-20-ligand_xyz.txt

C:\Users\George\AppData\Local\Temp\ipykernel_7832\386804788.py:583: DeprecationWarning:

to_plotly_figure is deprecated and will be removed in version 4.0.0. Use MolGraph.to_plotly() instead.

C:\Users\George\AppData\Local\Temp\ipykernel_7832\386804788.py:589: DeprecationWarning:

to_networkx_graph is deprecated and will be removed in version 4.0.0. Use MolGraph.to_networkx() instead.

Ending node: 0
Starting node: 2
(1.287618, -1.961432, 0.069142)   2
(2.104951, -1.043157, 0.013342)   1
(1.79745, 0.349208, -0.168828)   13
(0.432796, 0.802214, -0.224619)   12
(-0.673231, 0.13923, -0.132788)   0
ligand-170-n-o-21
Pd number index:  12
['N', 'C', 'O', 'C', 'C', 'C', 'C', 'C', 'C', 'H', 'H', 'H', 'Pd', 'C', 'H', 'H', 'H', 'C', 'H', 'H', 'H', 'C', 'C', 'C', 'H', 'C', 'H', 'H', 'H', 'C', 'H', 'H', 'H', 'C', 'H', 'C', 'H', 'H', 'H', 'C', 'H', 'H', 'H', 'C', 'O', 'C', 'F', 'F', 'F', 'C', 'F', 'F', 'F', 'C', 'H', 'H', 'H']
Ligand atom label:  1  Ligand atom B nbo:  -0.5813
Ligand atom label:  3  Ligand atom A nbo:  -0.51597
Atom_a:  3 Atom_b:  1
C:\Users\George\Desktop\Research_UCLA\CIC\Computational Work\Project cluster version 2\project_catalyst_repurposing\structures_ligand_id\pd_me2_structures\ligand_xyz\ligand-170-n-o-21-ligand_xyz.txt
Ending node: 0
Starting node: 2
(1.097166, -2.065437, -0.128034)   2
(1.944065, -1.206232, 0.139866)   1
(1.726893, 0.155874, 0.48401)   13
(0.404385, 0.727819, 0.662629)   12
(-0.70414, 0.160627, 0.283233)   0
ligand-171-n-o-22

C:\Users\George\AppData\Local\Temp\ipykernel_7832\386804788.py:583: DeprecationWarning:

to_plotly_figure is deprecated and will be removed in version 4.0.0. Use MolGraph.to_plotly() instead.

C:\Users\George\AppData\Local\Temp\ipykernel_7832\386804788.py:589: DeprecationWarning:

to_networkx_graph is deprecated and will be removed in version 4.0.0. Use MolGraph.to_networkx() instead.

Pd number index:  12
['N', 'C', 'O', 'C', 'C', 'C', 'C', 'C', 'C', 'H', 'H', 'H', 'Pd', 'C', 'H', 'H', 'H', 'C', 'H', 'H', 'H', 'C', 'C', 'C', 'H', 'C', 'H', 'H', 'H', 'C', 'H', 'H', 'H', 'C', 'H', 'C', 'H', 'H', 'H', 'C', 'H', 'H', 'H', 'C', 'F', 'F', 'F', 'C', 'H', 'H', 'H', 'H']
Ligand atom label:  1  Ligand atom B nbo:  -0.61025
Ligand atom label:  3  Ligand atom A nbo:  -0.54757
Atom_a:  3 Atom_b:  1
C:\Users\George\Desktop\Research_UCLA\CIC\Computational Work\Project cluster version 2\project_catalyst_repurposing\structures_ligand_id\pd_me2_structures\ligand_xyz\ligand-171-n-o-22-ligand_xyz.txt

C:\Users\George\AppData\Local\Temp\ipykernel_7832\386804788.py:583: DeprecationWarning:

to_plotly_figure is deprecated and will be removed in version 4.0.0. Use MolGraph.to_plotly() instead.

C:\Users\George\AppData\Local\Temp\ipykernel_7832\386804788.py:589: DeprecationWarning:

to_networkx_graph is deprecated and will be removed in version 4.0.0. Use MolGraph.to_networkx() instead.

Ending node: 0
Starting node: 2
(2.316172, -0.690631, -0.046237)   2
(2.587865, 0.524741, 0.037689)   1
(1.759377, 1.644574, 0.113081)   13
(0.335531, 1.659029, 0.1134)   12
(-0.418748, 0.590372, 0.032656)   0
ligand-172-n-o-23
Pd number index:  12
['N', 'C', 'O', 'C', 'C', 'C', 'C', 'C', 'C', 'H', 'H', 'H', 'Pd', 'C', 'H', 'H', 'H', 'C', 'H', 'H', 'H', 'C', 'C', 'C', 'F', 'F', 'F', 'C', 'H', 'H', 'H', 'C', 'H', 'H', 'H', 'C', 'H', 'H', 'H', 'C', 'C', 'O', 'F', 'F', 'F']
Ligand atom label:  1  Ligand atom B nbo:  -0.55392
Ligand atom label:  3  Ligand atom A nbo:  -0.59144
Atom_a:  1 Atom_b:  3
C:\Users\George\Desktop\Research_UCLA\CIC\Computational Work\Project cluster version 2\project_catalyst_repurposing\structures_ligand_id\pd_me2_structures\ligand_xyz\ligand-172-n-o-23-ligand_xyz.txt
Starting node: 0
Ending node: 2
(-0.929611, 0.354065, 0.126572)   0
(0.187208, 0.945188, 0.435576)   12
(1.498239, 0.317902, 0.383451)   13
(1.670308, -1.095473, 0.386097)   1
(0.793608, -1.964206, 0.348955)   2
ligand-173-n-o-24

C:\Users\George\AppData\Local\Temp\ipykernel_7832\386804788.py:583: DeprecationWarning:

to_plotly_figure is deprecated and will be removed in version 4.0.0. Use MolGraph.to_plotly() instead.

C:\Users\George\AppData\Local\Temp\ipykernel_7832\386804788.py:589: DeprecationWarning:

to_networkx_graph is deprecated and will be removed in version 4.0.0. Use MolGraph.to_networkx() instead.

Pd number index:  12
['N', 'C', 'O', 'C', 'C', 'C', 'C', 'C', 'C', 'H', 'H', 'H', 'Pd', 'C', 'H', 'H', 'H', 'C', 'H', 'H', 'H', 'C', 'C', 'C', 'H', 'C', 'H', 'H', 'H', 'C', 'C', 'C', 'C', 'C', 'H', 'C', 'H', 'H', 'H', 'H', 'C', 'H', 'H', 'H', 'C', 'H', 'H', 'H', 'C', 'H', 'H', 'H', 'C', 'H', 'H', 'H']
Ligand atom label:  1  Ligand atom B nbo:  -0.61517
Ligand atom label:  3  Ligand atom A nbo:  -0.58775
Atom_a:  3 Atom_b:  1
C:\Users\George\Desktop\Research_UCLA\CIC\Computational Work\Project cluster version 2\project_catalyst_repurposing\structures_ligand_id\pd_me2_structures\ligand_xyz\ligand-173-n-o-24-ligand_xyz.txt

C:\Users\George\AppData\Local\Temp\ipykernel_7832\386804788.py:583: DeprecationWarning:

to_plotly_figure is deprecated and will be removed in version 4.0.0. Use MolGraph.to_plotly() instead.

C:\Users\George\AppData\Local\Temp\ipykernel_7832\386804788.py:589: DeprecationWarning:

to_networkx_graph is deprecated and will be removed in version 4.0.0. Use MolGraph.to_networkx() instead.

Ending node: 0
Starting node: 2
(-1.908382, -0.755383, -0.248882)   2
(-2.291622, 0.382537, 0.111673)   1
(-1.469205, 1.465649, 0.48136)   13
(-0.060485, 1.484419, 0.498411)   12
(0.790084, 0.54794, 0.175932)   0
ligand-174-n-o-25
Pd number index:  12
['N', 'C', 'O', 'C', 'C', 'C', 'C', 'C', 'C', 'H', 'H', 'H', 'Pd', 'C', 'H', 'H', 'H', 'C', 'H', 'H', 'H', 'C', 'C', 'C', 'H', 'C', 'H', 'H', 'H', 'C', 'C', 'C', 'C', 'C', 'H', 'C', 'H', 'H', 'H', 'C', 'C', 'C', 'C', 'H', 'C', 'H', 'C', 'H', 'H', 'H', 'C', 'H', 'H', 'H', 'C', 'H', 'H', 'H', 'C', 'H', 'H', 'H', 'C', 'H', 'H', 'H']
Ligand atom label:  1  Ligand atom B nbo:  -0.60673
Ligand atom label:  3  Ligand atom A nbo:  -0.64473
Atom_a:  1 Atom_b:  3
C:\Users\George\Desktop\Research_UCLA\CIC\Computational Work\Project cluster version 2\project_catalyst_repurposing\structures_ligand_id\pd_me2_structures\ligand_xyz\ligand-174-n-o-25-ligand_xyz.txt

C:\Users\George\AppData\Local\Temp\ipykernel_7832\386804788.py:583: DeprecationWarning:

to_plotly_figure is deprecated and will be removed in version 4.0.0. Use MolGraph.to_plotly() instead.

C:\Users\George\AppData\Local\Temp\ipykernel_7832\386804788.py:589: DeprecationWarning:

to_networkx_graph is deprecated and will be removed in version 4.0.0. Use MolGraph.to_networkx() instead.

Starting node: 0
Ending node: 2
(1.446155, 0.694843, 0.280123)   0
(0.784174, 1.507204, 1.057304)   12
(-0.595846, 1.797505, 1.066809)   13
(-1.560084, 1.309234, 0.160823)   1
(-1.367598, 0.572416, -0.831725)   2
ligand-175-n-o-26
Pd number index:  12
['N', 'C', 'O', 'C', 'C', 'C', 'C', 'C', 'C', 'H', 'H', 'H', 'Pd', 'C', 'H', 'H', 'H', 'C', 'H', 'H', 'H', 'C', 'C', 'C', 'H', 'C', 'H', 'H', 'H', 'C', 'C', 'C', 'C', 'C', 'H', 'C', 'H', 'H', 'H', 'C', 'C', 'C', 'C', 'C', 'C', 'C', 'H', 'C', 'C', 'H', 'C', 'H', 'H', 'H', 'H', 'H', 'C', 'H', 'H', 'H', 'C', 'H', 'H', 'H', 'C', 'H', 'H', 'H', 'C', 'H', 'H', 'H']
Ligand atom label:  1  Ligand atom B nbo:  -0.60933
Ligand atom label:  3  Ligand atom A nbo:  -0.64538
Atom_a:  1 Atom_b:  3
C:\Users\George\Desktop\Research_UCLA\CIC\Computational Work\Project cluster version 2\project_catalyst_repurposing\structures_ligand_id\pd_me2_structures\ligand_xyz\ligand-175-n-o-26-ligand_xyz.txt
Starting node: 0
Ending node: 2
(1.954958, 0.68554, 0.158086)   0
(1.504663, 1.81976, 0.618128)   12
(0.197381, 2.347305, 0.559435)   13
(-0.917069, 1.744204, -0.052215)   1
(-0.944128, 0.697236, -0.738849)   2
ligand-176-n-o-27

C:\Users\George\AppData\Local\Temp\ipykernel_7832\386804788.py:583: DeprecationWarning:

to_plotly_figure is deprecated and will be removed in version 4.0.0. Use MolGraph.to_plotly() instead.

C:\Users\George\AppData\Local\Temp\ipykernel_7832\386804788.py:589: DeprecationWarning:

to_networkx_graph is deprecated and will be removed in version 4.0.0. Use MolGraph.to_networkx() instead.

Pd number index:  12
['N', 'C', 'O', 'C', 'C', 'C', 'C', 'C', 'C', 'H', 'H', 'H', 'Pd', 'C', 'H', 'H', 'H', 'C', 'H', 'H', 'H', 'C', 'C', 'C', 'H', 'C', 'H', 'H', 'C', 'C', 'C', 'C', 'C', 'H', 'C', 'H', 'H', 'H', 'C', 'C', 'C', 'C', 'H', 'C', 'H', 'C', 'H', 'H', 'H', 'C', 'H', 'H', 'H', 'C', 'H', 'H', 'H', 'C', 'H', 'H', 'H', 'C', 'H', 'H', 'H', 'C', 'H', 'H', 'H']
Ligand atom label:  1  Ligand atom B nbo:  -0.60123
Ligand atom label:  3  Ligand atom A nbo:  -0.58648
Atom_a:  3 Atom_b:  1
C:\Users\George\Desktop\Research_UCLA\CIC\Computational Work\Project cluster version 2\project_catalyst_repurposing\structures_ligand_id\pd_me2_structures\ligand_xyz\ligand-176-n-o-27-ligand_xyz.txt

C:\Users\George\AppData\Local\Temp\ipykernel_7832\386804788.py:583: DeprecationWarning:

to_plotly_figure is deprecated and will be removed in version 4.0.0. Use MolGraph.to_plotly() instead.

C:\Users\George\AppData\Local\Temp\ipykernel_7832\386804788.py:589: DeprecationWarning:

to_networkx_graph is deprecated and will be removed in version 4.0.0. Use MolGraph.to_networkx() instead.

Ending node: 0
Starting node: 2
(-1.439381, 0.616935, -0.977613)   2
(-1.618933, 1.371327, 0.004234)   1
(-0.66286, 1.871528, 0.908344)   13
(0.713171, 1.527612, 0.998358)   12
(1.298989, 0.584745, 0.295361)   0
ligand-177-n-o-28
Pd number index:  12
['N', 'C', 'O', 'C', 'C', 'C', 'C', 'C', 'C', 'H', 'H', 'H', 'Pd', 'C', 'H', 'H', 'H', 'C', 'H', 'H', 'H', 'C', 'C', 'C', 'H', 'C', 'H', 'H', 'C', 'C', 'C', 'C', 'C', 'H', 'C', 'H', 'H', 'H', 'C', 'C', 'C', 'C', 'H', 'C', 'H', 'C', 'H', 'H', 'H', 'C', 'C', 'H', 'H', 'H', 'C', 'H', 'H', 'H', 'C', 'H', 'H', 'H', 'C', 'H', 'H', 'H', 'F', 'F', 'F']
Ligand atom label:  1  Ligand atom B nbo:  -0.58339
Ligand atom label:  3  Ligand atom A nbo:  -0.57755
Atom_a:  3 Atom_b:  1
C:\Users\George\Desktop\Research_UCLA\CIC\Computational Work\Project cluster version 2\project_catalyst_repurposing\structures_ligand_id\pd_me2_structures\ligand_xyz\ligand-177-n-o-28-ligand_xyz.txt
Ending node: 0
Starting node: 2
(-1.581902, 0.233805, -1.193188)   2
(-1.69679, 1.199925, -0.412966)   1
(-0.686518, 1.840015, 0.33774)   13
(0.660123, 1.432586, 0.478523)   12
(1.201268, 0.335097, 0.018049)   0
ligand-178-n-o-29

C:\Users\George\AppData\Local\Temp\ipykernel_7832\386804788.py:583: DeprecationWarning:

to_plotly_figure is deprecated and will be removed in version 4.0.0. Use MolGraph.to_plotly() instead.

C:\Users\George\AppData\Local\Temp\ipykernel_7832\386804788.py:589: DeprecationWarning:

to_networkx_graph is deprecated and will be removed in version 4.0.0. Use MolGraph.to_networkx() instead.

Pd number index:  12
['N', 'C', 'O', 'C', 'C', 'C', 'C', 'C', 'C', 'H', 'H', 'H', 'Pd', 'C', 'H', 'H', 'H', 'C', 'H', 'H', 'H', 'C', 'C', 'C', 'H', 'C', 'H', 'C', 'C', 'C', 'C', 'C', 'C', 'H', 'H', 'H', 'C', 'H', 'H', 'H', 'C', 'H', 'H', 'H', 'C', 'H', 'H', 'H', 'C', 'H', 'H', 'H', 'H', 'C', 'H', 'H', 'H']
Ligand atom label:  1  Ligand atom B nbo:  -0.5636
Ligand atom label:  3  Ligand atom A nbo:  -0.55521
Atom_a:  3 Atom_b:  1
C:\Users\George\Desktop\Research_UCLA\CIC\Computational Work\Project cluster version 2\project_catalyst_repurposing\structures_ligand_id\pd_me2_structures\ligand_xyz\ligand-178-n-o-29-ligand_xyz.txt

C:\Users\George\AppData\Local\Temp\ipykernel_7832\386804788.py:583: DeprecationWarning:

to_plotly_figure is deprecated and will be removed in version 4.0.0. Use MolGraph.to_plotly() instead.

C:\Users\George\AppData\Local\Temp\ipykernel_7832\386804788.py:589: DeprecationWarning:

to_networkx_graph is deprecated and will be removed in version 4.0.0. Use MolGraph.to_networkx() instead.

Ending node: 0
Starting node: 2
(-1.935257, -1.18658, -0.566393)   2
(-2.36842, -0.138757, -0.044435)   1
(-1.687642, 0.984016, 0.49945)   13
(-0.297535, 1.166655, 0.57744)   12
(0.648264, 0.353345, 0.185218)   0
ligand-179-n-o-30
Pd number index:  12
['N', 'C', 'O', 'C', 'C', 'C', 'C', 'C', 'C', 'H', 'H', 'H', 'Pd', 'C', 'H', 'H', 'H', 'C', 'H', 'H', 'H', 'C', 'C', 'C', 'H', 'C', 'H', 'C', 'C', 'C', 'C', 'C', 'C', 'H', 'H', 'H', 'C', 'H', 'H', 'H', 'C', 'H', 'H', 'H', 'C', 'H', 'H', 'H', 'C', 'H', 'H', 'H', 'H', 'C', 'H', 'H', 'C', 'H', 'H', 'H']
Ligand atom label:  1  Ligand atom B nbo:  -0.58682
Ligand atom label:  3  Ligand atom A nbo:  -0.57471
Atom_a:  3 Atom_b:  1
C:\Users\George\Desktop\Research_UCLA\CIC\Computational Work\Project cluster version 2\project_catalyst_repurposing\structures_ligand_id\pd_me2_structures\ligand_xyz\ligand-179-n-o-30-ligand_xyz.txt
Ending node: 0
Starting node: 2
(1.776554, -1.009196, 0.47792)   2
(2.237248, 0.004079, -0.097081)   1
(1.502315, 1.062944, -0.689031)   13
(0.091049, 1.134838, -0.704965)   12
(-0.80817, 0.316002, -0.225278)   0
ligand-180-n-o-31

C:\Users\George\AppData\Local\Temp\ipykernel_7832\386804788.py:583: DeprecationWarning:

to_plotly_figure is deprecated and will be removed in version 4.0.0. Use MolGraph.to_plotly() instead.

C:\Users\George\AppData\Local\Temp\ipykernel_7832\386804788.py:589: DeprecationWarning:

to_networkx_graph is deprecated and will be removed in version 4.0.0. Use MolGraph.to_networkx() instead.

Pd number index:  12
['N', 'C', 'O', 'C', 'C', 'C', 'C', 'C', 'C', 'H', 'H', 'H', 'Pd', 'C', 'H', 'H', 'H', 'C', 'H', 'H', 'H', 'C', 'C', 'C', 'H', 'C', 'H', 'C', 'C', 'C', 'C', 'C', 'C', 'H', 'H', 'H', 'C', 'H', 'H', 'H', 'C', 'H', 'H', 'H', 'C', 'H', 'H', 'H', 'C', 'H', 'H', 'H', 'H', 'C', 'H', 'H', 'C', 'H', 'H', 'C', 'H', 'H', 'H']
Ligand atom label:  1  Ligand atom B nbo:  -0.58788
Ligand atom label:  3  Ligand atom A nbo:  -0.56239
Atom_a:  3 Atom_b:  1
C:\Users\George\Desktop\Research_UCLA\CIC\Computational Work\Project cluster version 2\project_catalyst_repurposing\structures_ligand_id\pd_me2_structures\ligand_xyz\ligand-180-n-o-31-ligand_xyz.txt
Ending node: 0
Starting node: 2
(-1.637582, -1.144824, -0.503269)   2
(-2.125651, -0.208292, 0.170256)   1
(-1.422058, 0.791728, 0.892278)   13
(-0.014209, 0.930397, 0.876616)   12
(0.905556, 0.233599, 0.263107)   0
ligand-181-n-o-32

C:\Users\George\AppData\Local\Temp\ipykernel_7832\386804788.py:583: DeprecationWarning:

to_plotly_figure is deprecated and will be removed in version 4.0.0. Use MolGraph.to_plotly() instead.

C:\Users\George\AppData\Local\Temp\ipykernel_7832\386804788.py:589: DeprecationWarning:

to_networkx_graph is deprecated and will be removed in version 4.0.0. Use MolGraph.to_networkx() instead.

Pd number index:  41
['N', 'C', 'H', 'C', 'C', 'C', 'C', 'H', 'C', 'C', 'H', 'O', 'C', 'C', 'C', 'C', 'C', 'C', 'H', 'H', 'H', 'C', 'H', 'C', 'H', 'H', 'H', 'C', 'H', 'H', 'H', 'C', 'H', 'C', 'H', 'H', 'H', 'C', 'H', 'H', 'H', 'Pd', 'C', 'H', 'H', 'H', 'C', 'H', 'H', 'H', 'C', 'C', 'C', 'C', 'H', 'C', 'C', 'H', 'H', 'H', 'O', 'H', 'H']
Ligand atom label:  1  Ligand atom B nbo:  -0.57404
Ligand atom label:  12  Ligand atom A nbo:  -0.63343
Atom_a:  1 Atom_b:  12
C:\Users\George\Desktop\Research_UCLA\CIC\Computational Work\Project cluster version 2\project_catalyst_repurposing\structures_ligand_id\pd_me2_structures\ligand_xyz\ligand-181-n-o-32-ligand_xyz.txt
Starting node: 0
Ending node: 11
(-1.414325, 0.525178, 0.045219)   0
(-0.788347, 1.639664, 0.201616)   1
(0.625262, 1.915411, 0.264604)   3
(1.659213, 0.919962, 0.138868)   5
(1.417092, -0.324662, -0.01457)   11
ligand-182-n-o-33

C:\Users\George\AppData\Local\Temp\ipykernel_7832\386804788.py:583: DeprecationWarning:

to_plotly_figure is deprecated and will be removed in version 4.0.0. Use MolGraph.to_plotly() instead.

C:\Users\George\AppData\Local\Temp\ipykernel_7832\386804788.py:589: DeprecationWarning:

to_networkx_graph is deprecated and will be removed in version 4.0.0. Use MolGraph.to_networkx() instead.

Pd number index:  41
['N', 'C', 'H', 'C', 'C', 'C', 'C', 'H', 'C', 'C', 'H', 'O', 'C', 'C', 'C', 'C', 'C', 'C', 'H', 'H', 'H', 'C', 'H', 'C', 'H', 'H', 'H', 'C', 'H', 'H', 'H', 'C', 'H', 'C', 'H', 'H', 'H', 'C', 'H', 'H', 'H', 'Pd', 'C', 'H', 'H', 'H', 'C', 'H', 'H', 'H', 'C', 'C', 'C', 'C', 'C', 'C', 'H', 'H', 'H', 'H', 'O', 'H', 'C', 'H', 'N', 'C', 'C', 'C', 'C', 'C', 'C', 'H', 'H', 'H', 'C', 'H', 'C', 'H', 'C', 'H', 'H', 'H', 'C', 'H', 'H', 'H', 'C', 'H', 'H', 'H', 'C', 'H', 'H', 'H']
Ligand atom label:  1  Ligand atom B nbo:  -0.57182
Ligand atom label:  12  Ligand atom A nbo:  -0.68191
Atom_a:  1 Atom_b:  12
C:\Users\George\Desktop\Research_UCLA\CIC\Computational Work\Project cluster version 2\project_catalyst_repurposing\structures_ligand_id\pd_me2_structures\ligand_xyz\ligand-182-n-o-33-ligand_xyz.txt
Starting node: 0
Ending node: 11
(-4.246183, 0.331337, -0.352538)   0
(-3.679879, 1.369208, -0.869406)   1
(-2.319466, 1.826584, -0.773555)   3
(-1.248049, 1.062105, -0.167233)   5
(-1.394567, -0.090041, 0.319072)   11
ligand-183-n-o-34

C:\Users\George\AppData\Local\Temp\ipykernel_7832\386804788.py:583: DeprecationWarning:

to_plotly_figure is deprecated and will be removed in version 4.0.0. Use MolGraph.to_plotly() instead.

C:\Users\George\AppData\Local\Temp\ipykernel_7832\386804788.py:589: DeprecationWarning:

to_networkx_graph is deprecated and will be removed in version 4.0.0. Use MolGraph.to_networkx() instead.

Pd number index:  11
['N', 'O', 'C', 'C', 'C', 'C', 'C', 'C', 'H', 'H', 'H', 'Pd', 'C', 'H', 'H', 'H', 'C', 'H', 'H', 'H', 'C', 'C', 'H', 'C', 'H', 'H', 'C', 'H', 'H', 'H', 'C', 'H', 'H', 'H', 'C', 'H', 'H', 'H', 'C', 'H', 'H', 'H', 'N', 'C', 'C', 'C', 'C', 'C', 'C', 'H', 'H', 'H', 'C', 'H', 'C', 'H', 'H', 'H', 'C', 'H', 'H', 'H', 'C', 'H', 'C', 'H', 'H', 'H', 'C', 'H', 'H', 'H', 'P', 'C', 'C', 'C', 'C', 'H', 'C', 'H', 'C', 'H', 'H', 'H', 'C', 'C', 'C', 'C', 'H', 'C', 'H', 'C', 'H', 'H', 'H']
Ligand atom label:  1  Ligand atom B nbo:  -0.56796
Ligand atom label:  2  Ligand atom A nbo:  -1.03279
Atom_a:  1 Atom_b:  2
C:\Users\George\Desktop\Research_UCLA\CIC\Computational Work\Project cluster version 2\project_catalyst_repurposing\structures_ligand_id\pd_me2_structures\ligand_xyz\ligand-183-n-o-34-ligand_xyz.txt
Starting node: 0
Ending node: 1
(1.474546, -0.179912, 0.33054)   0
(0.401345, -0.652618, 0.833032)   11
(-0.896003, -0.373528, 0.437744)   33
(-1.199426, 0.742298, -0.872208)   63
(-0.394328, 0.409662, -2.098395)   1
ligand-184-n-o-35

C:\Users\George\AppData\Local\Temp\ipykernel_7832\386804788.py:583: DeprecationWarning:

to_plotly_figure is deprecated and will be removed in version 4.0.0. Use MolGraph.to_plotly() instead.

C:\Users\George\AppData\Local\Temp\ipykernel_7832\386804788.py:589: DeprecationWarning:

to_networkx_graph is deprecated and will be removed in version 4.0.0. Use MolGraph.to_networkx() instead.

Pd number index:  11
['N', 'O', 'C', 'C', 'C', 'C', 'C', 'C', 'H', 'H', 'H', 'Pd', 'C', 'H', 'H', 'H', 'C', 'H', 'H', 'H', 'C', 'H', 'N', 'C', 'C', 'C', 'C', 'C', 'C', 'H', 'H', 'H', 'P', 'C', 'C', 'C', 'C', 'H', 'C', 'H', 'C', 'H', 'H', 'H', 'C', 'C', 'C', 'C', 'H', 'C', 'H', 'C', 'H', 'H', 'H', 'F', 'F', 'F', 'F']
Ligand atom label:  1  Ligand atom A nbo:  -0.51817
Ligand atom label:  2  Ligand atom B nbo:  -0.99974
Atom_a:  1 Atom_b:  2
C:\Users\George\Desktop\Research_UCLA\CIC\Computational Work\Project cluster version 2\project_catalyst_repurposing\structures_ligand_id\pd_me2_structures\ligand_xyz\ligand-184-n-o-35-ligand_xyz.txt

C:\Users\George\AppData\Local\Temp\ipykernel_7832\386804788.py:583: DeprecationWarning:

to_plotly_figure is deprecated and will be removed in version 4.0.0. Use MolGraph.to_plotly() instead.

C:\Users\George\AppData\Local\Temp\ipykernel_7832\386804788.py:589: DeprecationWarning:

to_networkx_graph is deprecated and will be removed in version 4.0.0. Use MolGraph.to_networkx() instead.

Starting node: 0
Ending node: 1
(-1.45811, -0.856904, 0.215034)   0
(-0.367415, -1.4517, -0.070222)   11
(0.877981, -0.870097, 0.00914)   13
(1.069706, 0.835582, 0.418931)   23
(0.472497, 1.202677, 1.746307)   1
ligand-186-p-o-53
Pd number index:  15
['P', 'C', 'C', 'S', 'O', 'O', 'O', 'C', 'C', 'C', 'C', 'H', 'H', 'H', 'H', 'Pd', 'C', 'H', 'H', 'H', 'C', 'H', 'H', 'H', 'C', 'C', 'C', 'C', 'C', 'H', 'C', 'H', 'H', 'H', 'C', 'C', 'C', 'C', 'C', 'H', 'C', 'H', 'H', 'H', 'H', 'H']
Ligand atom label:  1  Ligand atom B nbo:  0.97344
Ligand atom label:  5  Ligand atom A nbo:  -0.942
Atom_a:  1 Atom_b:  5
C:\Users\George\Desktop\Research_UCLA\CIC\Computational Work\Project cluster version 2\project_catalyst_repurposing\structures_ligand_id\pd_me2_structures\ligand_xyz\ligand-186-p-o-53-ligand_xyz.txt
Starting node: 0
Ending node: 4
(-0.461524, -0.012613, 0.029953)   0
(0.254089, -1.380883, -0.992992)   1
(1.644919, -1.592311, -0.977933)   2
(2.747653, -0.607893, 0.079174)   3
(2.660602, 0.777897, -0.49371)   4
ligand-187-p-o-54
Pd number index:  15
['P', 'C', 'C', 'S', 'O', 'O', 'O', 'C', 'C', 'C', 'C', 'H', 'H', 'H', 'H', 'Pd', 'C', 'H', 'H', 'H', 'C', 'H', 'H', 'H', 'C', 'C', 'C', 'H', 'C', 'H', 'H', 'C', 'H', 'H', 'C', 'H', 'H', 'H', 'H', 'H', 'H', 'C', 'C', 'C', 'H', 'C', 'H', 'H', 'C', 'H', 'H', 'C', 'H', 'H', 'H', 'H', 'H', 'H']
Ligand atom label:  1  Ligand atom B nbo:  0.99782
Ligand atom label:  5  Ligand atom A nbo:  -0.93895
Atom_a:  1 Atom_b:  5

C:\Users\George\AppData\Local\Temp\ipykernel_7832\386804788.py:583: DeprecationWarning:

to_plotly_figure is deprecated and will be removed in version 4.0.0. Use MolGraph.to_plotly() instead.

C:\Users\George\AppData\Local\Temp\ipykernel_7832\386804788.py:589: DeprecationWarning:

to_networkx_graph is deprecated and will be removed in version 4.0.0. Use MolGraph.to_networkx() instead.

C:\Users\George\Desktop\Research_UCLA\CIC\Computational Work\Project cluster version 2\project_catalyst_repurposing\structures_ligand_id\pd_me2_structures\ligand_xyz\ligand-187-p-o-54-ligand_xyz.txt
Starting node: 0
Ending node: 4
(-0.364935, -0.174762, -0.113398)   0
(0.769651, -0.954789, -1.37193)   1
(2.167968, -0.831403, -1.235565)   2
(2.950142, 0.096102, 0.119812)   3
(2.466335, 1.498944, -0.095783)   4
ligand-188-p-o-55

C:\Users\George\AppData\Local\Temp\ipykernel_7832\386804788.py:583: DeprecationWarning:

to_plotly_figure is deprecated and will be removed in version 4.0.0. Use MolGraph.to_plotly() instead.

C:\Users\George\AppData\Local\Temp\ipykernel_7832\386804788.py:589: DeprecationWarning:

to_networkx_graph is deprecated and will be removed in version 4.0.0. Use MolGraph.to_networkx() instead.

Pd number index:  28
['P', 'C', 'C', 'C', 'C', 'C', 'C', 'C', 'C', 'H', 'H', 'C', 'C', 'C', 'C', 'C', 'H', 'H', 'H', 'H', 'C', 'C', 'C', 'C', 'C', 'H', 'H', 'H', 'Pd', 'H', 'O', 'H', 'C', 'H', 'H', 'H', 'C', 'H', 'H', 'H', 'O', 'O', 'C', 'H', 'H', 'H', 'C', 'H', 'H', 'H', 'C', 'C', 'C', 'C', 'C', 'C', 'F', 'F', 'F', 'F', 'F']
Ligand atom label:  1  Ligand atom B nbo:  1.0196
Ligand atom label:  31  Ligand atom A nbo:  -0.68971
Atom_a:  1 Atom_b:  31
C:\Users\George\Desktop\Research_UCLA\CIC\Computational Work\Project cluster version 2\project_catalyst_repurposing\structures_ligand_id\pd_me2_structures\ligand_xyz\ligand-188-p-o-55-ligand_xyz.txt

C:\Users\George\AppData\Local\Temp\ipykernel_7832\386804788.py:583: DeprecationWarning:

to_plotly_figure is deprecated and will be removed in version 4.0.0. Use MolGraph.to_plotly() instead.

C:\Users\George\AppData\Local\Temp\ipykernel_7832\386804788.py:589: DeprecationWarning:

to_networkx_graph is deprecated and will be removed in version 4.0.0. Use MolGraph.to_networkx() instead.

Starting node: 0
Ending node: 29
(-1.696789, -0.05337, -0.252138)   0
(-0.255833, 0.212922, -1.32875)   1
(1.01252, 0.032098, -0.66925)   2
(1.135088, -0.224379, 0.566113)   29
ligand-189-p-o-56
Pd number index:  27
['P', 'C', 'C', 'C', 'C', 'C', 'C', 'C', 'C', 'H', 'H', 'C', 'C', 'C', 'C', 'C', 'H', 'H', 'H', 'C', 'C', 'C', 'C', 'C', 'H', 'H', 'H', 'Pd', 'O', 'H', 'C', 'H', 'H', 'H', 'C', 'H', 'H', 'H', 'O', 'O', 'C', 'H', 'H', 'H', 'C', 'H', 'H', 'H', 'C', 'C', 'C', 'C', 'C', 'C', 'F', 'F', 'F', 'F', 'F', 'O', 'C', 'H', 'H', 'H', 'O', 'C', 'H', 'H', 'H']
Ligand atom label:  1  Ligand atom B nbo:  1.02836
Ligand atom label:  29  Ligand atom A nbo:  -0.69692
Atom_a:  1 Atom_b:  29
C:\Users\George\Desktop\Research_UCLA\CIC\Computational Work\Project cluster version 2\project_catalyst_repurposing\structures_ligand_id\pd_me2_structures\ligand_xyz\ligand-189-p-o-56-ligand_xyz.txt

C:\Users\George\AppData\Local\Temp\ipykernel_7832\386804788.py:583: DeprecationWarning:

to_plotly_figure is deprecated and will be removed in version 4.0.0. Use MolGraph.to_plotly() instead.

C:\Users\George\AppData\Local\Temp\ipykernel_7832\386804788.py:589: DeprecationWarning:

to_networkx_graph is deprecated and will be removed in version 4.0.0. Use MolGraph.to_networkx() instead.

Starting node: 0
Ending node: 27
(-1.439657, 0.149823, -0.063104)   0
(-0.057466, 0.190511, -1.242731)   1
(1.23632, 0.19032, -0.610445)   2
(1.407857, 0.276459, 0.644448)   27
ligand-190-p-o-57
Pd number index:  27
['P', 'C', 'C', 'C', 'C', 'C', 'C', 'C', 'C', 'H', 'H', 'C', 'C', 'C', 'C', 'C', 'H', 'H', 'H', 'C', 'C', 'C', 'C', 'C', 'H', 'H', 'H', 'Pd', 'O', 'H', 'C', 'H', 'H', 'H', 'C', 'H', 'H', 'H', 'O', 'O', 'C', 'H', 'H', 'H', 'C', 'C', 'C', 'C', 'C', 'C', 'F', 'F', 'F', 'F', 'F', 'O', 'C', 'H', 'H', 'H', 'O', 'C', 'H', 'H', 'H', 'C', 'C', 'C', 'C', 'H', 'C', 'H', 'C', 'H', 'H', 'H']
Ligand atom label:  1  Ligand atom B nbo:  1.02639
Ligand atom label:  29  Ligand atom A nbo:  -0.69589
Atom_a:  1 Atom_b:  29
C:\Users\George\Desktop\Research_UCLA\CIC\Computational Work\Project cluster version 2\project_catalyst_repurposing\structures_ligand_id\pd_me2_structures\ligand_xyz\ligand-190-p-o-57-ligand_xyz.txt

C:\Users\George\AppData\Local\Temp\ipykernel_7832\386804788.py:583: DeprecationWarning:

to_plotly_figure is deprecated and will be removed in version 4.0.0. Use MolGraph.to_plotly() instead.

C:\Users\George\AppData\Local\Temp\ipykernel_7832\386804788.py:589: DeprecationWarning:

to_networkx_graph is deprecated and will be removed in version 4.0.0. Use MolGraph.to_networkx() instead.

Starting node: 0
Ending node: 27
(-1.545496, -0.013012, -0.007262)   0
(-0.21077, 0.016645, -1.248257)   1
(1.094933, -0.223234, -0.688473)   2
(1.306585, -0.464655, 0.539039)   27
ligand-191-p-o-58
Pd number index:  27
['P', 'C', 'C', 'C', 'C', 'C', 'C', 'C', 'C', 'H', 'H', 'C', 'C', 'C', 'C', 'C', 'H', 'H', 'H', 'C', 'C', 'C', 'C', 'C', 'H', 'H', 'H', 'Pd', 'O', 'H', 'C', 'H', 'H', 'H', 'C', 'H', 'H', 'H', 'O', 'O', 'C', 'C', 'C', 'C', 'C', 'C', 'F', 'F', 'F', 'F', 'F', 'O', 'C', 'H', 'H', 'H', 'O', 'C', 'H', 'H', 'H', 'C', 'C', 'C', 'C', 'H', 'C', 'H', 'C', 'H', 'H', 'H', 'C', 'C', 'C', 'C', 'H', 'C', 'H', 'C', 'H', 'H', 'H']
Ligand atom label:  1  Ligand atom B nbo:  1.02451
Ligand atom label:  29  Ligand atom A nbo:  -0.69587
Atom_a:  1 Atom_b:  29
C:\Users\George\Desktop\Research_UCLA\CIC\Computational Work\Project cluster version 2\project_catalyst_repurposing\structures_ligand_id\pd_me2_structures\ligand_xyz\ligand-191-p-o-58-ligand_xyz.txt
Starting node: 0
Ending node: 27
(1.145043, -0.184656, 0.370228)   0
(-0.258173, 0.11572, 1.51891)   1
(-1.550563, -0.165279, 0.946314)   2
(-1.724766, -0.68828, -0.196283)   27
ligand-192-p-o-59

C:\Users\George\AppData\Local\Temp\ipykernel_7832\386804788.py:583: DeprecationWarning:

to_plotly_figure is deprecated and will be removed in version 4.0.0. Use MolGraph.to_plotly() instead.

C:\Users\George\AppData\Local\Temp\ipykernel_7832\386804788.py:589: DeprecationWarning:

to_networkx_graph is deprecated and will be removed in version 4.0.0. Use MolGraph.to_networkx() instead.

Pd number index:  27
['P', 'C', 'C', 'C', 'C', 'C', 'C', 'C', 'C', 'H', 'H', 'C', 'C', 'C', 'C', 'C', 'H', 'H', 'H', 'C', 'C', 'C', 'C', 'C', 'H', 'H', 'H', 'Pd', 'O', 'H', 'C', 'H', 'H', 'H', 'C', 'H', 'H', 'H', 'O', 'O', 'C', 'C', 'C', 'C', 'C', 'C', 'F', 'F', 'F', 'F', 'F', 'O', 'O', 'C', 'H', 'H', 'H', 'C', 'C', 'C', 'C', 'H', 'C', 'H', 'C', 'H', 'H', 'H', 'C', 'H', 'H', 'H', 'C', 'C', 'C', 'C', 'H', 'C', 'H', 'C', 'H', 'H', 'H']
Ligand atom label:  1  Ligand atom B nbo:  1.02602
Ligand atom label:  29  Ligand atom A nbo:  -0.69641
Atom_a:  1 Atom_b:  29
C:\Users\George\Desktop\Research_UCLA\CIC\Computational Work\Project cluster version 2\project_catalyst_repurposing\structures_ligand_id\pd_me2_structures\ligand_xyz\ligand-192-p-o-59-ligand_xyz.txt
Starting node: 0
Ending node: 27
(-1.090383, 0.012039, 0.351166)   0
(0.487481, 0.648343, 0.988717)   1
(1.63618, -0.064476, 0.493456)   2
(1.553816, -1.066518, -0.280111)   27
ligand-193-p-o-60

C:\Users\George\AppData\Local\Temp\ipykernel_7832\386804788.py:583: DeprecationWarning:

to_plotly_figure is deprecated and will be removed in version 4.0.0. Use MolGraph.to_plotly() instead.

C:\Users\George\AppData\Local\Temp\ipykernel_7832\386804788.py:589: DeprecationWarning:

to_networkx_graph is deprecated and will be removed in version 4.0.0. Use MolGraph.to_networkx() instead.

Pd number index:  27
['P', 'C', 'C', 'C', 'C', 'C', 'C', 'C', 'C', 'H', 'H', 'C', 'C', 'C', 'C', 'C', 'H', 'H', 'H', 'C', 'C', 'C', 'C', 'C', 'H', 'H', 'H', 'Pd', 'O', 'H', 'C', 'H', 'H', 'H', 'C', 'H', 'H', 'H', 'O', 'O', 'C', 'C', 'C', 'C', 'C', 'C', 'F', 'F', 'F', 'F', 'F', 'O', 'O', 'C', 'H', 'H', 'H', 'C', 'C', 'C', 'C', 'H', 'C', 'H', 'C', 'H', 'H', 'H', 'C', 'C', 'C', 'C', 'H', 'C', 'H', 'C', 'H', 'H', 'H', 'C', 'C', 'C', 'C', 'H', 'C', 'H', 'C', 'H', 'H', 'H']
Ligand atom label:  1  Ligand atom B nbo:  0.99053
Ligand atom label:  29  Ligand atom A nbo:  -0.69005
Atom_a:  1 Atom_b:  29
C:\Users\George\Desktop\Research_UCLA\CIC\Computational Work\Project cluster version 2\project_catalyst_repurposing\structures_ligand_id\pd_me2_structures\ligand_xyz\ligand-193-p-o-60-ligand_xyz.txt
Starting node: 0
Ending node: 27
(-1.069623, -0.016183, 0.152053)   0
(0.440678, 0.739191, 0.827832)   1
(1.645193, 0.273328, 0.187046)   2
(1.659214, -0.522184, -0.799836)   27
ligand-194-p-o-61

C:\Users\George\AppData\Local\Temp\ipykernel_7832\386804788.py:583: DeprecationWarning:

to_plotly_figure is deprecated and will be removed in version 4.0.0. Use MolGraph.to_plotly() instead.

C:\Users\George\AppData\Local\Temp\ipykernel_7832\386804788.py:589: DeprecationWarning:

to_networkx_graph is deprecated and will be removed in version 4.0.0. Use MolGraph.to_networkx() instead.

Pd number index:  27
['P', 'C', 'C', 'C', 'C', 'C', 'C', 'C', 'C', 'H', 'H', 'C', 'C', 'C', 'C', 'C', 'H', 'H', 'H', 'C', 'C', 'C', 'C', 'C', 'H', 'H', 'H', 'Pd', 'O', 'H', 'C', 'H', 'H', 'H', 'C', 'H', 'H', 'H', 'O', 'O', 'C', 'H', 'H', 'H', 'C', 'H', 'H', 'H', 'O', 'C', 'H', 'H', 'H', 'O', 'C', 'H', 'H', 'H', 'C', 'C', 'C', 'C', 'C', 'H', 'C', 'C', 'C', 'H', 'H', 'H', 'H', 'C', 'C', 'C', 'C', 'C', 'H', 'C', 'H', 'H', 'H']
Ligand atom label:  1  Ligand atom B nbo:  1.0283
Ligand atom label:  29  Ligand atom A nbo:  -0.69613
Atom_a:  1 Atom_b:  29
C:\Users\George\Desktop\Research_UCLA\CIC\Computational Work\Project cluster version 2\project_catalyst_repurposing\structures_ligand_id\pd_me2_structures\ligand_xyz\ligand-194-p-o-61-ligand_xyz.txt
Starting node: 0
Ending node: 27
(-1.547008, 0.180166, -0.010234)   0
(-0.104715, 0.407343, -1.088315)   1
(1.152545, 0.305794, -0.396064)   2
(1.253612, 0.201513, 0.867885)   27
ligand-195-p-o-62

C:\Users\George\AppData\Local\Temp\ipykernel_7832\386804788.py:583: DeprecationWarning:

to_plotly_figure is deprecated and will be removed in version 4.0.0. Use MolGraph.to_plotly() instead.

C:\Users\George\AppData\Local\Temp\ipykernel_7832\386804788.py:589: DeprecationWarning:

to_networkx_graph is deprecated and will be removed in version 4.0.0. Use MolGraph.to_networkx() instead.

Pd number index:  27
['P', 'C', 'C', 'C', 'C', 'C', 'C', 'C', 'C', 'H', 'H', 'C', 'C', 'C', 'C', 'C', 'H', 'H', 'H', 'C', 'C', 'C', 'C', 'C', 'H', 'H', 'H', 'Pd', 'O', 'H', 'C', 'H', 'H', 'H', 'C', 'H', 'H', 'H', 'O', 'O', 'C', 'H', 'H', 'H', 'C', 'H', 'H', 'H', 'O', 'C', 'H', 'H', 'H', 'O', 'C', 'H', 'H', 'H', 'Si', 'C', 'H', 'H', 'H', 'C', 'H', 'H', 'H', 'C', 'H', 'H', 'H']
Ligand atom label:  1  Ligand atom B nbo:  1.02656
Ligand atom label:  29  Ligand atom A nbo:  -0.69978
Atom_a:  1 Atom_b:  29
C:\Users\George\Desktop\Research_UCLA\CIC\Computational Work\Project cluster version 2\project_catalyst_repurposing\structures_ligand_id\pd_me2_structures\ligand_xyz\ligand-195-p-o-62-ligand_xyz.txt
Starting node: 0
Ending node: 27
(-0.651941, -0.073321, 0.125898)   0
(0.761936, 0.350843, 1.179991)   1
(2.034742, 0.044565, 0.591919)   2
(2.165701, -0.551198, -0.534037)   27
ligand-196-n-o-37

C:\Users\George\AppData\Local\Temp\ipykernel_7832\386804788.py:583: DeprecationWarning:

to_plotly_figure is deprecated and will be removed in version 4.0.0. Use MolGraph.to_plotly() instead.

C:\Users\George\AppData\Local\Temp\ipykernel_7832\386804788.py:589: DeprecationWarning:

to_networkx_graph is deprecated and will be removed in version 4.0.0. Use MolGraph.to_networkx() instead.

Pd number index:  15
['N', 'C', 'C', 'C', 'C', 'H', 'O', 'C', 'C', 'C', 'C', 'C', 'C', 'H', 'H', 'Pd', 'C', 'H', 'H', 'H', 'C', 'H', 'H', 'O', 'C', 'C', 'C', 'C', 'C', 'C', 'H', 'H', 'H', 'H', 'H', 'C', 'H', 'C', 'C', 'C', 'C', 'H', 'C', 'H', 'C', 'H', 'H', 'H', 'C', 'C', 'C', 'C', 'H', 'C', 'H', 'C', 'H', 'H', 'H', 'C', 'H', 'C', 'C', 'C', 'C', 'H', 'C', 'H', 'C', 'H', 'H', 'H', 'C', 'C', 'C', 'C', 'H', 'C', 'H', 'C', 'H', 'H', 'H', 'C', 'H', 'H', 'H']
Ligand atom label:  1  Ligand atom A nbo:  -0.49182
Ligand atom label:  7  Ligand atom B nbo:  -0.592
Atom_a:  1 Atom_b:  7
C:\Users\George\Desktop\Research_UCLA\CIC\Computational Work\Project cluster version 2\project_catalyst_repurposing\structures_ligand_id\pd_me2_structures\ligand_xyz\ligand-196-n-o-37-ligand_xyz.txt

C:\Users\George\AppData\Local\Temp\ipykernel_7832\386804788.py:583: DeprecationWarning:

to_plotly_figure is deprecated and will be removed in version 4.0.0. Use MolGraph.to_plotly() instead.

C:\Users\George\AppData\Local\Temp\ipykernel_7832\386804788.py:589: DeprecationWarning:

to_networkx_graph is deprecated and will be removed in version 4.0.0. Use MolGraph.to_networkx() instead.

Starting node: 0
Ending node: 6
(-0.004742, 0.204315, 0.300286)   0
(-0.613535, 1.209529, -0.309899)   1
(-0.908259, 2.368237, 0.593791)   3
(-0.611857, 2.327974, 1.784795)   6
ligand-197-n-o-38
Pd number index:  15
['N', 'C', 'C', 'C', 'C', 'H', 'O', 'C', 'C', 'C', 'C', 'C', 'C', 'H', 'H', 'Pd', 'C', 'H', 'H', 'H', 'C', 'H', 'H', 'O', 'C', 'C', 'C', 'C', 'C', 'C', 'H', 'H', 'H', 'H', 'H', 'H', 'O', 'O', 'C', 'H', 'H', 'H', 'C', 'H', 'H', 'H']
Ligand atom label:  1  Ligand atom A nbo:  -0.48468
Ligand atom label:  7  Ligand atom B nbo:  -0.57194
Atom_a:  1 Atom_b:  7
C:\Users\George\Desktop\Research_UCLA\CIC\Computational Work\Project cluster version 2\project_catalyst_repurposing\structures_ligand_id\pd_me2_structures\ligand_xyz\ligand-197-n-o-38-ligand_xyz.txt
Starting node: 0
Ending node: 6
(-0.527123, -0.118127, 0.040044)   0
(0.735768, -0.491711, 0.161771)   1
(1.700741, 0.64037, -0.018743)   3
(1.30405, 1.773974, -0.275833)   6
ligand-198-n-o-39

C:\Users\George\AppData\Local\Temp\ipykernel_7832\386804788.py:583: DeprecationWarning:

to_plotly_figure is deprecated and will be removed in version 4.0.0. Use MolGraph.to_plotly() instead.

C:\Users\George\AppData\Local\Temp\ipykernel_7832\386804788.py:589: DeprecationWarning:

to_networkx_graph is deprecated and will be removed in version 4.0.0. Use MolGraph.to_networkx() instead.

Pd number index:  15
['N', 'C', 'C', 'C', 'C', 'H', 'O', 'C', 'C', 'C', 'C', 'C', 'C', 'H', 'H', 'Pd', 'C', 'H', 'H', 'H', 'C', 'H', 'H', 'O', 'C', 'C', 'C', 'C', 'C', 'C', 'H', 'H', 'H', 'H', 'H', 'H', 'C', 'H', 'C', 'H', 'H', 'H', 'C', 'H', 'H', 'H', 'C', 'H', 'C', 'H', 'H', 'H', 'C', 'H', 'H', 'H']
Ligand atom label:  1  Ligand atom A nbo:  -0.49076
Ligand atom label:  7  Ligand atom B nbo:  -0.59505
Atom_a:  1 Atom_b:  7
C:\Users\George\Desktop\Research_UCLA\CIC\Computational Work\Project cluster version 2\project_catalyst_repurposing\structures_ligand_id\pd_me2_structures\ligand_xyz\ligand-198-n-o-39-ligand_xyz.txt
Starting node: 0
Ending node: 6
(0.479094, 0.094477, 0.177282)   0
(-0.786018, 0.479686, 0.155582)   1
(-1.747343, -0.659291, -0.007737)   3
(-1.340209, -1.809484, -0.151027)   6

C:\Users\George\AppData\Local\Temp\ipykernel_7832\386804788.py:583: DeprecationWarning:

to_plotly_figure is deprecated and will be removed in version 4.0.0. Use MolGraph.to_plotly() instead.

C:\Users\George\AppData\Local\Temp\ipykernel_7832\386804788.py:589: DeprecationWarning:

to_networkx_graph is deprecated and will be removed in version 4.0.0. Use MolGraph.to_networkx() instead.

ligand-199-n-o-40
Pd number index:  10
['N', 'O', 'C', 'C', 'C', 'C', 'C', 'C', 'H', 'H', 'Pd', 'C', 'H', 'H', 'H', 'C', 'H', 'H', 'H', 'C', 'C', 'C', 'C', 'C', 'H', 'C', 'C', 'H', 'H', 'H', 'C', 'H', 'C', 'H', 'H', 'H', 'H', 'H', 'H', 'H']
Ligand atom label:  1  Ligand atom A nbo:  -0.55851
Ligand atom label:  2  Ligand atom B nbo:  -0.53412
Atom_a:  2 Atom_b:  1
C:\Users\George\Desktop\Research_UCLA\CIC\Computational Work\Project cluster version 2\project_catalyst_repurposing\structures_ligand_id\pd_me2_structures\ligand_xyz\ligand-199-n-o-40-ligand_xyz.txt
Ending node: 0
Starting node: 1
(1.595582, 1.844356, -0.018228)   1
(2.185676, 0.742719, -0.003756)   11
(1.343965, -0.501928, 0.007917)   10
(0.04985, -0.262704, -0.00383)   0
ligand-200-n-o-41

C:\Users\George\AppData\Local\Temp\ipykernel_7832\386804788.py:583: DeprecationWarning:

to_plotly_figure is deprecated and will be removed in version 4.0.0. Use MolGraph.to_plotly() instead.

C:\Users\George\AppData\Local\Temp\ipykernel_7832\386804788.py:589: DeprecationWarning:

to_networkx_graph is deprecated and will be removed in version 4.0.0. Use MolGraph.to_networkx() instead.

Pd number index:  10
['N', 'O', 'C', 'C', 'C', 'C', 'C', 'C', 'H', 'H', 'Pd', 'C', 'H', 'H', 'H', 'C', 'H', 'H', 'H', 'C', 'C', 'C', 'C', 'C', 'H', 'C', 'C', 'H', 'H', 'H', 'C', 'H', 'C', 'H', 'H', 'H', 'C', 'H', 'H', 'H', 'C', 'H', 'C', 'H', 'H', 'H', 'C', 'H', 'H', 'H', 'H', 'H']
Ligand atom label:  1  Ligand atom A nbo:  -0.57967
Ligand atom label:  2  Ligand atom B nbo:  -0.5415
Atom_a:  2 Atom_b:  1
C:\Users\George\Desktop\Research_UCLA\CIC\Computational Work\Project cluster version 2\project_catalyst_repurposing\structures_ligand_id\pd_me2_structures\ligand_xyz\ligand-200-n-o-41-ligand_xyz.txt

C:\Users\George\AppData\Local\Temp\ipykernel_7832\386804788.py:583: DeprecationWarning:

to_plotly_figure is deprecated and will be removed in version 4.0.0. Use MolGraph.to_plotly() instead.

C:\Users\George\AppData\Local\Temp\ipykernel_7832\386804788.py:589: DeprecationWarning:

to_networkx_graph is deprecated and will be removed in version 4.0.0. Use MolGraph.to_networkx() instead.

Ending node: 0
Starting node: 1
(1.760343, 1.932831, 0.249395)   1
(2.335499, 0.836904, 0.067281)   11
(1.476942, -0.374763, -0.150085)   10
(0.187269, -0.108329, -0.167634)   0
ligand-201-n-o-42
Pd number index:  10
['N', 'O', 'C', 'C', 'C', 'C', 'C', 'C', 'H', 'H', 'Pd', 'C', 'H', 'H', 'H', 'C', 'H', 'H', 'H', 'C', 'C', 'C', 'C', 'C', 'H', 'C', 'C', 'H', 'H', 'H', 'C', 'H', 'H', 'C', 'H', 'H', 'H', 'C', 'H', 'H', 'H', 'C', 'H', 'H', 'H', 'H']
Ligand atom label:  1  Ligand atom A nbo:  -0.55993
Ligand atom label:  2  Ligand atom B nbo:  -0.52926
Atom_a:  2 Atom_b:  1
C:\Users\George\Desktop\Research_UCLA\CIC\Computational Work\Project cluster version 2\project_catalyst_repurposing\structures_ligand_id\pd_me2_structures\ligand_xyz\ligand-201-n-o-42-ligand_xyz.txt
Ending node: 0
Starting node: 1
(2.179927, -1.327089, 0.454421)   1
(2.469894, -0.132888, 0.222011)   11
(1.364001, 0.780489, -0.222543)   10
(0.190964, 0.185559, -0.295639)   0
ligand-202-n-o-43

C:\Users\George\AppData\Local\Temp\ipykernel_7832\386804788.py:583: DeprecationWarning:

to_plotly_figure is deprecated and will be removed in version 4.0.0. Use MolGraph.to_plotly() instead.

C:\Users\George\AppData\Local\Temp\ipykernel_7832\386804788.py:589: DeprecationWarning:

to_networkx_graph is deprecated and will be removed in version 4.0.0. Use MolGraph.to_networkx() instead.

Pd number index:  10
['N', 'O', 'C', 'C', 'C', 'C', 'C', 'C', 'H', 'H', 'Pd', 'C', 'H', 'H', 'H', 'C', 'H', 'H', 'H', 'C', 'C', 'C', 'C', 'C', 'H', 'C', 'C', 'H', 'H', 'H', 'C', 'H', 'H', 'C', 'H', 'H', 'H', 'C', 'H', 'H', 'H', 'C', 'H', 'H', 'H', 'C', 'H', 'H', 'H']
Ligand atom label:  1  Ligand atom A nbo:  -0.56283
Ligand atom label:  2  Ligand atom B nbo:  -0.52958
Atom_a:  2 Atom_b:  1
C:\Users\George\Desktop\Research_UCLA\CIC\Computational Work\Project cluster version 2\project_catalyst_repurposing\structures_ligand_id\pd_me2_structures\ligand_xyz\ligand-202-n-o-43-ligand_xyz.txt
Ending node: 0
Starting node: 1
(2.21317, -1.28356, 0.551131)   1
(2.459027, -0.079664, 0.315947)   11
(1.322861, 0.79101, -0.136367)   10
(0.166292, 0.1628, -0.191988)   0

C:\Users\George\AppData\Local\Temp\ipykernel_7832\386804788.py:583: DeprecationWarning:

to_plotly_figure is deprecated and will be removed in version 4.0.0. Use MolGraph.to_plotly() instead.

C:\Users\George\AppData\Local\Temp\ipykernel_7832\386804788.py:589: DeprecationWarning:

to_networkx_graph is deprecated and will be removed in version 4.0.0. Use MolGraph.to_networkx() instead.

ligand-203-n-o-44
Pd number index:  10
['N', 'O', 'C', 'C', 'C', 'C', 'C', 'C', 'H', 'H', 'Pd', 'C', 'H', 'H', 'H', 'C', 'H', 'H', 'H', 'C', 'C', 'C', 'C', 'C', 'H', 'C', 'C', 'H', 'H', 'H', 'H', 'H', 'C', 'C', 'C', 'C', 'H', 'C', 'H', 'C', 'H', 'H', 'H', 'C', 'C', 'C', 'C', 'H', 'C', 'H', 'C', 'H', 'H', 'H']
Ligand atom label:  1  Ligand atom A nbo:  -0.55811
Ligand atom label:  2  Ligand atom B nbo:  -0.5294
Atom_a:  2 Atom_b:  1
C:\Users\George\Desktop\Research_UCLA\CIC\Computational Work\Project cluster version 2\project_catalyst_repurposing\structures_ligand_id\pd_me2_structures\ligand_xyz\ligand-203-n-o-44-ligand_xyz.txt
Ending node: 0
Starting node: 1
(0.180815, -2.402159, 1.036329)   1
(0.785335, -2.322208, -0.054323)   11
(0.73639, -1.01599, -0.790165)   10
(0.026847, -0.092867, -0.17238)   0
ligand-204-n-o-45
Pd number index:  10
['N', 'O', 'C', 'C', 'C', 'C', 'C', 'C', 'H', 'H', 'Pd', 'C', 'H', 'H', 'H', 'C', 'H', 'H', 'H', 'C', 'C', 'C', 'C', 'C', 'H', 'C', 'C', 'H', 'H', 'H', 'H', 'H', 'Cl', 'Cl']

C:\Users\George\AppData\Local\Temp\ipykernel_7832\386804788.py:583: DeprecationWarning:

to_plotly_figure is deprecated and will be removed in version 4.0.0. Use MolGraph.to_plotly() instead.

C:\Users\George\AppData\Local\Temp\ipykernel_7832\386804788.py:589: DeprecationWarning:

to_networkx_graph is deprecated and will be removed in version 4.0.0. Use MolGraph.to_networkx() instead.

Ligand atom label:  1  Ligand atom A nbo:  -0.56489
Ligand atom label:  2  Ligand atom B nbo:  -0.52791
Atom_a:  2 Atom_b:  1
C:\Users\George\Desktop\Research_UCLA\CIC\Computational Work\Project cluster version 2\project_catalyst_repurposing\structures_ligand_id\pd_me2_structures\ligand_xyz\ligand-204-n-o-45-ligand_xyz.txt
Ending node: 0
Starting node: 1
(1.846831, 1.765569, -0.027502)   1
(2.334896, 0.617197, -0.003528)   11
(1.388453, -0.546664, 0.013152)   10
(0.121896, -0.182262, -0.00214)   0
ligand-205-n-o-46
Pd number index:  10
['N', 'O', 'C', 'C', 'C', 'C', 'C', 'C', 'H', 'H', 'Pd', 'C', 'H', 'H', 'H', 'C', 'H', 'H', 'H', 'C', 'C', 'C', 'C', 'C', 'H', 'C', 'C', 'H', 'H', 'H', 'H', 'H', 'Br', 'Br']

C:\Users\George\AppData\Local\Temp\ipykernel_7832\386804788.py:583: DeprecationWarning:

to_plotly_figure is deprecated and will be removed in version 4.0.0. Use MolGraph.to_plotly() instead.

C:\Users\George\AppData\Local\Temp\ipykernel_7832\386804788.py:589: DeprecationWarning:

to_networkx_graph is deprecated and will be removed in version 4.0.0. Use MolGraph.to_networkx() instead.

Ligand atom label:  1  Ligand atom A nbo:  -0.57364
Ligand atom label:  2  Ligand atom B nbo:  -0.52732
Atom_a:  2 Atom_b:  1
C:\Users\George\Desktop\Research_UCLA\CIC\Computational Work\Project cluster version 2\project_catalyst_repurposing\structures_ligand_id\pd_me2_structures\ligand_xyz\ligand-205-n-o-46-ligand_xyz.txt
Ending node: 0
Starting node: 1
(-2.205731, -1.612792, -0.124273)   1
(-2.529503, -0.414418, 0.003004)   11
(-1.432197, 0.60457, 0.086971)   10
(-0.226628, 0.074069, 0.004924)   0
ligand-206-n-o-47

C:\Users\George\AppData\Local\Temp\ipykernel_7832\386804788.py:583: DeprecationWarning:

to_plotly_figure is deprecated and will be removed in version 4.0.0. Use MolGraph.to_plotly() instead.

C:\Users\George\AppData\Local\Temp\ipykernel_7832\386804788.py:589: DeprecationWarning:

to_networkx_graph is deprecated and will be removed in version 4.0.0. Use MolGraph.to_networkx() instead.

Pd number index:  8
['N', 'O', 'C', 'C', 'C', 'C', 'C', 'C', 'Pd', 'C', 'H', 'H', 'H', 'C', 'H', 'H', 'H', 'C', 'C', 'C', 'C', 'C', 'H', 'C', 'C', 'H', 'H', 'H', 'H', 'F', 'F', 'F', 'F', 'F']
Ligand atom label:  1  Ligand atom A nbo:  -0.58092
Ligand atom label:  2  Ligand atom B nbo:  -0.52205
Atom_a:  2 Atom_b:  1
C:\Users\George\Desktop\Research_UCLA\CIC\Computational Work\Project cluster version 2\project_catalyst_repurposing\structures_ligand_id\pd_me2_structures\ligand_xyz\ligand-206-n-o-47-ligand_xyz.txt
Ending node: 0
Starting node: 1
(-2.901046, -0.764584, -0.05514)   1
(-2.806793, 0.472376, 0.07573)   9
(-1.432696, 1.066484, 0.175334)   8
(-0.476903, 0.153947, 0.128415)   0
ligand-207-n-o-48

C:\Users\George\AppData\Local\Temp\ipykernel_7832\386804788.py:583: DeprecationWarning:

to_plotly_figure is deprecated and will be removed in version 4.0.0. Use MolGraph.to_plotly() instead.

C:\Users\George\AppData\Local\Temp\ipykernel_7832\386804788.py:589: DeprecationWarning:

to_networkx_graph is deprecated and will be removed in version 4.0.0. Use MolGraph.to_networkx() instead.

Pd number index:  8
['N', 'O', 'C', 'C', 'C', 'C', 'C', 'C', 'Pd', 'C', 'H', 'H', 'H', 'C', 'H', 'H', 'H', 'C', 'C', 'C', 'C', 'C', 'H', 'C', 'C', 'H', 'H', 'H', 'H', 'C', 'H', 'H', 'H', 'H', 'H', 'H', 'H']
Ligand atom label:  1  Ligand atom A nbo:  -0.55214
Ligand atom label:  2  Ligand atom B nbo:  -0.53377
Atom_a:  2 Atom_b:  1
C:\Users\George\Desktop\Research_UCLA\CIC\Computational Work\Project cluster version 2\project_catalyst_repurposing\structures_ligand_id\pd_me2_structures\ligand_xyz\ligand-207-n-o-48-ligand_xyz.txt

C:\Users\George\AppData\Local\Temp\ipykernel_7832\386804788.py:583: DeprecationWarning:

to_plotly_figure is deprecated and will be removed in version 4.0.0. Use MolGraph.to_plotly() instead.

C:\Users\George\AppData\Local\Temp\ipykernel_7832\386804788.py:589: DeprecationWarning:

to_networkx_graph is deprecated and will be removed in version 4.0.0. Use MolGraph.to_networkx() instead.

Ending node: 0
Starting node: 1
(-1.485948, 1.853369, -0.042254)   1
(-2.12674, 0.780449, -0.042859)   9
(-1.343877, -0.501677, -0.066634)   8
(-0.041702, -0.320588, -0.133788)   0
ligand-208-n-o-49
Pd number index:  8
['N', 'O', 'C', 'C', 'C', 'C', 'C', 'C', 'Pd', 'C', 'H', 'H', 'H', 'C', 'H', 'H', 'H', 'C', 'C', 'C', 'C', 'C', 'H', 'C', 'C', 'H', 'H', 'H', 'H', 'C', 'H', 'H', 'H', 'H', 'H', 'H', 'C', 'F', 'F', 'F']
Ligand atom label:  1  Ligand atom A nbo:  -0.56705
Ligand atom label:  2  Ligand atom B nbo:  -0.52959
Atom_a:  2 Atom_b:  1
C:\Users\George\Desktop\Research_UCLA\CIC\Computational Work\Project cluster version 2\project_catalyst_repurposing\structures_ligand_id\pd_me2_structures\ligand_xyz\ligand-208-n-o-49-ligand_xyz.txt
Ending node: 0
Starting node: 1
(2.162136, 1.455778, 0.343842)   1
(2.458332, 0.256878, 0.158066)   9
(1.352673, -0.692631, -0.198029)   8
(0.158718, -0.131549, -0.198574)   0
ligand-209-n-o-50

C:\Users\George\AppData\Local\Temp\ipykernel_7832\386804788.py:583: DeprecationWarning:

to_plotly_figure is deprecated and will be removed in version 4.0.0. Use MolGraph.to_plotly() instead.

C:\Users\George\AppData\Local\Temp\ipykernel_7832\386804788.py:589: DeprecationWarning:

to_networkx_graph is deprecated and will be removed in version 4.0.0. Use MolGraph.to_networkx() instead.

Pd number index:  41
['N', 'C', 'C', 'C', 'C', 'H', 'C', 'C', 'H', 'H', 'H', 'O', 'C', 'C', 'C', 'C', 'C', 'C', 'H', 'H', 'H', 'C', 'H', 'C', 'H', 'H', 'H', 'C', 'H', 'H', 'H', 'C', 'H', 'C', 'H', 'H', 'H', 'C', 'H', 'H', 'H', 'Pd', 'C', 'H', 'H', 'H', 'C', 'H', 'H', 'H', 'N', 'C', 'H', 'H', 'H']
Ligand atom label:  1  Ligand atom A nbo:  -0.50432
Ligand atom label:  12  Ligand atom B nbo:  -0.43562
Atom_a:  12 Atom_b:  1
C:\Users\George\Desktop\Research_UCLA\CIC\Computational Work\Project cluster version 2\project_catalyst_repurposing\structures_ligand_id\pd_me2_structures\ligand_xyz\ligand-209-n-o-50-ligand_xyz.txt
Ending node: 0
Starting node: 11
(2.212354, 1.160492, -0.686508)   11
(2.749004, 0.011975, -0.574894)   41
(2.038451, -1.14979, -0.784815)   2
(0.571153, -1.125591, -1.020948)   1
(-0.171455, -0.269736, -0.420483)   0

C:\Users\George\AppData\Local\Temp\ipykernel_7832\386804788.py:583: DeprecationWarning:

to_plotly_figure is deprecated and will be removed in version 4.0.0. Use MolGraph.to_plotly() instead.

C:\Users\George\AppData\Local\Temp\ipykernel_7832\386804788.py:589: DeprecationWarning:

to_networkx_graph is deprecated and will be removed in version 4.0.0. Use MolGraph.to_networkx() instead.

ligand-210-n-o-51
Pd number index:  41
['N', 'C', 'C', 'C', 'C', 'H', 'C', 'C', 'H', 'H', 'H', 'O', 'C', 'C', 'C', 'C', 'C', 'C', 'H', 'H', 'H', 'C', 'H', 'C', 'H', 'H', 'H', 'C', 'H', 'H', 'H', 'C', 'H', 'C', 'H', 'H', 'H', 'C', 'H', 'H', 'H', 'Pd', 'C', 'H', 'H', 'H', 'C', 'H', 'H', 'H', 'N', 'H']
Ligand atom label:  1  Ligand atom A nbo:  -0.50628
Ligand atom label:  12  Ligand atom B nbo:  -0.43552
Atom_a:  12 Atom_b:  1
C:\Users\George\Desktop\Research_UCLA\CIC\Computational Work\Project cluster version 2\project_catalyst_repurposing\structures_ligand_id\pd_me2_structures\ligand_xyz\ligand-210-n-o-51-ligand_xyz.txt
Ending node: 0
Starting node: 11
(2.38775, -1.063173, 0.082027)   11
(2.892582, 0.086105, 0.24092)   41
(2.149171, 1.210117, 0.545576)   2
(0.695955, 1.203895, 0.679432)   1
(-0.137479, 0.311303, 0.306933)   0
ligand-211-n-o-52

C:\Users\George\AppData\Local\Temp\ipykernel_7832\386804788.py:583: DeprecationWarning:

to_plotly_figure is deprecated and will be removed in version 4.0.0. Use MolGraph.to_plotly() instead.

C:\Users\George\AppData\Local\Temp\ipykernel_7832\386804788.py:589: DeprecationWarning:

to_networkx_graph is deprecated and will be removed in version 4.0.0. Use MolGraph.to_networkx() instead.

Pd number index:  36
['N', 'C', 'C', 'C', 'H', 'C', 'O', 'C', 'C', 'C', 'C', 'C', 'C', 'H', 'H', 'H', 'C', 'H', 'C', 'H', 'H', 'H', 'C', 'H', 'H', 'H', 'C', 'H', 'C', 'H', 'H', 'H', 'C', 'H', 'H', 'H', 'Pd', 'C', 'H', 'H', 'H', 'C', 'H', 'H', 'H', 'N', 'H', 'H', 'C', 'C', 'C', 'C', 'H', 'C', 'C', 'H', 'H', 'H']
Ligand atom label:  1  Ligand atom A nbo:  -0.5039
Ligand atom label:  7  Ligand atom B nbo:  -0.44255
Atom_a:  7 Atom_b:  1
C:\Users\George\Desktop\Research_UCLA\CIC\Computational Work\Project cluster version 2\project_catalyst_repurposing\structures_ligand_id\pd_me2_structures\ligand_xyz\ligand-211-n-o-52-ligand_xyz.txt
Ending node: 0
Starting node: 6
(1.17597, 1.83777, -0.334783)   6
(2.033793, 0.901619, -0.295126)   36
(1.666256, -0.437769, -0.505274)   2
(0.275308, -0.857657, -0.669656)   1
(-0.781033, -0.239508, -0.311644)   0
ligand-212-n-o-53

C:\Users\George\AppData\Local\Temp\ipykernel_7832\386804788.py:583: DeprecationWarning:

to_plotly_figure is deprecated and will be removed in version 4.0.0. Use MolGraph.to_plotly() instead.

C:\Users\George\AppData\Local\Temp\ipykernel_7832\386804788.py:589: DeprecationWarning:

to_networkx_graph is deprecated and will be removed in version 4.0.0. Use MolGraph.to_networkx() instead.

Pd number index:  40
['N', 'C', 'C', 'C', 'C', 'H', 'C', 'C', 'H', 'H', 'O', 'C', 'C', 'C', 'C', 'C', 'C', 'H', 'H', 'H', 'C', 'H', 'C', 'H', 'H', 'H', 'C', 'H', 'H', 'H', 'C', 'H', 'C', 'H', 'H', 'H', 'C', 'H', 'H', 'H', 'Pd', 'C', 'H', 'H', 'H', 'C', 'H', 'H', 'H', 'N', 'H', 'C', 'C', 'C', 'C', 'H', 'C', 'H', 'C', 'H', 'H', 'H']
Ligand atom label:  1  Ligand atom A nbo:  -0.50758
Ligand atom label:  11  Ligand atom B nbo:  -0.43684
Atom_a:  11 Atom_b:  1
C:\Users\George\Desktop\Research_UCLA\CIC\Computational Work\Project cluster version 2\project_catalyst_repurposing\structures_ligand_id\pd_me2_structures\ligand_xyz\ligand-212-n-o-53-ligand_xyz.txt
Ending node: 0
Starting node: 10
(-1.528529, -0.263369, -0.636801)   10
(-1.733066, 0.983361, -0.50628)   40
(-0.700199, 1.890785, -0.623107)   2
(0.700689, 1.481435, -0.703152)   1
(1.218869, 0.369907, -0.348777)   0
ligand-213-n-o-54

C:\Users\George\AppData\Local\Temp\ipykernel_7832\386804788.py:583: DeprecationWarning:

to_plotly_figure is deprecated and will be removed in version 4.0.0. Use MolGraph.to_plotly() instead.

C:\Users\George\AppData\Local\Temp\ipykernel_7832\386804788.py:589: DeprecationWarning:

to_networkx_graph is deprecated and will be removed in version 4.0.0. Use MolGraph.to_networkx() instead.

Pd number index:  39
['N', 'C', 'C', 'C', 'C', 'H', 'C', 'C', 'H', 'O', 'C', 'C', 'C', 'C', 'C', 'C', 'H', 'H', 'H', 'C', 'H', 'C', 'H', 'H', 'H', 'C', 'H', 'H', 'H', 'C', 'H', 'C', 'H', 'H', 'H', 'C', 'H', 'H', 'H', 'Pd', 'C', 'H', 'H', 'H', 'C', 'H', 'H', 'H', 'N', 'H', 'H', 'N', 'O', 'O']
Ligand atom label:  1  Ligand atom A nbo:  -0.5077
Ligand atom label:  10  Ligand atom B nbo:  -0.40347
Atom_a:  10 Atom_b:  1
C:\Users\George\Desktop\Research_UCLA\CIC\Computational Work\Project cluster version 2\project_catalyst_repurposing\structures_ligand_id\pd_me2_structures\ligand_xyz\ligand-213-n-o-54-ligand_xyz.txt
Ending node: 0
Starting node: 9
(1.163216, 2.10234, -0.001252)   9
(2.105423, 1.271587, -0.033764)   39
(1.918648, -0.092351, -0.218271)   2
(0.613861, -0.726895, -0.382565)   1
(-0.548834, -0.226119, -0.222214)   0
ligand-214-n-o-55

C:\Users\George\AppData\Local\Temp\ipykernel_7832\386804788.py:583: DeprecationWarning:

to_plotly_figure is deprecated and will be removed in version 4.0.0. Use MolGraph.to_plotly() instead.

C:\Users\George\AppData\Local\Temp\ipykernel_7832\386804788.py:589: DeprecationWarning:

to_networkx_graph is deprecated and will be removed in version 4.0.0. Use MolGraph.to_networkx() instead.

Pd number index:  39
['N', 'C', 'C', 'C', 'C', 'H', 'C', 'C', 'H', 'O', 'C', 'C', 'C', 'C', 'C', 'C', 'H', 'H', 'H', 'C', 'H', 'C', 'H', 'H', 'H', 'C', 'H', 'H', 'H', 'C', 'H', 'C', 'H', 'H', 'H', 'C', 'H', 'H', 'H', 'Pd', 'C', 'H', 'H', 'H', 'C', 'H', 'H', 'H', 'N', 'H', 'H', 'O', 'C', 'H', 'H', 'H']
Ligand atom label:  1  Ligand atom A nbo:  -0.40022
Ligand atom label:  10  Ligand atom B nbo:  -0.41655
Atom_a:  1 Atom_b:  10
C:\Users\George\Desktop\Research_UCLA\CIC\Computational Work\Project cluster version 2\project_catalyst_repurposing\structures_ligand_id\pd_me2_structures\ligand_xyz\ligand-214-n-o-55-ligand_xyz.txt
Starting node: 0
Ending node: 9
(-0.470737, 0.206576, 0.348743)   0
(0.616382, 0.769748, 0.67961)   1
(1.97411, 0.272014, 0.497812)   2
(2.269491, -1.05035, 0.272598)   39
(1.389633, -1.979079, 0.281675)   9
ligand-215-n-o-56

C:\Users\George\AppData\Local\Temp\ipykernel_7832\386804788.py:583: DeprecationWarning:

to_plotly_figure is deprecated and will be removed in version 4.0.0. Use MolGraph.to_plotly() instead.

C:\Users\George\AppData\Local\Temp\ipykernel_7832\386804788.py:589: DeprecationWarning:

to_networkx_graph is deprecated and will be removed in version 4.0.0. Use MolGraph.to_networkx() instead.

Pd number index:  42
['N', 'C', 'H', 'C', 'C', 'C', 'C', 'H', 'C', 'C', 'H', 'H', 'O', 'C', 'C', 'C', 'C', 'C', 'C', 'H', 'H', 'H', 'C', 'H', 'C', 'H', 'H', 'H', 'C', 'H', 'H', 'H', 'C', 'H', 'C', 'H', 'H', 'H', 'C', 'H', 'H', 'H', 'Pd', 'C', 'H', 'H', 'H', 'C', 'H', 'H', 'H', 'C', 'C', 'C', 'C', 'H', 'C', 'C', 'H', 'H', 'H', 'N', 'O', 'O']
Ligand atom label:  1  Ligand atom B nbo:  -0.54359
Ligand atom label:  13  Ligand atom A nbo:  -0.65385
Atom_a:  1 Atom_b:  13
C:\Users\George\Desktop\Research_UCLA\CIC\Computational Work\Project cluster version 2\project_catalyst_repurposing\structures_ligand_id\pd_me2_structures\ligand_xyz\ligand-215-n-o-56-ligand_xyz.txt
Starting node: 0
Ending node: 12
(1.642972, 0.490446, -0.089826)   0
(1.008963, 1.569269, 0.223714)   1
(-0.388496, 1.756337, 0.509687)   3
(-1.39572, 0.73779, 0.291344)   5
(-1.161382, -0.398929, -0.197993)   12
ligand-216-n-o-57

C:\Users\George\AppData\Local\Temp\ipykernel_7832\386804788.py:583: DeprecationWarning:

to_plotly_figure is deprecated and will be removed in version 4.0.0. Use MolGraph.to_plotly() instead.

C:\Users\George\AppData\Local\Temp\ipykernel_7832\386804788.py:589: DeprecationWarning:

to_networkx_graph is deprecated and will be removed in version 4.0.0. Use MolGraph.to_networkx() instead.

Pd number index:  42
['N', 'C', 'H', 'C', 'C', 'C', 'C', 'H', 'C', 'C', 'H', 'H', 'O', 'C', 'C', 'C', 'C', 'C', 'C', 'H', 'H', 'H', 'C', 'H', 'C', 'H', 'H', 'H', 'C', 'H', 'H', 'H', 'C', 'H', 'C', 'H', 'H', 'H', 'C', 'H', 'H', 'H', 'Pd', 'C', 'H', 'H', 'H', 'C', 'H', 'H', 'H', 'C', 'C', 'C', 'C', 'C', 'C', 'F', 'F', 'F', 'F', 'F']
Ligand atom label:  1  Ligand atom B nbo:  -0.53856
Ligand atom label:  13  Ligand atom A nbo:  -0.67103
Atom_a:  1 Atom_b:  13
C:\Users\George\Desktop\Research_UCLA\CIC\Computational Work\Project cluster version 2\project_catalyst_repurposing\structures_ligand_id\pd_me2_structures\ligand_xyz\ligand-216-n-o-57-ligand_xyz.txt

C:\Users\George\AppData\Local\Temp\ipykernel_7832\386804788.py:583: DeprecationWarning:

to_plotly_figure is deprecated and will be removed in version 4.0.0. Use MolGraph.to_plotly() instead.

C:\Users\George\AppData\Local\Temp\ipykernel_7832\386804788.py:589: DeprecationWarning:

to_networkx_graph is deprecated and will be removed in version 4.0.0. Use MolGraph.to_networkx() instead.

Starting node: 0
Ending node: 12
(2.020413, -0.514062, 0.080703)   0
(1.538667, -1.654907, -0.278777)   1
(0.169571, -2.026373, -0.52277)   3
(-0.954311, -1.151653, -0.256987)   5
(-0.872461, -0.008892, 0.258509)   12
ligand-217-n-o-58
Pd number index:  42
['N', 'C', 'H', 'C', 'C', 'C', 'C', 'H', 'C', 'C', 'H', 'H', 'O', 'C', 'C', 'C', 'C', 'C', 'C', 'H', 'H', 'H', 'C', 'H', 'C', 'H', 'H', 'H', 'C', 'H', 'H', 'H', 'C', 'H', 'C', 'H', 'H', 'H', 'C', 'H', 'H', 'H', 'Pd', 'C', 'H', 'H', 'H', 'C', 'H', 'H', 'H', 'C', 'C', 'C', 'C', 'C', 'C', 'H', 'H', 'H', 'H', 'O', 'C', 'H', 'H', 'H']
Ligand atom label:  1  Ligand atom B nbo:  -0.54377
Ligand atom label:  13  Ligand atom A nbo:  -0.65646
Atom_a:  1 Atom_b:  13
C:\Users\George\Desktop\Research_UCLA\CIC\Computational Work\Project cluster version 2\project_catalyst_repurposing\structures_ligand_id\pd_me2_structures\ligand_xyz\ligand-217-n-o-58-ligand_xyz.txt
Starting node: 0
Ending node: 12
(-1.407757, 0.462589, 0.202992)   0
(-0.86714, 1.583169, 0.555419)   1
(0.507996, 1.989977, 0.512439)   3
(1.58837, 1.120599, 0.093826)   5
(1.432959, -0.00557, -0.444548)   12
ligand-218-n-o-59

C:\Users\George\AppData\Local\Temp\ipykernel_7832\386804788.py:583: DeprecationWarning:

to_plotly_figure is deprecated and will be removed in version 4.0.0. Use MolGraph.to_plotly() instead.

C:\Users\George\AppData\Local\Temp\ipykernel_7832\386804788.py:589: DeprecationWarning:

to_networkx_graph is deprecated and will be removed in version 4.0.0. Use MolGraph.to_networkx() instead.

Pd number index:  41
['N', 'C', 'H', 'C', 'C', 'C', 'C', 'H', 'C', 'C', 'H', 'O', 'C', 'C', 'C', 'C', 'C', 'C', 'H', 'H', 'H', 'C', 'H', 'C', 'H', 'H', 'H', 'C', 'H', 'H', 'H', 'C', 'H', 'C', 'H', 'H', 'H', 'C', 'H', 'H', 'H', 'Pd', 'C', 'H', 'H', 'H', 'C', 'H', 'H', 'H', 'C', 'C', 'C', 'H', 'C', 'H', 'H', 'C', 'H', 'H', 'C', 'H', 'H', 'H', 'H', 'H', 'H', 'C', 'H', 'H', 'H']
Ligand atom label:  1  Ligand atom B nbo:  -0.54439
Ligand atom label:  12  Ligand atom A nbo:  -0.68029
Atom_a:  1 Atom_b:  12
C:\Users\George\Desktop\Research_UCLA\CIC\Computational Work\Project cluster version 2\project_catalyst_repurposing\structures_ligand_id\pd_me2_structures\ligand_xyz\ligand-218-n-o-59-ligand_xyz.txt

C:\Users\George\AppData\Local\Temp\ipykernel_7832\386804788.py:583: DeprecationWarning:

to_plotly_figure is deprecated and will be removed in version 4.0.0. Use MolGraph.to_plotly() instead.

C:\Users\George\AppData\Local\Temp\ipykernel_7832\386804788.py:589: DeprecationWarning:

to_networkx_graph is deprecated and will be removed in version 4.0.0. Use MolGraph.to_networkx() instead.

Starting node: 0
Ending node: 11
(1.451077, 0.379935, -0.154649)   0
(0.782361, 1.486896, -0.133632)   1
(-0.63466, 1.700943, -0.087093)   3
(-1.612191, 0.641705, -0.171119)   5
(-1.341633, -0.588469, -0.262342)   11
ligand-219-n-o-60
Pd number index:  13
['N', 'C', 'H', 'C', 'C', 'C', 'C', 'H', 'C', 'C', 'H', 'H', 'O', 'Pd', 'C', 'H', 'H', 'H', 'C', 'H', 'H', 'H', 'C', 'C', 'H', 'H', 'H', 'C', 'H', 'H', 'H', 'C', 'H', 'H', 'H', 'C', 'C', 'C', 'C', 'C', 'C', 'C', 'C', 'C', 'H', 'C', 'H', 'H', 'H', 'C', 'H', 'C', 'C', 'C', 'C', 'H', 'C', 'H', 'C', 'H', 'H', 'H', 'C', 'C', 'C', 'C', 'H', 'C', 'H', 'C', 'H', 'H', 'H', 'C', 'H', 'C', 'C', 'C', 'C', 'H', 'C', 'H', 'C', 'H', 'H', 'H', 'C', 'C', 'C', 'C', 'H', 'C', 'H', 'C', 'H', 'H', 'H', 'C', 'C', 'C', 'C', 'H', 'C', 'H', 'C', 'H', 'H', 'C', 'C', 'H', 'H', 'H', 'C', 'H', 'H', 'H', 'C', 'H', 'H', 'H']
Ligand atom label:  1  Ligand atom B nbo:  -0.56454
Ligand atom label:  13  Ligand atom A nbo:  -0.6936
Atom_a:  1 Atom_b:  13
C:\Users\George\Desktop\Research_UCLA\CIC\Computational Work\Project cluster version 2\project_catalyst_repurposing\structures_ligand_id\pd_me2_structures\ligand_xyz\ligand-219-n-o-60-ligand_xyz.txt
Starting node: 0
Ending node: 12
(-0.749519, 0.253385, -0.241606)   0
(-1.596595, 0.002946, -1.184505)   1
(-2.927206, -0.52737, -1.092908)   3
(-3.494799, -1.073753, 0.123196)   5
(-2.940781, -0.985682, 1.256239)   12
ligand-220-n-o-61

C:\Users\George\AppData\Local\Temp\ipykernel_7832\386804788.py:583: DeprecationWarning:

to_plotly_figure is deprecated and will be removed in version 4.0.0. Use MolGraph.to_plotly() instead.

C:\Users\George\AppData\Local\Temp\ipykernel_7832\386804788.py:589: DeprecationWarning:

to_networkx_graph is deprecated and will be removed in version 4.0.0. Use MolGraph.to_networkx() instead.

Pd number index:  13
['N', 'C', 'H', 'C', 'C', 'C', 'C', 'H', 'C', 'C', 'H', 'H', 'O', 'Pd', 'C', 'H', 'H', 'H', 'C', 'H', 'H', 'H', 'C', 'C', 'H', 'H', 'H', 'C', 'H', 'H', 'H', 'C', 'H', 'H', 'H', 'C', 'C', 'C', 'C', 'C', 'C', 'C', 'C', 'C', 'H', 'C', 'H', 'H', 'H', 'C', 'H', 'C', 'C', 'C', 'C', 'H', 'C', 'H', 'C', 'H', 'H', 'H', 'C', 'C', 'C', 'C', 'H', 'C', 'H', 'C', 'H', 'H', 'H', 'C', 'H', 'C', 'C', 'C', 'C', 'H', 'C', 'H', 'C', 'H', 'H', 'H', 'C', 'C', 'C', 'C', 'H', 'C', 'H', 'C', 'H', 'H', 'H', 'C', 'C', 'C', 'C', 'H', 'C', 'H', 'C', 'H', 'H', 'C', 'H', 'H', 'H']
Ligand atom label:  1  Ligand atom B nbo:  -0.54335
Ligand atom label:  13  Ligand atom A nbo:  -0.71041
Atom_a:  1 Atom_b:  13
C:\Users\George\Desktop\Research_UCLA\CIC\Computational Work\Project cluster version 2\project_catalyst_repurposing\structures_ligand_id\pd_me2_structures\ligand_xyz\ligand-220-n-o-61-ligand_xyz.txt
Starting node: 0
Ending node: 12
(1.004843, -0.404336, -0.249369)   0
(1.803134, -0.218115, -1.248861)   1
(3.199157, 0.111331, -1.257721)   3
(3.960678, 0.455684, -0.075474)   5
(3.468022, 0.481327, 1.088802)   12
ligand-221-n-o-62

C:\Users\George\AppData\Local\Temp\ipykernel_7832\386804788.py:583: DeprecationWarning:

to_plotly_figure is deprecated and will be removed in version 4.0.0. Use MolGraph.to_plotly() instead.

C:\Users\George\AppData\Local\Temp\ipykernel_7832\386804788.py:589: DeprecationWarning:

to_networkx_graph is deprecated and will be removed in version 4.0.0. Use MolGraph.to_networkx() instead.

Pd number index:  13
['N', 'C', 'H', 'C', 'C', 'C', 'C', 'H', 'C', 'C', 'H', 'H', 'O', 'Pd', 'C', 'H', 'H', 'H', 'C', 'H', 'H', 'H', 'C', 'C', 'H', 'H', 'H', 'C', 'H', 'H', 'H', 'C', 'H', 'H', 'H', 'C', 'C', 'C', 'C', 'C', 'C', 'C', 'C', 'C', 'H', 'C', 'H', 'H', 'H', 'C', 'H', 'C', 'C', 'C', 'C', 'H', 'C', 'H', 'C', 'H', 'H', 'H', 'C', 'C', 'C', 'C', 'H', 'C', 'H', 'C', 'H', 'H', 'H', 'C', 'H', 'C', 'C', 'C', 'C', 'H', 'C', 'H', 'C', 'H', 'H', 'H', 'C', 'C', 'C', 'C', 'H', 'C', 'H', 'C', 'H', 'H', 'H', 'C', 'C', 'C', 'C', 'H', 'C', 'H', 'C', 'H', 'H', 'H']
Ligand atom label:  1  Ligand atom B nbo:  -0.54417
Ligand atom label:  13  Ligand atom A nbo:  -0.70988
Atom_a:  1 Atom_b:  13
C:\Users\George\Desktop\Research_UCLA\CIC\Computational Work\Project cluster version 2\project_catalyst_repurposing\structures_ligand_id\pd_me2_structures\ligand_xyz\ligand-221-n-o-62-ligand_xyz.txt
Starting node: 0
Ending node: 12
(1.088443, -0.412134, -0.272867)   0
(1.86899, -0.219921, -1.286103)   1
(3.272566, 0.059843, -1.32083)   3
(4.081402, 0.303561, -0.145611)   5
(3.616551, 0.316467, 1.030417)   12
ligand-222-n-o-63
Pd number index:  13
['N', 'C', 'H', 'C', 'C', 'C', 'C', 'H', 'C', 'C', 'H', 'H', 'O', 'Pd', 'C', 'H', 'H', 'H', 'C', 'H', 'H', 'H', 'C', 'C', 'H', 'H', 'H', 'C', 'H', 'H', 'H', 'C', 'H', 'H', 'H', 'C', 'C', 'C', 'C', 'C', 'C', 'C', 'C', 'C', 'H', 'C', 'H', 'H', 'H', 'C', 'H', 'C', 'C', 'C', 'C', 'H', 'C', 'H', 'C', 'H', 'H', 'H', 'C', 'C', 'C', 'C', 'H', 'C', 'H', 'C', 'H', 'H', 'H', 'C', 'H', 'C', 'C', 'C', 'C', 'H', 'C', 'H', 'C', 'H', 'H', 'H', 'C', 'C', 'C', 'C', 'H', 'C', 'H', 'C', 'H', 'H', 'H', 'C', 'C', 'C', 'C', 'H', 'C', 'H', 'C', 'H', 'H', 'C', 'F', 'F', 'F']
Ligand atom label:  1  Ligand atom B nbo:  -0.57356
Ligand atom label:  13  Ligand atom A nbo:  -0.69757
Atom_a:  1 Atom_b:  13

C:\Users\George\AppData\Local\Temp\ipykernel_7832\386804788.py:583: DeprecationWarning:

to_plotly_figure is deprecated and will be removed in version 4.0.0. Use MolGraph.to_plotly() instead.

C:\Users\George\AppData\Local\Temp\ipykernel_7832\386804788.py:589: DeprecationWarning:

to_networkx_graph is deprecated and will be removed in version 4.0.0. Use MolGraph.to_networkx() instead.

C:\Users\George\Desktop\Research_UCLA\CIC\Computational Work\Project cluster version 2\project_catalyst_repurposing\structures_ligand_id\pd_me2_structures\ligand_xyz\ligand-222-n-o-63-ligand_xyz.txt
Starting node: 0
Ending node: 12
(-0.709847, 0.007684, -0.176765)   0
(-1.536633, -0.339499, -1.109926)   1
(-2.898139, -0.765478, -0.992183)   3
(-3.537427, -1.09225, 0.265916)   5
(-2.914423, -1.15511, 1.36516)   12
ligand-223-n-o-64

C:\Users\George\AppData\Local\Temp\ipykernel_7832\386804788.py:583: DeprecationWarning:

to_plotly_figure is deprecated and will be removed in version 4.0.0. Use MolGraph.to_plotly() instead.

C:\Users\George\AppData\Local\Temp\ipykernel_7832\386804788.py:589: DeprecationWarning:

to_networkx_graph is deprecated and will be removed in version 4.0.0. Use MolGraph.to_networkx() instead.

Pd number index:  41
['N', 'C', 'H', 'C', 'C', 'C', 'C', 'H', 'C', 'C', 'H', 'O', 'C', 'C', 'C', 'C', 'C', 'C', 'H', 'H', 'H', 'C', 'H', 'C', 'H', 'H', 'H', 'C', 'H', 'H', 'H', 'C', 'H', 'C', 'H', 'H', 'H', 'C', 'H', 'H', 'H', 'Pd', 'C', 'H', 'H', 'H', 'C', 'H', 'H', 'H', 'C', 'C', 'C', 'H', 'H', 'H', 'C', 'H', 'H', 'H', 'C', 'H', 'H', 'H', 'C', 'H', 'H', 'H', 'C', 'H', 'H', 'H', 'C', 'H', 'H', 'H']
Ligand atom label:  1  Ligand atom B nbo:  -0.57219
Ligand atom label:  12  Ligand atom A nbo:  -0.68176
Atom_a:  1 Atom_b:  12
C:\Users\George\Desktop\Research_UCLA\CIC\Computational Work\Project cluster version 2\project_catalyst_repurposing\structures_ligand_id\pd_me2_structures\ligand_xyz\ligand-223-n-o-64-ligand_xyz.txt

C:\Users\George\AppData\Local\Temp\ipykernel_7832\386804788.py:583: DeprecationWarning:

to_plotly_figure is deprecated and will be removed in version 4.0.0. Use MolGraph.to_plotly() instead.

C:\Users\George\AppData\Local\Temp\ipykernel_7832\386804788.py:589: DeprecationWarning:

to_networkx_graph is deprecated and will be removed in version 4.0.0. Use MolGraph.to_networkx() instead.

Starting node: 0
Ending node: 11
(1.316287, -0.495229, 4e-06)   0
(0.209099, -1.162182, 0.000188)   1
(-1.152057, -0.707382, 0.000117)   3
(-1.538512, 0.683762, -6.2e-05)   5
(-0.714347, 1.639484, -0.000182)   11
ligand-224-n-o-65
Pd number index:  40
['N', 'C', 'H', 'C', 'C', 'C', 'C', 'H', 'C', 'C', 'H', 'O', 'C', 'C', 'C', 'C', 'C', 'C', 'H', 'H', 'C', 'H', 'C', 'H', 'H', 'H', 'C', 'H', 'H', 'H', 'C', 'H', 'C', 'H', 'H', 'H', 'C', 'H', 'H', 'H', 'Pd', 'C', 'H', 'H', 'H', 'C', 'H', 'H', 'H', 'C', 'C', 'C', 'C', 'H', 'C', 'H', 'C', 'H', 'H', 'H', 'H', 'H']
Ligand atom label:  1  Ligand atom B nbo:  -0.56794
Ligand atom label:  12  Ligand atom A nbo:  -0.665
Atom_a:  1 Atom_b:  12
C:\Users\George\Desktop\Research_UCLA\CIC\Computational Work\Project cluster version 2\project_catalyst_repurposing\structures_ligand_id\pd_me2_structures\ligand_xyz\ligand-224-n-o-65-ligand_xyz.txt
Starting node: 0
Ending node: 11
(-1.302147, 0.508926, -0.021687)   0
(-0.67469, 1.636565, -0.052204)   1
(0.734148, 1.916529, -0.013204)   3
(1.764549, 0.895451, -0.012185)   5
(1.528633, -0.339348, -0.058008)   11
ligand-225-n-o-66

C:\Users\George\AppData\Local\Temp\ipykernel_7832\386804788.py:583: DeprecationWarning:

to_plotly_figure is deprecated and will be removed in version 4.0.0. Use MolGraph.to_plotly() instead.

C:\Users\George\AppData\Local\Temp\ipykernel_7832\386804788.py:589: DeprecationWarning:

to_networkx_graph is deprecated and will be removed in version 4.0.0. Use MolGraph.to_networkx() instead.

Pd number index:  40
['N', 'C', 'H', 'C', 'C', 'C', 'C', 'H', 'C', 'C', 'H', 'O', 'C', 'C', 'C', 'C', 'C', 'C', 'H', 'H', 'C', 'H', 'C', 'H', 'H', 'H', 'C', 'H', 'H', 'H', 'C', 'H', 'C', 'H', 'H', 'H', 'C', 'H', 'H', 'H', 'Pd', 'C', 'H', 'H', 'H', 'C', 'H', 'H', 'H', 'C', 'C', 'C', 'C', 'H', 'C', 'H', 'C', 'H', 'H', 'H', 'H', 'C', 'H', 'H', 'C', 'H', 'C', 'H', 'H']
Ligand atom label:  1  Ligand atom B nbo:  -0.56798
Ligand atom label:  12  Ligand atom A nbo:  -0.66491
Atom_a:  1 Atom_b:  12
C:\Users\George\Desktop\Research_UCLA\CIC\Computational Work\Project cluster version 2\project_catalyst_repurposing\structures_ligand_id\pd_me2_structures\ligand_xyz\ligand-225-n-o-66-ligand_xyz.txt

C:\Users\George\AppData\Local\Temp\ipykernel_7832\386804788.py:583: DeprecationWarning:

to_plotly_figure is deprecated and will be removed in version 4.0.0. Use MolGraph.to_plotly() instead.

C:\Users\George\AppData\Local\Temp\ipykernel_7832\386804788.py:589: DeprecationWarning:

to_networkx_graph is deprecated and will be removed in version 4.0.0. Use MolGraph.to_networkx() instead.

Starting node: 0
Ending node: 11
(-0.708211, 0.325773, -0.098439)   0
(-0.170344, 1.489976, -0.245838)   1
(1.210746, 1.885148, -0.209972)   3
(2.319403, 0.954776, -0.106932)   5
(2.185144, -0.294955, -0.056008)   11
ligand-226-n-o-67
Pd number index:  20
['N', 'C', 'H', 'C', 'C', 'C', 'C', 'H', 'C', 'C', 'H', 'O', 'C', 'C', 'C', 'C', 'C', 'C', 'H', 'H', 'Pd', 'C', 'H', 'H', 'H', 'C', 'H', 'H', 'H', 'C', 'C', 'C', 'C', 'H', 'C', 'H', 'C', 'H', 'H', 'H', 'H', 'C', 'H', 'H', 'C', 'H', 'C', 'H', 'H', 'C', 'H', 'H', 'H', 'C', 'H', 'H', 'H']
Ligand atom label:  1  Ligand atom B nbo:  -0.49052
Ligand atom label:  12  Ligand atom A nbo:  -0.66699
Atom_a:  1 Atom_b:  12
C:\Users\George\Desktop\Research_UCLA\CIC\Computational Work\Project cluster version 2\project_catalyst_repurposing\structures_ligand_id\pd_me2_structures\ligand_xyz\ligand-226-n-o-67-ligand_xyz.txt
Starting node: 0
Ending node: 11
(0.875174, 0.37164, 0.102566)   0
(0.329579, 1.543268, 0.108683)   1
(-1.056845, 1.915078, 0.032967)   3
(-2.151786, 0.960889, 0.002869)   5
(-2.000154, -0.286226, 0.042228)   11
ligand-227-n-o-68

C:\Users\George\AppData\Local\Temp\ipykernel_7832\386804788.py:583: DeprecationWarning:

to_plotly_figure is deprecated and will be removed in version 4.0.0. Use MolGraph.to_plotly() instead.

C:\Users\George\AppData\Local\Temp\ipykernel_7832\386804788.py:589: DeprecationWarning:

to_networkx_graph is deprecated and will be removed in version 4.0.0. Use MolGraph.to_networkx() instead.

Pd number index:  20
['N', 'C', 'H', 'C', 'C', 'C', 'C', 'H', 'C', 'C', 'H', 'O', 'C', 'C', 'C', 'C', 'C', 'C', 'H', 'H', 'Pd', 'C', 'H', 'H', 'H', 'C', 'H', 'H', 'H', 'C', 'H', 'H', 'C', 'H', 'C', 'H', 'H', 'C', 'H', 'C', 'H', 'N', 'O', 'O', 'N', 'O', 'O', 'C', 'H', 'H', 'H', 'C', 'H', 'H', 'H', 'C', 'H', 'H', 'H', 'C', 'H', 'H', 'H']
Ligand atom label:  1  Ligand atom B nbo:  -0.53182
Ligand atom label:  12  Ligand atom A nbo:  -0.64781
Atom_a:  1 Atom_b:  12
C:\Users\George\Desktop\Research_UCLA\CIC\Computational Work\Project cluster version 2\project_catalyst_repurposing\structures_ligand_id\pd_me2_structures\ligand_xyz\ligand-227-n-o-68-ligand_xyz.txt

C:\Users\George\AppData\Local\Temp\ipykernel_7832\386804788.py:583: DeprecationWarning:

to_plotly_figure is deprecated and will be removed in version 4.0.0. Use MolGraph.to_plotly() instead.

C:\Users\George\AppData\Local\Temp\ipykernel_7832\386804788.py:589: DeprecationWarning:

to_networkx_graph is deprecated and will be removed in version 4.0.0. Use MolGraph.to_networkx() instead.

Starting node: 0
Ending node: 11
(0.49228, -0.009151, 0.093484)   0
(-0.335992, 0.969061, 0.153182)   1
(-1.782247, 0.954334, 0.075629)   3
(-2.576357, -0.270322, -0.063187)   5
(-2.093689, -1.402243, -0.194586)   11
ligand-228-n-o-69
Pd number index:  20
['N', 'C', 'H', 'C', 'C', 'C', 'C', 'H', 'C', 'C', 'H', 'O', 'C', 'C', 'C', 'C', 'C', 'C', 'H', 'H', 'Pd', 'C', 'H', 'H', 'H', 'C', 'H', 'H', 'H', 'C', 'H', 'H', 'C', 'H', 'C', 'H', 'H', 'C', 'H', 'C', 'H', 'C', 'H', 'H', 'H', 'C', 'H', 'H', 'H', 'C', 'H', 'H', 'H', 'C', 'H', 'H', 'H', 'C', 'C', 'H', 'H', 'H', 'C', 'H', 'H', 'H', 'C', 'H', 'H', 'H', 'C', 'H', 'H', 'H']
Ligand atom label:  1  Ligand atom B nbo:  -0.53846
Ligand atom label:  12  Ligand atom A nbo:  -0.68659
Atom_a:  1 Atom_b:  12
C:\Users\George\Desktop\Research_UCLA\CIC\Computational Work\Project cluster version 2\project_catalyst_repurposing\structures_ligand_id\pd_me2_structures\ligand_xyz\ligand-228-n-o-69-ligand_xyz.txt
Starting node: 0
Ending node: 11
(0.499611, 0.181181, 0.106485)   0
(-0.175979, 1.282051, 0.167188)   1
(-1.590796, 1.509636, 0.112362)   3
(-2.575376, 0.459982, -0.025485)   5
(-2.28166, -0.76471, -0.114157)   11
ligand-229-n-o-71

C:\Users\George\AppData\Local\Temp\ipykernel_7832\386804788.py:583: DeprecationWarning:

to_plotly_figure is deprecated and will be removed in version 4.0.0. Use MolGraph.to_plotly() instead.

C:\Users\George\AppData\Local\Temp\ipykernel_7832\386804788.py:589: DeprecationWarning:

to_networkx_graph is deprecated and will be removed in version 4.0.0. Use MolGraph.to_networkx() instead.

Pd number index:  11
['N', 'C', 'O', 'C', 'C', 'C', 'C', 'C', 'C', 'H', 'H', 'Pd', 'C', 'H', 'H', 'H', 'C', 'H', 'H', 'H', 'C', 'C', 'C', 'C', 'C', 'H', 'C', 'H', 'H', 'H', 'H', 'C', 'H', 'C', 'H', 'H', 'H', 'C', 'H', 'H', 'H', 'C', 'H', 'C', 'H', 'H', 'H', 'C', 'H', 'H', 'H', 'C', 'H', 'C', 'H', 'H', 'H', 'C', 'H', 'H', 'H']
Ligand atom label:  1  Ligand atom B nbo:  -0.60408
Ligand atom label:  3  Ligand atom A nbo:  -0.54849
Atom_a:  3 Atom_b:  1
C:\Users\George\Desktop\Research_UCLA\CIC\Computational Work\Project cluster version 2\project_catalyst_repurposing\structures_ligand_id\pd_me2_structures\ligand_xyz\ligand-229-n-o-71-ligand_xyz.txt
Ending node: 0
Starting node: 2
(-3.53182, -0.782613, -0.124379)   2
(-3.771267, 0.415555, -0.253546)   1
(-2.889875, 1.548078, -0.285735)   12
(-1.438912, 1.48281, -0.229026)   11
(-0.764334, 0.343968, -0.135346)   0
ligand-230-n-o-72

C:\Users\George\AppData\Local\Temp\ipykernel_7832\386804788.py:583: DeprecationWarning:

to_plotly_figure is deprecated and will be removed in version 4.0.0. Use MolGraph.to_plotly() instead.

C:\Users\George\AppData\Local\Temp\ipykernel_7832\386804788.py:589: DeprecationWarning:

to_networkx_graph is deprecated and will be removed in version 4.0.0. Use MolGraph.to_networkx() instead.

Pd number index:  24
['N', 'C', 'C', 'C', 'C', 'H', 'C', 'C', 'H', 'H', 'H', 'O', 'C', 'C', 'C', 'C', 'C', 'C', 'H', 'H', 'C', 'H', 'C', 'H', 'Pd', 'C', 'H', 'H', 'H', 'C', 'H', 'H', 'H', 'N', 'H', 'C', 'C', 'C', 'C', 'H', 'C', 'H', 'C', 'H', 'H', 'H', 'C', 'C', 'C', 'C', 'H', 'C', 'H', 'C', 'H', 'H', 'H', 'C', 'C', 'C', 'C', 'H', 'C', 'H', 'C', 'H', 'H', 'H', 'C', 'C', 'C', 'C', 'H', 'C', 'H', 'C', 'H', 'H', 'H', 'C', 'H', 'H', 'H']
Ligand atom label:  1  Ligand atom A nbo:  -0.48417
Ligand atom label:  12  Ligand atom B nbo:  -0.48366
Atom_a:  12 Atom_b:  1
C:\Users\George\Desktop\Research_UCLA\CIC\Computational Work\Project cluster version 2\project_catalyst_repurposing\structures_ligand_id\pd_me2_structures\ligand_xyz\ligand-230-n-o-72-ligand_xyz.txt
Ending node: 0
Starting node: 11
(1.998607, 1.397147, -1.960774)   11
(1.779862, 2.463021, -1.313131)   24
(1.03068, 2.516379, -0.15718)   2
(0.427791, 1.347555, 0.475202)   1
(0.232278, 0.180108, -0.004834)   0

C:\Users\George\AppData\Local\Temp\ipykernel_7832\386804788.py:583: DeprecationWarning:

to_plotly_figure is deprecated and will be removed in version 4.0.0. Use MolGraph.to_plotly() instead.

C:\Users\George\AppData\Local\Temp\ipykernel_7832\386804788.py:589: DeprecationWarning:

to_networkx_graph is deprecated and will be removed in version 4.0.0. Use MolGraph.to_networkx() instead.

ligand-231-n-o-73
Pd number index:  24
['N', 'C', 'C', 'C', 'C', 'H', 'C', 'C', 'H', 'H', 'H', 'O', 'C', 'C', 'C', 'C', 'C', 'C', 'H', 'H', 'C', 'H', 'C', 'H', 'Pd', 'C', 'H', 'H', 'H', 'C', 'H', 'H', 'H', 'N', 'H', 'C', 'H', 'H', 'H', 'C', 'C', 'C', 'C', 'C', 'C', 'H', 'C', 'H', 'C', 'C', 'H', 'C', 'H', 'H', 'H', 'H', 'C', 'C', 'C', 'C', 'C', 'C', 'H', 'C', 'H', 'C', 'C', 'H', 'C', 'H', 'H', 'H', 'H', 'C', 'C', 'C', 'C', 'C', 'C', 'H', 'C', 'H', 'C', 'C', 'H', 'C', 'H', 'H', 'H', 'H', 'C', 'C', 'C', 'C', 'C', 'C', 'H', 'C', 'H', 'C', 'C', 'H', 'C', 'H', 'H', 'H', 'H']
Ligand atom label:  1  Ligand atom B nbo:  -0.48729
Ligand atom label:  12  Ligand atom A nbo:  -0.48362
Atom_a:  12 Atom_b:  1
C:\Users\George\Desktop\Research_UCLA\CIC\Computational Work\Project cluster version 2\project_catalyst_repurposing\structures_ligand_id\pd_me2_structures\ligand_xyz\ligand-231-n-o-73-ligand_xyz.txt
Ending node: 0
Starting node: 11
(-0.834712, 1.856371, -2.407165)   11
(-0.723721, 2.845844, -1.624625)   24
(-0.377919, 2.747543, -0.292238)   2
(-0.093018, 1.495577, 0.400162)   1
(0.02002, 0.306225, -0.056676)   0
ligand-232-n-o-74

C:\Users\George\AppData\Local\Temp\ipykernel_7832\386804788.py:583: DeprecationWarning:

to_plotly_figure is deprecated and will be removed in version 4.0.0. Use MolGraph.to_plotly() instead.

C:\Users\George\AppData\Local\Temp\ipykernel_7832\386804788.py:589: DeprecationWarning:

to_networkx_graph is deprecated and will be removed in version 4.0.0. Use MolGraph.to_networkx() instead.

Pd number index:  22
['N', 'C', 'C', 'C', 'C', 'C', 'C', 'H', 'H', 'H', 'O', 'C', 'C', 'C', 'C', 'C', 'C', 'H', 'H', 'C', 'H', 'C', 'Pd', 'C', 'H', 'H', 'H', 'C', 'H', 'H', 'H', 'N', 'H', 'C', 'H', 'H', 'H', 'C', 'C', 'S', 'H', 'C', 'C', 'S', 'H', 'C', 'C', 'S', 'H', 'C', 'C', 'S', 'H', 'H', 'C', 'C', 'C', 'C', 'C', 'H', 'C', 'H', 'H', 'H', 'C', 'C', 'C', 'C', 'H', 'C', 'C', 'H', 'H', 'H', 'C', 'C', 'C', 'C', 'H', 'C', 'C', 'H', 'H', 'H', 'C', 'C', 'C', 'C', 'H', 'C', 'C', 'H', 'H', 'H']
Ligand atom label:  1  Ligand atom B nbo:  -0.55325
Ligand atom label:  11  Ligand atom A nbo:  -0.56027
Atom_a:  1 Atom_b:  11
C:\Users\George\Desktop\Research_UCLA\CIC\Computational Work\Project cluster version 2\project_catalyst_repurposing\structures_ligand_id\pd_me2_structures\ligand_xyz\ligand-232-n-o-74-ligand_xyz.txt
Starting node: 0
Ending node: 10
(-0.050317, 0.537407, 0.601501)   0
(-0.090625, 1.8191, 0.739891)   1
(0.187499, 2.651121, 1.894357)   2
(0.409164, 2.065101, 3.142646)   22
(-0.019118, 0.889772, 3.475842)   10
ligand-233-p-n-9

C:\Users\George\AppData\Local\Temp\ipykernel_7832\386804788.py:583: DeprecationWarning:

to_plotly_figure is deprecated and will be removed in version 4.0.0. Use MolGraph.to_plotly() instead.

C:\Users\George\AppData\Local\Temp\ipykernel_7832\386804788.py:589: DeprecationWarning:

to_networkx_graph is deprecated and will be removed in version 4.0.0. Use MolGraph.to_networkx() instead.

Pd number index:  54
['P', 'C', 'C', 'C', 'C', 'H', 'C', 'H', 'C', 'H', 'H', 'H', 'C', 'C', 'C', 'C', 'C', 'H', 'C', 'H', 'H', 'H', 'C', 'C', 'C', 'C', 'C', 'C', 'H', 'H', 'H', 'O', 'O', 'C', 'H', 'H', 'H', 'C', 'H', 'H', 'H', 'C', 'H', 'H', 'C', 'C', 'C', 'C', 'H', 'C', 'H', 'H', 'H', 'N', 'Pd', 'C', 'H', 'H', 'H', 'C', 'H', 'H', 'H']
Ligand atom label:  1  Ligand atom B nbo:  1.08969
Ligand atom label:  54  Ligand atom A nbo:  -0.49106
Atom_a:  1 Atom_b:  54
C:\Users\George\Desktop\Research_UCLA\CIC\Computational Work\Project cluster version 2\project_catalyst_repurposing\structures_ligand_id\pd_me2_structures\ligand_xyz\ligand-233-p-n-9-ligand_xyz.txt
Starting node: 0
Ending node: 53
(-0.259077, 0.415965, 0.584255)   0
(-0.142837, 0.412745, -1.28878)   41
(-1.529367, 0.137391, -1.773808)   44
(-2.14695, -0.931547, -1.235755)   53
ligand-234-p-n-10

C:\Users\George\AppData\Local\Temp\ipykernel_7832\386804788.py:583: DeprecationWarning:

to_plotly_figure is deprecated and will be removed in version 4.0.0. Use MolGraph.to_plotly() instead.

C:\Users\George\AppData\Local\Temp\ipykernel_7832\386804788.py:589: DeprecationWarning:

to_networkx_graph is deprecated and will be removed in version 4.0.0. Use MolGraph.to_networkx() instead.

Pd number index:  51
['P', 'C', 'C', 'C', 'C', 'H', 'C', 'H', 'C', 'H', 'H', 'H', 'C', 'C', 'C', 'C', 'C', 'H', 'C', 'H', 'H', 'H', 'C', 'C', 'C', 'C', 'C', 'C', 'H', 'H', 'H', 'O', 'O', 'C', 'H', 'H', 'H', 'C', 'H', 'H', 'H', 'C', 'C', 'C', 'C', 'H', 'C', 'H', 'H', 'H', 'N', 'Pd', 'C', 'H', 'H', 'H', 'C', 'H', 'H', 'H', 'N', 'H']
Ligand atom label:  1  Ligand atom B nbo:  1.34442
Ligand atom label:  51  Ligand atom A nbo:  -0.48788
Atom_a:  1 Atom_b:  51
C:\Users\George\Desktop\Research_UCLA\CIC\Computational Work\Project cluster version 2\project_catalyst_repurposing\structures_ligand_id\pd_me2_structures\ligand_xyz\ligand-234-p-n-10-ligand_xyz.txt

C:\Users\George\AppData\Local\Temp\ipykernel_7832\386804788.py:583: DeprecationWarning:

to_plotly_figure is deprecated and will be removed in version 4.0.0. Use MolGraph.to_plotly() instead.

C:\Users\George\AppData\Local\Temp\ipykernel_7832\386804788.py:589: DeprecationWarning:

to_networkx_graph is deprecated and will be removed in version 4.0.0. Use MolGraph.to_networkx() instead.

Starting node: 0
Ending node: 50
(-1.144795, 0.010793, -0.126732)   0
(-0.253905, 0.207655, -1.610011)   51
(0.80397, -0.601087, -1.94956)   41
(1.141251, -1.605307, -1.124069)   50
ligand-235-p-n-11
Pd number index:  51
['P', 'C', 'C', 'C', 'C', 'H', 'C', 'H', 'C', 'H', 'H', 'H', 'C', 'C', 'C', 'C', 'C', 'H', 'C', 'H', 'H', 'H', 'C', 'C', 'C', 'C', 'C', 'C', 'H', 'H', 'H', 'O', 'O', 'C', 'H', 'H', 'H', 'C', 'H', 'H', 'H', 'C', 'C', 'C', 'C', 'H', 'C', 'H', 'H', 'H', 'N', 'Pd', 'C', 'H', 'H', 'H', 'C', 'H', 'H', 'H', 'O']
Ligand atom label:  1  Ligand atom B nbo:  1.27958
Ligand atom label:  51  Ligand atom A nbo:  -0.54988
Atom_a:  1 Atom_b:  51
C:\Users\George\Desktop\Research_UCLA\CIC\Computational Work\Project cluster version 2\project_catalyst_repurposing\structures_ligand_id\pd_me2_structures\ligand_xyz\ligand-235-p-n-11-ligand_xyz.txt

C:\Users\George\AppData\Local\Temp\ipykernel_7832\386804788.py:583: DeprecationWarning:

to_plotly_figure is deprecated and will be removed in version 4.0.0. Use MolGraph.to_plotly() instead.

C:\Users\George\AppData\Local\Temp\ipykernel_7832\386804788.py:589: DeprecationWarning:

to_networkx_graph is deprecated and will be removed in version 4.0.0. Use MolGraph.to_networkx() instead.

Starting node: 0
Ending node: 50
(1.144717, 0.017795, 0.038741)   0
(0.357004, 0.279509, 1.541799)   51
(-0.644433, -0.506095, 1.941954)   41
(-1.043689, -1.530315, 1.185636)   50
ligand-236-p-n-12
Pd number index:  51
['P', 'C', 'C', 'C', 'C', 'H', 'C', 'H', 'C', 'H', 'H', 'H', 'C', 'C', 'C', 'C', 'C', 'H', 'C', 'H', 'H', 'H', 'C', 'C', 'C', 'C', 'C', 'C', 'H', 'H', 'H', 'O', 'O', 'C', 'H', 'H', 'H', 'C', 'H', 'H', 'H', 'C', 'C', 'C', 'C', 'H', 'C', 'H', 'H', 'H', 'N', 'Pd', 'C', 'H', 'H', 'H', 'C', 'H', 'H', 'H', 'C', 'H', 'C', 'C', 'C', 'C', 'C', 'C', 'F', 'F', 'F', 'F', 'F']
Ligand atom label:  1  Ligand atom B nbo:  0.98273
Ligand atom label:  51  Ligand atom A nbo:  -0.49323
Atom_a:  1 Atom_b:  51
C:\Users\George\Desktop\Research_UCLA\CIC\Computational Work\Project cluster version 2\project_catalyst_repurposing\structures_ligand_id\pd_me2_structures\ligand_xyz\ligand-236-p-n-12-ligand_xyz.txt
Starting node: 0
Ending node: 50
(1.221527, 0.629339, 0.451657)   0
(0.21661, -0.8476, -0.225559)   51
(1.186938, -2.008134, -0.185086)   41
(2.352302, -1.809841, -0.825587)   50
ligand-237-p-n-13

C:\Users\George\AppData\Local\Temp\ipykernel_7832\386804788.py:583: DeprecationWarning:

to_plotly_figure is deprecated and will be removed in version 4.0.0. Use MolGraph.to_plotly() instead.

C:\Users\George\AppData\Local\Temp\ipykernel_7832\386804788.py:589: DeprecationWarning:

to_networkx_graph is deprecated and will be removed in version 4.0.0. Use MolGraph.to_networkx() instead.

Pd number index:  51
['P', 'C', 'C', 'C', 'C', 'H', 'C', 'H', 'C', 'H', 'H', 'H', 'C', 'C', 'C', 'C', 'C', 'H', 'C', 'H', 'H', 'H', 'C', 'C', 'C', 'C', 'C', 'C', 'H', 'H', 'H', 'O', 'O', 'C', 'H', 'H', 'H', 'C', 'H', 'H', 'H', 'C', 'C', 'C', 'C', 'H', 'C', 'H', 'H', 'H', 'N', 'Pd', 'C', 'H', 'H', 'H', 'C', 'H', 'H', 'H', 'C', 'C', 'C', 'C', 'C', 'C', 'C', 'F', 'F', 'F', 'F', 'F', 'H']
Ligand atom label:  1  Ligand atom B nbo:  1.13456
Ligand atom label:  51  Ligand atom A nbo:  -0.48605
Atom_a:  1 Atom_b:  51
C:\Users\George\Desktop\Research_UCLA\CIC\Computational Work\Project cluster version 2\project_catalyst_repurposing\structures_ligand_id\pd_me2_structures\ligand_xyz\ligand-237-p-n-13-ligand_xyz.txt
Starting node: 0
Ending node: 50
(1.189735, 0.606443, -0.576196)   0
(0.258538, -0.242037, 0.840877)   51
(1.279263, -1.246454, 1.346315)   41
(1.80523, -2.081352, 0.435486)   50
ligand-238-n-o-75
Pd number index:  12
['N', 'C', 'C', 'C', 'C', 'H', 'C', 'C', 'H', 'H', 'H', 'O', 'Pd', 'C', 'H', 'H', 'H', 'C', 'H', 'H', 'H', 'N', 'H', 'C', 'C', 'C', 'C', 'C', 'C', 'H', 'C', 'H', 'C', 'C', 'C', 'C', 'H', 'C', 'H', 'C', 'H', 'H', 'H', 'C', 'C', 'C', 'C', 'H', 'C', 'H', 'C', 'H', 'H', 'H', 'H', 'C', 'H', 'C', 'C', 'C', 'C', 'H', 'C', 'H', 'C', 'H', 'H', 'H', 'C', 'C', 'C', 'C', 'H', 'C', 'H', 'C', 'H', 'H', 'H', 'C', 'H', 'H', 'H']

C:\Users\George\AppData\Local\Temp\ipykernel_7832\386804788.py:583: DeprecationWarning:

to_plotly_figure is deprecated and will be removed in version 4.0.0. Use MolGraph.to_plotly() instead.

C:\Users\George\AppData\Local\Temp\ipykernel_7832\386804788.py:589: DeprecationWarning:

to_networkx_graph is deprecated and will be removed in version 4.0.0. Use MolGraph.to_networkx() instead.

Ligand atom label:  1  Ligand atom A nbo:  -0.46993
Ligand atom label:  12  Ligand atom B nbo:  -0.46221
Atom_a:  12 Atom_b:  1
C:\Users\George\Desktop\Research_UCLA\CIC\Computational Work\Project cluster version 2\project_catalyst_repurposing\structures_ligand_id\pd_me2_structures\ligand_xyz\ligand-238-n-o-75-ligand_xyz.txt
Ending node: 0
Starting node: 11
(-0.344484, -3.243704, 0.83296)   11
(-0.418346, -3.528222, -0.395924)   12
(-0.203591, -2.622233, -1.417401)   2
(0.033781, -1.199471, -1.216437)   1
(0.007607, -0.509802, -0.140007)   0
ligand-239-n-o-76

C:\Users\George\AppData\Local\Temp\ipykernel_7832\386804788.py:583: DeprecationWarning:

to_plotly_figure is deprecated and will be removed in version 4.0.0. Use MolGraph.to_plotly() instead.

C:\Users\George\AppData\Local\Temp\ipykernel_7832\386804788.py:589: DeprecationWarning:

to_networkx_graph is deprecated and will be removed in version 4.0.0. Use MolGraph.to_networkx() instead.

Pd number index:  12
['N', 'C', 'C', 'C', 'C', 'H', 'C', 'C', 'H', 'H', 'H', 'O', 'Pd', 'C', 'H', 'H', 'H', 'C', 'H', 'H', 'H', 'N', 'H', 'C', 'C', 'C', 'C', 'C', 'C', 'C', 'C', 'C', 'H', 'C', 'H', 'H', 'H', 'C', 'H', 'C', 'C', 'C', 'C', 'H', 'C', 'H', 'C', 'H', 'H', 'H', 'C', 'C', 'C', 'C', 'H', 'C', 'H', 'C', 'H', 'H', 'H', 'C', 'H', 'C', 'C', 'C', 'C', 'H', 'C', 'H', 'C', 'H', 'H', 'H', 'C', 'C', 'C', 'C', 'H', 'C', 'H', 'C', 'H', 'H', 'H', 'C', 'C', 'C', 'C', 'H', 'C', 'H', 'C', 'H', 'H', 'C', 'H', 'H', 'H']
Ligand atom label:  1  Ligand atom A nbo:  -0.47779
Ligand atom label:  12  Ligand atom B nbo:  -0.47168
Atom_a:  12 Atom_b:  1
C:\Users\George\Desktop\Research_UCLA\CIC\Computational Work\Project cluster version 2\project_catalyst_repurposing\structures_ligand_id\pd_me2_structures\ligand_xyz\ligand-239-n-o-76-ligand_xyz.txt

C:\Users\George\AppData\Local\Temp\ipykernel_7832\386804788.py:583: DeprecationWarning:

to_plotly_figure is deprecated and will be removed in version 4.0.0. Use MolGraph.to_plotly() instead.

C:\Users\George\AppData\Local\Temp\ipykernel_7832\386804788.py:589: DeprecationWarning:

to_networkx_graph is deprecated and will be removed in version 4.0.0. Use MolGraph.to_networkx() instead.

Ending node: 0
Starting node: 11
(-4.085318, 0.612172, 1.112846)   11
(-4.430925, 0.812913, -0.088375)   12
(-3.606653, 0.625962, -1.1794)   2
(-2.223485, 0.174884, -1.109154)   1
(-1.509794, -0.136303, -0.097166)   0
ligand-240-n-o-77
Pd number index:  7
['N', 'C', 'C', 'C', 'C', 'H', 'O', 'Pd', 'C', 'H', 'H', 'H', 'C', 'H', 'H', 'C', 'C', 'H', 'H', 'H', 'H', 'C', 'C', 'C', 'H', 'H', 'N', 'N', 'C', 'C', 'C', 'C', 'C', 'C', 'H', 'H', 'C', 'C', 'C', 'C', 'C', 'C', 'H', 'H', 'C', 'H', 'H', 'H', 'C', 'H', 'H', 'H', 'C', 'H', 'H', 'H', 'C', 'H', 'H', 'H', 'C', 'H', 'H', 'H', 'C', 'H', 'H', 'H']
Ligand atom label:  1  Ligand atom B nbo:  -0.49675
Ligand atom label:  7  Ligand atom A nbo:  -0.70061
Atom_a:  1 Atom_b:  7
C:\Users\George\Desktop\Research_UCLA\CIC\Computational Work\Project cluster version 2\project_catalyst_repurposing\structures_ligand_id\pd_me2_structures\ligand_xyz\ligand-240-n-o-77-ligand_xyz.txt
Starting node: 0
Ending node: 6
(-0.107566, -0.095502, 0.769187)   0
(1.109269, 0.144031, 1.470885)   1
(1.861767, 1.320183, 1.125928)   3
(1.45171, 2.125644, 0.217294)   6
ligand-241-n-o-78
Pd number index:  7
['N', 'C', 'C', 'C', 'C', 'H', 'O', 'Pd', 'C', 'H', 'H', 'H', 'C', 'H', 'H', 'C', 'C', 'H', 'H', 'H', 'H', 'C', 'C', 'C', 'H', 'H', 'N', 'N', 'C', 'C', 'C', 'C', 'C', 'C', 'H', 'H', 'C', 'C', 'C', 'C', 'C', 'C', 'H', 'H', 'C', 'H', 'C', 'H', 'C', 'H', 'C', 'H', 'H', 'H', 'C', 'H', 'H', 'H', 'C', 'H', 'H', 'H', 'C', 'H', 'H', 'H', 'C', 'H', 'H', 'H', 'C', 'H', 'H', 'H', 'C', 'H', 'C', 'H', 'H', 'H', 'C', 'H', 'H', 'H', 'H', 'H']
Ligand atom label:  1  Ligand atom B nbo:  -0.65611
Ligand atom label:  7  Ligand atom A nbo:  -0.72162
Atom_a:  1 Atom_b:  7

C:\Users\George\AppData\Local\Temp\ipykernel_7832\386804788.py:583: DeprecationWarning:

to_plotly_figure is deprecated and will be removed in version 4.0.0. Use MolGraph.to_plotly() instead.

C:\Users\George\AppData\Local\Temp\ipykernel_7832\386804788.py:589: DeprecationWarning:

to_networkx_graph is deprecated and will be removed in version 4.0.0. Use MolGraph.to_networkx() instead.

C:\Users\George\Desktop\Research_UCLA\CIC\Computational Work\Project cluster version 2\project_catalyst_repurposing\structures_ligand_id\pd_me2_structures\ligand_xyz\ligand-241-n-o-78-ligand_xyz.txt
Starting node: 0
Ending node: 6
(0.085651, 0.589238, 0.469797)   0
(1.206022, 1.313443, 0.948214)   1
(1.078457, 2.746792, 1.056072)   3
(0.013651, 3.37171, 0.730783)   6
ligand-242-n-o-79

C:\Users\George\AppData\Local\Temp\ipykernel_7832\386804788.py:583: DeprecationWarning:

to_plotly_figure is deprecated and will be removed in version 4.0.0. Use MolGraph.to_plotly() instead.

C:\Users\George\AppData\Local\Temp\ipykernel_7832\386804788.py:589: DeprecationWarning:

to_networkx_graph is deprecated and will be removed in version 4.0.0. Use MolGraph.to_networkx() instead.

Pd number index:  7
['N', 'C', 'C', 'C', 'C', 'H', 'O', 'Pd', 'C', 'H', 'H', 'H', 'C', 'H', 'H', 'C', 'C', 'H', 'H', 'H', 'H', 'C', 'C', 'C', 'H', 'H', 'N', 'N', 'C', 'C', 'C', 'C', 'C', 'C', 'H', 'H', 'C', 'C', 'C', 'C', 'C', 'C', 'H', 'H', 'C', 'H', 'C', 'H', 'C', 'H', 'C', 'H', 'C', 'C', 'C', 'C', 'H', 'C', 'H', 'C', 'H', 'H', 'H', 'C', 'C', 'C', 'C', 'H', 'C', 'H', 'C', 'H', 'H', 'H', 'C', 'C', 'C', 'C', 'H', 'C', 'H', 'C', 'H', 'H', 'H', 'C', 'C', 'C', 'C', 'H', 'C', 'H', 'C', 'H', 'H', 'H', 'C', 'C', 'C', 'C', 'H', 'C', 'H', 'C', 'H', 'H', 'H', 'C', 'C', 'C', 'C', 'H', 'C', 'H', 'C', 'H', 'H', 'H', 'C', 'C', 'C', 'C', 'H', 'C', 'H', 'C', 'H', 'H', 'H', 'C', 'C', 'C', 'C', 'H', 'C', 'H', 'C', 'H', 'H', 'H', 'C', 'H', 'H', 'H', 'C', 'H', 'H', 'H']
Ligand atom label:  1  Ligand atom B nbo:  -0.65777
Ligand atom label:  7  Ligand atom A nbo:  -0.73018
Atom_a:  1 Atom_b:  7
C:\Users\George\Desktop\Research_UCLA\CIC\Computational Work\Project cluster version 2\project_catalyst_repurposing\structures_ligand_id\pd_me2_structures\ligand_xyz\ligand-242-n-o-79-ligand_xyz.txt
Starting node: 0
Ending node: 6
(-0.171922, 0.70737, -1.418937)   0
(-1.424079, 0.969247, -2.032863)   1
(-1.532583, 2.117787, -2.890467)   3
(-0.555745, 2.92976, -3.081956)   6
ligand-243-p-o-63

C:\Users\George\AppData\Local\Temp\ipykernel_7832\386804788.py:583: DeprecationWarning:

to_plotly_figure is deprecated and will be removed in version 4.0.0. Use MolGraph.to_plotly() instead.

C:\Users\George\AppData\Local\Temp\ipykernel_7832\386804788.py:589: DeprecationWarning:

to_networkx_graph is deprecated and will be removed in version 4.0.0. Use MolGraph.to_networkx() instead.

Pd number index:  1
['P', 'Pd', 'C', 'H', 'H', 'H', 'C', 'H', 'H', 'H', 'P', 'O', 'C', 'C', 'C', 'C', 'H', 'C', 'C', 'H', 'H', 'H', 'C', 'C', 'C', 'C', 'H', 'C', 'C', 'H', 'H', 'H', 'C', 'H', 'C', 'H', 'H', 'H', 'C', 'C', 'C', 'C', 'C', 'H', 'C', 'H', 'H', 'H', 'H', 'H', 'N', 'C', 'H', 'C', 'H', 'H', 'H', 'C', 'H', 'H', 'H', 'C', 'H', 'H', 'H', 'C', 'C', 'C', 'C', 'H', 'C', 'H', 'C', 'H', 'H', 'H']
Ligand atom label:  1  Ligand atom B nbo:  0.92532
Ligand atom label:  12  Ligand atom A nbo:  -0.91038
Atom_a:  1 Atom_b:  12
C:\Users\George\Desktop\Research_UCLA\CIC\Computational Work\Project cluster version 2\project_catalyst_repurposing\structures_ligand_id\pd_me2_structures\ligand_xyz\ligand-243-p-o-63-ligand_xyz.txt

C:\Users\George\AppData\Local\Temp\ipykernel_7832\386804788.py:583: DeprecationWarning:

to_plotly_figure is deprecated and will be removed in version 4.0.0. Use MolGraph.to_plotly() instead.

C:\Users\George\AppData\Local\Temp\ipykernel_7832\386804788.py:589: DeprecationWarning:

to_networkx_graph is deprecated and will be removed in version 4.0.0. Use MolGraph.to_networkx() instead.

Starting node: 0
Ending node: 2
(-1.727449, 0.011792, 0.036653)   0
(-0.698222, 0.578859, 1.484242)   30
(0.705883, 0.703212, 1.395719)   29
(1.70831, 0.133114, -0.03247)   1
(0.946755, -0.003326, -1.334553)   2
ligand-244-p-o-64
Pd number index:  1
['P', 'Pd', 'C', 'H', 'H', 'H', 'C', 'H', 'H', 'H', 'P', 'O', 'C', 'H', 'C', 'H', 'H', 'H', 'C', 'C', 'C', 'C', 'C', 'H', 'C', 'H', 'H', 'H', 'N', 'C', 'H', 'C', 'H', 'H', 'H', 'C', 'H', 'H', 'H', 'C', 'H', 'H', 'H', 'C', 'C', 'C', 'C', 'H', 'C', 'H', 'C', 'H', 'H', 'H', 'C', 'C', 'C', 'H', 'C', 'H', 'H', 'C', 'H', 'H', 'C', 'H', 'H', 'H', 'H', 'H', 'H', 'C', 'C', 'C', 'H', 'C', 'H', 'H', 'C', 'H', 'H', 'C', 'H', 'H', 'H', 'H', 'H', 'H']
Ligand atom label:  1  Ligand atom B nbo:  0.92593
Ligand atom label:  12  Ligand atom A nbo:  -0.91206
Atom_a:  1 Atom_b:  12
C:\Users\George\Desktop\Research_UCLA\CIC\Computational Work\Project cluster version 2\project_catalyst_repurposing\structures_ligand_id\pd_me2_structures\ligand_xyz\ligand-244-p-o-64-ligand_xyz.txt
Starting node: 0
Ending node: 2
(-1.585093, 0.252363, 0.367568)   0
(-0.293423, 0.659679, 1.666122)   10
(1.099031, 0.616092, 1.451607)   9
(1.857233, 0.209817, -0.169525)   1
(1.089861, 0.731962, -1.365455)   2
ligand-245-p-o-65

C:\Users\George\AppData\Local\Temp\ipykernel_7832\386804788.py:583: DeprecationWarning:

to_plotly_figure is deprecated and will be removed in version 4.0.0. Use MolGraph.to_plotly() instead.

C:\Users\George\AppData\Local\Temp\ipykernel_7832\386804788.py:589: DeprecationWarning:

to_networkx_graph is deprecated and will be removed in version 4.0.0. Use MolGraph.to_networkx() instead.

Pd number index:  1
['P', 'Pd', 'C', 'H', 'H', 'H', 'C', 'H', 'H', 'H', 'P', 'O', 'C', 'H', 'C', 'H', 'H', 'H', 'C', 'C', 'C', 'C', 'C', 'H', 'C', 'H', 'H', 'H', 'N', 'C', 'H', 'C', 'H', 'H', 'H', 'C', 'H', 'H', 'H', 'C', 'H', 'H', 'H', 'C', 'C', 'C', 'C', 'H', 'C', 'H', 'C', 'H', 'H', 'H', 'C', 'C', 'C', 'C', 'H', 'C', 'H', 'C', 'H', 'H', 'H', 'C', 'C', 'C', 'C', 'H', 'C', 'C', 'H', 'H', 'H', 'C', 'C', 'C', 'C', 'C', 'C', 'H', 'H', 'H', 'O', 'O', 'C', 'H', 'H', 'H', 'C', 'H', 'H', 'H']
Ligand atom label:  1  Ligand atom B nbo:  0.93627
Ligand atom label:  12  Ligand atom A nbo:  -0.89081
Atom_a:  1 Atom_b:  12
C:\Users\George\Desktop\Research_UCLA\CIC\Computational Work\Project cluster version 2\project_catalyst_repurposing\structures_ligand_id\pd_me2_structures\ligand_xyz\ligand-245-p-o-65-ligand_xyz.txt
Starting node: 0
Ending node: 2
(0.967712, 0.859944, -0.334861)   0
(-0.28441, 0.712516, -1.720177)   10
(-1.648112, 0.37556, -1.517025)   9
(-2.334169, -0.379547, 0.024308)   1
(-1.293797, -1.108509, 0.836104)   2
ligand-246-c-n-8

C:\Users\George\AppData\Local\Temp\ipykernel_7832\386804788.py:583: DeprecationWarning:

to_plotly_figure is deprecated and will be removed in version 4.0.0. Use MolGraph.to_plotly() instead.

C:\Users\George\AppData\Local\Temp\ipykernel_7832\386804788.py:589: DeprecationWarning:

to_networkx_graph is deprecated and will be removed in version 4.0.0. Use MolGraph.to_networkx() instead.

Pd number index:  0
['Pd', 'C', 'C', 'C', 'H', 'N', 'N', 'C', 'C', 'C', 'C', 'C', 'C', 'H', 'H', 'C', 'H', 'C', 'H', 'H', 'C', 'C', 'H', 'H', 'C', 'C', 'C', 'H', 'H', 'H', 'C', 'H', 'H', 'H', 'C', 'H', 'H', 'H', 'C', 'H', 'H', 'H', 'C', 'H', 'H', 'H', 'C', 'H', 'H', 'H', 'H', 'N', 'S', 'O', 'O', 'C', 'C', 'C', 'C', 'C', 'C', 'H', 'H', 'C', 'H', 'H', 'H', 'C', 'H', 'H', 'H', 'C', 'H', 'H', 'H']
Ligand atom label:  2  Ligand atom A nbo:  0.28129
Ligand atom label:  52  Ligand atom B nbo:  -0.9542
Atom_a:  2 Atom_b:  52
C:\Users\George\Desktop\Research_UCLA\CIC\Computational Work\Project cluster version 2\project_catalyst_repurposing\structures_ligand_id\pd_me2_structures\ligand_xyz\ligand-246-c-n-8-ligand_xyz.txt
Starting node: 0
Ending node: 42
(1.209753, -0.045433, -0.481246)   0
(0.225043, -0.305174, -1.405296)   5
(-1.044745, 0.296884, -1.364871)   24
(-1.22574, 1.084593, -0.284024)   42
ligand-247-c-n-9

C:\Users\George\AppData\Local\Temp\ipykernel_7832\386804788.py:583: DeprecationWarning:

to_plotly_figure is deprecated and will be removed in version 4.0.0. Use MolGraph.to_plotly() instead.

C:\Users\George\AppData\Local\Temp\ipykernel_7832\386804788.py:589: DeprecationWarning:

to_networkx_graph is deprecated and will be removed in version 4.0.0. Use MolGraph.to_networkx() instead.

Pd number index:  0
['Pd', 'C', 'C', 'C', 'H', 'N', 'N', 'C', 'C', 'C', 'C', 'C', 'C', 'H', 'H', 'C', 'H', 'C', 'H', 'H', 'C', 'C', 'H', 'H', 'C', 'C', 'C', 'H', 'H', 'H', 'C', 'H', 'H', 'H', 'C', 'H', 'H', 'H', 'C', 'H', 'H', 'H', 'C', 'H', 'H', 'H', 'C', 'H', 'H', 'H', 'H', 'N', 'S', 'O', 'O', 'C', 'H', 'H', 'H']
Ligand atom label:  2  Ligand atom A nbo:  0.2894
Ligand atom label:  52  Ligand atom B nbo:  -0.95291
Atom_a:  2 Atom_b:  52
C:\Users\George\Desktop\Research_UCLA\CIC\Computational Work\Project cluster version 2\project_catalyst_repurposing\structures_ligand_id\pd_me2_structures\ligand_xyz\ligand-247-c-n-9-ligand_xyz.txt
Starting node: 0
Ending node: 42
(-0.240054, 0.484003, -0.018551)   0
(0.621925, 1.554873, -0.055885)   5
(2.021277, 1.410994, -0.127874)   24
(2.409225, 0.122022, -0.139676)   42
ligand-248-c-o-4

C:\Users\George\AppData\Local\Temp\ipykernel_7832\386804788.py:583: DeprecationWarning:

to_plotly_figure is deprecated and will be removed in version 4.0.0. Use MolGraph.to_plotly() instead.

C:\Users\George\AppData\Local\Temp\ipykernel_7832\386804788.py:589: DeprecationWarning:

to_networkx_graph is deprecated and will be removed in version 4.0.0. Use MolGraph.to_networkx() instead.

Pd number index:  0
['Pd', 'C', 'C', 'C', 'H', 'N', 'N', 'C', 'C', 'C', 'C', 'C', 'C', 'H', 'H', 'C', 'H', 'C', 'H', 'H', 'C', 'C', 'H', 'H', 'C', 'C', 'C', 'H', 'H', 'H', 'C', 'H', 'H', 'H', 'C', 'H', 'H', 'H', 'C', 'H', 'H', 'H', 'C', 'H', 'H', 'H', 'C', 'H', 'H', 'H', 'P', 'C', 'C', 'H', 'O', 'C', 'H', 'H', 'H', 'C', 'H', 'H', 'H', 'C', 'H', 'H', 'H', 'C', 'H', 'H', 'H', 'C', 'H', 'H', 'H', 'C', 'H', 'H', 'H']
Ligand atom label:  2  Ligand atom A nbo:  0.22355
Ligand atom label:  55  Ligand atom B nbo:  -0.96027
Atom_a:  2 Atom_b:  55
C:\Users\George\Desktop\Research_UCLA\CIC\Computational Work\Project cluster version 2\project_catalyst_repurposing\structures_ligand_id\pd_me2_structures\ligand_xyz\ligand-248-c-o-4-ligand_xyz.txt
Starting node: 0
Ending node: 45
(0.538463, -0.452896, 0.121745)   0
(-0.386622, -1.475241, 0.273762)   5
(-1.7647, -1.475549, 0.020452)   24
(-2.719384, 0.103388, -0.020643)   41
(-1.864543, 1.286407, 0.370594)   45
ligand-249-c-o-5

C:\Users\George\AppData\Local\Temp\ipykernel_7832\386804788.py:583: DeprecationWarning:

to_plotly_figure is deprecated and will be removed in version 4.0.0. Use MolGraph.to_plotly() instead.

C:\Users\George\AppData\Local\Temp\ipykernel_7832\386804788.py:589: DeprecationWarning:

to_networkx_graph is deprecated and will be removed in version 4.0.0. Use MolGraph.to_networkx() instead.

Pd number index:  0
['Pd', 'C', 'C', 'C', 'H', 'N', 'N', 'C', 'C', 'C', 'C', 'C', 'C', 'H', 'H', 'C', 'C', 'H', 'H', 'C', 'C', 'C', 'H', 'H', 'H', 'C', 'H', 'H', 'H', 'P', 'C', 'C', 'H', 'O', 'C', 'H', 'H', 'C', 'H', 'H', 'C', 'C', 'C', 'C', 'H', 'C', 'H', 'C', 'H', 'H', 'H', 'C', 'C', 'C', 'C', 'H', 'C', 'H', 'C', 'H', 'H', 'H', 'C', 'H', 'H', 'H', 'C', 'H', 'H', 'H', 'C', 'H', 'H', 'H', 'C', 'H', 'H', 'H', 'C', 'H', 'H', 'H', 'C', 'H', 'H', 'H', 'C', 'H', 'H', 'H']
Ligand atom label:  2  Ligand atom A nbo:  0.24435
Ligand atom label:  34  Ligand atom B nbo:  -1.0045
Atom_a:  2 Atom_b:  34
C:\Users\George\Desktop\Research_UCLA\CIC\Computational Work\Project cluster version 2\project_catalyst_repurposing\structures_ligand_id\pd_me2_structures\ligand_xyz\ligand-249-c-o-5-ligand_xyz.txt
Starting node: 0
Ending node: 24
(-0.198761, -0.543759, 0.567399)   0
(-1.071438, -1.316994, 1.306201)   5
(-2.378104, -1.705663, 0.988185)   19
(-3.387108, -0.714499, -0.207475)   20
(-2.633408, 0.462863, -0.784718)   24
ligand-250-c-o-6

C:\Users\George\AppData\Local\Temp\ipykernel_7832\386804788.py:583: DeprecationWarning:

to_plotly_figure is deprecated and will be removed in version 4.0.0. Use MolGraph.to_plotly() instead.

C:\Users\George\AppData\Local\Temp\ipykernel_7832\386804788.py:589: DeprecationWarning:

to_networkx_graph is deprecated and will be removed in version 4.0.0. Use MolGraph.to_networkx() instead.

Pd number index:  0
['Pd', 'C', 'C', 'C', 'H', 'N', 'N', 'C', 'C', 'C', 'C', 'C', 'C', 'H', 'H', 'C', 'H', 'C', 'H', 'H', 'C', 'H', 'H', 'H', 'C', 'H', 'H', 'H', 'C', 'H', 'H', 'H', 'C', 'H', 'H', 'H', 'C', 'H', 'H', 'H', 'C', 'H', 'H', 'H', 'P', 'C', 'C', 'O', 'H', 'C', 'H', 'H', 'H', 'C', 'H', 'H', 'H', 'C', 'H', 'H', 'H', 'C', 'H', 'H', 'H', 'C', 'H', 'H', 'H', 'C', 'H', 'H', 'H']
Ligand atom label:  2  Ligand atom A nbo:  0.25555
Ligand atom label:  48  Ligand atom B nbo:  -1.01161
Atom_a:  2 Atom_b:  48
C:\Users\George\Desktop\Research_UCLA\CIC\Computational Work\Project cluster version 2\project_catalyst_repurposing\structures_ligand_id\pd_me2_structures\ligand_xyz\ligand-250-c-o-6-ligand_xyz.txt

C:\Users\George\AppData\Local\Temp\ipykernel_7832\386804788.py:583: DeprecationWarning:

to_plotly_figure is deprecated and will be removed in version 4.0.0. Use MolGraph.to_plotly() instead.

C:\Users\George\AppData\Local\Temp\ipykernel_7832\386804788.py:589: DeprecationWarning:

to_networkx_graph is deprecated and will be removed in version 4.0.0. Use MolGraph.to_networkx() instead.

Starting node: 0
Ending node: 38
(-0.217445, -0.080217, 0.161304)   0
(0.930078, -0.644512, 0.687365)   5
(2.483105, -0.054274, 0.114144)   35
(2.236344, 1.126562, -0.781995)   38
ligand-251-p-o-66
Pd number index:  15
['P', 'C', 'C', 'S', 'O', 'O', 'O', 'C', 'C', 'C', 'C', 'H', 'H', 'H', 'H', 'Pd', 'C', 'H', 'C', 'H', 'C', 'H', 'H', 'H', 'C', 'H', 'H', 'H', 'C', 'H', 'H', 'H', 'C', 'H', 'H', 'H', 'C', 'H', 'H', 'H', 'C', 'H', 'H', 'H']
Ligand atom label:  1  Ligand atom B nbo:  0.92219
Ligand atom label:  5  Ligand atom A nbo:  -0.93883
Atom_a:  1 Atom_b:  5
C:\Users\George\Desktop\Research_UCLA\CIC\Computational Work\Project cluster version 2\project_catalyst_repurposing\structures_ligand_id\pd_me2_structures\ligand_xyz\ligand-251-p-o-66-ligand_xyz.txt
Starting node: 0
Ending node: 4
(0.165376, 0.999497, 0.123539)   0
(-1.610823, 0.665322, -0.341859)   1
(-2.171356, -0.610605, -0.127065)   2
(-1.225702, -1.997087, 0.572185)   3
(-0.146821, -2.226988, -0.443732)   4
ligand-252-p-o-67
Pd number index:  15
['P', 'C', 'C', 'S', 'O', 'O', 'O', 'C', 'C', 'C', 'C', 'H', 'H', 'H', 'H', 'Pd', 'C', 'C', 'C', 'H', 'H', 'H', 'C', 'H', 'H', 'H', 'C', 'H', 'H', 'H', 'C', 'H', 'H', 'H', 'C', 'H', 'H', 'H', 'C', 'H', 'H', 'H', 'C', 'H', 'H', 'H', 'C', 'H', 'H', 'H']
Ligand atom label:  1  Ligand atom B nbo:  0.89055
Ligand atom label:  5  Ligand atom A nbo:  -0.94634
Atom_a:  1 Atom_b:  5

C:\Users\George\AppData\Local\Temp\ipykernel_7832\386804788.py:583: DeprecationWarning:

to_plotly_figure is deprecated and will be removed in version 4.0.0. Use MolGraph.to_plotly() instead.

C:\Users\George\AppData\Local\Temp\ipykernel_7832\386804788.py:589: DeprecationWarning:

to_networkx_graph is deprecated and will be removed in version 4.0.0. Use MolGraph.to_networkx() instead.

C:\Users\George\Desktop\Research_UCLA\CIC\Computational Work\Project cluster version 2\project_catalyst_repurposing\structures_ligand_id\pd_me2_structures\ligand_xyz\ligand-252-p-o-67-ligand_xyz.txt
Starting node: 0
Ending node: 4
(-0.057525, 0.925915, 0.059587)   0
(-1.762289, 0.183098, -0.180441)   1
(-1.989498, -1.207053, -0.140521)   2
(-0.698992, -2.437963, 0.222994)   3
(0.373192, -2.136909, -0.781989)   4
ligand-253-p-o-68
Pd number index:  15
['P', 'C', 'C', 'S', 'O', 'O', 'O', 'C', 'C', 'C', 'C', 'H', 'H', 'H', 'H', 'Pd', 'C', 'C', 'C', 'H', 'H', 'C', 'H', 'H', 'C', 'H', 'H', 'H', 'C', 'H', 'H', 'H', 'C', 'H', 'H', 'C', 'H', 'H', 'C', 'H', 'H', 'H', 'C', 'H', 'H', 'H', 'H', 'H', 'C', 'H', 'H', 'H', 'C', 'H', 'H', 'H']

C:\Users\George\AppData\Local\Temp\ipykernel_7832\386804788.py:583: DeprecationWarning:

to_plotly_figure is deprecated and will be removed in version 4.0.0. Use MolGraph.to_plotly() instead.

C:\Users\George\AppData\Local\Temp\ipykernel_7832\386804788.py:589: DeprecationWarning:

to_networkx_graph is deprecated and will be removed in version 4.0.0. Use MolGraph.to_networkx() instead.

Ligand atom label:  1  Ligand atom B nbo:  0.9332
Ligand atom label:  5  Ligand atom A nbo:  -0.93668
Atom_a:  1 Atom_b:  5
C:\Users\George\Desktop\Research_UCLA\CIC\Computational Work\Project cluster version 2\project_catalyst_repurposing\structures_ligand_id\pd_me2_structures\ligand_xyz\ligand-253-p-o-68-ligand_xyz.txt

C:\Users\George\AppData\Local\Temp\ipykernel_7832\386804788.py:583: DeprecationWarning:

to_plotly_figure is deprecated and will be removed in version 4.0.0. Use MolGraph.to_plotly() instead.

C:\Users\George\AppData\Local\Temp\ipykernel_7832\386804788.py:589: DeprecationWarning:

to_networkx_graph is deprecated and will be removed in version 4.0.0. Use MolGraph.to_networkx() instead.

Starting node: 0
Ending node: 4
(-0.575756, -0.226601, 0.132059)   0
(0.54062, -1.387853, -0.794562)   1
(1.939826, -1.238418, -0.721197)   2
(2.738206, 0.002628, 0.337745)   3
(2.341688, 1.317574, -0.261766)   4
ligand-254-p-o-69
Pd number index:  15
['P', 'C', 'C', 'S', 'O', 'O', 'O', 'C', 'C', 'C', 'C', 'H', 'H', 'H', 'H', 'Pd', 'C', 'C', 'C', 'H', 'H', 'C', 'H', 'H', 'C', 'H', 'H', 'H', 'C', 'H', 'H', 'H', 'C', 'H', 'H', 'C', 'H', 'H', 'C', 'H', 'C', 'H', 'H', 'H', 'C', 'H', 'C', 'H', 'C', 'H', 'H', 'H', 'C', 'H', 'H', 'H', 'C', 'H', 'H', 'H', 'C', 'H', 'H', 'H', 'C', 'H', 'H', 'H', 'C', 'H', 'H', 'H', 'C', 'H', 'H', 'H', 'C', 'H', 'H', 'H']
Ligand atom label:  1  Ligand atom B nbo:  0.94179
Ligand atom label:  5  Ligand atom A nbo:  -0.93651
Atom_a:  1 Atom_b:  5
C:\Users\George\Desktop\Research_UCLA\CIC\Computational Work\Project cluster version 2\project_catalyst_repurposing\structures_ligand_id\pd_me2_structures\ligand_xyz\ligand-254-p-o-69-ligand_xyz.txt
Starting node: 0
Ending node: 4
(-0.054991, -0.175769, 0.178531)   0
(0.844703, -0.20164, 1.812865)   1
(2.2309, -0.442652, 1.843832)   2
(3.225037, -0.550042, 0.330563)   3
(2.746185, -1.796717, -0.355093)   4
ligand-255-p-o-70

C:\Users\George\AppData\Local\Temp\ipykernel_7832\386804788.py:583: DeprecationWarning:

to_plotly_figure is deprecated and will be removed in version 4.0.0. Use MolGraph.to_plotly() instead.

C:\Users\George\AppData\Local\Temp\ipykernel_7832\386804788.py:589: DeprecationWarning:

to_networkx_graph is deprecated and will be removed in version 4.0.0. Use MolGraph.to_networkx() instead.

Pd number index:  15
['P', 'C', 'C', 'S', 'O', 'O', 'O', 'C', 'C', 'C', 'C', 'H', 'H', 'H', 'H', 'Pd', 'C', 'C', 'C', 'H', 'C', 'H', 'C', 'H', 'H', 'C', 'H', 'H', 'H', 'H', 'H', 'C', 'C', 'C', 'H', 'C', 'H', 'C', 'H', 'H', 'C', 'H', 'H', 'H', 'H', 'C', 'H', 'H', 'H', 'C', 'H', 'H', 'H', 'C', 'H', 'C', 'H', 'H', 'H', 'C', 'H', 'H', 'H', 'C', 'H', 'C', 'H', 'H', 'H', 'C', 'H', 'H', 'H', 'C', 'H', 'H', 'H', 'H', 'C', 'H', 'H', 'H']
Ligand atom label:  1  Ligand atom B nbo:  0.89113
Ligand atom label:  5  Ligand atom A nbo:  -0.94036
Atom_a:  1 Atom_b:  5
C:\Users\George\Desktop\Research_UCLA\CIC\Computational Work\Project cluster version 2\project_catalyst_repurposing\structures_ligand_id\pd_me2_structures\ligand_xyz\ligand-255-p-o-70-ligand_xyz.txt
Starting node: 0
Ending node: 4
(-0.025649, -0.112314, 0.214544)   0
(1.174061, -0.587302, 1.587053)   1
(2.538283, -0.830887, 1.333118)   2
(3.299745, -0.688526, -0.309253)   3
(2.556837, -1.680862, -1.149334)   4
ligand-256-p-o-71

C:\Users\George\AppData\Local\Temp\ipykernel_7832\386804788.py:583: DeprecationWarning:

to_plotly_figure is deprecated and will be removed in version 4.0.0. Use MolGraph.to_plotly() instead.

C:\Users\George\AppData\Local\Temp\ipykernel_7832\386804788.py:589: DeprecationWarning:

to_networkx_graph is deprecated and will be removed in version 4.0.0. Use MolGraph.to_networkx() instead.

Pd number index:  35
['P', 'C', 'C', 'S', 'O', 'O', 'O', 'C', 'C', 'C', 'C', 'C', 'C', 'H', 'H', 'H', 'H', 'C', 'C', 'C', 'C', 'C', 'H', 'H', 'H', 'H', 'C', 'C', 'C', 'C', 'C', 'H', 'H', 'H', 'H', 'Pd', 'C', 'H', 'H', 'H', 'C', 'H', 'H', 'H', 'C', 'C', 'C', 'C', 'C', 'C', 'H', 'H', 'H', 'C', 'C', 'C', 'C', 'C', 'C', 'H', 'H', 'H', 'O', 'O', 'C', 'H', 'H', 'H', 'C', 'H', 'H', 'H', 'O', 'O', 'C', 'H', 'H', 'H', 'C', 'H', 'H', 'H']
Ligand atom label:  1  Ligand atom B nbo:  0.92427
Ligand atom label:  5  Ligand atom A nbo:  -0.96377
Atom_a:  1 Atom_b:  5
C:\Users\George\Desktop\Research_UCLA\CIC\Computational Work\Project cluster version 2\project_catalyst_repurposing\structures_ligand_id\pd_me2_structures\ligand_xyz\ligand-256-p-o-71-ligand_xyz.txt
Starting node: 0
Ending node: 4
(-0.55856, -0.320338, 0.505588)   0
(-2.173369, 0.165825, 1.32726)   1
(-3.383227, 0.145966, 0.608018)   2
(-3.458388, -0.207204, -1.166543)   3
(-2.682986, 0.939753, -1.756183)   4
ligand-257-c-o-7

C:\Users\George\AppData\Local\Temp\ipykernel_7832\386804788.py:583: DeprecationWarning:

to_plotly_figure is deprecated and will be removed in version 4.0.0. Use MolGraph.to_plotly() instead.

C:\Users\George\AppData\Local\Temp\ipykernel_7832\386804788.py:589: DeprecationWarning:

to_networkx_graph is deprecated and will be removed in version 4.0.0. Use MolGraph.to_networkx() instead.

Pd number index:  0
['Pd', 'C', 'C', 'N', 'C', 'C', 'C', 'C', 'C', 'C', 'H', 'H', 'C', 'H', 'C', 'H', 'H', 'C', 'C', 'H', 'C', 'C', 'C', 'H', 'C', 'C', 'C', 'H', 'H', 'C', 'H', 'H', 'H', 'C', 'H', 'H', 'H', 'C', 'H', 'H', 'H', 'C', 'H', 'H', 'H', 'C', 'H', 'H', 'H', 'C', 'H', 'H', 'H', 'O', 'C', 'N', 'C', 'C', 'C', 'C', 'H', 'C', 'H', 'C', 'H', 'H', 'H', 'C', 'C', 'C', 'C', 'H', 'C', 'H', 'C', 'H', 'H', 'H']
Ligand atom label:  2  Ligand atom A nbo:  -0.045
Ligand atom label:  54  Ligand atom B nbo:  -0.65949
Atom_a:  2 Atom_b:  54
C:\Users\George\Desktop\Research_UCLA\CIC\Computational Work\Project cluster version 2\project_catalyst_repurposing\structures_ligand_id\pd_me2_structures\ligand_xyz\ligand-257-c-o-7-ligand_xyz.txt

C:\Users\George\AppData\Local\Temp\ipykernel_7832\386804788.py:583: DeprecationWarning:

to_plotly_figure is deprecated and will be removed in version 4.0.0. Use MolGraph.to_plotly() instead.

C:\Users\George\AppData\Local\Temp\ipykernel_7832\386804788.py:589: DeprecationWarning:

to_networkx_graph is deprecated and will be removed in version 4.0.0. Use MolGraph.to_networkx() instead.

Starting node: 0
Ending node: 44
(-1.116239, 0.308156, 0.025487)   0
(-0.292684, 1.453647, -0.041463)   45
(-0.611785, 2.846824, -0.127526)   21
(-1.989725, 3.311148, -0.128737)   23
(-2.997935, 2.566312, -0.01194)   44
ligand-258-c-o-8
Pd number index:  0
['Pd', 'C', 'C', 'N', 'C', 'C', 'C', 'C', 'C', 'C', 'H', 'H', 'C', 'H', 'C', 'H', 'H', 'C', 'C', 'H', 'C', 'C', 'C', 'H', 'C', 'C', 'C', 'H', 'H', 'C', 'H', 'H', 'C', 'H', 'H', 'C', 'H', 'H', 'C', 'H', 'H', 'C', 'H', 'H', 'H', 'C', 'H', 'H', 'H', 'O', 'C', 'N', 'C', 'C', 'C', 'C', 'H', 'C', 'H', 'C', 'H', 'H', 'H', 'C', 'C', 'C', 'C', 'H', 'C', 'H', 'C', 'H', 'H', 'H', 'C', 'H', 'H', 'H', 'C', 'H', 'H', 'H', 'C', 'H', 'H', 'H', 'C', 'H', 'H', 'H']
Ligand atom label:  2  Ligand atom A nbo:  -0.0401
Ligand atom label:  50  Ligand atom B nbo:  -0.65997
Atom_a:  2 Atom_b:  50
C:\Users\George\Desktop\Research_UCLA\CIC\Computational Work\Project cluster version 2\project_catalyst_repurposing\structures_ligand_id\pd_me2_structures\ligand_xyz\ligand-258-c-o-8-ligand_xyz.txt
Starting node: 0
Ending node: 40
(-1.027081, 0.42906, 0.05425)   0
(-0.174894, 1.549591, -0.060266)   41
(-0.456587, 2.950535, -0.160559)   21
(-1.819061, 3.457768, -0.140451)   23
(-2.847386, 2.747191, 0.011775)   40
ligand-259-c-o-9

C:\Users\George\AppData\Local\Temp\ipykernel_7832\386804788.py:583: DeprecationWarning:

to_plotly_figure is deprecated and will be removed in version 4.0.0. Use MolGraph.to_plotly() instead.

C:\Users\George\AppData\Local\Temp\ipykernel_7832\386804788.py:589: DeprecationWarning:

to_networkx_graph is deprecated and will be removed in version 4.0.0. Use MolGraph.to_networkx() instead.

Pd number index:  0
['Pd', 'C', 'C', 'C', 'H', 'N', 'N', 'C', 'C', 'C', 'C', 'C', 'C', 'H', 'H', 'C', 'H', 'C', 'H', 'C', 'C', 'H', 'H', 'C', 'C', 'C', 'H', 'C', 'C', 'C', 'H', 'H', 'C', 'H', 'H', 'H', 'C', 'H', 'H', 'H', 'O', 'H', 'H', 'H', 'H', 'C', 'H', 'H', 'H']
Ligand atom label:  2  Ligand atom A nbo:  0.26294
Ligand atom label:  41  Ligand atom B nbo:  -0.67415
Atom_a:  2 Atom_b:  41
C:\Users\George\Desktop\Research_UCLA\CIC\Computational Work\Project cluster version 2\project_catalyst_repurposing\structures_ligand_id\pd_me2_structures\ligand_xyz\ligand-259-c-o-9-ligand_xyz.txt

C:\Users\George\AppData\Local\Temp\ipykernel_7832\386804788.py:583: DeprecationWarning:

to_plotly_figure is deprecated and will be removed in version 4.0.0. Use MolGraph.to_plotly() instead.

C:\Users\George\AppData\Local\Temp\ipykernel_7832\386804788.py:589: DeprecationWarning:

to_networkx_graph is deprecated and will be removed in version 4.0.0. Use MolGraph.to_networkx() instead.

Starting node: 0
Ending node: 31
(-0.283372, -0.290694, -0.043138)   0
(-1.44303, -1.032561, 0.019807)   5
(-2.786765, -0.566537, 0.045229)   24
(-3.098119, 0.838288, 0.185185)   26
(-2.260635, 1.775984, 0.319384)   31
ligand-260-c-o-10
Pd number index:  0
['Pd', 'C', 'C', 'C', 'H', 'N', 'N', 'C', 'C', 'C', 'C', 'C', 'C', 'H', 'H', 'C', 'H', 'C', 'H', 'H', 'C', 'C', 'H', 'H', 'C', 'C', 'C', 'H', 'C', 'C', 'C', 'H', 'C', 'H', 'H', 'H', 'C', 'H', 'H', 'H', 'C', 'H', 'H', 'H', 'C', 'H', 'H', 'H', 'C', 'H', 'H', 'H', 'C', 'H', 'H', 'H', 'O', 'C', 'C', 'C', 'C', 'C', 'C', 'H', 'H', 'C', 'H', 'H', 'H', 'C', 'H', 'H', 'H', 'C', 'H', 'H', 'H']
Ligand atom label:  2  Ligand atom A nbo:  0.23732
Ligand atom label:  57  Ligand atom B nbo:  -0.67745
Atom_a:  2 Atom_b:  57
C:\Users\George\Desktop\Research_UCLA\CIC\Computational Work\Project cluster version 2\project_catalyst_repurposing\structures_ligand_id\pd_me2_structures\ligand_xyz\ligand-260-c-o-10-ligand_xyz.txt

C:\Users\George\AppData\Local\Temp\ipykernel_7832\386804788.py:583: DeprecationWarning:

to_plotly_figure is deprecated and will be removed in version 4.0.0. Use MolGraph.to_plotly() instead.

C:\Users\George\AppData\Local\Temp\ipykernel_7832\386804788.py:589: DeprecationWarning:

to_networkx_graph is deprecated and will be removed in version 4.0.0. Use MolGraph.to_networkx() instead.

Starting node: 0
Ending node: 47
(1.255108, 0.507703, 0.028397)   0
(0.607766, 1.729344, 0.040811)   5
(-0.787812, 2.002148, -0.043598)   25
(-1.766912, 0.95357, 0.087445)   27
(-1.50709, -0.24907, 0.378033)   47
ligand-261-p-o-72
Pd number index:  0
['Pd', 'P', 'C', 'C', 'C', 'C', 'H', 'C', 'C', 'H', 'H', 'H', 'C', 'C', 'C', 'C', 'H', 'C', 'C', 'H', 'H', 'H', 'P', 'O', 'C', 'H', 'H', 'O', 'O', 'C', 'H', 'H', 'H', 'C', 'H', 'H', 'H', 'C', 'C', 'C', 'H', 'H', 'H', 'C', 'H', 'H', 'H', 'C', 'H', 'H', 'H', 'C', 'H', 'H', 'H', 'C', 'H', 'H', 'H', 'C', 'H', 'H', 'H', 'C', 'H', 'H', 'H', 'C', 'H', 'H', 'H']
Ligand atom label:  2  Ligand atom B nbo:  0.94595
Ligand atom label:  24  Ligand atom A nbo:  -1.04371
Atom_a:  2 Atom_b:  24
C:\Users\George\Desktop\Research_UCLA\CIC\Computational Work\Project cluster version 2\project_catalyst_repurposing\structures_ligand_id\pd_me2_structures\ligand_xyz\ligand-261-p-o-72-ligand_xyz.txt
Starting node: 0
Ending node: 22
(-0.83545, 0.071627, -0.310702)   0
(0.651654, -0.263931, -1.428552)   23
(2.172058, -0.485475, -0.416062)   21
(2.13946, 0.357854, 0.849751)   22
ligand-262-p-o-73

C:\Users\George\AppData\Local\Temp\ipykernel_7832\386804788.py:583: DeprecationWarning:

to_plotly_figure is deprecated and will be removed in version 4.0.0. Use MolGraph.to_plotly() instead.

C:\Users\George\AppData\Local\Temp\ipykernel_7832\386804788.py:589: DeprecationWarning:

to_networkx_graph is deprecated and will be removed in version 4.0.0. Use MolGraph.to_networkx() instead.

Pd number index:  0
['Pd', 'P', 'C', 'C', 'C', 'C', 'H', 'C', 'C', 'H', 'H', 'H', 'C', 'C', 'C', 'C', 'H', 'C', 'C', 'H', 'H', 'H', 'P', 'O', 'C', 'H', 'H', 'C', 'C', 'C', 'H', 'H', 'H', 'C', 'H', 'H', 'H', 'C', 'H', 'H', 'H', 'C', 'H', 'H', 'H', 'C', 'H', 'H', 'H', 'C', 'H', 'H', 'H', 'C', 'H', 'H', 'H', 'C', 'H', 'H', 'H', 'C', 'F', 'F', 'F', 'C', 'F', 'F', 'F']
Ligand atom label:  2  Ligand atom B nbo:  0.91742
Ligand atom label:  24  Ligand atom A nbo:  -1.04023
Atom_a:  2 Atom_b:  24
C:\Users\George\Desktop\Research_UCLA\CIC\Computational Work\Project cluster version 2\project_catalyst_repurposing\structures_ligand_id\pd_me2_structures\ligand_xyz\ligand-262-p-o-73-ligand_xyz.txt
Starting node: 0
Ending node: 22
(-0.696256, -0.055942, 0.036691)   0
(0.669747, 0.746387, -0.944645)   23
(2.341029, 0.231641, -0.347002)   21
(2.254246, -0.522459, 0.96974)   22
ligand-263-p-o-74

C:\Users\George\AppData\Local\Temp\ipykernel_7832\386804788.py:583: DeprecationWarning:

to_plotly_figure is deprecated and will be removed in version 4.0.0. Use MolGraph.to_plotly() instead.

C:\Users\George\AppData\Local\Temp\ipykernel_7832\386804788.py:589: DeprecationWarning:

to_networkx_graph is deprecated and will be removed in version 4.0.0. Use MolGraph.to_networkx() instead.

Pd number index:  0
['Pd', 'P', 'P', 'O', 'C', 'H', 'H', 'C', 'C', 'C', 'H', 'H', 'H', 'C', 'H', 'H', 'H', 'C', 'H', 'H', 'H', 'C', 'H', 'H', 'H', 'C', 'H', 'H', 'H', 'C', 'H', 'H', 'H', 'C', 'H', 'H', 'H', 'C', 'H', 'H', 'H', 'C', 'H', 'C', 'H', 'C', 'H', 'H', 'H', 'C', 'H', 'H', 'H', 'C', 'H', 'H', 'H', 'C', 'H', 'H', 'H']
Ligand atom label:  2  Ligand atom B nbo:  0.88959
Ligand atom label:  4  Ligand atom A nbo:  -1.04037
Atom_a:  2 Atom_b:  4
C:\Users\George\Desktop\Research_UCLA\CIC\Computational Work\Project cluster version 2\project_catalyst_repurposing\structures_ligand_id\pd_me2_structures\ligand_xyz\ligand-263-p-o-74-ligand_xyz.txt
Starting node: 0
Ending node: 2
(1.320281, -0.892229, 0.18925)   0
(-0.457671, -1.432992, 0.518252)   3
(-1.619808, -0.123426, -0.075238)   1
(-0.929949, 0.76284, -1.104416)   2
ligand-266-p-o-75

C:\Users\George\AppData\Local\Temp\ipykernel_7832\386804788.py:583: DeprecationWarning:

to_plotly_figure is deprecated and will be removed in version 4.0.0. Use MolGraph.to_plotly() instead.

C:\Users\George\AppData\Local\Temp\ipykernel_7832\386804788.py:589: DeprecationWarning:

to_networkx_graph is deprecated and will be removed in version 4.0.0. Use MolGraph.to_networkx() instead.

Pd number index:  0
['Pd', 'P', 'P', 'O', 'C', 'H', 'H', 'C', 'H', 'H', 'H', 'C', 'H', 'H', 'H', 'C', 'H', 'H', 'H', 'C', 'H', 'H', 'H', 'C', 'C', 'C', 'H', 'C', 'H', 'C', 'H', 'H', 'C', 'H', 'H', 'H', 'H', 'H', 'C', 'C', 'C', 'H', 'C', 'H', 'C', 'H', 'H', 'C', 'H', 'H', 'H', 'H', 'H', 'C', 'H', 'H', 'H', 'C', 'H', 'C', 'H', 'H', 'H', 'C', 'H', 'H', 'H', 'C', 'H', 'H', 'H', 'C', 'H', 'C', 'H', 'H', 'H', 'C', 'H', 'H', 'H']
Ligand atom label:  2  Ligand atom B nbo:  0.89769
Ligand atom label:  4  Ligand atom A nbo:  -1.02902
Atom_a:  2 Atom_b:  4
C:\Users\George\Desktop\Research_UCLA\CIC\Computational Work\Project cluster version 2\project_catalyst_repurposing\structures_ligand_id\pd_me2_structures\ligand_xyz\ligand-266-p-o-75-ligand_xyz.txt
Starting node: 0
Ending node: 2
(-0.158709, 0.127469, 0.163183)   0
(-0.225232, -0.679585, 1.87048)   3
(0.447195, -2.382917, 1.777458)   1
(1.505134, -2.5531, 0.705828)   2
ligand-267-p-o-76
Pd number index:  12
['P', 'C', 'C', 'O', 'C', 'C', 'C', 'C', 'H', 'H', 'H', 'H', 'Pd', 'P', 'C', 'H', 'H', 'H', 'C', 'H', 'H', 'H', 'C', 'H', 'C', 'H', 'C', 'C', 'C', 'H', 'H', 'H', 'C', 'H', 'H', 'H', 'C', 'H', 'H', 'H', 'C', 'H', 'H', 'H', 'C', 'H', 'H', 'H', 'C', 'H', 'H', 'H', 'C', 'H', 'H', 'H', 'C', 'H', 'H', 'H', 'C', 'H', 'H', 'H', 'C', 'H', 'H', 'H']
Ligand atom label:  1  Ligand atom B nbo:  0.90452
Ligand atom label:  4  Ligand atom A nbo:  -1.04262
Atom_a:  1 Atom_b:  4

C:\Users\George\AppData\Local\Temp\ipykernel_7832\386804788.py:583: DeprecationWarning:

to_plotly_figure is deprecated and will be removed in version 4.0.0. Use MolGraph.to_plotly() instead.

C:\Users\George\AppData\Local\Temp\ipykernel_7832\386804788.py:589: DeprecationWarning:

to_networkx_graph is deprecated and will be removed in version 4.0.0. Use MolGraph.to_networkx() instead.

C:\Users\George\Desktop\Research_UCLA\CIC\Computational Work\Project cluster version 2\project_catalyst_repurposing\structures_ligand_id\pd_me2_structures\ligand_xyz\ligand-267-p-o-76-ligand_xyz.txt
Starting node: 0
Ending node: 3
(-1.622846, 0.824747, 0.115598)   0
(-0.094746, 1.895723, -0.135483)   1
(1.21583, 1.405998, -0.345859)   2
(1.755134, -0.30542, 0.078138)   12
(0.698917, -1.074007, 0.853886)   3
ligand-268-p-o-77
Pd number index:  12
['P', 'C', 'C', 'O', 'C', 'C', 'C', 'C', 'H', 'H', 'H', 'H', 'Pd', 'P', 'C', 'H', 'H', 'H', 'C', 'H', 'H', 'H', 'C', 'C', 'C', 'H', 'H', 'H', 'C', 'H', 'H', 'H', 'C', 'H', 'H', 'H', 'C', 'H', 'H', 'H', 'C', 'H', 'H', 'H', 'C', 'H', 'H', 'H', 'C', 'C', 'C', 'C', 'H', 'C', 'H', 'C', 'H', 'H', 'H', 'C', 'C', 'C', 'C', 'H', 'C', 'H', 'C', 'H', 'H', 'H']

C:\Users\George\AppData\Local\Temp\ipykernel_7832\386804788.py:583: DeprecationWarning:

to_plotly_figure is deprecated and will be removed in version 4.0.0. Use MolGraph.to_plotly() instead.

C:\Users\George\AppData\Local\Temp\ipykernel_7832\386804788.py:589: DeprecationWarning:

to_networkx_graph is deprecated and will be removed in version 4.0.0. Use MolGraph.to_networkx() instead.

Ligand atom label:  1  Ligand atom B nbo:  0.97263
Ligand atom label:  4  Ligand atom A nbo:  -1.04465
Atom_a:  1 Atom_b:  4
C:\Users\George\Desktop\Research_UCLA\CIC\Computational Work\Project cluster version 2\project_catalyst_repurposing\structures_ligand_id\pd_me2_structures\ligand_xyz\ligand-268-p-o-77-ligand_xyz.txt

C:\Users\George\AppData\Local\Temp\ipykernel_7832\386804788.py:583: DeprecationWarning:

to_plotly_figure is deprecated and will be removed in version 4.0.0. Use MolGraph.to_plotly() instead.

C:\Users\George\AppData\Local\Temp\ipykernel_7832\386804788.py:589: DeprecationWarning:

to_networkx_graph is deprecated and will be removed in version 4.0.0. Use MolGraph.to_networkx() instead.

Starting node: 0
Ending node: 3
(-1.290919, 0.015861, -0.029152)   0
(-0.358038, 0.777225, 1.400552)   1
(1.056161, 0.790883, 1.475688)   2
(2.167313, 0.109107, 0.171491)   12
(1.40699, -0.440021, -1.024962)   3
ligand-269-p-o-78
Pd number index:  12
['P', 'C', 'C', 'O', 'C', 'C', 'C', 'C', 'H', 'H', 'H', 'H', 'Pd', 'P', 'C', 'H', 'H', 'H', 'C', 'H', 'H', 'H', 'C', 'C', 'C', 'H', 'H', 'H', 'C', 'H', 'H', 'H', 'C', 'H', 'H', 'H', 'C', 'H', 'H', 'H', 'C', 'H', 'H', 'H', 'C', 'H', 'H', 'H', 'C', 'C', 'C', 'C', 'H', 'C', 'C', 'H', 'H', 'H', 'C', 'C', 'C', 'C', 'H', 'C', 'C', 'H', 'H', 'H', 'O', 'O', 'C', 'H', 'H', 'H', 'C', 'H', 'H', 'H']
Ligand atom label:  1  Ligand atom B nbo:  0.97444
Ligand atom label:  4  Ligand atom A nbo:  -1.04509
Atom_a:  1 Atom_b:  4
C:\Users\George\Desktop\Research_UCLA\CIC\Computational Work\Project cluster version 2\project_catalyst_repurposing\structures_ligand_id\pd_me2_structures\ligand_xyz\ligand-269-p-o-78-ligand_xyz.txt
Starting node: 0
Ending node: 3
(-1.033562, 0.160798, 0.341155)   0
(0.094797, -0.359707, 1.72878)   1
(1.496559, -0.475814, 1.582428)   2
(2.407579, -0.123191, 0.016836)   12
(1.535415, 0.472028, -1.076646)   3
ligand-270-p-o-79
Pd number index:  12
['P', 'C', 'C', 'O', 'C', 'C', 'C', 'C', 'H', 'H', 'H', 'H', 'Pd', 'P', 'C', 'H', 'H', 'H', 'C', 'H', 'H', 'H', 'C', 'C', 'C', 'H', 'H', 'H', 'C', 'H', 'H', 'H', 'C', 'H', 'H', 'H', 'C', 'H', 'H', 'H', 'C', 'H', 'H', 'H', 'C', 'H', 'H', 'H', 'C', 'C', 'C', 'C', 'H', 'C', 'C', 'H', 'H', 'H', 'C', 'C', 'C', 'C', 'H', 'C', 'C', 'H', 'H', 'H', 'C', 'C', 'F', 'F', 'F', 'F', 'F', 'F']

C:\Users\George\AppData\Local\Temp\ipykernel_7832\386804788.py:583: DeprecationWarning:

to_plotly_figure is deprecated and will be removed in version 4.0.0. Use MolGraph.to_plotly() instead.

C:\Users\George\AppData\Local\Temp\ipykernel_7832\386804788.py:589: DeprecationWarning:

to_networkx_graph is deprecated and will be removed in version 4.0.0. Use MolGraph.to_networkx() instead.

Ligand atom label:  1  Ligand atom B nbo:  0.9531
Ligand atom label:  4  Ligand atom A nbo:  -1.04472
Atom_a:  1 Atom_b:  4
C:\Users\George\Desktop\Research_UCLA\CIC\Computational Work\Project cluster version 2\project_catalyst_repurposing\structures_ligand_id\pd_me2_structures\ligand_xyz\ligand-270-p-o-79-ligand_xyz.txt
Starting node: 0
Ending node: 3
(-0.871792, 0.139036, 0.272319)   0
(0.150921, -0.818858, 1.51048)   1
(1.55152, -0.98329, 1.394197)   2
(2.583131, -0.216046, 0.070609)   12
(1.761001, 0.643971, -0.875661)   3
ligand-271-p-o-80
Pd number index:  12
['P', 'C', 'C', 'O', 'C', 'C', 'C', 'C', 'H', 'H', 'H', 'H', 'Pd', 'P', 'C', 'H', 'H', 'H', 'C', 'H', 'H', 'H', 'C', 'C', 'C', 'H', 'H', 'H', 'C', 'H', 'H', 'H', 'C', 'H', 'H', 'H', 'C', 'H', 'H', 'H', 'C', 'C', 'C', 'C', 'H', 'C', 'C', 'H', 'H', 'H', 'C', 'C', 'C', 'C', 'H', 'C', 'C', 'H', 'H', 'H', 'C', 'C', 'F', 'F', 'F', 'F', 'F', 'F', 'H', 'H']

C:\Users\George\AppData\Local\Temp\ipykernel_7832\386804788.py:583: DeprecationWarning:

to_plotly_figure is deprecated and will be removed in version 4.0.0. Use MolGraph.to_plotly() instead.

C:\Users\George\AppData\Local\Temp\ipykernel_7832\386804788.py:589: DeprecationWarning:

to_networkx_graph is deprecated and will be removed in version 4.0.0. Use MolGraph.to_networkx() instead.

Ligand atom label:  1  Ligand atom B nbo:  0.95434
Ligand atom label:  4  Ligand atom A nbo:  -1.03436
Atom_a:  1 Atom_b:  4
C:\Users\George\Desktop\Research_UCLA\CIC\Computational Work\Project cluster version 2\project_catalyst_repurposing\structures_ligand_id\pd_me2_structures\ligand_xyz\ligand-271-p-o-80-ligand_xyz.txt
Starting node: 0
Ending node: 3
(0.68391, 0.145377, -0.282398)   0
(-0.303213, -0.89122, -1.482015)   1
(-1.690675, -1.099886, -1.325607)   2
(-2.721751, -0.316667, -0.026113)   12
(-1.970204, 0.662103, 0.859302)   3

C:\Users\George\AppData\Local\Temp\ipykernel_7832\386804788.py:583: DeprecationWarning:

to_plotly_figure is deprecated and will be removed in version 4.0.0. Use MolGraph.to_plotly() instead.

C:\Users\George\AppData\Local\Temp\ipykernel_7832\386804788.py:589: DeprecationWarning:

to_networkx_graph is deprecated and will be removed in version 4.0.0. Use MolGraph.to_networkx() instead.

ligand-272-p-o-81
Pd number index:  12
['P', 'C', 'C', 'O', 'C', 'C', 'C', 'C', 'H', 'H', 'H', 'H', 'Pd', 'P', 'C', 'H', 'H', 'H', 'C', 'H', 'H', 'H', 'C', 'C', 'C', 'C', 'H', 'C', 'C', 'H', 'H', 'H', 'C', 'C', 'C', 'C', 'H', 'C', 'C', 'H', 'H', 'H', 'C', 'C', 'F', 'F', 'F', 'F', 'F', 'F', 'C', 'H', 'H', 'H', 'C', 'H', 'H', 'H']
Ligand atom label:  1  Ligand atom B nbo:  0.95641
Ligand atom label:  4  Ligand atom A nbo:  -1.02335
Atom_a:  1 Atom_b:  4
C:\Users\George\Desktop\Research_UCLA\CIC\Computational Work\Project cluster version 2\project_catalyst_repurposing\structures_ligand_id\pd_me2_structures\ligand_xyz\ligand-272-p-o-81-ligand_xyz.txt
Starting node: 0
Ending node: 3
(-0.250353, 0.186503, 0.270743)   0
(-0.07651, -1.358502, 1.301229)   1
(1.045247, -2.20556, 1.174678)   2
(2.496338, -1.840788, 0.114994)   12
(2.520696, -0.441412, -0.464015)   3
ligand-273-p-o-82
Pd number index:  12
['P', 'C', 'C', 'O', 'C', 'C', 'C', 'C', 'H', 'H', 'H', 'H', 'Pd', 'P', 'C', 'C', 'C', 'C', 'H', 'C', 'C', 'H', 'H', 'H', 'C', 'C', 'C', 'C', 'H', 'C', 'C', 'H', 'H', 'H', 'H', 'C', 'H', 'H', 'H', 'C', 'H', 'H', 'H', 'C', 'C', 'C', 'C', 'H', 'C', 'H', 'C', 'H', 'H', 'H', 'C', 'C', 'C', 'C', 'H', 'C', 'H', 'C', 'H', 'H', 'H', 'H']

C:\Users\George\AppData\Local\Temp\ipykernel_7832\386804788.py:583: DeprecationWarning:

to_plotly_figure is deprecated and will be removed in version 4.0.0. Use MolGraph.to_plotly() instead.

C:\Users\George\AppData\Local\Temp\ipykernel_7832\386804788.py:589: DeprecationWarning:

to_networkx_graph is deprecated and will be removed in version 4.0.0. Use MolGraph.to_networkx() instead.

Ligand atom label:  1  Ligand atom B nbo:  0.95457
Ligand atom label:  4  Ligand atom A nbo:  -1.01659
Atom_a:  1 Atom_b:  4
C:\Users\George\Desktop\Research_UCLA\CIC\Computational Work\Project cluster version 2\project_catalyst_repurposing\structures_ligand_id\pd_me2_structures\ligand_xyz\ligand-273-p-o-82-ligand_xyz.txt
Starting node: 0
Ending node: 3
(1.429139, -0.263133, -0.106956)   0
(0.392826, -1.117648, -1.393071)   1
(-1.019386, -1.140217, -1.287791)   2
(-1.897353, -0.43183, 0.162283)   12
(-1.445068, -1.002, 1.491718)   3
ligand-274-p-o-83

C:\Users\George\AppData\Local\Temp\ipykernel_7832\386804788.py:583: DeprecationWarning:

to_plotly_figure is deprecated and will be removed in version 4.0.0. Use MolGraph.to_plotly() instead.

C:\Users\George\AppData\Local\Temp\ipykernel_7832\386804788.py:589: DeprecationWarning:

to_networkx_graph is deprecated and will be removed in version 4.0.0. Use MolGraph.to_networkx() instead.

Pd number index:  12
['P', 'C', 'C', 'O', 'C', 'C', 'C', 'C', 'H', 'H', 'H', 'H', 'Pd', 'P', 'C', 'C', 'C', 'C', 'H', 'C', 'C', 'H', 'H', 'H', 'C', 'C', 'C', 'C', 'H', 'C', 'C', 'H', 'H', 'H', 'H', 'C', 'H', 'H', 'H', 'C', 'H', 'H', 'H', 'C', 'C', 'C', 'H', 'H', 'H', 'C', 'H', 'H', 'H', 'C', 'H', 'H', 'H', 'C', 'H', 'H', 'H', 'C', 'H', 'H', 'H', 'C', 'H', 'H', 'H', 'H']
Ligand atom label:  1  Ligand atom B nbo:  0.97266
Ligand atom label:  4  Ligand atom A nbo:  -1.04466
Atom_a:  1 Atom_b:  4
C:\Users\George\Desktop\Research_UCLA\CIC\Computational Work\Project cluster version 2\project_catalyst_repurposing\structures_ligand_id\pd_me2_structures\ligand_xyz\ligand-274-p-o-83-ligand_xyz.txt

C:\Users\George\AppData\Local\Temp\ipykernel_7832\386804788.py:583: DeprecationWarning:

to_plotly_figure is deprecated and will be removed in version 4.0.0. Use MolGraph.to_plotly() instead.

C:\Users\George\AppData\Local\Temp\ipykernel_7832\386804788.py:589: DeprecationWarning:

to_networkx_graph is deprecated and will be removed in version 4.0.0. Use MolGraph.to_networkx() instead.

Starting node: 0
Ending node: 3
(-1.290953, 0.015958, -0.029158)   0
(-0.358047, 0.77739, 1.400494)   1
(1.056167, 0.791686, 1.475237)   2
(2.167246, 0.108819, 0.171553)   12
(1.407037, -0.440736, -1.024768)   3
ligand-275-p-o-84
Pd number index:  12
['P', 'C', 'C', 'O', 'C', 'C', 'C', 'C', 'H', 'H', 'H', 'H', 'Pd', 'P', 'C', 'H', 'H', 'H', 'C', 'H', 'H', 'H', 'C', 'C', 'C', 'C', 'H', 'C', 'H', 'C', 'H', 'H', 'H', 'C', 'C', 'C', 'C', 'H', 'C', 'H', 'C', 'H', 'H', 'H', 'C', 'H', 'C', 'H', 'C', 'H', 'H', 'H', 'C', 'H', 'H', 'H', 'C', 'H', 'H', 'H', 'C', 'H', 'H', 'H']
Ligand atom label:  1  Ligand atom B nbo:  0.90279
Ligand atom label:  4  Ligand atom A nbo:  -1.02021
Atom_a:  1 Atom_b:  4
C:\Users\George\Desktop\Research_UCLA\CIC\Computational Work\Project cluster version 2\project_catalyst_repurposing\structures_ligand_id\pd_me2_structures\ligand_xyz\ligand-275-p-o-84-ligand_xyz.txt
Starting node: 0
Ending node: 3
(1.872181, 0.883094, 0.090796)   0
(0.426236, 1.937467, 0.653574)   1
(-0.925601, 1.571769, 0.470222)   2
(-1.401222, -0.031642, -0.280345)   12
(-0.647604, -0.364482, -1.552876)   3
ligand-276-n-n-23

C:\Users\George\AppData\Local\Temp\ipykernel_7832\386804788.py:583: DeprecationWarning:

to_plotly_figure is deprecated and will be removed in version 4.0.0. Use MolGraph.to_plotly() instead.

C:\Users\George\AppData\Local\Temp\ipykernel_7832\386804788.py:589: DeprecationWarning:

to_networkx_graph is deprecated and will be removed in version 4.0.0. Use MolGraph.to_networkx() instead.

Pd number index:  0
['Pd', 'C', 'C', 'N', 'N', 'C', 'H', 'H', 'H', 'C', 'H', 'H', 'H', 'C', 'H', 'H', 'H', 'C', 'H', 'H', 'H', 'C', 'C', 'C', 'C', 'C', 'C', 'H', 'C', 'C', 'C', 'H', 'C', 'H', 'H', 'H', 'H', 'C', 'C', 'C', 'C', 'C', 'C', 'H', 'C', 'C', 'C', 'H', 'C', 'H', 'H', 'H', 'H', 'C', 'C', 'C', 'C', 'H', 'C', 'H', 'C', 'H', 'H', 'C', 'C', 'C', 'C', 'H', 'C', 'H', 'C', 'H', 'H', 'C', 'H', 'H', 'H', 'C', 'H', 'H', 'H']
Ligand atom label:  4  Ligand atom A nbo:  -0.47987
Ligand atom label:  5  Ligand atom B nbo:  -0.4798
Atom_a:  5 Atom_b:  4
C:\Users\George\Desktop\Research_UCLA\CIC\Computational Work\Project cluster version 2\project_catalyst_repurposing\structures_ligand_id\pd_me2_structures\ligand_xyz\ligand-276-n-n-23-ligand_xyz.txt
Ending node: 2
Starting node: 3
(-1.278892, 0.353814, 0.044228)   3
(-0.692221, 0.277031, -1.097666)   1
(0.692202, -0.277057, -1.097622)   0
(1.278855, -0.353641, 0.044303)   2
ligand-277-n-n-24

C:\Users\George\AppData\Local\Temp\ipykernel_7832\386804788.py:583: DeprecationWarning:

to_plotly_figure is deprecated and will be removed in version 4.0.0. Use MolGraph.to_plotly() instead.

C:\Users\George\AppData\Local\Temp\ipykernel_7832\386804788.py:589: DeprecationWarning:

to_networkx_graph is deprecated and will be removed in version 4.0.0. Use MolGraph.to_networkx() instead.

Pd number index:  0
['Pd', 'C', 'C', 'N', 'N', 'C', 'H', 'H', 'H', 'C', 'H', 'H', 'H', 'C', 'C', 'C', 'C', 'C', 'C', 'H', 'C', 'C', 'C', 'H', 'C', 'H', 'H', 'H', 'H', 'C', 'C', 'C', 'C', 'C', 'C', 'H', 'C', 'C', 'C', 'H', 'C', 'H', 'H', 'H', 'H', 'C', 'C', 'C', 'C', 'H', 'C', 'H', 'C', 'H', 'H', 'C', 'C', 'C', 'C', 'H', 'C', 'H', 'C', 'H', 'H', 'C', 'H', 'H', 'H', 'C', 'H', 'H', 'H', 'C', 'C', 'C', 'C', 'C', 'C', 'H', 'C', 'C', 'C', 'H', 'C', 'H', 'H', 'H', 'H']
Ligand atom label:  4  Ligand atom B nbo:  -0.46446
Ligand atom label:  5  Ligand atom A nbo:  -0.46446
Atom_a:  5 Atom_b:  4
C:\Users\George\Desktop\Research_UCLA\CIC\Computational Work\Project cluster version 2\project_catalyst_repurposing\structures_ligand_id\pd_me2_structures\ligand_xyz\ligand-277-n-n-24-ligand_xyz.txt
Ending node: 2
Starting node: 3
(-1.334808, 0.703675, -0.31132)   3
(-0.716327, -0.415128, -0.215407)   1
(0.716296, -0.414235, 0.215634)   0
(1.333734, 0.705259, 0.310211)   2
ligand-278-p-o-85
Pd number index:  2
['P', 'O', 'Pd', 'P', 'C', 'H', 'H', 'H', 'C', 'H', 'H', 'H', 'C', 'C', 'C', 'C', 'H', 'C', 'H', 'C', 'H', 'H', 'H', 'C', 'C', 'C', 'C', 'H', 'C', 'H', 'C', 'H', 'H', 'H', 'C', 'C', 'C', 'C', 'H', 'C', 'C', 'H', 'H', 'H', 'C', 'C', 'C', 'C', 'H', 'C', 'C', 'H', 'H', 'H', 'C', 'C', 'S', 'C', 'C', 'H', 'Br', 'O', 'O', 'C', 'H', 'H', 'H', 'C', 'H', 'H', 'H']

C:\Users\George\AppData\Local\Temp\ipykernel_7832\386804788.py:583: DeprecationWarning:

to_plotly_figure is deprecated and will be removed in version 4.0.0. Use MolGraph.to_plotly() instead.

C:\Users\George\AppData\Local\Temp\ipykernel_7832\386804788.py:589: DeprecationWarning:

to_networkx_graph is deprecated and will be removed in version 4.0.0. Use MolGraph.to_networkx() instead.

Ligand atom label:  1  Ligand atom B nbo:  1.00286
Ligand atom label:  2  Ligand atom A nbo:  -1.03343
Atom_a:  1 Atom_b:  2
C:\Users\George\Desktop\Research_UCLA\CIC\Computational Work\Project cluster version 2\project_catalyst_repurposing\structures_ligand_id\pd_me2_structures\ligand_xyz\ligand-278-p-o-85-ligand_xyz.txt

C:\Users\George\AppData\Local\Temp\ipykernel_7832\386804788.py:583: DeprecationWarning:

to_plotly_figure is deprecated and will be removed in version 4.0.0. Use MolGraph.to_plotly() instead.

C:\Users\George\AppData\Local\Temp\ipykernel_7832\386804788.py:589: DeprecationWarning:

to_networkx_graph is deprecated and will be removed in version 4.0.0. Use MolGraph.to_networkx() instead.

Starting node: 0
Ending node: 1
(1.671894, 0.032849, -0.20215)   0
(0.276737, -0.579506, -1.24077)   45
(-1.082484, -0.582774, -0.953924)   46
(-1.724232, 0.267624, 0.531074)   2
(-0.653909, 0.488064, 1.575061)   1
ligand-279-p-o-86
Pd number index:  2
['P', 'O', 'Pd', 'P', 'C', 'H', 'H', 'H', 'C', 'H', 'H', 'H', 'C', 'C', 'C', 'C', 'H', 'C', 'H', 'C', 'H', 'H', 'H', 'C', 'C', 'C', 'C', 'H', 'C', 'H', 'C', 'H', 'H', 'H', 'C', 'C', 'C', 'C', 'H', 'C', 'C', 'H', 'H', 'H', 'C', 'C', 'C', 'C', 'H', 'C', 'C', 'H', 'H', 'H', 'C', 'C', 'S', 'O', 'O', 'C', 'H', 'H', 'H', 'C', 'H', 'H', 'H', 'C', 'C', 'C', 'C', 'H', 'C', 'C', 'H', 'H', 'H']
Ligand atom label:  1  Ligand atom B nbo:  0.98982
Ligand atom label:  2  Ligand atom A nbo:  -1.02715
Atom_a:  1 Atom_b:  2
C:\Users\George\Desktop\Research_UCLA\CIC\Computational Work\Project cluster version 2\project_catalyst_repurposing\structures_ligand_id\pd_me2_structures\ligand_xyz\ligand-279-p-o-86-ligand_xyz.txt
Starting node: 0
Ending node: 1
(-1.581787, -0.119593, -0.164642)   0
(-0.275509, 0.915344, -0.952425)   45
(1.074928, 0.91677, -0.668393)   46
(1.805311, -0.334758, 0.427659)   2
(0.797508, -1.02475, 1.322497)   1
ligand-280-p-o-87

C:\Users\George\AppData\Local\Temp\ipykernel_7832\386804788.py:583: DeprecationWarning:

to_plotly_figure is deprecated and will be removed in version 4.0.0. Use MolGraph.to_plotly() instead.

C:\Users\George\AppData\Local\Temp\ipykernel_7832\386804788.py:589: DeprecationWarning:

to_networkx_graph is deprecated and will be removed in version 4.0.0. Use MolGraph.to_networkx() instead.

Pd number index:  2
['P', 'O', 'Pd', 'P', 'C', 'H', 'H', 'H', 'C', 'H', 'H', 'H', 'C', 'C', 'C', 'C', 'H', 'C', 'H', 'C', 'H', 'H', 'H', 'C', 'C', 'C', 'C', 'H', 'C', 'H', 'C', 'H', 'H', 'H', 'C', 'C', 'S', 'C', 'C', 'C', 'C', 'H', 'C', 'C', 'H', 'H', 'H', 'C', 'C', 'C', 'H', 'C', 'H', 'H', 'C', 'H', 'H', 'C', 'H', 'H', 'H', 'H', 'H', 'H', 'C', 'C', 'C', 'H', 'C', 'H', 'H', 'C', 'H', 'H', 'C', 'H', 'H', 'H', 'H', 'H', 'H']
Ligand atom label:  1  Ligand atom B nbo:  0.96046
Ligand atom label:  2  Ligand atom A nbo:  -1.01061
Atom_a:  1 Atom_b:  2
C:\Users\George\Desktop\Research_UCLA\CIC\Computational Work\Project cluster version 2\project_catalyst_repurposing\structures_ligand_id\pd_me2_structures\ligand_xyz\ligand-280-p-o-87-ligand_xyz.txt
Starting node: 0
Ending node: 1
(1.657794, 0.026038, -0.094416)   0
(0.325406, 1.246213, 0.312662)   25
(-1.042738, 1.058822, 0.199383)   26
(-1.742714, -0.409579, -0.649323)   2
(-0.981302, -0.830778, -1.886864)   1
ligand-281-p-o-88

C:\Users\George\AppData\Local\Temp\ipykernel_7832\386804788.py:583: DeprecationWarning:

to_plotly_figure is deprecated and will be removed in version 4.0.0. Use MolGraph.to_plotly() instead.

C:\Users\George\AppData\Local\Temp\ipykernel_7832\386804788.py:589: DeprecationWarning:

to_networkx_graph is deprecated and will be removed in version 4.0.0. Use MolGraph.to_networkx() instead.

Pd number index:  2
['P', 'O', 'Pd', 'P', 'C', 'H', 'H', 'H', 'C', 'H', 'H', 'H', 'C', 'C', 'C', 'C', 'H', 'C', 'H', 'C', 'H', 'H', 'H', 'C', 'C', 'C', 'C', 'H', 'C', 'H', 'C', 'H', 'H', 'H', 'C', 'C', 'S', 'C', 'C', 'C', 'C', 'C', 'C', 'H', 'H', 'H', 'C', 'C', 'C', 'C', 'H', 'C', 'H', 'C', 'H', 'H', 'H', 'C', 'C', 'C', 'C', 'H', 'C', 'C', 'H', 'H', 'H', 'C', 'C', 'C', 'C', 'C', 'C', 'H', 'H', 'H', 'O', 'O', 'C', 'H', 'H', 'H', 'C', 'H', 'H', 'H', 'H']
Ligand atom label:  1  Ligand atom B nbo:  0.99437
Ligand atom label:  2  Ligand atom A nbo:  -1.01971
Atom_a:  1 Atom_b:  2
C:\Users\George\Desktop\Research_UCLA\CIC\Computational Work\Project cluster version 2\project_catalyst_repurposing\structures_ligand_id\pd_me2_structures\ligand_xyz\ligand-281-p-o-88-ligand_xyz.txt
Starting node: 0
Ending node: 1
(-1.235789, 0.597278, 0.613785)   0
(0.155307, -0.388385, 1.331452)   25
(1.410281, -0.581597, 0.790429)   26
(1.847026, 0.290925, -0.753406)   2
(0.881067, 0.067553, -1.900217)   1
ligand-282-p-o-89
Pd number index:  12
['P', 'C', 'C', 'O', 'C', 'C', 'C', 'C', 'H', 'H', 'H', 'H', 'Pd', 'P', 'C', 'C', 'C', 'C', 'H', 'C', 'C', 'H', 'H', 'H', 'C', 'C', 'C', 'C', 'C', 'C', 'H', 'H', 'H', 'H', 'C', 'H', 'H', 'H', 'C', 'H', 'H', 'H', 'C', 'C', 'C', 'C', 'H', 'C', 'H', 'C', 'H', 'H', 'H', 'C', 'C', 'C', 'C', 'H', 'C', 'H', 'C', 'H', 'H', 'H', 'O', 'O', 'C', 'H', 'H', 'H', 'C', 'H', 'H', 'H']
Ligand atom label:  1  Ligand atom B nbo:  0.94929
Ligand atom label:  4  Ligand atom A nbo:  -1.02296
Atom_a:  1 Atom_b:  4

C:\Users\George\AppData\Local\Temp\ipykernel_7832\386804788.py:583: DeprecationWarning:

to_plotly_figure is deprecated and will be removed in version 4.0.0. Use MolGraph.to_plotly() instead.

C:\Users\George\AppData\Local\Temp\ipykernel_7832\386804788.py:589: DeprecationWarning:

to_networkx_graph is deprecated and will be removed in version 4.0.0. Use MolGraph.to_networkx() instead.

C:\Users\George\Desktop\Research_UCLA\CIC\Computational Work\Project cluster version 2\project_catalyst_repurposing\structures_ligand_id\pd_me2_structures\ligand_xyz\ligand-282-p-o-89-ligand_xyz.txt
Starting node: 0
Ending node: 3
(-1.146553, -0.074661, 0.410022)   0
(0.003881, -0.735053, 1.711472)   1
(1.396938, -0.802572, 1.479225)   2
(2.113503, -0.401967, -0.16115)   12
(1.567297, -1.262101, -1.282208)   3
ligand-283-p-o-90

C:\Users\George\AppData\Local\Temp\ipykernel_7832\386804788.py:583: DeprecationWarning:

to_plotly_figure is deprecated and will be removed in version 4.0.0. Use MolGraph.to_plotly() instead.

C:\Users\George\AppData\Local\Temp\ipykernel_7832\386804788.py:589: DeprecationWarning:

to_networkx_graph is deprecated and will be removed in version 4.0.0. Use MolGraph.to_networkx() instead.

Pd number index:  12
['P', 'C', 'C', 'O', 'C', 'C', 'C', 'C', 'H', 'H', 'H', 'H', 'Pd', 'P', 'C', 'C', 'C', 'C', 'H', 'C', 'C', 'H', 'H', 'H', 'C', 'C', 'C', 'C', 'H', 'C', 'C', 'H', 'H', 'H', 'H', 'C', 'H', 'H', 'H', 'C', 'H', 'H', 'H', 'H', 'O', 'O', 'C', 'H', 'H', 'C', 'H', 'H', 'H', 'C', 'H', 'H', 'C', 'H', 'H', 'H']
Ligand atom label:  1  Ligand atom B nbo:  0.95215
Ligand atom label:  4  Ligand atom A nbo:  -1.02531
Atom_a:  1 Atom_b:  4
C:\Users\George\Desktop\Research_UCLA\CIC\Computational Work\Project cluster version 2\project_catalyst_repurposing\structures_ligand_id\pd_me2_structures\ligand_xyz\ligand-283-p-o-90-ligand_xyz.txt

C:\Users\George\AppData\Local\Temp\ipykernel_7832\386804788.py:583: DeprecationWarning:

to_plotly_figure is deprecated and will be removed in version 4.0.0. Use MolGraph.to_plotly() instead.

C:\Users\George\AppData\Local\Temp\ipykernel_7832\386804788.py:589: DeprecationWarning:

to_networkx_graph is deprecated and will be removed in version 4.0.0. Use MolGraph.to_networkx() instead.

Starting node: 0
Ending node: 3
(1.080951, 0.098738, -0.06759)   0
(0.295407, 1.769059, -0.27146)   1
(-1.112673, 1.897276, -0.265819)   2
(-2.189428, 0.457237, -0.126122)   12
(-2.035984, -0.591328, -1.186214)   3
ligand-284-p-o-92
Pd number index:  9
['P', 'C', 'C', 'O', 'C', 'C', 'C', 'H', 'H', 'Pd', 'P', 'C', 'H', 'H', 'H', 'C', 'H', 'H', 'H', 'O', 'O', 'C', 'H', 'H', 'C', 'H', 'H', 'H', 'C', 'H', 'H', 'C', 'H', 'H', 'H', 'C', 'H', 'C', 'H', 'C', 'H', 'H', 'H', 'C', 'H', 'H', 'H', 'C', 'H', 'H', 'H', 'C', 'H', 'H', 'H', 'C', 'H', 'C', 'H', 'H', 'H']
Ligand atom label:  1  Ligand atom B nbo:  0.90638
Ligand atom label:  4  Ligand atom A nbo:  -1.02787
Atom_a:  1 Atom_b:  4
C:\Users\George\Desktop\Research_UCLA\CIC\Computational Work\Project cluster version 2\project_catalyst_repurposing\structures_ligand_id\pd_me2_structures\ligand_xyz\ligand-284-p-o-92-ligand_xyz.txt
Starting node: 0
Ending node: 3
(-1.465472, -0.679124, 0.25123)   0
(-1.364174, 1.175603, -0.017451)   1
(-0.147445, 1.884515, -0.093017)   2
(1.479347, 1.179049, 0.247689)   9
(1.502827, -0.035646, 1.125933)   3
ligand-285-p-o-93

C:\Users\George\AppData\Local\Temp\ipykernel_7832\386804788.py:583: DeprecationWarning:

to_plotly_figure is deprecated and will be removed in version 4.0.0. Use MolGraph.to_plotly() instead.

C:\Users\George\AppData\Local\Temp\ipykernel_7832\386804788.py:589: DeprecationWarning:

to_networkx_graph is deprecated and will be removed in version 4.0.0. Use MolGraph.to_networkx() instead.

Pd number index:  9
['P', 'C', 'C', 'O', 'C', 'C', 'C', 'H', 'H', 'Pd', 'P', 'C', 'H', 'H', 'H', 'O', 'O', 'C', 'H', 'H', 'C', 'H', 'H', 'H', 'C', 'H', 'H', 'C', 'H', 'H', 'H', 'C', 'H', 'C', 'H', 'H', 'H', 'C', 'C', 'C', 'C', 'H', 'C', 'H', 'C', 'H', 'H', 'C', 'C', 'H', 'H', 'H', 'C', 'H', 'H', 'H', 'C', 'H', 'H', 'H', 'C', 'H', 'H', 'H', 'C', 'C', 'C', 'C', 'H', 'C', 'C', 'H', 'H', 'C', 'H', 'H', 'H', 'P', 'O', 'O', 'O', 'C', 'H', 'H', 'C', 'H', 'H', 'C', 'H', 'H', 'H', 'C', 'H', 'H', 'H']
Ligand atom label:  1  Ligand atom B nbo:  0.96314
Ligand atom label:  4  Ligand atom A nbo:  -1.0289
Atom_a:  1 Atom_b:  4
C:\Users\George\Desktop\Research_UCLA\CIC\Computational Work\Project cluster version 2\project_catalyst_repurposing\structures_ligand_id\pd_me2_structures\ligand_xyz\ligand-285-p-o-93-ligand_xyz.txt
Starting node: 0
Ending node: 3
(0.414403, -0.296464, -0.134876)   0
(-0.09685, 0.316006, 1.535851)   1
(-0.239501, 1.696637, 1.785492)   2
(-0.114797, 2.934682, 0.477464)   9
(0.860131, 2.697362, -0.632994)   3
ligand-286-p-o-98
Pd number index:  12
['P', 'C', 'C', 'O', 'C', 'C', 'C', 'C', 'H', 'H', 'H', 'H', 'Pd', 'P', 'C', 'H', 'H', 'H', 'C', 'H', 'H', 'H', 'N', 'N', 'C', 'H', 'H', 'H', 'C', 'H', 'H', 'H', 'C', 'H', 'H', 'C', 'H', 'H', 'H', 'H', 'C', 'H', 'C', 'H', 'C', 'H', 'H', 'H', 'C', 'H', 'H', 'H', 'C', 'H', 'H', 'H', 'C', 'H', 'H', 'H']
Ligand atom label:  1  Ligand atom B nbo:  0.90658
Ligand atom label:  4  Ligand atom A nbo:  -1.02648
Atom_a:  1 Atom_b:  4

C:\Users\George\AppData\Local\Temp\ipykernel_7832\386804788.py:583: DeprecationWarning:

to_plotly_figure is deprecated and will be removed in version 4.0.0. Use MolGraph.to_plotly() instead.

C:\Users\George\AppData\Local\Temp\ipykernel_7832\386804788.py:589: DeprecationWarning:

to_networkx_graph is deprecated and will be removed in version 4.0.0. Use MolGraph.to_networkx() instead.

C:\Users\George\Desktop\Research_UCLA\CIC\Computational Work\Project cluster version 2\project_catalyst_repurposing\structures_ligand_id\pd_me2_structures\ligand_xyz\ligand-286-p-o-98-ligand_xyz.txt
Starting node: 0
Ending node: 3
(1.323357, 0.902572, 0.016188)   0
(-0.279243, 1.879999, 0.025615)   1
(-1.56601, 1.30308, -0.027729)   2
(-1.828252, -0.500456, -0.133537)   12
(-0.8698, -1.221252, -1.046483)   3
ligand-287-p-o-99
Pd number index:  12
['P', 'C', 'C', 'O', 'C', 'C', 'C', 'C', 'H', 'H', 'H', 'H', 'Pd', 'P', 'C', 'H', 'H', 'H', 'C', 'H', 'H', 'H', 'N', 'N', 'C', 'H', 'C', 'H', 'C', 'C', 'H', 'H', 'C', 'H', 'C', 'H', 'C', 'H', 'H', 'H', 'C', 'H', 'H', 'H', 'C', 'H', 'H', 'H', 'C', 'H', 'H', 'H', 'C', 'H', 'H', 'H', 'C', 'H', 'H', 'H', 'C', 'H', 'H', 'H', 'C', 'H', 'H', 'H', 'C', 'H', 'H', 'H', 'C', 'H', 'H', 'H', 'C', 'H', 'H', 'H', 'C', 'H', 'H', 'H']

C:\Users\George\AppData\Local\Temp\ipykernel_7832\386804788.py:583: DeprecationWarning:

to_plotly_figure is deprecated and will be removed in version 4.0.0. Use MolGraph.to_plotly() instead.

C:\Users\George\AppData\Local\Temp\ipykernel_7832\386804788.py:589: DeprecationWarning:

to_networkx_graph is deprecated and will be removed in version 4.0.0. Use MolGraph.to_networkx() instead.

Ligand atom label:  1  Ligand atom B nbo:  0.89581
Ligand atom label:  4  Ligand atom A nbo:  -1.05651
Atom_a:  1 Atom_b:  4
C:\Users\George\Desktop\Research_UCLA\CIC\Computational Work\Project cluster version 2\project_catalyst_repurposing\structures_ligand_id\pd_me2_structures\ligand_xyz\ligand-287-p-o-99-ligand_xyz.txt

C:\Users\George\AppData\Local\Temp\ipykernel_7832\386804788.py:583: DeprecationWarning:

to_plotly_figure is deprecated and will be removed in version 4.0.0. Use MolGraph.to_plotly() instead.

C:\Users\George\AppData\Local\Temp\ipykernel_7832\386804788.py:589: DeprecationWarning:

to_networkx_graph is deprecated and will be removed in version 4.0.0. Use MolGraph.to_networkx() instead.

Starting node: 0
Ending node: 3
(-2.168675, 0.792953, 0.0826)   0
(-0.74254, 1.961733, 0.427462)   1
(0.616489, 1.580276, 0.526447)   2
(1.325125, 0.037242, -0.207936)   12
(0.340369, -0.552958, -1.191859)   3
ligand-288-p-o-100
Pd number index:  12
['P', 'C', 'C', 'O', 'C', 'C', 'C', 'C', 'H', 'H', 'H', 'H', 'Pd', 'P', 'C', 'H', 'H', 'H', 'C', 'H', 'H', 'H', 'N', 'N', 'C', 'H', 'C', 'H', 'C', 'C', 'H', 'H', 'C', 'H', 'C', 'H', 'C', 'H', 'H', 'C', 'H', 'H', 'C', 'H', 'H', 'C', 'H', 'H', 'C', 'H', 'H', 'H', 'C', 'H', 'H', 'H', 'C', 'H', 'H', 'H', 'C', 'H', 'H', 'H', 'C', 'H', 'H', 'H', 'C', 'H', 'H', 'H', 'C', 'H', 'H', 'H', 'C', 'H', 'H', 'H', 'C', 'H', 'H', 'H', 'C', 'H', 'H', 'H', 'C', 'H', 'H', 'H', 'C', 'H', 'H', 'H']
Ligand atom label:  1  Ligand atom B nbo:  0.87096
Ligand atom label:  4  Ligand atom A nbo:  -1.05789
Atom_a:  1 Atom_b:  4
C:\Users\George\Desktop\Research_UCLA\CIC\Computational Work\Project cluster version 2\project_catalyst_repurposing\structures_ligand_id\pd_me2_structures\ligand_xyz\ligand-288-p-o-100-ligand_xyz.txt
Starting node: 0
Ending node: 3
(-1.877528, 0.470945, 0.324482)   0
(-0.515827, 1.720418, 0.689466)   1
(0.871264, 1.533634, 0.474997)   2
(1.624408, -0.036324, -0.124791)   12
(0.810784, -1.195641, 0.400382)   3
ligand-289-p-o-101
Pd number index:  12
['P', 'C', 'C', 'O', 'C', 'C', 'C', 'C', 'H', 'H', 'H', 'H', 'Pd', 'P', 'C', 'H', 'H', 'H', 'C', 'H', 'H', 'H', 'N', 'N', 'C', 'H', 'C', 'H', 'C', 'C', 'H', 'H', 'C', 'H', 'H', 'H', 'C', 'H', 'H', 'H', 'C', 'H', 'H', 'H', 'C', 'H', 'H', 'H', 'C', 'H', 'H', 'H', 'C', 'H', 'H', 'H', 'C', 'H', 'H', 'H', 'C', 'H', 'H', 'H', 'C', 'C', 'C', 'C', 'H', 'C', 'H', 'C', 'H', 'H', 'H', 'C', 'C', 'C', 'C', 'H', 'C', 'H', 'C', 'H', 'H', 'H']
Ligand atom label:  1  Ligand atom B nbo:  0.96122
Ligand atom label:  4  Ligand atom A nbo:  -1.04298
Atom_a:  1 Atom_b:  4

C:\Users\George\AppData\Local\Temp\ipykernel_7832\386804788.py:583: DeprecationWarning:

to_plotly_figure is deprecated and will be removed in version 4.0.0. Use MolGraph.to_plotly() instead.

C:\Users\George\AppData\Local\Temp\ipykernel_7832\386804788.py:589: DeprecationWarning:

to_networkx_graph is deprecated and will be removed in version 4.0.0. Use MolGraph.to_networkx() instead.

C:\Users\George\Desktop\Research_UCLA\CIC\Computational Work\Project cluster version 2\project_catalyst_repurposing\structures_ligand_id\pd_me2_structures\ligand_xyz\ligand-289-p-o-101-ligand_xyz.txt
Starting node: 0
Ending node: 3
(-1.777941, -0.205074, 0.050514)   0
(-0.689648, -0.941257, 1.378035)   1
(0.725045, -0.851743, 1.380074)   2
(1.73808, -0.184294, -0.00705)   12
(1.108026, -0.481136, -1.34764)   3
ligand-290-p-o-102

C:\Users\George\AppData\Local\Temp\ipykernel_7832\386804788.py:583: DeprecationWarning:

to_plotly_figure is deprecated and will be removed in version 4.0.0. Use MolGraph.to_plotly() instead.

C:\Users\George\AppData\Local\Temp\ipykernel_7832\386804788.py:589: DeprecationWarning:

to_networkx_graph is deprecated and will be removed in version 4.0.0. Use MolGraph.to_networkx() instead.

Pd number index:  12
['P', 'C', 'C', 'O', 'C', 'C', 'C', 'C', 'H', 'H', 'H', 'H', 'Pd', 'P', 'C', 'H', 'H', 'H', 'C', 'H', 'H', 'H', 'N', 'N', 'C', 'C', 'C', 'C', 'C', 'H', 'C', 'H', 'H', 'H', 'C', 'C', 'C', 'C', 'H', 'C', 'C', 'H', 'H', 'H', 'O', 'O', 'C', 'H', 'H', 'H', 'C', 'H', 'H', 'H', 'C', 'H', 'H', 'H', 'C', 'H', 'H', 'H', 'C', 'H', 'H', 'H', 'C', 'H', 'H', 'H']
Ligand atom label:  1  Ligand atom B nbo:  0.97757
Ligand atom label:  4  Ligand atom A nbo:  -1.04991
Atom_a:  1 Atom_b:  4
C:\Users\George\Desktop\Research_UCLA\CIC\Computational Work\Project cluster version 2\project_catalyst_repurposing\structures_ligand_id\pd_me2_structures\ligand_xyz\ligand-290-p-o-102-ligand_xyz.txt
Starting node: 0
Ending node: 3
(-0.927022, 0.033703, -0.270059)   0
(-0.123551, 0.427218, 1.364217)   1
(1.270177, 0.321144, 1.548235)   2
(2.474509, 0.028025, 0.20729)   12
(1.858904, -0.128078, -1.161142)   3
ligand-291-p-o-103

C:\Users\George\AppData\Local\Temp\ipykernel_7832\386804788.py:583: DeprecationWarning:

to_plotly_figure is deprecated and will be removed in version 4.0.0. Use MolGraph.to_plotly() instead.

C:\Users\George\AppData\Local\Temp\ipykernel_7832\386804788.py:589: DeprecationWarning:

to_networkx_graph is deprecated and will be removed in version 4.0.0. Use MolGraph.to_networkx() instead.

Pd number index:  12
['P', 'C', 'C', 'O', 'C', 'C', 'C', 'C', 'H', 'H', 'H', 'H', 'Pd', 'P', 'C', 'H', 'H', 'H', 'C', 'H', 'H', 'H', 'N', 'N', 'C', 'C', 'C', 'C', 'C', 'H', 'C', 'H', 'H', 'H', 'C', 'C', 'C', 'C', 'H', 'C', 'C', 'H', 'H', 'H', 'O', 'O', 'C', 'H', 'H', 'H', 'C', 'H', 'H', 'H', 'C', 'H', 'H', 'C', 'H', 'H', 'C', 'H', 'H', 'C', 'H', 'H', 'C', 'H', 'H', 'H', 'C', 'H', 'H', 'H', 'C', 'H', 'H', 'H', 'C', 'H', 'H', 'H']
Ligand atom label:  1  Ligand atom B nbo:  0.9745
Ligand atom label:  4  Ligand atom A nbo:  -1.03721
Atom_a:  1 Atom_b:  4
C:\Users\George\Desktop\Research_UCLA\CIC\Computational Work\Project cluster version 2\project_catalyst_repurposing\structures_ligand_id\pd_me2_structures\ligand_xyz\ligand-291-p-o-103-ligand_xyz.txt
Starting node: 0
Ending node: 3
(-1.248887, 0.220537, 0.283146)   0
(-0.075157, 0.223077, 1.726605)   1
(1.321402, 0.106408, 1.566006)   2
(2.18157, 0.098939, -0.05536)   12
(1.315512, 0.597148, -1.189551)   3
ligand-292-p-o-104

C:\Users\George\AppData\Local\Temp\ipykernel_7832\386804788.py:583: DeprecationWarning:

to_plotly_figure is deprecated and will be removed in version 4.0.0. Use MolGraph.to_plotly() instead.

C:\Users\George\AppData\Local\Temp\ipykernel_7832\386804788.py:589: DeprecationWarning:

to_networkx_graph is deprecated and will be removed in version 4.0.0. Use MolGraph.to_networkx() instead.

Pd number index:  12
['P', 'C', 'C', 'O', 'C', 'C', 'C', 'C', 'H', 'H', 'H', 'H', 'Pd', 'P', 'C', 'H', 'H', 'H', 'C', 'H', 'H', 'H', 'N', 'N', 'C', 'C', 'C', 'C', 'C', 'H', 'C', 'H', 'H', 'H', 'C', 'C', 'C', 'C', 'H', 'C', 'C', 'H', 'H', 'H', 'O', 'O', 'C', 'H', 'H', 'H', 'C', 'H', 'H', 'H', 'C', 'H', 'C', 'H', 'C', 'H', 'C', 'H', 'C', 'H', 'H', 'H', 'C', 'H', 'H', 'H', 'C', 'H', 'H', 'H', 'C', 'H', 'H', 'H', 'C', 'H', 'H', 'H', 'C', 'H', 'H', 'H', 'C', 'H', 'H', 'H', 'C', 'H', 'H', 'H']
Ligand atom label:  1  Ligand atom B nbo:  0.95987
Ligand atom label:  4  Ligand atom A nbo:  -1.05226
Atom_a:  1 Atom_b:  4
C:\Users\George\Desktop\Research_UCLA\CIC\Computational Work\Project cluster version 2\project_catalyst_repurposing\structures_ligand_id\pd_me2_structures\ligand_xyz\ligand-292-p-o-104-ligand_xyz.txt
Starting node: 0
Ending node: 3
(-1.531124, 0.125016, 0.342169)   0
(-0.350732, 0.010546, 1.780224)   1
(1.052057, 0.150095, 1.648729)   2
(1.958884, 0.111781, 0.050159)   12
(1.09637, 0.610615, -1.085892)   3
ligand-293-p-o-105

C:\Users\George\AppData\Local\Temp\ipykernel_7832\386804788.py:583: DeprecationWarning:

to_plotly_figure is deprecated and will be removed in version 4.0.0. Use MolGraph.to_plotly() instead.

C:\Users\George\AppData\Local\Temp\ipykernel_7832\386804788.py:589: DeprecationWarning:

to_networkx_graph is deprecated and will be removed in version 4.0.0. Use MolGraph.to_networkx() instead.

Pd number index:  12
['P', 'C', 'C', 'O', 'C', 'C', 'C', 'C', 'H', 'H', 'H', 'H', 'Pd', 'P', 'C', 'H', 'H', 'H', 'C', 'H', 'H', 'H', 'N', 'N', 'C', 'C', 'C', 'C', 'C', 'C', 'H', 'H', 'H', 'C', 'C', 'C', 'C', 'C', 'C', 'H', 'H', 'H', 'C', 'H', 'C', 'H', 'C', 'H', 'C', 'H', 'C', 'H', 'H', 'H', 'C', 'H', 'H', 'H', 'C', 'H', 'H', 'H', 'C', 'H', 'H', 'H', 'C', 'H', 'H', 'H', 'C', 'H', 'H', 'H', 'C', 'H', 'H', 'H', 'C', 'H', 'H', 'H', 'F', 'F', 'F', 'F']
Ligand atom label:  1  Ligand atom B nbo:  0.9637
Ligand atom label:  4  Ligand atom A nbo:  -1.05727
Atom_a:  1 Atom_b:  4
C:\Users\George\Desktop\Research_UCLA\CIC\Computational Work\Project cluster version 2\project_catalyst_repurposing\structures_ligand_id\pd_me2_structures\ligand_xyz\ligand-293-p-o-105-ligand_xyz.txt
Starting node: 0
Ending node: 3
(-1.519235, -0.022901, 0.005821)   0
(-0.489146, 0.234606, 1.55191)   1
(0.927172, 0.252161, 1.552815)   2
(1.965122, 0.114893, 0.045901)   12
(1.088451, -0.130329, -1.161295)   3
ligand-294-p-o-106
Pd number index:  11
['P', 'C', 'C', 'O', 'C', 'C', 'C', 'C', 'H', 'H', 'H', 'Pd', 'P', 'C', 'H', 'H', 'H', 'C', 'H', 'H', 'H', 'N', 'N', 'C', 'C', 'C', 'C', 'C', 'C', 'H', 'H', 'H', 'C', 'C', 'C', 'C', 'C', 'C', 'H', 'H', 'H', 'O', 'O', 'C', 'H', 'H', 'H', 'C', 'H', 'H', 'H', 'C', 'H', 'H', 'H', 'C', 'H', 'H', 'H', 'C', 'H', 'H', 'H', 'C', 'H', 'H', 'H', 'O', 'O', 'C', 'H', 'H', 'H', 'C', 'H', 'H', 'H', 'N', 'C', 'H', 'H', 'H', 'C', 'H', 'H', 'H']

C:\Users\George\AppData\Local\Temp\ipykernel_7832\386804788.py:583: DeprecationWarning:

to_plotly_figure is deprecated and will be removed in version 4.0.0. Use MolGraph.to_plotly() instead.

C:\Users\George\AppData\Local\Temp\ipykernel_7832\386804788.py:589: DeprecationWarning:

to_networkx_graph is deprecated and will be removed in version 4.0.0. Use MolGraph.to_networkx() instead.

Ligand atom label:  1  Ligand atom B nbo:  0.96173
Ligand atom label:  4  Ligand atom A nbo:  -1.03901
Atom_a:  1 Atom_b:  4
C:\Users\George\Desktop\Research_UCLA\CIC\Computational Work\Project cluster version 2\project_catalyst_repurposing\structures_ligand_id\pd_me2_structures\ligand_xyz\ligand-294-p-o-106-ligand_xyz.txt

C:\Users\George\AppData\Local\Temp\ipykernel_7832\386804788.py:583: DeprecationWarning:

to_plotly_figure is deprecated and will be removed in version 4.0.0. Use MolGraph.to_plotly() instead.

C:\Users\George\AppData\Local\Temp\ipykernel_7832\386804788.py:589: DeprecationWarning:

to_networkx_graph is deprecated and will be removed in version 4.0.0. Use MolGraph.to_networkx() instead.

Starting node: 0
Ending node: 3
(0.605069, -0.547925, -0.08304)   0
(0.290983, 1.275669, 0.124117)   1
(-1.003438, 1.832049, -0.01466)   2
(-2.512488, 0.845098, -0.101897)   11
(-2.328848, -0.614902, -0.438236)   3
ligand-295-p-o-107
Pd number index:  14
['P', 'C', 'C', 'S', 'O', 'O', 'C', 'C', 'C', 'C', 'H', 'H', 'H', 'H', 'Pd', 'C', 'H', 'H', 'H', 'C', 'H', 'H', 'H', 'C', 'C', 'C', 'C', 'H', 'C', 'H', 'C', 'H', 'H', 'H', 'N', 'C', 'C', 'C', 'C', 'H', 'C', 'H', 'C', 'H', 'H', 'H', 'C', 'C', 'C', 'H', 'C', 'H', 'H', 'C', 'H', 'H', 'C', 'H', 'H', 'H', 'H', 'H', 'H', 'C', 'C', 'C', 'H', 'C', 'H', 'H', 'C', 'H', 'H', 'C', 'H', 'H', 'H', 'H', 'H', 'H']
Ligand atom label:  1  Ligand atom B nbo:  0.95179
Ligand atom label:  5  Ligand atom A nbo:  -0.89807
Atom_a:  1 Atom_b:  5
C:\Users\George\Desktop\Research_UCLA\CIC\Computational Work\Project cluster version 2\project_catalyst_repurposing\structures_ligand_id\pd_me2_structures\ligand_xyz\ligand-295-p-o-107-ligand_xyz.txt
Starting node: 0
Ending node: 4
(-2.202525, 0.054703, 0.031871)   0
(-1.122752, 0.44163, 1.499552)   1
(0.28362, 0.357487, 1.426197)   2
(1.064721, -0.068256, -0.142345)   3
(0.734323, -1.47651, -0.423608)   4
ligand-296-p-o-108
Pd number index:  14
['P', 'C', 'C', 'S', 'O', 'O', 'C', 'C', 'C', 'C', 'H', 'H', 'H', 'H', 'Pd', 'C', 'H', 'H', 'H', 'C', 'H', 'H', 'H', 'C', 'C', 'C', 'C', 'H', 'C', 'C', 'H', 'H', 'H', 'N', 'C', 'C', 'C', 'C', 'H', 'C', 'C', 'H', 'H', 'H', 'C', 'C', 'C', 'H', 'C', 'H', 'H', 'C', 'H', 'H', 'C', 'H', 'H', 'H', 'H', 'H', 'H', 'C', 'C', 'C', 'H', 'C', 'H', 'H', 'C', 'H', 'H', 'C', 'H', 'H', 'H', 'H', 'H', 'H', 'O', 'C', 'H', 'H', 'H', 'O', 'C', 'H', 'H', 'H']
Ligand atom label:  1  Ligand atom B nbo:  0.95348
Ligand atom label:  5  Ligand atom A nbo:  -0.89849
Atom_a:  1 Atom_b:  5

C:\Users\George\AppData\Local\Temp\ipykernel_7832\386804788.py:583: DeprecationWarning:

to_plotly_figure is deprecated and will be removed in version 4.0.0. Use MolGraph.to_plotly() instead.

C:\Users\George\AppData\Local\Temp\ipykernel_7832\386804788.py:589: DeprecationWarning:

to_networkx_graph is deprecated and will be removed in version 4.0.0. Use MolGraph.to_networkx() instead.

C:\Users\George\Desktop\Research_UCLA\CIC\Computational Work\Project cluster version 2\project_catalyst_repurposing\structures_ligand_id\pd_me2_structures\ligand_xyz\ligand-296-p-o-108-ligand_xyz.txt
Starting node: 0
Ending node: 4
(-1.887661, 0.26378, 0.199096)   0
(-0.710272, 0.287742, 1.644322)   1
(0.680171, 0.130197, 1.483221)   2
(1.364861, -0.009922, -0.178107)   3
(0.968983, -1.325383, -0.709159)   4
ligand-297-p-o-109

C:\Users\George\AppData\Local\Temp\ipykernel_7832\386804788.py:583: DeprecationWarning:

to_plotly_figure is deprecated and will be removed in version 4.0.0. Use MolGraph.to_plotly() instead.

C:\Users\George\AppData\Local\Temp\ipykernel_7832\386804788.py:589: DeprecationWarning:

to_networkx_graph is deprecated and will be removed in version 4.0.0. Use MolGraph.to_networkx() instead.

Pd number index:  14
['P', 'C', 'C', 'S', 'O', 'O', 'C', 'C', 'C', 'C', 'H', 'H', 'H', 'H', 'Pd', 'C', 'H', 'H', 'H', 'C', 'H', 'H', 'H', 'N', 'C', 'C', 'C', 'H', 'C', 'H', 'H', 'C', 'H', 'H', 'C', 'H', 'H', 'H', 'H', 'H', 'H', 'C', 'C', 'C', 'H', 'C', 'H', 'H', 'C', 'H', 'H', 'C', 'H', 'H', 'H', 'H', 'H', 'H', 'C', 'C', 'C', 'H', 'C', 'H', 'H', 'C', 'H', 'H', 'C', 'H', 'H', 'H', 'H', 'H', 'H', 'C', 'C', 'C', 'H', 'C', 'H', 'H', 'C', 'H', 'H', 'C', 'H', 'H', 'H', 'H', 'H', 'H']
Ligand atom label:  1  Ligand atom B nbo:  0.88604
Ligand atom label:  5  Ligand atom A nbo:  -0.89557
Atom_a:  1 Atom_b:  5
C:\Users\George\Desktop\Research_UCLA\CIC\Computational Work\Project cluster version 2\project_catalyst_repurposing\structures_ligand_id\pd_me2_structures\ligand_xyz\ligand-297-p-o-109-ligand_xyz.txt
Starting node: 0
Ending node: 4
(-2.041437, -0.009997, 0.162276)   0
(-0.907876, 0.487711, 1.57379)   1
(0.500806, 0.435372, 1.46079)   2
(1.274606, -0.035792, -0.097505)   3
(0.936417, -1.444813, -0.35591)   4
ligand-298-p-o-110

C:\Users\George\AppData\Local\Temp\ipykernel_7832\386804788.py:583: DeprecationWarning:

to_plotly_figure is deprecated and will be removed in version 4.0.0. Use MolGraph.to_plotly() instead.

C:\Users\George\AppData\Local\Temp\ipykernel_7832\386804788.py:589: DeprecationWarning:

to_networkx_graph is deprecated and will be removed in version 4.0.0. Use MolGraph.to_networkx() instead.

Pd number index:  14
['P', 'C', 'C', 'S', 'O', 'O', 'C', 'C', 'C', 'C', 'H', 'H', 'H', 'H', 'Pd', 'C', 'H', 'H', 'H', 'C', 'H', 'H', 'H', 'N', 'C', 'C', 'C', 'H', 'C', 'H', 'H', 'C', 'H', 'H', 'C', 'H', 'H', 'H', 'H', 'H', 'H', 'C', 'C', 'C', 'H', 'C', 'H', 'H', 'C', 'H', 'H', 'C', 'H', 'H', 'H', 'H', 'H', 'H', 'C', 'H', 'C', 'H', 'C', 'H', 'H', 'H', 'C', 'H', 'H', 'H', 'C', 'H', 'H', 'H', 'C', 'H', 'H', 'H']
Ligand atom label:  1  Ligand atom B nbo:  0.88661
Ligand atom label:  5  Ligand atom A nbo:  -0.9003
Atom_a:  1 Atom_b:  5
C:\Users\George\Desktop\Research_UCLA\CIC\Computational Work\Project cluster version 2\project_catalyst_repurposing\structures_ligand_id\pd_me2_structures\ligand_xyz\ligand-298-p-o-110-ligand_xyz.txt
Starting node: 0
Ending node: 4
(-2.740534, 0.465176, -0.132033)   0
(-1.451551, 1.80928, -0.371818)   1
(-0.068941, 1.585562, -0.530044)   2
(0.659633, -0.060314, -0.412344)   3
(0.10666, -0.702602, 0.793502)   4
ligand-299-p-o-111
Pd number index:  14
['P', 'C', 'C', 'S', 'O', 'O', 'C', 'C', 'C', 'C', 'H', 'H', 'H', 'H', 'Pd', 'C', 'H', 'H', 'H', 'C', 'H', 'H', 'H', 'N', 'C', 'H', 'H', 'H', 'C', 'H', 'H', 'H', 'C', 'C', 'C', 'C', 'H', 'C', 'H', 'C', 'H', 'H', 'H', 'C', 'C', 'C', 'C', 'H', 'C', 'H', 'C', 'H', 'H', 'H']
Ligand atom label:  1  Ligand atom B nbo:  0.95142
Ligand atom label:  5  Ligand atom A nbo:  -0.89336
Atom_a:  1 Atom_b:  5

C:\Users\George\AppData\Local\Temp\ipykernel_7832\386804788.py:583: DeprecationWarning:

to_plotly_figure is deprecated and will be removed in version 4.0.0. Use MolGraph.to_plotly() instead.

C:\Users\George\AppData\Local\Temp\ipykernel_7832\386804788.py:589: DeprecationWarning:

to_networkx_graph is deprecated and will be removed in version 4.0.0. Use MolGraph.to_networkx() instead.

C:\Users\George\Desktop\Research_UCLA\CIC\Computational Work\Project cluster version 2\project_catalyst_repurposing\structures_ligand_id\pd_me2_structures\ligand_xyz\ligand-299-p-o-111-ligand_xyz.txt
Starting node: 0
Ending node: 4
(-0.849399, -0.055127, 0.027359)   0
(0.120426, -1.233776, -1.037064)   1
(1.531185, -1.237561, -1.029306)   2
(2.42443, -0.098795, 0.043308)   3
(2.174142, 1.263134, -0.460163)   4
ligand-300-p-o-112
Pd number index:  14
['P', 'C', 'C', 'S', 'O', 'O', 'C', 'C', 'C', 'C', 'H', 'H', 'H', 'H', 'Pd', 'C', 'H', 'H', 'H', 'C', 'H', 'H', 'H', 'N', 'C', 'H', 'H', 'H', 'C', 'H', 'H', 'H', 'C', 'H', 'C', 'H', 'H', 'H', 'C', 'H', 'H', 'H', 'C', 'H', 'C', 'H', 'H', 'H', 'C', 'H', 'H', 'H']
Ligand atom label:  1  Ligand atom B nbo:  0.88899
Ligand atom label:  5  Ligand atom A nbo:  -0.89395
Atom_a:  1 Atom_b:  5

C:\Users\George\AppData\Local\Temp\ipykernel_7832\386804788.py:583: DeprecationWarning:

to_plotly_figure is deprecated and will be removed in version 4.0.0. Use MolGraph.to_plotly() instead.

C:\Users\George\AppData\Local\Temp\ipykernel_7832\386804788.py:589: DeprecationWarning:

to_networkx_graph is deprecated and will be removed in version 4.0.0. Use MolGraph.to_networkx() instead.

C:\Users\George\Desktop\Research_UCLA\CIC\Computational Work\Project cluster version 2\project_catalyst_repurposing\structures_ligand_id\pd_me2_structures\ligand_xyz\ligand-300-p-o-112-ligand_xyz.txt
Starting node: 0
Ending node: 4
(1.088432, 0.939384, 0.067428)   0
(-0.611906, 1.688526, -0.215208)   1
(-1.824656, 0.980783, -0.110715)   2
(-1.824204, -0.770788, 0.298719)   3
(-0.965394, -1.450848, -0.686234)   4
ligand-301-p-o-113

C:\Users\George\AppData\Local\Temp\ipykernel_7832\386804788.py:583: DeprecationWarning:

to_plotly_figure is deprecated and will be removed in version 4.0.0. Use MolGraph.to_plotly() instead.

C:\Users\George\AppData\Local\Temp\ipykernel_7832\386804788.py:589: DeprecationWarning:

to_networkx_graph is deprecated and will be removed in version 4.0.0. Use MolGraph.to_networkx() instead.

Pd number index:  14
['P', 'C', 'C', 'S', 'O', 'O', 'C', 'C', 'C', 'C', 'H', 'H', 'H', 'H', 'Pd', 'C', 'H', 'H', 'H', 'C', 'H', 'H', 'H', 'C', 'H', 'H', 'O', 'N', 'C', 'H', 'H', 'N', 'C', 'C', 'C', 'C', 'H', 'C', 'H', 'C', 'H', 'H', 'H', 'C', 'C', 'C', 'C', 'H', 'C', 'H', 'C', 'H', 'H', 'H']
Ligand atom label:  1  Ligand atom B nbo:  1.2081
Ligand atom label:  5  Ligand atom A nbo:  -0.92709
Atom_a:  1 Atom_b:  5
C:\Users\George\Desktop\Research_UCLA\CIC\Computational Work\Project cluster version 2\project_catalyst_repurposing\structures_ligand_id\pd_me2_structures\ligand_xyz\ligand-301-p-o-113-ligand_xyz.txt
Starting node: 0
Ending node: 4
(0.063467, 0.585199, 0.055468)   0
(-0.375841, -0.313229, 1.627622)   1
(-0.528603, -1.70877, 1.680803)   2
(-0.085684, -2.837132, 0.31554)   3
(-0.782775, -2.282622, -0.896722)   4
ligand-302-p-o-114

C:\Users\George\AppData\Local\Temp\ipykernel_7832\386804788.py:583: DeprecationWarning:

to_plotly_figure is deprecated and will be removed in version 4.0.0. Use MolGraph.to_plotly() instead.

C:\Users\George\AppData\Local\Temp\ipykernel_7832\386804788.py:589: DeprecationWarning:

to_networkx_graph is deprecated and will be removed in version 4.0.0. Use MolGraph.to_networkx() instead.

Pd number index:  14
['P', 'C', 'C', 'S', 'O', 'O', 'C', 'C', 'C', 'C', 'H', 'H', 'H', 'H', 'Pd', 'C', 'H', 'H', 'H', 'C', 'H', 'H', 'H', 'C', 'H', 'H', 'O', 'N', 'C', 'H', 'H', 'N', 'C', 'C', 'C', 'C', 'C', 'H', 'C', 'H', 'H', 'H', 'C', 'C', 'C', 'C', 'H', 'C', 'C', 'H', 'H', 'H', 'C', 'H', 'H', 'H', 'C', 'H', 'H', 'H']
Ligand atom label:  1  Ligand atom B nbo:  1.18579
Ligand atom label:  5  Ligand atom A nbo:  -0.92546
Atom_a:  1 Atom_b:  5
C:\Users\George\Desktop\Research_UCLA\CIC\Computational Work\Project cluster version 2\project_catalyst_repurposing\structures_ligand_id\pd_me2_structures\ligand_xyz\ligand-302-p-o-114-ligand_xyz.txt
Starting node: 0
Ending node: 4
(-0.323089, 0.057676, 0.41711)   0
(-0.300976, -1.344576, -0.792897)   1
(0.541514, -1.299437, -1.915579)   2
(1.715229, 0.06497, -2.191845)   3
(0.85315, 1.293385, -2.283212)   4
ligand-303-p-o-115

C:\Users\George\AppData\Local\Temp\ipykernel_7832\386804788.py:583: DeprecationWarning:

to_plotly_figure is deprecated and will be removed in version 4.0.0. Use MolGraph.to_plotly() instead.

C:\Users\George\AppData\Local\Temp\ipykernel_7832\386804788.py:589: DeprecationWarning:

to_networkx_graph is deprecated and will be removed in version 4.0.0. Use MolGraph.to_networkx() instead.

Pd number index:  14
['P', 'C', 'C', 'S', 'O', 'O', 'C', 'C', 'C', 'C', 'H', 'H', 'H', 'H', 'Pd', 'C', 'H', 'H', 'H', 'C', 'H', 'H', 'H', 'C', 'H', 'H', 'O', 'N', 'C', 'H', 'H', 'N', 'C', 'C', 'C', 'C', 'C', 'H', 'C', 'H', 'H', 'H', 'C', 'C', 'C', 'C', 'H', 'C', 'C', 'H', 'H', 'H', 'O', 'O', 'C', 'H', 'H', 'H', 'C', 'H', 'H', 'H']
Ligand atom label:  1  Ligand atom B nbo:  1.21621
Ligand atom label:  5  Ligand atom A nbo:  -0.9269
Atom_a:  1 Atom_b:  5
C:\Users\George\Desktop\Research_UCLA\CIC\Computational Work\Project cluster version 2\project_catalyst_repurposing\structures_ligand_id\pd_me2_structures\ligand_xyz\ligand-303-p-o-115-ligand_xyz.txt
Starting node: 0
Ending node: 4
(-0.078286, -0.077714, 0.525081)   0
(0.801538, -1.641378, 1.037582)   1
(1.789147, -2.215186, 0.222087)   2
(2.27862, -1.455288, -1.350483)   3
(1.038734, -1.536662, -2.194268)   4
ligand-304-p-o-116

C:\Users\George\AppData\Local\Temp\ipykernel_7832\386804788.py:583: DeprecationWarning:

to_plotly_figure is deprecated and will be removed in version 4.0.0. Use MolGraph.to_plotly() instead.

C:\Users\George\AppData\Local\Temp\ipykernel_7832\386804788.py:589: DeprecationWarning:

to_networkx_graph is deprecated and will be removed in version 4.0.0. Use MolGraph.to_networkx() instead.

Pd number index:  14
['P', 'C', 'C', 'S', 'O', 'O', 'C', 'C', 'C', 'C', 'H', 'H', 'H', 'H', 'Pd', 'C', 'H', 'H', 'H', 'C', 'H', 'H', 'H', 'C', 'H', 'H', 'O', 'N', 'C', 'H', 'H', 'N', 'C', 'C', 'C', 'C', 'C', 'C', 'H', 'H', 'C', 'C', 'C', 'C', 'C', 'C', 'H', 'H', 'C', 'H', 'H', 'H', 'C', 'H', 'H', 'H', 'C', 'H', 'H', 'H', 'C', 'H', 'H', 'H', 'C', 'H', 'H', 'H', 'C', 'H', 'H', 'H']
Ligand atom label:  1  Ligand atom B nbo:  1.36137
Ligand atom label:  5  Ligand atom A nbo:  -0.94868
Atom_a:  1 Atom_b:  5
C:\Users\George\Desktop\Research_UCLA\CIC\Computational Work\Project cluster version 2\project_catalyst_repurposing\structures_ligand_id\pd_me2_structures\ligand_xyz\ligand-304-p-o-116-ligand_xyz.txt
Starting node: 0
Ending node: 4
(0.143164, 0.025997, -0.400829)   0
(-0.558787, 1.58453, -1.186261)   1
(-1.510119, 2.351928, -0.494117)   2
(-1.954345, 1.972464, 1.218922)   3
(-0.65405, 2.159311, 1.9498)   4
ligand-305-p-o-117

C:\Users\George\AppData\Local\Temp\ipykernel_7832\386804788.py:583: DeprecationWarning:

to_plotly_figure is deprecated and will be removed in version 4.0.0. Use MolGraph.to_plotly() instead.

C:\Users\George\AppData\Local\Temp\ipykernel_7832\386804788.py:589: DeprecationWarning:

to_networkx_graph is deprecated and will be removed in version 4.0.0. Use MolGraph.to_networkx() instead.

Pd number index:  14
['P', 'C', 'C', 'S', 'O', 'O', 'C', 'C', 'C', 'C', 'H', 'H', 'H', 'H', 'Pd', 'C', 'H', 'H', 'H', 'C', 'H', 'H', 'H', 'C', 'H', 'H', 'O', 'N', 'C', 'H', 'H', 'N', 'C', 'C', 'C', 'C', 'C', 'C', 'H', 'H', 'H', 'C', 'C', 'C', 'C', 'C', 'C', 'H', 'H', 'H', 'C', 'H', 'C', 'H', 'C', 'H', 'C', 'H', 'C', 'H', 'H', 'H', 'C', 'H', 'H', 'H', 'C', 'H', 'H', 'H', 'C', 'H', 'H', 'H', 'C', 'H', 'H', 'H', 'C', 'H', 'H', 'H', 'C', 'H', 'H', 'H', 'C', 'H', 'H', 'H']
Ligand atom label:  1  Ligand atom B nbo:  1.31738
Ligand atom label:  5  Ligand atom A nbo:  -0.89118
Atom_a:  1 Atom_b:  5
C:\Users\George\Desktop\Research_UCLA\CIC\Computational Work\Project cluster version 2\project_catalyst_repurposing\structures_ligand_id\pd_me2_structures\ligand_xyz\ligand-305-p-o-117-ligand_xyz.txt
Starting node: 0
Ending node: 4
(-0.048252, -0.035477, 0.225985)   0
(-0.55463, 0.142975, -1.556024)   1
(-0.039372, -0.67415, -2.572484)   2
(1.243526, -1.955321, -2.358651)   3
(2.053995, -1.493208, -1.177957)   4
ligand-306-p-o-118

C:\Users\George\AppData\Local\Temp\ipykernel_7832\386804788.py:583: DeprecationWarning:

to_plotly_figure is deprecated and will be removed in version 4.0.0. Use MolGraph.to_plotly() instead.

C:\Users\George\AppData\Local\Temp\ipykernel_7832\386804788.py:589: DeprecationWarning:

to_networkx_graph is deprecated and will be removed in version 4.0.0. Use MolGraph.to_networkx() instead.

Pd number index:  14
['P', 'C', 'C', 'S', 'O', 'O', 'C', 'C', 'C', 'C', 'H', 'H', 'H', 'H', 'Pd', 'C', 'H', 'H', 'H', 'C', 'H', 'H', 'H', 'C', 'H', 'H', 'O', 'N', 'C', 'H', 'H', 'N', 'C', 'C', 'C', 'C', 'C', 'C', 'H', 'H', 'H', 'C', 'C', 'C', 'C', 'C', 'C', 'H', 'H', 'H', 'C', 'C', 'C', 'C', 'H', 'C', 'H', 'C', 'H', 'H', 'C', 'C', 'C', 'C', 'H', 'C', 'H', 'C', 'H', 'H', 'C', 'C', 'C', 'C', 'H', 'C', 'H', 'C', 'H', 'H', 'C', 'C', 'C', 'C', 'H', 'C', 'H', 'C', 'H', 'H', 'C', 'H', 'H', 'H', 'C', 'H', 'H', 'H', 'C', 'H', 'H', 'H', 'C', 'H', 'H', 'H']
Ligand atom label:  1  Ligand atom B nbo:  1.35031
Ligand atom label:  5  Ligand atom A nbo:  -0.95052
Atom_a:  1 Atom_b:  5
C:\Users\George\Desktop\Research_UCLA\CIC\Computational Work\Project cluster version 2\project_catalyst_repurposing\structures_ligand_id\pd_me2_structures\ligand_xyz\ligand-306-p-o-118-ligand_xyz.txt
Starting node: 0
Ending node: 4
(0.154626, -0.074647, -0.093508)   0
(2.02425, 0.019358, 0.119777)   1
(2.845444, 0.333214, -0.975049)   2
(2.120105, 0.818222, -2.548292)   3
(1.560362, -0.452974, -3.117323)   4
ligand-307-n-n-25
Pd number index:  0
['Pd', 'C', 'C', 'N', 'N', 'C', 'H', 'H', 'H', 'C', 'C', 'C', 'C', 'C', 'C', 'H', 'H', 'H', 'C', 'C', 'C', 'H', 'H', 'H', 'H', 'H', 'H', 'H', 'C', 'C', 'C', 'H', 'H', 'H', 'H', 'H', 'H', 'H', 'C', 'C', 'C', 'C', 'C', 'C', 'H', 'H', 'H', 'C', 'H', 'H', 'H', 'C', 'H', 'C', 'H', 'H', 'H', 'C', 'H', 'H', 'H', 'C', 'H', 'C', 'H', 'H', 'H', 'C', 'H', 'H', 'H', 'C', 'H', 'H', 'H', 'C', 'H', 'H', 'H']

C:\Users\George\AppData\Local\Temp\ipykernel_7832\386804788.py:583: DeprecationWarning:

to_plotly_figure is deprecated and will be removed in version 4.0.0. Use MolGraph.to_plotly() instead.

C:\Users\George\AppData\Local\Temp\ipykernel_7832\386804788.py:589: DeprecationWarning:

to_networkx_graph is deprecated and will be removed in version 4.0.0. Use MolGraph.to_networkx() instead.

Ligand atom label:  4  Ligand atom A nbo:  -0.47397
Ligand atom label:  5  Ligand atom B nbo:  -0.47397
Atom_a:  4 Atom_b:  5
C:\Users\George\Desktop\Research_UCLA\CIC\Computational Work\Project cluster version 2\project_catalyst_repurposing\structures_ligand_id\pd_me2_structures\ligand_xyz\ligand-307-n-n-25-ligand_xyz.txt
Starting node: 2
Ending node: 3
(1.334852, 0.019618, 0.476449)   2
(0.747477, -0.043322, 1.617083)   0
(-0.747949, 0.043518, 1.616897)   1
(-1.335093, -0.019368, 0.476115)   3

C:\Users\George\AppData\Local\Temp\ipykernel_7832\386804788.py:583: DeprecationWarning:

to_plotly_figure is deprecated and will be removed in version 4.0.0. Use MolGraph.to_plotly() instead.

C:\Users\George\AppData\Local\Temp\ipykernel_7832\386804788.py:589: DeprecationWarning:

to_networkx_graph is deprecated and will be removed in version 4.0.0. Use MolGraph.to_networkx() instead.

ligand-308-n-n-26
Pd number index:  0
['Pd', 'C', 'C', 'N', 'N', 'C', 'C', 'C', 'C', 'C', 'C', 'H', 'H', 'H', 'C', 'C', 'C', 'H', 'H', 'H', 'H', 'H', 'H', 'H', 'C', 'C', 'C', 'H', 'H', 'H', 'H', 'H', 'H', 'H', 'C', 'C', 'C', 'C', 'C', 'C', 'H', 'H', 'H', 'C', 'H', 'C', 'H', 'H', 'H', 'C', 'H', 'H', 'H', 'C', 'H', 'C', 'H', 'H', 'H', 'C', 'H', 'H', 'H', 'C', 'H', 'H', 'H', 'C', 'H', 'H', 'H', 'H', 'H']
Ligand atom label:  4  Ligand atom A nbo:  -0.44988
Ligand atom label:  5  Ligand atom B nbo:  -0.44989
Atom_a:  4 Atom_b:  5
C:\Users\George\Desktop\Research_UCLA\CIC\Computational Work\Project cluster version 2\project_catalyst_repurposing\structures_ligand_id\pd_me2_structures\ligand_xyz\ligand-308-n-n-26-ligand_xyz.txt
Starting node: 2
Ending node: 3
(1.357597, -0.014612, -0.527339)   2
(0.73325, 0.014895, -1.642507)   0
(-0.733313, -0.015088, -1.642485)   1
(-1.357636, 0.014544, -0.527308)   3
ligand-309-n-n-27

C:\Users\George\AppData\Local\Temp\ipykernel_7832\386804788.py:583: DeprecationWarning:

to_plotly_figure is deprecated and will be removed in version 4.0.0. Use MolGraph.to_plotly() instead.

C:\Users\George\AppData\Local\Temp\ipykernel_7832\386804788.py:589: DeprecationWarning:

to_networkx_graph is deprecated and will be removed in version 4.0.0. Use MolGraph.to_networkx() instead.

Pd number index:  0
['Pd', 'C', 'C', 'N', 'N', 'C', 'C', 'C', 'C', 'C', 'C', 'H', 'H', 'H', 'C', 'C', 'C', 'H', 'H', 'H', 'H', 'H', 'H', 'H', 'C', 'C', 'C', 'H', 'H', 'H', 'H', 'H', 'H', 'H', 'C', 'C', 'C', 'C', 'C', 'C', 'H', 'H', 'H', 'C', 'H', 'C', 'H', 'H', 'H', 'C', 'H', 'H', 'H', 'C', 'H', 'C', 'H', 'H', 'H', 'C', 'H', 'H', 'H', 'C', 'H', 'H', 'H', 'C', 'H', 'H', 'H', 'C', 'C', 'C', 'C', 'C', 'C', 'H', 'C', 'C', 'C', 'H', 'C', 'H', 'H', 'H', 'H']
Ligand atom label:  4  Ligand atom B nbo:  -0.46207
Ligand atom label:  5  Ligand atom A nbo:  -0.46208
Atom_a:  4 Atom_b:  5
C:\Users\George\Desktop\Research_UCLA\CIC\Computational Work\Project cluster version 2\project_catalyst_repurposing\structures_ligand_id\pd_me2_structures\ligand_xyz\ligand-309-n-n-27-ligand_xyz.txt
Starting node: 2
Ending node: 3
(-1.378933, -0.338662, 0.024788)   2
(-0.750588, 0.77693, -0.012436)   0
(0.750411, 0.776976, 0.012613)   1
(1.378738, -0.338638, -0.024796)   3
ligand-310-p-o-119

C:\Users\George\AppData\Local\Temp\ipykernel_7832\386804788.py:583: DeprecationWarning:

to_plotly_figure is deprecated and will be removed in version 4.0.0. Use MolGraph.to_plotly() instead.

C:\Users\George\AppData\Local\Temp\ipykernel_7832\386804788.py:589: DeprecationWarning:

to_networkx_graph is deprecated and will be removed in version 4.0.0. Use MolGraph.to_networkx() instead.

Pd number index:  13
['P', 'C', 'C', 'S', 'O', 'O', 'O', 'C', 'C', 'C', 'C', 'H', 'H', 'Pd', 'C', 'H', 'H', 'H', 'C', 'H', 'H', 'H', 'C', 'C', 'C', 'H', 'C', 'H', 'C', 'H', 'H', 'C', 'H', 'H', 'H', 'H', 'H', 'C', 'C', 'C', 'H', 'C', 'H', 'C', 'H', 'H', 'C', 'H', 'H', 'H', 'H', 'H', 'C', 'H', 'H', 'H', 'C', 'H', 'C', 'H', 'H', 'H', 'C', 'H', 'H', 'H', 'C', 'H', 'H', 'H', 'C', 'H', 'C', 'H', 'H', 'H', 'C', 'H', 'H', 'H', 'Si', 'C', 'H', 'H', 'H', 'C', 'H', 'H', 'H', 'C', 'H', 'H', 'H', 'H']
Ligand atom label:  1  Ligand atom B nbo:  0.98013
Ligand atom label:  5  Ligand atom A nbo:  -0.91269
Atom_a:  1 Atom_b:  5
C:\Users\George\Desktop\Research_UCLA\CIC\Computational Work\Project cluster version 2\project_catalyst_repurposing\structures_ligand_id\pd_me2_structures\ligand_xyz\ligand-310-p-o-119-ligand_xyz.txt
Starting node: 0
Ending node: 4
(0.660592, -0.121045, -0.160194)   0
(-0.966681, -0.397604, -1.080672)   1
(-2.228497, -0.365848, -0.448093)   2
(-2.372351, -0.207007, 1.347621)   3
(-1.521538, -1.283705, 1.930505)   4
ligand-311-p-o-120

C:\Users\George\AppData\Local\Temp\ipykernel_7832\386804788.py:583: DeprecationWarning:

to_plotly_figure is deprecated and will be removed in version 4.0.0. Use MolGraph.to_plotly() instead.

C:\Users\George\AppData\Local\Temp\ipykernel_7832\386804788.py:589: DeprecationWarning:

to_networkx_graph is deprecated and will be removed in version 4.0.0. Use MolGraph.to_networkx() instead.

Pd number index:  13
['P', 'C', 'C', 'S', 'O', 'O', 'O', 'C', 'C', 'C', 'C', 'H', 'H', 'Pd', 'C', 'H', 'H', 'H', 'C', 'H', 'H', 'H', 'C', 'C', 'C', 'H', 'C', 'H', 'C', 'H', 'H', 'C', 'H', 'H', 'H', 'H', 'H', 'C', 'C', 'C', 'H', 'C', 'H', 'C', 'H', 'H', 'C', 'H', 'H', 'H', 'H', 'H', 'C', 'H', 'H', 'H', 'C', 'H', 'C', 'H', 'H', 'H', 'C', 'H', 'H', 'H', 'C', 'H', 'H', 'H', 'C', 'H', 'C', 'H', 'H', 'H', 'C', 'H', 'H', 'H', 'Si', 'C', 'H', 'H', 'H', 'C', 'C', 'C', 'C', 'H', 'C', 'H', 'C', 'H', 'H', 'H', 'C', 'C', 'C', 'C', 'H', 'C', 'H', 'C', 'H', 'H', 'H', 'H']
Ligand atom label:  1  Ligand atom B nbo:  0.97911
Ligand atom label:  5  Ligand atom A nbo:  -0.90397
Atom_a:  1 Atom_b:  5
C:\Users\George\Desktop\Research_UCLA\CIC\Computational Work\Project cluster version 2\project_catalyst_repurposing\structures_ligand_id\pd_me2_structures\ligand_xyz\ligand-311-p-o-120-ligand_xyz.txt
Starting node: 0
Ending node: 4
(-1.707164, 0.013592, 0.199143)   0
(0.030408, 0.398389, 0.83123)   1
(1.194333, 0.130248, 0.081689)   2
(1.108364, -0.761059, -1.483137)   3
(0.404122, -2.04079, -1.189656)   4
ligand-312-p-o-121

C:\Users\George\AppData\Local\Temp\ipykernel_7832\386804788.py:583: DeprecationWarning:

to_plotly_figure is deprecated and will be removed in version 4.0.0. Use MolGraph.to_plotly() instead.

C:\Users\George\AppData\Local\Temp\ipykernel_7832\386804788.py:589: DeprecationWarning:

to_networkx_graph is deprecated and will be removed in version 4.0.0. Use MolGraph.to_networkx() instead.

Pd number index:  13
['P', 'C', 'C', 'S', 'O', 'O', 'O', 'C', 'C', 'C', 'C', 'H', 'H', 'Pd', 'C', 'H', 'H', 'H', 'C', 'H', 'H', 'H', 'C', 'C', 'C', 'H', 'C', 'H', 'C', 'H', 'H', 'C', 'H', 'H', 'H', 'H', 'H', 'C', 'C', 'C', 'H', 'C', 'H', 'C', 'H', 'H', 'C', 'H', 'H', 'H', 'H', 'H', 'C', 'H', 'H', 'H', 'C', 'H', 'C', 'H', 'H', 'H', 'C', 'H', 'H', 'H', 'C', 'H', 'H', 'H', 'C', 'H', 'C', 'H', 'H', 'H', 'C', 'H', 'H', 'H', 'C', 'C', 'C', 'C', 'H', 'C', 'H', 'C', 'H', 'H', 'H', 'H']
Ligand atom label:  1  Ligand atom B nbo:  0.98244
Ligand atom label:  5  Ligand atom A nbo:  -0.9152
Atom_a:  1 Atom_b:  5
C:\Users\George\Desktop\Research_UCLA\CIC\Computational Work\Project cluster version 2\project_catalyst_repurposing\structures_ligand_id\pd_me2_structures\ligand_xyz\ligand-312-p-o-121-ligand_xyz.txt
Starting node: 0
Ending node: 4
(0.673837, -0.003477, -0.158725)   0
(-0.899536, 0.244863, -1.184554)   1
(-2.165652, 0.432819, -0.587876)   2
(-2.247974, 0.862566, 1.182561)   3
(-1.994708, -0.444107, 1.874119)   4

C:\Users\George\AppData\Local\Temp\ipykernel_7832\386804788.py:583: DeprecationWarning:

to_plotly_figure is deprecated and will be removed in version 4.0.0. Use MolGraph.to_plotly() instead.

C:\Users\George\AppData\Local\Temp\ipykernel_7832\386804788.py:589: DeprecationWarning:

to_networkx_graph is deprecated and will be removed in version 4.0.0. Use MolGraph.to_networkx() instead.

ligand-313-p-o-122
Pd number index:  13
['P', 'C', 'C', 'S', 'O', 'O', 'O', 'C', 'C', 'C', 'C', 'H', 'H', 'Pd', 'C', 'H', 'H', 'H', 'C', 'H', 'H', 'H', 'C', 'C', 'C', 'H', 'C', 'H', 'C', 'H', 'H', 'C', 'H', 'H', 'H', 'H', 'H', 'C', 'C', 'C', 'H', 'C', 'H', 'C', 'H', 'H', 'C', 'H', 'H', 'H', 'H', 'H', 'C', 'H', 'H', 'H', 'C', 'H', 'C', 'H', 'H', 'H', 'C', 'H', 'H', 'H', 'C', 'H', 'H', 'H', 'C', 'H', 'C', 'H', 'H', 'H', 'C', 'H', 'H', 'H', 'C', 'C', 'C', 'C', 'C', 'C', 'H', 'F', 'F', 'F', 'F', 'F']
Ligand atom label:  1  Ligand atom B nbo:  0.98224
Ligand atom label:  5  Ligand atom A nbo:  -0.90914
Atom_a:  1 Atom_b:  5
C:\Users\George\Desktop\Research_UCLA\CIC\Computational Work\Project cluster version 2\project_catalyst_repurposing\structures_ligand_id\pd_me2_structures\ligand_xyz\ligand-313-p-o-122-ligand_xyz.txt

C:\Users\George\AppData\Local\Temp\ipykernel_7832\386804788.py:583: DeprecationWarning:

to_plotly_figure is deprecated and will be removed in version 4.0.0. Use MolGraph.to_plotly() instead.

C:\Users\George\AppData\Local\Temp\ipykernel_7832\386804788.py:589: DeprecationWarning:

to_networkx_graph is deprecated and will be removed in version 4.0.0. Use MolGraph.to_networkx() instead.

Starting node: 0
Ending node: 4
(1.368505, -0.124769, -0.134726)   0
(-0.23312, -0.481841, -1.081804)   1
(-1.51249, -0.394005, -0.485901)   2
(-1.680356, -0.140711, 1.319524)   3
(-0.859363, -1.248795, 1.892908)   4
ligand-314-n-n-28
Pd number index:  0
['Pd', 'C', 'C', 'N', 'N', 'C', 'H', 'H', 'H', 'C', 'C', 'C', 'C', 'C', 'C', 'H', 'H', 'H', 'C', 'H', 'C', 'H', 'C', 'C', 'C', 'C', 'C', 'C', 'H', 'H', 'H', 'C', 'H', 'H', 'H', 'C', 'H', 'H', 'H', 'C', 'H', 'H', 'H', 'C', 'H', 'C', 'C', 'C', 'C', 'H', 'C', 'H', 'H', 'C', 'C', 'C', 'H', 'C', 'H', 'H', 'C', 'C', 'C', 'H', 'C', 'H', 'H', 'C', 'C', 'C', 'H', 'C', 'H', 'H', 'C', 'C', 'C', 'H', 'C', 'H', 'H', 'C', 'C', 'C', 'H', 'C', 'H', 'H', 'C', 'C', 'C', 'H', 'C', 'H', 'H', 'C', 'C', 'C', 'C', 'H', 'H', 'H', 'C', 'C', 'C', 'C', 'C', 'H', 'C', 'H', 'H', 'H', 'C', 'C', 'C', 'C', 'C', 'H', 'C', 'H', 'H', 'H', 'C', 'C', 'C', 'C', 'C', 'H', 'C', 'H', 'H', 'H', 'C', 'C', 'C', 'C', 'C', 'H', 'C', 'H', 'H', 'H', 'C', 'C', 'C', 'C', 'H', 'C', 'H', 'H', 'H', 'C', 'C', 'C', 'C', 'C', 'C', 'H', 'C', 'H', 'H', 'H', 'C', 'C', 'C', 'C', 'H', 'C', 'C', 'H', 'H', 'H', 'C', 'C', 'C', 'C', 'C', 'H', 'C', 'H', 'H', 'H', 'H']
Ligand atom label:  4  Ligand atom B nbo:  -0.50522
Ligand atom label:  5  Ligand atom A nbo:  -0.5077
Atom_a:  4 Atom_b:  5
C:\Users\George\Desktop\Research_UCLA\CIC\Computational Work\Project cluster version 2\project_catalyst_repurposing\structures_ligand_id\pd_me2_structures\ligand_xyz\ligand-314-n-n-28-ligand_xyz.txt
Starting node: 2
Ending node: 3
(0.222149, -0.817149, 1.221945)   2
(0.208899, -1.558577, 0.172907)   0
(0.036333, -0.847557, -1.136829)   1
(-0.150135, 0.421407, -1.063278)   3
ligand-315-n-n-29

C:\Users\George\AppData\Local\Temp\ipykernel_7832\386804788.py:583: DeprecationWarning:

to_plotly_figure is deprecated and will be removed in version 4.0.0. Use MolGraph.to_plotly() instead.

C:\Users\George\AppData\Local\Temp\ipykernel_7832\386804788.py:589: DeprecationWarning:

to_networkx_graph is deprecated and will be removed in version 4.0.0. Use MolGraph.to_networkx() instead.

Pd number index:  0
['Pd', 'C', 'C', 'N', 'N', 'C', 'H', 'H', 'H', 'C', 'C', 'C', 'C', 'C', 'C', 'H', 'H', 'H', 'C', 'H', 'C', 'H', 'C', 'C', 'C', 'C', 'C', 'C', 'H', 'H', 'H', 'C', 'H', 'H', 'H', 'C', 'H', 'C', 'H', 'C', 'H', 'H', 'H', 'C', 'H', 'H', 'H', 'C', 'C', 'H', 'C', 'C', 'H', 'C', 'C', 'H', 'C', 'C', 'H', 'C', 'C', 'H', 'C', 'C', 'H', 'C', 'C', 'H', 'C', 'C', 'H', 'S', 'C', 'C', 'C', 'C', 'H', 'C', 'C', 'H', 'H', 'H', 'S', 'C', 'C', 'C', 'C', 'H', 'C', 'C', 'H', 'H', 'H', 'S', 'S', 'S', 'S', 'S', 'S', 'C', 'C', 'C', 'C', 'C', 'H', 'C', 'H', 'H', 'H', 'C', 'C', 'C', 'C', 'H', 'C', 'C', 'H', 'H', 'H', 'C', 'C', 'C', 'C', 'H', 'C', 'C', 'H', 'H', 'H', 'C', 'C', 'C', 'C', 'H', 'C', 'C', 'H', 'H', 'H', 'C', 'C', 'C', 'C', 'C', 'H', 'C', 'H', 'H', 'H', 'C', 'C', 'C', 'C', 'H', 'C', 'C', 'H', 'H', 'H']
Ligand atom label:  4  Ligand atom A nbo:  -0.51763
Ligand atom label:  5  Ligand atom B nbo:  -0.50994
Atom_a:  5 Atom_b:  4
C:\Users\George\Desktop\Research_UCLA\CIC\Computational Work\Project cluster version 2\project_catalyst_repurposing\structures_ligand_id\pd_me2_structures\ligand_xyz\ligand-315-n-n-29-ligand_xyz.txt
Ending node: 2
Starting node: 3
(0.465361, 0.756632, -1.11445)   3
(0.528652, 1.486638, -0.055326)   1
(0.385868, 0.780865, 1.267583)   0
(0.445817, -0.505674, 1.273943)   2
ligand-316-p-o-123

C:\Users\George\AppData\Local\Temp\ipykernel_7832\386804788.py:583: DeprecationWarning:

to_plotly_figure is deprecated and will be removed in version 4.0.0. Use MolGraph.to_plotly() instead.

C:\Users\George\AppData\Local\Temp\ipykernel_7832\386804788.py:589: DeprecationWarning:

to_networkx_graph is deprecated and will be removed in version 4.0.0. Use MolGraph.to_networkx() instead.

Pd number index:  14
['P', 'C', 'C', 'S', 'O', 'O', 'O', 'C', 'C', 'C', 'C', 'H', 'H', 'H', 'Pd', 'C', 'H', 'H', 'H', 'C', 'H', 'H', 'H', 'C', 'C', 'H', 'H', 'H', 'C', 'H', 'H', 'H', 'C', 'H', 'H', 'H', 'C', 'C', 'C', 'C', 'C', 'C', 'H', 'H', 'H', 'O', 'O', 'O', 'C', 'H', 'H', 'H', 'C', 'H', 'H', 'H', 'C', 'H', 'H', 'H']
Ligand atom label:  1  Ligand atom B nbo:  1.02361
Ligand atom label:  5  Ligand atom A nbo:  -0.93938
Atom_a:  1 Atom_b:  5
C:\Users\George\Desktop\Research_UCLA\CIC\Computational Work\Project cluster version 2\project_catalyst_repurposing\structures_ligand_id\pd_me2_structures\ligand_xyz\ligand-316-p-o-123-ligand_xyz.txt
Starting node: 0
Ending node: 4
(0.689334, 0.038172, 0.987235)   0
(1.094769, 1.637879, 0.135221)   1
(0.882261, 1.778031, -1.253095)   2
(-0.11745, 0.662724, -2.295482)   3
(0.08839, -0.727098, -1.765592)   4
ligand-317-n-n-30

C:\Users\George\AppData\Local\Temp\ipykernel_7832\386804788.py:583: DeprecationWarning:

to_plotly_figure is deprecated and will be removed in version 4.0.0. Use MolGraph.to_plotly() instead.

C:\Users\George\AppData\Local\Temp\ipykernel_7832\386804788.py:589: DeprecationWarning:

to_networkx_graph is deprecated and will be removed in version 4.0.0. Use MolGraph.to_networkx() instead.

Pd number index:  0
['Pd', 'C', 'C', 'N', 'N', 'C', 'C', 'C', 'C', 'C', 'C', 'H', 'H', 'C', 'C', 'C', 'C', 'C', 'C', 'H', 'H', 'C', 'H', 'H', 'H', 'C', 'H', 'H', 'H', 'C', 'H', 'H', 'H', 'H', 'C', 'H', 'H', 'H', 'H', 'C', 'H', 'H', 'H', 'C', 'H', 'H', 'H', 'H', 'H']
Ligand atom label:  4  Ligand atom A nbo:  -0.45023
Ligand atom label:  5  Ligand atom B nbo:  -0.45024
Atom_a:  4 Atom_b:  5
C:\Users\George\Desktop\Research_UCLA\CIC\Computational Work\Project cluster version 2\project_catalyst_repurposing\structures_ligand_id\pd_me2_structures\ligand_xyz\ligand-317-n-n-30-ligand_xyz.txt

C:\Users\George\AppData\Local\Temp\ipykernel_7832\386804788.py:583: DeprecationWarning:

to_plotly_figure is deprecated and will be removed in version 4.0.0. Use MolGraph.to_plotly() instead.

C:\Users\George\AppData\Local\Temp\ipykernel_7832\386804788.py:589: DeprecationWarning:

to_networkx_graph is deprecated and will be removed in version 4.0.0. Use MolGraph.to_networkx() instead.

Starting node: 2
Ending node: 3
(1.355495, -0.771534, 0.025033)   2
(0.729754, -1.890658, -0.012016)   0
(-0.729757, -1.890657, 0.011941)   1
(-1.355498, -0.771532, -0.025052)   3
ligand-318-n-n-31
Pd number index:  0
['Pd', 'C', 'C', 'N', 'N', 'C', 'C', 'C', 'C', 'C', 'C', 'H', 'H', 'H', 'C', 'C', 'C', 'C', 'C', 'C', 'H', 'H', 'H', 'C', 'H', 'H', 'H', 'C', 'H', 'H', 'H', 'C', 'H', 'H', 'H', 'C', 'H', 'H', 'H', 'C', 'H', 'H', 'H', 'C', 'H', 'H', 'H', 'H', 'H']
Ligand atom label:  4  Ligand atom A nbo:  -0.45025
Ligand atom label:  5  Ligand atom B nbo:  -0.45033
Atom_a:  4 Atom_b:  5
C:\Users\George\Desktop\Research_UCLA\CIC\Computational Work\Project cluster version 2\project_catalyst_repurposing\structures_ligand_id\pd_me2_structures\ligand_xyz\ligand-318-n-n-31-ligand_xyz.txt
Starting node: 2
Ending node: 3
(1.336438, 0.26913, -0.674543)   2
(0.732267, 0.819936, -1.660216)   0
(-0.732234, 0.817227, -1.66288)   1
(-1.337916, 0.259978, -0.681605)   3
ligand-319-n-n-32

C:\Users\George\AppData\Local\Temp\ipykernel_7832\386804788.py:583: DeprecationWarning:

to_plotly_figure is deprecated and will be removed in version 4.0.0. Use MolGraph.to_plotly() instead.

C:\Users\George\AppData\Local\Temp\ipykernel_7832\386804788.py:589: DeprecationWarning:

to_networkx_graph is deprecated and will be removed in version 4.0.0. Use MolGraph.to_networkx() instead.

Pd number index:  0
['Pd', 'C', 'C', 'N', 'N', 'C', 'C', 'C', 'C', 'C', 'C', 'H', 'H', 'C', 'C', 'C', 'C', 'C', 'C', 'H', 'H', 'C', 'H', 'H', 'H', 'C', 'H', 'H', 'H', 'C', 'H', 'H', 'C', 'C', 'H', 'H', 'H', 'C', 'H', 'H', 'H', 'C', 'H', 'H', 'H', 'C', 'H', 'H', 'H', 'C', 'H', 'H', 'H', 'C', 'H', 'H', 'H', 'H', 'H', 'H', 'H']
Ligand atom label:  4  Ligand atom A nbo:  -0.44849
Ligand atom label:  5  Ligand atom B nbo:  -0.4485
Atom_a:  4 Atom_b:  5
C:\Users\George\Desktop\Research_UCLA\CIC\Computational Work\Project cluster version 2\project_catalyst_repurposing\structures_ligand_id\pd_me2_structures\ligand_xyz\ligand-319-n-n-32-ligand_xyz.txt
Starting node: 2
Ending node: 3
(1.316283, 0.306349, -0.58408)   2
(0.696953, 0.224966, -1.7009)   0
(-0.696949, -0.225009, -1.700913)   1
(-1.316309, -0.306361, -0.58411)   3
ligand-320-n-n-33

C:\Users\George\AppData\Local\Temp\ipykernel_7832\386804788.py:583: DeprecationWarning:

to_plotly_figure is deprecated and will be removed in version 4.0.0. Use MolGraph.to_plotly() instead.

C:\Users\George\AppData\Local\Temp\ipykernel_7832\386804788.py:589: DeprecationWarning:

to_networkx_graph is deprecated and will be removed in version 4.0.0. Use MolGraph.to_networkx() instead.

Pd number index:  0
['Pd', 'C', 'C', 'N', 'N', 'C', 'C', 'C', 'C', 'C', 'C', 'H', 'H', 'C', 'C', 'C', 'C', 'C', 'C', 'H', 'H', 'C', 'H', 'H', 'H', 'C', 'H', 'H', 'H', 'C', 'H', 'H', 'H', 'H', 'C', 'H', 'H', 'H', 'H', 'C', 'H', 'H', 'H', 'C', 'H', 'H', 'H', 'C', 'H', 'H', 'H', 'C', 'H', 'H', 'H']
Ligand atom label:  4  Ligand atom A nbo:  -0.46309
Ligand atom label:  5  Ligand atom B nbo:  -0.46547
Atom_a:  4 Atom_b:  5
C:\Users\George\Desktop\Research_UCLA\CIC\Computational Work\Project cluster version 2\project_catalyst_repurposing\structures_ligand_id\pd_me2_structures\ligand_xyz\ligand-320-n-n-33-ligand_xyz.txt

C:\Users\George\AppData\Local\Temp\ipykernel_7832\386804788.py:583: DeprecationWarning:

to_plotly_figure is deprecated and will be removed in version 4.0.0. Use MolGraph.to_plotly() instead.

C:\Users\George\AppData\Local\Temp\ipykernel_7832\386804788.py:589: DeprecationWarning:

to_networkx_graph is deprecated and will be removed in version 4.0.0. Use MolGraph.to_networkx() instead.

Starting node: 2
Ending node: 3
(1.319873, 0.685541, -0.025008)   2
(0.747373, 1.833065, 0.079718)   0
(-0.746121, 1.834177, 0.080596)   1
(-1.320113, 0.684359, 0.008764)   3
ligand-321-n-n-34
Pd number index:  0
['Pd', 'C', 'C', 'N', 'N', 'C', 'C', 'C', 'C', 'C', 'C', 'H', 'H', 'H', 'C', 'C', 'C', 'C', 'C', 'C', 'H', 'H', 'H', 'C', 'H', 'H', 'H', 'C', 'H', 'H', 'H', 'C', 'H', 'H', 'H', 'C', 'H', 'H', 'H', 'C', 'H', 'H', 'H', 'C', 'H', 'H', 'H', 'C', 'H', 'H', 'H', 'C', 'H', 'H', 'H']
Ligand atom label:  4  Ligand atom B nbo:  -0.47757
Ligand atom label:  5  Ligand atom A nbo:  -0.47057
Atom_a:  5 Atom_b:  4
C:\Users\George\Desktop\Research_UCLA\CIC\Computational Work\Project cluster version 2\project_catalyst_repurposing\structures_ligand_id\pd_me2_structures\ligand_xyz\ligand-321-n-n-34-ligand_xyz.txt
Ending node: 2
Starting node: 3
(1.315055, 0.567357, -0.030799)   3
(0.746588, 1.719644, -0.044534)   1
(-0.746911, 1.719482, -0.049219)   0
(-1.315238, 0.567306, -0.024169)   2
ligand-322-n-n-35

C:\Users\George\AppData\Local\Temp\ipykernel_7832\386804788.py:583: DeprecationWarning:

to_plotly_figure is deprecated and will be removed in version 4.0.0. Use MolGraph.to_plotly() instead.

C:\Users\George\AppData\Local\Temp\ipykernel_7832\386804788.py:589: DeprecationWarning:

to_networkx_graph is deprecated and will be removed in version 4.0.0. Use MolGraph.to_networkx() instead.

Pd number index:  0
['Pd', 'C', 'C', 'N', 'N', 'C', 'C', 'C', 'C', 'C', 'C', 'H', 'H', 'C', 'C', 'C', 'C', 'C', 'C', 'H', 'H', 'C', 'H', 'H', 'H', 'C', 'H', 'H', 'H', 'C', 'H', 'H', 'C', 'C', 'H', 'H', 'H', 'C', 'H', 'H', 'H', 'C', 'H', 'H', 'H', 'C', 'H', 'H', 'H', 'C', 'H', 'H', 'H', 'C', 'H', 'H', 'H', 'H', 'H', 'C', 'H', 'H', 'H', 'C', 'H', 'H', 'H']
Ligand atom label:  4  Ligand atom A nbo:  -0.47104
Ligand atom label:  5  Ligand atom B nbo:  -0.47105
Atom_a:  4 Atom_b:  5
C:\Users\George\Desktop\Research_UCLA\CIC\Computational Work\Project cluster version 2\project_catalyst_repurposing\structures_ligand_id\pd_me2_structures\ligand_xyz\ligand-322-n-n-35-ligand_xyz.txt
Starting node: 2
Ending node: 3
(-1.301702, 0.281512, 0.470588)   2
(-0.697631, 0.266714, 1.603414)   0
(0.697626, -0.267508, 1.603273)   1
(1.301692, -0.281733, 0.470438)   3
ligand-323-n-n-36

C:\Users\George\AppData\Local\Temp\ipykernel_7832\386804788.py:583: DeprecationWarning:

to_plotly_figure is deprecated and will be removed in version 4.0.0. Use MolGraph.to_plotly() instead.

C:\Users\George\AppData\Local\Temp\ipykernel_7832\386804788.py:589: DeprecationWarning:

to_networkx_graph is deprecated and will be removed in version 4.0.0. Use MolGraph.to_networkx() instead.

Pd number index:  0
['Pd', 'C', 'C', 'N', 'N', 'C', 'C', 'C', 'C', 'C', 'C', 'H', 'H', 'C', 'C', 'C', 'C', 'C', 'C', 'H', 'H', 'C', 'H', 'H', 'H', 'C', 'H', 'H', 'H', 'C', 'C', 'C', 'C', 'C', 'C', 'H', 'C', 'C', 'C', 'H', 'C', 'H', 'H', 'H', 'H', 'C', 'H', 'H', 'H', 'C', 'H', 'H', 'H', 'H', 'C', 'H', 'H', 'H', 'C', 'H', 'H', 'H', 'H']
Ligand atom label:  4  Ligand atom B nbo:  -0.4547
Ligand atom label:  5  Ligand atom A nbo:  -0.4547
Atom_a:  5 Atom_b:  4
C:\Users\George\Desktop\Research_UCLA\CIC\Computational Work\Project cluster version 2\project_catalyst_repurposing\structures_ligand_id\pd_me2_structures\ligand_xyz\ligand-323-n-n-36-ligand_xyz.txt
Ending node: 2
Starting node: 3
(1.364617, -0.422545, 0.051685)   3
(0.747544, 0.700605, 0.023119)   1
(-0.747549, 0.700603, -0.023137)   0
(-1.364619, -0.422548, -0.051705)   2
ligand-324-n-n-37

C:\Users\George\AppData\Local\Temp\ipykernel_7832\386804788.py:583: DeprecationWarning:

to_plotly_figure is deprecated and will be removed in version 4.0.0. Use MolGraph.to_plotly() instead.

C:\Users\George\AppData\Local\Temp\ipykernel_7832\386804788.py:589: DeprecationWarning:

to_networkx_graph is deprecated and will be removed in version 4.0.0. Use MolGraph.to_networkx() instead.

Pd number index:  0
['Pd', 'C', 'C', 'N', 'N', 'C', 'C', 'C', 'C', 'C', 'C', 'H', 'H', 'C', 'C', 'C', 'C', 'C', 'C', 'H', 'H', 'C', 'H', 'H', 'H', 'C', 'H', 'H', 'H', 'C', 'C', 'C', 'C', 'C', 'C', 'H', 'C', 'C', 'C', 'H', 'C', 'H', 'H', 'H', 'H', 'C', 'H', 'H', 'H', 'C', 'H', 'H', 'H', 'C', 'H', 'H', 'H', 'C', 'H', 'H', 'H', 'H', 'H']
Ligand atom label:  4  Ligand atom A nbo:  -0.46018
Ligand atom label:  5  Ligand atom B nbo:  -0.45358
Atom_a:  5 Atom_b:  4
C:\Users\George\Desktop\Research_UCLA\CIC\Computational Work\Project cluster version 2\project_catalyst_repurposing\structures_ligand_id\pd_me2_structures\ligand_xyz\ligand-324-n-n-37-ligand_xyz.txt
Ending node: 2
Starting node: 3
(-1.366459, -0.443849, -0.03837)   3
(-0.747752, 0.678153, -0.045648)   1
(0.748067, 0.677574, -0.043414)   0
(1.365808, -0.444977, -0.036052)   2
ligand-325-n-n-38

C:\Users\George\AppData\Local\Temp\ipykernel_7832\386804788.py:583: DeprecationWarning:

to_plotly_figure is deprecated and will be removed in version 4.0.0. Use MolGraph.to_plotly() instead.

C:\Users\George\AppData\Local\Temp\ipykernel_7832\386804788.py:589: DeprecationWarning:

to_networkx_graph is deprecated and will be removed in version 4.0.0. Use MolGraph.to_networkx() instead.

Pd number index:  0
['Pd', 'C', 'C', 'N', 'N', 'C', 'C', 'C', 'C', 'C', 'C', 'H', 'H', 'C', 'C', 'C', 'C', 'C', 'C', 'H', 'H', 'C', 'H', 'H', 'H', 'C', 'H', 'H', 'H', 'C', 'C', 'C', 'C', 'C', 'C', 'H', 'C', 'C', 'C', 'H', 'C', 'H', 'H', 'H', 'H', 'C', 'C', 'H', 'H', 'C', 'H', 'H', 'H', 'C', 'H', 'H', 'H', 'C', 'H', 'H', 'H', 'C', 'H', 'H', 'H', 'C', 'H', 'H', 'H', 'H', 'H', 'C', 'H', 'H', 'H']
Ligand atom label:  4  Ligand atom A nbo:  -0.45628
Ligand atom label:  5  Ligand atom B nbo:  -0.45628
Atom_a:  4 Atom_b:  5
C:\Users\George\Desktop\Research_UCLA\CIC\Computational Work\Project cluster version 2\project_catalyst_repurposing\structures_ligand_id\pd_me2_structures\ligand_xyz\ligand-325-n-n-38-ligand_xyz.txt

C:\Users\George\AppData\Local\Temp\ipykernel_7832\386804788.py:583: DeprecationWarning:

to_plotly_figure is deprecated and will be removed in version 4.0.0. Use MolGraph.to_plotly() instead.

C:\Users\George\AppData\Local\Temp\ipykernel_7832\386804788.py:589: DeprecationWarning:

to_networkx_graph is deprecated and will be removed in version 4.0.0. Use MolGraph.to_networkx() instead.

Starting node: 2
Ending node: 3
(-1.344183, 0.403128, -0.293368)   2
(-0.719337, -0.712533, -0.20978)   0
(0.719142, -0.712686, 0.209183)   1
(1.34416, 0.40286, 0.293041)   3
ligand-326-n-n-39
Pd number index:  0
['Pd', 'N', 'N', 'C', 'C', 'C', 'C', 'C', 'C', 'H', 'H', 'C', 'C', 'C', 'C', 'C', 'C', 'H', 'H', 'C', 'H', 'H', 'H', 'C', 'H', 'H', 'H', 'C', 'C', 'C', 'C', 'H', 'H', 'C', 'C', 'H', 'H', 'H', 'H', 'H', 'H', 'C', 'H', 'H', 'H', 'C', 'H', 'H', 'H', 'H', 'H', 'C', 'H', 'H', 'H', 'C', 'H', 'H', 'H']
Ligand atom label:  2  Ligand atom B nbo:  -0.46761
Ligand atom label:  3  Ligand atom A nbo:  -0.4637
Atom_a:  3 Atom_b:  2
C:\Users\George\Desktop\Research_UCLA\CIC\Computational Work\Project cluster version 2\project_catalyst_repurposing\structures_ligand_id\pd_me2_structures\ligand_xyz\ligand-326-n-n-39-ligand_xyz.txt
Ending node: 0
Starting node: 1
(-1.314969, 0.376753, -0.199395)   1
(-0.748249, 1.530761, -0.146533)   20
(0.742597, 1.531297, -0.129601)   18
(1.31196, 0.377038, -0.140487)   0
ligand-327-n-n-40
Pd number index:  0
['Pd', 'N', 'N', 'C', 'C', 'C', 'C', 'C', 'C', 'H', 'H', 'C', 'C', 'C', 'C', 'C', 'C', 'H', 'H', 'C', 'H', 'H', 'H', 'C', 'H', 'H', 'H', 'H', 'H', 'C', 'C', 'C', 'C', 'H', 'H', 'C', 'C', 'H', 'H', 'H', 'H', 'H', 'H', 'C', 'H', 'H', 'H', 'C', 'H', 'H', 'H', 'C', 'H', 'H', 'H', 'C', 'H', 'H', 'H']
Ligand atom label:  2  Ligand atom B nbo:  -0.47192
Ligand atom label:  3  Ligand atom A nbo:  -0.47021
Atom_a:  3 Atom_b:  2

C:\Users\George\AppData\Local\Temp\ipykernel_7832\386804788.py:583: DeprecationWarning:

to_plotly_figure is deprecated and will be removed in version 4.0.0. Use MolGraph.to_plotly() instead.

C:\Users\George\AppData\Local\Temp\ipykernel_7832\386804788.py:589: DeprecationWarning:

to_networkx_graph is deprecated and will be removed in version 4.0.0. Use MolGraph.to_networkx() instead.

C:\Users\George\Desktop\Research_UCLA\CIC\Computational Work\Project cluster version 2\project_catalyst_repurposing\structures_ligand_id\pd_me2_structures\ligand_xyz\ligand-327-n-n-40-ligand_xyz.txt
Ending node: 0
Starting node: 1
(-1.312844, 0.292784, -0.049366)   1
(-0.746557, 1.447103, -0.028905)   22
(0.744532, 1.447939, -0.034963)   20
(1.311801, 0.294483, -7.3e-05)   0
ligand-328-n-n-41
Pd number index:  0
['Pd', 'N', 'N', 'C', 'C', 'C', 'C', 'C', 'C', 'H', 'H', 'C', 'C', 'C', 'C', 'C', 'C', 'H', 'H', 'C', 'H', 'H', 'H', 'C', 'H', 'H', 'H', 'C', 'C', 'H', 'H', 'C', 'H', 'H', 'C', 'H', 'H', 'H', 'C', 'H', 'H', 'H', 'C', 'H', 'H', 'H', 'C', 'C', 'C', 'C', 'H', 'H', 'C', 'C', 'H', 'H', 'H', 'H', 'H', 'H', 'H', 'C', 'H', 'C', 'H', 'H', 'H', 'C', 'H', 'H', 'H', 'H', 'C', 'H', 'C', 'H', 'H', 'H', 'C', 'H', 'H', 'H', 'H']

C:\Users\George\AppData\Local\Temp\ipykernel_7832\386804788.py:583: DeprecationWarning:

to_plotly_figure is deprecated and will be removed in version 4.0.0. Use MolGraph.to_plotly() instead.

C:\Users\George\AppData\Local\Temp\ipykernel_7832\386804788.py:589: DeprecationWarning:

to_networkx_graph is deprecated and will be removed in version 4.0.0. Use MolGraph.to_networkx() instead.

Ligand atom label:  2  Ligand atom A nbo:  -0.47716
Ligand atom label:  3  Ligand atom B nbo:  -0.48067
Atom_a:  2 Atom_b:  3
C:\Users\George\Desktop\Research_UCLA\CIC\Computational Work\Project cluster version 2\project_catalyst_repurposing\structures_ligand_id\pd_me2_structures\ligand_xyz\ligand-328-n-n-41-ligand_xyz.txt
Starting node: 0
Ending node: 1
(1.263389, -0.176846, 0.325524)   0
(0.692823, 0.205964, 1.410933)   37
(-0.799747, 0.196847, 1.41884)   39
(-1.376936, 0.060725, 0.278107)   1

C:\Users\George\AppData\Local\Temp\ipykernel_7832\386804788.py:583: DeprecationWarning:

to_plotly_figure is deprecated and will be removed in version 4.0.0. Use MolGraph.to_plotly() instead.

C:\Users\George\AppData\Local\Temp\ipykernel_7832\386804788.py:589: DeprecationWarning:

to_networkx_graph is deprecated and will be removed in version 4.0.0. Use MolGraph.to_networkx() instead.

ligand-329-n-n-42
Pd number index:  0
['Pd', 'N', 'N', 'C', 'C', 'C', 'C', 'C', 'C', 'H', 'H', 'C', 'C', 'C', 'C', 'C', 'C', 'H', 'H', 'C', 'H', 'H', 'H', 'C', 'H', 'H', 'H', 'C', 'C', 'H', 'H', 'C', 'H', 'H', 'C', 'H', 'H', 'H', 'C', 'H', 'H', 'H', 'C', 'H', 'H', 'H', 'C', 'H', 'H', 'H', 'H', 'H', 'C', 'H', 'H', 'H', 'C', 'C', 'C', 'C', 'H', 'H', 'C', 'C', 'H', 'H', 'H', 'H', 'H', 'H', 'H']
Ligand atom label:  2  Ligand atom B nbo:  -0.46549
Ligand atom label:  3  Ligand atom A nbo:  -0.46804
Atom_a:  2 Atom_b:  3
C:\Users\George\Desktop\Research_UCLA\CIC\Computational Work\Project cluster version 2\project_catalyst_repurposing\structures_ligand_id\pd_me2_structures\ligand_xyz\ligand-329-n-n-42-ligand_xyz.txt
Starting node: 0
Ending node: 1
(1.321411, 0.247907, -0.244727)   0
(0.731693, 1.38994, -0.278889)   47
(-0.672069, 1.427015, 0.221372)   49
(-1.249649, 0.289932, 0.365276)   1
ligand-330-p-o-124
Pd number index:  2
['P', 'C', 'Pd', 'C', 'H', 'H', 'H', 'C', 'H', 'H', 'H', 'C', 'C', 'C', 'H', 'H', 'H', 'C', 'H', 'H', 'H', 'C', 'H', 'H', 'H', 'C', 'H', 'H', 'H', 'C', 'H', 'H', 'H', 'C', 'H', 'H', 'H', 'O', 'H', 'H', 'C', 'C', 'C', 'C', 'C', 'H', 'C', 'H', 'C', 'H', 'H', 'H']
Ligand atom label:  1  Ligand atom B nbo:  1.01541
Ligand atom label:  38  Ligand atom A nbo:  -0.46578
Atom_a:  1 Atom_b:  38

C:\Users\George\AppData\Local\Temp\ipykernel_7832\386804788.py:583: DeprecationWarning:

to_plotly_figure is deprecated and will be removed in version 4.0.0. Use MolGraph.to_plotly() instead.

C:\Users\George\AppData\Local\Temp\ipykernel_7832\386804788.py:589: DeprecationWarning:

to_networkx_graph is deprecated and will be removed in version 4.0.0. Use MolGraph.to_networkx() instead.

C:\Users\George\Desktop\Research_UCLA\CIC\Computational Work\Project cluster version 2\project_catalyst_repurposing\structures_ligand_id\pd_me2_structures\ligand_xyz\ligand-330-p-o-124-ligand_xyz.txt
Starting node: 0
Ending node: 28
(0.967629, 0.741733, -0.016821)   0
(-0.634899, 0.78115, -0.995357)   1
(-1.533718, -0.344526, -0.55929)   31
(-1.046286, -1.442354, -0.317474)   28
ligand-331-n-n-104

C:\Users\George\AppData\Local\Temp\ipykernel_7832\386804788.py:583: DeprecationWarning:

to_plotly_figure is deprecated and will be removed in version 4.0.0. Use MolGraph.to_plotly() instead.

C:\Users\George\AppData\Local\Temp\ipykernel_7832\386804788.py:589: DeprecationWarning:

to_networkx_graph is deprecated and will be removed in version 4.0.0. Use MolGraph.to_networkx() instead.

Pd number index:  0
['Pd', 'C', 'C', 'N', 'N', 'C', 'H', 'H', 'H', 'C', 'C', 'C', 'C', 'C', 'C', 'H', 'H', 'C', 'H', 'C', 'H', 'C', 'C', 'C', 'C', 'C', 'C', 'H', 'H', 'C', 'H', 'H', 'H', 'C', 'H', 'C', 'H', 'C', 'H', 'H', 'H', 'C', 'H', 'H', 'H', 'C', 'C', 'C', 'C', 'H', 'C', 'H', 'C', 'H', 'H', 'H', 'C', 'C', 'C', 'C', 'H', 'C', 'H', 'C', 'H', 'H', 'H', 'C', 'C', 'C', 'C', 'H', 'C', 'H', 'C', 'H', 'H', 'H', 'C', 'C', 'C', 'C', 'H', 'C', 'H', 'C', 'H', 'H', 'H', 'C', 'C', 'C', 'C', 'H', 'C', 'H', 'C', 'H', 'H', 'H', 'C', 'C', 'C', 'C', 'H', 'C', 'H', 'C', 'H', 'H', 'H', 'C', 'C', 'C', 'C', 'H', 'C', 'H', 'C', 'H', 'H', 'H', 'C', 'C', 'C', 'C', 'H', 'C', 'H', 'C', 'H', 'H', 'H', 'C', 'H', 'H', 'H', 'C', 'H', 'H', 'H']
Ligand atom label:  4  Ligand atom B nbo:  -0.49902
Ligand atom label:  5  Ligand atom A nbo:  -0.49902
Atom_a:  5 Atom_b:  4
C:\Users\George\Desktop\Research_UCLA\CIC\Computational Work\Project cluster version 2\project_catalyst_repurposing\structures_ligand_id\pd_me2_structures\ligand_xyz\ligand-331-n-n-104-ligand_xyz.txt
Ending node: 2
Starting node: 3
(-0.251474, 1.282062, 0.400947)   3
(-0.219992, 0.710763, 1.553123)   1
(0.222696, -0.711328, 1.553147)   0
(0.253693, -1.282868, 0.401048)   2
ligand-332-n-n-105

C:\Users\George\AppData\Local\Temp\ipykernel_7832\386804788.py:583: DeprecationWarning:

to_plotly_figure is deprecated and will be removed in version 4.0.0. Use MolGraph.to_plotly() instead.

C:\Users\George\AppData\Local\Temp\ipykernel_7832\386804788.py:589: DeprecationWarning:

to_networkx_graph is deprecated and will be removed in version 4.0.0. Use MolGraph.to_networkx() instead.

Pd number index:  0
['Pd', 'C', 'C', 'N', 'N', 'C', 'H', 'H', 'H', 'C', 'C', 'C', 'C', 'C', 'C', 'H', 'H', 'C', 'H', 'C', 'H', 'C', 'C', 'C', 'C', 'C', 'C', 'H', 'H', 'C', 'H', 'H', 'H', 'C', 'H', 'C', 'H', 'C', 'H', 'H', 'H', 'C', 'H', 'H', 'H', 'C', 'C', 'C', 'C', 'H', 'C', 'H', 'C', 'H', 'H', 'H', 'C', 'C', 'C', 'C', 'H', 'C', 'H', 'C', 'H', 'H', 'H', 'C', 'C', 'C', 'C', 'H', 'C', 'H', 'C', 'H', 'H', 'H', 'C', 'C', 'C', 'C', 'H', 'C', 'H', 'C', 'H', 'H', 'H', 'C', 'C', 'C', 'C', 'H', 'C', 'H', 'C', 'H', 'H', 'H', 'C', 'C', 'C', 'C', 'H', 'C', 'H', 'C', 'H', 'H', 'H', 'C', 'C', 'C', 'C', 'H', 'C', 'H', 'C', 'H', 'H', 'H', 'C', 'C', 'C', 'C', 'H', 'C', 'H', 'C', 'H', 'H', 'H', 'O', 'O', 'C', 'H', 'H', 'H', 'C', 'H', 'H', 'H']
Ligand atom label:  4  Ligand atom B nbo:  -0.49906
Ligand atom label:  5  Ligand atom A nbo:  -0.49925
Atom_a:  4 Atom_b:  5
C:\Users\George\Desktop\Research_UCLA\CIC\Computational Work\Project cluster version 2\project_catalyst_repurposing\structures_ligand_id\pd_me2_structures\ligand_xyz\ligand-332-n-n-105-ligand_xyz.txt
Starting node: 2
Ending node: 3
(1.308681, -0.047222, 0.418801)   2
(0.745908, 0.085134, 1.568408)   0
(-0.74217, 0.019731, 1.567118)   1
(-1.302252, 0.128328, 0.413614)   3
ligand-333-n-n-106

C:\Users\George\AppData\Local\Temp\ipykernel_7832\386804788.py:583: DeprecationWarning:

to_plotly_figure is deprecated and will be removed in version 4.0.0. Use MolGraph.to_plotly() instead.

C:\Users\George\AppData\Local\Temp\ipykernel_7832\386804788.py:589: DeprecationWarning:

to_networkx_graph is deprecated and will be removed in version 4.0.0. Use MolGraph.to_networkx() instead.

Pd number index:  0
['Pd', 'C', 'C', 'N', 'N', 'C', 'H', 'H', 'H', 'C', 'C', 'C', 'C', 'C', 'C', 'H', 'H', 'C', 'H', 'C', 'H', 'C', 'C', 'C', 'C', 'C', 'C', 'H', 'H', 'C', 'H', 'H', 'H', 'C', 'H', 'C', 'H', 'C', 'H', 'H', 'H', 'C', 'H', 'H', 'H', 'C', 'C', 'C', 'C', 'H', 'C', 'H', 'C', 'H', 'H', 'H', 'C', 'C', 'C', 'C', 'H', 'C', 'H', 'C', 'H', 'H', 'H', 'C', 'C', 'C', 'C', 'H', 'C', 'H', 'C', 'H', 'H', 'H', 'C', 'C', 'C', 'C', 'H', 'C', 'H', 'C', 'H', 'H', 'H', 'C', 'C', 'C', 'C', 'H', 'C', 'H', 'C', 'H', 'H', 'H', 'C', 'C', 'C', 'C', 'H', 'C', 'H', 'C', 'H', 'H', 'H', 'C', 'C', 'C', 'C', 'H', 'C', 'H', 'C', 'H', 'H', 'H', 'C', 'C', 'C', 'C', 'H', 'C', 'H', 'C', 'H', 'H', 'H', 'Cl', 'Cl']
Ligand atom label:  4  Ligand atom B nbo:  -0.50929
Ligand atom label:  5  Ligand atom A nbo:  -0.5098
Atom_a:  4 Atom_b:  5
C:\Users\George\Desktop\Research_UCLA\CIC\Computational Work\Project cluster version 2\project_catalyst_repurposing\structures_ligand_id\pd_me2_structures\ligand_xyz\ligand-333-n-n-106-ligand_xyz.txt
Starting node: 2
Ending node: 3
(-1.310866, 0.080462, 0.42263)   2
(-0.751255, -0.051058, 1.573645)   0
(0.737378, 0.000721, 1.57332)   1
(1.295276, -0.107578, 0.418924)   3
ligand-334-n-n-107

C:\Users\George\AppData\Local\Temp\ipykernel_7832\386804788.py:583: DeprecationWarning:

to_plotly_figure is deprecated and will be removed in version 4.0.0. Use MolGraph.to_plotly() instead.

C:\Users\George\AppData\Local\Temp\ipykernel_7832\386804788.py:589: DeprecationWarning:

to_networkx_graph is deprecated and will be removed in version 4.0.0. Use MolGraph.to_networkx() instead.

Pd number index:  0
['Pd', 'C', 'C', 'N', 'N', 'C', 'H', 'H', 'H', 'C', 'C', 'C', 'C', 'C', 'C', 'H', 'H', 'C', 'H', 'C', 'H', 'C', 'C', 'C', 'C', 'C', 'C', 'H', 'H', 'C', 'H', 'H', 'H', 'C', 'H', 'C', 'H', 'C', 'H', 'H', 'H', 'C', 'H', 'H', 'H', 'C', 'C', 'C', 'C', 'H', 'C', 'H', 'C', 'H', 'H', 'H', 'C', 'C', 'C', 'C', 'H', 'C', 'H', 'C', 'H', 'H', 'H', 'C', 'C', 'C', 'C', 'H', 'C', 'H', 'C', 'H', 'H', 'H', 'C', 'C', 'C', 'C', 'H', 'C', 'H', 'C', 'H', 'H', 'H', 'C', 'C', 'C', 'C', 'H', 'C', 'H', 'C', 'H', 'H', 'H', 'C', 'C', 'C', 'C', 'H', 'C', 'H', 'C', 'H', 'H', 'H', 'C', 'C', 'C', 'C', 'H', 'C', 'H', 'C', 'H', 'H', 'H', 'C', 'C', 'C', 'C', 'H', 'C', 'H', 'C', 'H', 'H', 'H', 'C', 'C', 'F', 'F', 'F', 'F', 'F', 'F']
Ligand atom label:  4  Ligand atom A nbo:  -0.50096
Ligand atom label:  5  Ligand atom B nbo:  -0.50096
Atom_a:  4 Atom_b:  5
C:\Users\George\Desktop\Research_UCLA\CIC\Computational Work\Project cluster version 2\project_catalyst_repurposing\structures_ligand_id\pd_me2_structures\ligand_xyz\ligand-334-n-n-107-ligand_xyz.txt
Starting node: 2
Ending node: 3
(-1.302658, 0.085036, 0.460819)   2
(-0.74408, -0.028796, 1.613743)   0
(0.744151, 0.028396, 1.613764)   1
(1.302767, -0.085175, 0.46084)   3
ligand-335-n-n-43

C:\Users\George\AppData\Local\Temp\ipykernel_7832\386804788.py:583: DeprecationWarning:

to_plotly_figure is deprecated and will be removed in version 4.0.0. Use MolGraph.to_plotly() instead.

C:\Users\George\AppData\Local\Temp\ipykernel_7832\386804788.py:589: DeprecationWarning:

to_networkx_graph is deprecated and will be removed in version 4.0.0. Use MolGraph.to_networkx() instead.

Pd number index:  0
['Pd', 'C', 'C', 'N', 'N', 'C', 'C', 'C', 'C', 'C', 'C', 'H', 'H', 'C', 'C', 'C', 'C', 'C', 'C', 'H', 'H', 'C', 'H', 'H', 'H', 'C', 'H', 'H', 'H', 'C', 'C', 'C', 'C', 'C', 'C', 'H', 'C', 'C', 'C', 'C', 'H', 'H', 'H', 'C', 'H', 'C', 'H', 'C', 'H', 'C', 'H', 'H', 'H', 'C', 'H', 'H', 'H', 'C', 'H', 'H', 'H', 'C', 'H', 'H', 'H', 'C', 'H', 'H', 'H', 'C', 'H', 'H', 'H', 'C', 'H', 'H', 'H', 'C', 'H', 'H', 'H', 'C', 'H', 'H', 'H', 'C', 'H', 'H', 'H', 'C', 'H', 'H', 'H']
Ligand atom label:  4  Ligand atom B nbo:  -0.46404
Ligand atom label:  5  Ligand atom A nbo:  -0.46404
Atom_a:  5 Atom_b:  4
C:\Users\George\Desktop\Research_UCLA\CIC\Computational Work\Project cluster version 2\project_catalyst_repurposing\structures_ligand_id\pd_me2_structures\ligand_xyz\ligand-335-n-n-43-ligand_xyz.txt
Ending node: 2
Starting node: 3
(-1.418028, -0.453418, 8.8e-05)   3
(-0.695704, 0.604667, -5.5e-05)   1
(0.801369, 0.475413, -0.000175)   0
(1.331239, -0.690495, -0.000217)   2
ligand-336-n-n-44
Pd number index:  0
['Pd', 'C', 'C', 'N', 'N', 'C', 'C', 'C', 'C', 'C', 'C', 'H', 'H', 'C', 'C', 'C', 'C', 'C', 'C', 'H', 'H', 'C', 'H', 'H', 'H', 'C', 'H', 'H', 'H', 'C', 'C', 'C', 'C', 'C', 'C', 'H', 'C', 'C', 'C', 'C', 'H', 'H', 'C', 'H', 'C', 'H', 'C', 'H', 'C', 'H', 'H', 'H', 'C', 'H', 'H', 'H', 'C', 'H', 'H', 'H', 'C', 'H', 'H', 'H', 'C', 'H', 'H', 'H', 'C', 'H', 'H', 'H', 'C', 'H', 'H', 'H', 'C', 'H', 'H', 'H', 'C', 'H', 'H', 'H', 'H', 'H', 'O', 'C', 'H', 'H', 'H']

C:\Users\George\AppData\Local\Temp\ipykernel_7832\386804788.py:583: DeprecationWarning:

to_plotly_figure is deprecated and will be removed in version 4.0.0. Use MolGraph.to_plotly() instead.

C:\Users\George\AppData\Local\Temp\ipykernel_7832\386804788.py:589: DeprecationWarning:

to_networkx_graph is deprecated and will be removed in version 4.0.0. Use MolGraph.to_networkx() instead.

Ligand atom label:  4  Ligand atom B nbo:  -0.47369
Ligand atom label:  5  Ligand atom A nbo:  -0.46403
Atom_a:  5 Atom_b:  4
C:\Users\George\Desktop\Research_UCLA\CIC\Computational Work\Project cluster version 2\project_catalyst_repurposing\structures_ligand_id\pd_me2_structures\ligand_xyz\ligand-336-n-n-44-ligand_xyz.txt
Ending node: 2
Starting node: 3
(-1.555933, 0.388203, 8.8e-05)   3
(-0.371131, 0.876063, 6e-05)   1
(0.810789, -0.052328, -0.000136)   0
(0.612105, -1.318976, -0.000108)   2
ligand-337-n-n-45

C:\Users\George\AppData\Local\Temp\ipykernel_7832\386804788.py:583: DeprecationWarning:

to_plotly_figure is deprecated and will be removed in version 4.0.0. Use MolGraph.to_plotly() instead.

C:\Users\George\AppData\Local\Temp\ipykernel_7832\386804788.py:589: DeprecationWarning:

to_networkx_graph is deprecated and will be removed in version 4.0.0. Use MolGraph.to_networkx() instead.

Pd number index:  0
['Pd', 'C', 'C', 'N', 'N', 'C', 'C', 'C', 'C', 'C', 'C', 'H', 'H', 'C', 'C', 'C', 'C', 'C', 'C', 'H', 'H', 'C', 'H', 'H', 'H', 'C', 'H', 'H', 'H', 'C', 'C', 'C', 'C', 'C', 'C', 'H', 'C', 'C', 'C', 'C', 'H', 'C', 'H', 'C', 'H', 'C', 'H', 'C', 'H', 'H', 'H', 'C', 'H', 'H', 'H', 'C', 'H', 'H', 'H', 'C', 'H', 'H', 'H', 'C', 'H', 'H', 'H', 'C', 'H', 'H', 'H', 'C', 'H', 'H', 'H', 'C', 'H', 'H', 'H', 'C', 'H', 'H', 'H', 'H', 'H', 'O', 'C', 'H', 'H', 'H', 'O', 'C', 'H', 'H', 'H']
Ligand atom label:  4  Ligand atom B nbo:  -0.47752
Ligand atom label:  5  Ligand atom A nbo:  -0.4781
Atom_a:  4 Atom_b:  5
C:\Users\George\Desktop\Research_UCLA\CIC\Computational Work\Project cluster version 2\project_catalyst_repurposing\structures_ligand_id\pd_me2_structures\ligand_xyz\ligand-337-n-n-45-ligand_xyz.txt
Starting node: 2
Ending node: 3
(-0.76123, 1.487426, 6.7e-05)   2
(0.272905, 0.728888, -4.7e-05)   0
(0.090812, -0.761022, -7.4e-05)   1
(-1.094937, -1.250844, -0.000133)   3
ligand-338-n-n-46

C:\Users\George\AppData\Local\Temp\ipykernel_7832\386804788.py:583: DeprecationWarning:

to_plotly_figure is deprecated and will be removed in version 4.0.0. Use MolGraph.to_plotly() instead.

C:\Users\George\AppData\Local\Temp\ipykernel_7832\386804788.py:589: DeprecationWarning:

to_networkx_graph is deprecated and will be removed in version 4.0.0. Use MolGraph.to_networkx() instead.

Pd number index:  0
['Pd', 'C', 'C', 'N', 'N', 'C', 'C', 'C', 'C', 'C', 'C', 'H', 'H', 'C', 'C', 'C', 'C', 'C', 'C', 'H', 'H', 'C', 'H', 'H', 'H', 'C', 'H', 'H', 'H', 'C', 'C', 'C', 'C', 'C', 'C', 'H', 'C', 'C', 'C', 'C', 'H', 'H', 'H', 'C', 'H', 'C', 'H', 'C', 'H', 'C', 'H', 'H', 'H', 'C', 'H', 'H', 'H', 'C', 'H', 'H', 'H', 'C', 'H', 'H', 'H', 'C', 'H', 'H', 'H', 'C', 'H', 'H', 'H', 'C', 'H', 'H', 'H', 'C', 'H', 'H', 'H', 'C', 'H', 'H', 'H', 'O', 'C', 'H', 'H', 'H', 'H']
Ligand atom label:  4  Ligand atom B nbo:  -0.45931
Ligand atom label:  5  Ligand atom A nbo:  -0.46414
Atom_a:  4 Atom_b:  5
C:\Users\George\Desktop\Research_UCLA\CIC\Computational Work\Project cluster version 2\project_catalyst_repurposing\structures_ligand_id\pd_me2_structures\ligand_xyz\ligand-338-n-n-46-ligand_xyz.txt
Starting node: 2
Ending node: 3
(-0.780251, -1.101806, -0.000315)   2
(-0.756251, 0.178078, -6.6e-05)   0
(0.564578, 0.891919, 0.000192)   1
(1.64764, 0.207582, 0.000266)   3
ligand-339-n-n-47

C:\Users\George\AppData\Local\Temp\ipykernel_7832\386804788.py:583: DeprecationWarning:

to_plotly_figure is deprecated and will be removed in version 4.0.0. Use MolGraph.to_plotly() instead.

C:\Users\George\AppData\Local\Temp\ipykernel_7832\386804788.py:589: DeprecationWarning:

to_networkx_graph is deprecated and will be removed in version 4.0.0. Use MolGraph.to_networkx() instead.

Pd number index:  0
['Pd', 'C', 'C', 'N', 'N', 'C', 'C', 'C', 'C', 'C', 'C', 'H', 'H', 'C', 'C', 'C', 'C', 'C', 'C', 'H', 'H', 'C', 'H', 'H', 'H', 'C', 'H', 'H', 'H', 'C', 'C', 'C', 'C', 'C', 'C', 'H', 'C', 'C', 'C', 'C', 'H', 'H', 'H', 'C', 'H', 'C', 'H', 'C', 'H', 'C', 'H', 'H', 'H', 'C', 'H', 'H', 'H', 'C', 'H', 'H', 'H', 'C', 'H', 'H', 'H', 'C', 'H', 'H', 'H', 'C', 'H', 'H', 'H', 'C', 'H', 'H', 'H', 'C', 'H', 'H', 'H', 'C', 'H', 'H', 'H', 'O', 'C', 'H', 'H', 'H', 'O', 'C', 'H', 'H', 'H']
Ligand atom label:  4  Ligand atom A nbo:  -0.46094
Ligand atom label:  5  Ligand atom B nbo:  -0.46094
Atom_a:  4 Atom_b:  5
C:\Users\George\Desktop\Research_UCLA\CIC\Computational Work\Project cluster version 2\project_catalyst_repurposing\structures_ligand_id\pd_me2_structures\ligand_xyz\ligand-339-n-n-47-ligand_xyz.txt
Starting node: 2
Ending node: 3
(-1.378382, -0.829017, -0.042585)   2
(-0.750478, 0.285989, 0.001726)   0
(0.750463, 0.286037, -0.001687)   1
(1.378494, -0.828884, 0.04265)   3
ligand-340-p-o-125
Pd number index:  13
['P', 'C', 'C', 'S', 'O', 'O', 'O', 'C', 'C', 'C', 'C', 'H', 'H', 'Pd', 'C', 'H', 'H', 'H', 'C', 'H', 'H', 'H', 'C', 'H', 'H', 'H', 'C', 'H', 'H', 'H', 'C', 'C', 'C', 'H', 'C', 'H', 'H', 'C', 'H', 'H', 'C', 'H', 'H', 'H', 'H', 'H', 'H', 'C', 'C', 'C', 'H', 'C', 'H', 'H', 'C', 'H', 'H', 'C', 'H', 'H', 'H', 'H', 'H', 'H']
Ligand atom label:  1  Ligand atom B nbo:  0.96096
Ligand atom label:  5  Ligand atom A nbo:  -0.96648
Atom_a:  1 Atom_b:  5

C:\Users\George\AppData\Local\Temp\ipykernel_7832\386804788.py:583: DeprecationWarning:

to_plotly_figure is deprecated and will be removed in version 4.0.0. Use MolGraph.to_plotly() instead.

C:\Users\George\AppData\Local\Temp\ipykernel_7832\386804788.py:589: DeprecationWarning:

to_networkx_graph is deprecated and will be removed in version 4.0.0. Use MolGraph.to_networkx() instead.

C:\Users\George\Desktop\Research_UCLA\CIC\Computational Work\Project cluster version 2\project_catalyst_repurposing\structures_ligand_id\pd_me2_structures\ligand_xyz\ligand-340-p-o-125-ligand_xyz.txt
Starting node: 0
Ending node: 4
(-0.898564, -0.063251, -0.308354)   0
(0.3066, -0.358358, -1.732723)   13
(1.714838, -0.754569, -1.390977)   1
(2.65608, 0.081459, -0.760445)   2
(2.272932, 1.707312, -0.032448)   3
(1.156903, 2.264114, -0.866603)   4
ligand-341-p-o-126

C:\Users\George\AppData\Local\Temp\ipykernel_7832\386804788.py:583: DeprecationWarning:

to_plotly_figure is deprecated and will be removed in version 4.0.0. Use MolGraph.to_plotly() instead.

C:\Users\George\AppData\Local\Temp\ipykernel_7832\386804788.py:589: DeprecationWarning:

to_networkx_graph is deprecated and will be removed in version 4.0.0. Use MolGraph.to_networkx() instead.

Pd number index:  33
['P', 'C', 'C', 'S', 'O', 'O', 'O', 'C', 'C', 'C', 'C', 'C', 'C', 'H', 'H', 'C', 'C', 'C', 'C', 'C', 'H', 'H', 'H', 'H', 'C', 'C', 'C', 'C', 'C', 'H', 'H', 'H', 'H', 'Pd', 'C', 'H', 'H', 'H', 'C', 'H', 'H', 'H', 'O', 'O', 'C', 'H', 'H', 'H', 'C', 'H', 'H', 'H', 'C', 'H', 'H', 'H', 'C', 'H', 'H', 'H']
Ligand atom label:  1  Ligand atom B nbo:  1.01222
Ligand atom label:  5  Ligand atom A nbo:  -0.99105
Atom_a:  1 Atom_b:  5
C:\Users\George\Desktop\Research_UCLA\CIC\Computational Work\Project cluster version 2\project_catalyst_repurposing\structures_ligand_id\pd_me2_structures\ligand_xyz\ligand-341-p-o-126-ligand_xyz.txt

C:\Users\George\AppData\Local\Temp\ipykernel_7832\386804788.py:583: DeprecationWarning:

to_plotly_figure is deprecated and will be removed in version 4.0.0. Use MolGraph.to_plotly() instead.

C:\Users\George\AppData\Local\Temp\ipykernel_7832\386804788.py:589: DeprecationWarning:

to_networkx_graph is deprecated and will be removed in version 4.0.0. Use MolGraph.to_networkx() instead.

Starting node: 0
Ending node: 4
(0.654713, 0.512174, -0.101639)   0
(-0.400971, 0.554678, -1.668268)   43
(-1.898826, 0.501286, -1.556302)   1
(-2.639911, -0.536723, -0.958103)   2
(-1.905233, -1.898561, -0.007398)   3
(-0.651802, -2.26341, -0.749492)   4
ligand-342-p-o-127
Pd number index:  33
['P', 'C', 'C', 'S', 'O', 'O', 'O', 'C', 'C', 'C', 'C', 'C', 'C', 'H', 'H', 'C', 'C', 'C', 'C', 'C', 'H', 'H', 'H', 'H', 'C', 'C', 'C', 'C', 'C', 'H', 'H', 'H', 'H', 'Pd', 'C', 'H', 'H', 'H', 'C', 'H', 'H', 'H', 'C', 'H', 'H', 'H', 'C', 'H', 'H', 'H', 'H', 'C', 'C', 'C', 'C', 'C', 'C', 'H', 'H', 'H', 'O', 'O', 'C', 'H', 'H', 'H', 'C', 'H', 'H', 'H']
Ligand atom label:  1  Ligand atom B nbo:  0.96919
Ligand atom label:  7  Ligand atom A nbo:  -0.91592
Atom_a:  1 Atom_b:  7
C:\Users\George\Desktop\Research_UCLA\CIC\Computational Work\Project cluster version 2\project_catalyst_repurposing\structures_ligand_id\pd_me2_structures\ligand_xyz\ligand-342-p-o-127-ligand_xyz.txt

C:\Users\George\AppData\Local\Temp\ipykernel_7832\386804788.py:583: DeprecationWarning:

to_plotly_figure is deprecated and will be removed in version 4.0.0. Use MolGraph.to_plotly() instead.

C:\Users\George\AppData\Local\Temp\ipykernel_7832\386804788.py:589: DeprecationWarning:

to_networkx_graph is deprecated and will be removed in version 4.0.0. Use MolGraph.to_networkx() instead.

Starting node: 0
Ending node: 6
(-0.469648, -0.479542, -0.899673)   0
(1.013924, -0.975363, -1.929165)   33
(2.295634, -0.269969, -1.597922)   1
(3.146665, -0.656579, -0.545088)   2
(2.694281, -1.90854, 0.694255)   3
(1.747536, -1.150391, 1.585879)   6
ligand-343-n-n-48
Pd number index:  0
['Pd', 'C', 'C', 'N', 'N', 'C', 'H', 'H', 'H', 'C', 'C', 'C', 'C', 'C', 'C', 'H', 'H', 'C', 'C', 'C', 'H', 'H', 'H', 'H', 'H', 'H', 'H', 'C', 'C', 'C', 'H', 'H', 'H', 'H', 'H', 'H', 'H', 'C', 'C', 'C', 'C', 'C', 'C', 'H', 'H', 'C', 'H', 'H', 'H', 'C', 'H', 'C', 'H', 'H', 'H', 'C', 'H', 'H', 'H', 'C', 'H', 'C', 'H', 'H', 'H', 'C', 'H', 'H', 'H', 'N', 'N', 'O', 'O', 'O', 'O', 'C', 'H', 'H', 'H', 'C', 'H', 'H', 'H']
Ligand atom label:  4  Ligand atom A nbo:  -0.47651
Ligand atom label:  5  Ligand atom B nbo:  -0.4765
Atom_a:  5 Atom_b:  4
C:\Users\George\Desktop\Research_UCLA\CIC\Computational Work\Project cluster version 2\project_catalyst_repurposing\structures_ligand_id\pd_me2_structures\ligand_xyz\ligand-343-n-n-48-ligand_xyz.txt
Ending node: 2
Starting node: 3
(1.332169, -0.023946, 0.536256)   3
(0.747878, 0.04117, 1.678401)   1
(-0.747784, -0.040794, 1.678438)   0
(-1.332114, 0.024148, 0.536295)   2
ligand-344-n-n-49

C:\Users\George\AppData\Local\Temp\ipykernel_7832\386804788.py:583: DeprecationWarning:

to_plotly_figure is deprecated and will be removed in version 4.0.0. Use MolGraph.to_plotly() instead.

C:\Users\George\AppData\Local\Temp\ipykernel_7832\386804788.py:589: DeprecationWarning:

to_networkx_graph is deprecated and will be removed in version 4.0.0. Use MolGraph.to_networkx() instead.

Pd number index:  0
['Pd', 'C', 'C', 'N', 'N', 'C', 'H', 'H', 'H', 'C', 'C', 'C', 'C', 'C', 'C', 'H', 'H', 'C', 'C', 'C', 'H', 'H', 'H', 'H', 'H', 'H', 'H', 'C', 'C', 'C', 'H', 'H', 'H', 'H', 'H', 'H', 'H', 'C', 'C', 'C', 'C', 'C', 'C', 'H', 'H', 'C', 'H', 'H', 'H', 'C', 'H', 'C', 'H', 'H', 'H', 'C', 'H', 'H', 'H', 'C', 'H', 'C', 'H', 'H', 'H', 'C', 'H', 'H', 'H', 'C', 'H', 'H', 'H', 'C', 'H', 'H', 'H', 'C', 'C', 'F', 'F', 'F', 'F', 'F', 'F']
Ligand atom label:  4  Ligand atom B nbo:  -0.47605
Ligand atom label:  5  Ligand atom A nbo:  -0.47605
Atom_a:  5 Atom_b:  4
C:\Users\George\Desktop\Research_UCLA\CIC\Computational Work\Project cluster version 2\project_catalyst_repurposing\structures_ligand_id\pd_me2_structures\ligand_xyz\ligand-344-n-n-49-ligand_xyz.txt

C:\Users\George\AppData\Local\Temp\ipykernel_7832\386804788.py:583: DeprecationWarning:

to_plotly_figure is deprecated and will be removed in version 4.0.0. Use MolGraph.to_plotly() instead.

C:\Users\George\AppData\Local\Temp\ipykernel_7832\386804788.py:589: DeprecationWarning:

to_networkx_graph is deprecated and will be removed in version 4.0.0. Use MolGraph.to_networkx() instead.

Ending node: 2
Starting node: 3
(-1.332613, -0.019228, 0.546993)   3
(-0.747563, 0.044158, 1.688804)   1
(0.74788, -0.044119, 1.688655)   0
(1.332734, 0.019195, 0.546735)   2
ligand-345-n-n-50
Pd number index:  0
['Pd', 'C', 'C', 'N', 'N', 'C', 'H', 'H', 'H', 'C', 'C', 'C', 'C', 'C', 'C', 'H', 'H', 'C', 'C', 'C', 'H', 'H', 'H', 'H', 'H', 'H', 'H', 'C', 'C', 'C', 'H', 'H', 'H', 'H', 'H', 'H', 'H', 'C', 'C', 'C', 'C', 'C', 'C', 'H', 'H', 'C', 'H', 'H', 'H', 'C', 'H', 'C', 'H', 'H', 'H', 'C', 'H', 'H', 'H', 'C', 'H', 'C', 'H', 'H', 'H', 'C', 'H', 'H', 'H', 'C', 'H', 'H', 'H', 'C', 'H', 'H', 'H', 'Cl', 'Cl']
Ligand atom label:  4  Ligand atom A nbo:  -0.47513
Ligand atom label:  5  Ligand atom B nbo:  -0.47511
Atom_a:  5 Atom_b:  4
C:\Users\George\Desktop\Research_UCLA\CIC\Computational Work\Project cluster version 2\project_catalyst_repurposing\structures_ligand_id\pd_me2_structures\ligand_xyz\ligand-345-n-n-50-ligand_xyz.txt
Ending node: 2
Starting node: 3
(-1.333524, 0.027763, 0.509317)   3
(-0.74813, -0.039555, 1.651015)   1
(0.747732, 0.03971, 1.65121)   0
(1.333383, -0.027913, 0.509672)   2
ligand-346-n-n-51

C:\Users\George\AppData\Local\Temp\ipykernel_7832\386804788.py:583: DeprecationWarning:

to_plotly_figure is deprecated and will be removed in version 4.0.0. Use MolGraph.to_plotly() instead.

C:\Users\George\AppData\Local\Temp\ipykernel_7832\386804788.py:589: DeprecationWarning:

to_networkx_graph is deprecated and will be removed in version 4.0.0. Use MolGraph.to_networkx() instead.

Pd number index:  0
['Pd', 'C', 'C', 'N', 'N', 'C', 'H', 'H', 'H', 'C', 'C', 'C', 'C', 'C', 'C', 'H', 'H', 'C', 'C', 'C', 'H', 'H', 'H', 'H', 'H', 'H', 'H', 'C', 'C', 'C', 'H', 'H', 'H', 'H', 'H', 'H', 'H', 'C', 'C', 'C', 'C', 'C', 'C', 'H', 'H', 'C', 'H', 'H', 'H', 'C', 'H', 'C', 'H', 'H', 'H', 'C', 'H', 'H', 'H', 'C', 'H', 'C', 'H', 'H', 'H', 'C', 'H', 'H', 'H', 'C', 'H', 'H', 'H', 'C', 'H', 'H', 'H', 'C', 'H', 'H', 'H', 'C', 'H', 'H', 'H']
Ligand atom label:  4  Ligand atom A nbo:  -0.47345
Ligand atom label:  5  Ligand atom B nbo:  -0.47345
Atom_a:  4 Atom_b:  5
C:\Users\George\Desktop\Research_UCLA\CIC\Computational Work\Project cluster version 2\project_catalyst_repurposing\structures_ligand_id\pd_me2_structures\ligand_xyz\ligand-346-n-n-51-ligand_xyz.txt

C:\Users\George\AppData\Local\Temp\ipykernel_7832\386804788.py:583: DeprecationWarning:

to_plotly_figure is deprecated and will be removed in version 4.0.0. Use MolGraph.to_plotly() instead.

C:\Users\George\AppData\Local\Temp\ipykernel_7832\386804788.py:589: DeprecationWarning:

to_networkx_graph is deprecated and will be removed in version 4.0.0. Use MolGraph.to_networkx() instead.

Starting node: 2
Ending node: 3
(-1.33425, -0.025018, 0.491816)   2
(-0.747587, 0.040603, 1.632749)   0
(0.747889, -0.040357, 1.63262)   1
(1.334387, 0.025042, 0.491581)   3
ligand-347-n-n-52
Pd number index:  0
['Pd', 'C', 'C', 'N', 'N', 'C', 'H', 'H', 'H', 'C', 'C', 'C', 'C', 'C', 'C', 'H', 'H', 'C', 'C', 'C', 'H', 'H', 'H', 'H', 'H', 'H', 'H', 'C', 'C', 'C', 'H', 'H', 'H', 'H', 'H', 'H', 'H', 'C', 'C', 'C', 'C', 'C', 'C', 'H', 'H', 'C', 'H', 'H', 'H', 'C', 'H', 'C', 'H', 'H', 'H', 'C', 'H', 'H', 'H', 'C', 'H', 'C', 'H', 'H', 'H', 'C', 'H', 'H', 'H', 'C', 'H', 'H', 'H', 'C', 'H', 'H', 'H', 'O', 'O', 'C', 'H', 'H', 'H', 'C', 'H', 'H', 'H']
Ligand atom label:  4  Ligand atom A nbo:  -0.47358
Ligand atom label:  5  Ligand atom B nbo:  -0.47358
Atom_a:  4 Atom_b:  5
C:\Users\George\Desktop\Research_UCLA\CIC\Computational Work\Project cluster version 2\project_catalyst_repurposing\structures_ligand_id\pd_me2_structures\ligand_xyz\ligand-347-n-n-52-ligand_xyz.txt
Starting node: 2
Ending node: 3
(1.331874, -0.094172, 0.514906)   2
(0.748874, 0.00442, 1.655636)   0
(-0.748994, -0.004248, 1.655584)   1
(-1.331922, 0.094244, 0.51481)   3
ligand-348-n-n-53

C:\Users\George\AppData\Local\Temp\ipykernel_7832\386804788.py:583: DeprecationWarning:

to_plotly_figure is deprecated and will be removed in version 4.0.0. Use MolGraph.to_plotly() instead.

C:\Users\George\AppData\Local\Temp\ipykernel_7832\386804788.py:589: DeprecationWarning:

to_networkx_graph is deprecated and will be removed in version 4.0.0. Use MolGraph.to_networkx() instead.

Pd number index:  0
['Pd', 'C', 'C', 'N', 'N', 'C', 'H', 'H', 'H', 'C', 'C', 'C', 'C', 'C', 'C', 'H', 'H', 'C', 'C', 'C', 'H', 'H', 'H', 'H', 'H', 'H', 'H', 'C', 'C', 'C', 'H', 'H', 'H', 'H', 'H', 'H', 'H', 'C', 'C', 'C', 'C', 'C', 'C', 'H', 'H', 'C', 'H', 'H', 'H', 'C', 'H', 'C', 'H', 'H', 'H', 'C', 'H', 'H', 'H', 'C', 'H', 'C', 'H', 'H', 'H', 'C', 'H', 'H', 'H', 'C', 'H', 'H', 'H', 'C', 'H', 'H', 'H', 'C', 'H', 'H', 'H', 'C', 'H', 'H', 'H', 'N', 'N', 'C', 'H', 'H', 'H', 'C', 'H', 'H', 'H']
Ligand atom label:  4  Ligand atom B nbo:  -0.47176
Ligand atom label:  5  Ligand atom A nbo:  -0.47178
Atom_a:  4 Atom_b:  5
C:\Users\George\Desktop\Research_UCLA\CIC\Computational Work\Project cluster version 2\project_catalyst_repurposing\structures_ligand_id\pd_me2_structures\ligand_xyz\ligand-348-n-n-53-ligand_xyz.txt
Starting node: 2
Ending node: 3
(1.33522, 0.030148, 0.521183)   2
(0.747724, -0.038205, 1.66189)   0
(-0.747747, 0.038053, 1.661881)   1
(-1.335199, -0.030211, 0.521157)   3
ligand-349-p-o-128
Pd number index:  34
['P', 'C', 'C', 'S', 'O', 'O', 'O', 'C', 'C', 'C', 'C', 'C', 'C', 'H', 'H', 'H', 'C', 'C', 'C', 'C', 'C', 'H', 'H', 'H', 'H', 'C', 'C', 'C', 'C', 'C', 'H', 'H', 'H', 'H', 'Pd', 'C', 'H', 'H', 'H', 'C', 'H', 'H', 'H', 'H', 'H', 'C', 'C', 'O', 'C', 'H', 'C', 'H', 'H']
Ligand atom label:  1  Ligand atom B nbo:  0.98888
Ligand atom label:  5  Ligand atom A nbo:  -0.93871
Atom_a:  1 Atom_b:  5

C:\Users\George\AppData\Local\Temp\ipykernel_7832\386804788.py:583: DeprecationWarning:

to_plotly_figure is deprecated and will be removed in version 4.0.0. Use MolGraph.to_plotly() instead.

C:\Users\George\AppData\Local\Temp\ipykernel_7832\386804788.py:589: DeprecationWarning:

to_networkx_graph is deprecated and will be removed in version 4.0.0. Use MolGraph.to_networkx() instead.

C:\Users\George\Desktop\Research_UCLA\CIC\Computational Work\Project cluster version 2\project_catalyst_repurposing\structures_ligand_id\pd_me2_structures\ligand_xyz\ligand-349-p-o-128-ligand_xyz.txt
Starting node: 0
Ending node: 4
(0.297149, 0.553759, -0.064449)   0
(0.974177, -0.011515, 1.566366)   1
(1.647749, -1.244343, 1.649411)   2
(1.925154, -2.282486, 0.18316)   3
(0.537335, -2.679801, -0.235417)   4
ligand-350-p-o-129
Pd number index:  34
['P', 'C', 'C', 'S', 'O', 'O', 'O', 'C', 'C', 'C', 'C', 'C', 'C', 'H', 'H', 'H', 'C', 'C', 'C', 'C', 'C', 'H', 'H', 'H', 'H', 'C', 'C', 'C', 'C', 'C', 'H', 'H', 'H', 'H', 'Pd', 'C', 'H', 'H', 'H', 'C', 'H', 'H', 'H', 'H', 'H', 'C', 'C', 'O', 'H', 'C', 'C', 'C', 'C', 'C', 'H', 'C', 'H', 'H', 'H']

C:\Users\George\AppData\Local\Temp\ipykernel_7832\386804788.py:583: DeprecationWarning:

to_plotly_figure is deprecated and will be removed in version 4.0.0. Use MolGraph.to_plotly() instead.

C:\Users\George\AppData\Local\Temp\ipykernel_7832\386804788.py:589: DeprecationWarning:

to_networkx_graph is deprecated and will be removed in version 4.0.0. Use MolGraph.to_networkx() instead.

Ligand atom label:  1  Ligand atom B nbo:  0.98637
Ligand atom label:  5  Ligand atom A nbo:  -0.9417
Atom_a:  1 Atom_b:  5
C:\Users\George\Desktop\Research_UCLA\CIC\Computational Work\Project cluster version 2\project_catalyst_repurposing\structures_ligand_id\pd_me2_structures\ligand_xyz\ligand-350-p-o-129-ligand_xyz.txt

C:\Users\George\AppData\Local\Temp\ipykernel_7832\386804788.py:583: DeprecationWarning:

to_plotly_figure is deprecated and will be removed in version 4.0.0. Use MolGraph.to_plotly() instead.

C:\Users\George\AppData\Local\Temp\ipykernel_7832\386804788.py:589: DeprecationWarning:

to_networkx_graph is deprecated and will be removed in version 4.0.0. Use MolGraph.to_networkx() instead.

Starting node: 0
Ending node: 4
(1.042347, 0.388077, -0.052659)   0
(1.348425, -0.505978, 1.544367)   1
(1.288342, -1.91142, 1.578387)   2
(0.950257, -2.888291, 0.083733)   3
(-0.451537, -2.486709, -0.286985)   4
ligand-351-p-o-130
Pd number index:  34
['P', 'C', 'C', 'S', 'O', 'O', 'O', 'C', 'C', 'C', 'C', 'C', 'C', 'H', 'H', 'H', 'C', 'C', 'C', 'C', 'C', 'H', 'H', 'H', 'H', 'C', 'C', 'C', 'C', 'C', 'H', 'H', 'H', 'H', 'Pd', 'C', 'H', 'H', 'H', 'C', 'H', 'H', 'H', 'H', 'H', 'C', 'C', 'C', 'H', 'C', 'H', 'H', 'N', 'C', 'H', 'H', 'H']
Ligand atom label:  1  Ligand atom B nbo:  0.99431
Ligand atom label:  5  Ligand atom A nbo:  -0.98253
Atom_a:  1 Atom_b:  5
C:\Users\George\Desktop\Research_UCLA\CIC\Computational Work\Project cluster version 2\project_catalyst_repurposing\structures_ligand_id\pd_me2_structures\ligand_xyz\ligand-351-p-o-130-ligand_xyz.txt
Starting node: 0
Ending node: 4
(0.221978, 0.611146, -0.060013)   0
(1.234633, 0.307818, 1.471648)   1
(2.061394, -0.821342, 1.609206)   2
(2.047654, -2.265233, 0.490581)   3
(1.924586, -1.685619, -0.888595)   4
ligand-352-p-o-131

C:\Users\George\AppData\Local\Temp\ipykernel_7832\386804788.py:583: DeprecationWarning:

to_plotly_figure is deprecated and will be removed in version 4.0.0. Use MolGraph.to_plotly() instead.

C:\Users\George\AppData\Local\Temp\ipykernel_7832\386804788.py:589: DeprecationWarning:

to_networkx_graph is deprecated and will be removed in version 4.0.0. Use MolGraph.to_networkx() instead.

Pd number index:  34
['P', 'C', 'C', 'S', 'O', 'O', 'O', 'C', 'C', 'C', 'C', 'C', 'C', 'H', 'H', 'H', 'C', 'C', 'C', 'C', 'C', 'H', 'H', 'H', 'H', 'C', 'C', 'C', 'C', 'C', 'H', 'H', 'H', 'H', 'Pd', 'C', 'H', 'H', 'H', 'C', 'H', 'H', 'H', 'H', 'H', 'C', 'C', 'C', 'H', 'C', 'H', 'H', 'S']
Ligand atom label:  1  Ligand atom B nbo:  0.99073
Ligand atom label:  5  Ligand atom A nbo:  -0.93671
Atom_a:  1 Atom_b:  5
C:\Users\George\Desktop\Research_UCLA\CIC\Computational Work\Project cluster version 2\project_catalyst_repurposing\structures_ligand_id\pd_me2_structures\ligand_xyz\ligand-352-p-o-131-ligand_xyz.txt

C:\Users\George\AppData\Local\Temp\ipykernel_7832\386804788.py:583: DeprecationWarning:

to_plotly_figure is deprecated and will be removed in version 4.0.0. Use MolGraph.to_plotly() instead.

C:\Users\George\AppData\Local\Temp\ipykernel_7832\386804788.py:589: DeprecationWarning:

to_networkx_graph is deprecated and will be removed in version 4.0.0. Use MolGraph.to_networkx() instead.

Starting node: 0
Ending node: 4
(0.459059, 0.526298, -0.0691)   0
(1.190639, -0.106469, 1.516284)   1
(1.689635, -1.420201, 1.585715)   2
(1.728109, -2.510048, 0.13204)   3
(0.27696, -2.710235, -0.202261)   4
ligand-353-p-o-132
Pd number index:  34
['P', 'C', 'C', 'S', 'O', 'O', 'O', 'C', 'C', 'C', 'C', 'C', 'C', 'H', 'H', 'H', 'C', 'C', 'C', 'C', 'C', 'H', 'H', 'H', 'H', 'C', 'C', 'C', 'C', 'C', 'H', 'H', 'H', 'H', 'Pd', 'C', 'H', 'H', 'H', 'C', 'H', 'H', 'H', 'H', 'H', 'C', 'C', 'H', 'S', 'C', 'C', 'C', 'C', 'C', 'H', 'C', 'H', 'H', 'H']
Ligand atom label:  1  Ligand atom B nbo:  0.98811
Ligand atom label:  5  Ligand atom A nbo:  -0.93537
Atom_a:  1 Atom_b:  5
C:\Users\George\Desktop\Research_UCLA\CIC\Computational Work\Project cluster version 2\project_catalyst_repurposing\structures_ligand_id\pd_me2_structures\ligand_xyz\ligand-353-p-o-132-ligand_xyz.txt
Starting node: 0
Ending node: 4
(1.111654, 0.334881, -0.064475)   0
(1.4468, -0.599231, 1.509523)   1
(1.286011, -1.996707, 1.553571)   2
(0.828927, -2.952994, 0.07999)   3
(-0.552895, -2.457635, -0.249312)   4
ligand-354-c-o-11

C:\Users\George\AppData\Local\Temp\ipykernel_7832\386804788.py:583: DeprecationWarning:

to_plotly_figure is deprecated and will be removed in version 4.0.0. Use MolGraph.to_plotly() instead.

C:\Users\George\AppData\Local\Temp\ipykernel_7832\386804788.py:589: DeprecationWarning:

to_networkx_graph is deprecated and will be removed in version 4.0.0. Use MolGraph.to_networkx() instead.

Pd number index:  0
['Pd', 'C', 'C', 'C', 'H', 'N', 'N', 'C', 'C', 'C', 'C', 'C', 'C', 'H', 'H', 'C', 'H', 'C', 'H', 'H', 'C', 'C', 'H', 'H', 'C', 'C', 'C', 'H', 'C', 'C', 'C', 'H', 'C', 'H', 'H', 'H', 'C', 'H', 'H', 'H', 'C', 'H', 'H', 'H', 'C', 'H', 'H', 'H', 'C', 'H', 'H', 'H', 'C', 'H', 'H', 'H', 'O', 'O', 'C', 'H', 'H', 'C', 'H', 'H', 'O', 'C', 'H', 'H', 'H']
Ligand atom label:  2  Ligand atom A nbo:  0.23442
Ligand atom label:  57  Ligand atom B nbo:  -0.67389
Atom_a:  2 Atom_b:  57
C:\Users\George\Desktop\Research_UCLA\CIC\Computational Work\Project cluster version 2\project_catalyst_repurposing\structures_ligand_id\pd_me2_structures\ligand_xyz\ligand-354-c-o-11-ligand_xyz.txt
Starting node: 0
Ending node: 47
(0.740549, 0.513843, -0.016596)   0
(-0.012391, 1.672985, 0.038374)   5
(-1.429197, 1.832776, -0.05235)   25
(-2.29282, 0.712394, -0.271592)   27
(-1.949334, -0.493317, -0.419848)   47

C:\Users\George\AppData\Local\Temp\ipykernel_7832\386804788.py:583: DeprecationWarning:

to_plotly_figure is deprecated and will be removed in version 4.0.0. Use MolGraph.to_plotly() instead.

C:\Users\George\AppData\Local\Temp\ipykernel_7832\386804788.py:589: DeprecationWarning:

to_networkx_graph is deprecated and will be removed in version 4.0.0. Use MolGraph.to_networkx() instead.

ligand-355-p-o-133
Pd number index:  32
['P', 'O', 'P', 'N', 'C', 'C', 'C', 'C', 'H', 'C', 'H', 'C', 'H', 'H', 'C', 'C', 'C', 'C', 'C', 'C', 'H', 'H', 'H', 'C', 'C', 'C', 'C', 'C', 'C', 'H', 'H', 'H', 'Pd', 'H', 'H', 'C', 'H', 'H', 'H', 'C', 'H', 'H', 'H', 'H', 'H', 'C', 'C', 'C', 'C', 'C', 'C', 'H', 'H', 'H', 'O', 'O', 'C', 'H', 'H', 'H', 'C', 'H', 'H', 'H', 'C', 'H', 'C', 'H', 'C', 'H', 'H', 'H', 'C', 'H', 'H', 'H', 'C', 'H', 'H', 'H', 'C', 'H', 'H', 'H']
Ligand atom label:  1  Ligand atom B nbo:  1.22827
Ligand atom label:  2  Ligand atom A nbo:  -0.94122
Atom_a:  1 Atom_b:  2
C:\Users\George\Desktop\Research_UCLA\CIC\Computational Work\Project cluster version 2\project_catalyst_repurposing\structures_ligand_id\pd_me2_structures\ligand_xyz\ligand-355-p-o-133-ligand_xyz.txt
Starting node: 0
Ending node: 1
(-0.142186, 0.894211, 0.120776)   0
(1.46138, 0.127598, -0.001198)   3
(1.789145, -0.665136, -1.483564)   2
(1.028065, 0.038471, -2.58784)   1
ligand-356-p-o-134

C:\Users\George\AppData\Local\Temp\ipykernel_7832\386804788.py:583: DeprecationWarning:

to_plotly_figure is deprecated and will be removed in version 4.0.0. Use MolGraph.to_plotly() instead.

C:\Users\George\AppData\Local\Temp\ipykernel_7832\386804788.py:589: DeprecationWarning:

to_networkx_graph is deprecated and will be removed in version 4.0.0. Use MolGraph.to_networkx() instead.

Pd number index:  54
['P', 'O', 'P', 'N', 'C', 'C', 'C', 'C', 'C', 'C', 'H', 'H', 'H', 'H', 'H', 'C', 'C', 'C', 'C', 'C', 'C', 'H', 'H', 'H', 'H', 'H', 'C', 'C', 'C', 'C', 'H', 'C', 'H', 'C', 'H', 'H', 'C', 'C', 'C', 'C', 'C', 'C', 'H', 'H', 'H', 'C', 'C', 'C', 'C', 'C', 'C', 'H', 'H', 'H', 'Pd', 'H', 'H', 'C', 'H', 'H', 'H', 'C', 'H', 'H', 'H', 'H', 'C', 'C', 'C', 'C', 'C', 'C', 'H', 'H', 'H', 'O', 'O', 'C', 'H', 'H', 'H', 'C', 'H', 'H', 'H', 'C', 'F', 'F', 'F']
Ligand atom label:  1  Ligand atom B nbo:  1.23138
Ligand atom label:  2  Ligand atom A nbo:  -0.93597
Atom_a:  1 Atom_b:  2
C:\Users\George\Desktop\Research_UCLA\CIC\Computational Work\Project cluster version 2\project_catalyst_repurposing\structures_ligand_id\pd_me2_structures\ligand_xyz\ligand-356-p-o-134-ligand_xyz.txt
Starting node: 0
Ending node: 1
(-0.743027, 0.946106, 0.04906)   0
(0.703357, -0.095116, -0.096742)   3
(0.451525, -1.654412, -0.757243)   2
(-0.956585, -1.801696, -1.281398)   1
ligand-357-n-n-54

C:\Users\George\AppData\Local\Temp\ipykernel_7832\386804788.py:583: DeprecationWarning:

to_plotly_figure is deprecated and will be removed in version 4.0.0. Use MolGraph.to_plotly() instead.

C:\Users\George\AppData\Local\Temp\ipykernel_7832\386804788.py:589: DeprecationWarning:

to_networkx_graph is deprecated and will be removed in version 4.0.0. Use MolGraph.to_networkx() instead.

Pd number index:  0
['Pd', 'C', 'N', 'C', 'H', 'H', 'C', 'H', 'H', 'H', 'C', 'H', 'H', 'C', 'C', 'C', 'C', 'C', 'C', 'H', 'H', 'C', 'C', 'C', 'C', 'H', 'C', 'H', 'C', 'H', 'H', 'H', 'C', 'H', 'H', 'H', 'H', 'C', 'H', 'C', 'C', 'C', 'C', 'H', 'C', 'H', 'C', 'H', 'H', 'H', 'C', 'C', 'C', 'C', 'H', 'C', 'H', 'C', 'H', 'H', 'H', 'C', 'C', 'C', 'H', 'C', 'C', 'H', 'H', 'H', 'N', 'H']
Ligand atom label:  3  Ligand atom B nbo:  -0.56979
Ligand atom label:  71  Ligand atom A nbo:  -0.56906
Atom_a:  71 Atom_b:  3
C:\Users\George\Desktop\Research_UCLA\CIC\Computational Work\Project cluster version 2\project_catalyst_repurposing\structures_ligand_id\pd_me2_structures\ligand_xyz\ligand-357-n-n-54-ligand_xyz.txt

C:\Users\George\AppData\Local\Temp\ipykernel_7832\386804788.py:583: DeprecationWarning:

to_plotly_figure is deprecated and will be removed in version 4.0.0. Use MolGraph.to_plotly() instead.

C:\Users\George\AppData\Local\Temp\ipykernel_7832\386804788.py:589: DeprecationWarning:

to_networkx_graph is deprecated and will be removed in version 4.0.0. Use MolGraph.to_networkx() instead.

Ending node: 1
Starting node: 62
(-0.394215, -2.537069, -0.59455)   62
(-1.06424, -2.266396, 0.543018)   53
(-1.12134, -0.842815, 0.964433)   0
(-0.531532, 0.005627, 0.203282)   1
ligand-358-n-n-55
Pd number index:  0
['Pd', 'C', 'N', 'C', 'H', 'H', 'C', 'H', 'H', 'H', 'C', 'H', 'H', 'C', 'C', 'C', 'C', 'C', 'C', 'H', 'H', 'C', 'C', 'C', 'C', 'H', 'C', 'H', 'C', 'H', 'H', 'H', 'C', 'H', 'H', 'H', 'H', 'C', 'H', 'C', 'C', 'C', 'C', 'H', 'C', 'H', 'C', 'H', 'H', 'C', 'C', 'C', 'C', 'H', 'C', 'H', 'C', 'H', 'H', 'C', 'C', 'C', 'H', 'C', 'C', 'H', 'H', 'H', 'N', 'H', 'C', 'H', 'H', 'H', 'C', 'H', 'H', 'H']
Ligand atom label:  3  Ligand atom B nbo:  -0.56809
Ligand atom label:  69  Ligand atom A nbo:  -0.57236
Atom_a:  3 Atom_b:  69
C:\Users\George\Desktop\Research_UCLA\CIC\Computational Work\Project cluster version 2\project_catalyst_repurposing\structures_ligand_id\pd_me2_structures\ligand_xyz\ligand-358-n-n-55-ligand_xyz.txt
Starting node: 1
Ending node: 60
(-0.750539, 0.210309, 0.199107)   1
(-1.629408, -0.537373, 0.761466)   0
(-1.924623, -1.83246, 0.095984)   51
(-1.266946, -2.089918, -1.051357)   60
ligand-359-n-n-56
Pd number index:  0
['Pd', 'C', 'N', 'C', 'H', 'H', 'C', 'H', 'H', 'H', 'C', 'H', 'H', 'C', 'C', 'C', 'C', 'C', 'C', 'H', 'H', 'C', 'C', 'C', 'C', 'H', 'C', 'H', 'C', 'H', 'H', 'H', 'C', 'H', 'H', 'H', 'H', 'C', 'H', 'C', 'C', 'C', 'C', 'H', 'C', 'H', 'C', 'H', 'H', 'C', 'C', 'C', 'C', 'H', 'C', 'H', 'C', 'H', 'H', 'C', 'C', 'C', 'H', 'C', 'C', 'H', 'H', 'H', 'N', 'H', 'F', 'F']

C:\Users\George\AppData\Local\Temp\ipykernel_7832\386804788.py:583: DeprecationWarning:

to_plotly_figure is deprecated and will be removed in version 4.0.0. Use MolGraph.to_plotly() instead.

C:\Users\George\AppData\Local\Temp\ipykernel_7832\386804788.py:589: DeprecationWarning:

to_networkx_graph is deprecated and will be removed in version 4.0.0. Use MolGraph.to_networkx() instead.

Ligand atom label:  3  Ligand atom B nbo:  -0.4902
Ligand atom label:  69  Ligand atom A nbo:  -0.48892
Atom_a:  69 Atom_b:  3
C:\Users\George\Desktop\Research_UCLA\CIC\Computational Work\Project cluster version 2\project_catalyst_repurposing\structures_ligand_id\pd_me2_structures\ligand_xyz\ligand-359-n-n-56-ligand_xyz.txt

C:\Users\George\AppData\Local\Temp\ipykernel_7832\386804788.py:583: DeprecationWarning:

to_plotly_figure is deprecated and will be removed in version 4.0.0. Use MolGraph.to_plotly() instead.

C:\Users\George\AppData\Local\Temp\ipykernel_7832\386804788.py:589: DeprecationWarning:

to_networkx_graph is deprecated and will be removed in version 4.0.0. Use MolGraph.to_networkx() instead.

Ending node: 1
Starting node: 60
(1.688618, -1.969852, 0.83289)   60
(2.191415, -1.578724, -0.353319)   51
(1.669225, -0.305199, -0.91341)   0
(0.741782, 0.284297, -0.24823)   1
ligand-360-n-n-57
Pd number index:  0
['Pd', 'C', 'N', 'C', 'H', 'H', 'C', 'H', 'H', 'H', 'C', 'H', 'H', 'C', 'C', 'C', 'C', 'C', 'C', 'H', 'H', 'C', 'C', 'C', 'C', 'H', 'C', 'H', 'C', 'H', 'H', 'H', 'C', 'H', 'H', 'H', 'H', 'C', 'H', 'C', 'C', 'C', 'C', 'H', 'C', 'H', 'C', 'H', 'H', 'C', 'C', 'C', 'C', 'H', 'C', 'H', 'C', 'H', 'H', 'C', 'C', 'C', 'H', 'C', 'C', 'H', 'H', 'H', 'N', 'H', 'Cl', 'Cl']
Ligand atom label:  3  Ligand atom B nbo:  -0.5666
Ligand atom label:  69  Ligand atom A nbo:  -0.57722
Atom_a:  3 Atom_b:  69
C:\Users\George\Desktop\Research_UCLA\CIC\Computational Work\Project cluster version 2\project_catalyst_repurposing\structures_ligand_id\pd_me2_structures\ligand_xyz\ligand-360-n-n-57-ligand_xyz.txt
Starting node: 1
Ending node: 60
(-0.888466, 0.341878, 0.138262)   1
(-1.841608, -0.442956, 0.491315)   0
(-2.061026, -1.644669, -0.35526)   51
(-1.280204, -1.767457, -1.447387)   60
ligand-361-n-n-58

C:\Users\George\AppData\Local\Temp\ipykernel_7832\386804788.py:583: DeprecationWarning:

to_plotly_figure is deprecated and will be removed in version 4.0.0. Use MolGraph.to_plotly() instead.

C:\Users\George\AppData\Local\Temp\ipykernel_7832\386804788.py:589: DeprecationWarning:

to_networkx_graph is deprecated and will be removed in version 4.0.0. Use MolGraph.to_networkx() instead.

Pd number index:  0
['Pd', 'C', 'N', 'C', 'H', 'H', 'C', 'H', 'H', 'H', 'C', 'H', 'H', 'C', 'C', 'C', 'C', 'C', 'C', 'H', 'H', 'C', 'C', 'C', 'C', 'H', 'C', 'H', 'C', 'H', 'H', 'H', 'C', 'H', 'H', 'H', 'H', 'C', 'C', 'C', 'H', 'C', 'C', 'H', 'H', 'H', 'N', 'H', 'C', 'H', 'C', 'C', 'C', 'C', 'H', 'C', 'C', 'H', 'H', 'H', 'C', 'C', 'C', 'C', 'H', 'C', 'C', 'H', 'H', 'H', 'C', 'H', 'H', 'C', 'H', 'H']
Ligand atom label:  3  Ligand atom B nbo:  -0.5043
Ligand atom label:  47  Ligand atom A nbo:  -0.50492
Atom_a:  3 Atom_b:  47
C:\Users\George\Desktop\Research_UCLA\CIC\Computational Work\Project cluster version 2\project_catalyst_repurposing\structures_ligand_id\pd_me2_structures\ligand_xyz\ligand-361-n-n-58-ligand_xyz.txt

C:\Users\George\AppData\Local\Temp\ipykernel_7832\386804788.py:583: DeprecationWarning:

to_plotly_figure is deprecated and will be removed in version 4.0.0. Use MolGraph.to_plotly() instead.

C:\Users\George\AppData\Local\Temp\ipykernel_7832\386804788.py:589: DeprecationWarning:

to_networkx_graph is deprecated and will be removed in version 4.0.0. Use MolGraph.to_networkx() instead.

Starting node: 1
Ending node: 38
(0.842176, 0.202787, -0.059543)   1
(1.479386, -0.242211, -1.081609)   0
(2.39827, -1.385552, -0.853026)   29
(2.500816, -1.835629, 0.412129)   38
ligand-362-n-n-59
Pd number index:  0
['Pd', 'N', 'N', 'C', 'C', 'C', 'C', 'C', 'C', 'H', 'H', 'C', 'C', 'C', 'C', 'C', 'C', 'H', 'H', 'C', 'H', 'H', 'H', 'C', 'H', 'H', 'H', 'C', 'H', 'C', 'H', 'C', 'C', 'C', 'H', 'C', 'H', 'C', 'C', 'C', 'C', 'C', 'H', 'C', 'H', 'H', 'H', 'C', 'C', 'C', 'C', 'C', 'H', 'C', 'H', 'H', 'H', 'H', 'H', 'C', 'H', 'C', 'H', 'H', 'H', 'C', 'H', 'H', 'H', 'C', 'H', 'H', 'H', 'C', 'H', 'H', 'H', 'C', 'H', 'C', 'H', 'H', 'H', 'C', 'H', 'H', 'H', 'C', 'H', 'H', 'H', 'C', 'H', 'H', 'H']
Ligand atom label:  2  Ligand atom A nbo:  -0.47212
Ligand atom label:  3  Ligand atom B nbo:  -0.46941
Atom_a:  3 Atom_b:  2
C:\Users\George\Desktop\Research_UCLA\CIC\Computational Work\Project cluster version 2\project_catalyst_repurposing\structures_ligand_id\pd_me2_structures\ligand_xyz\ligand-362-n-n-59-ligand_xyz.txt
Ending node: 0
Starting node: 1
(1.401068, -0.42753, 0.064639)   1
(0.774759, 0.639353, 0.377539)   22
(-0.705598, 0.650741, 0.248094)   24
(-1.297425, -0.398779, -0.170058)   0
ligand-363-n-n-60

C:\Users\George\AppData\Local\Temp\ipykernel_7832\386804788.py:583: DeprecationWarning:

to_plotly_figure is deprecated and will be removed in version 4.0.0. Use MolGraph.to_plotly() instead.

C:\Users\George\AppData\Local\Temp\ipykernel_7832\386804788.py:589: DeprecationWarning:

to_networkx_graph is deprecated and will be removed in version 4.0.0. Use MolGraph.to_networkx() instead.

Pd number index:  0
['Pd', 'C', 'N', 'C', 'H', 'H', 'C', 'H', 'H', 'H', 'C', 'H', 'H', 'H', 'C', 'C', 'C', 'C', 'H', 'C', 'H', 'C', 'H', 'H', 'H', 'C', 'C', 'C', 'C', 'H', 'C', 'H', 'C', 'H', 'H', 'H', 'C', 'C', 'C', 'H', 'C', 'C', 'H', 'H', 'H', 'N', 'H', 'C', 'C', 'C', 'C', 'C', 'C', 'C', 'C', 'C', 'H', 'C', 'H', 'H', 'H', 'C', 'H', 'C', 'C', 'C', 'C', 'H', 'C', 'H', 'C', 'H', 'H', 'H', 'C', 'C', 'C', 'C', 'H', 'C', 'H', 'C', 'H', 'H', 'H', 'C', 'H', 'C', 'C', 'C', 'C', 'H', 'C', 'H', 'C', 'H', 'H', 'C', 'H', 'H', 'H']
Ligand atom label:  3  Ligand atom B nbo:  -0.58708
Ligand atom label:  46  Ligand atom A nbo:  -0.56892
Atom_a:  46 Atom_b:  3
C:\Users\George\Desktop\Research_UCLA\CIC\Computational Work\Project cluster version 2\project_catalyst_repurposing\structures_ligand_id\pd_me2_structures\ligand_xyz\ligand-363-n-n-60-ligand_xyz.txt
Ending node: 1
Starting node: 37
(3.932919, 0.432508, 0.165364)   37
(3.463138, -0.091861, 1.310827)   28
(2.020379, -0.441672, 1.341412)   0
(1.352262, -0.244137, 0.263762)   1
ligand-364-n-n-61

C:\Users\George\AppData\Local\Temp\ipykernel_7832\386804788.py:583: DeprecationWarning:

to_plotly_figure is deprecated and will be removed in version 4.0.0. Use MolGraph.to_plotly() instead.

C:\Users\George\AppData\Local\Temp\ipykernel_7832\386804788.py:589: DeprecationWarning:

to_networkx_graph is deprecated and will be removed in version 4.0.0. Use MolGraph.to_networkx() instead.

Pd number index:  0
['Pd', 'C', 'N', 'C', 'H', 'H', 'C', 'H', 'H', 'H', 'C', 'H', 'H', 'H', 'C', 'C', 'C', 'C', 'H', 'C', 'H', 'C', 'H', 'H', 'H', 'C', 'C', 'C', 'C', 'H', 'C', 'H', 'C', 'H', 'H', 'H', 'C', 'C', 'C', 'H', 'C', 'C', 'H', 'H', 'H', 'N', 'H', 'C', 'C', 'C', 'C', 'C', 'C', 'C', 'C', 'C', 'H', 'C', 'H', 'H', 'H', 'C', 'H', 'C', 'C', 'C', 'C', 'H', 'C', 'H', 'C', 'H', 'H', 'H', 'C', 'C', 'C', 'C', 'H', 'C', 'H', 'C', 'H', 'H', 'H', 'C', 'H', 'C', 'C', 'C', 'C', 'H', 'C', 'H', 'C', 'H', 'H', 'C', 'H', 'H', 'H']
Ligand atom label:  3  Ligand atom B nbo:  -0.58708
Ligand atom label:  46  Ligand atom A nbo:  -0.56892
Atom_a:  46 Atom_b:  3
C:\Users\George\Desktop\Research_UCLA\CIC\Computational Work\Project cluster version 2\project_catalyst_repurposing\structures_ligand_id\pd_me2_structures\ligand_xyz\ligand-364-n-n-61-ligand_xyz.txt
Ending node: 1
Starting node: 37
(3.932982, 0.432446, 0.165233)   37
(3.463188, -0.091627, 1.310828)   28
(2.020413, -0.44138, 1.341511)   0
(1.352286, -0.244027, 0.263835)   1
ligand-365-n-n-62

C:\Users\George\AppData\Local\Temp\ipykernel_7832\386804788.py:583: DeprecationWarning:

to_plotly_figure is deprecated and will be removed in version 4.0.0. Use MolGraph.to_plotly() instead.

C:\Users\George\AppData\Local\Temp\ipykernel_7832\386804788.py:589: DeprecationWarning:

to_networkx_graph is deprecated and will be removed in version 4.0.0. Use MolGraph.to_networkx() instead.

Pd number index:  0
['Pd', 'C', 'N', 'C', 'H', 'H', 'H', 'C', 'H', 'H', 'C', 'C', 'C', 'C', 'H', 'C', 'H', 'C', 'H', 'H', 'C', 'C', 'C', 'C', 'H', 'C', 'H', 'C', 'H', 'H', 'C', 'C', 'C', 'H', 'C', 'C', 'H', 'H', 'H', 'N', 'H', 'C', 'C', 'C', 'C', 'C', 'C', 'C', 'C', 'C', 'H', 'C', 'H', 'H', 'H', 'C', 'H', 'C', 'C', 'C', 'C', 'H', 'C', 'H', 'C', 'H', 'H', 'C', 'C', 'C', 'C', 'H', 'C', 'H', 'C', 'H', 'H', 'C', 'H', 'C', 'C', 'C', 'C', 'H', 'C', 'H', 'C', 'H', 'H', 'C', 'H', 'H', 'H', 'C', 'H', 'H', 'H', 'O', 'O', 'O', 'O', 'C', 'H', 'H', 'H', 'C', 'H', 'H', 'H', 'C', 'H', 'H', 'H', 'C', 'H', 'H', 'H']
Ligand atom label:  3  Ligand atom B nbo:  -0.48316
Ligand atom label:  40  Ligand atom A nbo:  -0.48217
Atom_a:  40 Atom_b:  3
C:\Users\George\Desktop\Research_UCLA\CIC\Computational Work\Project cluster version 2\project_catalyst_repurposing\structures_ligand_id\pd_me2_structures\ligand_xyz\ligand-365-n-n-62-ligand_xyz.txt
Ending node: 1
Starting node: 31
(4.394171, 0.119802, -0.047125)   31
(3.983763, -0.577207, 1.0268)   22
(2.549145, -0.960681, 1.063973)   0
(1.833971, -0.624213, 0.054341)   1
ligand-366-n-n-63

C:\Users\George\AppData\Local\Temp\ipykernel_7832\386804788.py:583: DeprecationWarning:

to_plotly_figure is deprecated and will be removed in version 4.0.0. Use MolGraph.to_plotly() instead.

C:\Users\George\AppData\Local\Temp\ipykernel_7832\386804788.py:589: DeprecationWarning:

to_networkx_graph is deprecated and will be removed in version 4.0.0. Use MolGraph.to_networkx() instead.

Pd number index:  0
['Pd', 'C', 'N', 'C', 'H', 'H', 'H', 'C', 'H', 'H', 'C', 'C', 'C', 'C', 'H', 'C', 'H', 'C', 'H', 'H', 'C', 'C', 'C', 'C', 'H', 'C', 'H', 'C', 'H', 'H', 'C', 'C', 'C', 'H', 'C', 'C', 'H', 'H', 'H', 'N', 'H', 'C', 'C', 'C', 'C', 'C', 'C', 'C', 'C', 'C', 'H', 'C', 'H', 'H', 'H', 'C', 'H', 'C', 'C', 'C', 'C', 'H', 'C', 'H', 'C', 'H', 'H', 'C', 'C', 'C', 'C', 'H', 'C', 'H', 'C', 'H', 'H', 'C', 'H', 'C', 'C', 'C', 'C', 'H', 'C', 'H', 'C', 'H', 'H', 'C', 'H', 'H', 'H', 'C', 'H', 'H', 'H', 'C', 'H', 'H', 'H', 'C', 'H', 'H', 'H', 'C', 'H', 'H', 'H', 'C', 'H', 'H', 'H']
Ligand atom label:  3  Ligand atom B nbo:  -0.485
Ligand atom label:  40  Ligand atom A nbo:  -0.48305
Atom_a:  40 Atom_b:  3
C:\Users\George\Desktop\Research_UCLA\CIC\Computational Work\Project cluster version 2\project_catalyst_repurposing\structures_ligand_id\pd_me2_structures\ligand_xyz\ligand-366-n-n-63-ligand_xyz.txt
Ending node: 1
Starting node: 31
(4.1627, 0.216241, 0.102836)   31
(3.690512, -0.356599, 1.223568)   22
(2.247412, -0.70791, 1.236087)   0
(1.577525, -0.443544, 0.174305)   1
ligand-367-n-n-64

C:\Users\George\AppData\Local\Temp\ipykernel_7832\386804788.py:583: DeprecationWarning:

to_plotly_figure is deprecated and will be removed in version 4.0.0. Use MolGraph.to_plotly() instead.

C:\Users\George\AppData\Local\Temp\ipykernel_7832\386804788.py:589: DeprecationWarning:

to_networkx_graph is deprecated and will be removed in version 4.0.0. Use MolGraph.to_networkx() instead.

Pd number index:  0
['Pd', 'C', 'N', 'C', 'H', 'H', 'H', 'C', 'H', 'H', 'C', 'C', 'C', 'C', 'H', 'C', 'H', 'C', 'H', 'H', 'C', 'C', 'C', 'C', 'H', 'C', 'H', 'C', 'H', 'H', 'C', 'C', 'C', 'H', 'C', 'C', 'H', 'H', 'H', 'N', 'H', 'C', 'C', 'C', 'C', 'C', 'C', 'C', 'C', 'C', 'H', 'C', 'H', 'H', 'H', 'C', 'H', 'C', 'C', 'C', 'C', 'H', 'C', 'H', 'C', 'H', 'H', 'C', 'C', 'C', 'C', 'H', 'C', 'H', 'C', 'H', 'H', 'C', 'H', 'C', 'C', 'C', 'C', 'H', 'C', 'H', 'C', 'H', 'H', 'C', 'H', 'H', 'H', 'C', 'H', 'H', 'H', 'F', 'F', 'F', 'F']
Ligand atom label:  3  Ligand atom B nbo:  -0.56735
Ligand atom label:  40  Ligand atom A nbo:  -0.57635
Atom_a:  3 Atom_b:  40
C:\Users\George\Desktop\Research_UCLA\CIC\Computational Work\Project cluster version 2\project_catalyst_repurposing\structures_ligand_id\pd_me2_structures\ligand_xyz\ligand-367-n-n-64-ligand_xyz.txt
Starting node: 1
Ending node: 31
(1.598369, -0.430413, 0.184658)   1
(2.28403, -0.665778, 1.24355)   0
(3.719419, -0.286326, 1.211416)   22
(4.174625, 0.257248, 0.068855)   31
ligand-368-n-n-65

C:\Users\George\AppData\Local\Temp\ipykernel_7832\386804788.py:583: DeprecationWarning:

to_plotly_figure is deprecated and will be removed in version 4.0.0. Use MolGraph.to_plotly() instead.

C:\Users\George\AppData\Local\Temp\ipykernel_7832\386804788.py:589: DeprecationWarning:

to_networkx_graph is deprecated and will be removed in version 4.0.0. Use MolGraph.to_networkx() instead.

Pd number index:  0
['Pd', 'C', 'N', 'C', 'H', 'H', 'C', 'H', 'H', 'H', 'C', 'H', 'H', 'C', 'C', 'C', 'C', 'C', 'C', 'H', 'H', 'C', 'H', 'H', 'H', 'H', 'C', 'C', 'C', 'H', 'C', 'C', 'H', 'H', 'H', 'N', 'H', 'C', 'H', 'C', 'C', 'C', 'C', 'H', 'C', 'C', 'H', 'H', 'H', 'C', 'C', 'C', 'C', 'H', 'C', 'C', 'H', 'H', 'H', 'C', 'H', 'H', 'C', 'H', 'H', 'C', 'H', 'C', 'C', 'C', 'C', 'H', 'C', 'C', 'H', 'H', 'H', 'C', 'C', 'C', 'C', 'C', 'H', 'C', 'H', 'H', 'H', 'C', 'H', 'H', 'C', 'H', 'H']
Ligand atom label:  3  Ligand atom A nbo:  -0.52311
Ligand atom label:  36  Ligand atom B nbo:  -0.50386
Atom_a:  36 Atom_b:  3
C:\Users\George\Desktop\Research_UCLA\CIC\Computational Work\Project cluster version 2\project_catalyst_repurposing\structures_ligand_id\pd_me2_structures\ligand_xyz\ligand-368-n-n-65-ligand_xyz.txt
Ending node: 1
Starting node: 27
(-0.541536, 3.134373, 0.457769)   27
(-0.402127, 2.81693, -0.843998)   18
(-0.150933, 1.387759, -1.153379)   0
(-0.018839, 0.595927, -0.14982)   1
ligand-369-n-n-66

C:\Users\George\AppData\Local\Temp\ipykernel_7832\386804788.py:583: DeprecationWarning:

to_plotly_figure is deprecated and will be removed in version 4.0.0. Use MolGraph.to_plotly() instead.

C:\Users\George\AppData\Local\Temp\ipykernel_7832\386804788.py:589: DeprecationWarning:

to_networkx_graph is deprecated and will be removed in version 4.0.0. Use MolGraph.to_networkx() instead.

Pd number index:  0
['Pd', 'C', 'N', 'C', 'H', 'H', 'C', 'H', 'H', 'H', 'C', 'H', 'H', 'H', 'C', 'C', 'C', 'H', 'C', 'C', 'H', 'H', 'H', 'N', 'H', 'C', 'C', 'C', 'C', 'H', 'C', 'C', 'H', 'H', 'H', 'C', 'C', 'C', 'C', 'C', 'H', 'C', 'H', 'H', 'H', 'C', 'H', 'H', 'C', 'H', 'H', 'C', 'C', 'C', 'C', 'C', 'C', 'C', 'C', 'C', 'H', 'C', 'H', 'H', 'H', 'C', 'H', 'C', 'H', 'C', 'C', 'C', 'C', 'H', 'C', 'C', 'H', 'H', 'H', 'C', 'C', 'C', 'C', 'C', 'H', 'C', 'H', 'H', 'H', 'C', 'H', 'H', 'C', 'H', 'H', 'C', 'C', 'C', 'C', 'H', 'C', 'H', 'C', 'H', 'H', 'C', 'H', 'H', 'H']
Ligand atom label:  3  Ligand atom B nbo:  -0.5132
Ligand atom label:  24  Ligand atom A nbo:  -0.49278
Atom_a:  24 Atom_b:  3
C:\Users\George\Desktop\Research_UCLA\CIC\Computational Work\Project cluster version 2\project_catalyst_repurposing\structures_ligand_id\pd_me2_structures\ligand_xyz\ligand-369-n-n-66-ligand_xyz.txt
Ending node: 1
Starting node: 15
(-4.347359, -0.025619, -0.275051)   15
(-3.772344, -0.411492, -1.428969)   6
(-2.292901, -0.547644, -1.433034)   0
(-1.687709, -0.433794, -0.304149)   1
ligand-370-n-n-70

C:\Users\George\AppData\Local\Temp\ipykernel_7832\386804788.py:583: DeprecationWarning:

to_plotly_figure is deprecated and will be removed in version 4.0.0. Use MolGraph.to_plotly() instead.

C:\Users\George\AppData\Local\Temp\ipykernel_7832\386804788.py:589: DeprecationWarning:

to_networkx_graph is deprecated and will be removed in version 4.0.0. Use MolGraph.to_networkx() instead.

Pd number index:  0
['Pd', 'C', 'C', 'N', 'N', 'C', 'C', 'C', 'C', 'C', 'C', 'H', 'H', 'C', 'C', 'C', 'C', 'C', 'C', 'H', 'H', 'C', 'H', 'H', 'H', 'C', 'H', 'H', 'H', 'C', 'H', 'C', 'H', 'C', 'C', 'C', 'C', 'H', 'C', 'H', 'C', 'H', 'H', 'H', 'C', 'C', 'C', 'C', 'H', 'C', 'H', 'C', 'H', 'H', 'H', 'C', 'C', 'C', 'C', 'H', 'C', 'H', 'C', 'H', 'H', 'H', 'C', 'C', 'C', 'C', 'H', 'C', 'H', 'C', 'H', 'H', 'H', 'C', 'H', 'C', 'H', 'C', 'C', 'C', 'C', 'H', 'C', 'H', 'C', 'H', 'H', 'H', 'C', 'C', 'C', 'C', 'H', 'C', 'H', 'C', 'H', 'H', 'H', 'C', 'C', 'C', 'C', 'H', 'C', 'H', 'C', 'H', 'H', 'H', 'C', 'C', 'C', 'C', 'H', 'C', 'H', 'C', 'H', 'H', 'H', 'O', 'H', 'O', 'H', 'C', 'H', 'H', 'H', 'C', 'H', 'H', 'H']
Ligand atom label:  4  Ligand atom B nbo:  -0.50119
Ligand atom label:  5  Ligand atom A nbo:  -0.50403
Atom_a:  4 Atom_b:  5
C:\Users\George\Desktop\Research_UCLA\CIC\Computational Work\Project cluster version 2\project_catalyst_repurposing\structures_ligand_id\pd_me2_structures\ligand_xyz\ligand-370-n-n-70-ligand_xyz.txt
Starting node: 2
Ending node: 3
(-1.315788, -0.295347, 0.210614)   2
(-0.743446, -0.375203, 1.359922)   0
(0.749829, -0.225256, 1.348876)   1
(1.318876, -0.28822, 0.1982)   3
ligand-376-c-o-12
Pd number index:  0
['Pd', 'C', 'C', 'C', 'H', 'N', 'N', 'C', 'C', 'C', 'C', 'C', 'C', 'H', 'H', 'C', 'C', 'H', 'H', 'C', 'C', 'C', 'H', 'H', 'H', 'C', 'H', 'H', 'H', 'H', 'C', 'H', 'H', 'C', 'H', 'H', 'H', 'S', 'O', 'O', 'O', 'C', 'H', 'H', 'H', 'H']
Ligand atom label:  2  Ligand atom A nbo:  0.27495
Ligand atom label:  41  Ligand atom B nbo:  -0.79984
Atom_a:  2 Atom_b:  41

C:\Users\George\AppData\Local\Temp\ipykernel_7832\386804788.py:583: DeprecationWarning:

to_plotly_figure is deprecated and will be removed in version 4.0.0. Use MolGraph.to_plotly() instead.

C:\Users\George\AppData\Local\Temp\ipykernel_7832\386804788.py:589: DeprecationWarning:

to_networkx_graph is deprecated and will be removed in version 4.0.0. Use MolGraph.to_networkx() instead.

C:\Users\George\Desktop\Research_UCLA\CIC\Computational Work\Project cluster version 2\project_catalyst_repurposing\structures_ligand_id\pd_me2_structures\ligand_xyz\ligand-376-c-o-12-ligand_xyz.txt
Starting node: 0
Ending node: 31
(0.307378, 0.477859, 0.070047)   0
(1.380338, 1.346177, -0.043241)   5
(2.736068, 1.037913, -0.050113)   19
(3.312662, -0.673248, 0.2065)   28
(2.478517, -1.452379, -0.757719)   31
ligand-377-c-o-13
Pd number index:  0
['Pd', 'C', 'C', 'C', 'H', 'N', 'N', 'C', 'C', 'C', 'C', 'C', 'C', 'H', 'H', 'C', 'C', 'H', 'H', 'C', 'C', 'C', 'H', 'H', 'H', 'C', 'H', 'H', 'H', 'H', 'C', 'S', 'O', 'O', 'O', 'C', 'H', 'H', 'H', 'C', 'H', 'H', 'H', 'C', 'H', 'H', 'H', 'H', 'H']

C:\Users\George\AppData\Local\Temp\ipykernel_7832\386804788.py:583: DeprecationWarning:

to_plotly_figure is deprecated and will be removed in version 4.0.0. Use MolGraph.to_plotly() instead.

C:\Users\George\AppData\Local\Temp\ipykernel_7832\386804788.py:589: DeprecationWarning:

to_networkx_graph is deprecated and will be removed in version 4.0.0. Use MolGraph.to_networkx() instead.

Ligand atom label:  2  Ligand atom A nbo:  0.28142
Ligand atom label:  35  Ligand atom B nbo:  -0.79904
Atom_a:  2 Atom_b:  35
C:\Users\George\Desktop\Research_UCLA\CIC\Computational Work\Project cluster version 2\project_catalyst_repurposing\structures_ligand_id\pd_me2_structures\ligand_xyz\ligand-377-c-o-13-ligand_xyz.txt
Starting node: 0
Ending node: 25
(0.874765, 0.500677, -0.093177)   0
(1.997273, 1.29573, -0.168343)   5
(3.309624, 0.916227, 0.079131)   19
(3.650231, -0.621701, 1.010126)   22
(3.039456, -1.726923, 0.22075)   25
ligand-378-n-n-71

C:\Users\George\AppData\Local\Temp\ipykernel_7832\386804788.py:583: DeprecationWarning:

to_plotly_figure is deprecated and will be removed in version 4.0.0. Use MolGraph.to_plotly() instead.

C:\Users\George\AppData\Local\Temp\ipykernel_7832\386804788.py:589: DeprecationWarning:

to_networkx_graph is deprecated and will be removed in version 4.0.0. Use MolGraph.to_networkx() instead.

Pd number index:  0
['Pd', 'C', 'C', 'N', 'N', 'C', 'C', 'C', 'C', 'C', 'C', 'H', 'H', 'C', 'C', 'C', 'C', 'C', 'C', 'H', 'H', 'C', 'H', 'H', 'H', 'C', 'H', 'H', 'H', 'C', 'H', 'H', 'H', 'C', 'H', 'H', 'H', 'O', 'C', 'H', 'H', 'H', 'O', 'C', 'H', 'H', 'H', 'C', 'H', 'C', 'H', 'C', 'C', 'C', 'C', 'H', 'C', 'H', 'C', 'H', 'H', 'H', 'C', 'C', 'C', 'C', 'H', 'C', 'H', 'C', 'H', 'H', 'H', 'C', 'C', 'C', 'C', 'H', 'C', 'H', 'C', 'H', 'H', 'H', 'C', 'C', 'C', 'C', 'H', 'C', 'H', 'C', 'H', 'H', 'H', 'C', 'H', 'H', 'H', 'C', 'H', 'H', 'H']
Ligand atom label:  4  Ligand atom A nbo:  -0.46673
Ligand atom label:  5  Ligand atom B nbo:  -0.4662
Atom_a:  5 Atom_b:  4
C:\Users\George\Desktop\Research_UCLA\CIC\Computational Work\Project cluster version 2\project_catalyst_repurposing\structures_ligand_id\pd_me2_structures\ligand_xyz\ligand-378-n-n-71-ligand_xyz.txt
Ending node: 2
Starting node: 3
(1.123418, 0.699312, 0.417806)   3
(0.632743, 0.39573, 1.567493)   1
(-0.63196, -0.396247, 1.566899)   0
(-1.122587, -0.698111, 0.416715)   2
ligand-379-n-n-72

C:\Users\George\AppData\Local\Temp\ipykernel_7832\386804788.py:583: DeprecationWarning:

to_plotly_figure is deprecated and will be removed in version 4.0.0. Use MolGraph.to_plotly() instead.

C:\Users\George\AppData\Local\Temp\ipykernel_7832\386804788.py:589: DeprecationWarning:

to_networkx_graph is deprecated and will be removed in version 4.0.0. Use MolGraph.to_networkx() instead.

Pd number index:  0
['Pd', 'C', 'C', 'N', 'N', 'C', 'C', 'C', 'C', 'C', 'C', 'H', 'H', 'C', 'C', 'C', 'C', 'C', 'C', 'H', 'H', 'C', 'H', 'H', 'H', 'C', 'H', 'H', 'H', 'C', 'H', 'H', 'H', 'C', 'H', 'H', 'H', 'C', 'H', 'C', 'H', 'C', 'C', 'C', 'C', 'H', 'C', 'H', 'C', 'H', 'H', 'H', 'C', 'C', 'C', 'C', 'H', 'C', 'H', 'C', 'H', 'H', 'H', 'C', 'C', 'C', 'C', 'H', 'C', 'H', 'C', 'H', 'H', 'H', 'C', 'C', 'C', 'C', 'H', 'C', 'H', 'C', 'H', 'H', 'H', 'C', 'H', 'H', 'H', 'C', 'H', 'H', 'H', 'C', 'H', 'H', 'H', 'C', 'H', 'H', 'H']
Ligand atom label:  4  Ligand atom A nbo:  -0.46658
Ligand atom label:  5  Ligand atom B nbo:  -0.4662
Atom_a:  5 Atom_b:  4
C:\Users\George\Desktop\Research_UCLA\CIC\Computational Work\Project cluster version 2\project_catalyst_repurposing\structures_ligand_id\pd_me2_structures\ligand_xyz\ligand-379-n-n-72-ligand_xyz.txt
Ending node: 2
Starting node: 3
(1.067855, 0.777846, 0.384481)   3
(0.596724, 0.448012, 1.534111)   1
(-0.59672, -0.448069, 1.534057)   0
(-1.067835, -0.777795, 0.38439)   2
ligand-380-n-n-73

C:\Users\George\AppData\Local\Temp\ipykernel_7832\386804788.py:583: DeprecationWarning:

to_plotly_figure is deprecated and will be removed in version 4.0.0. Use MolGraph.to_plotly() instead.

C:\Users\George\AppData\Local\Temp\ipykernel_7832\386804788.py:589: DeprecationWarning:

to_networkx_graph is deprecated and will be removed in version 4.0.0. Use MolGraph.to_networkx() instead.

Pd number index:  0
['Pd', 'C', 'C', 'N', 'N', 'C', 'C', 'C', 'C', 'C', 'C', 'H', 'H', 'C', 'C', 'C', 'C', 'C', 'C', 'H', 'H', 'C', 'H', 'H', 'H', 'C', 'H', 'H', 'H', 'C', 'H', 'H', 'H', 'C', 'H', 'H', 'H', 'C', 'H', 'C', 'H', 'C', 'C', 'C', 'C', 'H', 'C', 'H', 'C', 'H', 'H', 'H', 'C', 'C', 'C', 'C', 'H', 'C', 'H', 'C', 'H', 'H', 'H', 'C', 'C', 'C', 'C', 'H', 'C', 'H', 'C', 'H', 'H', 'H', 'C', 'C', 'C', 'C', 'H', 'C', 'H', 'C', 'H', 'H', 'H', 'C', 'H', 'H', 'H', 'C', 'H', 'H', 'H', 'Cl', 'Cl']
Ligand atom label:  4  Ligand atom B nbo:  -0.46773
Ligand atom label:  5  Ligand atom A nbo:  -0.46721
Atom_a:  5 Atom_b:  4
C:\Users\George\Desktop\Research_UCLA\CIC\Computational Work\Project cluster version 2\project_catalyst_repurposing\structures_ligand_id\pd_me2_structures\ligand_xyz\ligand-380-n-n-73-ligand_xyz.txt
Ending node: 2
Starting node: 3
(1.131621, 0.680496, 0.41768)   3
(0.633719, 0.394292, 1.568049)   1
(-0.63376, -0.394271, 1.568116)   0
(-1.13172, -0.680594, 0.417804)   2
ligand-381-n-n-74

C:\Users\George\AppData\Local\Temp\ipykernel_7832\386804788.py:583: DeprecationWarning:

to_plotly_figure is deprecated and will be removed in version 4.0.0. Use MolGraph.to_plotly() instead.

C:\Users\George\AppData\Local\Temp\ipykernel_7832\386804788.py:589: DeprecationWarning:

to_networkx_graph is deprecated and will be removed in version 4.0.0. Use MolGraph.to_networkx() instead.

Pd number index:  0
['Pd', 'C', 'C', 'N', 'N', 'C', 'C', 'C', 'C', 'C', 'C', 'H', 'H', 'C', 'C', 'C', 'C', 'C', 'C', 'H', 'H', 'C', 'H', 'H', 'H', 'C', 'H', 'H', 'H', 'C', 'H', 'H', 'H', 'C', 'H', 'H', 'H', 'C', 'H', 'C', 'H', 'C', 'C', 'C', 'C', 'H', 'C', 'H', 'C', 'H', 'H', 'H', 'C', 'C', 'C', 'C', 'H', 'C', 'H', 'C', 'H', 'H', 'H', 'C', 'C', 'C', 'C', 'H', 'C', 'H', 'C', 'H', 'H', 'H', 'C', 'C', 'C', 'C', 'H', 'C', 'H', 'C', 'H', 'H', 'H', 'C', 'H', 'H', 'H', 'C', 'H', 'H', 'H', 'N', 'N', 'O', 'O', 'O', 'O']
Ligand atom label:  4  Ligand atom A nbo:  -0.46767
Ligand atom label:  5  Ligand atom B nbo:  -0.46728
Atom_a:  5 Atom_b:  4
C:\Users\George\Desktop\Research_UCLA\CIC\Computational Work\Project cluster version 2\project_catalyst_repurposing\structures_ligand_id\pd_me2_structures\ligand_xyz\ligand-381-n-n-74-ligand_xyz.txt

C:\Users\George\AppData\Local\Temp\ipykernel_7832\386804788.py:583: DeprecationWarning:

to_plotly_figure is deprecated and will be removed in version 4.0.0. Use MolGraph.to_plotly() instead.

C:\Users\George\AppData\Local\Temp\ipykernel_7832\386804788.py:589: DeprecationWarning:

to_networkx_graph is deprecated and will be removed in version 4.0.0. Use MolGraph.to_networkx() instead.

Ending node: 2
Starting node: 3
(1.170584, 0.6068, 0.429277)   3
(0.649407, 0.367734, 1.578973)   1
(-0.649442, -0.367775, 1.578958)   0
(-1.170604, -0.606825, 0.429249)   2
ligand-382-n-n-75
Pd number index:  0
['Pd', 'C', 'C', 'N', 'N', 'C', 'C', 'C', 'C', 'C', 'C', 'H', 'H', 'C', 'C', 'C', 'C', 'C', 'C', 'H', 'H', 'C', 'H', 'H', 'H', 'C', 'H', 'H', 'H', 'C', 'H', 'H', 'H', 'C', 'H', 'H', 'H', 'C', 'H', 'C', 'H', 'C', 'C', 'C', 'C', 'H', 'C', 'H', 'C', 'H', 'H', 'H', 'C', 'C', 'C', 'C', 'H', 'C', 'H', 'C', 'H', 'H', 'H', 'C', 'C', 'C', 'C', 'H', 'C', 'H', 'C', 'H', 'H', 'H', 'C', 'C', 'C', 'C', 'H', 'C', 'H', 'C', 'H', 'H', 'H', 'C', 'H', 'H', 'H', 'C', 'H', 'H', 'H', 'C', 'C', 'C', 'C', 'C', 'C', 'H', 'C', 'C', 'C', 'H', 'C', 'H', 'H', 'H', 'H']
Ligand atom label:  4  Ligand atom A nbo:  -0.46926
Ligand atom label:  5  Ligand atom B nbo:  -0.4595
Atom_a:  5 Atom_b:  4
C:\Users\George\Desktop\Research_UCLA\CIC\Computational Work\Project cluster version 2\project_catalyst_repurposing\structures_ligand_id\pd_me2_structures\ligand_xyz\ligand-382-n-n-75-ligand_xyz.txt
Ending node: 2
Starting node: 3
(-1.126547, -0.294518, 0.780832)   3
(-0.61121, 0.832956, 0.453446)   1
(0.59859, 0.852342, -0.423191)   0
(1.121675, -0.259167, -0.791083)   2
ligand-383-p-n-19

C:\Users\George\AppData\Local\Temp\ipykernel_7832\386804788.py:583: DeprecationWarning:

to_plotly_figure is deprecated and will be removed in version 4.0.0. Use MolGraph.to_plotly() instead.

C:\Users\George\AppData\Local\Temp\ipykernel_7832\386804788.py:589: DeprecationWarning:

to_networkx_graph is deprecated and will be removed in version 4.0.0. Use MolGraph.to_networkx() instead.

Pd number index:  1
['P', 'Pd', 'C', 'H', 'H', 'H', 'C', 'H', 'H', 'H', 'N', 'C', 'C', 'H', 'C', 'C', 'H', 'H', 'H', 'H', 'H', 'H', 'C', 'C', 'C', 'H', 'H', 'H', 'C', 'H', 'H', 'H', 'C', 'H', 'H', 'H', 'C', 'C', 'H', 'H', 'H', 'C', 'H', 'H', 'H', 'C', 'H', 'H', 'H', 'C', 'C', 'C', 'C', 'C', 'C', 'H', 'H', 'H', 'C', 'H', 'C', 'H', 'C', 'H', 'H', 'H', 'C', 'H', 'H', 'H', 'C', 'H', 'H', 'H', 'C', 'H', 'H', 'H']
Ligand atom label:  1  Ligand atom B nbo:  1.02848
Ligand atom label:  11  Ligand atom A nbo:  -0.39679
Atom_a:  1 Atom_b:  11
C:\Users\George\Desktop\Research_UCLA\CIC\Computational Work\Project cluster version 2\project_catalyst_repurposing\structures_ligand_id\pd_me2_structures\ligand_xyz\ligand-383-p-n-19-ligand_xyz.txt
Starting node: 0
Ending node: 1
(-2.073237, 0.095849, -0.065688)   0
(-1.095987, 0.931901, -1.445706)   2
(0.36324, 0.552736, -1.402761)   13
(0.948475, 0.163528, -0.337011)   1
ligand-384-p-n-20

C:\Users\George\AppData\Local\Temp\ipykernel_7832\386804788.py:583: DeprecationWarning:

to_plotly_figure is deprecated and will be removed in version 4.0.0. Use MolGraph.to_plotly() instead.

C:\Users\George\AppData\Local\Temp\ipykernel_7832\386804788.py:589: DeprecationWarning:

to_networkx_graph is deprecated and will be removed in version 4.0.0. Use MolGraph.to_networkx() instead.

Pd number index:  1
['P', 'Pd', 'C', 'H', 'H', 'H', 'C', 'H', 'H', 'H', 'N', 'C', 'C', 'H', 'H', 'H', 'C', 'H', 'H', 'H', 'C', 'H', 'H', 'H', 'C', 'C', 'H', 'H', 'H', 'C', 'H', 'H', 'H', 'C', 'H', 'H', 'H', 'C', 'C', 'C', 'C', 'C', 'C', 'H', 'H', 'H', 'C', 'H', 'C', 'H', 'C', 'H', 'H', 'H', 'C', 'H', 'H', 'H', 'C', 'H', 'H', 'H', 'C', 'H', 'H', 'H', 'C', 'C', 'C', 'C', 'C', 'H', 'C', 'H', 'H', 'H', 'H', 'C', 'H', 'H', 'H', 'H']
Ligand atom label:  1  Ligand atom B nbo:  1.02574
Ligand atom label:  11  Ligand atom A nbo:  -0.47361
Atom_a:  1 Atom_b:  11
C:\Users\George\Desktop\Research_UCLA\CIC\Computational Work\Project cluster version 2\project_catalyst_repurposing\structures_ligand_id\pd_me2_structures\ligand_xyz\ligand-384-p-n-20-ligand_xyz.txt
Starting node: 0
Ending node: 1
(2.098593, -0.066638, -0.075924)   0
(1.093854, 1.440519, 0.459687)   57
(-0.358662, 1.108645, 0.692291)   59
(-0.965074, 0.17622, 0.066482)   1
ligand-385-p-n-21

C:\Users\George\AppData\Local\Temp\ipykernel_7832\386804788.py:583: DeprecationWarning:

to_plotly_figure is deprecated and will be removed in version 4.0.0. Use MolGraph.to_plotly() instead.

C:\Users\George\AppData\Local\Temp\ipykernel_7832\386804788.py:589: DeprecationWarning:

to_networkx_graph is deprecated and will be removed in version 4.0.0. Use MolGraph.to_networkx() instead.

Pd number index:  1
['P', 'Pd', 'C', 'H', 'H', 'H', 'C', 'H', 'H', 'H', 'N', 'C', 'C', 'C', 'C', 'C', 'C', 'H', 'H', 'H', 'C', 'H', 'C', 'H', 'C', 'H', 'H', 'H', 'C', 'H', 'H', 'H', 'C', 'H', 'H', 'H', 'C', 'H', 'H', 'H', 'C', 'C', 'C', 'C', 'C', 'H', 'C', 'H', 'H', 'H', 'H', 'C', 'H', 'H', 'H', 'C', 'C', 'C', 'C', 'H', 'C', 'H', 'C', 'H', 'H', 'H', 'C', 'C', 'C', 'C', 'H', 'C', 'H', 'C', 'H', 'H', 'H', 'H']
Ligand atom label:  1  Ligand atom B nbo:  0.9858
Ligand atom label:  11  Ligand atom A nbo:  -0.50912
Atom_a:  1 Atom_b:  11
C:\Users\George\Desktop\Research_UCLA\CIC\Computational Work\Project cluster version 2\project_catalyst_repurposing\structures_ligand_id\pd_me2_structures\ligand_xyz\ligand-385-p-n-21-ligand_xyz.txt
Starting node: 0
Ending node: 1
(-1.71434, -0.135156, -0.227467)   0
(-0.833013, -1.008663, 1.189468)   31
(0.615902, -0.583033, 1.191449)   33
(1.255876, -0.328916, 0.118266)   1
ligand-386-p-n-22

C:\Users\George\AppData\Local\Temp\ipykernel_7832\386804788.py:583: DeprecationWarning:

to_plotly_figure is deprecated and will be removed in version 4.0.0. Use MolGraph.to_plotly() instead.

C:\Users\George\AppData\Local\Temp\ipykernel_7832\386804788.py:589: DeprecationWarning:

to_networkx_graph is deprecated and will be removed in version 4.0.0. Use MolGraph.to_networkx() instead.

Pd number index:  1
['P', 'Pd', 'C', 'H', 'H', 'H', 'C', 'H', 'H', 'H', 'N', 'C', 'C', 'C', 'C', 'C', 'C', 'C', 'C', 'H', 'H', 'C', 'C', 'C', 'C', 'C', 'C', 'H', 'H', 'C', 'H', 'H', 'H', 'C', 'H', 'H', 'H', 'C', 'H', 'H', 'H', 'C', 'H', 'H', 'H', 'C', 'H', 'H', 'H', 'C', 'H', 'H', 'H', 'H', 'C', 'H', 'H', 'H', 'C', 'H', 'H', 'H', 'C', 'H', 'H', 'H']
Ligand atom label:  1  Ligand atom B nbo:  0.98846
Ligand atom label:  11  Ligand atom A nbo:  -0.47104
Atom_a:  1 Atom_b:  11
C:\Users\George\Desktop\Research_UCLA\CIC\Computational Work\Project cluster version 2\project_catalyst_repurposing\structures_ligand_id\pd_me2_structures\ligand_xyz\ligand-386-p-n-22-ligand_xyz.txt
Starting node: 0
Ending node: 1
(-1.356794, -0.800455, -0.422771)   0
(-0.578209, -1.626427, 1.127432)   2
(0.834862, -1.122027, 1.275716)   3
(1.46624, -0.396975, 0.442626)   1
ligand-387-p-n-23

C:\Users\George\AppData\Local\Temp\ipykernel_7832\386804788.py:583: DeprecationWarning:

to_plotly_figure is deprecated and will be removed in version 4.0.0. Use MolGraph.to_plotly() instead.

C:\Users\George\AppData\Local\Temp\ipykernel_7832\386804788.py:589: DeprecationWarning:

to_networkx_graph is deprecated and will be removed in version 4.0.0. Use MolGraph.to_networkx() instead.

Pd number index:  1
['P', 'Pd', 'C', 'H', 'H', 'H', 'C', 'H', 'H', 'H', 'N', 'C', 'C', 'C', 'C', 'C', 'C', 'C', 'C', 'H', 'H', 'C', 'C', 'C', 'C', 'C', 'C', 'H', 'H', 'C', 'H', 'H', 'H', 'C', 'H', 'H', 'H', 'C', 'H', 'H', 'H', 'C', 'H', 'H', 'H', 'C', 'H', 'H', 'H', 'C', 'H', 'H', 'H', 'C', 'H', 'H', 'H', 'C', 'H', 'H', 'H', 'C', 'H', 'H', 'H', 'C', 'C', 'C', 'C', 'H', 'C', 'H', 'C', 'H', 'H', 'H']
Ligand atom label:  1  Ligand atom B nbo:  0.99434
Ligand atom label:  11  Ligand atom A nbo:  -0.51707
Atom_a:  1 Atom_b:  11
C:\Users\George\Desktop\Research_UCLA\CIC\Computational Work\Project cluster version 2\project_catalyst_repurposing\structures_ligand_id\pd_me2_structures\ligand_xyz\ligand-387-p-n-23-ligand_xyz.txt
Starting node: 0
Ending node: 1
(-1.693828, -0.46936, 0.919858)   0
(-0.671562, 1.125417, 1.253138)   2
(0.68297, 0.997311, 0.543571)   3
(1.178102, -0.156808, 0.277387)   1
ligand-388-p-n-24
Pd number index:  1
['P', 'Pd', 'C', 'H', 'H', 'H', 'C', 'H', 'H', 'N', 'C', 'C', 'C', 'C', 'C', 'C', 'C', 'C', 'H', 'H', 'C', 'H', 'H', 'H', 'C', 'H', 'H', 'H', 'C', 'H', 'H', 'H', 'C', 'H', 'H', 'H', 'C', 'H', 'H', 'H', 'C', 'H', 'H', 'H', 'C', 'C', 'C', 'C', 'H', 'C', 'H', 'C', 'H', 'H', 'H', 'C', 'H', 'H', 'H', 'H']

C:\Users\George\AppData\Local\Temp\ipykernel_7832\386804788.py:583: DeprecationWarning:

to_plotly_figure is deprecated and will be removed in version 4.0.0. Use MolGraph.to_plotly() instead.

C:\Users\George\AppData\Local\Temp\ipykernel_7832\386804788.py:589: DeprecationWarning:

to_networkx_graph is deprecated and will be removed in version 4.0.0. Use MolGraph.to_networkx() instead.

Ligand atom label:  1  Ligand atom B nbo:  0.96363
Ligand atom label:  10  Ligand atom A nbo:  -0.45359
Atom_a:  1 Atom_b:  10
C:\Users\George\Desktop\Research_UCLA\CIC\Computational Work\Project cluster version 2\project_catalyst_repurposing\structures_ligand_id\pd_me2_structures\ligand_xyz\ligand-388-p-n-24-ligand_xyz.txt

C:\Users\George\AppData\Local\Temp\ipykernel_7832\386804788.py:583: DeprecationWarning:

to_plotly_figure is deprecated and will be removed in version 4.0.0. Use MolGraph.to_plotly() instead.

C:\Users\George\AppData\Local\Temp\ipykernel_7832\386804788.py:589: DeprecationWarning:

to_networkx_graph is deprecated and will be removed in version 4.0.0. Use MolGraph.to_networkx() instead.

Starting node: 0
Ending node: 1
(2.589183, 0.781304, 0.525437)   0
(1.325115, 1.87923, -0.383975)   2
(-0.026854, 1.19508, -0.171954)   3
(-0.071601, -0.087918, -0.100851)   1
ligand-389-p-n-25
Pd number index:  1
['P', 'Pd', 'C', 'H', 'H', 'H', 'C', 'H', 'H', 'N', 'C', 'C', 'C', 'C', 'C', 'C', 'C', 'C', 'H', 'H', 'C', 'H', 'H', 'H', 'C', 'H', 'H', 'H', 'C', 'H', 'H', 'H', 'C', 'H', 'H', 'H', 'C', 'H', 'H', 'H', 'C', 'C', 'C', 'C', 'H', 'C', 'H', 'C', 'H', 'H', 'H', 'C', 'C', 'C', 'C', 'H', 'C', 'H', 'C', 'H', 'H', 'H', 'C', 'C', 'C', 'C', 'H', 'C', 'H', 'C', 'H', 'H', 'H', 'H']
Ligand atom label:  1  Ligand atom B nbo:  1.00823
Ligand atom label:  10  Ligand atom A nbo:  -0.50187
Atom_a:  1 Atom_b:  10
C:\Users\George\Desktop\Research_UCLA\CIC\Computational Work\Project cluster version 2\project_catalyst_repurposing\structures_ligand_id\pd_me2_structures\ligand_xyz\ligand-389-p-n-25-ligand_xyz.txt
Starting node: 0
Ending node: 1
(1.800401, -0.067094, -0.027668)   0
(0.828505, 1.148684, -1.137722)   2
(-0.632964, 0.960096, -0.721878)   3
(-1.023137, -0.226788, -0.413803)   1
ligand-390-p-n-26
Pd number index:  33
['P', 'C', 'H', 'H', 'C', 'C', 'C', 'H', 'C', 'C', 'H', 'H', 'N', 'C', 'C', 'C', 'C', 'C', 'C', 'H', 'H', 'C', 'H', 'H', 'H', 'C', 'H', 'H', 'H', 'C', 'H', 'H', 'H', 'Pd', 'C', 'H', 'H', 'H', 'C', 'H', 'H', 'H', 'C', 'C', 'C', 'C', 'C', 'C', 'H', 'H', 'C', 'C', 'C', 'C', 'C', 'C', 'H', 'H', 'C', 'H', 'H', 'H', 'C', 'H', 'H', 'H', 'C', 'H', 'H', 'H', 'C', 'H', 'H', 'H', 'C', 'H', 'H', 'H', 'C', 'H', 'H', 'H']

C:\Users\George\AppData\Local\Temp\ipykernel_7832\386804788.py:583: DeprecationWarning:

to_plotly_figure is deprecated and will be removed in version 4.0.0. Use MolGraph.to_plotly() instead.

C:\Users\George\AppData\Local\Temp\ipykernel_7832\386804788.py:589: DeprecationWarning:

to_networkx_graph is deprecated and will be removed in version 4.0.0. Use MolGraph.to_networkx() instead.

Ligand atom label:  1  Ligand atom A nbo:  1.0334
Ligand atom label:  13  Ligand atom B nbo:  -0.50259
Atom_a:  1 Atom_b:  13
C:\Users\George\Desktop\Research_UCLA\CIC\Computational Work\Project cluster version 2\project_catalyst_repurposing\structures_ligand_id\pd_me2_structures\ligand_xyz\ligand-390-p-n-26-ligand_xyz.txt

C:\Users\George\AppData\Local\Temp\ipykernel_7832\386804788.py:583: DeprecationWarning:

to_plotly_figure is deprecated and will be removed in version 4.0.0. Use MolGraph.to_plotly() instead.

C:\Users\George\AppData\Local\Temp\ipykernel_7832\386804788.py:589: DeprecationWarning:

to_networkx_graph is deprecated and will be removed in version 4.0.0. Use MolGraph.to_networkx() instead.

Starting node: 0
Ending node: 12
(-1.359932, -0.103163, 0.164288)   0
(-0.750337, -0.283781, 1.926408)   1
(0.63841, 0.199557, 2.211092)   4
(1.588046, 0.010992, 1.275901)   12
ligand-391-p-n-27
Pd number index:  33
['P', 'C', 'H', 'H', 'C', 'C', 'C', 'H', 'C', 'C', 'H', 'H', 'N', 'C', 'C', 'C', 'C', 'C', 'C', 'H', 'H', 'C', 'H', 'H', 'H', 'C', 'H', 'H', 'H', 'C', 'H', 'H', 'H', 'Pd', 'C', 'H', 'H', 'H', 'C', 'H', 'H', 'H', 'C', 'C', 'C', 'C', 'C', 'C', 'H', 'H', 'C', 'C', 'C', 'C', 'C', 'C', 'H', 'H', 'C', 'H', 'H', 'H', 'C', 'H', 'H', 'H', 'H', 'H', 'H', 'H']
Ligand atom label:  1  Ligand atom B nbo:  1.03281
Ligand atom label:  13  Ligand atom A nbo:  -0.49783
Atom_a:  1 Atom_b:  13
C:\Users\George\Desktop\Research_UCLA\CIC\Computational Work\Project cluster version 2\project_catalyst_repurposing\structures_ligand_id\pd_me2_structures\ligand_xyz\ligand-391-p-n-27-ligand_xyz.txt
Starting node: 0
Ending node: 12
(-1.773116, 0.045997, 0.193321)   0
(-1.420815, -0.006265, 2.021838)   1
(-0.011942, -0.463202, 2.260815)   4
(0.929821, -0.086167, 1.374678)   12
ligand-392-p-o-135
Pd number index:  33
['P', 'C', 'C', 'S', 'O', 'O', 'C', 'C', 'C', 'C', 'C', 'C', 'H', 'H', 'H', 'C', 'C', 'C', 'C', 'C', 'H', 'H', 'H', 'H', 'C', 'C', 'C', 'C', 'C', 'H', 'H', 'H', 'H', 'Pd', 'C', 'H', 'H', 'H', 'C', 'H', 'H', 'H', 'O', 'O', 'C', 'H', 'H', 'H', 'C', 'H', 'H', 'H', 'H', 'N', 'H', 'C', 'C', 'C', 'C', 'H', 'C', 'H', 'C', 'H', 'H', 'H']

C:\Users\George\AppData\Local\Temp\ipykernel_7832\386804788.py:583: DeprecationWarning:

to_plotly_figure is deprecated and will be removed in version 4.0.0. Use MolGraph.to_plotly() instead.

C:\Users\George\AppData\Local\Temp\ipykernel_7832\386804788.py:589: DeprecationWarning:

to_networkx_graph is deprecated and will be removed in version 4.0.0. Use MolGraph.to_networkx() instead.

Ligand atom label:  1  Ligand atom B nbo:  0.97283
Ligand atom label:  5  Ligand atom A nbo:  -0.88239
Atom_a:  1 Atom_b:  5
C:\Users\George\Desktop\Research_UCLA\CIC\Computational Work\Project cluster version 2\project_catalyst_repurposing\structures_ligand_id\pd_me2_structures\ligand_xyz\ligand-392-p-o-135-ligand_xyz.txt
Starting node: 0
Ending node: 4
(-1.220552, 0.167791, 0.229646)   0
(-0.004696, 0.307872, 1.632152)   1
(1.348051, 0.631582, 1.411896)   2
(1.919738, 0.949264, -0.261099)   3
(1.897686, -0.314613, -1.006582)   4

C:\Users\George\AppData\Local\Temp\ipykernel_7832\386804788.py:583: DeprecationWarning:

to_plotly_figure is deprecated and will be removed in version 4.0.0. Use MolGraph.to_plotly() instead.

C:\Users\George\AppData\Local\Temp\ipykernel_7832\386804788.py:589: DeprecationWarning:

to_networkx_graph is deprecated and will be removed in version 4.0.0. Use MolGraph.to_networkx() instead.

ligand-393-p-o-136
Pd number index:  33
['P', 'C', 'C', 'S', 'O', 'O', 'C', 'C', 'C', 'C', 'C', 'C', 'H', 'H', 'H', 'C', 'C', 'C', 'C', 'C', 'H', 'H', 'H', 'H', 'C', 'C', 'C', 'C', 'C', 'H', 'H', 'H', 'H', 'Pd', 'C', 'H', 'H', 'H', 'C', 'H', 'H', 'H', 'O', 'O', 'C', 'H', 'H', 'H', 'C', 'H', 'H', 'H', 'H', 'N', 'H', 'C', 'C', 'C', 'C', 'C', 'C', 'H', 'H', 'H', 'C', 'H', 'C', 'H', 'H', 'H', 'C', 'H', 'H', 'H', 'C', 'H', 'C', 'H', 'H', 'H', 'C', 'H', 'H', 'H']
Ligand atom label:  1  Ligand atom B nbo:  0.96479
Ligand atom label:  5  Ligand atom A nbo:  -0.87414
Atom_a:  1 Atom_b:  5
C:\Users\George\Desktop\Research_UCLA\CIC\Computational Work\Project cluster version 2\project_catalyst_repurposing\structures_ligand_id\pd_me2_structures\ligand_xyz\ligand-393-p-o-136-ligand_xyz.txt
Starting node: 0
Ending node: 4
(-1.837871, -0.024077, 0.273806)   0
(-0.914165, -1.025364, 1.548719)   1
(0.473439, -0.895457, 1.748659)   2
(1.371904, 0.298562, 0.756041)   3
(1.414284, -0.171849, -0.636645)   4
ligand-394-p-o-137

C:\Users\George\AppData\Local\Temp\ipykernel_7832\386804788.py:583: DeprecationWarning:

to_plotly_figure is deprecated and will be removed in version 4.0.0. Use MolGraph.to_plotly() instead.

C:\Users\George\AppData\Local\Temp\ipykernel_7832\386804788.py:589: DeprecationWarning:

to_networkx_graph is deprecated and will be removed in version 4.0.0. Use MolGraph.to_networkx() instead.

Pd number index:  33
['P', 'C', 'C', 'S', 'O', 'O', 'C', 'C', 'C', 'C', 'C', 'C', 'H', 'H', 'H', 'C', 'C', 'C', 'C', 'C', 'H', 'H', 'H', 'H', 'C', 'C', 'C', 'C', 'C', 'H', 'H', 'H', 'H', 'Pd', 'C', 'H', 'H', 'H', 'C', 'H', 'H', 'H', 'O', 'O', 'C', 'H', 'H', 'H', 'C', 'H', 'H', 'H', 'H', 'N', 'H', 'C', 'C', 'C', 'C', 'C', 'C', 'H', 'H', 'H', 'C', 'H', 'F', 'F', 'F']
Ligand atom label:  1  Ligand atom B nbo:  0.97135
Ligand atom label:  5  Ligand atom A nbo:  -0.88335
Atom_a:  1 Atom_b:  5
C:\Users\George\Desktop\Research_UCLA\CIC\Computational Work\Project cluster version 2\project_catalyst_repurposing\structures_ligand_id\pd_me2_structures\ligand_xyz\ligand-394-p-o-137-ligand_xyz.txt

C:\Users\George\AppData\Local\Temp\ipykernel_7832\386804788.py:583: DeprecationWarning:

to_plotly_figure is deprecated and will be removed in version 4.0.0. Use MolGraph.to_plotly() instead.

C:\Users\George\AppData\Local\Temp\ipykernel_7832\386804788.py:589: DeprecationWarning:

to_networkx_graph is deprecated and will be removed in version 4.0.0. Use MolGraph.to_networkx() instead.

Starting node: 0
Ending node: 4
(1.67724, -0.001447, 0.269601)   0
(0.615884, 0.78254, 1.588036)   1
(-0.757213, 0.49885, 1.717998)   2
(-1.468051, -0.748823, 0.648716)   3
(-1.578102, -0.247015, -0.725661)   4
ligand-395-p-n-28
Pd number index:  11
['P', 'C', 'C', 'C', 'C', 'C', 'C', 'H', 'H', 'H', 'H', 'Pd', 'P', 'C', 'H', 'H', 'H', 'C', 'H', 'H', 'H', 'C', 'H', 'C', 'H', 'N', 'C', 'C', 'C', 'C', 'C', 'C', 'H', 'H', 'C', 'H', 'H', 'H', 'C', 'H', 'H', 'H', 'C', 'H', 'H', 'H', 'C', 'C', 'C', 'C', 'H', 'C', 'H', 'C', 'H', 'H', 'H', 'C', 'C', 'C', 'C', 'H', 'C', 'H', 'C', 'H', 'H', 'H', 'C', 'H', 'H', 'H', 'C', 'H', 'H', 'H', 'C', 'H', 'H', 'H', 'C', 'H', 'H', 'H']
Ligand atom label:  1  Ligand atom B nbo:  0.95963
Ligand atom label:  26  Ligand atom A nbo:  -1.11543
Atom_a:  1 Atom_b:  26
C:\Users\George\Desktop\Research_UCLA\CIC\Computational Work\Project cluster version 2\project_catalyst_repurposing\structures_ligand_id\pd_me2_structures\ligand_xyz\ligand-395-p-n-28-ligand_xyz.txt
Starting node: 0
Ending node: 16
(2.417061, -0.461248, -0.541525)   0
(1.526955, 0.428787, -1.929115)   1
(0.318358, 1.135017, -1.698322)   2
(-0.621708, 1.019275, -0.111362)   11
(-0.89948, -0.459769, 0.415624)   16
ligand-396-p-n-29

C:\Users\George\AppData\Local\Temp\ipykernel_7832\386804788.py:583: DeprecationWarning:

to_plotly_figure is deprecated and will be removed in version 4.0.0. Use MolGraph.to_plotly() instead.

C:\Users\George\AppData\Local\Temp\ipykernel_7832\386804788.py:589: DeprecationWarning:

to_networkx_graph is deprecated and will be removed in version 4.0.0. Use MolGraph.to_networkx() instead.

Pd number index:  11
['P', 'C', 'C', 'C', 'C', 'C', 'C', 'H', 'H', 'H', 'H', 'Pd', 'P', 'C', 'H', 'H', 'H', 'C', 'H', 'H', 'H', 'N', 'C', 'C', 'C', 'C', 'C', 'C', 'H', 'H', 'C', 'H', 'H', 'H', 'C', 'H', 'H', 'H', 'C', 'H', 'H', 'H', 'C', 'C', 'C', 'C', 'H', 'C', 'H', 'C', 'H', 'H', 'H', 'C', 'C', 'C', 'C', 'H', 'C', 'H', 'C', 'H', 'H', 'H', 'C', 'C', 'C', 'C', 'H', 'C', 'C', 'H', 'H', 'H', 'C', 'C', 'C', 'C', 'H', 'C', 'C', 'H', 'H', 'H', 'O', 'O', 'C', 'H', 'H', 'H', 'C', 'H', 'H', 'H']
Ligand atom label:  1  Ligand atom B nbo:  0.99201
Ligand atom label:  22  Ligand atom A nbo:  -1.11603
Atom_a:  1 Atom_b:  22
C:\Users\George\Desktop\Research_UCLA\CIC\Computational Work\Project cluster version 2\project_catalyst_repurposing\structures_ligand_id\pd_me2_structures\ligand_xyz\ligand-396-p-n-29-ligand_xyz.txt
Starting node: 0
Ending node: 12
(-1.771243, -0.301587, 0.336462)   0
(-0.848337, -0.075677, 1.929744)   1
(0.375142, 0.637719, 1.95476)   2
(1.305251, 1.03253, 0.406971)   11
(1.570092, -0.220312, -0.545945)   12
ligand-397-p-n-30

C:\Users\George\AppData\Local\Temp\ipykernel_7832\386804788.py:583: DeprecationWarning:

to_plotly_figure is deprecated and will be removed in version 4.0.0. Use MolGraph.to_plotly() instead.

C:\Users\George\AppData\Local\Temp\ipykernel_7832\386804788.py:589: DeprecationWarning:

to_networkx_graph is deprecated and will be removed in version 4.0.0. Use MolGraph.to_networkx() instead.

Pd number index:  11
['P', 'C', 'C', 'C', 'C', 'C', 'C', 'H', 'H', 'H', 'H', 'Pd', 'P', 'C', 'H', 'H', 'H', 'C', 'H', 'H', 'H', 'N', 'C', 'C', 'C', 'C', 'C', 'C', 'H', 'H', 'C', 'H', 'C', 'H', 'C', 'C', 'C', 'C', 'H', 'C', 'H', 'C', 'H', 'H', 'H', 'C', 'C', 'C', 'C', 'H', 'C', 'H', 'C', 'H', 'H', 'H', 'C', 'C', 'C', 'C', 'H', 'C', 'C', 'H', 'H', 'H', 'C', 'C', 'C', 'C', 'H', 'C', 'C', 'H', 'H', 'H', 'O', 'O', 'C', 'H', 'H', 'H', 'C', 'H', 'H', 'H', 'H', 'C', 'H', 'H', 'H', 'C', 'H', 'H', 'H', 'C', 'H', 'H', 'H', 'C', 'H', 'H', 'H']
Ligand atom label:  1  Ligand atom B nbo:  0.98566
Ligand atom label:  22  Ligand atom A nbo:  -1.12432
Atom_a:  1 Atom_b:  22
C:\Users\George\Desktop\Research_UCLA\CIC\Computational Work\Project cluster version 2\project_catalyst_repurposing\structures_ligand_id\pd_me2_structures\ligand_xyz\ligand-397-p-n-30-ligand_xyz.txt
Starting node: 0
Ending node: 12
(-1.927414, -0.061236, 0.210834)   0
(-1.147608, -0.311455, 1.873936)   1
(0.203732, 0.053731, 2.08715)   2
(1.309573, 0.634219, 0.717501)   11
(1.446961, -0.341803, -0.540175)   12
ligand-398-n-n-76

C:\Users\George\AppData\Local\Temp\ipykernel_7832\386804788.py:583: DeprecationWarning:

to_plotly_figure is deprecated and will be removed in version 4.0.0. Use MolGraph.to_plotly() instead.

C:\Users\George\AppData\Local\Temp\ipykernel_7832\386804788.py:589: DeprecationWarning:

to_networkx_graph is deprecated and will be removed in version 4.0.0. Use MolGraph.to_networkx() instead.

Pd number index:  0
['Pd', 'C', 'C', 'N', 'N', 'C', 'C', 'C', 'C', 'C', 'C', 'H', 'H', 'C', 'C', 'C', 'C', 'C', 'C', 'H', 'H', 'C', 'H', 'H', 'H', 'C', 'H', 'H', 'H', 'C', 'H', 'C', 'C', 'H', 'H', 'H', 'C', 'H', 'H', 'H', 'C', 'H', 'H', 'H', 'C', 'C', 'H', 'H', 'H', 'H', 'H', 'H', 'C', 'H', 'H', 'H', 'C', 'H', 'H', 'H', 'C', 'H', 'H', 'H', 'C', 'H', 'H', 'H', 'C', 'H', 'H', 'H', 'C', 'H', 'H', 'H', 'C', 'H', 'H', 'H', 'C', 'H', 'H', 'H']
Ligand atom label:  4  Ligand atom B nbo:  -0.75972
Ligand atom label:  5  Ligand atom A nbo:  -0.53599
Atom_a:  5 Atom_b:  4
C:\Users\George\Desktop\Research_UCLA\CIC\Computational Work\Project cluster version 2\project_catalyst_repurposing\structures_ligand_id\pd_me2_structures\ligand_xyz\ligand-398-n-n-76-ligand_xyz.txt
Ending node: 2
Starting node: 3
(1.360215, -0.301979, 0.464575)   3
(0.807011, -0.106589, 1.603281)   1
(-0.658016, -0.542899, 1.812048)   0
(-1.422909, -0.522296, 0.516888)   2
ligand-399-n-n-77
Pd number index:  0
['Pd', 'C', 'C', 'N', 'N', 'C', 'C', 'C', 'C', 'C', 'C', 'H', 'H', 'C', 'C', 'C', 'C', 'C', 'C', 'H', 'H', 'C', 'H', 'H', 'H', 'C', 'H', 'H', 'H', 'C', 'H', 'C', 'H', 'C', 'H', 'H', 'H', 'C', 'H', 'H', 'H', 'C', 'H', 'H', 'H', 'C', 'H', 'C', 'H', 'H', 'H', 'H', 'H', 'H', 'H', 'H', 'H', 'H', 'H', 'H']

C:\Users\George\AppData\Local\Temp\ipykernel_7832\386804788.py:583: DeprecationWarning:

to_plotly_figure is deprecated and will be removed in version 4.0.0. Use MolGraph.to_plotly() instead.

C:\Users\George\AppData\Local\Temp\ipykernel_7832\386804788.py:589: DeprecationWarning:

to_networkx_graph is deprecated and will be removed in version 4.0.0. Use MolGraph.to_networkx() instead.

Ligand atom label:  4  Ligand atom B nbo:  -0.77073
Ligand atom label:  5  Ligand atom A nbo:  -0.5315
Atom_a:  5 Atom_b:  4
C:\Users\George\Desktop\Research_UCLA\CIC\Computational Work\Project cluster version 2\project_catalyst_repurposing\structures_ligand_id\pd_me2_structures\ligand_xyz\ligand-399-n-n-77-ligand_xyz.txt
Ending node: 2
Starting node: 3
(1.261003, 0.513065, 0.059035)   3
(0.650363, 1.637005, 0.033627)   1
(-0.763847, 1.729036, 0.634638)   0
(-1.474303, 0.413628, 0.605044)   2
ligand-400-n-n-78

C:\Users\George\AppData\Local\Temp\ipykernel_7832\386804788.py:583: DeprecationWarning:

to_plotly_figure is deprecated and will be removed in version 4.0.0. Use MolGraph.to_plotly() instead.

C:\Users\George\AppData\Local\Temp\ipykernel_7832\386804788.py:589: DeprecationWarning:

to_networkx_graph is deprecated and will be removed in version 4.0.0. Use MolGraph.to_networkx() instead.

Pd number index:  0
['Pd', 'C', 'C', 'N', 'N', 'C', 'C', 'C', 'C', 'C', 'C', 'H', 'H', 'C', 'C', 'C', 'C', 'C', 'C', 'H', 'H', 'C', 'H', 'H', 'H', 'C', 'H', 'H', 'H', 'C', 'H', 'C', 'H', 'C', 'H', 'C', 'C', 'C', 'C', 'C', 'C', 'H', 'C', 'C', 'C', 'H', 'C', 'H', 'H', 'H', 'H', 'C', 'H', 'C', 'H', 'H', 'H', 'C', 'H', 'H', 'H', 'C', 'H', 'H', 'H', 'C', 'H', 'H', 'H', 'C', 'H', 'H', 'H', 'C', 'H', 'H', 'H', 'C', 'H', 'H', 'H', 'C', 'H', 'H', 'H', 'C', 'C', 'C', 'C', 'H', 'C', 'C', 'H', 'H', 'C', 'C', 'C', 'C', 'C', 'H', 'C', 'H', 'H', 'O', 'O', 'C', 'C', 'C', 'C', 'C', 'C', 'H', 'H', 'H', 'C', 'C', 'C', 'C', 'C', 'C', 'H', 'H', 'H', 'C', 'H', 'H', 'C', 'C', 'C', 'C', 'H', 'C', 'H', 'C', 'H', 'H', 'C', 'C', 'C', 'C', 'H', 'C', 'H', 'C', 'H', 'H', 'H', 'C', 'H', 'H', 'C', 'C', 'C', 'C', 'H', 'C', 'H', 'C', 'H', 'H', 'C', 'C', 'C', 'C', 'H', 'C', 'H', 'C', 'H', 'H', 'H']
Ligand atom label:  4  Ligand atom B nbo:  -0.51804
Ligand atom label:  5  Ligand atom A nbo:  -0.48616
Atom_a:  5 Atom_b:  4
C:\Users\George\Desktop\Research_UCLA\CIC\Computational Work\Project cluster version 2\project_catalyst_repurposing\structures_ligand_id\pd_me2_structures\ligand_xyz\ligand-400-n-n-78-ligand_xyz.txt
Ending node: 2
Starting node: 3
(-1.132378, 0.478218, 0.053114)   3
(-0.785729, -0.469812, 0.837498)   1
(0.59272, -1.03947, 0.72792)   0
(1.427073, -0.48998, -0.074582)   2
ligand-401-n-n-79

C:\Users\George\AppData\Local\Temp\ipykernel_7832\386804788.py:583: DeprecationWarning:

to_plotly_figure is deprecated and will be removed in version 4.0.0. Use MolGraph.to_plotly() instead.

C:\Users\George\AppData\Local\Temp\ipykernel_7832\386804788.py:589: DeprecationWarning:

to_networkx_graph is deprecated and will be removed in version 4.0.0. Use MolGraph.to_networkx() instead.

Pd number index:  0
['Pd', 'C', 'C', 'N', 'N', 'C', 'C', 'C', 'C', 'C', 'C', 'H', 'H', 'C', 'C', 'C', 'C', 'C', 'C', 'H', 'H', 'C', 'H', 'H', 'H', 'C', 'H', 'H', 'H', 'C', 'H', 'C', 'H', 'C', 'H', 'C', 'C', 'C', 'C', 'C', 'C', 'H', 'C', 'C', 'C', 'H', 'C', 'H', 'H', 'H', 'H', 'C', 'H', 'C', 'H', 'H', 'H', 'C', 'H', 'H', 'H', 'C', 'H', 'H', 'H', 'C', 'H', 'H', 'H', 'C', 'H', 'H', 'H', 'C', 'H', 'H', 'H', 'C', 'H', 'H', 'H', 'C', 'H', 'H', 'H', 'C', 'C', 'C', 'C', 'H', 'C', 'C', 'H', 'H', 'C', 'C', 'C', 'C', 'C', 'H', 'C', 'H', 'H', 'O', 'O', 'C', 'C', 'C', 'C', 'C', 'C', 'H', 'H', 'H', 'C', 'C', 'C', 'C', 'C', 'C', 'H', 'H', 'H', 'C', 'H', 'H', 'C', 'C', 'C', 'C', 'H', 'C', 'H', 'C', 'H', 'H', 'C', 'H', 'H', 'C', 'C', 'C', 'C', 'H', 'C', 'H', 'C', 'H', 'H', 'C', 'F', 'F', 'F', 'C', 'F', 'F', 'F']
Ligand atom label:  4  Ligand atom A nbo:  -0.50491
Ligand atom label:  5  Ligand atom B nbo:  -0.46403
Atom_a:  5 Atom_b:  4
C:\Users\George\Desktop\Research_UCLA\CIC\Computational Work\Project cluster version 2\project_catalyst_repurposing\structures_ligand_id\pd_me2_structures\ligand_xyz\ligand-401-n-n-79-ligand_xyz.txt
Ending node: 2
Starting node: 3
(-1.061843, 0.466807, 0.620722)   3
(-0.764983, -0.373016, 1.540411)   1
(0.61865, -0.941311, 1.580988)   0
(1.473916, -0.533771, 0.71914)   2
ligand-402-n-n-80

C:\Users\George\AppData\Local\Temp\ipykernel_7832\386804788.py:583: DeprecationWarning:

to_plotly_figure is deprecated and will be removed in version 4.0.0. Use MolGraph.to_plotly() instead.

C:\Users\George\AppData\Local\Temp\ipykernel_7832\386804788.py:589: DeprecationWarning:

to_networkx_graph is deprecated and will be removed in version 4.0.0. Use MolGraph.to_networkx() instead.

Pd number index:  0
['Pd', 'C', 'C', 'N', 'N', 'C', 'C', 'C', 'C', 'C', 'C', 'H', 'H', 'C', 'C', 'C', 'C', 'C', 'C', 'H', 'H', 'C', 'H', 'H', 'H', 'C', 'H', 'H', 'H', 'C', 'H', 'C', 'H', 'C', 'H', 'C', 'C', 'C', 'C', 'C', 'C', 'H', 'C', 'C', 'C', 'H', 'C', 'H', 'H', 'H', 'H', 'C', 'H', 'C', 'H', 'H', 'H', 'C', 'H', 'H', 'H', 'C', 'H', 'H', 'H', 'C', 'H', 'H', 'H', 'C', 'H', 'H', 'H', 'C', 'H', 'H', 'H', 'C', 'H', 'H', 'H', 'C', 'H', 'H', 'H', 'C', 'C', 'C', 'C', 'H', 'C', 'C', 'H', 'H', 'C', 'C', 'C', 'C', 'C', 'H', 'C', 'H', 'H', 'O', 'O', 'C', 'C', 'C', 'C', 'C', 'C', 'H', 'H', 'H', 'C', 'C', 'C', 'C', 'C', 'C', 'H', 'H', 'H', 'C', 'H', 'H', 'C', 'C', 'C', 'C', 'H', 'C', 'H', 'C', 'H', 'H', 'C', 'H', 'H', 'C', 'C', 'C', 'C', 'H', 'C', 'H', 'C', 'H', 'H', 'N', 'O', 'O', 'N', 'O', 'O']
Ligand atom label:  4  Ligand atom A nbo:  -0.50408
Ligand atom label:  5  Ligand atom B nbo:  -0.48063
Atom_a:  5 Atom_b:  4
C:\Users\George\Desktop\Research_UCLA\CIC\Computational Work\Project cluster version 2\project_catalyst_repurposing\structures_ligand_id\pd_me2_structures\ligand_xyz\ligand-402-n-n-80-ligand_xyz.txt
Ending node: 2
Starting node: 3
(-1.261307, 0.40348, 0.122272)   3
(-0.808336, 0.028332, 1.258053)   1
(0.588622, -0.503905, 1.335978)   0
(1.304031, -0.508643, 0.273837)   2
ligand-403-n-n-81

C:\Users\George\AppData\Local\Temp\ipykernel_7832\386804788.py:583: DeprecationWarning:

to_plotly_figure is deprecated and will be removed in version 4.0.0. Use MolGraph.to_plotly() instead.

C:\Users\George\AppData\Local\Temp\ipykernel_7832\386804788.py:589: DeprecationWarning:

to_networkx_graph is deprecated and will be removed in version 4.0.0. Use MolGraph.to_networkx() instead.

Pd number index:  0
['Pd', 'C', 'C', 'N', 'N', 'C', 'C', 'C', 'C', 'C', 'C', 'H', 'H', 'C', 'C', 'C', 'C', 'C', 'C', 'H', 'H', 'C', 'H', 'H', 'H', 'C', 'H', 'H', 'H', 'C', 'H', 'C', 'H', 'C', 'H', 'C', 'C', 'C', 'C', 'C', 'C', 'H', 'C', 'C', 'C', 'H', 'C', 'H', 'H', 'H', 'H', 'C', 'H', 'C', 'H', 'H', 'H', 'C', 'H', 'H', 'H', 'C', 'H', 'H', 'H', 'C', 'H', 'H', 'H', 'C', 'H', 'H', 'H', 'C', 'H', 'H', 'H', 'C', 'H', 'H', 'H', 'C', 'H', 'H', 'H', 'C', 'C', 'C', 'C', 'H', 'C', 'C', 'H', 'H', 'C', 'C', 'C', 'C', 'C', 'H', 'C', 'H', 'H', 'O', 'O', 'C', 'C', 'C', 'C', 'C', 'C', 'H', 'H', 'H', 'C', 'C', 'C', 'C', 'C', 'C', 'H', 'H', 'H', 'C', 'H', 'H', 'C', 'C', 'C', 'C', 'H', 'C', 'H', 'C', 'H', 'H', 'C', 'H', 'H', 'C', 'C', 'C', 'C', 'H', 'C', 'H', 'C', 'H', 'H', 'O', 'O', 'C', 'H', 'H', 'H', 'C', 'H', 'H', 'H']
Ligand atom label:  4  Ligand atom B nbo:  -0.51528
Ligand atom label:  5  Ligand atom A nbo:  -0.44852
Atom_a:  5 Atom_b:  4
C:\Users\George\Desktop\Research_UCLA\CIC\Computational Work\Project cluster version 2\project_catalyst_repurposing\structures_ligand_id\pd_me2_structures\ligand_xyz\ligand-403-n-n-81-ligand_xyz.txt
Ending node: 2
Starting node: 3
(-1.23461, 0.536196, -0.007139)   3
(-0.806681, -0.166422, 0.972478)   1
(0.600472, -0.669033, 0.945414)   0
(1.374459, -0.290365, -0.003064)   2
ligand-404-p-n-31

C:\Users\George\AppData\Local\Temp\ipykernel_7832\386804788.py:583: DeprecationWarning:

to_plotly_figure is deprecated and will be removed in version 4.0.0. Use MolGraph.to_plotly() instead.

C:\Users\George\AppData\Local\Temp\ipykernel_7832\386804788.py:589: DeprecationWarning:

to_networkx_graph is deprecated and will be removed in version 4.0.0. Use MolGraph.to_networkx() instead.

Pd number index:  1
['P', 'Pd', 'C', 'H', 'H', 'H', 'C', 'H', 'H', 'N', 'C', 'C', 'C', 'C', 'C', 'C', 'C', 'H', 'H', 'C', 'H', 'C', 'H', 'C', 'H', 'C', 'H', 'C', 'H', 'H', 'H', 'C', 'H', 'H', 'H', 'C', 'H', 'H', 'H', 'C', 'H', 'H', 'H', 'O', 'C', 'H', 'H', 'H', 'H', 'C', 'H', 'H', 'H', 'C', 'H', 'H', 'H', 'C', 'H', 'H', 'H', 'C', 'H', 'H', 'H', 'H']
Ligand atom label:  1  Ligand atom B nbo:  1.25135
Ligand atom label:  10  Ligand atom A nbo:  -0.5843
Atom_a:  1 Atom_b:  10
C:\Users\George\Desktop\Research_UCLA\CIC\Computational Work\Project cluster version 2\project_catalyst_repurposing\structures_ligand_id\pd_me2_structures\ligand_xyz\ligand-404-p-n-31-ligand_xyz.txt
Starting node: 0
Ending node: 1
(2.198864, 0.096404, -0.426637)   0
(1.206648, 0.109161, -1.84611)   35
(-0.121245, 0.092681, -1.71364)   2
(-0.677258, 0.123285, -0.561501)   1
ligand-405-p-n-32

C:\Users\George\AppData\Local\Temp\ipykernel_7832\386804788.py:583: DeprecationWarning:

to_plotly_figure is deprecated and will be removed in version 4.0.0. Use MolGraph.to_plotly() instead.

C:\Users\George\AppData\Local\Temp\ipykernel_7832\386804788.py:589: DeprecationWarning:

to_networkx_graph is deprecated and will be removed in version 4.0.0. Use MolGraph.to_networkx() instead.

Pd number index:  1
['P', 'Pd', 'C', 'H', 'H', 'H', 'C', 'H', 'H', 'N', 'C', 'C', 'C', 'C', 'C', 'C', 'C', 'H', 'H', 'C', 'H', 'C', 'H', 'C', 'H', 'C', 'H', 'C', 'H', 'H', 'H', 'C', 'H', 'H', 'H', 'C', 'H', 'H', 'H', 'C', 'H', 'H', 'H', 'O', 'C', 'H', 'C', 'H', 'H', 'H', 'C', 'H', 'H', 'H', 'C', 'H', 'H', 'H', 'C', 'H', 'H', 'H', 'C', 'H', 'H', 'H', 'C', 'H', 'H', 'H', 'C', 'H', 'H', 'H', 'H']
Ligand atom label:  1  Ligand atom A nbo:  1.24528
Ligand atom label:  10  Ligand atom B nbo:  -0.5897
Atom_a:  1 Atom_b:  10
C:\Users\George\Desktop\Research_UCLA\CIC\Computational Work\Project cluster version 2\project_catalyst_repurposing\structures_ligand_id\pd_me2_structures\ligand_xyz\ligand-405-p-n-32-ligand_xyz.txt
Starting node: 0
Ending node: 1
(2.243975, 0.210389, -0.04132)   0
(1.221922, 1.52241, -0.478869)   35
(-0.11133, 1.413579, -0.401841)   2
(-0.632599, 0.295582, -0.063771)   1
ligand-406-p-n-33

C:\Users\George\AppData\Local\Temp\ipykernel_7832\386804788.py:583: DeprecationWarning:

to_plotly_figure is deprecated and will be removed in version 4.0.0. Use MolGraph.to_plotly() instead.

C:\Users\George\AppData\Local\Temp\ipykernel_7832\386804788.py:589: DeprecationWarning:

to_networkx_graph is deprecated and will be removed in version 4.0.0. Use MolGraph.to_networkx() instead.

Pd number index:  1
['P', 'Pd', 'C', 'H', 'H', 'H', 'C', 'H', 'H', 'N', 'C', 'C', 'C', 'C', 'C', 'C', 'C', 'H', 'H', 'C', 'H', 'C', 'H', 'C', 'C', 'C', 'H', 'H', 'H', 'C', 'H', 'H', 'H', 'C', 'H', 'H', 'H', 'C', 'H', 'H', 'H', 'O', 'H', 'C', 'H', 'H', 'H', 'C', 'H', 'H', 'H', 'C', 'H', 'H', 'H', 'C', 'H', 'H', 'H', 'C', 'H', 'H', 'H', 'C', 'H', 'H', 'H', 'C', 'H', 'H', 'H', 'H']
Ligand atom label:  1  Ligand atom B nbo:  1.2612
Ligand atom label:  10  Ligand atom A nbo:  -0.59038
Atom_a:  1 Atom_b:  10
C:\Users\George\Desktop\Research_UCLA\CIC\Computational Work\Project cluster version 2\project_catalyst_repurposing\structures_ligand_id\pd_me2_structures\ligand_xyz\ligand-406-p-n-33-ligand_xyz.txt
Starting node: 0
Ending node: 1
(2.061947, 0.024629, -0.238197)   0
(1.138472, -0.005389, -1.700175)   33
(-0.195218, 0.018272, -1.642123)   2
(-0.815902, 0.031451, -0.523669)   1
ligand-407-p-o-138

C:\Users\George\AppData\Local\Temp\ipykernel_7832\386804788.py:583: DeprecationWarning:

to_plotly_figure is deprecated and will be removed in version 4.0.0. Use MolGraph.to_plotly() instead.

C:\Users\George\AppData\Local\Temp\ipykernel_7832\386804788.py:589: DeprecationWarning:

to_networkx_graph is deprecated and will be removed in version 4.0.0. Use MolGraph.to_networkx() instead.

Pd number index:  33
['P', 'C', 'C', 'S', 'O', 'O', 'O', 'C', 'C', 'C', 'C', 'C', 'C', 'H', 'H', 'C', 'C', 'C', 'C', 'C', 'H', 'H', 'H', 'H', 'C', 'C', 'C', 'C', 'C', 'H', 'H', 'H', 'H', 'Pd', 'C', 'H', 'H', 'H', 'C', 'H', 'H', 'H', 'O', 'O', 'C', 'H', 'H', 'C', 'H', 'H', 'H', 'C', 'H', 'H', 'O', 'C', 'H', 'H', 'H', 'C', 'H', 'H', 'O', 'C', 'H', 'H', 'H', 'H']
Ligand atom label:  1  Ligand atom B nbo:  0.90695
Ligand atom label:  5  Ligand atom A nbo:  -0.96072
Atom_a:  1 Atom_b:  5
C:\Users\George\Desktop\Research_UCLA\CIC\Computational Work\Project cluster version 2\project_catalyst_repurposing\structures_ligand_id\pd_me2_structures\ligand_xyz\ligand-407-p-o-138-ligand_xyz.txt
Starting node: 0
Ending node: 4
(0.07861, -0.673234, 0.259436)   0
(-1.393398, -1.39465, 1.12969)   1
(-2.574503, -1.683395, 0.427067)   2
(-2.674558, -1.520755, -1.376818)   3
(-2.583348, -0.041074, -1.624583)   4
ligand-408-p-o-139

C:\Users\George\AppData\Local\Temp\ipykernel_7832\386804788.py:583: DeprecationWarning:

to_plotly_figure is deprecated and will be removed in version 4.0.0. Use MolGraph.to_plotly() instead.

C:\Users\George\AppData\Local\Temp\ipykernel_7832\386804788.py:589: DeprecationWarning:

to_networkx_graph is deprecated and will be removed in version 4.0.0. Use MolGraph.to_networkx() instead.

Pd number index:  33
['P', 'C', 'C', 'S', 'O', 'O', 'O', 'C', 'C', 'C', 'C', 'C', 'C', 'H', 'H', 'C', 'C', 'C', 'C', 'C', 'H', 'H', 'H', 'H', 'C', 'C', 'C', 'C', 'C', 'H', 'H', 'H', 'H', 'Pd', 'C', 'H', 'H', 'H', 'C', 'H', 'H', 'H', 'O', 'O', 'C', 'H', 'H', 'C', 'H', 'H', 'H', 'C', 'H', 'H', 'O', 'C', 'H', 'H', 'C', 'H', 'H', 'O', 'C', 'H', 'H', 'H', 'C', 'H', 'H', 'C', 'H', 'H', 'H', 'O', 'C', 'H', 'H', 'C', 'H', 'H', 'H', 'O']
Ligand atom label:  1  Ligand atom B nbo:  0.90664
Ligand atom label:  5  Ligand atom A nbo:  -0.96027
Atom_a:  1 Atom_b:  5
C:\Users\George\Desktop\Research_UCLA\CIC\Computational Work\Project cluster version 2\project_catalyst_repurposing\structures_ligand_id\pd_me2_structures\ligand_xyz\ligand-408-p-o-139-ligand_xyz.txt
Starting node: 0
Ending node: 4
(-0.140172, -1.345771, 0.176697)   0
(-1.539758, -2.270451, 0.971477)   1
(-2.772368, -2.417658, 0.314844)   2
(-3.012829, -1.862782, -1.395163)   3
(-2.93213, -0.363189, -1.319065)   4
ligand-409-p-o-140

C:\Users\George\AppData\Local\Temp\ipykernel_7832\386804788.py:583: DeprecationWarning:

to_plotly_figure is deprecated and will be removed in version 4.0.0. Use MolGraph.to_plotly() instead.

C:\Users\George\AppData\Local\Temp\ipykernel_7832\386804788.py:589: DeprecationWarning:

to_networkx_graph is deprecated and will be removed in version 4.0.0. Use MolGraph.to_networkx() instead.

Pd number index:  33
['P', 'C', 'C', 'S', 'O', 'O', 'O', 'C', 'C', 'C', 'C', 'C', 'C', 'H', 'H', 'C', 'C', 'C', 'C', 'C', 'H', 'H', 'H', 'H', 'C', 'C', 'C', 'C', 'C', 'H', 'H', 'H', 'H', 'Pd', 'C', 'H', 'H', 'H', 'C', 'H', 'H', 'H', 'O', 'O', 'C', 'H', 'H', 'C', 'H', 'H', 'H', 'C', 'H', 'H', 'C', 'H', 'H', 'C', 'H', 'H', 'C', 'H', 'H', 'H', 'C', 'H', 'H', 'C', 'H', 'H', 'H', 'C', 'H', 'H', 'C', 'H', 'H', 'H', 'C', 'H', 'H', 'C', 'H', 'H', 'C', 'H', 'H', 'C', 'H', 'H']
Ligand atom label:  1  Ligand atom B nbo:  0.90806
Ligand atom label:  5  Ligand atom A nbo:  -0.96018
Atom_a:  1 Atom_b:  5
C:\Users\George\Desktop\Research_UCLA\CIC\Computational Work\Project cluster version 2\project_catalyst_repurposing\structures_ligand_id\pd_me2_structures\ligand_xyz\ligand-409-p-o-140-ligand_xyz.txt
Starting node: 0
Ending node: 4
(-0.222882, -1.334361, 0.187682)   0
(-1.655146, -2.217616, 0.971599)   1
(-2.920258, -2.231805, 0.360448)   2
(-3.199632, -1.534908, -1.291911)   3
(-2.992708, -0.05566, -1.118711)   4
ligand-410-p-p-30
Pd number index:  9
['P', 'C', 'C', 'C', 'C', 'C', 'C', 'H', 'H', 'Pd', 'H', 'C', 'H', 'H', 'H', 'C', 'H', 'H', 'H', 'H', 'P', 'C', 'C', 'H', 'H', 'H', 'C', 'H', 'H', 'H', 'C', 'H', 'C', 'H', 'C', 'C', 'H', 'H', 'H', 'C', 'H', 'H', 'H', 'H', 'H', 'C', 'H', 'H', 'H', 'C', 'H', 'H', 'H', 'C', 'H', 'H', 'H', 'C', 'H', 'H', 'H']

C:\Users\George\AppData\Local\Temp\ipykernel_7832\386804788.py:583: DeprecationWarning:

to_plotly_figure is deprecated and will be removed in version 4.0.0. Use MolGraph.to_plotly() instead.

C:\Users\George\AppData\Local\Temp\ipykernel_7832\386804788.py:589: DeprecationWarning:

to_networkx_graph is deprecated and will be removed in version 4.0.0. Use MolGraph.to_networkx() instead.

Ligand atom label:  1  Ligand atom B nbo:  1.03934
Ligand atom label:  21  Ligand atom A nbo:  1.32119
Atom_a:  21 Atom_b:  1
C:\Users\George\Desktop\Research_UCLA\CIC\Computational Work\Project cluster version 2\project_catalyst_repurposing\structures_ligand_id\pd_me2_structures\ligand_xyz\ligand-410-p-p-30-ligand_xyz.txt
Ending node: 0
Starting node: 11
(-1.606537, 0.06165, -0.003905)   11
(-0.705309, 1.687063, -0.022596)   2
(0.703028, 1.685699, 0.054689)   1
(1.602852, 0.060055, 0.002394)   0
ligand-411-p-o-95
Pd number index:  12
['P', 'C', 'C', 'O', 'C', 'C', 'C', 'C', 'H', 'H', 'H', 'H', 'Pd', 'P', 'C', 'C', 'C', 'C', 'H', 'C', 'C', 'H', 'H', 'H', 'C', 'C', 'C', 'C', 'H', 'C', 'C', 'H', 'H', 'H', 'C', 'H', 'H', 'H', 'C', 'H', 'H', 'H', 'C', 'C', 'C', 'C', 'H', 'C', 'H', 'C', 'H', 'H', 'H', 'N', 'C', 'H', 'C', 'H', 'C', 'H', 'H', 'H', 'C', 'H', 'H', 'H', 'C', 'H', 'H', 'H', 'C', 'H', 'H', 'H', 'O', 'O', 'C', 'H', 'H', 'H', 'C', 'H', 'H', 'H']

C:\Users\George\AppData\Local\Temp\ipykernel_7832\386804788.py:583: DeprecationWarning:

to_plotly_figure is deprecated and will be removed in version 4.0.0. Use MolGraph.to_plotly() instead.

C:\Users\George\AppData\Local\Temp\ipykernel_7832\386804788.py:589: DeprecationWarning:

to_networkx_graph is deprecated and will be removed in version 4.0.0. Use MolGraph.to_networkx() instead.

Ligand atom label:  1  Ligand atom B nbo:  0.97685
Ligand atom label:  4  Ligand atom A nbo:  -1.03697
Atom_a:  1 Atom_b:  4
C:\Users\George\Desktop\Research_UCLA\CIC\Computational Work\Project cluster version 2\project_catalyst_repurposing\structures_ligand_id\pd_me2_structures\ligand_xyz\ligand-411-p-o-95-ligand_xyz.txt

C:\Users\George\AppData\Local\Temp\ipykernel_7832\386804788.py:583: DeprecationWarning:

to_plotly_figure is deprecated and will be removed in version 4.0.0. Use MolGraph.to_plotly() instead.

C:\Users\George\AppData\Local\Temp\ipykernel_7832\386804788.py:589: DeprecationWarning:

to_networkx_graph is deprecated and will be removed in version 4.0.0. Use MolGraph.to_networkx() instead.

Starting node: 0
Ending node: 3
(-1.487602, 0.253074, 0.278127)   0
(-0.414057, -0.054783, 1.765401)   1
(0.975195, -0.2817, 1.662492)   2
(1.932077, -0.138068, 0.103204)   12
(1.103817, 0.086012, -1.142772)   3
ligand-412-p-o-97
Pd number index:  12
['P', 'C', 'C', 'O', 'C', 'C', 'C', 'C', 'H', 'H', 'H', 'H', 'Pd', 'P', 'C', 'C', 'C', 'C', 'H', 'C', 'C', 'H', 'H', 'H', 'C', 'C', 'C', 'C', 'H', 'C', 'C', 'H', 'H', 'H', 'H', 'C', 'H', 'H', 'H', 'C', 'H', 'H', 'H', 'C', 'C', 'C', 'C', 'H', 'C', 'H', 'C', 'H', 'H', 'H', 'H', 'N', 'C', 'H', 'C', 'H', 'C', 'H', 'H', 'H', 'C', 'H', 'H', 'H', 'H', 'H']
Ligand atom label:  1  Ligand atom B nbo:  0.95651
Ligand atom label:  4  Ligand atom A nbo:  -1.02384
Atom_a:  1 Atom_b:  4
C:\Users\George\Desktop\Research_UCLA\CIC\Computational Work\Project cluster version 2\project_catalyst_repurposing\structures_ligand_id\pd_me2_structures\ligand_xyz\ligand-412-p-o-97-ligand_xyz.txt

C:\Users\George\AppData\Local\Temp\ipykernel_7832\386804788.py:583: DeprecationWarning:

to_plotly_figure is deprecated and will be removed in version 4.0.0. Use MolGraph.to_plotly() instead.

C:\Users\George\AppData\Local\Temp\ipykernel_7832\386804788.py:589: DeprecationWarning:

to_networkx_graph is deprecated and will be removed in version 4.0.0. Use MolGraph.to_networkx() instead.

Starting node: 0
Ending node: 3
(-1.402529, -0.093645, 0.082988)   0
(-0.669678, -0.661446, 1.695278)   1
(0.719246, -0.910574, 1.80453)   2
(1.86126, -0.767938, 0.37767)   12
(1.466875, -1.683797, -0.758249)   3
ligand-413-n-n-82
Pd number index:  0
['Pd', 'C', 'N', 'C', 'H', 'H', 'H', 'C', 'H', 'H', 'C', 'C', 'C', 'C', 'C', 'C', 'H', 'H', 'C', 'C', 'C', 'H', 'C', 'C', 'H', 'H', 'H', 'N', 'H', 'C', 'C', 'H', 'H', 'H', 'C', 'H', 'H', 'H', 'C', 'H', 'H', 'H', 'H', 'H', 'H']
Ligand atom label:  3  Ligand atom B nbo:  -0.46527
Ligand atom label:  28  Ligand atom A nbo:  -0.49655
Atom_a:  3 Atom_b:  28
C:\Users\George\Desktop\Research_UCLA\CIC\Computational Work\Project cluster version 2\project_catalyst_repurposing\structures_ligand_id\pd_me2_structures\ligand_xyz\ligand-413-n-n-82-ligand_xyz.txt
Starting node: 1
Ending node: 19
(-0.240075, -0.517223, -0.478548)   1
(0.478025, -1.554281, -0.680242)   0
(1.904163, -1.542628, -0.350488)   10
(2.411631, -0.374539, 0.089738)   19
ligand-414-n-n-83
Pd number index:  0
['Pd', 'C', 'C', 'N', 'N', 'C', 'H', 'H', 'H', 'C', 'H', 'H', 'H', 'H', 'H', 'C', 'C', 'C', 'H', 'C', 'H', 'H', 'C', 'H', 'H', 'C', 'H', 'H', 'H', 'H', 'H', 'H', 'C', 'C', 'C', 'H', 'C', 'H', 'H', 'C', 'H', 'H', 'C', 'H', 'H', 'H', 'H', 'H', 'H']
Ligand atom label:  4  Ligand atom A nbo:  -0.44401
Ligand atom label:  5  Ligand atom B nbo:  -0.4443
Atom_a:  4 Atom_b:  5

C:\Users\George\AppData\Local\Temp\ipykernel_7832\386804788.py:583: DeprecationWarning:

to_plotly_figure is deprecated and will be removed in version 4.0.0. Use MolGraph.to_plotly() instead.

C:\Users\George\AppData\Local\Temp\ipykernel_7832\386804788.py:589: DeprecationWarning:

to_networkx_graph is deprecated and will be removed in version 4.0.0. Use MolGraph.to_networkx() instead.

C:\Users\George\Desktop\Research_UCLA\CIC\Computational Work\Project cluster version 2\project_catalyst_repurposing\structures_ligand_id\pd_me2_structures\ligand_xyz\ligand-414-n-n-83-ligand_xyz.txt
Starting node: 2
Ending node: 3
(1.37341, -1.008385, -0.01082)   2
(0.73048, -2.111047, -0.025902)   0
(-0.730444, -2.111061, 0.026115)   1
(-1.373406, -1.008417, 0.010985)   3
ligand-415-n-n-84
Pd number index:  0
['Pd', 'C', 'H', 'H', 'H', 'C', 'H', 'H', 'H', 'C', 'C', 'C', 'C', 'C', 'H', 'C', 'C', 'H', 'H', 'C', 'C', 'C', 'H', 'H', 'H', 'N', 'N', 'C', 'C', 'H', 'H']
Ligand atom label:  26  Ligand atom A nbo:  -0.48899
Ligand atom label:  27  Ligand atom B nbo:  -0.48658
Atom_a:  27 Atom_b:  26

C:\Users\George\AppData\Local\Temp\ipykernel_7832\386804788.py:583: DeprecationWarning:

to_plotly_figure is deprecated and will be removed in version 4.0.0. Use MolGraph.to_plotly() instead.

C:\Users\George\AppData\Local\Temp\ipykernel_7832\386804788.py:589: DeprecationWarning:

to_networkx_graph is deprecated and will be removed in version 4.0.0. Use MolGraph.to_networkx() instead.

C:\Users\George\Desktop\Research_UCLA\CIC\Computational Work\Project cluster version 2\project_catalyst_repurposing\structures_ligand_id\pd_me2_structures\ligand_xyz\ligand-415-n-n-84-ligand_xyz.txt
Ending node: 16
Starting node: 17
(0.001371, -1.377216, -3.8e-05)   17
(1.180211, -0.712256, -2.1e-05)   3
(1.152595, 0.730551, 3.2e-05)   0
(-0.050589, 1.347707, 0.000192)   16
ligand-416-n-n-85
Pd number index:  0
['Pd', 'C', 'C', 'N', 'N', 'C', 'C', 'C', 'C', 'C', 'C', 'H', 'H', 'C', 'C', 'C', 'C', 'C', 'C', 'H', 'H', 'C', 'H', 'H', 'H', 'C', 'H', 'H', 'H', 'C', 'H', 'H', 'H', 'C', 'H', 'H', 'H', 'C', 'H', 'H', 'H', 'C', 'H', 'H', 'H', 'H', 'H', 'C', 'H', 'H', 'H', 'C', 'H', 'H', 'H']
Ligand atom label:  4  Ligand atom B nbo:  -0.45125
Ligand atom label:  5  Ligand atom A nbo:  -0.45125
Atom_a:  5 Atom_b:  4

C:\Users\George\AppData\Local\Temp\ipykernel_7832\386804788.py:583: DeprecationWarning:

to_plotly_figure is deprecated and will be removed in version 4.0.0. Use MolGraph.to_plotly() instead.

C:\Users\George\AppData\Local\Temp\ipykernel_7832\386804788.py:589: DeprecationWarning:

to_networkx_graph is deprecated and will be removed in version 4.0.0. Use MolGraph.to_networkx() instead.

C:\Users\George\Desktop\Research_UCLA\CIC\Computational Work\Project cluster version 2\project_catalyst_repurposing\structures_ligand_id\pd_me2_structures\ligand_xyz\ligand-416-n-n-85-ligand_xyz.txt
Ending node: 2
Starting node: 3
(1.336074, -0.015557, -0.710742)   3
(0.732873, -0.005372, -1.839725)   1
(-0.732808, 0.000297, -1.839785)   0
(-1.336095, 0.01547, -0.710906)   2
ligand-417-n-n-86
Pd number index:  0
['Pd', 'C', 'C', 'N', 'N', 'C', 'C', 'C', 'C', 'C', 'C', 'H', 'H', 'C', 'C', 'C', 'C', 'C', 'C', 'H', 'H', 'C', 'H', 'H', 'H', 'C', 'H', 'H', 'H', 'C', 'H', 'H', 'H', 'C', 'H', 'H', 'H', 'C', 'H', 'H', 'H', 'C', 'H', 'H', 'H', 'C', 'H', 'H', 'H', 'C', 'H', 'H', 'H', 'C', 'H', 'H', 'H', 'C', 'H', 'H', 'H']
Ligand atom label:  4  Ligand atom A nbo:  -0.46243
Ligand atom label:  5  Ligand atom B nbo:  -0.46216
Atom_a:  5 Atom_b:  4

C:\Users\George\AppData\Local\Temp\ipykernel_7832\386804788.py:583: DeprecationWarning:

to_plotly_figure is deprecated and will be removed in version 4.0.0. Use MolGraph.to_plotly() instead.

C:\Users\George\AppData\Local\Temp\ipykernel_7832\386804788.py:589: DeprecationWarning:

to_networkx_graph is deprecated and will be removed in version 4.0.0. Use MolGraph.to_networkx() instead.

C:\Users\George\Desktop\Research_UCLA\CIC\Computational Work\Project cluster version 2\project_catalyst_repurposing\structures_ligand_id\pd_me2_structures\ligand_xyz\ligand-417-n-n-86-ligand_xyz.txt
Ending node: 2
Starting node: 3
(-1.315753, -0.59835, -0.027874)   3
(-0.747184, -1.75075, -0.037238)   1
(0.746365, -1.751206, -0.030136)   0
(1.315467, -0.599114, -0.01836)   2
ligand-418-n-n-87
Pd number index:  0
['Pd', 'C', 'C', 'N', 'N', 'C', 'C', 'C', 'C', 'C', 'C', 'H', 'H', 'C', 'C', 'C', 'C', 'C', 'C', 'H', 'H', 'C', 'H', 'H', 'H', 'C', 'H', 'H', 'H', 'C', 'C', 'C', 'C', 'C', 'C', 'H', 'C', 'C', 'C', 'C', 'H', 'H', 'H', 'C', 'H', 'C', 'H', 'C', 'H', 'C', 'H', 'H', 'H', 'H', 'H', 'H', 'H', 'H', 'H', 'H', 'H', 'C', 'H', 'H', 'H', 'C', 'H', 'H', 'H']

C:\Users\George\AppData\Local\Temp\ipykernel_7832\386804788.py:583: DeprecationWarning:

to_plotly_figure is deprecated and will be removed in version 4.0.0. Use MolGraph.to_plotly() instead.

C:\Users\George\AppData\Local\Temp\ipykernel_7832\386804788.py:589: DeprecationWarning:

to_networkx_graph is deprecated and will be removed in version 4.0.0. Use MolGraph.to_networkx() instead.

Ligand atom label:  4  Ligand atom A nbo:  -0.45447
Ligand atom label:  5  Ligand atom B nbo:  -0.45447
Atom_a:  4 Atom_b:  5
C:\Users\George\Desktop\Research_UCLA\CIC\Computational Work\Project cluster version 2\project_catalyst_repurposing\structures_ligand_id\pd_me2_structures\ligand_xyz\ligand-418-n-n-87-ligand_xyz.txt
Starting node: 2
Ending node: 3
(1.366228, -0.405947, -0.04192)   2
(0.748035, 0.716412, -0.047358)   0
(-0.747803, 0.716865, -0.050357)   1
(-1.366767, -0.40506, -0.045854)   3
ligand-419-n-n-88

C:\Users\George\AppData\Local\Temp\ipykernel_7832\386804788.py:583: DeprecationWarning:

to_plotly_figure is deprecated and will be removed in version 4.0.0. Use MolGraph.to_plotly() instead.

C:\Users\George\AppData\Local\Temp\ipykernel_7832\386804788.py:589: DeprecationWarning:

to_networkx_graph is deprecated and will be removed in version 4.0.0. Use MolGraph.to_networkx() instead.

Pd number index:  0
['Pd', 'C', 'C', 'N', 'N', 'C', 'C', 'C', 'C', 'C', 'C', 'H', 'H', 'C', 'C', 'C', 'C', 'C', 'C', 'H', 'H', 'C', 'H', 'H', 'H', 'C', 'H', 'H', 'H', 'C', 'C', 'C', 'C', 'H', 'H', 'H', 'H', 'H', 'H', 'C', 'H', 'H', 'H', 'C', 'H', 'H', 'H', 'C', 'H', 'H', 'H', 'C', 'H', 'H', 'H', 'C', 'H', 'H', 'H', 'C', 'H', 'H', 'H', 'C', 'H', 'H', 'H', 'C', 'H', 'H', 'H', 'C', 'C', 'C', 'C', 'H', 'H', 'C', 'H', 'H', 'H', 'H', 'H', 'H', 'H', 'H']
Ligand atom label:  4  Ligand atom A nbo:  -0.47673
Ligand atom label:  5  Ligand atom B nbo:  -0.49292
Atom_a:  4 Atom_b:  5
C:\Users\George\Desktop\Research_UCLA\CIC\Computational Work\Project cluster version 2\project_catalyst_repurposing\structures_ligand_id\pd_me2_structures\ligand_xyz\ligand-419-n-n-88-ligand_xyz.txt
Starting node: 2
Ending node: 3
(-1.448618, 0.184202, 0.332137)   2
(-1.235521, 0.792718, 1.425006)   0
(0.058543, 1.128697, 2.094696)   62
(1.344413, 0.635924, 1.508605)   1
(1.552412, 0.018646, 0.419869)   3
ligand-420-n-n-89
Pd number index:  0
['Pd', 'C', 'C', 'N', 'N', 'C', 'C', 'C', 'C', 'C', 'C', 'H', 'H', 'C', 'C', 'C', 'C', 'C', 'C', 'H', 'H', 'C', 'H', 'H', 'H', 'C', 'H', 'H', 'H', 'H', 'H', 'C', 'C', 'C', 'C', 'H', 'H', 'C', 'H', 'H', 'H', 'H', 'H', 'H', 'H', 'H', 'C', 'H', 'H', 'H', 'C', 'H', 'H', 'H', 'C', 'H', 'H', 'H', 'C', 'H', 'H', 'H']
Ligand atom label:  4  Ligand atom A nbo:  -0.46908
Ligand atom label:  5  Ligand atom B nbo:  -0.47119
Atom_a:  4 Atom_b:  5

C:\Users\George\AppData\Local\Temp\ipykernel_7832\386804788.py:583: DeprecationWarning:

to_plotly_figure is deprecated and will be removed in version 4.0.0. Use MolGraph.to_plotly() instead.

C:\Users\George\AppData\Local\Temp\ipykernel_7832\386804788.py:589: DeprecationWarning:

to_networkx_graph is deprecated and will be removed in version 4.0.0. Use MolGraph.to_networkx() instead.

C:\Users\George\Desktop\Research_UCLA\CIC\Computational Work\Project cluster version 2\project_catalyst_repurposing\structures_ligand_id\pd_me2_structures\ligand_xyz\ligand-420-n-n-89-ligand_xyz.txt
Starting node: 2
Ending node: 3
(1.501085, 0.311235, 0.030363)   2
(1.292985, 1.561848, -0.034843)   0
(-8.5e-05, 2.315413, -0.000263)   22
(-1.293097, 1.561728, 0.034372)   1
(-1.501092, 0.311091, -0.030678)   3
ligand-421-n-n-90

C:\Users\George\AppData\Local\Temp\ipykernel_7832\386804788.py:583: DeprecationWarning:

to_plotly_figure is deprecated and will be removed in version 4.0.0. Use MolGraph.to_plotly() instead.

C:\Users\George\AppData\Local\Temp\ipykernel_7832\386804788.py:589: DeprecationWarning:

to_networkx_graph is deprecated and will be removed in version 4.0.0. Use MolGraph.to_networkx() instead.

Pd number index:  0
['Pd', 'C', 'C', 'N', 'N', 'C', 'H', 'H', 'H', 'C', 'H', 'H', 'H', 'C', 'C', 'C', 'C', 'H', 'H', 'C', 'H', 'H', 'H', 'H', 'H', 'H', 'H', 'H', 'C', 'C', 'C', 'H', 'C', 'H', 'H', 'C', 'H', 'H', 'C', 'H', 'H', 'H', 'H', 'H', 'H', 'C', 'C', 'C', 'H', 'C', 'H', 'H', 'C', 'H', 'H', 'C', 'H', 'H', 'H', 'H', 'H', 'H']
Ligand atom label:  4  Ligand atom A nbo:  -0.46239
Ligand atom label:  5  Ligand atom B nbo:  -0.46782
Atom_a:  4 Atom_b:  5
C:\Users\George\Desktop\Research_UCLA\CIC\Computational Work\Project cluster version 2\project_catalyst_repurposing\structures_ligand_id\pd_me2_structures\ligand_xyz\ligand-421-n-n-90-ligand_xyz.txt
Starting node: 2
Ending node: 3
(1.498311, 0.32336, -0.371795)   2
(1.322221, 1.415306, -0.991593)   0
(0.200711, 2.381441, -0.67685)   4
(-1.098725, 1.679558, -0.991466)   1
(-1.458902, 0.580116, -0.468853)   3
ligand-422-n-n-91

C:\Users\George\AppData\Local\Temp\ipykernel_7832\386804788.py:583: DeprecationWarning:

to_plotly_figure is deprecated and will be removed in version 4.0.0. Use MolGraph.to_plotly() instead.

C:\Users\George\AppData\Local\Temp\ipykernel_7832\386804788.py:589: DeprecationWarning:

to_networkx_graph is deprecated and will be removed in version 4.0.0. Use MolGraph.to_networkx() instead.

Pd number index:  0
['Pd', 'C', 'C', 'N', 'N', 'C', 'H', 'H', 'H', 'C', 'H', 'H', 'H', 'C', 'C', 'C', 'C', 'H', 'H', 'C', 'H', 'H', 'H', 'H', 'H', 'H', 'H', 'H', 'C', 'C', 'C', 'H', 'H', 'H', 'C', 'H', 'H', 'H', 'C', 'H', 'H', 'H', 'C', 'H', 'H', 'H', 'C', 'H', 'H', 'H', 'C', 'H', 'H', 'H']
Ligand atom label:  4  Ligand atom B nbo:  -0.47578
Ligand atom label:  5  Ligand atom A nbo:  -0.47847
Atom_a:  4 Atom_b:  5
C:\Users\George\Desktop\Research_UCLA\CIC\Computational Work\Project cluster version 2\project_catalyst_repurposing\structures_ligand_id\pd_me2_structures\ligand_xyz\ligand-422-n-n-91-ligand_xyz.txt
Starting node: 2
Ending node: 3
(1.363273, -0.700689, -0.445932)   2
(0.617438, -1.713185, -0.615691)   0
(-0.801932, -1.823352, -0.09506)   4
(-1.576879, -0.685948, -0.736528)   1
(-1.331659, 0.537186, -0.51108)   3
ligand-423-n-n-92
Pd number index:  0
['Pd', 'C', 'C', 'N', 'N', 'C', 'C', 'C', 'C', 'C', 'C', 'H', 'H', 'C', 'C', 'C', 'C', 'C', 'C', 'H', 'H', 'C', 'H', 'H', 'H', 'C', 'H', 'H', 'H', 'C', 'H', 'H', 'H', 'C', 'H', 'H', 'H', 'C', 'H', 'H', 'H', 'C', 'H', 'H', 'H', 'H', 'H', 'C', 'H', 'H', 'H', 'C', 'H', 'H', 'H', 'H', 'H', 'H', 'H']

C:\Users\George\AppData\Local\Temp\ipykernel_7832\386804788.py:583: DeprecationWarning:

to_plotly_figure is deprecated and will be removed in version 4.0.0. Use MolGraph.to_plotly() instead.

C:\Users\George\AppData\Local\Temp\ipykernel_7832\386804788.py:589: DeprecationWarning:

to_networkx_graph is deprecated and will be removed in version 4.0.0. Use MolGraph.to_networkx() instead.

Ligand atom label:  4  Ligand atom B nbo:  -0.71572
Ligand atom label:  5  Ligand atom A nbo:  -0.64823
Atom_a:  5 Atom_b:  4
C:\Users\George\Desktop\Research_UCLA\CIC\Computational Work\Project cluster version 2\project_catalyst_repurposing\structures_ligand_id\pd_me2_structures\ligand_xyz\ligand-423-n-n-92-ligand_xyz.txt
Ending node: 2
Starting node: 3
(-1.40038, -0.336588, 0.714879)   3
(-0.740077, 0.319733, 1.846308)   1
(0.740579, 0.007437, 1.871523)   0
(1.398132, 0.456815, 0.642226)   2
ligand-424-n-n-93

C:\Users\George\AppData\Local\Temp\ipykernel_7832\386804788.py:583: DeprecationWarning:

to_plotly_figure is deprecated and will be removed in version 4.0.0. Use MolGraph.to_plotly() instead.

C:\Users\George\AppData\Local\Temp\ipykernel_7832\386804788.py:589: DeprecationWarning:

to_networkx_graph is deprecated and will be removed in version 4.0.0. Use MolGraph.to_networkx() instead.

Pd number index:  0
['Pd', 'C', 'N', 'C', 'H', 'H', 'H', 'C', 'H', 'H', 'C', 'C', 'C', 'C', 'C', 'C', 'H', 'H', 'C', 'C', 'C', 'H', 'C', 'C', 'H', 'H', 'H', 'N', 'H', 'H', 'H', 'H', 'C', 'H', 'H', 'C', 'H', 'H', 'C', 'H', 'H', 'C', 'H', 'H', 'H']
Ligand atom label:  3  Ligand atom B nbo:  -0.46027
Ligand atom label:  28  Ligand atom A nbo:  -0.49956
Atom_a:  3 Atom_b:  28
C:\Users\George\Desktop\Research_UCLA\CIC\Computational Work\Project cluster version 2\project_catalyst_repurposing\structures_ligand_id\pd_me2_structures\ligand_xyz\ligand-424-n-n-93-ligand_xyz.txt
Starting node: 1
Ending node: 19
(-0.548551, 0.394527, 0.136184)   1
(-1.036142, 1.579461, 0.136117)   0
(-2.47312, 1.794362, -0.022239)   10
(-3.23269, 0.695838, -0.198242)   19
ligand-425-n-n-94

C:\Users\George\AppData\Local\Temp\ipykernel_7832\386804788.py:583: DeprecationWarning:

to_plotly_figure is deprecated and will be removed in version 4.0.0. Use MolGraph.to_plotly() instead.

C:\Users\George\AppData\Local\Temp\ipykernel_7832\386804788.py:589: DeprecationWarning:

to_networkx_graph is deprecated and will be removed in version 4.0.0. Use MolGraph.to_networkx() instead.

Pd number index:  0
['Pd', 'C', 'N', 'C', 'H', 'H', 'H', 'C', 'H', 'H', 'C', 'C', 'C', 'C', 'C', 'C', 'H', 'H', 'C', 'C', 'C', 'H', 'C', 'C', 'H', 'H', 'H', 'N', 'H', 'H', 'H', 'H', 'C', 'C', 'H', 'H', 'H', 'C', 'H', 'H', 'H', 'H']
Ligand atom label:  3  Ligand atom B nbo:  -0.46048
Ligand atom label:  28  Ligand atom A nbo:  -0.49958
Atom_a:  3 Atom_b:  28
C:\Users\George\Desktop\Research_UCLA\CIC\Computational Work\Project cluster version 2\project_catalyst_repurposing\structures_ligand_id\pd_me2_structures\ligand_xyz\ligand-425-n-n-94-ligand_xyz.txt
Starting node: 1
Ending node: 19
(-0.160127, -0.470764, 0.071963)   1
(-0.740903, -1.612625, 0.060435)   0
(-2.198184, -1.709031, 0.03693)   10
(-2.884195, -0.549573, 0.057208)   19

C:\Users\George\AppData\Local\Temp\ipykernel_7832\386804788.py:583: DeprecationWarning:

to_plotly_figure is deprecated and will be removed in version 4.0.0. Use MolGraph.to_plotly() instead.

C:\Users\George\AppData\Local\Temp\ipykernel_7832\386804788.py:589: DeprecationWarning:

to_networkx_graph is deprecated and will be removed in version 4.0.0. Use MolGraph.to_networkx() instead.

ligand-426-n-n-95
Pd number index:  0
['Pd', 'C', 'C', 'N', 'N', 'C', 'C', 'C', 'C', 'C', 'C', 'H', 'H', 'C', 'C', 'C', 'C', 'C', 'C', 'H', 'H', 'C', 'H', 'H', 'H', 'C', 'H', 'H', 'H', 'C', 'C', 'C', 'C', 'C', 'C', 'H', 'C', 'C', 'C', 'C', 'H', 'H', 'H', 'H', 'H', 'C', 'H', 'H', 'C', 'H', 'H', 'H', 'H', 'H', 'H', 'C', 'H', 'H', 'C', 'H', 'H', 'C', 'H', 'H', 'H', 'C', 'H', 'H', 'C', 'H', 'H', 'C', 'H', 'H', 'H']
Ligand atom label:  4  Ligand atom B nbo:  -0.45482
Ligand atom label:  5  Ligand atom A nbo:  -0.4545
Atom_a:  5 Atom_b:  4
C:\Users\George\Desktop\Research_UCLA\CIC\Computational Work\Project cluster version 2\project_catalyst_repurposing\structures_ligand_id\pd_me2_structures\ligand_xyz\ligand-426-n-n-95-ligand_xyz.txt
Ending node: 2
Starting node: 3
(-1.269227, -0.482792, -0.014898)   3
(-0.839051, 0.735767, -0.006957)   1
(0.635729, 0.977876, -0.089461)   0
(1.418882, -0.038545, -0.151095)   2
ligand-427-n-n-96
Pd number index:  0
['Pd', 'C', 'N', 'C', 'H', 'H', 'H', 'C', 'H', 'H', 'C', 'C', 'C', 'C', 'C', 'C', 'H', 'H', 'C', 'C', 'C', 'H', 'C', 'C', 'H', 'H', 'H', 'N', 'H', 'C', 'C', 'H', 'H', 'H', 'C', 'H', 'H', 'H', 'H', 'H', 'H', 'H']
Ligand atom label:  3  Ligand atom A nbo:  -0.46167
Ligand atom label:  28  Ligand atom B nbo:  -0.4966
Atom_a:  3 Atom_b:  28

C:\Users\George\AppData\Local\Temp\ipykernel_7832\386804788.py:583: DeprecationWarning:

to_plotly_figure is deprecated and will be removed in version 4.0.0. Use MolGraph.to_plotly() instead.

C:\Users\George\AppData\Local\Temp\ipykernel_7832\386804788.py:589: DeprecationWarning:

to_networkx_graph is deprecated and will be removed in version 4.0.0. Use MolGraph.to_networkx() instead.

C:\Users\George\Desktop\Research_UCLA\CIC\Computational Work\Project cluster version 2\project_catalyst_repurposing\structures_ligand_id\pd_me2_structures\ligand_xyz\ligand-427-n-n-96-ligand_xyz.txt
Starting node: 1
Ending node: 19
(-0.336756, -0.323022, -0.591789)   1
(0.281808, -1.414451, -0.830666)   0
(1.725365, -1.505433, -0.600545)   10
(2.330195, -0.393444, -0.139592)   19
ligand-428-n-n-97
Pd number index:  0
['Pd', 'C', 'N', 'C', 'H', 'H', 'H', 'C', 'H', 'H', 'C', 'C', 'C', 'C', 'C', 'C', 'H', 'H', 'C', 'C', 'C', 'H', 'C', 'C', 'H', 'H', 'H', 'N', 'H', 'C', 'C', 'H', 'H', 'H', 'H', 'H', 'H', 'H', 'H']
Ligand atom label:  3  Ligand atom B nbo:  -0.46132
Ligand atom label:  28  Ligand atom A nbo:  -0.49985
Atom_a:  3 Atom_b:  28

C:\Users\George\AppData\Local\Temp\ipykernel_7832\386804788.py:583: DeprecationWarning:

to_plotly_figure is deprecated and will be removed in version 4.0.0. Use MolGraph.to_plotly() instead.

C:\Users\George\AppData\Local\Temp\ipykernel_7832\386804788.py:589: DeprecationWarning:

to_networkx_graph is deprecated and will be removed in version 4.0.0. Use MolGraph.to_networkx() instead.

C:\Users\George\Desktop\Research_UCLA\CIC\Computational Work\Project cluster version 2\project_catalyst_repurposing\structures_ligand_id\pd_me2_structures\ligand_xyz\ligand-428-n-n-97-ligand_xyz.txt
Starting node: 1
Ending node: 19
(-0.368347, -0.798071, -0.031618)   1
(0.447325, -1.767255, 0.146188)   0
(1.885278, -1.519807, 0.257635)   10
(2.290367, -0.240475, 0.138174)   19
ligand-429-n-n-98

C:\Users\George\AppData\Local\Temp\ipykernel_7832\386804788.py:583: DeprecationWarning:

to_plotly_figure is deprecated and will be removed in version 4.0.0. Use MolGraph.to_plotly() instead.

C:\Users\George\AppData\Local\Temp\ipykernel_7832\386804788.py:589: DeprecationWarning:

to_networkx_graph is deprecated and will be removed in version 4.0.0. Use MolGraph.to_networkx() instead.

Pd number index:  0
['Pd', 'C', 'C', 'N', 'N', 'C', 'C', 'C', 'C', 'C', 'C', 'H', 'H', 'C', 'C', 'C', 'C', 'C', 'C', 'H', 'H', 'C', 'H', 'H', 'H', 'C', 'H', 'H', 'H', 'C', 'C', 'C', 'C', 'H', 'H', 'H', 'H', 'H', 'H', 'C', 'H', 'H', 'H', 'C', 'H', 'H', 'H', 'C', 'H', 'H', 'H', 'C', 'H', 'H', 'H', 'C', 'H', 'H', 'H', 'C', 'H', 'H', 'H', 'C', 'H', 'H', 'H', 'C', 'H', 'H', 'H', 'C', 'H', 'H', 'H', 'H']
Ligand atom label:  4  Ligand atom A nbo:  -0.4783
Ligand atom label:  5  Ligand atom B nbo:  -0.48797
Atom_a:  4 Atom_b:  5
C:\Users\George\Desktop\Research_UCLA\CIC\Computational Work\Project cluster version 2\project_catalyst_repurposing\structures_ligand_id\pd_me2_structures\ligand_xyz\ligand-429-n-n-98-ligand_xyz.txt
Starting node: 2
Ending node: 3
(1.477495, 0.096798, -0.793567)   2
(1.263031, 0.096641, -2.045278)   0
(-0.046534, 0.095562, -2.75526)   62
(-1.356674, -0.032171, -2.060473)   1
(-1.573094, -0.117111, -0.813136)   3
ligand-430-n-n-99

C:\Users\George\AppData\Local\Temp\ipykernel_7832\386804788.py:583: DeprecationWarning:

to_plotly_figure is deprecated and will be removed in version 4.0.0. Use MolGraph.to_plotly() instead.

C:\Users\George\AppData\Local\Temp\ipykernel_7832\386804788.py:589: DeprecationWarning:

to_networkx_graph is deprecated and will be removed in version 4.0.0. Use MolGraph.to_networkx() instead.

Pd number index:  1
['C', 'Pd', 'C', 'H', 'H', 'H', 'C', 'H', 'H', 'H', 'H', 'H', 'C', 'H', 'C', 'H', 'C', 'C', 'C', 'H', 'H', 'N', 'N', 'H', 'H', 'H', 'H', 'H', 'H', 'C', 'H', 'H', 'H', 'C', 'C', 'C', 'C', 'H', 'C', 'H', 'C', 'H', 'H', 'H', 'C', 'C', 'C', 'C', 'H', 'C', 'H', 'C', 'H', 'H', 'H', 'C', 'H', 'H', 'H']
Ligand atom label:  22  Ligand atom B nbo:  -0.55209
Ligand atom label:  23  Ligand atom A nbo:  -0.49772
Atom_a:  23 Atom_b:  22
C:\Users\George\Desktop\Research_UCLA\CIC\Computational Work\Project cluster version 2\project_catalyst_repurposing\structures_ligand_id\pd_me2_structures\ligand_xyz\ligand-430-n-n-99-ligand_xyz.txt
Ending node: 12
Starting node: 13
(0.587465, -1.061705, -0.837079)   13
(-0.660952, -1.042344, -1.605795)   9
(-1.072011, 0.33607, -2.084715)   0
(-1.201596, 1.347968, -1.018956)   12
ligand-431-p-c-29

C:\Users\George\AppData\Local\Temp\ipykernel_7832\386804788.py:583: DeprecationWarning:

to_plotly_figure is deprecated and will be removed in version 4.0.0. Use MolGraph.to_plotly() instead.

C:\Users\George\AppData\Local\Temp\ipykernel_7832\386804788.py:589: DeprecationWarning:

to_networkx_graph is deprecated and will be removed in version 4.0.0. Use MolGraph.to_networkx() instead.

Pd number index:  12
['C', 'H', 'H', 'H', 'C', 'H', 'H', 'H', 'C', 'C', 'H', 'H', 'Pd', 'C', 'N', 'N', 'C', 'C', 'C', 'C', 'C', 'C', 'H', 'H', 'H', 'C', 'H', 'H', 'C', 'H', 'H', 'H', 'C', 'H', 'H', 'H', 'P', 'C', 'C', 'C', 'C', 'H', 'C', 'H', 'C', 'H', 'H', 'H', 'C', 'C', 'C', 'C', 'H', 'C', 'H', 'C', 'H', 'H', 'H', 'C', 'H', 'C', 'H', 'C', 'H', 'H', 'H', 'C', 'H', 'H', 'H']
Ligand atom label:  14  Ligand atom A nbo:  0.52096
Ligand atom label:  37  Ligand atom B nbo:  1.25976
Atom_a:  37 Atom_b:  14
C:\Users\George\Desktop\Research_UCLA\CIC\Computational Work\Project cluster version 2\project_catalyst_repurposing\structures_ligand_id\pd_me2_structures\ligand_xyz\ligand-431-p-c-29-ligand_xyz.txt
Ending node: 4
Starting node: 27
(2.058269, -0.311167, 0.206553)   27
(1.46044, -0.684234, 1.940611)   16
(0.029721, -0.443837, 1.95962)   5
(-0.727385, -0.52437, 0.824233)   4
ligand-432-p-c-30

C:\Users\George\AppData\Local\Temp\ipykernel_7832\386804788.py:583: DeprecationWarning:

to_plotly_figure is deprecated and will be removed in version 4.0.0. Use MolGraph.to_plotly() instead.

C:\Users\George\AppData\Local\Temp\ipykernel_7832\386804788.py:589: DeprecationWarning:

to_networkx_graph is deprecated and will be removed in version 4.0.0. Use MolGraph.to_networkx() instead.

Pd number index:  44
['C', 'C', 'C', 'C', 'C', 'C', 'H', 'H', 'H', 'C', 'H', 'H', 'H', 'C', 'H', 'H', 'H', 'H', 'P', 'C', 'C', 'C', 'C', 'H', 'C', 'H', 'C', 'H', 'H', 'H', 'C', 'C', 'C', 'C', 'H', 'C', 'C', 'H', 'H', 'H', 'C', 'C', 'H', 'H', 'Pd', 'C', 'N', 'N', 'C', 'C', 'C', 'C', 'C', 'C', 'H', 'H', 'H', 'C', 'H', 'H', 'C', 'H', 'C', 'H', 'H', 'H', 'C', 'H', 'H', 'H', 'C', 'H', 'C', 'H', 'H', 'H', 'C', 'H', 'H', 'H', 'H']
Ligand atom label:  19  Ligand atom B nbo:  1.34254
Ligand atom label:  46  Ligand atom A nbo:  0.56338
Atom_a:  19 Atom_b:  46
C:\Users\George\Desktop\Research_UCLA\CIC\Computational Work\Project cluster version 2\project_catalyst_repurposing\structures_ligand_id\pd_me2_structures\ligand_xyz\ligand-432-p-c-30-ligand_xyz.txt
Starting node: 10
Ending node: 36
(1.884106, -0.022394, -0.140751)   10
(2.294033, -1.113853, 1.320966)   1
(1.6465, -2.351819, 1.499342)   0
(0.494788, -2.785859, 0.63024)   48
(-0.731843, -2.072853, 0.950417)   37
(-1.257292, -1.085108, 0.178658)   36
ligand-433-p-c-31

C:\Users\George\AppData\Local\Temp\ipykernel_7832\386804788.py:583: DeprecationWarning:

to_plotly_figure is deprecated and will be removed in version 4.0.0. Use MolGraph.to_plotly() instead.

C:\Users\George\AppData\Local\Temp\ipykernel_7832\386804788.py:589: DeprecationWarning:

to_networkx_graph is deprecated and will be removed in version 4.0.0. Use MolGraph.to_networkx() instead.

Pd number index:  44
['C', 'C', 'C', 'C', 'C', 'C', 'H', 'H', 'H', 'C', 'H', 'H', 'H', 'C', 'H', 'H', 'H', 'H', 'P', 'C', 'C', 'C', 'C', 'H', 'C', 'H', 'C', 'H', 'H', 'H', 'C', 'C', 'C', 'C', 'H', 'C', 'C', 'H', 'H', 'H', 'C', 'C', 'H', 'H', 'Pd', 'C', 'N', 'N', 'C', 'C', 'C', 'C', 'C', 'C', 'H', 'H', 'H', 'C', 'H', 'H', 'C', 'H', 'H', 'H', 'C', 'H', 'H', 'H', 'H', 'N', 'H']
Ligand atom label:  19  Ligand atom B nbo:  1.34694
Ligand atom label:  46  Ligand atom A nbo:  0.55621
Atom_a:  19 Atom_b:  46
C:\Users\George\Desktop\Research_UCLA\CIC\Computational Work\Project cluster version 2\project_catalyst_repurposing\structures_ligand_id\pd_me2_structures\ligand_xyz\ligand-433-p-c-31-ligand_xyz.txt
Starting node: 10
Ending node: 36
(-1.489944, -0.106362, 0.170301)   10
(-1.927702, 1.657935, -0.240985)   1
(-1.507891, 2.307171, -1.42712)   0
(-0.734109, 1.63534, -2.539938)   48
(0.659482, 1.380108, -2.219683)   37
(1.060992, 0.232574, -1.62317)   36
ligand-434-c-n-10

C:\Users\George\AppData\Local\Temp\ipykernel_7832\386804788.py:583: DeprecationWarning:

to_plotly_figure is deprecated and will be removed in version 4.0.0. Use MolGraph.to_plotly() instead.

C:\Users\George\AppData\Local\Temp\ipykernel_7832\386804788.py:589: DeprecationWarning:

to_networkx_graph is deprecated and will be removed in version 4.0.0. Use MolGraph.to_networkx() instead.

Pd number index:  12
['C', 'H', 'H', 'H', 'C', 'H', 'H', 'H', 'C', 'C', 'H', 'H', 'Pd', 'C', 'N', 'N', 'C', 'C', 'C', 'C', 'C', 'C', 'H', 'H', 'H', 'C', 'H', 'H', 'H', 'C', 'H', 'H', 'H', 'C', 'H', 'C', 'H', 'C', 'H', 'H', 'H', 'C', 'H', 'H', 'H', 'C', 'C', 'C', 'H', 'C', 'C', 'H', 'H', 'H', 'N']
Ligand atom label:  14  Ligand atom A nbo:  0.60227
Ligand atom label:  55  Ligand atom B nbo:  -0.53419
Atom_a:  14 Atom_b:  55
C:\Users\George\Desktop\Research_UCLA\CIC\Computational Work\Project cluster version 2\project_catalyst_repurposing\structures_ligand_id\pd_me2_structures\ligand_xyz\ligand-434-c-n-10-ligand_xyz.txt

C:\Users\George\AppData\Local\Temp\ipykernel_7832\386804788.py:583: DeprecationWarning:

to_plotly_figure is deprecated and will be removed in version 4.0.0. Use MolGraph.to_plotly() instead.

C:\Users\George\AppData\Local\Temp\ipykernel_7832\386804788.py:589: DeprecationWarning:

to_networkx_graph is deprecated and will be removed in version 4.0.0. Use MolGraph.to_networkx() instead.

Starting node: 4
Ending node: 45
(0.34141, -0.001296, 0.580611)   4
(1.282672, -0.003324, 1.590581)   5
(2.656141, -0.00271, 1.288393)   36
(2.946372, 0.000107, -0.01386)   45
ligand-435-n-n-100
Pd number index:  0
['Pd', 'N', 'N', 'C', 'C', 'C', 'C', 'C', 'C', 'H', 'H', 'C', 'C', 'C', 'C', 'C', 'C', 'H', 'H', 'C', 'H', 'H', 'H', 'C', 'H', 'H', 'H', 'C', 'C', 'C', 'H', 'C', 'H', 'C', 'C', 'C', 'C', 'C', 'H', 'C', 'H', 'H', 'H', 'C', 'C', 'C', 'C', 'C', 'H', 'C', 'H', 'H', 'H', 'H', 'H', 'C', 'H', 'H', 'H', 'C', 'H', 'H', 'H', 'C', 'H', 'H', 'H', 'C', 'H', 'H', 'H']
Ligand atom label:  2  Ligand atom A nbo:  -0.46094
Ligand atom label:  3  Ligand atom B nbo:  -0.46184
Atom_a:  2 Atom_b:  3
C:\Users\George\Desktop\Research_UCLA\CIC\Computational Work\Project cluster version 2\project_catalyst_repurposing\structures_ligand_id\pd_me2_structures\ligand_xyz\ligand-435-n-n-100-ligand_xyz.txt
Starting node: 0
Ending node: 1
(-1.355931, -0.613333, 0.061354)   0
(-0.742135, 0.505895, 0.051332)   20
(0.742372, 0.506235, 0.050009)   18
(1.356841, -0.612564, 0.062953)   1
ligand-436-n-n-101

C:\Users\George\AppData\Local\Temp\ipykernel_7832\386804788.py:583: DeprecationWarning:

to_plotly_figure is deprecated and will be removed in version 4.0.0. Use MolGraph.to_plotly() instead.

C:\Users\George\AppData\Local\Temp\ipykernel_7832\386804788.py:589: DeprecationWarning:

to_networkx_graph is deprecated and will be removed in version 4.0.0. Use MolGraph.to_networkx() instead.

Pd number index:  0
['Pd', 'N', 'N', 'C', 'C', 'C', 'C', 'C', 'C', 'H', 'H', 'C', 'C', 'C', 'C', 'C', 'C', 'H', 'H', 'C', 'H', 'H', 'H', 'C', 'H', 'H', 'H', 'C', 'C', 'C', 'H', 'C', 'H', 'C', 'C', 'C', 'C', 'C', 'H', 'C', 'H', 'H', 'H', 'C', 'C', 'C', 'C', 'C', 'H', 'C', 'H', 'H', 'H', 'C', 'H', 'H', 'H', 'C', 'H', 'H', 'H', 'C', 'H', 'H', 'H', 'C', 'H', 'H', 'H', 'C', 'H', 'H', 'H', 'C', 'H', 'H', 'H']
Ligand atom label:  2  Ligand atom A nbo:  -0.46013
Ligand atom label:  3  Ligand atom B nbo:  -0.46086
Atom_a:  2 Atom_b:  3
C:\Users\George\Desktop\Research_UCLA\CIC\Computational Work\Project cluster version 2\project_catalyst_repurposing\structures_ligand_id\pd_me2_structures\ligand_xyz\ligand-436-n-n-101-ligand_xyz.txt
Starting node: 0
Ending node: 1
(-1.35576, -0.555061, 0.078565)   0
(-0.742707, 0.564479, 0.060889)   20
(0.741852, 0.566388, 0.060346)   18
(1.357808, -0.551507, 0.082095)   1
ligand-437-n-n-102

C:\Users\George\AppData\Local\Temp\ipykernel_7832\386804788.py:583: DeprecationWarning:

to_plotly_figure is deprecated and will be removed in version 4.0.0. Use MolGraph.to_plotly() instead.

C:\Users\George\AppData\Local\Temp\ipykernel_7832\386804788.py:589: DeprecationWarning:

to_networkx_graph is deprecated and will be removed in version 4.0.0. Use MolGraph.to_networkx() instead.

Pd number index:  0
['Pd', 'N', 'N', 'C', 'C', 'C', 'C', 'C', 'C', 'H', 'H', 'C', 'C', 'C', 'C', 'C', 'C', 'H', 'H', 'C', 'H', 'H', 'H', 'C', 'H', 'H', 'H', 'C', 'C', 'C', 'H', 'C', 'H', 'C', 'C', 'C', 'C', 'C', 'H', 'C', 'H', 'H', 'H', 'C', 'C', 'C', 'C', 'C', 'H', 'C', 'H', 'H', 'H', 'C', 'H', 'H', 'H', 'C', 'H', 'H', 'H', 'C', 'H', 'H', 'H', 'C', 'H', 'H', 'H', 'Br', 'Br']
Ligand atom label:  2  Ligand atom A nbo:  -0.46344
Ligand atom label:  3  Ligand atom B nbo:  -0.46433
Atom_a:  2 Atom_b:  3
C:\Users\George\Desktop\Research_UCLA\CIC\Computational Work\Project cluster version 2\project_catalyst_repurposing\structures_ligand_id\pd_me2_structures\ligand_xyz\ligand-437-n-n-102-ligand_xyz.txt
Starting node: 0
Ending node: 1
(-1.354337, -0.391055, 0.111258)   0
(-0.742369, 0.729136, 0.077706)   20
(0.742408, 0.72968, 0.078262)   18
(1.355244, -0.389888, 0.115729)   1
ligand-438-n-n-103
Pd number index:  0
['Pd', 'N', 'N', 'C', 'C', 'C', 'C', 'C', 'C', 'H', 'H', 'C', 'C', 'C', 'C', 'C', 'C', 'H', 'H', 'C', 'H', 'H', 'H', 'C', 'H', 'H', 'H', 'C', 'C', 'C', 'H', 'C', 'H', 'C', 'C', 'C', 'C', 'C', 'H', 'C', 'H', 'H', 'H', 'C', 'C', 'C', 'C', 'C', 'H', 'C', 'H', 'H', 'H', 'H', 'H', 'H', 'H', 'Cl', 'Cl']

C:\Users\George\AppData\Local\Temp\ipykernel_7832\386804788.py:583: DeprecationWarning:

to_plotly_figure is deprecated and will be removed in version 4.0.0. Use MolGraph.to_plotly() instead.

C:\Users\George\AppData\Local\Temp\ipykernel_7832\386804788.py:589: DeprecationWarning:

to_networkx_graph is deprecated and will be removed in version 4.0.0. Use MolGraph.to_networkx() instead.

Ligand atom label:  2  Ligand atom B nbo:  -0.46136
Ligand atom label:  3  Ligand atom A nbo:  -0.46208
Atom_a:  2 Atom_b:  3
C:\Users\George\Desktop\Research_UCLA\CIC\Computational Work\Project cluster version 2\project_catalyst_repurposing\structures_ligand_id\pd_me2_structures\ligand_xyz\ligand-438-n-n-103-ligand_xyz.txt

C:\Users\George\AppData\Local\Temp\ipykernel_7832\386804788.py:583: DeprecationWarning:

to_plotly_figure is deprecated and will be removed in version 4.0.0. Use MolGraph.to_plotly() instead.

C:\Users\George\AppData\Local\Temp\ipykernel_7832\386804788.py:589: DeprecationWarning:

to_networkx_graph is deprecated and will be removed in version 4.0.0. Use MolGraph.to_networkx() instead.

Starting node: 0
Ending node: 1
(-1.356785, -0.575052, -0.049063)   0
(-0.741638, 0.548821, -0.036)   20
(0.741654, 0.548585, 0.035951)   18
(1.356477, -0.575488, 0.048803)   1
ligand-439-p-o-141
Pd number index:  2
['P', 'C', 'Pd', 'C', 'H', 'H', 'H', 'C', 'H', 'H', 'H', 'O', 'H', 'H', 'C', 'C', 'C', 'C', 'C', 'H', 'C', 'H', 'C', 'H', 'H', 'H', 'C', 'C', 'C', 'C', 'C', 'H', 'C', 'H', 'H', 'H', 'C', 'C', 'C', 'C', 'C', 'H', 'C', 'H', 'H', 'H', 'O', 'O', 'C', 'H', 'H', 'H', 'C', 'H', 'H', 'H']
Ligand atom label:  1  Ligand atom B nbo:  1.00911
Ligand atom label:  12  Ligand atom A nbo:  -0.47716
Atom_a:  1 Atom_b:  12
C:\Users\George\Desktop\Research_UCLA\CIC\Computational Work\Project cluster version 2\project_catalyst_repurposing\structures_ligand_id\pd_me2_structures\ligand_xyz\ligand-439-p-o-141-ligand_xyz.txt
Starting node: 0
Ending node: 2
(-0.495796, -0.181605, -0.231922)   0
(1.017574, 0.261524, -1.235742)   1
(2.141724, 0.648762, -0.311096)   5
(1.891288, 1.22677, 0.740174)   2
ligand-440-p-o-142

C:\Users\George\AppData\Local\Temp\ipykernel_7832\386804788.py:583: DeprecationWarning:

to_plotly_figure is deprecated and will be removed in version 4.0.0. Use MolGraph.to_plotly() instead.

C:\Users\George\AppData\Local\Temp\ipykernel_7832\386804788.py:589: DeprecationWarning:

to_networkx_graph is deprecated and will be removed in version 4.0.0. Use MolGraph.to_networkx() instead.

Pd number index:  1
['P', 'Pd', 'C', 'H', 'H', 'H', 'C', 'H', 'H', 'H', 'O', 'C', 'C', 'C', 'C', 'C', 'H', 'C', 'H', 'C', 'H', 'H', 'H', 'C', 'C', 'C', 'C', 'C', 'H', 'C', 'H', 'H', 'H', 'C', 'C', 'C', 'C', 'C', 'H', 'C', 'H', 'H', 'H', 'O', 'O', 'C', 'H', 'H', 'H', 'C', 'H', 'H', 'H', 'N', 'C', 'H', 'H', 'H']
Ligand atom label:  1  Ligand atom A nbo:  1.2043
Ligand atom label:  44  Ligand atom B nbo:  -0.54259
Atom_a:  1 Atom_b:  44
C:\Users\George\Desktop\Research_UCLA\CIC\Computational Work\Project cluster version 2\project_catalyst_repurposing\structures_ligand_id\pd_me2_structures\ligand_xyz\ligand-440-p-o-142-ligand_xyz.txt
Starting node: 0
Ending node: 34
(-0.267582, 0.118476, -0.211795)   0
(-0.253229, -1.544679, -0.994422)   14
(-1.264461, -2.45039, -0.62314)   15
(-2.190222, -2.008749, 0.273397)   34
ligand-441-p-o-143

C:\Users\George\AppData\Local\Temp\ipykernel_7832\386804788.py:583: DeprecationWarning:

to_plotly_figure is deprecated and will be removed in version 4.0.0. Use MolGraph.to_plotly() instead.

C:\Users\George\AppData\Local\Temp\ipykernel_7832\386804788.py:589: DeprecationWarning:

to_networkx_graph is deprecated and will be removed in version 4.0.0. Use MolGraph.to_networkx() instead.

Pd number index:  1
['P', 'Pd', 'C', 'H', 'H', 'H', 'C', 'H', 'H', 'H', 'O', 'C', 'C', 'C', 'C', 'C', 'H', 'C', 'H', 'C', 'H', 'H', 'H', 'C', 'C', 'C', 'C', 'C', 'H', 'C', 'H', 'H', 'H', 'C', 'C', 'C', 'C', 'C', 'H', 'C', 'H', 'H', 'H', 'N', 'C', 'H', 'H', 'H', 'C', 'C', 'F', 'F', 'F', 'F', 'F', 'F']
Ligand atom label:  1  Ligand atom B nbo:  1.18787
Ligand atom label:  11  Ligand atom A nbo:  -0.56072
Atom_a:  1 Atom_b:  11
C:\Users\George\Desktop\Research_UCLA\CIC\Computational Work\Project cluster version 2\project_catalyst_repurposing\structures_ligand_id\pd_me2_structures\ligand_xyz\ligand-441-p-o-143-ligand_xyz.txt

C:\Users\George\AppData\Local\Temp\ipykernel_7832\386804788.py:583: DeprecationWarning:

to_plotly_figure is deprecated and will be removed in version 4.0.0. Use MolGraph.to_plotly() instead.

C:\Users\George\AppData\Local\Temp\ipykernel_7832\386804788.py:589: DeprecationWarning:

to_networkx_graph is deprecated and will be removed in version 4.0.0. Use MolGraph.to_networkx() instead.

Starting node: 0
Ending node: 1
(0.319458, 0.054945, 0.16616)   0
(-1.334693, 0.323969, 0.807667)   34
(-2.353523, -0.072229, -0.025562)   2
(-2.140669, -0.485547, -1.162199)   1
ligand-442-p-o-144
Pd number index:  1
['P', 'Pd', 'C', 'H', 'H', 'H', 'C', 'H', 'H', 'H', 'O', 'C', 'C', 'C', 'C', 'C', 'H', 'C', 'H', 'C', 'H', 'H', 'H', 'C', 'C', 'C', 'C', 'C', 'H', 'C', 'H', 'H', 'H', 'C', 'C', 'C', 'C', 'C', 'H', 'C', 'H', 'H', 'H', 'N', 'C', 'H', 'H', 'H', 'H', 'C', 'C', 'C', 'C', 'C', 'C', 'H', 'H', 'H', 'O', 'O', 'C', 'H', 'H', 'H', 'C', 'H', 'H', 'H']
Ligand atom label:  1  Ligand atom B nbo:  1.19954
Ligand atom label:  11  Ligand atom A nbo:  -0.58227
Atom_a:  1 Atom_b:  11
C:\Users\George\Desktop\Research_UCLA\CIC\Computational Work\Project cluster version 2\project_catalyst_repurposing\structures_ligand_id\pd_me2_structures\ligand_xyz\ligand-442-p-o-144-ligand_xyz.txt

C:\Users\George\AppData\Local\Temp\ipykernel_7832\386804788.py:583: DeprecationWarning:

to_plotly_figure is deprecated and will be removed in version 4.0.0. Use MolGraph.to_plotly() instead.

C:\Users\George\AppData\Local\Temp\ipykernel_7832\386804788.py:589: DeprecationWarning:

to_networkx_graph is deprecated and will be removed in version 4.0.0. Use MolGraph.to_networkx() instead.

Starting node: 0
Ending node: 1
(1.252913, 0.001999, 0.22224)   0
(-0.342415, -0.386137, 0.909409)   34
(-1.067406, -1.351527, 0.258292)   2
(-0.722366, -1.825332, -0.824709)   1
ligand-443-p-o-145
Pd number index:  1
['P', 'Pd', 'C', 'H', 'H', 'H', 'C', 'H', 'H', 'H', 'O', 'C', 'C', 'C', 'C', 'C', 'H', 'C', 'H', 'C', 'H', 'H', 'H', 'C', 'C', 'C', 'C', 'C', 'H', 'C', 'H', 'H', 'H', 'C', 'C', 'C', 'C', 'C', 'H', 'C', 'H', 'H', 'H', 'N', 'C', 'H', 'H', 'H', 'H', 'C', 'C', 'C', 'C', 'C', 'C', 'H', 'H', 'H', 'F', 'F']
Ligand atom label:  1  Ligand atom B nbo:  1.19571
Ligand atom label:  11  Ligand atom A nbo:  -0.57692
Atom_a:  1 Atom_b:  11
C:\Users\George\Desktop\Research_UCLA\CIC\Computational Work\Project cluster version 2\project_catalyst_repurposing\structures_ligand_id\pd_me2_structures\ligand_xyz\ligand-443-p-o-145-ligand_xyz.txt
Starting node: 0
Ending node: 1
(-1.050498, 0.455755, -0.013785)   0
(0.520296, 1.016095, 0.626095)   34
(1.607938, 0.826241, -0.194445)   2
(1.551343, 0.158252, -1.225022)   1
ligand-444-p-o-146
Pd number index:  1
['P', 'Pd', 'C', 'H', 'H', 'H', 'C', 'H', 'H', 'H', 'O', 'C', 'C', 'C', 'C', 'C', 'H', 'C', 'H', 'C', 'H', 'H', 'H', 'N', 'C', 'H', 'H', 'H', 'C', 'C', 'H', 'H', 'H', 'C', 'H', 'H', 'H', 'C', 'H', 'H', 'H', 'C', 'C', 'H', 'H', 'H', 'C', 'H', 'H', 'H', 'C', 'H', 'H', 'H']

C:\Users\George\AppData\Local\Temp\ipykernel_7832\386804788.py:583: DeprecationWarning:

to_plotly_figure is deprecated and will be removed in version 4.0.0. Use MolGraph.to_plotly() instead.

C:\Users\George\AppData\Local\Temp\ipykernel_7832\386804788.py:589: DeprecationWarning:

to_networkx_graph is deprecated and will be removed in version 4.0.0. Use MolGraph.to_networkx() instead.

Ligand atom label:  1  Ligand atom B nbo:  1.19898
Ligand atom label:  11  Ligand atom A nbo:  -0.48762
Atom_a:  1 Atom_b:  11
C:\Users\George\Desktop\Research_UCLA\CIC\Computational Work\Project cluster version 2\project_catalyst_repurposing\structures_ligand_id\pd_me2_structures\ligand_xyz\ligand-444-p-o-146-ligand_xyz.txt
Starting node: 0
Ending node: 1
(0.996542, 0.675498, -0.030947)   0
(-0.774913, 0.900783, -0.166271)   14
(-1.539954, -0.240927, -0.118201)   2
(-1.067271, -1.373843, -0.105776)   1
ligand-445-p-o-147

C:\Users\George\AppData\Local\Temp\ipykernel_7832\386804788.py:583: DeprecationWarning:

to_plotly_figure is deprecated and will be removed in version 4.0.0. Use MolGraph.to_plotly() instead.

C:\Users\George\AppData\Local\Temp\ipykernel_7832\386804788.py:589: DeprecationWarning:

to_networkx_graph is deprecated and will be removed in version 4.0.0. Use MolGraph.to_networkx() instead.

Pd number index:  1
['P', 'Pd', 'C', 'H', 'H', 'H', 'C', 'H', 'H', 'H', 'O', 'C', 'C', 'C', 'C', 'C', 'H', 'C', 'H', 'C', 'H', 'H', 'H', 'C', 'C', 'C', 'C', 'C', 'H', 'C', 'H', 'H', 'H', 'C', 'C', 'C', 'C', 'C', 'H', 'C', 'H', 'H', 'H', 'N', 'H', 'C', 'C', 'C', 'C', 'C', 'C', 'H', 'H', 'H', 'O', 'O', 'C', 'H', 'H', 'H', 'C', 'H', 'H', 'H', 'H']
Ligand atom label:  1  Ligand atom B nbo:  1.16799
Ligand atom label:  11  Ligand atom A nbo:  -0.5047
Atom_a:  1 Atom_b:  11
C:\Users\George\Desktop\Research_UCLA\CIC\Computational Work\Project cluster version 2\project_catalyst_repurposing\structures_ligand_id\pd_me2_structures\ligand_xyz\ligand-445-p-o-147-ligand_xyz.txt
Starting node: 0
Ending node: 1
(1.192834, -0.441417, 0.017771)   0
(-0.397158, -1.188326, -0.1013)   34
(-1.260795, -0.805513, -1.088216)   2
(-0.968709, 0.031626, -1.937719)   1
ligand-446-p-o-148

C:\Users\George\AppData\Local\Temp\ipykernel_7832\386804788.py:583: DeprecationWarning:

to_plotly_figure is deprecated and will be removed in version 4.0.0. Use MolGraph.to_plotly() instead.

C:\Users\George\AppData\Local\Temp\ipykernel_7832\386804788.py:589: DeprecationWarning:

to_networkx_graph is deprecated and will be removed in version 4.0.0. Use MolGraph.to_networkx() instead.

Pd number index:  1
['P', 'Pd', 'C', 'H', 'H', 'H', 'C', 'H', 'H', 'H', 'O', 'C', 'C', 'C', 'C', 'C', 'H', 'C', 'H', 'C', 'H', 'H', 'H', 'C', 'C', 'C', 'C', 'C', 'H', 'C', 'H', 'H', 'H', 'C', 'C', 'C', 'C', 'C', 'H', 'C', 'H', 'H', 'H', 'N', 'H', 'C', 'C', 'C', 'C', 'C', 'C', 'H', 'H', 'H', 'O', 'O', 'C', 'H', 'H', 'H', 'C', 'H', 'H', 'H', 'C', 'H', 'H', 'C', 'C', 'C', 'C', 'H', 'C', 'H', 'C', 'H', 'H', 'H']
Ligand atom label:  1  Ligand atom B nbo:  1.17255
Ligand atom label:  11  Ligand atom A nbo:  -0.50683
Atom_a:  1 Atom_b:  11
C:\Users\George\Desktop\Research_UCLA\CIC\Computational Work\Project cluster version 2\project_catalyst_repurposing\structures_ligand_id\pd_me2_structures\ligand_xyz\ligand-446-p-o-148-ligand_xyz.txt
Starting node: 0
Ending node: 1
(-0.109469, 1.019995, -0.170339)   0
(0.78851, -0.528338, -0.088878)   34
(0.324438, -1.498271, -0.953862)   2
(-0.658695, -1.357239, -1.674224)   1
ligand-447-p-o-149

C:\Users\George\AppData\Local\Temp\ipykernel_7832\386804788.py:583: DeprecationWarning:

to_plotly_figure is deprecated and will be removed in version 4.0.0. Use MolGraph.to_plotly() instead.

C:\Users\George\AppData\Local\Temp\ipykernel_7832\386804788.py:589: DeprecationWarning:

to_networkx_graph is deprecated and will be removed in version 4.0.0. Use MolGraph.to_networkx() instead.

Pd number index:  1
['P', 'Pd', 'C', 'H', 'H', 'H', 'C', 'H', 'H', 'H', 'O', 'C', 'C', 'C', 'C', 'C', 'C', 'H', 'C', 'H', 'H', 'H', 'C', 'C', 'C', 'C', 'C', 'H', 'C', 'H', 'H', 'H', 'N', 'C', 'H', 'H', 'H', 'H', 'C', 'C', 'C', 'C', 'C', 'C', 'H', 'H', 'H', 'O', 'O', 'C', 'H', 'H', 'H', 'C', 'H', 'H', 'H', 'C', 'H', 'C', 'H', 'H', 'H', 'C', 'H', 'H', 'H']
Ligand atom label:  1  Ligand atom B nbo:  1.20029
Ligand atom label:  11  Ligand atom A nbo:  -0.59254
Atom_a:  1 Atom_b:  11
C:\Users\George\Desktop\Research_UCLA\CIC\Computational Work\Project cluster version 2\project_catalyst_repurposing\structures_ligand_id\pd_me2_structures\ligand_xyz\ligand-447-p-o-149-ligand_xyz.txt
Starting node: 0
Ending node: 1
(0.916273, -0.469739, 0.085239)   0
(-0.16687, 0.004395, -1.244156)   23
(-0.290985, 1.351132, -1.487466)   2
(0.296906, 2.192473, -0.808601)   1
ligand-448-p-o-150

C:\Users\George\AppData\Local\Temp\ipykernel_7832\386804788.py:583: DeprecationWarning:

to_plotly_figure is deprecated and will be removed in version 4.0.0. Use MolGraph.to_plotly() instead.

C:\Users\George\AppData\Local\Temp\ipykernel_7832\386804788.py:589: DeprecationWarning:

to_networkx_graph is deprecated and will be removed in version 4.0.0. Use MolGraph.to_networkx() instead.

Pd number index:  1
['P', 'Pd', 'C', 'H', 'H', 'H', 'C', 'H', 'H', 'H', 'O', 'C', 'C', 'C', 'C', 'C', 'C', 'H', 'C', 'H', 'H', 'H', 'C', 'C', 'C', 'C', 'C', 'H', 'C', 'H', 'H', 'H', 'N', 'C', 'H', 'H', 'H', 'H', 'C', 'C', 'C', 'C', 'C', 'C', 'H', 'H', 'H', 'O', 'O', 'C', 'H', 'H', 'H', 'C', 'H', 'H', 'H', 'C', 'C', 'C', 'C', 'H', 'C', 'H', 'H', 'H', 'N']
Ligand atom label:  1  Ligand atom B nbo:  1.20432
Ligand atom label:  11  Ligand atom A nbo:  -0.56306
Atom_a:  1 Atom_b:  11
C:\Users\George\Desktop\Research_UCLA\CIC\Computational Work\Project cluster version 2\project_catalyst_repurposing\structures_ligand_id\pd_me2_structures\ligand_xyz\ligand-448-p-o-150-ligand_xyz.txt
Starting node: 0
Ending node: 1
(1.227415, 0.040746, 0.220641)   0
(-0.390559, -0.390637, 0.828469)   23
(-1.04838, -1.384634, 0.158673)   2
(-0.649965, -1.885024, -0.888079)   1
ligand-449-p-o-151

C:\Users\George\AppData\Local\Temp\ipykernel_7832\386804788.py:583: DeprecationWarning:

to_plotly_figure is deprecated and will be removed in version 4.0.0. Use MolGraph.to_plotly() instead.

C:\Users\George\AppData\Local\Temp\ipykernel_7832\386804788.py:589: DeprecationWarning:

to_networkx_graph is deprecated and will be removed in version 4.0.0. Use MolGraph.to_networkx() instead.

Pd number index:  1
['P', 'Pd', 'C', 'H', 'H', 'H', 'C', 'H', 'H', 'H', 'O', 'C', 'C', 'C', 'C', 'C', 'C', 'H', 'C', 'H', 'H', 'H', 'C', 'C', 'C', 'C', 'C', 'H', 'C', 'H', 'H', 'H', 'N', 'C', 'H', 'H', 'H', 'H', 'C', 'C', 'C', 'C', 'C', 'C', 'H', 'H', 'H', 'O', 'O', 'C', 'H', 'H', 'H', 'C', 'H', 'H', 'H', 'C', 'C', 'C', 'H', 'C', 'H', 'H', 'C', 'H', 'N']
Ligand atom label:  1  Ligand atom B nbo:  1.20256
Ligand atom label:  11  Ligand atom A nbo:  -0.58097
Atom_a:  1 Atom_b:  11
C:\Users\George\Desktop\Research_UCLA\CIC\Computational Work\Project cluster version 2\project_catalyst_repurposing\structures_ligand_id\pd_me2_structures\ligand_xyz\ligand-449-p-o-151-ligand_xyz.txt
Starting node: 0
Ending node: 1
(1.262654, 0.026497, 0.204535)   0
(-0.332484, -0.290726, 0.936118)   23
(-1.047159, -1.332754, 0.40628)   2
(-0.69183, -1.941146, -0.602913)   1
ligand-450-p-o-152

C:\Users\George\AppData\Local\Temp\ipykernel_7832\386804788.py:583: DeprecationWarning:

to_plotly_figure is deprecated and will be removed in version 4.0.0. Use MolGraph.to_plotly() instead.

C:\Users\George\AppData\Local\Temp\ipykernel_7832\386804788.py:589: DeprecationWarning:

to_networkx_graph is deprecated and will be removed in version 4.0.0. Use MolGraph.to_networkx() instead.

Pd number index:  1
['P', 'Pd', 'C', 'H', 'H', 'H', 'C', 'H', 'H', 'H', 'O', 'C', 'C', 'C', 'C', 'C', 'C', 'H', 'C', 'H', 'H', 'H', 'C', 'C', 'C', 'C', 'C', 'H', 'C', 'H', 'H', 'H', 'N', 'C', 'H', 'H', 'H', 'H', 'C', 'C', 'C', 'C', 'C', 'C', 'H', 'H', 'H', 'O', 'O', 'C', 'H', 'H', 'H', 'C', 'H', 'H', 'H', 'C', 'C', 'C', 'H', 'H', 'C', 'H', 'C', 'H', 'N']
Ligand atom label:  1  Ligand atom B nbo:  1.2026
Ligand atom label:  11  Ligand atom A nbo:  -0.58071
Atom_a:  1 Atom_b:  11
C:\Users\George\Desktop\Research_UCLA\CIC\Computational Work\Project cluster version 2\project_catalyst_repurposing\structures_ligand_id\pd_me2_structures\ligand_xyz\ligand-450-p-o-152-ligand_xyz.txt

C:\Users\George\AppData\Local\Temp\ipykernel_7832\386804788.py:583: DeprecationWarning:

to_plotly_figure is deprecated and will be removed in version 4.0.0. Use MolGraph.to_plotly() instead.

C:\Users\George\AppData\Local\Temp\ipykernel_7832\386804788.py:589: DeprecationWarning:

to_networkx_graph is deprecated and will be removed in version 4.0.0. Use MolGraph.to_networkx() instead.

Starting node: 0
Ending node: 1
(1.249605, -0.034367, 0.230495)   0
(-0.364974, -0.419165, 0.882345)   23
(-1.084149, -1.362008, 0.201078)   2
(-0.734552, -1.828772, -0.881757)   1
ligand-451-n-o-18
Pd number index:  10
['N', 'C', 'C', 'C', 'C', 'C', 'C', 'H', 'H', 'H', 'Pd', 'C', 'H', 'H', 'H', 'C', 'H', 'H', 'H', 'C', 'C', 'C', 'C', 'H', 'C', 'C', 'H', 'H', 'H', 'C', 'O', 'O', 'C', 'H', 'H', 'H', 'H', 'H']
Ligand atom label:  1  Ligand atom B nbo:  -0.58571
Ligand atom label:  32  Ligand atom A nbo:  -0.60417
Atom_a:  1 Atom_b:  32
C:\Users\George\Desktop\Research_UCLA\CIC\Computational Work\Project cluster version 2\project_catalyst_repurposing\structures_ligand_id\pd_me2_structures\ligand_xyz\ligand-451-n-o-18-ligand_xyz.txt

C:\Users\George\AppData\Local\Temp\ipykernel_7832\386804788.py:583: DeprecationWarning:

to_plotly_figure is deprecated and will be removed in version 4.0.0. Use MolGraph.to_plotly() instead.

C:\Users\George\AppData\Local\Temp\ipykernel_7832\386804788.py:589: DeprecationWarning:

to_networkx_graph is deprecated and will be removed in version 4.0.0. Use MolGraph.to_networkx() instead.

Starting node: 0
Ending node: 22
(0.471662, 0.449618, 0.027862)   0
(-0.336936, 1.506103, 0.04749)   10
(-1.790177, 1.434552, 0.032228)   12
(-2.511777, 0.1777, -0.048456)   20
(-2.070128, -0.961342, -0.088457)   22
ligand-452-n-o-19
Pd number index:  30
['N', 'C', 'C', 'C', 'C', 'C', 'C', 'H', 'H', 'H', 'C', 'H', 'C', 'H', 'H', 'H', 'C', 'H', 'H', 'H', 'C', 'H', 'C', 'H', 'H', 'H', 'C', 'H', 'H', 'H', 'Pd', 'C', 'H', 'H', 'H', 'C', 'H', 'H', 'H', 'C', 'C', 'C', 'C', 'H', 'C', 'C', 'H', 'H', 'H', 'C', 'O', 'O', 'C', 'H', 'H', 'H']
Ligand atom label:  1  Ligand atom B nbo:  -0.61174
Ligand atom label:  52  Ligand atom A nbo:  -0.60489
Atom_a:  52 Atom_b:  1
C:\Users\George\Desktop\Research_UCLA\CIC\Computational Work\Project cluster version 2\project_catalyst_repurposing\structures_ligand_id\pd_me2_structures\ligand_xyz\ligand-452-n-o-19-ligand_xyz.txt
Ending node: 0
Starting node: 42
(2.50527, 0.81595, 0.135577)   42
(2.839725, -0.357744, 0.055657)   40
(2.000935, -1.535218, -0.071473)   32
(0.555963, -1.4557, -0.215066)   30
(-0.14514, -0.32425, -0.189028)   0
ligand-453-n-n-20

C:\Users\George\AppData\Local\Temp\ipykernel_7832\386804788.py:583: DeprecationWarning:

to_plotly_figure is deprecated and will be removed in version 4.0.0. Use MolGraph.to_plotly() instead.

C:\Users\George\AppData\Local\Temp\ipykernel_7832\386804788.py:589: DeprecationWarning:

to_networkx_graph is deprecated and will be removed in version 4.0.0. Use MolGraph.to_networkx() instead.

Pd number index:  0
['Pd', 'C', 'C', 'N', 'N', 'C', 'C', 'C', 'C', 'C', 'C', 'H', 'H', 'C', 'C', 'C', 'C', 'C', 'C', 'H', 'H', 'C', 'H', 'H', 'H', 'C', 'H', 'H', 'H', 'C', 'H', 'H', 'H', 'C', 'H', 'H', 'H', 'H', 'H', 'C', 'C', 'C', 'C', 'H', 'C', 'H', 'C', 'H', 'H', 'H', 'C', 'C', 'C', 'C', 'H', 'C', 'H', 'C', 'H', 'H', 'H', 'C', 'C', 'C', 'C', 'H', 'C', 'H', 'C', 'H', 'H', 'H', 'C', 'C', 'C', 'C', 'H', 'C', 'H', 'C', 'H', 'H', 'H']
Ligand atom label:  4  Ligand atom B nbo:  -0.47891
Ligand atom label:  5  Ligand atom A nbo:  -0.47607
Atom_a:  5 Atom_b:  4
C:\Users\George\Desktop\Research_UCLA\CIC\Computational Work\Project cluster version 2\project_catalyst_repurposing\structures_ligand_id\pd_me2_structures\ligand_xyz\ligand-453-n-n-20-ligand_xyz.txt
Ending node: 2
Starting node: 3
(0.812264, -1.030745, 0.314011)   3
(0.270983, -0.682751, 1.42567)   1
(-0.678143, 0.472384, 1.377081)   0
(-0.878758, 1.017536, 0.229743)   2
ligand-454-n-n-21

C:\Users\George\AppData\Local\Temp\ipykernel_7832\386804788.py:583: DeprecationWarning:

to_plotly_figure is deprecated and will be removed in version 4.0.0. Use MolGraph.to_plotly() instead.

C:\Users\George\AppData\Local\Temp\ipykernel_7832\386804788.py:589: DeprecationWarning:

to_networkx_graph is deprecated and will be removed in version 4.0.0. Use MolGraph.to_networkx() instead.

Pd number index:  0
['Pd', 'C', 'C', 'N', 'N', 'C', 'C', 'C', 'C', 'C', 'C', 'H', 'H', 'C', 'C', 'C', 'C', 'C', 'C', 'H', 'H', 'C', 'H', 'H', 'H', 'C', 'H', 'H', 'H', 'C', 'H', 'H', 'H', 'C', 'H', 'H', 'H', 'H', 'H', 'C', 'C', 'C', 'C', 'H', 'C', 'H', 'C', 'H', 'H', 'C', 'C', 'C', 'C', 'H', 'C', 'H', 'C', 'H', 'C', 'C', 'C', 'C', 'H', 'C', 'H', 'C', 'H', 'H', 'C', 'C', 'C', 'C', 'H', 'C', 'H', 'C', 'H', 'H', 'O', 'O', 'O', 'C', 'H', 'H', 'H', 'C', 'H', 'H', 'H', 'C', 'H', 'H', 'H', 'H', 'O', 'C', 'H', 'H', 'H']
Ligand atom label:  4  Ligand atom A nbo:  -0.47875
Ligand atom label:  5  Ligand atom B nbo:  -0.47575
Atom_a:  5 Atom_b:  4
C:\Users\George\Desktop\Research_UCLA\CIC\Computational Work\Project cluster version 2\project_catalyst_repurposing\structures_ligand_id\pd_me2_structures\ligand_xyz\ligand-454-n-n-21-ligand_xyz.txt
Ending node: 2
Starting node: 3
(0.233342, 1.309729, 0.298462)   3
(0.357398, 0.612783, 1.371702)   1
(0.261689, -0.871956, 1.222361)   0
(-0.16316, -1.322955, 0.095362)   2
ligand-455-n-n-22

C:\Users\George\AppData\Local\Temp\ipykernel_7832\386804788.py:583: DeprecationWarning:

to_plotly_figure is deprecated and will be removed in version 4.0.0. Use MolGraph.to_plotly() instead.

C:\Users\George\AppData\Local\Temp\ipykernel_7832\386804788.py:589: DeprecationWarning:

to_networkx_graph is deprecated and will be removed in version 4.0.0. Use MolGraph.to_networkx() instead.

Pd number index:  0
['Pd', 'C', 'C', 'N', 'N', 'C', 'C', 'C', 'C', 'C', 'C', 'H', 'H', 'C', 'C', 'C', 'C', 'C', 'C', 'H', 'H', 'C', 'H', 'H', 'H', 'C', 'H', 'H', 'H', 'C', 'H', 'H', 'H', 'C', 'H', 'H', 'H', 'H', 'H', 'C', 'C', 'C', 'C', 'H', 'C', 'H', 'C', 'H', 'H', 'C', 'C', 'C', 'C', 'H', 'C', 'H', 'C', 'H', 'C', 'C', 'C', 'C', 'H', 'C', 'H', 'C', 'H', 'H', 'C', 'C', 'C', 'C', 'H', 'C', 'H', 'C', 'H', 'H', 'C', 'H', 'H', 'H', 'C', 'H', 'H', 'H', 'C', 'H', 'H', 'H', 'C', 'C', 'C', 'C', 'H', 'H', 'H', 'C', 'H', 'H', 'H', 'C', 'H', 'H', 'H', 'C', 'H', 'H', 'H', 'C', 'H', 'H', 'H', 'C', 'H', 'H', 'H', 'H', 'C', 'C', 'H', 'H', 'H', 'C', 'H', 'H', 'H', 'C', 'H', 'H', 'H']
Ligand atom label:  4  Ligand atom B nbo:  -0.48026
Ligand atom label:  5  Ligand atom A nbo:  -0.47831
Atom_a:  5 Atom_b:  4
C:\Users\George\Desktop\Research_UCLA\CIC\Computational Work\Project cluster version 2\project_catalyst_repurposing\structures_ligand_id\pd_me2_structures\ligand_xyz\ligand-455-n-n-22-ligand_xyz.txt
Ending node: 2
Starting node: 3
(0.163452, -1.227355, 0.676569)   3
(0.095105, -0.126588, 1.337808)   1
(-0.131712, 1.118571, 0.543219)   0
(0.012523, 1.026207, -0.729453)   2
ligand-456-p-o-153

C:\Users\George\AppData\Local\Temp\ipykernel_7832\386804788.py:583: DeprecationWarning:

to_plotly_figure is deprecated and will be removed in version 4.0.0. Use MolGraph.to_plotly() instead.

C:\Users\George\AppData\Local\Temp\ipykernel_7832\386804788.py:589: DeprecationWarning:

to_networkx_graph is deprecated and will be removed in version 4.0.0. Use MolGraph.to_networkx() instead.

Pd number index:  34
['P', 'C', 'C', 'S', 'O', 'O', 'O', 'C', 'C', 'C', 'C', 'C', 'C', 'H', 'H', 'H', 'C', 'C', 'C', 'C', 'C', 'H', 'H', 'H', 'H', 'C', 'C', 'C', 'C', 'C', 'H', 'H', 'H', 'H', 'Pd', 'C', 'H', 'H', 'H', 'C', 'H', 'H', 'H', 'C', 'H', 'H', 'H', 'C', 'H', 'H', 'H', 'C', 'H', 'H', 'H']
Ligand atom label:  1  Ligand atom B nbo:  0.96187
Ligand atom label:  5  Ligand atom A nbo:  -0.93958
Atom_a:  1 Atom_b:  5
C:\Users\George\Desktop\Research_UCLA\CIC\Computational Work\Project cluster version 2\project_catalyst_repurposing\structures_ligand_id\pd_me2_structures\ligand_xyz\ligand-456-p-o-153-ligand_xyz.txt
Starting node: 0
Ending node: 4
(0.368022, -0.188905, 0.155709)   0
(-0.005788, 1.546415, -0.373046)   1
(-1.323095, 2.025954, -0.278752)   2
(-2.673192, 1.003889, 0.374081)   3
(-2.844558, -0.066409, -0.666288)   4
ligand-457-p-o-154

C:\Users\George\AppData\Local\Temp\ipykernel_7832\386804788.py:583: DeprecationWarning:

to_plotly_figure is deprecated and will be removed in version 4.0.0. Use MolGraph.to_plotly() instead.

C:\Users\George\AppData\Local\Temp\ipykernel_7832\386804788.py:589: DeprecationWarning:

to_networkx_graph is deprecated and will be removed in version 4.0.0. Use MolGraph.to_networkx() instead.

Pd number index:  34
['P', 'C', 'C', 'S', 'O', 'O', 'O', 'C', 'C', 'C', 'C', 'C', 'C', 'H', 'H', 'H', 'C', 'C', 'C', 'C', 'C', 'H', 'H', 'H', 'H', 'C', 'C', 'C', 'C', 'C', 'H', 'H', 'H', 'H', 'Pd', 'C', 'H', 'H', 'H', 'C', 'H', 'H', 'H', 'C', 'H', 'H', 'H', 'C', 'H', 'H', 'H', 'H']
Ligand atom label:  1  Ligand atom B nbo:  0.96151
Ligand atom label:  5  Ligand atom A nbo:  -0.93865
Atom_a:  1 Atom_b:  5
C:\Users\George\Desktop\Research_UCLA\CIC\Computational Work\Project cluster version 2\project_catalyst_repurposing\structures_ligand_id\pd_me2_structures\ligand_xyz\ligand-457-p-o-154-ligand_xyz.txt

C:\Users\George\AppData\Local\Temp\ipykernel_7832\386804788.py:583: DeprecationWarning:

to_plotly_figure is deprecated and will be removed in version 4.0.0. Use MolGraph.to_plotly() instead.

C:\Users\George\AppData\Local\Temp\ipykernel_7832\386804788.py:589: DeprecationWarning:

to_networkx_graph is deprecated and will be removed in version 4.0.0. Use MolGraph.to_networkx() instead.

Starting node: 0
Ending node: 4
(-0.423999, 0.11519, -0.007605)   0
(0.454653, 0.970681, 1.381005)   1
(1.851823, 1.116219, 1.33085)   2
(2.825063, 0.518938, -0.08211)   3
(2.707779, -0.975398, 0.012211)   4
ligand-458-p-o-155
Pd number index:  64
['P', 'O', 'P', 'N', 'C', 'C', 'C', 'C', 'C', 'C', 'H', 'H', 'H', 'H', 'H', 'C', 'C', 'C', 'C', 'C', 'C', 'H', 'H', 'H', 'H', 'H', 'C', 'C', 'C', 'C', 'H', 'C', 'H', 'C', 'H', 'H', 'C', 'C', 'C', 'C', 'C', 'C', 'H', 'H', 'C', 'H', 'H', 'H', 'O', 'H', 'C', 'C', 'C', 'C', 'C', 'C', 'H', 'H', 'H', 'C', 'H', 'H', 'H', 'O', 'Pd', 'H', 'H', 'O', 'C', 'H', 'H', 'H', 'C', 'H', 'H', 'H', 'C', 'H', 'H', 'H']
Ligand atom label:  1  Ligand atom B nbo:  1.20226
Ligand atom label:  2  Ligand atom A nbo:  -1.01146
Atom_a:  1 Atom_b:  2
C:\Users\George\Desktop\Research_UCLA\CIC\Computational Work\Project cluster version 2\project_catalyst_repurposing\structures_ligand_id\pd_me2_structures\ligand_xyz\ligand-458-p-o-155-ligand_xyz.txt
Starting node: 0
Ending node: 1
(-1.252793, -0.35681, 0.597435)   0
(0.35226, 0.185355, 0.119993)   3
(0.41659, 1.490855, -0.972162)   2
(-0.942123, 2.131634, -1.111386)   1
ligand-459-p-o-156

C:\Users\George\AppData\Local\Temp\ipykernel_7832\386804788.py:583: DeprecationWarning:

to_plotly_figure is deprecated and will be removed in version 4.0.0. Use MolGraph.to_plotly() instead.

C:\Users\George\AppData\Local\Temp\ipykernel_7832\386804788.py:589: DeprecationWarning:

to_networkx_graph is deprecated and will be removed in version 4.0.0. Use MolGraph.to_networkx() instead.

Pd number index:  57
['P', 'O', 'P', 'N', 'C', 'C', 'C', 'C', 'C', 'C', 'H', 'H', 'H', 'H', 'H', 'C', 'C', 'C', 'C', 'C', 'C', 'H', 'H', 'H', 'H', 'H', 'C', 'C', 'C', 'C', 'H', 'C', 'H', 'C', 'H', 'H', 'C', 'C', 'C', 'C', 'C', 'C', 'H', 'H', 'H', 'C', 'C', 'C', 'C', 'C', 'C', 'H', 'H', 'H', 'C', 'H', 'H', 'Pd', 'H', 'H', 'C', 'F', 'F', 'F', 'O', 'O', 'C', 'H', 'H', 'H', 'C', 'H', 'H', 'H', 'H', 'C', 'H', 'H', 'H']
Ligand atom label:  1  Ligand atom B nbo:  1.20276
Ligand atom label:  2  Ligand atom A nbo:  -1.00727
Atom_a:  1 Atom_b:  2
C:\Users\George\Desktop\Research_UCLA\CIC\Computational Work\Project cluster version 2\project_catalyst_repurposing\structures_ligand_id\pd_me2_structures\ligand_xyz\ligand-459-p-o-156-ligand_xyz.txt
Starting node: 0
Ending node: 1
(-0.987789, 1.07051, 0.276961)   0
(0.236445, -0.153272, -0.084479)   3
(-0.394607, -1.44585, -1.014569)   2
(-1.339599, -1.02344, -2.116562)   1
ligand-460-p-o-157

C:\Users\George\AppData\Local\Temp\ipykernel_7832\386804788.py:583: DeprecationWarning:

to_plotly_figure is deprecated and will be removed in version 4.0.0. Use MolGraph.to_plotly() instead.

C:\Users\George\AppData\Local\Temp\ipykernel_7832\386804788.py:589: DeprecationWarning:

to_networkx_graph is deprecated and will be removed in version 4.0.0. Use MolGraph.to_networkx() instead.

Pd number index:  57
['P', 'O', 'P', 'N', 'C', 'C', 'C', 'C', 'C', 'C', 'H', 'H', 'H', 'H', 'H', 'C', 'C', 'C', 'C', 'C', 'C', 'H', 'H', 'H', 'H', 'H', 'C', 'C', 'C', 'C', 'H', 'C', 'H', 'C', 'H', 'H', 'C', 'C', 'C', 'C', 'C', 'C', 'H', 'H', 'H', 'C', 'C', 'C', 'C', 'C', 'C', 'H', 'H', 'H', 'C', 'H', 'H', 'Pd', 'H', 'H', 'H', 'H', 'O', 'C', 'H', 'H', 'H', 'C', 'H', 'H', 'H', 'H']
Ligand atom label:  1  Ligand atom A nbo:  1.25548
Ligand atom label:  2  Ligand atom B nbo:  -1.02864
Atom_a:  1 Atom_b:  2
C:\Users\George\Desktop\Research_UCLA\CIC\Computational Work\Project cluster version 2\project_catalyst_repurposing\structures_ligand_id\pd_me2_structures\ligand_xyz\ligand-460-p-o-157-ligand_xyz.txt
Starting node: 0
Ending node: 1
(1.22409, -0.896912, -0.125587)   0
(-0.23702, 0.050798, -0.081201)   3
(-0.104348, 1.68597, -0.467175)   2
(1.149479, 1.954535, -1.215674)   1
ligand-461-p-o-158

C:\Users\George\AppData\Local\Temp\ipykernel_7832\386804788.py:583: DeprecationWarning:

to_plotly_figure is deprecated and will be removed in version 4.0.0. Use MolGraph.to_plotly() instead.

C:\Users\George\AppData\Local\Temp\ipykernel_7832\386804788.py:589: DeprecationWarning:

to_networkx_graph is deprecated and will be removed in version 4.0.0. Use MolGraph.to_networkx() instead.

Pd number index:  57
['P', 'O', 'P', 'N', 'C', 'C', 'C', 'C', 'C', 'C', 'H', 'H', 'H', 'H', 'H', 'C', 'C', 'C', 'C', 'C', 'C', 'H', 'H', 'H', 'H', 'H', 'C', 'C', 'C', 'C', 'H', 'C', 'H', 'C', 'H', 'H', 'C', 'C', 'C', 'C', 'C', 'C', 'H', 'H', 'H', 'C', 'C', 'C', 'C', 'C', 'C', 'H', 'H', 'H', 'C', 'H', 'H', 'Pd', 'H', 'H', 'H', 'H', 'H', 'C', 'H', 'H', 'H', 'H']
Ligand atom label:  1  Ligand atom B nbo:  1.19709
Ligand atom label:  2  Ligand atom A nbo:  -0.99717
Atom_a:  1 Atom_b:  2
C:\Users\George\Desktop\Research_UCLA\CIC\Computational Work\Project cluster version 2\project_catalyst_repurposing\structures_ligand_id\pd_me2_structures\ligand_xyz\ligand-461-p-o-158-ligand_xyz.txt
Starting node: 0
Ending node: 1
(-1.394814, 0.092208, -0.117343)   0
(0.311817, 0.350829, 0.257384)   3
(1.447532, -0.519212, -0.676187)   2
(0.79445, -1.042173, -1.932471)   1
ligand-462-p-o-159

C:\Users\George\AppData\Local\Temp\ipykernel_7832\386804788.py:583: DeprecationWarning:

to_plotly_figure is deprecated and will be removed in version 4.0.0. Use MolGraph.to_plotly() instead.

C:\Users\George\AppData\Local\Temp\ipykernel_7832\386804788.py:589: DeprecationWarning:

to_networkx_graph is deprecated and will be removed in version 4.0.0. Use MolGraph.to_networkx() instead.

Pd number index:  54
['P', 'O', 'P', 'N', 'C', 'C', 'C', 'C', 'C', 'C', 'H', 'H', 'H', 'H', 'H', 'C', 'C', 'C', 'C', 'C', 'C', 'H', 'H', 'H', 'H', 'H', 'C', 'C', 'C', 'C', 'H', 'C', 'H', 'C', 'H', 'H', 'C', 'C', 'C', 'C', 'C', 'C', 'H', 'H', 'H', 'C', 'C', 'C', 'C', 'C', 'C', 'H', 'H', 'H', 'Pd', 'H', 'H', 'H', 'C', 'C', 'C', 'C', 'C', 'C', 'H', 'H', 'H', 'O', 'O', 'C', 'H', 'H', 'H', 'C', 'H', 'H', 'H', 'C', 'C', 'H', 'H', 'H', 'C', 'H', 'H', 'H', 'C', 'H', 'H', 'H', 'C', 'H', 'H', 'H', 'C', 'H', 'H', 'H']
Ligand atom label:  1  Ligand atom B nbo:  1.15159
Ligand atom label:  2  Ligand atom A nbo:  -1.01924
Atom_a:  1 Atom_b:  2
C:\Users\George\Desktop\Research_UCLA\CIC\Computational Work\Project cluster version 2\project_catalyst_repurposing\structures_ligand_id\pd_me2_structures\ligand_xyz\ligand-462-p-o-159-ligand_xyz.txt
Starting node: 0
Ending node: 1
(0.649915, -0.387919, 0.047746)   0
(-0.863774, 0.565123, 0.282154)   3
(-0.769515, 2.090242, -0.491804)   2
(-0.497376, 2.002529, -1.977428)   1
ligand-463-p-o-160

C:\Users\George\AppData\Local\Temp\ipykernel_7832\386804788.py:583: DeprecationWarning:

to_plotly_figure is deprecated and will be removed in version 4.0.0. Use MolGraph.to_plotly() instead.

C:\Users\George\AppData\Local\Temp\ipykernel_7832\386804788.py:589: DeprecationWarning:

to_networkx_graph is deprecated and will be removed in version 4.0.0. Use MolGraph.to_networkx() instead.

Pd number index:  54
['P', 'O', 'P', 'N', 'C', 'C', 'C', 'C', 'C', 'C', 'H', 'H', 'H', 'H', 'H', 'C', 'C', 'C', 'C', 'C', 'C', 'H', 'H', 'H', 'H', 'H', 'C', 'C', 'C', 'C', 'H', 'C', 'H', 'C', 'H', 'H', 'C', 'C', 'C', 'C', 'C', 'C', 'H', 'H', 'H', 'C', 'C', 'C', 'C', 'C', 'C', 'H', 'H', 'H', 'Pd', 'H', 'H', 'H', 'C', 'C', 'C', 'C', 'C', 'C', 'H', 'H', 'O', 'O', 'C', 'H', 'H', 'H', 'C', 'H', 'H', 'H', 'O', 'C', 'H', 'H', 'H', 'O', 'C', 'H', 'H', 'H', 'C', 'H', 'H', 'H', 'C', 'H', 'H', 'H']
Ligand atom label:  1  Ligand atom B nbo:  1.16454
Ligand atom label:  2  Ligand atom A nbo:  -1.02089
Atom_a:  1 Atom_b:  2
C:\Users\George\Desktop\Research_UCLA\CIC\Computational Work\Project cluster version 2\project_catalyst_repurposing\structures_ligand_id\pd_me2_structures\ligand_xyz\ligand-463-p-o-160-ligand_xyz.txt
Starting node: 0
Ending node: 1
(0.287329, -0.207951, 0.218656)   0
(-1.467008, 0.181986, 0.330017)   3
(-1.854325, 1.648534, -0.456521)   2
(-1.542204, 1.648862, -1.93773)   1
ligand-464-p-o-161

C:\Users\George\AppData\Local\Temp\ipykernel_7832\386804788.py:583: DeprecationWarning:

to_plotly_figure is deprecated and will be removed in version 4.0.0. Use MolGraph.to_plotly() instead.

C:\Users\George\AppData\Local\Temp\ipykernel_7832\386804788.py:589: DeprecationWarning:

to_networkx_graph is deprecated and will be removed in version 4.0.0. Use MolGraph.to_networkx() instead.

Pd number index:  54
['P', 'O', 'P', 'N', 'C', 'C', 'C', 'C', 'C', 'C', 'H', 'H', 'H', 'H', 'H', 'C', 'C', 'C', 'C', 'C', 'C', 'H', 'H', 'H', 'H', 'H', 'C', 'C', 'C', 'C', 'H', 'C', 'H', 'C', 'H', 'H', 'N', 'C', 'H', 'H', 'H', 'C', 'H', 'H', 'H', 'C', 'C', 'C', 'C', 'C', 'C', 'H', 'H', 'H', 'Pd', 'H', 'C', 'C', 'C', 'C', 'C', 'C', 'H', 'H', 'O', 'O', 'C', 'H', 'H', 'H', 'C', 'H', 'H', 'H', 'C', 'C', 'C', 'C', 'H', 'C', 'H', 'C', 'H', 'H', 'H', 'H', 'C', 'H', 'H', 'H', 'C', 'H', 'H', 'H']
Ligand atom label:  1  Ligand atom B nbo:  1.20304
Ligand atom label:  2  Ligand atom A nbo:  -1.01449
Atom_a:  1 Atom_b:  2
C:\Users\George\Desktop\Research_UCLA\CIC\Computational Work\Project cluster version 2\project_catalyst_repurposing\structures_ligand_id\pd_me2_structures\ligand_xyz\ligand-464-p-o-161-ligand_xyz.txt
Starting node: 0
Ending node: 1
(0.80124, -0.037192, 1.06943)   0
(-0.529367, 0.630932, 0.116098)   3
(-0.063631, 1.133052, -1.455361)   2
(1.094286, 0.337627, -2.017167)   1
ligand-465-p-o-162

C:\Users\George\AppData\Local\Temp\ipykernel_7832\386804788.py:583: DeprecationWarning:

to_plotly_figure is deprecated and will be removed in version 4.0.0. Use MolGraph.to_plotly() instead.

C:\Users\George\AppData\Local\Temp\ipykernel_7832\386804788.py:589: DeprecationWarning:

to_networkx_graph is deprecated and will be removed in version 4.0.0. Use MolGraph.to_networkx() instead.

Pd number index:  54
['P', 'O', 'P', 'N', 'C', 'C', 'C', 'C', 'C', 'C', 'H', 'H', 'H', 'H', 'H', 'C', 'C', 'C', 'C', 'C', 'C', 'H', 'H', 'H', 'H', 'H', 'C', 'C', 'C', 'C', 'H', 'C', 'H', 'C', 'H', 'H', 'C', 'C', 'C', 'C', 'C', 'C', 'H', 'H', 'H', 'C', 'C', 'C', 'C', 'C', 'C', 'H', 'H', 'H', 'Pd', 'H', 'H', 'H', 'C', 'C', 'C', 'C', 'C', 'C', 'H', 'H', 'O', 'O', 'C', 'H', 'H', 'H', 'C', 'H', 'H', 'H', 'O', 'C', 'H', 'H', 'H', 'N', 'C', 'H', 'H', 'H', 'C', 'H', 'H', 'H', 'C', 'H', 'H', 'H', 'C', 'H', 'H', 'H']
Ligand atom label:  1  Ligand atom B nbo:  1.15571
Ligand atom label:  2  Ligand atom A nbo:  -1.01593
Atom_a:  1 Atom_b:  2
C:\Users\George\Desktop\Research_UCLA\CIC\Computational Work\Project cluster version 2\project_catalyst_repurposing\structures_ligand_id\pd_me2_structures\ligand_xyz\ligand-465-p-o-162-ligand_xyz.txt
Starting node: 0
Ending node: 1
(0.381742, -0.179585, 0.204369)   0
(-1.316753, 0.401178, 0.305133)   3
(-1.52438, 1.915418, -0.453594)   2
(-1.203212, 1.912004, -1.933115)   1
ligand-466-p-o-163
Pd number index:  73
['P', 'O', 'P', 'N', 'C', 'C', 'C', 'C', 'C', 'C', 'H', 'H', 'H', 'H', 'H', 'C', 'C', 'C', 'C', 'C', 'C', 'H', 'H', 'H', 'H', 'H', 'C', 'C', 'C', 'C', 'H', 'C', 'H', 'C', 'H', 'H', 'N', 'C', 'H', 'H', 'H', 'C', 'H', 'H', 'H', 'C', 'C', 'C', 'C', 'C', 'C', 'H', 'H', 'C', 'H', 'H', 'H', 'O', 'H', 'C', 'C', 'C', 'C', 'C', 'C', 'H', 'H', 'H', 'C', 'H', 'H', 'H', 'O', 'Pd', 'H', 'H', 'C', 'H', 'H', 'H', 'C', 'H', 'H', 'H']

C:\Users\George\AppData\Local\Temp\ipykernel_7832\386804788.py:583: DeprecationWarning:

to_plotly_figure is deprecated and will be removed in version 4.0.0. Use MolGraph.to_plotly() instead.

C:\Users\George\AppData\Local\Temp\ipykernel_7832\386804788.py:589: DeprecationWarning:

to_networkx_graph is deprecated and will be removed in version 4.0.0. Use MolGraph.to_networkx() instead.

Ligand atom label:  1  Ligand atom B nbo:  1.1819
Ligand atom label:  2  Ligand atom A nbo:  -1.01029
Atom_a:  1 Atom_b:  2
C:\Users\George\Desktop\Research_UCLA\CIC\Computational Work\Project cluster version 2\project_catalyst_repurposing\structures_ligand_id\pd_me2_structures\ligand_xyz\ligand-466-p-o-163-ligand_xyz.txt

C:\Users\George\AppData\Local\Temp\ipykernel_7832\386804788.py:583: DeprecationWarning:

to_plotly_figure is deprecated and will be removed in version 4.0.0. Use MolGraph.to_plotly() instead.

C:\Users\George\AppData\Local\Temp\ipykernel_7832\386804788.py:589: DeprecationWarning:

to_networkx_graph is deprecated and will be removed in version 4.0.0. Use MolGraph.to_networkx() instead.

Starting node: 0
Ending node: 1
(-0.888609, 1.052417, 0.303973)   0
(0.368071, -0.130205, -0.050775)   3
(-0.20281, -1.392692, -1.049091)   2
(-1.114935, -0.951452, -2.173404)   1
ligand-467-p-o-164
Pd number index:  64
['P', 'O', 'P', 'N', 'C', 'C', 'C', 'C', 'C', 'C', 'H', 'H', 'H', 'H', 'H', 'C', 'C', 'C', 'C', 'C', 'C', 'H', 'H', 'H', 'H', 'H', 'C', 'C', 'C', 'C', 'H', 'C', 'H', 'C', 'H', 'H', 'C', 'C', 'C', 'C', 'C', 'C', 'H', 'H', 'C', 'H', 'H', 'H', 'O', 'H', 'C', 'C', 'C', 'C', 'C', 'C', 'H', 'H', 'H', 'C', 'H', 'H', 'H', 'O', 'Pd', 'C', 'H', 'H', 'H', 'O', 'C', 'H', 'H', 'H', 'O', 'C', 'H', 'H', 'H', 'N', 'C', 'H', 'H', 'H', 'C', 'H', 'H', 'H', 'C', 'H', 'H', 'H']
Ligand atom label:  1  Ligand atom B nbo:  1.20905
Ligand atom label:  2  Ligand atom A nbo:  -1.00544
Atom_a:  1 Atom_b:  2
C:\Users\George\Desktop\Research_UCLA\CIC\Computational Work\Project cluster version 2\project_catalyst_repurposing\structures_ligand_id\pd_me2_structures\ligand_xyz\ligand-467-p-o-164-ligand_xyz.txt
Starting node: 0
Ending node: 1
(1.204259, -0.450191, -0.125305)   0
(-0.307936, 0.454942, -0.188687)   3
(-0.167176, 2.136919, -0.373923)   2
(1.243346, 2.509904, -0.760507)   1
ligand-468-p-o-165
Pd number index:  28
['P', 'C', 'C', 'C', 'C', 'C', 'C', 'C', 'C', 'H', 'H', 'C', 'C', 'C', 'C', 'C', 'H', 'H', 'H', 'H', 'C', 'C', 'C', 'C', 'C', 'H', 'H', 'H', 'Pd', 'H', 'O', 'H', 'H', 'C', 'H', 'H', 'H', 'C', 'H', 'H', 'H', 'C', 'C', 'C', 'C', 'C', 'C', 'H', 'H', 'H', 'O', 'O', 'C', 'H', 'H', 'H', 'C', 'H', 'H', 'H', 'C', 'C', 'C', 'C', 'C', 'C', 'F', 'F', 'F', 'F', 'F']

C:\Users\George\AppData\Local\Temp\ipykernel_7832\386804788.py:583: DeprecationWarning:

to_plotly_figure is deprecated and will be removed in version 4.0.0. Use MolGraph.to_plotly() instead.

C:\Users\George\AppData\Local\Temp\ipykernel_7832\386804788.py:589: DeprecationWarning:

to_networkx_graph is deprecated and will be removed in version 4.0.0. Use MolGraph.to_networkx() instead.

Ligand atom label:  1  Ligand atom B nbo:  1.01414
Ligand atom label:  31  Ligand atom A nbo:  -0.69464
Atom_a:  1 Atom_b:  31
C:\Users\George\Desktop\Research_UCLA\CIC\Computational Work\Project cluster version 2\project_catalyst_repurposing\structures_ligand_id\pd_me2_structures\ligand_xyz\ligand-468-p-o-165-ligand_xyz.txt
Starting node: 0
Ending node: 29
(1.956423, 0.389984, -0.347008)   0
(0.542075, 0.00805, -1.426878)   1
(-0.743193, 0.34128, -0.866986)   2
(-0.905783, 0.850158, 0.281161)   29

C:\Users\George\AppData\Local\Temp\ipykernel_7832\386804788.py:583: DeprecationWarning:

to_plotly_figure is deprecated and will be removed in version 4.0.0. Use MolGraph.to_plotly() instead.

C:\Users\George\AppData\Local\Temp\ipykernel_7832\386804788.py:589: DeprecationWarning:

to_networkx_graph is deprecated and will be removed in version 4.0.0. Use MolGraph.to_networkx() instead.

ligand-469-p-o-166
Pd number index:  28
['P', 'C', 'C', 'C', 'C', 'C', 'C', 'C', 'C', 'H', 'H', 'C', 'C', 'C', 'C', 'C', 'H', 'H', 'H', 'H', 'C', 'C', 'C', 'C', 'C', 'H', 'H', 'H', 'Pd', 'H', 'O', 'H', 'H', 'C', 'H', 'H', 'H', 'C', 'H', 'H', 'H', 'C', 'C', 'C', 'C', 'C', 'C', 'H', 'H', 'H', 'O', 'O', 'C', 'H', 'H', 'H', 'C', 'H', 'H', 'H', 'C', 'C', 'C', 'C', 'C', 'C', 'H', 'H', 'H', 'C', 'C', 'C', 'C', 'C', 'C', 'C', 'C', 'C', 'C', 'C', 'C', 'F', 'F', 'F', 'F', 'F', 'F', 'F', 'F', 'F', 'F', 'F', 'F', 'F', 'F', 'F', 'F', 'F', 'F', 'F', 'F', 'F', 'F', 'F', 'F', 'F', 'F']
Ligand atom label:  1  Ligand atom B nbo:  1.01294
Ligand atom label:  31  Ligand atom A nbo:  -0.69657
Atom_a:  1 Atom_b:  31
C:\Users\George\Desktop\Research_UCLA\CIC\Computational Work\Project cluster version 2\project_catalyst_repurposing\structures_ligand_id\pd_me2_structures\ligand_xyz\ligand-469-p-o-166-ligand_xyz.txt
Starting node: 0
Ending node: 29
(-5.199435, 0.982373, -0.933586)   0
(-3.525053, 1.63854, -1.22883)   1
(-2.466096, 0.922273, -0.558579)   2
(-2.681273, -0.113083, 0.141228)   29
ligand-471-p-o-168
Pd number index:  9
['P', 'C', 'C', 'C', 'C', 'C', 'C', 'H', 'H', 'Pd', 'O', 'C', 'C', 'H', 'H', 'H', 'C', 'H', 'H', 'H', 'C', 'H', 'H', 'H', 'H', 'C', 'H', 'H', 'H', 'C', 'H', 'H', 'H', 'C', 'C', 'C', 'H', 'C', 'H', 'H', 'C', 'H', 'H', 'C', 'H', 'H', 'H', 'H', 'H', 'H', 'C', 'C', 'C', 'H', 'C', 'H', 'H', 'C', 'H', 'H', 'C', 'H', 'H', 'H', 'H', 'H', 'H']
Ligand atom label:  1  Ligand atom B nbo:  1.02244
Ligand atom label:  11  Ligand atom A nbo:  -0.70788
Atom_a:  1 Atom_b:  11

C:\Users\George\AppData\Local\Temp\ipykernel_7832\386804788.py:583: DeprecationWarning:

to_plotly_figure is deprecated and will be removed in version 4.0.0. Use MolGraph.to_plotly() instead.

C:\Users\George\AppData\Local\Temp\ipykernel_7832\386804788.py:589: DeprecationWarning:

to_networkx_graph is deprecated and will be removed in version 4.0.0. Use MolGraph.to_networkx() instead.

C:\Users\George\Desktop\Research_UCLA\CIC\Computational Work\Project cluster version 2\project_catalyst_repurposing\structures_ligand_id\pd_me2_structures\ligand_xyz\ligand-471-p-o-168-ligand_xyz.txt
Starting node: 0
Ending node: 9
(0.697453, -0.038143, 0.112658)   0
(-0.716257, -1.183569, 0.243196)   1
(-2.00204, -0.540439, 0.16097)   2
(-2.122983, 0.725825, 0.035417)   9
ligand-472-p-o-169
Pd number index:  25
['P', 'C', 'C', 'C', 'C', 'C', 'C', 'H', 'C', 'C', 'C', 'C', 'C', 'H', 'H', 'H', 'H', 'C', 'C', 'C', 'C', 'C', 'H', 'H', 'H', 'Pd', 'H', 'O', 'H', 'H', 'C', 'H', 'H', 'H', 'C', 'H', 'H', 'H', 'C', 'C', 'C', 'C', 'C', 'C', 'H', 'H', 'H', 'O', 'O', 'C', 'H', 'H', 'H', 'C', 'H', 'H', 'H', 'C', 'C', 'C', 'C', 'C', 'H', 'C', 'H', 'H', 'H']
Ligand atom label:  1  Ligand atom B nbo:  1.0122
Ligand atom label:  28  Ligand atom A nbo:  -0.69581
Atom_a:  1 Atom_b:  28

C:\Users\George\AppData\Local\Temp\ipykernel_7832\386804788.py:583: DeprecationWarning:

to_plotly_figure is deprecated and will be removed in version 4.0.0. Use MolGraph.to_plotly() instead.

C:\Users\George\AppData\Local\Temp\ipykernel_7832\386804788.py:589: DeprecationWarning:

to_networkx_graph is deprecated and will be removed in version 4.0.0. Use MolGraph.to_networkx() instead.

C:\Users\George\Desktop\Research_UCLA\CIC\Computational Work\Project cluster version 2\project_catalyst_repurposing\structures_ligand_id\pd_me2_structures\ligand_xyz\ligand-472-p-o-169-ligand_xyz.txt
Starting node: 0
Ending node: 26
(1.055794, -0.581161, 0.05422)   0
(-0.610509, -1.28336, 0.041327)   1
(-1.488174, -0.721763, -0.934258)   2
(-1.152336, 0.153562, -1.784118)   26
ligand-473-p-o-170
Pd number index:  15
['P', 'C', 'C', 'S', 'O', 'O', 'O', 'C', 'C', 'C', 'C', 'H', 'H', 'H', 'H', 'Pd', 'C', 'H', 'H', 'H', 'C', 'H', 'H', 'H', 'C', 'C', 'C', 'H', 'C', 'H', 'H', 'C', 'H', 'H', 'C', 'H', 'H', 'H', 'H', 'H', 'H', 'C', 'C', 'C', 'C', 'H', 'C', 'H', 'C', 'H', 'H', 'H']
Ligand atom label:  1  Ligand atom B nbo:  0.97595
Ligand atom label:  5  Ligand atom A nbo:  -0.9382
Atom_a:  1 Atom_b:  5

C:\Users\George\AppData\Local\Temp\ipykernel_7832\386804788.py:583: DeprecationWarning:

to_plotly_figure is deprecated and will be removed in version 4.0.0. Use MolGraph.to_plotly() instead.

C:\Users\George\AppData\Local\Temp\ipykernel_7832\386804788.py:589: DeprecationWarning:

to_networkx_graph is deprecated and will be removed in version 4.0.0. Use MolGraph.to_networkx() instead.

C:\Users\George\Desktop\Research_UCLA\CIC\Computational Work\Project cluster version 2\project_catalyst_repurposing\structures_ligand_id\pd_me2_structures\ligand_xyz\ligand-473-p-o-170-ligand_xyz.txt
Starting node: 0
Ending node: 4
(0.443093, -0.058836, -0.088291)   0
(-0.357933, 1.195325, -1.199589)   1
(-1.743337, 1.443596, -1.120337)   2
(-2.82874, 0.654325, 0.10909)   3
(-2.727834, -0.811829, -0.1868)   4
ligand-474-p-c-32

C:\Users\George\AppData\Local\Temp\ipykernel_7832\386804788.py:583: DeprecationWarning:

to_plotly_figure is deprecated and will be removed in version 4.0.0. Use MolGraph.to_plotly() instead.

C:\Users\George\AppData\Local\Temp\ipykernel_7832\386804788.py:589: DeprecationWarning:

to_networkx_graph is deprecated and will be removed in version 4.0.0. Use MolGraph.to_networkx() instead.

Pd number index:  21
['C', 'H', 'H', 'H', 'C', 'H', 'H', 'H', 'P', 'C', 'C', 'C', 'C', 'H', 'C', 'C', 'H', 'H', 'H', 'C', 'H', 'Pd', 'C', 'N', 'N', 'C', 'C', 'C', 'C', 'C', 'C', 'H', 'H', 'H', 'C', 'H', 'H', 'H', 'C', 'H', 'H', 'H', 'H', 'C', 'C', 'C', 'H', 'C', 'C', 'H', 'H', 'C', 'C', 'C', 'C', 'H', 'C', 'H', 'C', 'H', 'H', 'H', 'C', 'H', 'C', 'H', 'C', 'H', 'H', 'H', 'C', 'H', 'H', 'H']
Ligand atom label:  9  Ligand atom B nbo:  1.11907
Ligand atom label:  23  Ligand atom A nbo:  0.53576
Atom_a:  9 Atom_b:  23
C:\Users\George\Desktop\Research_UCLA\CIC\Computational Work\Project cluster version 2\project_catalyst_repurposing\structures_ligand_id\pd_me2_structures\ligand_xyz\ligand-474-p-c-32-ligand_xyz.txt
Starting node: 0
Ending node: 13
(2.024323, -0.259029, -0.164753)   0
(1.434304, -0.733686, 1.510486)   38
(0.048431, -0.667091, 1.578521)   14
(-0.78201, -0.445126, 0.504054)   13
ligand-475-p-c-33

C:\Users\George\AppData\Local\Temp\ipykernel_7832\386804788.py:583: DeprecationWarning:

to_plotly_figure is deprecated and will be removed in version 4.0.0. Use MolGraph.to_plotly() instead.

C:\Users\George\AppData\Local\Temp\ipykernel_7832\386804788.py:589: DeprecationWarning:

to_networkx_graph is deprecated and will be removed in version 4.0.0. Use MolGraph.to_networkx() instead.

Pd number index:  21
['C', 'H', 'H', 'H', 'C', 'H', 'H', 'H', 'P', 'C', 'C', 'C', 'C', 'H', 'C', 'C', 'H', 'H', 'H', 'C', 'H', 'Pd', 'C', 'N', 'N', 'C', 'C', 'C', 'C', 'C', 'C', 'H', 'H', 'H', 'C', 'C', 'C', 'H', 'C', 'C', 'H', 'H', 'C', 'C', 'C', 'C', 'H', 'C', 'H', 'C', 'H', 'H', 'H', 'C', 'H', 'C', 'H', 'C', 'H', 'H', 'H', 'C', 'C', 'C', 'C', 'H', 'C', 'H', 'C', 'H', 'H', 'H', 'C', 'C', 'C', 'C', 'H', 'C', 'H', 'C', 'H', 'H', 'H', 'C', 'C', 'C', 'C', 'H', 'C', 'H', 'C', 'H', 'H', 'H', 'C', 'C', 'C', 'C', 'H', 'C', 'H', 'C', 'H', 'H', 'H']
Ligand atom label:  9  Ligand atom B nbo:  1.1165
Ligand atom label:  23  Ligand atom A nbo:  0.52338
Atom_a:  9 Atom_b:  23
C:\Users\George\Desktop\Research_UCLA\CIC\Computational Work\Project cluster version 2\project_catalyst_repurposing\structures_ligand_id\pd_me2_structures\ligand_xyz\ligand-475-p-c-33-ligand_xyz.txt
Starting node: 0
Ending node: 13
(2.83259, -0.984337, -0.324869)   0
(2.110944, -1.359077, 1.329832)   29
(0.803031, -0.901028, 1.418659)   14
(0.068333, -0.396629, 0.375379)   13
ligand-476-p-p-31

C:\Users\George\AppData\Local\Temp\ipykernel_7832\386804788.py:583: DeprecationWarning:

to_plotly_figure is deprecated and will be removed in version 4.0.0. Use MolGraph.to_plotly() instead.

C:\Users\George\AppData\Local\Temp\ipykernel_7832\386804788.py:589: DeprecationWarning:

to_networkx_graph is deprecated and will be removed in version 4.0.0. Use MolGraph.to_networkx() instead.

Pd number index:  18
['Fe', 'C', 'C', 'C', 'H', 'C', 'C', 'H', 'H', 'C', 'C', 'C', 'C', 'H', 'C', 'H', 'H', 'P', 'Pd', 'P', 'C', 'H', 'H', 'H', 'C', 'H', 'H', 'H', 'H', 'H', 'C', 'C', 'H', 'H', 'H', 'C', 'H', 'H', 'H', 'C', 'H', 'H', 'H', 'C', 'C', 'H', 'H', 'H', 'C', 'H', 'H', 'H', 'C', 'H', 'H', 'H', 'C', 'C', 'H', 'H', 'H', 'C', 'H', 'H', 'H', 'C', 'H', 'H', 'H', 'C', 'C', 'H', 'H', 'H', 'C', 'H', 'H', 'H', 'C', 'H', 'H', 'H']
Ligand atom label:  18  Ligand atom B nbo:  1.08588
Ligand atom label:  20  Ligand atom A nbo:  1.06744
Atom_a:  18 Atom_b:  20
C:\Users\George\Desktop\Research_UCLA\CIC\Computational Work\Project cluster version 2\project_catalyst_repurposing\structures_ligand_id\pd_me2_structures\ligand_xyz\ligand-476-p-p-31-ligand_xyz.txt
Starting node: 17
Ending node: 18
(1.996536, -0.365606, -0.048537)   17
(1.661112, 1.401277, 0.360081)   5
(2.1e-05, 2.517535, -1.5e-05)   0
(-1.66121, 1.401393, -0.359988)   9
(-1.996407, -0.365599, 0.048536)   18
ligand-477-p-p-32

C:\Users\George\AppData\Local\Temp\ipykernel_7832\386804788.py:583: DeprecationWarning:

to_plotly_figure is deprecated and will be removed in version 4.0.0. Use MolGraph.to_plotly() instead.

C:\Users\George\AppData\Local\Temp\ipykernel_7832\386804788.py:589: DeprecationWarning:

to_networkx_graph is deprecated and will be removed in version 4.0.0. Use MolGraph.to_networkx() instead.

Pd number index:  18
['Fe', 'C', 'C', 'C', 'H', 'C', 'C', 'H', 'H', 'C', 'C', 'C', 'C', 'H', 'C', 'H', 'H', 'P', 'Pd', 'P', 'C', 'H', 'H', 'H', 'C', 'H', 'H', 'H', 'H', 'H', 'C', 'C', 'C', 'H', 'C', 'H', 'H', 'C', 'H', 'H', 'C', 'H', 'H', 'H', 'H', 'H', 'H', 'C', 'C', 'C', 'H', 'C', 'H', 'H', 'C', 'H', 'H', 'C', 'H', 'H', 'H', 'H', 'H', 'H', 'C', 'C', 'C', 'H', 'C', 'H', 'H', 'C', 'H', 'H', 'C', 'H', 'H', 'H', 'H', 'H', 'H', 'C', 'C', 'C', 'H', 'C', 'H', 'H', 'C', 'H', 'H', 'C', 'H', 'H', 'H', 'H', 'H', 'H']
Ligand atom label:  18  Ligand atom A nbo:  1.09009
Ligand atom label:  20  Ligand atom B nbo:  1.07056
Atom_a:  18 Atom_b:  20
C:\Users\George\Desktop\Research_UCLA\CIC\Computational Work\Project cluster version 2\project_catalyst_repurposing\structures_ligand_id\pd_me2_structures\ligand_xyz\ligand-477-p-p-32-ligand_xyz.txt
Starting node: 17
Ending node: 18
(1.82256, 0.014022, -0.253016)   17
(1.625698, 0.997983, 1.274056)   5
(-0.03041, 2.00283, 1.953552)   0
(-1.686903, 1.374741, 0.952597)   9
(-1.814823, 0.044542, -0.288961)   18
ligand-478-p-p-33

C:\Users\George\AppData\Local\Temp\ipykernel_7832\386804788.py:583: DeprecationWarning:

to_plotly_figure is deprecated and will be removed in version 4.0.0. Use MolGraph.to_plotly() instead.

C:\Users\George\AppData\Local\Temp\ipykernel_7832\386804788.py:589: DeprecationWarning:

to_networkx_graph is deprecated and will be removed in version 4.0.0. Use MolGraph.to_networkx() instead.

Pd number index:  38
['Fe', 'C', 'C', 'C', 'H', 'C', 'C', 'H', 'H', 'C', 'C', 'C', 'C', 'H', 'C', 'H', 'H', 'P', 'C', 'C', 'C', 'C', 'H', 'C', 'C', 'H', 'H', 'H', 'C', 'C', 'C', 'C', 'H', 'C', 'C', 'H', 'H', 'H', 'Pd', 'P', 'H', 'H', 'C', 'C', 'C', 'C', 'H', 'C', 'H', 'C', 'H', 'H', 'H', 'C', 'C', 'C', 'C', 'H', 'C', 'H', 'C', 'H', 'H', 'H', 'C', 'H', 'H', 'H', 'C', 'H', 'H', 'H', 'H', 'H']
Ligand atom label:  18  Ligand atom B nbo:  1.06591
Ligand atom label:  40  Ligand atom A nbo:  1.06581
Atom_a:  18 Atom_b:  40
C:\Users\George\Desktop\Research_UCLA\CIC\Computational Work\Project cluster version 2\project_catalyst_repurposing\structures_ligand_id\pd_me2_structures\ligand_xyz\ligand-478-p-p-33-ligand_xyz.txt
Starting node: 17
Ending node: 38
(-1.726065, 0.153768, -0.305701)   17
(-1.553092, -0.641539, 1.339925)   5
(0.005287, -1.845944, 1.846941)   0
(1.627267, -1.465047, 0.712202)   9
(1.867592, 0.030181, -0.298002)   38
ligand-479-p-p-34

C:\Users\George\AppData\Local\Temp\ipykernel_7832\386804788.py:583: DeprecationWarning:

to_plotly_figure is deprecated and will be removed in version 4.0.0. Use MolGraph.to_plotly() instead.

C:\Users\George\AppData\Local\Temp\ipykernel_7832\386804788.py:589: DeprecationWarning:

to_networkx_graph is deprecated and will be removed in version 4.0.0. Use MolGraph.to_networkx() instead.

Pd number index:  0
['Pd', 'P', 'C', 'C', 'C', 'C', 'H', 'C', 'H', 'C', 'H', 'H', 'H', 'C', 'C', 'C', 'C', 'H', 'C', 'H', 'C', 'H', 'H', 'H', 'C', 'C', 'C', 'C', 'H', 'H', 'C', 'C', 'C', 'C', 'H', 'H', 'P', 'C', 'C', 'C', 'C', 'H', 'C', 'H', 'C', 'H', 'H', 'H', 'C', 'C', 'C', 'C', 'H', 'C', 'H', 'C', 'H', 'H', 'H', 'C', 'H', 'H', 'H', 'C', 'H', 'H', 'H', 'C', 'C', 'C', 'C', 'H', 'C', 'C', 'H', 'H', 'H', 'C', 'C', 'C', 'C', 'C', 'H', 'C', 'H', 'H', 'H']
Ligand atom label:  2  Ligand atom B nbo:  1.02045
Ligand atom label:  37  Ligand atom A nbo:  1.20602
Atom_a:  37 Atom_b:  2
C:\Users\George\Desktop\Research_UCLA\CIC\Computational Work\Project cluster version 2\project_catalyst_repurposing\structures_ligand_id\pd_me2_structures\ligand_xyz\ligand-479-p-p-34-ligand_xyz.txt
Ending node: 0
Starting node: 35
(-1.72211, -0.811198, -0.208223)   35
(-1.151361, 0.642677, -1.215118)   30
(-0.213489, 1.546646, -0.716445)   29
(0.212365, 1.547228, 0.715959)   24
(1.150636, 0.643928, 1.21504)   23
(1.721858, -0.809983, 0.208734)   0
ligand-480-p-p-35

C:\Users\George\AppData\Local\Temp\ipykernel_7832\386804788.py:583: DeprecationWarning:

to_plotly_figure is deprecated and will be removed in version 4.0.0. Use MolGraph.to_plotly() instead.

C:\Users\George\AppData\Local\Temp\ipykernel_7832\386804788.py:589: DeprecationWarning:

to_networkx_graph is deprecated and will be removed in version 4.0.0. Use MolGraph.to_networkx() instead.

Pd number index:  18
['Fe', 'C', 'C', 'C', 'H', 'C', 'C', 'H', 'H', 'C', 'C', 'C', 'C', 'H', 'C', 'H', 'H', 'P', 'Pd', 'P', 'C', 'H', 'H', 'H', 'C', 'H', 'H', 'H', 'H', 'H', 'C', 'C', 'H', 'H', 'H', 'C', 'H', 'H', 'H', 'C', 'C', 'H', 'H', 'H', 'C', 'H', 'H', 'H', 'C', 'C', 'H', 'H', 'H', 'C', 'H', 'H', 'H', 'C', 'C', 'H', 'H', 'H', 'C', 'H', 'H', 'H', 'H', 'H', 'H', 'H']
Ligand atom label:  18  Ligand atom A nbo:  1.07207
Ligand atom label:  20  Ligand atom B nbo:  1.15993
Atom_a:  20 Atom_b:  18
C:\Users\George\Desktop\Research_UCLA\CIC\Computational Work\Project cluster version 2\project_catalyst_repurposing\structures_ligand_id\pd_me2_structures\ligand_xyz\ligand-480-p-p-35-ligand_xyz.txt
Ending node: 17
Starting node: 18
(-1.492876, -1.177329, 0.080683)   18
(-2.103481, 0.517016, -0.263934)   9
(-1.12503, 2.270921, 0.067847)   0
(0.86696, 1.953861, 0.312)   5
(1.882945, 0.478117, -0.094589)   17
ligand-481-p-p-36

C:\Users\George\AppData\Local\Temp\ipykernel_7832\386804788.py:583: DeprecationWarning:

to_plotly_figure is deprecated and will be removed in version 4.0.0. Use MolGraph.to_plotly() instead.

C:\Users\George\AppData\Local\Temp\ipykernel_7832\386804788.py:589: DeprecationWarning:

to_networkx_graph is deprecated and will be removed in version 4.0.0. Use MolGraph.to_networkx() instead.

Pd number index:  74
['C', 'C', 'C', 'C', 'C', 'C', 'H', 'H', 'H', 'H', 'P', 'C', 'C', 'C', 'C', 'H', 'C', 'H', 'C', 'H', 'H', 'H', 'C', 'C', 'C', 'C', 'C', 'H', 'C', 'H', 'H', 'O', 'C', 'C', 'C', 'C', 'C', 'C', 'H', 'H', 'H', 'C', 'C', 'H', 'H', 'H', 'C', 'H', 'H', 'H', 'P', 'C', 'C', 'C', 'C', 'H', 'C', 'H', 'C', 'H', 'H', 'H', 'C', 'C', 'C', 'C', 'H', 'C', 'H', 'C', 'H', 'H', 'H', 'H', 'Pd', 'C', 'H', 'H', 'H', 'C', 'H', 'H', 'H']
Ligand atom label:  11  Ligand atom A nbo:  0.93772
Ligand atom label:  51  Ligand atom B nbo:  1.03958
Atom_a:  51 Atom_b:  11
C:\Users\George\Desktop\Research_UCLA\CIC\Computational Work\Project cluster version 2\project_catalyst_repurposing\structures_ligand_id\pd_me2_structures\ligand_xyz\ligand-481-p-p-36-ligand_xyz.txt
Ending node: 10
Starting node: 50
(1.955085, -0.413196, -0.28119)   50
(2.245954, 1.41328, -0.389604)   33
(1.143907, 2.252649, -0.218571)   32
(-0.028937, 1.648082, 0.128218)   31
(-1.172558, 2.188477, -0.383332)   23
(-2.20665, 1.294099, -0.662176)   22
(-1.894246, -0.493355, -0.303975)   10
ligand-482-p-p-37

C:\Users\George\AppData\Local\Temp\ipykernel_7832\386804788.py:583: DeprecationWarning:

to_plotly_figure is deprecated and will be removed in version 4.0.0. Use MolGraph.to_plotly() instead.

C:\Users\George\AppData\Local\Temp\ipykernel_7832\386804788.py:589: DeprecationWarning:

to_networkx_graph is deprecated and will be removed in version 4.0.0. Use MolGraph.to_networkx() instead.

Pd number index:  9
['P', 'C', 'C', 'C', 'C', 'C', 'C', 'H', 'H', 'Pd', 'H', 'C', 'H', 'H', 'H', 'C', 'H', 'H', 'H', 'H', 'P', 'C', 'C', 'C', 'C', 'H', 'C', 'H', 'C', 'H', 'H', 'H', 'C', 'C', 'C', 'C', 'H', 'C', 'H', 'C', 'H', 'H', 'H', 'C', 'C', 'C', 'C', 'H', 'C', 'H', 'C', 'H', 'H', 'H', 'C', 'C', 'C', 'C', 'H', 'C', 'H', 'C', 'H', 'H', 'H']
Ligand atom label:  1  Ligand atom A nbo:  1.03072
Ligand atom label:  21  Ligand atom B nbo:  1.03321
Atom_a:  21 Atom_b:  1
C:\Users\George\Desktop\Research_UCLA\CIC\Computational Work\Project cluster version 2\project_catalyst_repurposing\structures_ligand_id\pd_me2_structures\ligand_xyz\ligand-482-p-p-37-ligand_xyz.txt
Ending node: 0
Starting node: 11
(1.561294, -0.222895, -0.047053)   11
(0.758718, -0.565222, 1.584696)   2
(-0.650634, -0.559859, 1.611563)   1
(-1.526529, -0.2837, 0.00756)   0
ligand-483-p-p-38

C:\Users\George\AppData\Local\Temp\ipykernel_7832\386804788.py:583: DeprecationWarning:

to_plotly_figure is deprecated and will be removed in version 4.0.0. Use MolGraph.to_plotly() instead.

C:\Users\George\AppData\Local\Temp\ipykernel_7832\386804788.py:589: DeprecationWarning:

to_networkx_graph is deprecated and will be removed in version 4.0.0. Use MolGraph.to_networkx() instead.

Pd number index:  65
['C', 'C', 'C', 'C', 'C', 'C', 'H', 'H', 'H', 'H', 'P', 'C', 'C', 'C', 'C', 'H', 'C', 'H', 'C', 'H', 'H', 'H', 'C', 'C', 'C', 'C', 'C', 'H', 'C', 'H', 'H', 'O', 'C', 'C', 'C', 'C', 'C', 'C', 'H', 'H', 'H', 'P', 'C', 'C', 'C', 'C', 'H', 'C', 'H', 'C', 'H', 'H', 'H', 'C', 'C', 'C', 'C', 'H', 'C', 'H', 'C', 'H', 'H', 'H', 'H', 'Pd', 'C', 'H', 'H', 'H', 'C', 'H', 'H', 'H', 'N', 'H']
Ligand atom label:  11  Ligand atom A nbo:  0.93895
Ligand atom label:  42  Ligand atom B nbo:  1.04049
Atom_a:  42 Atom_b:  11
C:\Users\George\Desktop\Research_UCLA\CIC\Computational Work\Project cluster version 2\project_catalyst_repurposing\structures_ligand_id\pd_me2_structures\ligand_xyz\ligand-483-p-p-38-ligand_xyz.txt
Ending node: 10
Starting node: 41
(-1.967545, -0.14349, 0.257606)   41
(-2.27952, 1.672074, 0.05607)   33
(-1.168561, 2.464299, -0.194903)   32
(0.009087, 1.837026, -0.494008)   31
(1.141948, 2.454816, -0.040675)   23
(2.21577, 1.653942, 0.319836)   22
(1.921143, -0.173418, 0.291636)   10
ligand-484-p-p-39

C:\Users\George\AppData\Local\Temp\ipykernel_7832\386804788.py:583: DeprecationWarning:

to_plotly_figure is deprecated and will be removed in version 4.0.0. Use MolGraph.to_plotly() instead.

C:\Users\George\AppData\Local\Temp\ipykernel_7832\386804788.py:589: DeprecationWarning:

to_networkx_graph is deprecated and will be removed in version 4.0.0. Use MolGraph.to_networkx() instead.

Pd number index:  65
['C', 'C', 'C', 'C', 'C', 'C', 'H', 'H', 'H', 'H', 'P', 'C', 'C', 'C', 'C', 'H', 'C', 'H', 'C', 'H', 'H', 'H', 'C', 'C', 'C', 'C', 'C', 'H', 'C', 'H', 'H', 'O', 'C', 'C', 'C', 'C', 'C', 'C', 'H', 'H', 'H', 'P', 'C', 'C', 'C', 'C', 'H', 'C', 'H', 'C', 'H', 'H', 'H', 'C', 'C', 'C', 'C', 'H', 'C', 'H', 'C', 'H', 'H', 'H', 'H', 'Pd', 'C', 'H', 'H', 'H', 'C', 'H', 'H', 'H', 'H', 'H']
Ligand atom label:  11  Ligand atom B nbo:  1.02823
Ligand atom label:  42  Ligand atom A nbo:  0.9755
Atom_a:  11 Atom_b:  42
C:\Users\George\Desktop\Research_UCLA\CIC\Computational Work\Project cluster version 2\project_catalyst_repurposing\structures_ligand_id\pd_me2_structures\ligand_xyz\ligand-484-p-p-39-ligand_xyz.txt
Starting node: 10
Ending node: 41
(1.845449, 0.085604, -0.218089)   10
(2.199606, -1.672443, 0.265405)   22
(1.137882, -2.535997, 0.575273)   23
(-0.142404, -2.051628, 0.588342)   31
(-0.634268, -1.450556, 1.715885)   32
(-1.582591, -0.442259, 1.495699)   33
(-1.875039, 0.033306, -0.258685)   41
ligand-486-p-p-41

C:\Users\George\AppData\Local\Temp\ipykernel_7832\386804788.py:583: DeprecationWarning:

to_plotly_figure is deprecated and will be removed in version 4.0.0. Use MolGraph.to_plotly() instead.

C:\Users\George\AppData\Local\Temp\ipykernel_7832\386804788.py:589: DeprecationWarning:

to_networkx_graph is deprecated and will be removed in version 4.0.0. Use MolGraph.to_networkx() instead.

Pd number index:  9
['P', 'C', 'C', 'C', 'C', 'C', 'C', 'H', 'H', 'Pd', 'H', 'C', 'H', 'H', 'H', 'C', 'H', 'H', 'H', 'H', 'P', 'C', 'C', 'H', 'H', 'H', 'C', 'H', 'H', 'H', 'C', 'H', 'H', 'H', 'C', 'H', 'C', 'H', 'H', 'H', 'C', 'C', 'H', 'H', 'H', 'C', 'H', 'H', 'H', 'C', 'H', 'H', 'H', 'C', 'H', 'H', 'H', 'C', 'H', 'H', 'H']
Ligand atom label:  1  Ligand atom A nbo:  1.03517
Ligand atom label:  21  Ligand atom B nbo:  1.34083
Atom_a:  21 Atom_b:  1
C:\Users\George\Desktop\Research_UCLA\CIC\Computational Work\Project cluster version 2\project_catalyst_repurposing\structures_ligand_id\pd_me2_structures\ligand_xyz\ligand-486-p-p-41-ligand_xyz.txt
Ending node: 0
Starting node: 11
(1.409582, -0.086269, 0.218915)   11
(0.694952, 1.619878, 0.048146)   2
(-0.631547, 1.743699, -0.419153)   1
(-1.685381, 0.219988, -0.571963)   0
ligand-487-p-p-42

C:\Users\George\AppData\Local\Temp\ipykernel_7832\386804788.py:583: DeprecationWarning:

to_plotly_figure is deprecated and will be removed in version 4.0.0. Use MolGraph.to_plotly() instead.

C:\Users\George\AppData\Local\Temp\ipykernel_7832\386804788.py:589: DeprecationWarning:

to_networkx_graph is deprecated and will be removed in version 4.0.0. Use MolGraph.to_networkx() instead.

Pd number index:  9
['P', 'C', 'C', 'C', 'C', 'C', 'C', 'H', 'H', 'Pd', 'H', 'C', 'H', 'H', 'H', 'C', 'H', 'H', 'H', 'H', 'P', 'C', 'C', 'H', 'H', 'H', 'C', 'H', 'H', 'H', 'C', 'H', 'H', 'H', 'C', 'H', 'H', 'H', 'C', 'C', 'H', 'H', 'H', 'C', 'H', 'H', 'H', 'C', 'H', 'H', 'H', 'C', 'C', 'C', 'H', 'C', 'H', 'H', 'C', 'H', 'H', 'C', 'H', 'H', 'H', 'H', 'H', 'H']
Ligand atom label:  1  Ligand atom A nbo:  1.03913
Ligand atom label:  21  Ligand atom B nbo:  1.34374
Atom_a:  21 Atom_b:  1
C:\Users\George\Desktop\Research_UCLA\CIC\Computational Work\Project cluster version 2\project_catalyst_repurposing\structures_ligand_id\pd_me2_structures\ligand_xyz\ligand-487-p-p-42-ligand_xyz.txt
Ending node: 0
Starting node: 11
(-1.011761, -0.057346, 0.567686)   11
(-0.289813, 1.644726, 0.383056)   2
(1.116136, 1.766646, 0.333004)   1
(2.155805, 0.236521, 0.153295)   0
ligand-488-p-n-34

C:\Users\George\AppData\Local\Temp\ipykernel_7832\386804788.py:583: DeprecationWarning:

to_plotly_figure is deprecated and will be removed in version 4.0.0. Use MolGraph.to_plotly() instead.

C:\Users\George\AppData\Local\Temp\ipykernel_7832\386804788.py:589: DeprecationWarning:

to_networkx_graph is deprecated and will be removed in version 4.0.0. Use MolGraph.to_networkx() instead.

Pd number index:  1
['P', 'Pd', 'C', 'H', 'H', 'H', 'C', 'H', 'H', 'H', 'C', 'H', 'H', 'C', 'C', 'C', 'H', 'H', 'H', 'O', 'N', 'C', 'C', 'C', 'C', 'H', 'C', 'H', 'C', 'H', 'H', 'H', 'C', 'C', 'C', 'C', 'H', 'C', 'H', 'C', 'H', 'H', 'H', 'C', 'H', 'C', 'H', 'H', 'H', 'C', 'H', 'H', 'H']
Ligand atom label:  1  Ligand atom B nbo:  1.07606
Ligand atom label:  21  Ligand atom A nbo:  -0.47637
Atom_a:  1 Atom_b:  21
C:\Users\George\Desktop\Research_UCLA\CIC\Computational Work\Project cluster version 2\project_catalyst_repurposing\structures_ligand_id\pd_me2_structures\ligand_xyz\ligand-488-p-n-34-ligand_xyz.txt
Starting node: 0
Ending node: 11
(1.013706, -0.163115, -0.156452)   0
(0.137493, 0.021094, -1.794032)   1
(-1.261116, 0.449273, -1.531897)   4
(-1.874569, 0.310446, -0.417698)   11
ligand-489-p-n-35

C:\Users\George\AppData\Local\Temp\ipykernel_7832\386804788.py:583: DeprecationWarning:

to_plotly_figure is deprecated and will be removed in version 4.0.0. Use MolGraph.to_plotly() instead.

C:\Users\George\AppData\Local\Temp\ipykernel_7832\386804788.py:589: DeprecationWarning:

to_networkx_graph is deprecated and will be removed in version 4.0.0. Use MolGraph.to_networkx() instead.

Pd number index:  1
['P', 'Pd', 'C', 'H', 'H', 'H', 'C', 'H', 'H', 'H', 'C', 'C', 'C', 'C', 'H', 'C', 'H', 'C', 'H', 'H', 'H', 'C', 'C', 'C', 'C', 'H', 'C', 'H', 'C', 'H', 'H', 'H', 'C', 'C', 'C', 'C', 'H', 'C', 'C', 'H', 'H', 'H', 'C', 'C', 'C', 'H', 'H', 'H', 'H', 'O', 'N']
Ligand atom label:  1  Ligand atom B nbo:  1.04046
Ligand atom label:  51  Ligand atom A nbo:  -0.55395
Atom_a:  1 Atom_b:  51
C:\Users\George\Desktop\Research_UCLA\CIC\Computational Work\Project cluster version 2\project_catalyst_repurposing\structures_ligand_id\pd_me2_structures\ligand_xyz\ligand-489-p-n-35-ligand_xyz.txt
Starting node: 0
Ending node: 41
(0.665209, -0.106261, 0.057272)   0
(0.243803, 1.186998, -1.203432)   23
(-1.10299, 1.555937, -1.433537)   25
(-2.238724, 0.930811, -0.734759)   33
(-2.307241, -0.248739, -0.241231)   41
ligand-490-p-n-36

C:\Users\George\AppData\Local\Temp\ipykernel_7832\386804788.py:583: DeprecationWarning:

to_plotly_figure is deprecated and will be removed in version 4.0.0. Use MolGraph.to_plotly() instead.

C:\Users\George\AppData\Local\Temp\ipykernel_7832\386804788.py:589: DeprecationWarning:

to_networkx_graph is deprecated and will be removed in version 4.0.0. Use MolGraph.to_networkx() instead.

Pd number index:  1
['P', 'Pd', 'C', 'H', 'H', 'H', 'C', 'H', 'H', 'H', 'C', 'C', 'C', 'H', 'C', 'H', 'H', 'C', 'C', 'C', 'C', 'H', 'C', 'H', 'C', 'H', 'H', 'H', 'C', 'C', 'C', 'C', 'H', 'C', 'C', 'H', 'H', 'H', 'C', 'C', 'C', 'H', 'H', 'H', 'H', 'O', 'N', 'C', 'C', 'C', 'C', 'C', 'H', 'C', 'H', 'H', 'H']
Ligand atom label:  1  Ligand atom B nbo:  1.00999
Ligand atom label:  47  Ligand atom A nbo:  -0.55418
Atom_a:  1 Atom_b:  47
C:\Users\George\Desktop\Research_UCLA\CIC\Computational Work\Project cluster version 2\project_catalyst_repurposing\structures_ligand_id\pd_me2_structures\ligand_xyz\ligand-490-p-n-36-ligand_xyz.txt
Starting node: 0
Ending node: 37
(-0.234803, -0.621434, -0.088087)   0
(1.065871, -1.553715, 0.846397)   19
(2.320241, -0.96535, 1.136436)   21
(2.690935, 0.394526, 0.709796)   29
(2.26265, 1.043343, -0.306797)   37
ligand-491-p-n-37
Pd number index:  1
['P', 'Pd', 'C', 'H', 'H', 'H', 'C', 'H', 'H', 'H', 'C', 'C', 'C', 'C', 'H', 'C', 'H', 'C', 'H', 'H', 'H', 'C', 'C', 'C', 'C', 'H', 'C', 'H', 'C', 'H', 'H', 'H', 'C', 'C', 'C', 'C', 'H', 'C', 'C', 'H', 'H', 'H', 'C', 'C', 'C', 'H', 'H', 'H', 'O', 'N', 'C', 'H', 'C', 'H', 'H', 'H', 'C', 'H', 'H', 'H']

C:\Users\George\AppData\Local\Temp\ipykernel_7832\386804788.py:583: DeprecationWarning:

to_plotly_figure is deprecated and will be removed in version 4.0.0. Use MolGraph.to_plotly() instead.

C:\Users\George\AppData\Local\Temp\ipykernel_7832\386804788.py:589: DeprecationWarning:

to_networkx_graph is deprecated and will be removed in version 4.0.0. Use MolGraph.to_networkx() instead.

Ligand atom label:  1  Ligand atom B nbo:  1.03929
Ligand atom label:  50  Ligand atom A nbo:  -0.55842
Atom_a:  1 Atom_b:  50
C:\Users\George\Desktop\Research_UCLA\CIC\Computational Work\Project cluster version 2\project_catalyst_repurposing\structures_ligand_id\pd_me2_structures\ligand_xyz\ligand-491-p-n-37-ligand_xyz.txt
Starting node: 0
Ending node: 40
(1.001855, -0.113042, 0.072281)   0
(0.923376, 1.407826, -0.983137)   23
(-0.314827, 1.909069, -1.451532)   25
(-1.615165, 1.299285, -1.11908)   33
(-1.866564, 0.088625, -0.784476)   40

C:\Users\George\AppData\Local\Temp\ipykernel_7832\386804788.py:583: DeprecationWarning:

to_plotly_figure is deprecated and will be removed in version 4.0.0. Use MolGraph.to_plotly() instead.

C:\Users\George\AppData\Local\Temp\ipykernel_7832\386804788.py:589: DeprecationWarning:

to_networkx_graph is deprecated and will be removed in version 4.0.0. Use MolGraph.to_networkx() instead.

ligand-492-p-n-38
Pd number index:  1
['P', 'Pd', 'C', 'H', 'H', 'H', 'C', 'H', 'H', 'H', 'C', 'C', 'C', 'C', 'H', 'C', 'H', 'C', 'H', 'H', 'H', 'C', 'C', 'C', 'C', 'H', 'C', 'H', 'C', 'H', 'H', 'H', 'C', 'C', 'C', 'C', 'H', 'C', 'C', 'H', 'H', 'H', 'C', 'C', 'C', 'H', 'H', 'O', 'N', 'C', 'C', 'H', 'H', 'H', 'C', 'H', 'H', 'H', 'C', 'H', 'H', 'H', 'H']
Ligand atom label:  1  Ligand atom B nbo:  1.03857
Ligand atom label:  49  Ligand atom A nbo:  -0.56244
Atom_a:  1 Atom_b:  49
C:\Users\George\Desktop\Research_UCLA\CIC\Computational Work\Project cluster version 2\project_catalyst_repurposing\structures_ligand_id\pd_me2_structures\ligand_xyz\ligand-492-p-n-38-ligand_xyz.txt
Starting node: 0
Ending node: 39
(1.094787, -0.081582, 0.097353)   0
(0.982527, 1.080091, -1.344241)   23
(-0.255979, 1.380189, -1.963346)   25
(-1.552617, 0.823432, -1.531164)   33
(-1.784496, -0.216511, -0.819119)   39
ligand-493-p-n-39
Pd number index:  1
['P', 'Pd', 'C', 'H', 'H', 'H', 'C', 'H', 'H', 'H', 'C', 'C', 'C', 'C', 'H', 'C', 'H', 'C', 'H', 'H', 'H', 'C', 'C', 'C', 'C', 'H', 'C', 'H', 'C', 'H', 'H', 'H', 'C', 'C', 'C', 'C', 'H', 'C', 'C', 'H', 'H', 'H', 'C', 'C', 'C', 'H', 'H', 'O', 'N', 'C', 'H', 'C', 'C', 'C', 'C', 'H', 'C', 'H', 'C', 'H', 'H', 'H', 'H', 'H']

C:\Users\George\AppData\Local\Temp\ipykernel_7832\386804788.py:583: DeprecationWarning:

to_plotly_figure is deprecated and will be removed in version 4.0.0. Use MolGraph.to_plotly() instead.

C:\Users\George\AppData\Local\Temp\ipykernel_7832\386804788.py:589: DeprecationWarning:

to_networkx_graph is deprecated and will be removed in version 4.0.0. Use MolGraph.to_networkx() instead.

Ligand atom label:  1  Ligand atom B nbo:  1.04034
Ligand atom label:  49  Ligand atom A nbo:  -0.55841
Atom_a:  1 Atom_b:  49
C:\Users\George\Desktop\Research_UCLA\CIC\Computational Work\Project cluster version 2\project_catalyst_repurposing\structures_ligand_id\pd_me2_structures\ligand_xyz\ligand-493-p-n-39-ligand_xyz.txt

C:\Users\George\AppData\Local\Temp\ipykernel_7832\386804788.py:583: DeprecationWarning:

to_plotly_figure is deprecated and will be removed in version 4.0.0. Use MolGraph.to_plotly() instead.

C:\Users\George\AppData\Local\Temp\ipykernel_7832\386804788.py:589: DeprecationWarning:

to_networkx_graph is deprecated and will be removed in version 4.0.0. Use MolGraph.to_networkx() instead.

Starting node: 0
Ending node: 39
(-1.64523, 0.184486, 0.095703)   0
(-1.901133, -1.432986, -0.768264)   23
(-0.810694, -2.116253, -1.355778)   25
(0.566683, -1.595471, -1.329924)   33
(0.946243, -0.371993, -1.315481)   39
ligand-494-p-n-40
Pd number index:  1
['P', 'Pd', 'C', 'H', 'H', 'H', 'C', 'H', 'H', 'H', 'C', 'C', 'C', 'C', 'H', 'C', 'H', 'C', 'C', 'C', 'C', 'C', 'H', 'C', 'H', 'C', 'C', 'C', 'C', 'C', 'H', 'C', 'C', 'H', 'H', 'H', 'C', 'C', 'C', 'H', 'H', 'O', 'N', 'C', 'H', 'C', 'C', 'C', 'C', 'H', 'C', 'H', 'C', 'H', 'H', 'H', 'H', 'H', 'C', 'H', 'H', 'H', 'C', 'H', 'H', 'H', 'C', 'H', 'H', 'H', 'C', 'H', 'H', 'H', 'O', 'O', 'C', 'H', 'H', 'H', 'C', 'H', 'H', 'H']
Ligand atom label:  1  Ligand atom B nbo:  1.0404
Ligand atom label:  43  Ligand atom A nbo:  -0.55916
Atom_a:  1 Atom_b:  43
C:\Users\George\Desktop\Research_UCLA\CIC\Computational Work\Project cluster version 2\project_catalyst_repurposing\structures_ligand_id\pd_me2_structures\ligand_xyz\ligand-494-p-n-40-ligand_xyz.txt
Starting node: 0
Ending node: 33
(-1.162211, -0.481687, 0.144376)   0
(-1.201611, -0.900599, 1.948264)   17
(-0.026956, -1.324799, 2.612249)   19
(1.268244, -1.460085, 1.924619)   27
(1.477296, -1.79709, 0.706817)   33
ligand-495-p-n-41

C:\Users\George\AppData\Local\Temp\ipykernel_7832\386804788.py:583: DeprecationWarning:

to_plotly_figure is deprecated and will be removed in version 4.0.0. Use MolGraph.to_plotly() instead.

C:\Users\George\AppData\Local\Temp\ipykernel_7832\386804788.py:589: DeprecationWarning:

to_networkx_graph is deprecated and will be removed in version 4.0.0. Use MolGraph.to_networkx() instead.

Pd number index:  1
['P', 'Pd', 'C', 'H', 'H', 'H', 'C', 'H', 'H', 'H', 'C', 'C', 'C', 'C', 'H', 'C', 'C', 'H', 'H', 'H', 'C', 'C', 'C', 'C', 'H', 'C', 'C', 'H', 'H', 'H', 'N', 'C', 'H', 'H', 'H', 'C', 'C', 'C', 'H', 'C', 'H', 'H', 'C', 'H', 'H', 'C', 'H', 'H', 'H', 'H', 'H', 'H', 'C', 'C', 'C', 'H', 'C', 'H', 'H', 'C', 'H', 'C', 'H', 'H', 'H', 'H', 'H', 'H', 'C', 'H', 'H', 'H', 'H']
Ligand atom label:  1  Ligand atom B nbo:  1.07634
Ligand atom label:  31  Ligand atom A nbo:  -0.6742
Atom_a:  1 Atom_b:  31
C:\Users\George\Desktop\Research_UCLA\CIC\Computational Work\Project cluster version 2\project_catalyst_repurposing\structures_ligand_id\pd_me2_structures\ligand_xyz\ligand-495-p-n-41-ligand_xyz.txt
Starting node: 0
Ending node: 21
(-0.723569, -0.33112, 0.001914)   0
(0.025761, -1.140191, -1.442069)   1
(1.477035, -1.148402, -1.646606)   3
(2.481567, -0.444441, -0.8439)   11
(2.539207, 0.943868, -0.455791)   13
(1.636536, 1.96189, -0.96036)   21
ligand-497-p-n-43

C:\Users\George\AppData\Local\Temp\ipykernel_7832\386804788.py:583: DeprecationWarning:

to_plotly_figure is deprecated and will be removed in version 4.0.0. Use MolGraph.to_plotly() instead.

C:\Users\George\AppData\Local\Temp\ipykernel_7832\386804788.py:589: DeprecationWarning:

to_networkx_graph is deprecated and will be removed in version 4.0.0. Use MolGraph.to_networkx() instead.

Pd number index:  1
['P', 'Pd', 'C', 'H', 'H', 'H', 'C', 'H', 'H', 'H', 'C', 'O', 'N', 'C', 'C', 'C', 'C', 'H', 'C', 'C', 'H', 'H', 'H', 'C', 'C', 'C', 'C', 'C', 'H', 'C', 'H', 'H', 'H', 'N', 'C', 'C', 'C', 'C', 'H', 'C', 'H', 'C', 'H', 'H', 'H', 'C', 'C', 'C', 'C', 'H', 'C', 'H', 'C', 'H', 'H', 'H', 'O', 'O', 'C', 'H', 'H', 'H', 'C', 'H', 'H', 'H']
Ligand atom label:  1  Ligand atom B nbo:  1.27262
Ligand atom label:  13  Ligand atom A nbo:  -0.59825
Atom_a:  1 Atom_b:  13
C:\Users\George\Desktop\Research_UCLA\CIC\Computational Work\Project cluster version 2\project_catalyst_repurposing\structures_ligand_id\pd_me2_structures\ligand_xyz\ligand-497-p-n-43-ligand_xyz.txt
Starting node: 0
Ending node: 3
(-0.519376, -0.486206, -0.004802)   0
(-0.424458, 1.119918, -0.662907)   24
(0.893265, 1.737745, -0.689777)   1
(1.833636, 0.987267, -0.092021)   3
ligand-498-p-n-44

C:\Users\George\AppData\Local\Temp\ipykernel_7832\386804788.py:583: DeprecationWarning:

to_plotly_figure is deprecated and will be removed in version 4.0.0. Use MolGraph.to_plotly() instead.

C:\Users\George\AppData\Local\Temp\ipykernel_7832\386804788.py:589: DeprecationWarning:

to_networkx_graph is deprecated and will be removed in version 4.0.0. Use MolGraph.to_networkx() instead.

Pd number index:  1
['P', 'Pd', 'C', 'H', 'H', 'H', 'C', 'H', 'H', 'H', 'C', 'O', 'N', 'C', 'C', 'C', 'C', 'H', 'C', 'C', 'H', 'H', 'H', 'C', 'C', 'C', 'C', 'C', 'H', 'C', 'H', 'H', 'H', 'N', 'C', 'C', 'C', 'C', 'H', 'C', 'H', 'C', 'H', 'H', 'H', 'C', 'C', 'C', 'C', 'C', 'C', 'H', 'H', 'H', 'O', 'O', 'C', 'H', 'H', 'H', 'C', 'H', 'H', 'H', 'C', 'H', 'C', 'H', 'H', 'H', 'C', 'H', 'H', 'H', 'C', 'H', 'C', 'H', 'H', 'H', 'C', 'H', 'H', 'H']
Ligand atom label:  1  Ligand atom B nbo:  1.24867
Ligand atom label:  13  Ligand atom A nbo:  -0.61816
Atom_a:  1 Atom_b:  13
C:\Users\George\Desktop\Research_UCLA\CIC\Computational Work\Project cluster version 2\project_catalyst_repurposing\structures_ligand_id\pd_me2_structures\ligand_xyz\ligand-498-p-n-44-ligand_xyz.txt
Starting node: 0
Ending node: 3
(-1.126437, 0.144375, -0.155994)   0
(-0.513851, -0.588911, 1.288385)   24
(0.936226, -0.601286, 1.437122)   1
(1.596226, -0.326343, 0.312108)   3
ligand-499-p-n-45

C:\Users\George\AppData\Local\Temp\ipykernel_7832\386804788.py:583: DeprecationWarning:

to_plotly_figure is deprecated and will be removed in version 4.0.0. Use MolGraph.to_plotly() instead.

C:\Users\George\AppData\Local\Temp\ipykernel_7832\386804788.py:589: DeprecationWarning:

to_networkx_graph is deprecated and will be removed in version 4.0.0. Use MolGraph.to_networkx() instead.

Pd number index:  1
['P', 'Pd', 'C', 'H', 'H', 'H', 'C', 'H', 'H', 'H', 'C', 'O', 'N', 'C', 'C', 'C', 'C', 'C', 'C', 'H', 'H', 'H', 'C', 'C', 'C', 'C', 'C', 'C', 'H', 'H', 'H', 'N', 'C', 'C', 'C', 'C', 'H', 'C', 'H', 'C', 'H', 'H', 'H', 'C', 'C', 'C', 'C', 'H', 'C', 'H', 'C', 'H', 'H', 'H', 'O', 'O', 'C', 'H', 'H', 'H', 'C', 'H', 'H', 'H', 'O', 'O', 'C', 'H', 'H', 'H', 'C', 'H', 'H', 'H']
Ligand atom label:  1  Ligand atom B nbo:  1.28696
Ligand atom label:  13  Ligand atom A nbo:  -0.61727
Atom_a:  1 Atom_b:  13
C:\Users\George\Desktop\Research_UCLA\CIC\Computational Work\Project cluster version 2\project_catalyst_repurposing\structures_ligand_id\pd_me2_structures\ligand_xyz\ligand-499-p-n-45-ligand_xyz.txt
Starting node: 0
Ending node: 3
(-0.477415, 0.286835, 0.042613)   0
(-0.098974, -1.177168, 0.869037)   22
(1.290734, -1.450096, 1.100186)   1
(2.067664, -0.365375, 0.9051)   3
ligand-508-p-p-43

C:\Users\George\AppData\Local\Temp\ipykernel_7832\386804788.py:583: DeprecationWarning:

to_plotly_figure is deprecated and will be removed in version 4.0.0. Use MolGraph.to_plotly() instead.

C:\Users\George\AppData\Local\Temp\ipykernel_7832\386804788.py:589: DeprecationWarning:

to_networkx_graph is deprecated and will be removed in version 4.0.0. Use MolGraph.to_networkx() instead.

Pd number index:  9
['P', 'C', 'C', 'C', 'C', 'C', 'C', 'H', 'H', 'Pd', 'H', 'C', 'H', 'H', 'H', 'C', 'H', 'H', 'H', 'H', 'P', 'C', 'C', 'C', 'C', 'C', 'H', 'C', 'H', 'H', 'H', 'C', 'C', 'C', 'C', 'C', 'H', 'C', 'H', 'H', 'H', 'C', 'C', 'C', 'C', 'H', 'C', 'C', 'H', 'H', 'H', 'O', 'O', 'C', 'H', 'H', 'H', 'C', 'H', 'H', 'H', 'O', 'B', 'C', 'C', 'C', 'C', 'H', 'C', 'H', 'C', 'H', 'C', 'C', 'C', 'C', 'H', 'C', 'H', 'C', 'H', 'C', 'C', 'C', 'C', 'F', 'F', 'F', 'F', 'F', 'F', 'F', 'F', 'F', 'F', 'F', 'F', 'O', 'C', 'H', 'H', 'H']
Ligand atom label:  1  Ligand atom A nbo:  1.33937
Ligand atom label:  21  Ligand atom B nbo:  1.02546
Atom_a:  1 Atom_b:  21
C:\Users\George\Desktop\Research_UCLA\CIC\Computational Work\Project cluster version 2\project_catalyst_repurposing\structures_ligand_id\pd_me2_structures\ligand_xyz\ligand-508-p-p-43-ligand_xyz.txt
Starting node: 0
Ending node: 11
(-0.555052, 0.447872, 0.384462)   0
(-1.542686, 0.732415, 1.906562)   1
(-2.939897, 0.613427, 1.808173)   2
(-3.650515, 0.196476, 0.153661)   11
ligand-509-p-p-44

C:\Users\George\AppData\Local\Temp\ipykernel_7832\386804788.py:583: DeprecationWarning:

to_plotly_figure is deprecated and will be removed in version 4.0.0. Use MolGraph.to_plotly() instead.

C:\Users\George\AppData\Local\Temp\ipykernel_7832\386804788.py:589: DeprecationWarning:

to_networkx_graph is deprecated and will be removed in version 4.0.0. Use MolGraph.to_networkx() instead.

Pd number index:  9
['P', 'C', 'C', 'C', 'C', 'C', 'C', 'H', 'H', 'Pd', 'H', 'C', 'H', 'H', 'H', 'C', 'H', 'H', 'H', 'H', 'P', 'C', 'C', 'C', 'C', 'C', 'H', 'C', 'H', 'H', 'C', 'C', 'C', 'C', 'C', 'H', 'C', 'H', 'H', 'H', 'C', 'C', 'C', 'C', 'H', 'C', 'C', 'H', 'H', 'H', 'O', 'O', 'C', 'H', 'H', 'H', 'C', 'H', 'H', 'H', 'O', 'B', 'C', 'C', 'C', 'C', 'H', 'C', 'H', 'C', 'H', 'C', 'C', 'C', 'C', 'H', 'C', 'H', 'C', 'H', 'C', 'C', 'C', 'C', 'F', 'F', 'F', 'F', 'F', 'F', 'F', 'F', 'F', 'F', 'F', 'F', 'H', 'N', 'C', 'H', 'H', 'H', 'C', 'H', 'H', 'H']
Ligand atom label:  1  Ligand atom A nbo:  1.33376
Ligand atom label:  21  Ligand atom B nbo:  1.02933
Atom_a:  1 Atom_b:  21
C:\Users\George\Desktop\Research_UCLA\CIC\Computational Work\Project cluster version 2\project_catalyst_repurposing\structures_ligand_id\pd_me2_structures\ligand_xyz\ligand-509-p-p-44-ligand_xyz.txt
Starting node: 0
Ending node: 11
(-0.64022, -0.062891, -0.590924)   0
(-1.576588, -0.446798, -2.114714)   1
(-2.960422, -0.642183, -1.953258)   2
(-3.647746, -0.472754, -0.244808)   11
ligand-510-p-p-45

C:\Users\George\AppData\Local\Temp\ipykernel_7832\386804788.py:583: DeprecationWarning:

to_plotly_figure is deprecated and will be removed in version 4.0.0. Use MolGraph.to_plotly() instead.

C:\Users\George\AppData\Local\Temp\ipykernel_7832\386804788.py:589: DeprecationWarning:

to_networkx_graph is deprecated and will be removed in version 4.0.0. Use MolGraph.to_networkx() instead.

Pd number index:  0
['Pd', 'P', 'C', 'C', 'C', 'C', 'H', 'C', 'H', 'C', 'H', 'H', 'H', 'C', 'C', 'C', 'C', 'H', 'C', 'H', 'C', 'H', 'H', 'H', 'C', 'C', 'C', 'C', 'H', 'H', 'C', 'C', 'C', 'C', 'H', 'H', 'P', 'C', 'C', 'C', 'C', 'H', 'C', 'H', 'C', 'H', 'H', 'H', 'C', 'C', 'C', 'C', 'H', 'C', 'H', 'C', 'H', 'H', 'H', 'C', 'H', 'H', 'H', 'C', 'H', 'H', 'H', 'C', 'C', 'C', 'C', 'H', 'H', 'C', 'H', 'H', 'H', 'C', 'H', 'H', 'H']
Ligand atom label:  2  Ligand atom A nbo:  1.01829
Ligand atom label:  37  Ligand atom B nbo:  1.20398
Atom_a:  37 Atom_b:  2
C:\Users\George\Desktop\Research_UCLA\CIC\Computational Work\Project cluster version 2\project_catalyst_repurposing\structures_ligand_id\pd_me2_structures\ligand_xyz\ligand-510-p-p-45-ligand_xyz.txt
Ending node: 0
Starting node: 35
(-1.768668, -0.360963, -0.004481)   35
(-1.332495, 1.074331, -1.097075)   30
(-0.290705, 1.963241, -0.734489)   29
(0.297466, 1.995527, 0.642143)   24
(1.320644, 1.108861, 1.052429)   23
(1.740972, -0.369554, 0.015663)   0
ligand-511-p-p-46

C:\Users\George\AppData\Local\Temp\ipykernel_7832\386804788.py:583: DeprecationWarning:

to_plotly_figure is deprecated and will be removed in version 4.0.0. Use MolGraph.to_plotly() instead.

C:\Users\George\AppData\Local\Temp\ipykernel_7832\386804788.py:589: DeprecationWarning:

to_networkx_graph is deprecated and will be removed in version 4.0.0. Use MolGraph.to_networkx() instead.

Pd number index:  0
['Pd', 'P', 'C', 'C', 'C', 'C', 'H', 'C', 'H', 'C', 'H', 'H', 'H', 'C', 'C', 'C', 'C', 'H', 'C', 'H', 'C', 'H', 'H', 'H', 'C', 'C', 'C', 'C', 'H', 'H', 'C', 'C', 'C', 'C', 'H', 'H', 'P', 'C', 'C', 'C', 'C', 'H', 'C', 'H', 'C', 'H', 'H', 'H', 'C', 'C', 'C', 'C', 'H', 'C', 'H', 'C', 'H', 'H', 'H', 'C', 'H', 'H', 'H', 'C', 'H', 'H', 'H', 'C', 'C', 'C', 'C', 'H', 'H', 'O', 'O', 'C', 'H', 'H', 'H', 'C', 'H', 'H', 'H']
Ligand atom label:  2  Ligand atom A nbo:  1.01946
Ligand atom label:  37  Ligand atom B nbo:  1.20333
Atom_a:  37 Atom_b:  2
C:\Users\George\Desktop\Research_UCLA\CIC\Computational Work\Project cluster version 2\project_catalyst_repurposing\structures_ligand_id\pd_me2_structures\ligand_xyz\ligand-511-p-p-46-ligand_xyz.txt
Ending node: 0
Starting node: 35
(-1.751885, -0.598592, -0.071848)   35
(-1.273917, 0.836291, -1.137777)   30
(-0.278638, 1.72429, -0.693178)   29
(0.277875, 1.725158, 0.691974)   24
(1.273621, 0.838156, 1.137484)   23
(1.752235, -0.597491, 0.072941)   0
ligand-512-p-p-47

C:\Users\George\AppData\Local\Temp\ipykernel_7832\386804788.py:583: DeprecationWarning:

to_plotly_figure is deprecated and will be removed in version 4.0.0. Use MolGraph.to_plotly() instead.

C:\Users\George\AppData\Local\Temp\ipykernel_7832\386804788.py:589: DeprecationWarning:

to_networkx_graph is deprecated and will be removed in version 4.0.0. Use MolGraph.to_networkx() instead.

Pd number index:  0
['Pd', 'P', 'C', 'C', 'C', 'C', 'H', 'C', 'H', 'C', 'H', 'H', 'C', 'C', 'C', 'C', 'C', 'H', 'C', 'H', 'H', 'H', 'C', 'C', 'C', 'C', 'H', 'H', 'C', 'C', 'C', 'C', 'H', 'H', 'P', 'C', 'C', 'C', 'C', 'C', 'H', 'C', 'H', 'H', 'H', 'C', 'C', 'C', 'C', 'H', 'C', 'C', 'H', 'H', 'H', 'C', 'H', 'H', 'H', 'C', 'H', 'H', 'H', 'C', 'C', 'C', 'C', 'H', 'H', 'H', 'H', 'O', 'O', 'O', 'O', 'C', 'H', 'H', 'H', 'C', 'H', 'H', 'H', 'C', 'H', 'H', 'H', 'C', 'H', 'H', 'H']
Ligand atom label:  2  Ligand atom A nbo:  1.03998
Ligand atom label:  35  Ligand atom B nbo:  1.2039
Atom_a:  35 Atom_b:  2
C:\Users\George\Desktop\Research_UCLA\CIC\Computational Work\Project cluster version 2\project_catalyst_repurposing\structures_ligand_id\pd_me2_structures\ligand_xyz\ligand-512-p-p-47-ligand_xyz.txt
Ending node: 0
Starting node: 33
(-1.758991, -0.098569, -0.397324)   33
(-1.413615, 0.707744, 1.225017)   28
(-0.556504, 0.093961, 2.158736)   27
(-0.030746, -1.303736, 2.058)   22
(1.043338, -1.722118, 1.237268)   21
(1.698553, -0.579264, -0.070331)   0
ligand-513-p-p-48

C:\Users\George\AppData\Local\Temp\ipykernel_7832\386804788.py:583: DeprecationWarning:

to_plotly_figure is deprecated and will be removed in version 4.0.0. Use MolGraph.to_plotly() instead.

C:\Users\George\AppData\Local\Temp\ipykernel_7832\386804788.py:589: DeprecationWarning:

to_networkx_graph is deprecated and will be removed in version 4.0.0. Use MolGraph.to_networkx() instead.

Pd number index:  8
['P', 'C', 'C', 'C', 'C', 'C', 'C', 'H', 'Pd', 'H', 'C', 'H', 'H', 'H', 'C', 'H', 'H', 'H', 'H', 'P', 'C', 'C', 'C', 'C', 'H', 'C', 'H', 'C', 'H', 'H', 'H', 'C', 'C', 'C', 'C', 'H', 'C', 'H', 'C', 'H', 'H', 'H', 'C', 'H', 'C', 'H', 'H', 'H', 'C', 'H', 'H', 'H', 'C', 'H', 'C', 'H', 'H', 'H', 'C', 'H', 'H', 'H', 'B', 'C', 'C', 'C', 'C', 'H', 'C', 'H', 'C', 'H', 'H', 'H', 'C', 'C', 'C', 'C', 'H', 'C', 'H', 'C', 'H', 'H', 'H', 'C', 'C', 'C', 'C', 'H', 'C', 'H', 'C', 'H', 'H', 'H']
Ligand atom label:  1  Ligand atom A nbo:  1.01692
Ligand atom label:  20  Ligand atom B nbo:  1.01123
Atom_a:  1 Atom_b:  20
C:\Users\George\Desktop\Research_UCLA\CIC\Computational Work\Project cluster version 2\project_catalyst_repurposing\structures_ligand_id\pd_me2_structures\ligand_xyz\ligand-513-p-p-48-ligand_xyz.txt
Starting node: 0
Ending node: 10
(2.605694, 0.873738, -0.090858)   0
(0.778567, 0.826933, -0.112586)   1
(0.158289, -0.439592, -0.152129)   2
(1.234742, -1.941122, -0.139248)   10
ligand-514-p-p-49

C:\Users\George\AppData\Local\Temp\ipykernel_7832\386804788.py:583: DeprecationWarning:

to_plotly_figure is deprecated and will be removed in version 4.0.0. Use MolGraph.to_plotly() instead.

C:\Users\George\AppData\Local\Temp\ipykernel_7832\386804788.py:589: DeprecationWarning:

to_networkx_graph is deprecated and will be removed in version 4.0.0. Use MolGraph.to_networkx() instead.

Pd number index:  8
['P', 'C', 'C', 'C', 'C', 'C', 'C', 'H', 'Pd', 'H', 'C', 'H', 'H', 'H', 'C', 'H', 'H', 'H', 'H', 'P', 'C', 'C', 'C', 'C', 'H', 'C', 'H', 'C', 'H', 'H', 'H', 'C', 'C', 'C', 'C', 'H', 'C', 'H', 'C', 'H', 'H', 'H', 'C', 'H', 'C', 'H', 'H', 'H', 'C', 'H', 'H', 'H', 'C', 'H', 'C', 'H', 'H', 'H', 'C', 'H', 'H', 'H', 'B', 'C', 'C', 'C', 'C', 'H', 'C', 'H', 'C', 'H', 'C', 'C', 'C', 'C', 'H', 'C', 'H', 'C', 'H', 'C', 'C', 'C', 'C', 'H', 'C', 'H', 'C', 'H', 'F', 'F', 'F', 'F', 'F', 'F']
Ligand atom label:  1  Ligand atom A nbo:  1.01708
Ligand atom label:  20  Ligand atom B nbo:  1.01085
Atom_a:  1 Atom_b:  20
C:\Users\George\Desktop\Research_UCLA\CIC\Computational Work\Project cluster version 2\project_catalyst_repurposing\structures_ligand_id\pd_me2_structures\ligand_xyz\ligand-514-p-p-49-ligand_xyz.txt
Starting node: 0
Ending node: 10
(-3.052157, -1.011668, -0.194765)   0
(-1.228742, -0.853565, -0.167681)   1
(-0.690292, 0.449178, -0.145277)   2
(-1.852622, 1.887442, -0.201062)   10
ligand-515-p-p-50

C:\Users\George\AppData\Local\Temp\ipykernel_7832\386804788.py:583: DeprecationWarning:

to_plotly_figure is deprecated and will be removed in version 4.0.0. Use MolGraph.to_plotly() instead.

C:\Users\George\AppData\Local\Temp\ipykernel_7832\386804788.py:589: DeprecationWarning:

to_networkx_graph is deprecated and will be removed in version 4.0.0. Use MolGraph.to_networkx() instead.

Pd number index:  8
['P', 'C', 'C', 'C', 'C', 'C', 'C', 'H', 'Pd', 'H', 'C', 'H', 'H', 'H', 'C', 'H', 'H', 'H', 'H', 'P', 'C', 'C', 'C', 'C', 'C', 'H', 'C', 'H', 'H', 'H', 'C', 'C', 'C', 'C', 'C', 'H', 'C', 'H', 'H', 'H', 'B', 'C', 'C', 'C', 'C', 'H', 'C', 'H', 'C', 'H', 'C', 'C', 'C', 'C', 'H', 'C', 'H', 'C', 'H', 'C', 'C', 'C', 'C', 'H', 'C', 'H', 'C', 'H', 'F', 'F', 'F', 'F', 'F', 'F', 'C', 'C', 'C', 'C', 'H', 'C', 'H', 'C', 'H', 'H', 'H', 'C', 'C', 'C', 'C', 'H', 'C', 'H', 'C', 'H', 'H', 'H', 'O', 'C', 'H', 'H', 'H', 'O', 'C', 'H', 'H', 'H']
Ligand atom label:  1  Ligand atom B nbo:  1.02216
Ligand atom label:  20  Ligand atom A nbo:  1.02438
Atom_a:  20 Atom_b:  1
C:\Users\George\Desktop\Research_UCLA\CIC\Computational Work\Project cluster version 2\project_catalyst_repurposing\structures_ligand_id\pd_me2_structures\ligand_xyz\ligand-515-p-p-50-ligand_xyz.txt
Ending node: 0
Starting node: 10
(-1.268258, 1.945299, -0.387461)   10
(-0.275256, 0.396375, -0.467691)   2
(-0.949095, -0.822544, -0.680766)   1
(-2.779738, -0.744984, -0.753732)   0
ligand-516-p-p-51

C:\Users\George\AppData\Local\Temp\ipykernel_7832\386804788.py:583: DeprecationWarning:

to_plotly_figure is deprecated and will be removed in version 4.0.0. Use MolGraph.to_plotly() instead.

C:\Users\George\AppData\Local\Temp\ipykernel_7832\386804788.py:589: DeprecationWarning:

to_networkx_graph is deprecated and will be removed in version 4.0.0. Use MolGraph.to_networkx() instead.

Pd number index:  8
['P', 'C', 'C', 'C', 'C', 'C', 'C', 'H', 'Pd', 'H', 'C', 'H', 'H', 'H', 'C', 'H', 'H', 'H', 'H', 'P', 'C', 'C', 'C', 'C', 'C', 'H', 'C', 'H', 'H', 'H', 'C', 'C', 'C', 'C', 'C', 'H', 'C', 'H', 'H', 'H', 'B', 'C', 'C', 'C', 'C', 'H', 'C', 'H', 'C', 'H', 'C', 'C', 'C', 'C', 'H', 'C', 'H', 'C', 'H', 'C', 'C', 'C', 'C', 'H', 'C', 'H', 'C', 'H', 'F', 'F', 'F', 'F', 'F', 'F', 'O', 'C', 'H', 'H', 'H', 'O', 'C', 'H', 'H', 'H', 'C', 'H', 'C', 'H', 'H', 'H', 'C', 'H', 'H', 'H', 'C', 'H', 'C', 'H', 'H', 'H', 'C', 'H', 'H', 'H']
Ligand atom label:  1  Ligand atom A nbo:  1.02765
Ligand atom label:  20  Ligand atom B nbo:  1.01434
Atom_a:  1 Atom_b:  20
C:\Users\George\Desktop\Research_UCLA\CIC\Computational Work\Project cluster version 2\project_catalyst_repurposing\structures_ligand_id\pd_me2_structures\ligand_xyz\ligand-516-p-p-51-ligand_xyz.txt
Starting node: 0
Ending node: 10
(-2.844184, -0.387873, -0.218997)   0
(-1.008043, -0.449628, -0.150135)   1
(-0.284965, 0.758696, -0.066083)   2
(-1.200705, 2.355983, -0.204942)   10
ligand-517-p-p-52

C:\Users\George\AppData\Local\Temp\ipykernel_7832\386804788.py:583: DeprecationWarning:

to_plotly_figure is deprecated and will be removed in version 4.0.0. Use MolGraph.to_plotly() instead.

C:\Users\George\AppData\Local\Temp\ipykernel_7832\386804788.py:589: DeprecationWarning:

to_networkx_graph is deprecated and will be removed in version 4.0.0. Use MolGraph.to_networkx() instead.

Pd number index:  8
['P', 'C', 'C', 'C', 'C', 'C', 'C', 'H', 'Pd', 'H', 'C', 'H', 'H', 'H', 'C', 'H', 'H', 'H', 'H', 'P', 'C', 'C', 'C', 'C', 'C', 'H', 'C', 'H', 'H', 'H', 'C', 'C', 'C', 'C', 'C', 'H', 'C', 'H', 'H', 'H', 'B', 'C', 'C', 'C', 'C', 'H', 'C', 'H', 'C', 'H', 'C', 'C', 'C', 'C', 'H', 'C', 'H', 'C', 'H', 'C', 'C', 'C', 'C', 'H', 'C', 'H', 'C', 'H', 'F', 'F', 'F', 'F', 'F', 'F', 'O', 'C', 'H', 'H', 'H', 'O', 'C', 'H', 'H', 'H', 'C', 'H', 'C', 'H', 'H', 'H', 'C', 'H', 'C', 'H', 'H', 'H', 'H', 'H']
Ligand atom label:  1  Ligand atom B nbo:  1.02549
Ligand atom label:  20  Ligand atom A nbo:  0.98717
Atom_a:  1 Atom_b:  20
C:\Users\George\Desktop\Research_UCLA\CIC\Computational Work\Project cluster version 2\project_catalyst_repurposing\structures_ligand_id\pd_me2_structures\ligand_xyz\ligand-517-p-p-52-ligand_xyz.txt
Starting node: 0
Ending node: 10
(-2.825995, -0.29443, -0.290571)   0
(-0.988195, -0.367888, -0.31582)   1
(-0.273585, 0.843044, -0.32333)   2
(-1.184689, 2.439399, -0.359214)   10
ligand-518-p-p-53

C:\Users\George\AppData\Local\Temp\ipykernel_7832\386804788.py:583: DeprecationWarning:

to_plotly_figure is deprecated and will be removed in version 4.0.0. Use MolGraph.to_plotly() instead.

C:\Users\George\AppData\Local\Temp\ipykernel_7832\386804788.py:589: DeprecationWarning:

to_networkx_graph is deprecated and will be removed in version 4.0.0. Use MolGraph.to_networkx() instead.

Pd number index:  8
['P', 'C', 'C', 'C', 'C', 'C', 'C', 'H', 'Pd', 'H', 'C', 'H', 'H', 'H', 'C', 'H', 'H', 'H', 'H', 'P', 'C', 'C', 'C', 'C', 'C', 'H', 'C', 'H', 'H', 'H', 'C', 'C', 'C', 'C', 'C', 'H', 'C', 'H', 'H', 'H', 'B', 'C', 'C', 'C', 'C', 'C', 'H', 'C', 'H', 'C', 'C', 'C', 'C', 'C', 'H', 'C', 'H', 'C', 'C', 'C', 'C', 'C', 'H', 'C', 'H', 'O', 'C', 'H', 'H', 'H', 'O', 'C', 'H', 'H', 'H', 'C', 'C', 'C', 'C', 'H', 'C', 'H', 'C', 'H', 'H', 'H', 'C', 'C', 'C', 'C', 'H', 'C', 'H', 'C', 'H', 'H', 'H', 'H', 'H', 'H', 'H', 'H', 'H', 'C', 'H', 'H', 'H', 'C', 'H', 'H', 'H', 'C', 'H', 'H', 'H']
Ligand atom label:  1  Ligand atom B nbo:  1.02154
Ligand atom label:  20  Ligand atom A nbo:  1.02212
Atom_a:  20 Atom_b:  1
C:\Users\George\Desktop\Research_UCLA\CIC\Computational Work\Project cluster version 2\project_catalyst_repurposing\structures_ligand_id\pd_me2_structures\ligand_xyz\ligand-518-p-p-53-ligand_xyz.txt
Ending node: 0
Starting node: 10
(-0.992792, 2.030815, -0.148251)   10
(-0.085969, 0.478281, -0.52803)   2
(-0.819131, -0.692108, -0.775202)   1
(-2.641989, -0.569786, -0.638519)   0
ligand-519-p-p-54

C:\Users\George\AppData\Local\Temp\ipykernel_7832\386804788.py:583: DeprecationWarning:

to_plotly_figure is deprecated and will be removed in version 4.0.0. Use MolGraph.to_plotly() instead.

C:\Users\George\AppData\Local\Temp\ipykernel_7832\386804788.py:589: DeprecationWarning:

to_networkx_graph is deprecated and will be removed in version 4.0.0. Use MolGraph.to_networkx() instead.

Pd number index:  8
['P', 'C', 'C', 'C', 'C', 'C', 'C', 'H', 'Pd', 'H', 'C', 'H', 'H', 'H', 'C', 'H', 'H', 'H', 'H', 'P', 'C', 'C', 'C', 'C', 'C', 'H', 'C', 'H', 'H', 'H', 'C', 'C', 'C', 'C', 'C', 'H', 'C', 'H', 'H', 'H', 'B', 'C', 'C', 'C', 'C', 'H', 'C', 'H', 'C', 'H', 'C', 'C', 'C', 'C', 'H', 'C', 'H', 'C', 'H', 'C', 'C', 'C', 'C', 'H', 'C', 'H', 'C', 'H', 'F', 'F', 'F', 'F', 'F', 'F', 'C', 'C', 'H', 'H', 'H', 'C', 'H', 'C', 'H', 'H', 'H', 'H', 'C', 'H', 'H', 'H', 'C', 'H', 'H', 'H', 'C', 'H', 'H', 'H', 'C', 'H', 'H', 'H']
Ligand atom label:  1  Ligand atom A nbo:  1.01255
Ligand atom label:  20  Ligand atom B nbo:  1.01066
Atom_a:  1 Atom_b:  20
C:\Users\George\Desktop\Research_UCLA\CIC\Computational Work\Project cluster version 2\project_catalyst_repurposing\structures_ligand_id\pd_me2_structures\ligand_xyz\ligand-519-p-p-54-ligand_xyz.txt
Starting node: 0
Ending node: 10
(-2.912741, -0.781869, -0.522458)   0
(-1.101436, -0.641932, -0.717952)   1
(-0.529766, 0.599495, -0.372607)   2
(-1.634759, 2.063647, -0.137119)   10
ligand-520-n-o-80
Pd number index:  12
['C', 'C', 'C', 'C', 'H', 'H', 'H', 'N', 'N', 'C', 'O', 'O', 'Pd', 'C', 'H', 'H', 'H', 'C', 'H', 'H', 'H']
Ligand atom label:  8  Ligand atom A nbo:  -0.45532
Ligand atom label:  11  Ligand atom B nbo:  -0.65624
Atom_a:  8 Atom_b:  11
C:\Users\George\Desktop\Research_UCLA\CIC\Computational Work\Project cluster version 2\project_catalyst_repurposing\structures_ligand_id\pd_me2_structures\ligand_xyz\ligand-520-n-o-80-ligand_xyz.txt

C:\Users\George\AppData\Local\Temp\ipykernel_7832\386804788.py:583: DeprecationWarning:

to_plotly_figure is deprecated and will be removed in version 4.0.0. Use MolGraph.to_plotly() instead.

C:\Users\George\AppData\Local\Temp\ipykernel_7832\386804788.py:589: DeprecationWarning:

to_networkx_graph is deprecated and will be removed in version 4.0.0. Use MolGraph.to_networkx() instead.

C:\Users\George\AppData\Local\Temp\ipykernel_7832\386804788.py:583: DeprecationWarning:

to_plotly_figure is deprecated and will be removed in version 4.0.0. Use MolGraph.to_plotly() instead.

C:\Users\George\AppData\Local\Temp\ipykernel_7832\386804788.py:589: DeprecationWarning:

to_networkx_graph is deprecated and will be removed in version 4.0.0. Use MolGraph.to_networkx() instead.

C:\Users\George\AppData\Local\Temp\ipykernel_7832\386804788.py:583: DeprecationWarning:

to_plotly_figure is deprecated and will be removed in version 4.0.0. Use MolGraph.to_plotly() instead.

C:\Users\George\AppData\Local\Temp\ipykernel_7832\386804788.py:589: DeprecationWarning:

to_networkx_graph is deprecated and will be removed in version 4.0.0. Use MolGraph.to_networkx() instead.

Starting node: 7
Ending node: 10
(-0.812645, -0.60206, -0.000765)   7
(-1.626871, 0.461316, -8.5e-05)   2
(-1.014753, 1.871381, -0.000167)   9
(0.244889, 1.904316, -0.000851)   10
ligand-521-n-o-81
Pd number index:  11
['C', 'C', 'C', 'C', 'H', 'H', 'H', 'N', 'C', 'O', 'O', 'Pd', 'C', 'H', 'H', 'H', 'C', 'H', 'H', 'H', 'C', 'N', 'O', 'O']
Ligand atom label:  8  Ligand atom A nbo:  -0.48852
Ligand atom label:  10  Ligand atom B nbo:  -0.66422
Atom_a:  8 Atom_b:  10
C:\Users\George\Desktop\Research_UCLA\CIC\Computational Work\Project cluster version 2\project_catalyst_repurposing\structures_ligand_id\pd_me2_structures\ligand_xyz\ligand-521-n-o-81-ligand_xyz.txt
Starting node: 7
Ending node: 9
(0.075317, -0.403719, 7.7e-05)   7
(0.716725, 0.774612, 7.5e-05)   2
(-0.115775, 2.07369, 6.3e-05)   8
(-1.363218, 1.904893, -0.00041)   9
ligand-522-n-o-82
Pd number index:  11
['C', 'C', 'C', 'C', 'H', 'H', 'H', 'N', 'C', 'O', 'O', 'Pd', 'C', 'H', 'H', 'H', 'C', 'H', 'H', 'H', 'C', 'O', 'C', 'H', 'H', 'H']
Ligand atom label:  8  Ligand atom A nbo:  -0.48997
Ligand atom label:  10  Ligand atom B nbo:  -0.65335
Atom_a:  8 Atom_b:  10
C:\Users\George\Desktop\Research_UCLA\CIC\Computational Work\Project cluster version 2\project_catalyst_repurposing\structures_ligand_id\pd_me2_structures\ligand_xyz\ligand-522-n-o-82-ligand_xyz.txt
Starting node: 7
Ending node: 9
(-0.301715, -0.342745, -0.000642)   7
(-0.878656, 0.87385, -0.000201)   2
(0.031942, 2.119581, -0.000175)   8
(1.268745, 1.878523, -3.9e-05)   9
ligand-523-n-o-83

C:\Users\George\AppData\Local\Temp\ipykernel_7832\386804788.py:583: DeprecationWarning:

to_plotly_figure is deprecated and will be removed in version 4.0.0. Use MolGraph.to_plotly() instead.

C:\Users\George\AppData\Local\Temp\ipykernel_7832\386804788.py:589: DeprecationWarning:

to_networkx_graph is deprecated and will be removed in version 4.0.0. Use MolGraph.to_networkx() instead.

Pd number index:  16
['C', 'C', 'C', 'C', 'H', 'H', 'H', 'H', 'H', 'H', 'N', 'C', 'C', 'N', 'C', 'O', 'Pd', 'C', 'H', 'H', 'H', 'C', 'H', 'H', 'H', 'C', 'H', 'H', 'H']
Ligand atom label:  11  Ligand atom A nbo:  -0.47069
Ligand atom label:  16  Ligand atom B nbo:  -0.64109
Atom_a:  11 Atom_b:  16
C:\Users\George\Desktop\Research_UCLA\CIC\Computational Work\Project cluster version 2\project_catalyst_repurposing\structures_ligand_id\pd_me2_structures\ligand_xyz\ligand-523-n-o-83-ligand_xyz.txt
Starting node: 10
Ending node: 15
(0.134782, 1.150908, -0.017109)   10
(1.390006, 0.82233, -0.004793)   1
(1.946044, -0.50347, 0.001294)   11
(1.195556, -1.72412, -0.00844)   14
(-0.041728, -1.821741, -0.018976)   15
ligand-524-n-o-84

C:\Users\George\AppData\Local\Temp\ipykernel_7832\386804788.py:583: DeprecationWarning:

to_plotly_figure is deprecated and will be removed in version 4.0.0. Use MolGraph.to_plotly() instead.

C:\Users\George\AppData\Local\Temp\ipykernel_7832\386804788.py:589: DeprecationWarning:

to_networkx_graph is deprecated and will be removed in version 4.0.0. Use MolGraph.to_networkx() instead.

Pd number index:  27
['C', 'C', 'C', 'C', 'H', 'H', 'H', 'H', 'H', 'H', 'N', 'C', 'C', 'N', 'C', 'O', 'C', 'C', 'C', 'C', 'H', 'C', 'H', 'C', 'H', 'H', 'H', 'Pd', 'C', 'H', 'H', 'H', 'C', 'H', 'H', 'H']
Ligand atom label:  11  Ligand atom A nbo:  -0.46611
Ligand atom label:  16  Ligand atom B nbo:  -0.63229
Atom_a:  11 Atom_b:  16
C:\Users\George\Desktop\Research_UCLA\CIC\Computational Work\Project cluster version 2\project_catalyst_repurposing\structures_ligand_id\pd_me2_structures\ligand_xyz\ligand-524-n-o-84-ligand_xyz.txt
Starting node: 10
Ending node: 15
(-1.74674, 1.0125, 0.022477)   10
(-0.697043, 1.77297, -0.072328)   1
(0.686086, 1.366139, -0.107879)   11
(1.13196, 0.008976, -0.015665)   14
(0.394229, -0.99255, 0.02218)   15
ligand-525-n-o-85

C:\Users\George\AppData\Local\Temp\ipykernel_7832\386804788.py:583: DeprecationWarning:

to_plotly_figure is deprecated and will be removed in version 4.0.0. Use MolGraph.to_plotly() instead.

C:\Users\George\AppData\Local\Temp\ipykernel_7832\386804788.py:589: DeprecationWarning:

to_networkx_graph is deprecated and will be removed in version 4.0.0. Use MolGraph.to_networkx() instead.

Pd number index:  16
['C', 'C', 'C', 'C', 'H', 'H', 'H', 'H', 'H', 'H', 'N', 'C', 'C', 'N', 'C', 'O', 'Pd', 'C', 'H', 'H', 'H', 'C', 'H', 'H', 'H', 'C', 'F', 'F', 'F']
Ligand atom label:  11  Ligand atom A nbo:  -0.46223
Ligand atom label:  16  Ligand atom B nbo:  -0.62414
Atom_a:  11 Atom_b:  16
C:\Users\George\Desktop\Research_UCLA\CIC\Computational Work\Project cluster version 2\project_catalyst_repurposing\structures_ligand_id\pd_me2_structures\ligand_xyz\ligand-525-n-o-85-ligand_xyz.txt
Starting node: 10
Ending node: 15
(-1.003047, 1.288639, -0.015)   10
(0.232022, 1.686896, -0.022646)   1
(1.415413, 0.860423, -0.012382)   11
(1.386395, -0.558331, 0.007648)   14
(0.403537, -1.306682, 0.019597)   15
ligand-526-n-o-86

C:\Users\George\AppData\Local\Temp\ipykernel_7832\386804788.py:583: DeprecationWarning:

to_plotly_figure is deprecated and will be removed in version 4.0.0. Use MolGraph.to_plotly() instead.

C:\Users\George\AppData\Local\Temp\ipykernel_7832\386804788.py:589: DeprecationWarning:

to_networkx_graph is deprecated and will be removed in version 4.0.0. Use MolGraph.to_networkx() instead.

Pd number index:  16
['C', 'C', 'C', 'C', 'H', 'H', 'H', 'H', 'H', 'H', 'N', 'C', 'C', 'N', 'C', 'O', 'Pd', 'C', 'H', 'H', 'H', 'C', 'H', 'H', 'H', 'C', 'F', 'F', 'C', 'C', 'F', 'F', 'F', 'F', 'F']
Ligand atom label:  11  Ligand atom A nbo:  -0.46067
Ligand atom label:  16  Ligand atom B nbo:  -0.63081
Atom_a:  11 Atom_b:  16
C:\Users\George\Desktop\Research_UCLA\CIC\Computational Work\Project cluster version 2\project_catalyst_repurposing\structures_ligand_id\pd_me2_structures\ligand_xyz\ligand-526-n-o-86-ligand_xyz.txt
Starting node: 10
Ending node: 15
(-2.675971, 0.69955, -0.012201)   10
(-1.890926, 1.732302, -0.019372)   1
(-0.446026, 1.730552, -0.014822)   11
(0.337011, 0.548748, -0.002157)   14
(-0.049382, -0.627383, 0.008727)   15
ligand-527-n-o-87

C:\Users\George\AppData\Local\Temp\ipykernel_7832\386804788.py:583: DeprecationWarning:

to_plotly_figure is deprecated and will be removed in version 4.0.0. Use MolGraph.to_plotly() instead.

C:\Users\George\AppData\Local\Temp\ipykernel_7832\386804788.py:589: DeprecationWarning:

to_networkx_graph is deprecated and will be removed in version 4.0.0. Use MolGraph.to_networkx() instead.

Pd number index:  16
['C', 'C', 'C', 'C', 'H', 'H', 'H', 'H', 'H', 'H', 'N', 'C', 'C', 'N', 'C', 'O', 'Pd', 'C', 'H', 'H', 'H', 'C', 'H', 'H', 'H', 'C', 'F', 'F', 'C', 'C', 'F', 'F', 'F', 'F', 'C', 'C', 'C', 'C', 'F', 'F', 'F', 'F', 'F', 'F', 'F', 'F', 'F']
Ligand atom label:  11  Ligand atom A nbo:  -0.53709
Ligand atom label:  16  Ligand atom B nbo:  -0.60085
Atom_a:  11 Atom_b:  16
C:\Users\George\Desktop\Research_UCLA\CIC\Computational Work\Project cluster version 2\project_catalyst_repurposing\structures_ligand_id\pd_me2_structures\ligand_xyz\ligand-527-n-o-87-ligand_xyz.txt
Starting node: 10
Ending node: 15
(-5.139935, 0.157165, -0.110316)   10
(-4.640345, 1.353936, -0.093675)   1
(-3.242368, 1.71481, -0.018482)   11
(-2.193813, 0.76698, 0.076473)   14
(-2.274198, -0.467676, 0.125569)   15
ligand-528-p-o-179

C:\Users\George\AppData\Local\Temp\ipykernel_7832\386804788.py:583: DeprecationWarning:

to_plotly_figure is deprecated and will be removed in version 4.0.0. Use MolGraph.to_plotly() instead.

C:\Users\George\AppData\Local\Temp\ipykernel_7832\386804788.py:589: DeprecationWarning:

to_networkx_graph is deprecated and will be removed in version 4.0.0. Use MolGraph.to_networkx() instead.

Pd number index:  52
['P', 'O', 'P', 'N', 'C', 'C', 'C', 'C', 'C', 'C', 'H', 'H', 'H', 'H', 'H', 'C', 'C', 'C', 'C', 'C', 'C', 'H', 'H', 'H', 'H', 'H', 'C', 'C', 'C', 'C', 'H', 'C', 'H', 'C', 'H', 'H', 'C', 'C', 'C', 'C', 'C', 'C', 'H', 'H', 'C', 'C', 'C', 'C', 'C', 'C', 'H', 'H', 'Pd', 'H', 'H', 'C', 'H', 'H', 'H', 'C', 'H', 'H', 'H', 'H', 'H', 'C', 'F', 'F', 'F', 'C', 'C', 'C', 'C', 'C', 'C', 'H', 'H', 'H', 'H', 'O', 'O', 'C', 'H', 'H', 'H', 'C', 'H', 'H', 'H']
Ligand atom label:  1  Ligand atom B nbo:  1.23114
Ligand atom label:  2  Ligand atom A nbo:  -0.93614
Atom_a:  1 Atom_b:  2
C:\Users\George\Desktop\Research_UCLA\CIC\Computational Work\Project cluster version 2\project_catalyst_repurposing\structures_ligand_id\pd_me2_structures\ligand_xyz\ligand-528-p-o-179-ligand_xyz.txt
Starting node: 0
Ending node: 1
(-0.751027, 0.941315, 0.024819)   0
(0.704092, -0.086429, -0.125112)   3
(0.462014, -1.659288, -0.757037)   2
(-0.95082, -1.831822, -1.260146)   1
ligand-529-p-o-180

C:\Users\George\AppData\Local\Temp\ipykernel_7832\386804788.py:583: DeprecationWarning:

to_plotly_figure is deprecated and will be removed in version 4.0.0. Use MolGraph.to_plotly() instead.

C:\Users\George\AppData\Local\Temp\ipykernel_7832\386804788.py:589: DeprecationWarning:

to_networkx_graph is deprecated and will be removed in version 4.0.0. Use MolGraph.to_networkx() instead.

Pd number index:  52
['P', 'O', 'P', 'N', 'C', 'C', 'C', 'C', 'C', 'C', 'H', 'H', 'H', 'H', 'H', 'C', 'C', 'C', 'C', 'C', 'C', 'H', 'H', 'H', 'H', 'H', 'C', 'C', 'C', 'C', 'H', 'C', 'H', 'C', 'H', 'H', 'C', 'C', 'C', 'C', 'C', 'C', 'H', 'H', 'C', 'C', 'C', 'C', 'C', 'C', 'H', 'H', 'Pd', 'H', 'H', 'C', 'H', 'H', 'H', 'C', 'H', 'H', 'H', 'H', 'C', 'H', 'H', 'H', 'H', 'N', 'C', 'H', 'H', 'H', 'H', 'H']
Ligand atom label:  1  Ligand atom B nbo:  1.21332
Ligand atom label:  2  Ligand atom A nbo:  -0.94388
Atom_a:  1 Atom_b:  2
C:\Users\George\Desktop\Research_UCLA\CIC\Computational Work\Project cluster version 2\project_catalyst_repurposing\structures_ligand_id\pd_me2_structures\ligand_xyz\ligand-529-p-o-180-ligand_xyz.txt

C:\Users\George\AppData\Local\Temp\ipykernel_7832\386804788.py:583: DeprecationWarning:

to_plotly_figure is deprecated and will be removed in version 4.0.0. Use MolGraph.to_plotly() instead.

C:\Users\George\AppData\Local\Temp\ipykernel_7832\386804788.py:589: DeprecationWarning:

to_networkx_graph is deprecated and will be removed in version 4.0.0. Use MolGraph.to_networkx() instead.

Starting node: 0
Ending node: 1
(-1.216312, 1.097976, -0.177591)   0
(0.039836, -0.137223, -0.257453)   3
(-0.48433, -1.762009, -0.271266)   2
(-1.945542, -1.824833, -0.646369)   1
ligand-530-p-o-181
Pd number index:  52
['P', 'O', 'P', 'N', 'C', 'C', 'C', 'C', 'C', 'C', 'H', 'H', 'H', 'H', 'H', 'C', 'C', 'C', 'C', 'C', 'C', 'H', 'H', 'H', 'H', 'H', 'C', 'C', 'C', 'C', 'H', 'C', 'H', 'C', 'H', 'H', 'C', 'C', 'C', 'C', 'C', 'C', 'H', 'H', 'C', 'C', 'C', 'C', 'C', 'C', 'H', 'H', 'Pd', 'H', 'H', 'C', 'H', 'H', 'H', 'C', 'H', 'H', 'H', 'C', 'H', 'H', 'H', 'N', 'C', 'H', 'H', 'H', 'H', 'H', 'C', 'C', 'F', 'F', 'F', 'F', 'F', 'F']
Ligand atom label:  1  Ligand atom B nbo:  1.19276
Ligand atom label:  2  Ligand atom A nbo:  -0.94081
Atom_a:  1 Atom_b:  2
C:\Users\George\Desktop\Research_UCLA\CIC\Computational Work\Project cluster version 2\project_catalyst_repurposing\structures_ligand_id\pd_me2_structures\ligand_xyz\ligand-530-p-o-181-ligand_xyz.txt
Starting node: 0
Ending node: 1
(-1.103126, -0.381682, 0.547045)   0
(0.437915, -0.031361, -0.225293)   3
(0.400129, 0.271325, -1.920267)   2
(-1.014448, 0.235251, -2.437799)   1
ligand-531-p-o-182

C:\Users\George\AppData\Local\Temp\ipykernel_7832\386804788.py:583: DeprecationWarning:

to_plotly_figure is deprecated and will be removed in version 4.0.0. Use MolGraph.to_plotly() instead.

C:\Users\George\AppData\Local\Temp\ipykernel_7832\386804788.py:589: DeprecationWarning:

to_networkx_graph is deprecated and will be removed in version 4.0.0. Use MolGraph.to_networkx() instead.

Pd number index:  52
['P', 'O', 'P', 'N', 'C', 'C', 'C', 'C', 'C', 'C', 'H', 'H', 'H', 'H', 'H', 'C', 'C', 'C', 'C', 'C', 'C', 'H', 'H', 'H', 'H', 'H', 'C', 'C', 'C', 'C', 'H', 'C', 'H', 'C', 'H', 'H', 'C', 'C', 'C', 'C', 'C', 'C', 'H', 'H', 'C', 'C', 'C', 'C', 'C', 'C', 'H', 'H', 'Pd', 'H', 'H', 'C', 'H', 'H', 'H', 'C', 'H', 'H', 'H', 'H', 'C', 'H', 'H', 'H', 'H', 'N', 'C', 'H', 'H', 'H', 'O', 'O', 'C', 'H', 'H', 'H', 'C', 'H', 'H', 'H']
Ligand atom label:  1  Ligand atom B nbo:  1.21295
Ligand atom label:  2  Ligand atom A nbo:  -0.94405
Atom_a:  1 Atom_b:  2
C:\Users\George\Desktop\Research_UCLA\CIC\Computational Work\Project cluster version 2\project_catalyst_repurposing\structures_ligand_id\pd_me2_structures\ligand_xyz\ligand-531-p-o-182-ligand_xyz.txt
Starting node: 0
Ending node: 1
(-1.378344, -0.151407, 0.054044)   0
(0.344155, -0.303648, -0.313973)   3
(0.85226, -1.741235, -1.071464)   2
(-0.324865, -2.470015, -1.67574)   1
ligand-532-p-o-183

C:\Users\George\AppData\Local\Temp\ipykernel_7832\386804788.py:583: DeprecationWarning:

to_plotly_figure is deprecated and will be removed in version 4.0.0. Use MolGraph.to_plotly() instead.

C:\Users\George\AppData\Local\Temp\ipykernel_7832\386804788.py:589: DeprecationWarning:

to_networkx_graph is deprecated and will be removed in version 4.0.0. Use MolGraph.to_networkx() instead.

Pd number index:  52
['P', 'O', 'P', 'N', 'C', 'C', 'C', 'C', 'C', 'C', 'H', 'H', 'H', 'H', 'H', 'C', 'C', 'C', 'C', 'C', 'C', 'H', 'H', 'H', 'H', 'H', 'C', 'C', 'C', 'C', 'H', 'C', 'H', 'C', 'H', 'H', 'C', 'C', 'C', 'C', 'C', 'C', 'H', 'H', 'C', 'C', 'C', 'C', 'C', 'C', 'H', 'H', 'Pd', 'H', 'H', 'C', 'H', 'H', 'H', 'C', 'H', 'H', 'H', 'H', 'C', 'H', 'H', 'H', 'C', 'H', 'C', 'F', 'F', 'F', 'F', 'F', 'F', 'N', 'C', 'H', 'H', 'H']
Ligand atom label:  1  Ligand atom B nbo:  1.2117
Ligand atom label:  2  Ligand atom A nbo:  -0.94392
Atom_a:  1 Atom_b:  2
C:\Users\George\Desktop\Research_UCLA\CIC\Computational Work\Project cluster version 2\project_catalyst_repurposing\structures_ligand_id\pd_me2_structures\ligand_xyz\ligand-532-p-o-183-ligand_xyz.txt
Starting node: 0
Ending node: 1
(-0.729091, 0.06092, -1.133668)   0
(-0.122904, 0.758147, 0.364903)   3
(-0.350841, 2.443689, 0.559089)   2
(-1.39351, 2.921349, -0.423345)   1
           Filename  Pd_atom label  Methyl_atom_1 label  Methyl_atom_2 label  \
0  ligand-001-n-n-1              2                    3                    7
1  ligand-002-p-p-1              2                    7                    3
2  ligand-003-p-p-2              3                    4                    8
3  ligand-004-p-p-3              3                    8                    4
4  ligand-005-c-n-1              1                   42                   46

  Hydrogens_methyl_1_label Hydrogens_methyl_2_label  Ligand_atom_1 label  \
0                [6, 4, 5]               [10, 9, 8]                   23
1               [9, 8, 10]                [4, 6, 5]                   16
2                [5, 7, 6]              [10, 11, 9]                    1
3              [11, 10, 9]                [6, 5, 7]                   45
4             [43, 44, 45]             [49, 48, 47]                    2

   Ligand_atom_2 label    Atoms_distance_2 label  \
0                   22   [1, 13, 15, 17, 18, 19]
1                   17   [1, 40, 13, 18, 51, 29]
2                   12   [32, 2, 43, 17, 21, 54]
3                    1  [42, 46, 16, 20, 57, 31]
4                   59           [50, 52, 61, 6]

                              Atoms_distance_3 label  \
0  [11, 12, 14, 16, 20, 21, 24, 25, 26, 27, 28, 2...
1   [41, 42, 11, 12, 14, 15, 19, 20, 52, 53, 30, 31]
2  [33, 34, 13, 14, 15, 44, 45, 18, 19, 55, 22, 2...
3  [32, 2, 33, 43, 44, 14, 47, 48, 17, 18, 21, 22...
4                          [3, 4, 7, 51, 55, 56, 25]

                              Atoms_distance_4 label Atoms_distance_2_a label  \
0                                                 []             [17, 18, 19]
1  [21, 22, 23, 24, 32, 33, 34, 35, 43, 44, 45, 4...              [1, 18, 29]
2  [16, 20, 24, 25, 26, 27, 35, 36, 37, 38, 46, 4...             [17, 43, 54]
3  [12, 13, 15, 19, 23, 24, 25, 26, 34, 35, 36, 3...             [42, 46, 57]
4                      [5, 8, 9, 20, 53, 54, 24, 58]                  [6, 61]

              Atoms_distance_3_a label  \
0  [32, 33, 1, 20, 21, 28, 29, 30, 31]
1         [11, 12, 13, 19, 20, 30, 31]
2         [44, 45, 15, 18, 19, 55, 56]
3          [2, 43, 44, 47, 48, 58, 59]
4                        [3, 4, 7, 25]

                       Atoms_distance_4_a label Atoms_distance_2_b label  \
0                                      [11, 12]              [1, 13, 15]
1      [32, 33, 34, 35, 14, 15, 21, 22, 23, 24]             [13, 40, 51]
2   [2, 46, 47, 48, 49, 16, 20, 57, 58, 59, 60]              [2, 21, 32]
3  [12, 13, 14, 49, 50, 51, 52, 60, 61, 62, 63]             [16, 20, 31]
4                         [5, 8, 9, 50, 20, 24]                 [50, 52]

               Atoms_distance_3_b label  \
0  [11, 12, 14, 16, 19, 24, 25, 26, 27]
1           [1, 41, 42, 14, 15, 52, 53]
2          [33, 34, 13, 14, 15, 22, 23]
3          [32, 33, 14, 17, 18, 21, 22]
4                      [51, 55, 56, 25]

                       Atoms_distance_4_b label  Atom label shortest paths
0                                      [20, 21]         [2, 23, 19, 1, 22]
1      [11, 12, 43, 44, 45, 46, 54, 55, 56, 57]         [2, 16, 1, 13, 17]
2  [35, 36, 37, 38, 16, 17, 20, 24, 25, 26, 27]      [3, 1, 17, 15, 2, 12]
3   [34, 35, 36, 37, 2, 15, 19, 23, 24, 25, 26]  [3, 45, 42, 2, 14, 16, 1]
4                           [6, 53, 54, 24, 58]      [1, 2, 6, 25, 50, 59]

C:\Users\George\AppData\Local\Temp\ipykernel_7832\386804788.py:583: DeprecationWarning:

to_plotly_figure is deprecated and will be removed in version 4.0.0. Use MolGraph.to_plotly() instead.

C:\Users\George\AppData\Local\Temp\ipykernel_7832\386804788.py:589: DeprecationWarning:

to_networkx_graph is deprecated and will be removed in version 4.0.0. Use MolGraph.to_networkx() instead.

(-0.453569, -0.001281, 0.025399)
Starting node: 0
(0.280081, -1.353772, -1.005911)
(-0.921593, -0.840281, 1.590733)
(-2.103593, 0.197254, -0.783083)
(1.668692, -1.575559, -0.962845)
(-0.490093, -2.13391, -1.877283)
(2.747601, -0.627605, 0.149301)
(2.255078, -2.554863, -1.759459)
(2.689225, 0.772553, -0.390403)
Ending node: 4
(2.087469, -0.773044, 1.459512)
(4.077666, -1.229666, 0.013235)
(-1.23878, -0.01711, 2.676207)
(-0.994024, -2.227244, 1.740577)
(-3.294065, -0.363605, -0.309618)
(-2.143058, 0.98824, -1.939927)
(1.473211, -3.326043, -2.617489)
(3.339564, -2.691768, -1.683251)
(0.098058, -3.115212, -2.675416)
(1.941613, -4.095451, -3.244141)
(-0.527882, -3.716914, -3.346207)
(-1.574857, -1.97574, -1.934228)
(-4.495711, -0.15301, -0.988708)
(-3.286777, -0.976056, 0.601348)
(-4.520151, 0.616713, -2.149301)
(-5.422156, -0.597717, -0.604099)
(-3.33807, 1.187924, -2.624157)
(-5.46501, 0.78146, -2.682079)
(-3.35054, 1.8065, -3.529898)
(-1.214294, 1.461113, -2.290573)
(-1.654843, -0.572951, 3.884078)
(-1.139697, 1.071927, 2.569922)
(-1.739584, -1.95782, 4.024151)
(-1.900702, 0.08207, 4.728891)
(-1.401133, -2.783008, 2.952438)
(-2.057978, -2.396915, 4.977906)
(-1.44796, -3.873658, 3.062275)
(-0.719993, -2.88238, 0.903499)
(-0.453569, -0.001281, 0.025399)   0
(0.280081, -1.353772, -1.005911)   1
(1.668692, -1.575559, -0.962845)   2
(2.747601, -0.627605, 0.149301)   3
(2.689225, 0.772553, -0.390403)   4
{'Atom0': (-0.453569, -0.001281, 0.025399), 'Atom1': (0.280081, -1.353772, -1.005911), 'Atom2': (1.668692, -1.575559, -0.962845), 'Atom3': (2.747601, -0.627605, 0.149301), 'Atom4': (2.689225, 0.772553, -0.390403)}
-0.453569
-0.001281
0.025399
0.280081
-1.353772
-1.005911
1.668692
-1.575559
-0.962845
2.747601
-0.627605
0.149301
2.689225
0.772553
-0.390403
Atom label shortest path:  [36, 1, 2, 3, 4, 5]
    Filename  Pd_atom label  Methyl_atom_1 label  Methyl_atom_2 label  \
0   pd-c-o-1              1                   43                   47
1  pd-c-o-10              1                   22                   26
2  pd-c-o-11              1                   22                   26
3   pd-c-o-2              1                   22                   26
4   pd-c-o-3              1                   37                   41

  Hydrogens_methyl_1_label Hydrogens_methyl_2_label  Ligand_atom_1 label  \
0             [46, 44, 45]             [48, 49, 50]                    2
1             [25, 23, 24]             [27, 28, 29]                    2
2             [25, 24, 23]             [29, 28, 27]                    2
3             [25, 24, 23]             [29, 27, 28]                    2
4             [40, 38, 39]             [42, 44, 43]                    2

   Ligand_atom_2 label Atoms_distance_2 label Atoms_distance_3 label  \
0                   61             [51, 6, 7]  [3, 4, 8, 52, 56, 26]
1                   41             [38, 6, 7]  [3, 4, 39, 40, 8, 21]
2                   35             [32, 6, 7]  [33, 34, 3, 4, 8, 21]
3                   40             [30, 6, 7]  [35, 3, 4, 8, 21, 31]
4                   54             [45, 6, 7]      [3, 4, 8, 46, 50]

                       Atoms_distance_4 label Atoms_distance_2_a label  \
0  [5, 9, 10, 21, 53, 54, 55, 57, 58, 59, 25]                   [6, 7]
1                          [5, 9, 10, 16, 20]                   [6, 7]
2                          [5, 9, 10, 16, 20]                   [6, 7]
3  [32, 33, 34, 36, 38, 37, 5, 9, 10, 16, 20]                   [6, 7]
4      [5, 9, 10, 47, 48, 49, 51, 52, 53, 55]                   [6, 7]

  Atoms_distance_3_a label Atoms_distance_4_a label Atoms_distance_2_b label  \
0            [3, 4, 8, 26]   [5, 9, 10, 51, 21, 25]                     [51]
1            [3, 4, 8, 21]   [5, 38, 9, 10, 16, 20]                     [38]
2            [3, 4, 8, 21]   [32, 5, 9, 10, 16, 20]                     [32]
3            [3, 4, 8, 21]   [5, 9, 10, 16, 20, 30]                     [30]
4            [3, 4, 8, 45]   [5, 9, 10, 46, 50, 55]                     [45]

  Atoms_distance_3_b label         Atoms_distance_4_b label  \
0             [56, 26, 52]  [7, 53, 54, 55, 57, 58, 59, 25]
1             [40, 21, 39]                          [20, 7]
2             [33, 34, 21]                          [20, 7]
3             [35, 21, 31]  [32, 33, 34, 36, 37, 38, 7, 20]
4              [50, 46, 7]      [4, 47, 48, 49, 51, 52, 53]

  Atom label shortest paths
0     [1, 2, 7, 26, 51, 61]
1     [1, 2, 7, 21, 38, 41]
2     [1, 2, 7, 21, 32, 35]
3     [1, 2, 7, 21, 30, 40]
4         [1, 2, 7, 45, 54]

## Convert all opt .out files into spe .com files from opt_directory to spe_complex_directory

In [8]:
xyz_match = ['X           Y           Z']
for subdir,dirs,files in os.walk(opt_directory):                  # Loop over each directory, subdirectory and files
    for file in files:                                      # Loop over each file
        if any([file.endswith('-opt.out')]):                    # If file is a .out file
            filename = os.path.join(subdir, file)       # Return path to file
            name = Path(filename).stem.replace('-opt',"")         # Extract filename from the end of path and return as a string
            print(name)
        
            
            mylines = []
            with open (filename, 'rt') as myfile:       # Open .out for reading text
                # myfile = myfile.read()                # Read the entire file to a string
                for myline in myfile:                    # For each line, stored as myline,
                    mylines.append(myline)               # add its contents to mylines list.


                #initialize charge and multiplicity
                charge = None
                multiplicity = None  
                
                # Find and extract the Charge and Multiplicity values

                for line in mylines:
                    if 'Charge =' in line and 'Multiplicity =' in line:
                        # Use regular expressions to extract numbers
                        charge_multiplicity = re.findall(r'Charge\s*=\s*(-?\d+)\s*Multiplicity\s*=\s*(\d+)', line)
                        charge_str, multiplicity_str = charge_multiplicity[0]
                        charge = int(charge_str)
                        print('Charge: ',charge)
                        multiplicity = int(multiplicity_str)
                        print('Multiplicity: ',multiplicity)
                

#                 # Find XYZ Coordinates

                for line in mylines:
                    if 'NAtoms=' in line:
                        number_list = re.findall('-?\d*\.?\d+',line)            # get NAtoms value
                        natoms = int(number_list[0])
#                         print(natoms)                
                
                xyz_count = 0
                for line in mylines:
                    for phrase in xyz_match:                                # iterate through each phrases
                        if phrase in line:                                          # check if phrase is in line
                            xyz_count = xyz_count + 1
                
                line_count = 0
                for line in mylines:
                    line_count = line_count + 1
                    for phrase in xyz_match:                                # iterate through each phrases
                        if phrase in line:                                          # check if phrase is in line
                            xyz_count = xyz_count - 1
                            if xyz_count > 0:
                                continue
                            elif xyz_count == 0:
                                
                                                                               # For loop for generating the XYZ coordinates
                                count = 0
                                xyz = []
                                while count < natoms:
                                    count = count + 1
                                    xyz.append(mylines[line_count + 1])
                                    line_count = line_count +1


                x_coord = []
                y_coord = []
                z_coord = []
                atom_symbol =[]
        
                # Generate XYZ file in .txt form, then find xyz coordinates for metal, atom_a and atom_b
                for line in xyz:
                    number_list = re.findall('-?\d*\.?\d+',line)
                    # print(number_list)
                    # print(number_list[0])
                    atom_number = int(number_list[0])
                    element_number = int(number_list[1])
                    atom_x = float(number_list[3])
                    atom_x = f"{atom_x:.6f}"
                    atom_y = float(number_list[4])
                    atom_y = f"{atom_y:.6f}"
                    atom_z = float(number_list[5])
                    atom_z = f"{atom_z:.6f}"
                
                    # # Make xyz coord into .txt file 
                    # x_coord.append(atom_x)
                    # y_coord.append(atom_y)
                    # z_coord.append(atom_z)
                    # atom_symbol.append(element[int(element_number)])
                    # unique_atoms = list(set(atom_symbol))
                    # name_xyz = name + '-complex_xyz.txt'          

#                     # Make xyz coord into .txt file 
                    x_coord.append(atom_x)
                    y_coord.append(atom_y)
                    z_coord.append(atom_z)
                    atom_symbol.append(element_dict[str(element_number)])
                    unique_atoms = list(set(atom_symbol))
                    name_xyz = name + '-complex_xyz.txt'  
                    name_spe_xyz = name + '-complex_spe_xyz.txt'
                    
                # data = {
                #     'Atom': atom_symbol,
                #     'X': x_coord,
                #     'Y': y_coord,
                #     'Z': z_coord
                # }
                
                # xyz_df = pd.DataFrame(data)
                # xyz_df.to_csv(name_xyz, header=False, index=False, sep = " ")          # Generates .txt file 


                spe_data = {
                    'Name': name,
                    'Charge': charge,
                    'Multiplicity': multiplicity,
                    'Atom': atom_symbol,
                    'X': x_coord,
                    'Y': y_coord,
                    'Z': z_coord
                }
                xyz_spe_df = pd.DataFrame(spe_data).drop_duplicates()
                xyz_spe_df.to_csv(name_spe_xyz, header=False, index=False, sep = " ")          # Generates .txt file
                print(xyz_spe_df)

                os.makedirs(spe_complex_directory, exist_ok=True)


                # Extract unique elements from 'Atom' column, excluding 'Pd'
                elements = xyz_spe_df[xyz_spe_df['Atom'] != 'Pd']['Atom'].unique()
                
                # Convert the list of elements to a string formatted for output
                elements_string = " ".join(sorted(elements)) + " 0"
                                
                # Format the file content
                output_lines = []
                output_lines.append(f"%mem=16000MB\n")
                output_lines.append(f"%nprocshared=16\n")
                output_lines.append(f"%chk={name}-spe.chk\n")
                output_lines.append(f"#p m06/genecp pop=nbo\n\n")
                output_lines.append(f"{name}\n\n")
                output_lines.append(f"{charge} {multiplicity}\n")
                #Add the atom coordinates
                for index, row in xyz_spe_df.iterrows():
                    output_lines.append(f"{row['Atom']} {row['X']} {row['Y']} {row['Z']}\n")
                   
                # Add the additional lines with the dynamic elements_string
                output_lines.append("\n")
                output_lines.append(f"{elements_string}\n")
                output_lines.append("def2tzvp\n")
                output_lines.append("****\n")
                output_lines.append("Pd 0\n")
                output_lines.append("LANL2DZ\n")
                output_lines.append("****\n\n")
                output_lines.append("Pd 0\n")
                output_lines.append("LANL2DZ\n")
                output_lines.append("\n\n")
                # Specify the output path and save the file
                filename = f"{name}-spe.com"  # Replace with the desired filename or use 'name' variable
                output_path = os.path.join(spe_complex_directory, filename)
                
                # Save the output as a .txt file
                with open(output_path, 'w') as file:
                    file.writelines(output_lines)
                
                print(f"File saved to {output_path}")

ligand-001-n-n-1
Charge:  0
Multiplicity:  1
Charge:  0
Multiplicity:  1
                Name  Charge  Multiplicity Atom          X          Y  \
0   ligand-001-n-n-1       0             1    C   0.678885  -2.114263
1   ligand-001-n-n-1       0             1   Pd  -0.001914   0.826905
2   ligand-001-n-n-1       0             1    C  -1.379532   2.334521
3   ligand-001-n-n-1       0             1    H  -1.549512   2.670152
4   ligand-001-n-n-1       0             1    H  -2.335276   1.947701
5   ligand-001-n-n-1       0             1    H  -1.064722   3.207270
6   ligand-001-n-n-1       0             1    C   1.365704   2.343597
7   ligand-001-n-n-1       0             1    H   2.331368   1.957365
8   ligand-001-n-n-1       0             1    H   1.515839   2.700399
9   ligand-001-n-n-1       0             1    H   1.053042   3.202010
10  ligand-001-n-n-1       0             1    H   1.220897  -3.059859
11  ligand-001-n-n-1       0             1    H   0.533801  -2.114746
12  ligand-001-n-n-1       0             1    C   2.542354  -0.749599
13  ligand-001-n-n-1       0             1    H   3.227622  -1.628790
14  ligand-001-n-n-1       0             1    C   2.083226  -1.068457
15  ligand-001-n-n-1       0             1    H   2.782786  -1.936677
16  ligand-001-n-n-1       0             1    C  -2.539510  -0.759140
17  ligand-001-n-n-1       0             1    C  -2.075663  -1.082502
18  ligand-001-n-n-1       0             1    C  -0.668134  -2.116302
19  ligand-001-n-n-1       0             1    H  -1.205458  -3.065475
20  ligand-001-n-n-1       0             1    H  -0.523106  -2.111819
21  ligand-001-n-n-1       0             1    N   1.496369  -0.949341
22  ligand-001-n-n-1       0             1    N  -1.491218  -0.956693
23  ligand-001-n-n-1       0             1    H   1.299288  -1.190947
24  ligand-001-n-n-1       0             1    H   2.638765  -0.146275
25  ligand-001-n-n-1       0             1    H   3.134519   0.145266
26  ligand-001-n-n-1       0             1    H   2.090776  -0.581484
27  ligand-001-n-n-1       0             1    H  -3.135226   0.132458
28  ligand-001-n-n-1       0             1    H  -3.220878  -1.641270
29  ligand-001-n-n-1       0             1    H  -2.090069  -0.586433
30  ligand-001-n-n-1       0             1    H  -2.635819  -0.163954
31  ligand-001-n-n-1       0             1    H  -1.290113  -1.202805
32  ligand-001-n-n-1       0             1    H  -2.770511  -1.954589

            Z
0   -0.344581
1   -0.000642
2   -0.012891
3    1.031050
4   -0.428618
5   -0.615895
6    0.013341
7    0.406030
8   -1.026479
9    0.637799
10  -0.102202
11  -1.441258
12  -0.995468
13  -1.048846
14   1.322658
15   1.380138
16   0.993697
17  -1.322852
18   0.349288
19   0.110387
20   1.445973
21  -0.003770
22   0.003991
23   2.089639
24   1.565447
25  -0.737746
26  -1.989435
27   0.732821
28   1.048416
29   1.987853
30  -1.568777
31  -2.088528
32  -1.378951
File saved to C:\Users\George\Desktop\Research_UCLA\CIC\Computational Work\Project cluster version 2\project_catalyst_repurposing\structures_ligand_id\combined-spe-ligand-id\ligand-001-n-n-1-spe.com
ligand-002-p-p-1
Charge:  0
Multiplicity:  1
Charge:  0
Multiplicity:  1
                Name  Charge  Multiplicity Atom          X          Y  \
0   ligand-002-p-p-1       0             1    C   0.912710  -0.573164
1   ligand-002-p-p-1       0             1   Pd   0.121702  -1.104896
2   ligand-002-p-p-1       0             1    C  -1.320096  -2.022547
3   ligand-002-p-p-1       0             1    H  -1.100501  -1.867350
4   ligand-002-p-p-1       0             1    H  -2.342358  -1.656365
..               ...     ...           ...  ...        ...        ...
56  ligand-002-p-p-1       0             1    H  -4.408687   0.160644
57  ligand-002-p-p-1       0             1    C  -4.898674  -3.095527
58  ligand-002-p-p-1       0             1    H  -3.353102  -4.606812
59  ligand-002-p-p-1       0             1    H  -6.221096  -1.400919
60  ligand-002-p-p-1       0             1    H  -5.702316  -3.782857

            Z
0    1.865196
1   -1.326272
2   -2.535691
3   -3.608668
4   -2.310120
..        ...
56   0.674764
57   1.558430
58   1.674411
59   1.331791
60   1.847158

[61 rows x 7 columns]
File saved to C:\Users\George\Desktop\Research_UCLA\CIC\Computational Work\Project cluster version 2\project_catalyst_repurposing\structures_ligand_id\combined-spe-ligand-id\ligand-002-p-p-1-spe.com
ligand-003-p-p-2
Charge:  0
Multiplicity:  1
Charge:  0
Multiplicity:  1
                Name  Charge  Multiplicity Atom          X          Y  \
0   ligand-003-p-p-2       0             1    P  -1.705820   0.264426
1   ligand-003-p-p-2       0             1    C   1.267020   0.275635
2   ligand-003-p-p-2       0             1   Pd  -0.043193   1.195346
3   ligand-003-p-p-2       0             1    C  -1.506884   1.888600
4   ligand-003-p-p-2       0             1    H  -1.091722   2.256476
..               ...     ...           ...  ...        ...        ...
59  ligand-003-p-p-2       0             1    H  -0.939302  -1.405266
60  ligand-003-p-p-2       0             1    C  -2.036318  -4.297811
61  ligand-003-p-p-2       0             1    H  -3.001062  -4.434754
62  ligand-003-p-p-2       0             1    H  -1.065552  -3.859328
63  ligand-003-p-p-2       0             1    H  -2.081278  -5.377762

            Z
0   -0.437921
1   -2.256145
2    1.009660
3    2.338243
4    3.293386
..        ...
59   1.757724
60   0.314084
61  -1.618598
62   2.196849
63   0.497649

[64 rows x 7 columns]
File saved to C:\Users\George\Desktop\Research_UCLA\CIC\Computational Work\Project cluster version 2\project_catalyst_repurposing\structures_ligand_id\combined-spe-ligand-id\ligand-003-p-p-2-spe.com
ligand-004-p-p-3
Charge:  0
Multiplicity:  1
Charge:  0
Multiplicity:  1
                Name  Charge  Multiplicity Atom          X          Y  \
0   ligand-004-p-p-3       0             1    P   1.793732   0.226827
1   ligand-004-p-p-3       0             1    C  -0.444306   0.939033
2   ligand-004-p-p-3       0             1   Pd  -0.013978   1.282763
3   ligand-004-p-p-3       0             1    C   1.336965   2.005196
4   ligand-004-p-p-3       0             1    H   1.112172   1.527055
..               ...     ...           ...  ...        ...        ...
62  ligand-004-p-p-3       0             1    H  -4.250449  -1.087604
63  ligand-004-p-p-3       0             1    C  -6.113393   1.763520
64  ligand-004-p-p-3       0             1    H  -5.418339   3.730328
65  ligand-004-p-p-3       0             1    H  -6.513017  -0.295955
66  ligand-004-p-p-3       0             1    H  -7.116454   2.110525

            Z
0    0.476328
1    2.997387
2   -0.778741
3   -2.218134
4   -3.191384
..        ...
62  -0.451497
63  -0.546837
64   0.032091
65  -1.065377
66  -0.820811

[67 rows x 7 columns]
File saved to C:\Users\George\Desktop\Research_UCLA\CIC\Computational Work\Project cluster version 2\project_catalyst_repurposing\structures_ligand_id\combined-spe-ligand-id\ligand-004-p-p-3-spe.com
ligand-005-c-n-1
Charge:  0
Multiplicity:  1
Charge:  0
Multiplicity:  1
                Name  Charge  Multiplicity Atom          X          Y  \
0   ligand-005-c-n-1       0             1   Pd  -0.595467  -1.559498
1   ligand-005-c-n-1       0             1    C  -0.067313   0.516721
2   ligand-005-c-n-1       0             1    C   1.097890   2.419103
3   ligand-005-c-n-1       0             1    C  -0.220451   2.727250
4   ligand-005-c-n-1       0             1    H   1.993374   3.021203
..               ...     ...           ...  ...        ...        ...
56  ligand-005-c-n-1       0             1    H  -6.114395  -0.205713
57  ligand-005-c-n-1       0             1    H  -5.503888  -2.532496
58  ligand-005-c-n-1       0             1    N  -2.772904  -0.860542
59  ligand-005-c-n-1       0             1    H  -4.057084   2.673311
60  ligand-005-c-n-1       0             1    N   1.158683   1.104941

            Z
0    0.038877
1    0.001935
2    0.532669
3    0.680852
4    0.683328
..        ...
56  -1.647071
57  -0.850031
58   0.230531
59   0.807432
60   0.131870

[61 rows x 7 columns]
File saved to C:\Users\George\Desktop\Research_UCLA\CIC\Computational Work\Project cluster version 2\project_catalyst_repurposing\structures_ligand_id\combined-spe-ligand-id\ligand-005-c-n-1-spe.com
ligand-006-c-n-2
Charge:  0
Multiplicity:  1
Charge:  0
Multiplicity:  1
                Name  Charge  Multiplicity Atom          X          Y  \
0   ligand-006-c-n-2       0             1   Pd   1.045300  -1.642293
1   ligand-006-c-n-2       0             1    C   1.046587   0.173372
2   ligand-006-c-n-2       0             1    C   1.735311   2.293838
3   ligand-006-c-n-2       0             1    C   0.412793   2.390903
4   ligand-006-c-n-2       0             1    H   2.458802   3.051265
..               ...     ...           ...  ...        ...        ...
74  ligand-006-c-n-2       0             1    C  -6.162896  -1.232263
75  ligand-006-c-n-2       0             1    H  -6.230895  -1.350098
76  ligand-006-c-n-2       0             1    H  -5.875593  -0.184931
77  ligand-006-c-n-2       0             1    H  -7.173796  -1.390886
78  ligand-006-c-n-2       0             1    N   2.078172   0.963636

            Z
0    0.984544
1   -0.157530
2   -0.700827
3   -0.378572
4   -1.002271
..        ...
74  -0.124801
75   0.973905
76  -0.336136
77  -0.548092
78  -0.564421

[79 rows x 7 columns]
File saved to C:\Users\George\Desktop\Research_UCLA\CIC\Computational Work\Project cluster version 2\project_catalyst_repurposing\structures_ligand_id\combined-spe-ligand-id\ligand-006-c-n-2-spe.com
ligand-007-c-n-3
Charge:  0
Multiplicity:  1
Charge:  0
Multiplicity:  1
                Name  Charge  Multiplicity Atom          X          Y  \
0   ligand-007-c-n-3       0             1   Pd  -0.779671  -1.839397
1   ligand-007-c-n-3       0             1    C  -0.855198   0.120050
2   ligand-007-c-n-3       0             1    C  -1.649830   2.255809
3   ligand-007-c-n-3       0             1    C  -0.309106   2.372158
4   ligand-007-c-n-3       0             1    H  -2.419357   3.008678
..               ...     ...           ...  ...        ...        ...
80  ligand-007-c-n-3       0             1    C  -3.641918   0.738987
81  ligand-007-c-n-3       0             1    H  -2.929179   0.940916
82  ligand-007-c-n-3       0             1    H  -4.203112   1.670517
83  ligand-007-c-n-3       0             1    H  -4.360570  -0.013196
84  ligand-007-c-n-3       0             1    N  -1.938410   0.906833

            Z
0   -0.738127
1    0.121325
2    0.397847
3    0.170348
4    0.568591
..        ...
80   4.236003
81   5.057614
82   4.032355
83   4.615050
84   0.367673

[85 rows x 7 columns]
File saved to C:\Users\George\Desktop\Research_UCLA\CIC\Computational Work\Project cluster version 2\project_catalyst_repurposing\structures_ligand_id\combined-spe-ligand-id\ligand-007-c-n-3-spe.com
ligand-008-c-n-4
Charge:  0
Multiplicity:  1
Charge:  0
Multiplicity:  1
                Name  Charge  Multiplicity Atom         X          Y  \
0   ligand-008-c-n-4       0             1   Pd  0.824893  -1.728000
1   ligand-008-c-n-4       0             1    C  0.865196   0.108848
2   ligand-008-c-n-4       0             1    C  1.625045   2.215577
3   ligand-008-c-n-4       0             1    C  0.295259   2.343988
4   ligand-008-c-n-4       0             1    H  2.378859   2.955679
..               ...     ...           ...  ...       ...        ...
80  ligand-008-c-n-4       0             1    H  2.163316  -1.053531
81  ligand-008-c-n-4       0             1    H  1.054205  -1.421094
82  ligand-008-c-n-4       0             1    H  1.354446   0.271977
83  ligand-008-c-n-4       0             1    H  1.766841  -0.916679
84  ligand-008-c-n-4       0             1    N  1.929645   0.875867

            Z
0    0.974962
1   -0.118676
2   -0.619766
3   -0.342737
4   -0.888686
..        ...
80  -6.385606
81  -5.035988
82  -5.505184
83  -2.646869
84  -0.481579

[85 rows x 7 columns]
File saved to C:\Users\George\Desktop\Research_UCLA\CIC\Computational Work\Project cluster version 2\project_catalyst_repurposing\structures_ligand_id\combined-spe-ligand-id\ligand-008-c-n-4-spe.com
ligand-009-c-n-5
Charge:  0
Multiplicity:  1
Charge:  0
Multiplicity:  1
                Name  Charge  Multiplicity Atom         X          Y  \
0   ligand-009-c-n-5       0             1   Pd  0.761648  -1.891948
1   ligand-009-c-n-5       0             1    C  0.899524   0.166137
2   ligand-009-c-n-5       0             1    C  1.689529   2.319358
3   ligand-009-c-n-5       0             1    C  0.327733   2.407902
4   ligand-009-c-n-5       0             1    H  2.461653   3.088203
..               ...     ...           ...  ...       ...        ...
71  ligand-009-c-n-5       0             1    C  3.051913   0.095209
72  ligand-009-c-n-5       0             1    H  2.395420   0.979262
73  ligand-009-c-n-5       0             1    H  3.678932   0.013319
74  ligand-009-c-n-5       0             1    H  2.382339  -0.791325
75  ligand-009-c-n-5       0             1    N  1.996209   0.971889

            Z
0   -0.682622
1   -0.203912
2   -0.268540
3   -0.275728
4   -0.288741
..        ...
71  -2.745754
72  -2.854222
73  -3.650727
74  -2.696707
75  -0.226582

[76 rows x 7 columns]
File saved to C:\Users\George\Desktop\Research_UCLA\CIC\Computational Work\Project cluster version 2\project_catalyst_repurposing\structures_ligand_id\combined-spe-ligand-id\ligand-009-c-n-5-spe.com
ligand-010-c-n-6
Charge:  0
Multiplicity:  1
Charge:  0
Multiplicity:  1
                 Name  Charge  Multiplicity Atom          X          Y  \
0    ligand-010-c-n-6       0             1   Pd   0.239615   0.420024
1    ligand-010-c-n-6       0             1    C   0.108395   0.163140
2    ligand-010-c-n-6       0             1    C  -0.720441   0.305340
3    ligand-010-c-n-6       0             1    C   0.566553   0.748710
4    ligand-010-c-n-6       0             1    H  -1.497570   0.270968
..                ...     ...           ...  ...        ...        ...
111  ligand-010-c-n-6       0             1    C  -6.024304  -2.037840
112  ligand-010-c-n-6       0             1    H  -6.841038  -1.307356
113  ligand-010-c-n-6       0             1    H  -5.980075  -2.259776
114  ligand-010-c-n-6       0             1    H  -6.303154  -2.975003
115  ligand-010-c-n-6       0             1    N  -0.965883  -0.025275

             Z
0    -2.189503
1    -0.052504
2     2.084601
3     2.139826
4     2.847888
..         ...
111  -0.954938
112  -0.810992
113  -2.039331
114  -0.440800
115   0.766624

[116 rows x 7 columns]
File saved to C:\Users\George\Desktop\Research_UCLA\CIC\Computational Work\Project cluster version 2\project_catalyst_repurposing\structures_ligand_id\combined-spe-ligand-id\ligand-010-c-n-6-spe.com
ligand-011-c-n-7
Charge:  0
Multiplicity:  1
Charge:  0
Multiplicity:  1
                Name  Charge  Multiplicity Atom          X          Y  \
0   ligand-011-c-n-7       0             1   Pd   0.563572  -1.093536
1   ligand-011-c-n-7       0             1    C   0.445111   1.034705
2   ligand-011-c-n-7       0             1    C   1.506863   3.067203
3   ligand-011-c-n-7       0             1    N   1.589210   1.721456
4   ligand-011-c-n-7       0             1    C   2.806136   1.035441
5   ligand-011-c-n-7       0             1    C  -1.002318  -1.393818
6   ligand-011-c-n-7       0             1    H  -1.573455  -0.456886
7   ligand-011-c-n-7       0             1    H  -0.587409  -1.717150
8   ligand-011-c-n-7       0             1    H  -1.677973  -2.183389
9   ligand-011-c-n-7       0             1    C   0.782829  -3.150323
10  ligand-011-c-n-7       0             1    H   0.572837  -3.540491
11  ligand-011-c-n-7       0             1    H   1.813744  -3.455715
12  ligand-011-c-n-7       0             1    H   0.063030  -3.622868
13  ligand-011-c-n-7       0             1    C   3.329800   0.145718
14  ligand-011-c-n-7       0             1    C   4.586947   0.341656
15  ligand-011-c-n-7       0             1    C   2.924937  -1.664303
16  ligand-011-c-n-7       0             1    C   5.012009  -0.514895
17  ligand-011-c-n-7       0             1    H   5.226281   1.159362
18  ligand-011-c-n-7       0             1    C   4.163630  -1.536201
19  ligand-011-c-n-7       0             1    H   2.221725  -2.460636
20  ligand-011-c-n-7       0             1    H   4.453064  -2.231364
21  ligand-011-c-n-7       0             1    N   2.522102  -0.847432
22  ligand-011-c-n-7       0             1    H   2.327393   3.764517
23  ligand-011-c-n-7       0             1    H   2.570987   0.413513
24  ligand-011-c-n-7       0             1    H   3.557377   1.794409
25  ligand-011-c-n-7       0             1    H   5.996954  -0.382390
26  ligand-011-c-n-7       0             1    C   0.238260   3.275411
27  ligand-011-c-n-7       0             1    C  -0.488482   4.417224
28  ligand-011-c-n-7       0             1    C  -1.764475   4.251981
29  ligand-011-c-n-7       0             1    H  -0.002140   5.397628
30  ligand-011-c-n-7       0             1    C  -1.674329   1.835486
31  ligand-011-c-n-7       0             1    C  -2.343917   2.944186
32  ligand-011-c-n-7       0             1    H  -2.347470   5.112686
33  ligand-011-c-n-7       0             1    H  -3.345805   2.801369
34  ligand-011-c-n-7       0             1    N  -0.389396   2.005835
35  ligand-011-c-n-7       0             1    C  -2.234901   0.471912
36  ligand-011-c-n-7       0             1    C  -1.762573  -0.371535
37  ligand-011-c-n-7       0             1    C  -3.278994   0.058011
38  ligand-011-c-n-7       0             1    C  -2.331182  -1.636273
39  ligand-011-c-n-7       0             1    C  -3.820466  -1.215932
40  ligand-011-c-n-7       0             1    C  -3.350409  -2.084289
41  ligand-011-c-n-7       0             1    H  -1.959972  -2.300344
42  ligand-011-c-n-7       0             1    H  -4.621571  -1.551417
43  ligand-011-c-n-7       0             1    C  -0.670361   0.068507
44  ligand-011-c-n-7       0             1    H  -0.841441   1.091660
45  ligand-011-c-n-7       0             1    H  -0.587062  -0.611840
46  ligand-011-c-n-7       0             1    H   0.311125   0.074308
47  ligand-011-c-n-7       0             1    C  -3.798513   0.944142
48  ligand-011-c-n-7       0             1    H  -4.478518   1.729447
49  ligand-011-c-n-7       0             1    H  -2.979832   1.463613
50  ligand-011-c-n-7       0             1    H  -4.362138   0.355730
51  ligand-011-c-n-7       0             1    C  -3.886081  -3.478319
52  ligand-011-c-n-7       0             1    H  -3.280242  -4.182118
53  ligand-011-c-n-7       0             1    H  -3.856808  -3.841478
54  ligand-011-c-n-7       0             1    H  -4.927521  -3.550707

            Z
0   -0.884988
1   -0.625795
2   -0.577135
3   -0.875917
4   -1.277663
5   -2.187066
6   -2.328783
7   -3.161649
8   -1.804225
9   -1.070556
10  -2.084800
11  -0.787417
12  -0.366483
13  -0.178039
14   0.390438
15   1.194252
16   1.403944
17   0.037847
18   1.818715
19   1.473884
20   2.613410
21   0.221544
22  -0.745386
23  -2.162573
24  -1.556798
25   1.865785
26  -0.107604
27   0.331278
28   0.774644
29   0.306044
30   0.401713
31   0.826459
32   1.119690
33   1.245311
34  -0.123407
35   0.540487
36   1.564832
37  -0.302519
38   1.704543
39  -0.122830
40   0.861486
41   2.497937
42  -0.796320
43   2.493216
44   2.880323
45   3.359447
46   1.977577
47  -1.397262
48  -1.011738
49  -1.929895
50  -2.143087
51   0.980320
52   0.374901
53   2.023955
54   0.617802
File saved to C:\Users\George\Desktop\Research_UCLA\CIC\Computational Work\Project cluster version 2\project_catalyst_repurposing\structures_ligand_id\combined-spe-ligand-id\ligand-011-c-n-7-spe.com
ligand-013-p-p-5
Charge:  0
Multiplicity:  1
Charge:  0
Multiplicity:  1

In [9]:
xyz_spe_df

,Name,Charge,Multiplicity,Atom,X,Y,Z
0,ligand-532-p-o-183,0,1,P,-0.729091,0.060920,-1.133668
1,ligand-532-p-o-183,0,1,O,-1.393510,2.921349,-0.423345
2,ligand-532-p-o-183,0,1,P,-0.350841,2.443689,0.559089
3,ligand-532-p-o-183,0,1,N,-0.122904,0.758147,0.364903
4,ligand-532-p-o-183,0,1,C,-0.887958,2.690993,2.268850
...,...,...,...,...,...,...,...
77,ligand-532-p-o-183,0,1,N,3.332827,-2.335491,3.587570
78,ligand-532-p-o-183,0,1,C,4.736450,-2.386720,3.262441
79,ligand-532-p-o-183,0,1,H,5.238188,-3.118016,3.915658
80,ligand-532-p-o-183,0,1,H,4.909615,-2.696278,2.210550
81,ligand-532-p-o-183,0,1,H,5.237111,-1.408283,3.412870

In [10]:
atom_label_df

,Filename,Pd_atom label,Methyl_atom_1 label,Methyl_atom_2 label,Hydrogens_methyl_1_label,Hydrogens_methyl_2_label,Ligand_atom_1 label,Ligand_atom_2 label,Atoms_distance_2 label,Atoms_distance_3 label,Atoms_distance_4 label,Atoms_distance_2_a label,Atoms_distance_3_a label,Atoms_distance_4_a label,Atoms_distance_2_b label,Atoms_distance_3_b label,Atoms_distance_4_b label,Atom label shortest paths
0,ligand-001-n-n-1,2,3,7,"[6, 4, 5]","[10, 9, 8]",23,22,"[1, 13, 15, 17, 18, 19]","[11, 12, 14, 16, 20, 21, 24, 25, 26, 27, 28, 2...",[],"[17, 18, 19]","[32, 33, 1, 20, 21, 28, 29, 30, 31]","[11, 12]","[1, 13, 15]","[11, 12, 14, 16, 19, 24, 25, 26, 27]","[20, 21]","[2, 23, 19, 1, 22]"
1,ligand-002-p-p-1,2,7,3,"[9, 8, 10]","[4, 6, 5]",16,17,"[1, 40, 13, 18, 51, 29]","[41, 42, 11, 12, 14, 15, 19, 20, 52, 53, 30, 31]","[21, 22, 23, 24, 32, 33, 34, 35, 43, 44, 45, 4...","[1, 18, 29]","[11, 12, 13, 19, 20, 30, 31]","[32, 33, 34, 35, 14, 15, 21, 22, 23, 24]","[13, 40, 51]","[1, 41, 42, 14, 15, 52, 53]","[11, 12, 43, 44, 45, 46, 54, 55, 56, 57]","[2, 16, 1, 13, 17]"
2,ligand-003-p-p-2,3,4,8,"[5, 7, 6]","[10, 11, 9]",1,12,"[32, 2, 43, 17, 21, 54]","[33, 34, 13, 14, 15, 44, 45, 18, 19, 55, 22, 2...","[16, 20, 24, 25, 26, 27, 35, 36, 37, 38, 46, 4...","[17, 43, 54]","[44, 45, 15, 18, 19, 55, 56]","[2, 46, 47, 48, 49, 16, 20, 57, 58, 59, 60]","[2, 21, 32]","[33, 34, 13, 14, 15, 22, 23]","[35, 36, 37, 38, 16, 17, 20, 24, 25, 26, 27]","[3, 1, 17, 15, 2, 12]"
3,ligand-004-p-p-3,3,8,4,"[11, 10, 9]","[6, 5, 7]",45,1,"[42, 46, 16, 20, 57, 31]","[32, 2, 33, 43, 44, 14, 47, 48, 17, 18, 21, 22...","[12, 13, 15, 19, 23, 24, 25, 26, 34, 35, 36, 3...","[42, 46, 57]","[2, 43, 44, 47, 48, 58, 59]","[12, 13, 14, 49, 50, 51, 52, 60, 61, 62, 63]","[16, 20, 31]","[32, 33, 14, 17, 18, 21, 22]","[34, 35, 36, 37, 2, 15, 19, 23, 24, 25, 26]","[3, 45, 42, 2, 14, 16, 1]"
4,ligand-005-c-n-1,1,42,46,"[43, 44, 45]","[49, 48, 47]",2,59,"[50, 52, 61, 6]","[3, 4, 7, 51, 55, 56, 25]","[5, 8, 9, 20, 53, 54, 24, 58]","[6, 61]","[3, 4, 7, 25]","[5, 8, 9, 50, 20, 24]","[50, 52]","[51, 55, 56, 25]","[6, 53, 54, 24, 58]","[1, 2, 6, 25, 50, 59]"
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
485,ligand-528-p-o-179,53,56,60,"[57, 59, 58]","[61, 63, 62]",1,2,"[40, 50, 3, 4]","[5, 39, 41, 45, 49, 21, 27]","[38, 6, 70, 10, 42, 46, 79, 48, 16, 20, 54, 55...","[4, 40, 50]","[3, 39, 41, 45, 49, 27]","[5, 38, 70, 42, 46, 79, 48, 21, 54, 55, 28, 29]",[3],"[21, 4, 5]","[6, 10, 16, 20, 27]","[53, 1, 4, 3, 2]"
486,ligand-529-p-o-180,53,56,60,"[59, 57, 58]","[63, 61, 62]",1,2,"[40, 50, 3, 4]","[5, 39, 41, 45, 49, 21, 27]","[64, 69, 38, 6, 10, 42, 46, 48, 16, 20, 54, 55...","[4, 40, 50]","[3, 39, 41, 45, 49, 27]","[64, 5, 38, 69, 42, 46, 48, 21, 54, 55, 28, 29]",[3],"[21, 4, 5]","[6, 10, 16, 20, 27]","[53, 1, 4, 3, 2]"
487,ligand-530-p-o-181,53,60,56,"[63, 61, 62]","[59, 57, 58]",1,2,"[40, 50, 3, 4]","[5, 39, 41, 45, 49, 21, 27]","[38, 6, 10, 75, 42, 76, 46, 48, 16, 20, 54, 55...","[4, 40, 50]","[3, 39, 41, 45, 49, 27]","[5, 38, 42, 75, 76, 46, 48, 21, 54, 55, 28, 29]",[3],"[21, 4, 5]","[6, 10, 16, 20, 27]","[53, 1, 4, 3, 2]"
488,ligand-531-p-o-182,53,56,60,"[59, 57, 58]","[63, 61, 62]",1,2,"[40, 50, 3, 4]","[5, 39, 41, 45, 49, 21, 27]","[64, 69, 38, 6, 10, 42, 46, 48, 16, 20, 54, 55...","[4, 40, 50]","[3, 39, 41, 45, 49, 27]","[64, 5, 38, 69, 42, 46, 48, 21, 54, 55, 28, 29]",[3],"[21, 4, 5]","[6, 10, 16, 20, 27]","[53, 1, 4, 3, 2]"
489,ligand-532-p-o-183,53,56,60,"[59, 57, 58]","[63, 61, 62]",1,2,"[40, 50, 3, 4]","[5, 39, 41, 45, 49, 21, 27]","[64, 38, 6, 70, 10, 42, 46, 48, 16, 20, 54, 55...","[4, 40, 50]","[3, 39, 41, 45, 49, 27]","[64, 5, 38, 70, 42, 46, 48, 21, 54, 55, 28, 29]",[3],"[21, 4, 5]","[6, 10, 16, 20, 27]","[53, 1, 4, 3, 2]"